//HintName: TestApp.PersonEdit.DataPortalOperations.g.cs
//<auto-generated/>
#nullable enable
#pragma warning disable CS1998 // Async method lacks 'await' operators

namespace TestApp
{
  partial class PersonEdit : global::TestApp.PersonEdit.IDataPortalOperations, global::Csla.Server.IDataPortalOperationMapping, global::Csla.Server.IDataPortalOperationNamedMapping
  {
    /// <summary>
    /// Data portal operation methods declared by this type.
    /// Generated by CSLA .NET so the methods are statically referenced.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    internal interface IDataPortalOperations
    {
      void Fetch__Int32(int id, global::TestApp.IDal dal, global::TestApp.IDal? secondary);
      void Create(global::TestApp.IDal dal, global::TestApp.IDal other);
    }

    void IDataPortalOperations.Fetch__Int32(int id, global::TestApp.IDal dal, global::TestApp.IDal? secondary) => Fetch(id, dal, secondary);
    void IDataPortalOperations.Create(global::TestApp.IDal dal, global::TestApp.IDal other) => Create(dal, other);

    async global::System.Threading.Tasks.Task global::Csla.Server.IDataPortalOperationMapping.InvokeOperationAsync(
      global::System.Type operationType, bool isSync, object?[]? criteria, global::System.IServiceProvider serviceProvider)
    {
      var __operations = (IDataPortalOperations)this;
      if (operationType == typeof(global::Csla.CreateAttribute))
      {
        if (criteria is null or { Length: 0 })
        {
          try
          {
            var __c0i0 = (global::TestApp.IDal)(global::Csla.Server.DataPortalOperationHelper.GetKeyedService(serviceProvider, typeof(global::TestApp.IDal), (short)(-1), false))!;
            var __c0i1 = (global::TestApp.IDal)(global::Csla.Server.DataPortalOperationHelper.GetKeyedService(serviceProvider, typeof(global::TestApp.IDal), (byte)2, false))!;
            __operations.Create(__c0i0, __c0i1);
          }
          catch (global::System.Exception __ex)
          {
            throw global::Csla.Server.DataPortalOperationHelper.CreateCallMethodException(this, "Create", __ex);
          }
          return;
        }
      }
      else if (operationType == typeof(global::Csla.FetchAttribute))
      {
        if (criteria is { Length: 1 } && criteria[0] is int __c1p0)
        {
          try
          {
            var __c1i0 = (global::TestApp.IDal)(global::Csla.Server.DataPortalOperationHelper.GetKeyedService(serviceProvider, typeof(global::TestApp.IDal), "primary", false))!;
            var __c1i1 = (global::TestApp.IDal?)(global::Csla.Server.DataPortalOperationHelper.GetKeyedService(serviceProvider, typeof(global::TestApp.IDal), global::TestApp.DalKind.Secondary, true));
            __operations.Fetch__Int32(__c1p0, __c1i0, __c1i1);
          }
          catch (global::System.Exception __ex)
          {
            throw global::Csla.Server.DataPortalOperationHelper.CreateCallMethodException(this, "Fetch", __ex);
          }
          return;
        }
      }
      throw new global::Csla.Server.DataPortalOperationNotSupportedException(operationType, criteria);
    }

    async global::System.Threading.Tasks.Task global::Csla.Server.IDataPortalOperationNamedMapping.InvokeNamedOperationAsync(
      string operationName, bool isSync, object?[]? criteria, global::System.IServiceProvider serviceProvider)
    {
      var __operations = (IDataPortalOperations)this;
      switch (operationName)
      {
        case "Fetch__Int32":
          if (criteria is { Length: 1 } && criteria[0] is int __c0p0)
          {
            try
            {
              var __c0i0 = (global::TestApp.IDal)(global::Csla.Server.DataPortalOperationHelper.GetKeyedService(serviceProvider, typeof(global::TestApp.IDal), "primary", false))!;
              var __c0i1 = (global::TestApp.IDal?)(global::Csla.Server.DataPortalOperationHelper.GetKeyedService(serviceProvider, typeof(global::TestApp.IDal), global::TestApp.DalKind.Secondary, true));
              __operations.Fetch__Int32(__c0p0, __c0i0, __c0i1);
            }
            catch (global::System.Exception __ex)
            {
              throw global::Csla.Server.DataPortalOperationHelper.CreateCallMethodException(this, "Fetch", __ex);
            }
            return;
          }
          break;
        case "Create":
          if (criteria is null or { Length: 0 })
          {
            try
            {
              var __c1i0 = (global::TestApp.IDal)(global::Csla.Server.DataPortalOperationHelper.GetKeyedService(serviceProvider, typeof(global::TestApp.IDal), (short)(-1), false))!;
              var __c1i1 = (global::TestApp.IDal)(global::Csla.Server.DataPortalOperationHelper.GetKeyedService(serviceProvider, typeof(global::TestApp.IDal), (byte)2, false))!;
              __operations.Create(__c1i0, __c1i1);
            }
            catch (global::System.Exception __ex)
            {
              throw global::Csla.Server.DataPortalOperationHelper.CreateCallMethodException(this, "Create", __ex);
            }
            return;
          }
          break;
      }
      throw new global::Csla.Server.DataPortalOperationNotSupportedException(operationName, criteria);
    }
  }
}
