//HintName: TestApp.PersonEdit.DataPortalOperations.g.cs
//<auto-generated/>
#nullable enable
#pragma warning disable CS1998 // Async method lacks 'await' operators

namespace TestApp
{
  partial class PersonEdit : global::TestApp.PersonEdit.IDataPortalOperations, global::Csla.Server.IDataPortalOperationMapping, global::Csla.Server.IDataPortalOperationNamedMapping
  {
    /// <summary>
    /// Data portal operation methods declared by this type.
    /// Generated by CSLA .NET so the methods are statically referenced.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    internal interface IDataPortalOperations
    {
      void Fetch__String_Int32(in string? name, in int id);
      void Create(int? count, global::TestApp.IDal? dal);
    }

    void IDataPortalOperations.Fetch__String_Int32(in string? name, in int id) => Fetch(in name, in id);
    void IDataPortalOperations.Create(int? count, global::TestApp.IDal? dal) => Create(count, dal);

    async global::System.Threading.Tasks.Task global::Csla.Server.IDataPortalOperationMapping.InvokeOperationAsync(
      global::System.Type operationType, bool isSync, object?[]? criteria, global::System.IServiceProvider serviceProvider)
    {
      var __operations = (IDataPortalOperations)this;
      if (operationType == typeof(global::Csla.CreateAttribute))
      {
        if (criteria is null or { Length: 0 })
        {
          try
          {
            var __c0i0 = (int?)(global::Csla.Server.DataPortalOperationHelper.GetService(serviceProvider, typeof(int?), true));
            var __c0i1 = (global::TestApp.IDal?)(global::Csla.Server.DataPortalOperationHelper.GetService(serviceProvider, typeof(global::TestApp.IDal), true));
            __operations.Create(__c0i0, __c0i1);
          }
          catch (global::System.Exception __ex)
          {
            throw global::Csla.Server.DataPortalOperationHelper.CreateCallMethodException(this, "Create", __ex);
          }
          return;
        }
      }
      else if (operationType == typeof(global::Csla.FetchAttribute))
      {
        if (criteria is { Length: 2 } && criteria[0] is string __c1p0 && criteria[1] is int __c1p1)
        {
          try
          {
            __operations.Fetch__String_Int32(in __c1p0, in __c1p1);
          }
          catch (global::System.Exception __ex)
          {
            throw global::Csla.Server.DataPortalOperationHelper.CreateCallMethodException(this, "Fetch", __ex);
          }
          return;
        }
      }
      throw new global::Csla.Server.DataPortalOperationNotSupportedException(operationType, criteria);
    }

    async global::System.Threading.Tasks.Task global::Csla.Server.IDataPortalOperationNamedMapping.InvokeNamedOperationAsync(
      string operationName, bool isSync, object?[]? criteria, global::System.IServiceProvider serviceProvider)
    {
      var __operations = (IDataPortalOperations)this;
      switch (operationName)
      {
        case "Fetch__String_Int32":
          if (criteria is { Length: 2 } && (criteria[0] is null || criteria[0] is string) && criteria[1] is int __c0p1)
          {
            try
            {
              var __c0p0 = (string?)criteria[0]!;
              __operations.Fetch__String_Int32(in __c0p0, in __c0p1);
            }
            catch (global::System.Exception __ex)
            {
              throw global::Csla.Server.DataPortalOperationHelper.CreateCallMethodException(this, "Fetch", __ex);
            }
            return;
          }
          break;
        case "Create":
          if (criteria is null or { Length: 0 })
          {
            try
            {
              var __c1i0 = (int?)(global::Csla.Server.DataPortalOperationHelper.GetService(serviceProvider, typeof(int?), true));
              var __c1i1 = (global::TestApp.IDal?)(global::Csla.Server.DataPortalOperationHelper.GetService(serviceProvider, typeof(global::TestApp.IDal), true));
              __operations.Create(__c1i0, __c1i1);
            }
            catch (global::System.Exception __ex)
            {
              throw global::Csla.Server.DataPortalOperationHelper.CreateCallMethodException(this, "Create", __ex);
            }
            return;
          }
          break;
      }
      throw new global::Csla.Server.DataPortalOperationNotSupportedException(operationName, criteria);
    }
  }
}
