//HintName: TestApp.PersonEdit.DataPortalOperations.g.cs
//<auto-generated/>
#nullable enable
#pragma warning disable CS1998 // Async method lacks 'await' operators

namespace TestApp
{
  partial class PersonEdit : global::TestApp.PersonEdit.IDataPortalOperations, global::Csla.Server.IDataPortalOperationMapping, global::Csla.Server.IDataPortalOperationNamedMapping
  {
    /// <summary>
    /// Data portal operation methods declared by this type.
    /// Generated by CSLA .NET so the methods are statically referenced.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    internal interface IDataPortalOperations
    {
      void Fetch__Object(object value);
      void Fetch__Criteria(global::TestApp.Criteria criteria);
      void Fetch__Int32(int id);
    }

    void IDataPortalOperations.Fetch__Object(object value) => Fetch(value);
    void IDataPortalOperations.Fetch__Criteria(global::TestApp.Criteria criteria) => Fetch(criteria);
    void IDataPortalOperations.Fetch__Int32(int id) => Fetch(id);

    async global::System.Threading.Tasks.Task global::Csla.Server.IDataPortalOperationMapping.InvokeOperationAsync(
      global::System.Type operationType, bool isSync, object?[]? criteria, global::System.IServiceProvider serviceProvider)
    {
      var __operations = (IDataPortalOperations)this;
      if (operationType == typeof(global::Csla.FetchAttribute))
      {
        if (criteria is { Length: 1 } && criteria[0] is object __c0p0 && __c0p0.GetType() == typeof(object))
        {
          try
          {
            __operations.Fetch__Object(__c0p0);
          }
          catch (global::System.Exception __ex)
          {
            throw global::Csla.Server.DataPortalOperationHelper.CreateCallMethodException(this, "Fetch", __ex);
          }
          return;
        }
        if (criteria is { Length: 1 } && criteria[0] is global::TestApp.Criteria __c1p0 && __c1p0.GetType() == typeof(global::TestApp.Criteria))
        {
          try
          {
            __operations.Fetch__Criteria(__c1p0);
          }
          catch (global::System.Exception __ex)
          {
            throw global::Csla.Server.DataPortalOperationHelper.CreateCallMethodException(this, "Fetch", __ex);
          }
          return;
        }
        if (criteria is { Length: 1 } && criteria[0] is int __c2p0)
        {
          try
          {
            __operations.Fetch__Int32(__c2p0);
          }
          catch (global::System.Exception __ex)
          {
            throw global::Csla.Server.DataPortalOperationHelper.CreateCallMethodException(this, "Fetch", __ex);
          }
          return;
        }
      }
      throw new global::Csla.Server.DataPortalOperationNotSupportedException(operationType, criteria);
    }

    async global::System.Threading.Tasks.Task global::Csla.Server.IDataPortalOperationNamedMapping.InvokeNamedOperationAsync(
      string operationName, bool isSync, object?[]? criteria, global::System.IServiceProvider serviceProvider)
    {
      var __operations = (IDataPortalOperations)this;
      switch (operationName)
      {
        case "Fetch__Object":
          if (criteria is { Length: 1 } && (criteria[0] is null || criteria[0] is object))
          {
            try
            {
              __operations.Fetch__Object((object)criteria[0]!);
            }
            catch (global::System.Exception __ex)
            {
              throw global::Csla.Server.DataPortalOperationHelper.CreateCallMethodException(this, "Fetch", __ex);
            }
            return;
          }
          break;
        case "Fetch__Criteria":
          if (criteria is { Length: 1 } && (criteria[0] is null || criteria[0] is global::TestApp.Criteria))
          {
            try
            {
              __operations.Fetch__Criteria((global::TestApp.Criteria)criteria[0]!);
            }
            catch (global::System.Exception __ex)
            {
              throw global::Csla.Server.DataPortalOperationHelper.CreateCallMethodException(this, "Fetch", __ex);
            }
            return;
          }
          break;
        case "Fetch__Int32":
          if (criteria is { Length: 1 } && criteria[0] is int __c2p0)
          {
            try
            {
              __operations.Fetch__Int32(__c2p0);
            }
            catch (global::System.Exception __ex)
            {
              throw global::Csla.Server.DataPortalOperationHelper.CreateCallMethodException(this, "Fetch", __ex);
            }
            return;
          }
          break;
      }
      throw new global::Csla.Server.DataPortalOperationNotSupportedException(operationName, criteria);
    }
  }
}
