//HintName: TestApp.PersonEdit.DataPortalOperations.g.cs
//<auto-generated/>
#nullable enable
#pragma warning disable CS1998 // Async method lacks 'await' operators

namespace TestApp
{
  partial class PersonEdit : global::TestApp.PersonEdit.IDataPortalOperations, global::Csla.Server.IDataPortalOperationMapping, global::Csla.Server.IDataPortalOperationNamedMapping
  {
    /// <summary>
    /// Data portal operation methods declared by this type.
    /// Generated by CSLA .NET so the methods are statically referenced.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    internal interface IDataPortalOperations
    {
      void Create();
      void CreateChild();
    }

    void IDataPortalOperations.Create() => Create();
    void IDataPortalOperations.CreateChild() => Create();

    async global::System.Threading.Tasks.Task global::Csla.Server.IDataPortalOperationMapping.InvokeOperationAsync(
      global::System.Type operationType, bool isSync, object?[]? criteria, global::System.IServiceProvider serviceProvider)
    {
      var __operations = (IDataPortalOperations)this;
      if (operationType == typeof(global::Csla.CreateAttribute))
      {
        if (criteria is null or { Length: 0 })
        {
          try
          {
            __operations.Create();
          }
          catch (global::System.Exception __ex)
          {
            throw global::Csla.Server.DataPortalOperationHelper.CreateCallMethodException(this, "Create", __ex);
          }
          return;
        }
      }
      else if (operationType == typeof(global::Csla.CreateChildAttribute))
      {
        if (criteria is null or { Length: 0 })
        {
          try
          {
            __operations.CreateChild();
          }
          catch (global::System.Exception __ex)
          {
            throw global::Csla.Server.DataPortalOperationHelper.CreateCallMethodException(this, "Create", __ex);
          }
          return;
        }
      }
      throw new global::Csla.Server.DataPortalOperationNotSupportedException(operationType, criteria);
    }

    async global::System.Threading.Tasks.Task global::Csla.Server.IDataPortalOperationNamedMapping.InvokeNamedOperationAsync(
      string operationName, bool isSync, object?[]? criteria, global::System.IServiceProvider serviceProvider)
    {
      var __operations = (IDataPortalOperations)this;
      switch (operationName)
      {
        case "Create":
          if (criteria is null or { Length: 0 })
          {
            try
            {
              __operations.Create();
            }
            catch (global::System.Exception __ex)
            {
              throw global::Csla.Server.DataPortalOperationHelper.CreateCallMethodException(this, "Create", __ex);
            }
            return;
          }
          break;
        case "CreateChild":
          if (criteria is null or { Length: 0 })
          {
            try
            {
              __operations.CreateChild();
            }
            catch (global::System.Exception __ex)
            {
              throw global::Csla.Server.DataPortalOperationHelper.CreateCallMethodException(this, "Create", __ex);
            }
            return;
          }
          break;
      }
      throw new global::Csla.Server.DataPortalOperationNotSupportedException(operationName, criteria);
    }
  }
}
