//HintName: TestApp.PersonEdit.DataPortalOperations.g.cs
//<auto-generated/>
#nullable enable
#pragma warning disable CS1998 // Async method lacks 'await' operators

namespace TestApp
{
  partial class PersonEdit : global::TestApp.PersonEdit.IDataPortalOperations, global::Csla.Server.IDataPortalOperationMapping, global::Csla.Server.IDataPortalOperationNamedMapping
  {
    /// <summary>
    /// Data portal operation methods declared by this type.
    /// Generated by CSLA .NET so the methods are statically referenced.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    internal interface IDataPortalOperations
    {
      void Fetch__Int32_String(global::TestApp.IDal dal, int id, global::TestApp.IDal? backup, string name);
    }

    void IDataPortalOperations.Fetch__Int32_String(global::TestApp.IDal dal, int id, global::TestApp.IDal? backup, string name) => Fetch(dal, id, backup, name);

    async global::System.Threading.Tasks.Task global::Csla.Server.IDataPortalOperationMapping.InvokeOperationAsync(
      global::System.Type operationType, bool isSync, object?[]? criteria, global::System.IServiceProvider serviceProvider)
    {
      var __operations = (IDataPortalOperations)this;
      if (operationType == typeof(global::Csla.FetchAttribute))
      {
        if (criteria is { Length: 2 } && criteria[0] is int __c0p0 && criteria[1] is string __c0p1)
        {
          var __c0i0 = (global::TestApp.IDal)(global::Csla.Server.DataPortalOperationHelper.GetService(serviceProvider, typeof(global::TestApp.IDal), false))!;
          var __c0i1 = (global::TestApp.IDal?)(global::Csla.Server.DataPortalOperationHelper.GetService(serviceProvider, typeof(global::TestApp.IDal), true));
          try
          {
            __operations.Fetch__Int32_String(__c0i0, __c0p0, __c0i1, __c0p1);
          }
          catch (global::System.Exception __ex)
          {
            throw global::Csla.Server.DataPortalOperationHelper.CreateCallMethodException(this, "Fetch", __ex);
          }
          return;
        }
      }
      throw new global::Csla.Server.DataPortalOperationNotSupportedException(operationType, criteria);
    }

    async global::System.Threading.Tasks.Task global::Csla.Server.IDataPortalOperationNamedMapping.InvokeNamedOperationAsync(
      string operationName, bool isSync, object?[]? criteria, global::System.IServiceProvider serviceProvider)
    {
      var __operations = (IDataPortalOperations)this;
      switch (operationName)
      {
        case "Fetch__Int32_String":
          if (criteria is { Length: 2 } && criteria[0] is int __c0p0 && (criteria[1] is null || criteria[1] is string))
          {
            var __c0i0 = (global::TestApp.IDal)(global::Csla.Server.DataPortalOperationHelper.GetService(serviceProvider, typeof(global::TestApp.IDal), false))!;
            var __c0i1 = (global::TestApp.IDal?)(global::Csla.Server.DataPortalOperationHelper.GetService(serviceProvider, typeof(global::TestApp.IDal), true));
            try
            {
              __operations.Fetch__Int32_String(__c0i0, __c0p0, __c0i1, (string)criteria[1]!);
            }
            catch (global::System.Exception __ex)
            {
              throw global::Csla.Server.DataPortalOperationHelper.CreateCallMethodException(this, "Fetch", __ex);
            }
            return;
          }
          break;
      }
      throw new global::Csla.Server.DataPortalOperationNotSupportedException(operationName, criteria);
    }
  }
}
