//HintName: TestApp.PersonEdit.DataPortalOperations.g.cs
//<auto-generated/>
#nullable enable

namespace TestApp
{
  public partial class PersonEdit : Csla.Server.IDataPortalOperationMapping
  {
    async global::System.Threading.Tasks.Task Csla.Server.IDataPortalOperationMapping.InvokeOperationAsync(
      global::System.Type operationType, bool isSync, object?[]? criteria, global::System.IServiceProvider serviceProvider)
    {
      if (operationType == typeof(Csla.CreateAttribute))
      {
        if (criteria is null or { Length: 0 })
        {
          Create();
          return;
        }
      }
      throw new Csla.Server.DataPortalOperationNotSupportedException(operationType, criteria);
    }
  }
}
