//HintName: TestApp.PersonEdit.DataPortalOperations.g.cs
//<auto-generated/>
#nullable enable

namespace TestApp
{
  public partial class PersonEdit : Csla.Server.IDataPortalOperationMapping, Csla.Server.IDataPortalOperationNamedMapping
  {
    async global::System.Threading.Tasks.Task Csla.Server.IDataPortalOperationMapping.InvokeOperationAsync(
      global::System.Type operationType, bool isSync, object?[]? criteria, global::System.IServiceProvider serviceProvider)
    {
      if (operationType == typeof(Csla.FetchAttribute))
      {
        if (criteria is { Length: 1 } && criteria[0] is int p0_int)
        {
          var logger = (global::TestApp.ILogger?)serviceProvider.GetService(typeof(global::TestApp.ILogger));
          await Fetch(p0_int, logger).ConfigureAwait(false);
          return;
        }
      }
      throw new Csla.Server.DataPortalOperationNotSupportedException(operationType, criteria);
    }
    
    async global::System.Threading.Tasks.Task Csla.Server.IDataPortalOperationNamedMapping.InvokeNamedOperationAsync(
      string operationName, bool isSync, object?[]? criteria, global::System.IServiceProvider serviceProvider)
    {
      switch (operationName)
      {
        case "Fetch__Int32":
          if (criteria is { Length: 1 } && criteria[0] is int p0_int)
          {
            var logger = (global::TestApp.ILogger?)serviceProvider.GetService(typeof(global::TestApp.ILogger));
            await Fetch(p0_int, logger).ConfigureAwait(false);
            return;
          }
          break;
      }
      throw new Csla.Server.DataPortalOperationNotSupportedException(operationName, criteria);
    }
  }
}
