//HintName: TestApp.LineItem.DataPortalOperations.g.cs
//<auto-generated/>
#nullable enable

namespace TestApp
{
  public partial class LineItem : Csla.Server.IDataPortalOperationMapping
  {
    async global::System.Threading.Tasks.Task Csla.Server.IDataPortalOperationMapping.InvokeOperationAsync(
      global::System.Type operationType, bool isSync, object?[]? criteria, global::System.IServiceProvider serviceProvider)
    {
      if (operationType == typeof(Csla.CreateChildAttribute))
      {
        if (criteria is null or { Length: 0 })
        {
          CreateChild();
          return;
        }
      }
      else if (operationType == typeof(Csla.FetchChildAttribute))
      {
        if (criteria is { Length: 1 } && criteria[0] is int p0_int)
        {
          FetchChild(p0_int);
          return;
        }
      }
      else if (operationType == typeof(Csla.InsertChildAttribute))
      {
        if (criteria is null or { Length: 0 })
        {
          var dal = (global::TestApp.IDal)(serviceProvider.GetService(typeof(global::TestApp.IDal)) ?? throw new global::System.InvalidOperationException($"No service for type '{typeof(global::TestApp.IDal)}' has been registered."));
          await InsertChild(dal).ConfigureAwait(false);
          return;
        }
      }
      else if (operationType == typeof(Csla.UpdateChildAttribute))
      {
        if (criteria is null or { Length: 0 })
        {
          var dal = (global::TestApp.IDal)(serviceProvider.GetService(typeof(global::TestApp.IDal)) ?? throw new global::System.InvalidOperationException($"No service for type '{typeof(global::TestApp.IDal)}' has been registered."));
          await UpdateChild(dal).ConfigureAwait(false);
          return;
        }
      }
      else if (operationType == typeof(Csla.DeleteSelfChildAttribute))
      {
        if (criteria is null or { Length: 0 })
        {
          var dal = (global::TestApp.IDal)(serviceProvider.GetService(typeof(global::TestApp.IDal)) ?? throw new global::System.InvalidOperationException($"No service for type '{typeof(global::TestApp.IDal)}' has been registered."));
          await DeleteSelfChild(dal).ConfigureAwait(false);
          return;
        }
      }
      throw new Csla.Server.DataPortalOperationNotSupportedException(operationType, criteria);
    }
  }
}
