var namespace_csla_1_1_server =
[
    [ "Dashboard", "namespace_csla_1_1_server_1_1_dashboard.html", "namespace_csla_1_1_server_1_1_dashboard" ],
    [ "Hosts", "namespace_csla_1_1_server_1_1_hosts.html", "namespace_csla_1_1_server_1_1_hosts" ],
    [ "AuthorizeRequest", "class_csla_1_1_server_1_1_authorize_request.html", "class_csla_1_1_server_1_1_authorize_request" ],
    [ "ChildDataPortal", "class_csla_1_1_server_1_1_child_data_portal.html", "class_csla_1_1_server_1_1_child_data_portal" ],
    [ "DataPortal", "class_csla_1_1_server_1_1_data_portal.html", "class_csla_1_1_server_1_1_data_portal" ],
    [ "DataPortalBroker", "class_csla_1_1_server_1_1_data_portal_broker.html", "class_csla_1_1_server_1_1_data_portal_broker" ],
    [ "DataPortalContext", "class_csla_1_1_server_1_1_data_portal_context.html", "class_csla_1_1_server_1_1_data_portal_context" ],
    [ "DataPortalException", "class_csla_1_1_server_1_1_data_portal_exception.html", "class_csla_1_1_server_1_1_data_portal_exception" ],
    [ "DataPortalExceptionHandler", "class_csla_1_1_server_1_1_data_portal_exception_handler.html", "class_csla_1_1_server_1_1_data_portal_exception_handler" ],
    [ "DataPortalResult", "class_csla_1_1_server_1_1_data_portal_result.html", "class_csla_1_1_server_1_1_data_portal_result" ],
    [ "DataPortalSelector", "class_csla_1_1_server_1_1_data_portal_selector.html", "class_csla_1_1_server_1_1_data_portal_selector" ],
    [ "EmptyCriteria", "class_csla_1_1_server_1_1_empty_criteria.html", null ],
    [ "FactoryDataPortal", "class_csla_1_1_server_1_1_factory_data_portal.html", "class_csla_1_1_server_1_1_factory_data_portal" ],
    [ "GenericBusinessException", "class_csla_1_1_server_1_1_generic_business_exception.html", "class_csla_1_1_server_1_1_generic_business_exception" ],
    [ "IAuthorizeDataPortal", "interface_csla_1_1_server_1_1_i_authorize_data_portal.html", "interface_csla_1_1_server_1_1_i_authorize_data_portal" ],
    [ "IDataPortalActivator", "interface_csla_1_1_server_1_1_i_data_portal_activator.html", "interface_csla_1_1_server_1_1_i_data_portal_activator" ],
    [ "IDataPortalExceptionInspector", "interface_csla_1_1_server_1_1_i_data_portal_exception_inspector.html", "interface_csla_1_1_server_1_1_i_data_portal_exception_inspector" ],
    [ "IDataPortalServer", "interface_csla_1_1_server_1_1_i_data_portal_server.html", "interface_csla_1_1_server_1_1_i_data_portal_server" ],
    [ "IInterceptDataPortal", "interface_csla_1_1_server_1_1_i_intercept_data_portal.html", "interface_csla_1_1_server_1_1_i_intercept_data_portal" ],
    [ "InterceptArgs", "class_csla_1_1_server_1_1_intercept_args.html", "class_csla_1_1_server_1_1_intercept_args" ],
    [ "IObjectFactoryLoader", "interface_csla_1_1_server_1_1_i_object_factory_loader.html", "interface_csla_1_1_server_1_1_i_object_factory_loader" ],
    [ "MobileFactoryAttribute", "class_csla_1_1_server_1_1_mobile_factory_attribute.html", "class_csla_1_1_server_1_1_mobile_factory_attribute" ],
    [ "NullCriteria", "class_csla_1_1_server_1_1_null_criteria.html", null ],
    [ "ObjectFactory", "class_csla_1_1_server_1_1_object_factory.html", "class_csla_1_1_server_1_1_object_factory" ],
    [ "ObjectFactoryAttribute", "class_csla_1_1_server_1_1_object_factory_attribute.html", "class_csla_1_1_server_1_1_object_factory_attribute" ],
    [ "ObjectFactoryLoader", "class_csla_1_1_server_1_1_object_factory_loader.html", "class_csla_1_1_server_1_1_object_factory_loader" ],
    [ "ServicedDataPortalReadCommitted", "class_csla_1_1_server_1_1_serviced_data_portal_read_committed.html", "class_csla_1_1_server_1_1_serviced_data_portal_read_committed" ],
    [ "ServicedDataPortalReadUncommitted", "class_csla_1_1_server_1_1_serviced_data_portal_read_uncommitted.html", "class_csla_1_1_server_1_1_serviced_data_portal_read_uncommitted" ],
    [ "ServicedDataPortalRepeatableRead", "class_csla_1_1_server_1_1_serviced_data_portal_repeatable_read.html", "class_csla_1_1_server_1_1_serviced_data_portal_repeatable_read" ],
    [ "ServicedDataPortalSerializable", "class_csla_1_1_server_1_1_serviced_data_portal_serializable.html", "class_csla_1_1_server_1_1_serviced_data_portal_serializable" ],
    [ "SimpleDataPortal", "class_csla_1_1_server_1_1_simple_data_portal.html", "class_csla_1_1_server_1_1_simple_data_portal" ],
    [ "TransactionalDataPortal", "class_csla_1_1_server_1_1_transactional_data_portal.html", "class_csla_1_1_server_1_1_transactional_data_portal" ]
];