var namespace_csla_1_1_core =
[
    [ "FieldManager", "namespace_csla_1_1_core_1_1_field_manager.html", "namespace_csla_1_1_core_1_1_field_manager" ],
    [ "LoadManager", "namespace_csla_1_1_core_1_1_load_manager.html", "namespace_csla_1_1_core_1_1_load_manager" ],
    [ "TypeConverters", "namespace_csla_1_1_core_1_1_type_converters.html", "namespace_csla_1_1_core_1_1_type_converters" ],
    [ "AddedNewEventArgs", "class_csla_1_1_core_1_1_added_new_event_args.html", "class_csla_1_1_core_1_1_added_new_event_args" ],
    [ "ApplicationContextManager", "class_csla_1_1_core_1_1_application_context_manager.html", "class_csla_1_1_core_1_1_application_context_manager" ],
    [ "ApplicationContextManagerStatic", "class_csla_1_1_core_1_1_application_context_manager_static.html", "class_csla_1_1_core_1_1_application_context_manager_static" ],
    [ "ApplicationContextManagerTls", "class_csla_1_1_core_1_1_application_context_manager_tls.html", "class_csla_1_1_core_1_1_application_context_manager_tls" ],
    [ "BindableBase", "class_csla_1_1_core_1_1_bindable_base.html", "class_csla_1_1_core_1_1_bindable_base" ],
    [ "BusinessBase", "class_csla_1_1_core_1_1_business_base.html", "class_csla_1_1_core_1_1_business_base" ],
    [ "BusyChangedEventArgs", "class_csla_1_1_core_1_1_busy_changed_event_args.html", "class_csla_1_1_core_1_1_busy_changed_event_args" ],
    [ "ChildChangedEventArgs", "class_csla_1_1_core_1_1_child_changed_event_args.html", "class_csla_1_1_core_1_1_child_changed_event_args" ],
    [ "ContextDictionary", "class_csla_1_1_core_1_1_context_dictionary.html", "class_csla_1_1_core_1_1_context_dictionary" ],
    [ "ErrorEventArgs", "class_csla_1_1_core_1_1_error_event_args.html", "class_csla_1_1_core_1_1_error_event_args" ],
    [ "ExtendedBindingList", "class_csla_1_1_core_1_1_extended_binding_list.html", "class_csla_1_1_core_1_1_extended_binding_list" ],
    [ "GraphMerger", "class_csla_1_1_core_1_1_graph_merger.html", "class_csla_1_1_core_1_1_graph_merger" ],
    [ "IBusinessObject", "interface_csla_1_1_core_1_1_i_business_object.html", "interface_csla_1_1_core_1_1_i_business_object" ],
    [ "ICheckRules", "interface_csla_1_1_core_1_1_i_check_rules.html", "interface_csla_1_1_core_1_1_i_check_rules" ],
    [ "ICommandObject", "interface_csla_1_1_core_1_1_i_command_object.html", null ],
    [ "IContextManager", "interface_csla_1_1_core_1_1_i_context_manager.html", "interface_csla_1_1_core_1_1_i_context_manager" ],
    [ "IdentityManager", "class_csla_1_1_core_1_1_identity_manager.html", "class_csla_1_1_core_1_1_identity_manager" ],
    [ "IEditableBusinessObject", "interface_csla_1_1_core_1_1_i_editable_business_object.html", "interface_csla_1_1_core_1_1_i_editable_business_object" ],
    [ "IEditableCollection", "interface_csla_1_1_core_1_1_i_editable_collection.html", "interface_csla_1_1_core_1_1_i_editable_collection" ],
    [ "IExtendedBindingList", "interface_csla_1_1_core_1_1_i_extended_binding_list.html", "interface_csla_1_1_core_1_1_i_extended_binding_list" ],
    [ "IMemberInfo", "interface_csla_1_1_core_1_1_i_member_info.html", "interface_csla_1_1_core_1_1_i_member_info" ],
    [ "INotifyBusy", "interface_csla_1_1_core_1_1_i_notify_busy.html", "interface_csla_1_1_core_1_1_i_notify_busy" ],
    [ "INotifyChildChanged", "interface_csla_1_1_core_1_1_i_notify_child_changed.html", "interface_csla_1_1_core_1_1_i_notify_child_changed" ],
    [ "INotifyUnhandledAsyncException", "interface_csla_1_1_core_1_1_i_notify_unhandled_async_exception.html", "interface_csla_1_1_core_1_1_i_notify_unhandled_async_exception" ],
    [ "InvalidQueryException", "class_csla_1_1_core_1_1_invalid_query_exception.html", "class_csla_1_1_core_1_1_invalid_query_exception" ],
    [ "IObservableBindingList", "interface_csla_1_1_core_1_1_i_observable_binding_list.html", "interface_csla_1_1_core_1_1_i_observable_binding_list" ],
    [ "IParent", "interface_csla_1_1_core_1_1_i_parent.html", "interface_csla_1_1_core_1_1_i_parent" ],
    [ "IPropertyInfo", "interface_csla_1_1_core_1_1_i_property_info.html", "interface_csla_1_1_core_1_1_i_property_info" ],
    [ "IPropertyInfoFactory", "interface_csla_1_1_core_1_1_i_property_info_factory.html", "interface_csla_1_1_core_1_1_i_property_info_factory" ],
    [ "IReadOnlyCollection", "interface_csla_1_1_core_1_1_i_read_only_collection.html", null ],
    [ "IReadOnlyObject", "interface_csla_1_1_core_1_1_i_read_only_object.html", "interface_csla_1_1_core_1_1_i_read_only_object" ],
    [ "IReportTotalRowCount", "interface_csla_1_1_core_1_1_i_report_total_row_count.html", "interface_csla_1_1_core_1_1_i_report_total_row_count" ],
    [ "ISavable", "interface_csla_1_1_core_1_1_i_savable.html", "interface_csla_1_1_core_1_1_i_savable" ],
    [ "ISmartField", "interface_csla_1_1_core_1_1_i_smart_field.html", "interface_csla_1_1_core_1_1_i_smart_field" ],
    [ "ISupportUndo", "interface_csla_1_1_core_1_1_i_support_undo.html", "interface_csla_1_1_core_1_1_i_support_undo" ],
    [ "ITrackStatus", "interface_csla_1_1_core_1_1_i_track_status.html", "interface_csla_1_1_core_1_1_i_track_status" ],
    [ "IUndoableObject", "interface_csla_1_1_core_1_1_i_undoable_object.html", "interface_csla_1_1_core_1_1_i_undoable_object" ],
    [ "ManagedObjectBase", "class_csla_1_1_core_1_1_managed_object_base.html", "class_csla_1_1_core_1_1_managed_object_base" ],
    [ "MetaPropertyChangedEventArgs", "class_csla_1_1_core_1_1_meta_property_changed_event_args.html", "class_csla_1_1_core_1_1_meta_property_changed_event_args" ],
    [ "MobileBindingList", "class_csla_1_1_core_1_1_mobile_binding_list.html", "class_csla_1_1_core_1_1_mobile_binding_list" ],
    [ "MobileDictionary", "class_csla_1_1_core_1_1_mobile_dictionary.html", "class_csla_1_1_core_1_1_mobile_dictionary" ],
    [ "MobileList", "class_csla_1_1_core_1_1_mobile_list.html", "class_csla_1_1_core_1_1_mobile_list" ],
    [ "MobileObject", "class_csla_1_1_core_1_1_mobile_object.html", "class_csla_1_1_core_1_1_mobile_object" ],
    [ "MobileObservableCollection", "class_csla_1_1_core_1_1_mobile_observable_collection.html", "class_csla_1_1_core_1_1_mobile_observable_collection" ],
    [ "ObservableBindingList", "class_csla_1_1_core_1_1_observable_binding_list.html", "class_csla_1_1_core_1_1_observable_binding_list" ],
    [ "ReadOnlyBindingList", "class_csla_1_1_core_1_1_read_only_binding_list.html", "class_csla_1_1_core_1_1_read_only_binding_list" ],
    [ "ReadOnlyObservableBindingList", "class_csla_1_1_core_1_1_read_only_observable_binding_list.html", "class_csla_1_1_core_1_1_read_only_observable_binding_list" ],
    [ "RemovingItemEventArgs", "class_csla_1_1_core_1_1_removing_item_event_args.html", "class_csla_1_1_core_1_1_removing_item_event_args" ],
    [ "SavedEventArgs", "class_csla_1_1_core_1_1_saved_event_args.html", "class_csla_1_1_core_1_1_saved_event_args" ],
    [ "UndoableBase", "class_csla_1_1_core_1_1_undoable_base.html", "class_csla_1_1_core_1_1_undoable_base" ],
    [ "UndoException", "class_csla_1_1_core_1_1_undo_exception.html", "class_csla_1_1_core_1_1_undo_exception" ],
    [ "StateMode", "namespace_csla_1_1_core.html#ae4d1bfe03690e28c9ac1bd7066cd5c59", [
      [ "Serialization", "namespace_csla_1_1_core.html#ae4d1bfe03690e28c9ac1bd7066cd5c59a1adb0c1dbe31b0bf5fa0665a823707a0", null ],
      [ "Undo", "namespace_csla_1_1_core.html#ae4d1bfe03690e28c9ac1bd7066cd5c59a1cdc076b28f70afac5fcedadf99fa119", null ]
    ] ],
    [ "AsyncFactoryDelegate< R >", "namespace_csla_1_1_core.html#a3088984d8d151c5ec478070d6ca60acc", null ],
    [ "AsyncFactoryDelegate< T, R >", "namespace_csla_1_1_core.html#abb0298ac455b66a8628a9c567c8b947d", null ],
    [ "BusyChangedEventHandler", "namespace_csla_1_1_core.html#a6e5e9144d3f05f7275d0411443def6de", null ]
];