'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.26
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Csla.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Adding items not allowed.
        '''</summary>
        Friend ReadOnly Property AddItemException() As String
            Get
                Return ResourceManager.GetString("AddItemException", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Batch job completed.
        '''</summary>
        Friend ReadOnly Property BatchQueueJobCompleted() As String
            Get
                Return ResourceManager.GetString("BatchQueueJobCompleted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Batch job failed due to execution error .
        '''</summary>
        Friend ReadOnly Property BatchQueueJobFailed() As String
            Get
                Return ResourceManager.GetString("BatchQueueJobFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Job object:.
        '''</summary>
        Friend ReadOnly Property BatchQueueJobObjectPrefix() As String
            Get
                Return ResourceManager.GetString("BatchQueueJobObjectPrefix", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Batch job:.
        '''</summary>
        Friend ReadOnly Property BatchQueueJobPrefix() As String
            Get
                Return ResourceManager.GetString("BatchQueueJobPrefix", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Max jobs:.
        '''</summary>
        Friend ReadOnly Property BatchQueueProcMaxJobs() As String
            Get
                Return ResourceManager.GetString("BatchQueueProcMaxJobs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Name:.
        '''</summary>
        Friend ReadOnly Property BatchQueueProcName() As String
            Get
                Return ResourceManager.GetString("BatchQueueProcName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Port:.
        '''</summary>
        Friend ReadOnly Property BatchQueueProcPort() As String
            Get
                Return ResourceManager.GetString("BatchQueueProcPort", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Queue:.
        '''</summary>
        Friend ReadOnly Property BatchQueueProcQueue() As String
            Get
                Return ResourceManager.GetString("BatchQueueProcQueue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Batch queue processor started.
        '''</summary>
        Friend ReadOnly Property BatchQueueProcStarted() As String
            Get
                Return ResourceManager.GetString("BatchQueueProcStarted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Principal must be of type BusinessPrincipal, not.
        '''</summary>
        Friend ReadOnly Property BusinessPrincipalException() As String
            Get
                Return ResourceManager.GetString("BusinessPrincipalException", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Changing an element is an invalid operation.
        '''</summary>
        Friend ReadOnly Property ChangeInvalidException() As String
            Get
                Return ResourceManager.GetString("ChangeInvalidException", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Can not directly mark a child object for deletion - use its parent collection.
        '''</summary>
        Friend ReadOnly Property ChildDeleteException() As String
            Get
                Return ResourceManager.GetString("ChildDeleteException", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Clear is an invalid operation.
        '''</summary>
        Friend ReadOnly Property ClearInvalidException() As String
            Get
                Return ResourceManager.GetString("ClearInvalidException", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid operation - create not allowed.
        '''</summary>
        Friend ReadOnly Property CreateNotSupportedException() As String
            Get
                Return ResourceManager.GetString("CreateNotSupportedException", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid operation - delete not allowed.
        '''</summary>
        Friend ReadOnly Property DeleteNotSupportedException() As String
            Get
                Return ResourceManager.GetString("DeleteNotSupportedException", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error reading value:.
        '''</summary>
        Friend ReadOnly Property ErrorReadingValueException() As String
            Get
                Return ResourceManager.GetString("ErrorReadingValueException", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid operation - execute not allowed.
        '''</summary>
        Friend ReadOnly Property ExecuteNotSupportedException() As String
            Get
                Return ResourceManager.GetString("ExecuteNotSupportedException", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to failed.
        '''</summary>
        Friend ReadOnly Property Failed() As String
            Get
                Return ResourceManager.GetString("Failed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to failed on the server.
        '''</summary>
        Friend ReadOnly Property FailedOnServer() As String
            Get
                Return ResourceManager.GetString("FailedOnServer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid operation - fetch not allowed.
        '''</summary>
        Friend ReadOnly Property FetchNotSupportedException() As String
            Get
                Return ResourceManager.GetString("FetchNotSupportedException", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to GetIdValue must not return Nothing.
        '''</summary>
        Friend ReadOnly Property GetIdValueCantBeNull() As String
            Get
                Return ResourceManager.GetString("GetIdValueCantBeNull", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Insert is an invalid operation.
        '''</summary>
        Friend ReadOnly Property InsertInvalidException() As String
            Get
                Return ResourceManager.GetString("InsertInvalidException", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid operation - insert not allowed.
        '''</summary>
        Friend ReadOnly Property InsertNotSupportedException() As String
            Get
                Return ResourceManager.GetString("InsertNotSupportedException", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Value must be a valid date.
        '''</summary>
        Friend ReadOnly Property InvalidDateException() As String
            Get
                Return ResourceManager.GetString("InvalidDateException", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to method call failed.
        '''</summary>
        Friend ReadOnly Property MethodCallFailed() As String
            Get
                Return ResourceManager.GetString("MethodCallFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to not implemented.
        '''</summary>
        Friend ReadOnly Property MethodNotImplemented() As String
            Get
                Return ResourceManager.GetString("MethodNotImplemented", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ApplyEdit is not valid on a child object.
        '''</summary>
        Friend ReadOnly Property NoApplyEditChildException() As String
            Get
                Return ResourceManager.GetString("NoApplyEditChildException", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to BeginEdit is not valid on a child object.
        '''</summary>
        Friend ReadOnly Property NoBeginEditChildException() As String
            Get
                Return ResourceManager.GetString("NoBeginEditChildException", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CancelEdit is not valid on a child object.
        '''</summary>
        Friend ReadOnly Property NoCancelEditChildException() As String
            Get
                Return ResourceManager.GetString("NoCancelEditChildException", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Items can not be changed in a read-only collection.
        '''</summary>
        Friend ReadOnly Property NoChangeReadOnlyException() As String
            Get
                Return ResourceManager.GetString("NoChangeReadOnlyException", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Clear is invalid for a read-only collection.
        '''</summary>
        Friend ReadOnly Property NoClearReadOnlyException() As String
            Get
                Return ResourceManager.GetString("NoClearReadOnlyException", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid for root objects - use Delete instead.
        '''</summary>
        Friend ReadOnly Property NoDeleteRootException() As String
            Get
                Return ResourceManager.GetString("NoDeleteRootException", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Insert is invalid for a read-only collection.
        '''</summary>
        Friend ReadOnly Property NoInsertReadOnlyException() As String
            Get
                Return ResourceManager.GetString("NoInsertReadOnlyException", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No matching item in collection.
        '''</summary>
        Friend ReadOnly Property NoMatchException() As String
            Get
                Return ResourceManager.GetString("NoMatchException", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No principal object should be passed to DataPortal when using Windows integrated security.
        '''</summary>
        Friend ReadOnly Property NoPrincipalAllowedException() As String
            Get
                Return ResourceManager.GetString("NoPrincipalAllowedException", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Remove is invalid for a read-only collection.
        '''</summary>
        Friend ReadOnly Property NoRemoveReadOnlyException() As String
            Get
                Return ResourceManager.GetString("NoRemoveReadOnlyException", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Can not directly save a child object.
        '''</summary>
        Friend ReadOnly Property NoSaveChildException() As String
            Get
                Return ResourceManager.GetString("NoSaveChildException", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Object is still being edited and can not be saved.
        '''</summary>
        Friend ReadOnly Property NoSaveEditingException() As String
            Get
                Return ResourceManager.GetString("NoSaveEditingException", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Object is not valid and can not be saved.
        '''</summary>
        Friend ReadOnly Property NoSaveInvalidException() As String
            Get
                Return ResourceManager.GetString("NoSaveInvalidException", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No such value exists:.
        '''</summary>
        Friend ReadOnly Property NoSuchValueExistsException() As String
            Get
                Return ResourceManager.GetString("NoSuchValueExistsException", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Parent value can only be set for child objects.
        '''</summary>
        Friend ReadOnly Property ParentSetException() As String
            Get
                Return ResourceManager.GetString("ParentSetException", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Remove is an invalid operation.
        '''</summary>
        Friend ReadOnly Property RemoveInvalidException() As String
            Get
                Return ResourceManager.GetString("RemoveInvalidException", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Searching is not supported by this collection.
        '''</summary>
        Friend ReadOnly Property SearchingNotSupportedException() As String
            Get
                Return ResourceManager.GetString("SearchingNotSupportedException", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Security.
        '''</summary>
        Friend ReadOnly Property SecurityDataBase() As String
            Get
                Return ResourceManager.GetString("SecurityDataBase", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to @pw.
        '''</summary>
        Friend ReadOnly Property SecurityPasswordParam() As String
            Get
                Return ResourceManager.GetString("SecurityPasswordParam", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Login.
        '''</summary>
        Friend ReadOnly Property SecurityStoredProcedure() As String
            Get
                Return ResourceManager.GetString("SecurityStoredProcedure", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to @user.
        '''</summary>
        Friend ReadOnly Property SecurityUserParam() As String
            Get
                Return ResourceManager.GetString("SecurityUserParam", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to t.
        '''</summary>
        Friend ReadOnly Property SmartDateT() As String
            Get
                Return ResourceManager.GetString("SmartDateT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to today.
        '''</summary>
        Friend ReadOnly Property SmartDateToday() As String
            Get
                Return ResourceManager.GetString("SmartDateToday", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to tom.
        '''</summary>
        Friend ReadOnly Property SmartDateTom() As String
            Get
                Return ResourceManager.GetString("SmartDateTom", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to tomorrow.
        '''</summary>
        Friend ReadOnly Property SmartDateTomorrow() As String
            Get
                Return ResourceManager.GetString("SmartDateTomorrow", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to y.
        '''</summary>
        Friend ReadOnly Property SmartDateY() As String
            Get
                Return ResourceManager.GetString("SmartDateY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to yesterday.
        '''</summary>
        Friend ReadOnly Property SmartDateYesterday() As String
            Get
                Return ResourceManager.GetString("SmartDateYesterday", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sorting is not supported by this collection.
        '''</summary>
        Friend ReadOnly Property SortingNotSupportedException() As String
            Get
                Return ResourceManager.GetString("SortingNotSupportedException", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to String value can not be converted to a date.
        '''</summary>
        Friend ReadOnly Property StringToDateException() As String
            Get
                Return ResourceManager.GetString("StringToDateException", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid operation - update not allowed.
        '''</summary>
        Friend ReadOnly Property UpdateNotSupportedException() As String
            Get
                Return ResourceManager.GetString("UpdateNotSupportedException", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Value is not a SmartDate.
        '''</summary>
        Friend ReadOnly Property ValueNotSmartDateException() As String
            Get
                Return ResourceManager.GetString("ValueNotSmartDateException", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
