//HintName: BusinessBaseTestClass.g.cs
//<auto-generated/>
#nullable enable
using System;
using Csla;

namespace Test;

public partial class BusinessBaseTestClass
{
	public static readonly PropertyInfo<int> NameProperty = RegisterProperty<int>(nameof(Name));
	public partial int Name
	{
		get => GetProperty(NameProperty);
		private set => SetProperty(NameProperty, value);
	}
}
