//HintName: BusinessBaseTestClass.g.cs
//<auto-generated/>
#nullable enable
using System;
using Csla;

namespace Test;

public partial class BusinessBaseTestClass
{
	public static readonly PropertyInfo<char> NameProperty = RegisterProperty<char>(nameof(Name));
	public partial char Name
	{
		get => GetProperty(NameProperty)!;
		private set => SetProperty(NameProperty, value);
	}
}
