//HintName: BusinessBaseTestClass.g.cs
//<auto-generated/>
#nullable enable
using System;
using Csla;

namespace Test;

public partial class BusinessBaseTestClass
{
	public static readonly PropertyInfo<sbyte> NameProperty = RegisterProperty<sbyte>(nameof(Name));
	public partial sbyte Name
	{
		get => GetProperty(NameProperty)!;
		private set => SetProperty(NameProperty, value);
	}
}
