var namespace_csla_1_1_generators_1_1_c_sharp_1_1_auto_serialization_1_1_discovery =
[
    [ "AutoSerializableReceiver", "class_csla_1_1_generators_1_1_c_sharp_1_1_auto_serialization_1_1_discovery_1_1_auto_serializable_receiver.html", "class_csla_1_1_generators_1_1_c_sharp_1_1_auto_serialization_1_1_discovery_1_1_auto_serializable_receiver" ]
];