var namespace_csla_1_1_test_1_1_logical_execution_location =
[
    [ "LocationBusinessBase", "class_csla_1_1_test_1_1_logical_execution_location_1_1_location_business_base.html", "class_csla_1_1_test_1_1_logical_execution_location_1_1_location_business_base" ],
    [ "LogicalExecutionLocationTests", "class_csla_1_1_test_1_1_logical_execution_location_1_1_logical_execution_location_tests.html", "class_csla_1_1_test_1_1_logical_execution_location_1_1_logical_execution_location_tests" ]
];