//-----------------------------------------------------------------------
// <copyright file="DataPortalOperationsBuilder.cs" company="Marimer LLC">
//     Copyright (c) Marimer LLC. All rights reserved.
//     Website: https://cslanet.com
// </copyright>
// <summary>Builds generated source for a type's data portal operations</summary>
//-----------------------------------------------------------------------

using System.CodeDom.Compiler;
using Csla.Generator.AutoImplementProperties.CSharp.DataPortalOperations.Models;

namespace Csla.Generator.AutoImplementProperties.CSharp.DataPortalOperations
{
  /// <summary>
  /// Builds the partial type declaration that exposes a type's data portal
  /// operation methods through a nested <c>IDataPortalOperations</c> interface
  /// and, for concrete types, implements <c>IDataPortalOperationMapping</c>
  /// and <c>IDataPortalOperationNamedMapping</c>.
  /// </summary>
  internal static class DataPortalOperationsBuilder
  {
    private const string HelperType = "global::Csla.Server.DataPortalOperationHelper";
    private const string OperationsLocal = "__operations";
    private const string ExceptionLocal = "__ex";

    /// <summary>
    /// Build the generated source for a type.
    /// </summary>
    public static string Build(OperationTypeModel model)
    {
      var type = model.Type;
      var memberNames = GetInterfaceMemberNames(model.Methods);

      using var stringWriter = new StringWriter();
      var writer = new IndentedTextWriter(stringWriter, "  ");

      writer.WriteLine("//<auto-generated/>");
      writer.WriteLine("#nullable enable");
      writer.WriteLine("#pragma warning disable CS1998 // Async method lacks 'await' operators");
      writer.WriteLineNoTabs(string.Empty);

      if (type.Namespace.Length > 0)
      {
        writer.WriteLine($"namespace {type.Namespace}");
        OpenBlock(writer);
      }

      foreach (var container in type.ContainerDeclarations)
      {
        writer.WriteLine(container);
        OpenBlock(writer);
      }

      var emitMapping = !type.IsAbstract && !type.ImplementsOperationMapping;
      var emitNamedMapping = !type.IsAbstract && !type.ImplementsNamedOperationMapping;

      var baseList = new List<string> { $"{type.FullyQualifiedName}.{OperationDiscovery.OperationsInterfaceName}" };
      if (emitMapping)
        baseList.Add("global::Csla.Server.IDataPortalOperationMapping");
      if (emitNamedMapping)
        baseList.Add("global::Csla.Server.IDataPortalOperationNamedMapping");

      writer.WriteLine($"{type.TypeDeclaration} : {string.Join(", ", baseList)}");
      OpenBlock(writer);

      AppendOperationsInterface(writer, model, memberNames);
      writer.WriteLineNoTabs(string.Empty);
      AppendExplicitImplementations(writer, model, memberNames);

      if (emitMapping)
      {
        writer.WriteLineNoTabs(string.Empty);
        AppendInvokeOperationAsync(writer, model, memberNames);
      }

      if (emitNamedMapping)
      {
        writer.WriteLineNoTabs(string.Empty);
        AppendInvokeNamedOperationAsync(writer, model, memberNames);
      }

      CloseBlock(writer);

      foreach (var _ in type.ContainerDeclarations)
        CloseBlock(writer);

      if (type.Namespace.Length > 0)
        CloseBlock(writer);

      return stringWriter.ToString();
    }

    /// <summary>
    /// Selects the method used for each operation name in name-based
    /// dispatch. Like the runtime method resolution, when several methods
    /// share an operation name (they differ only in injected parameters)
    /// the one with the most injected parameters wins; ties go to the
    /// first declared. Returns the selected methods and any collisions.
    /// </summary>
    public static (List<OperationMethodModel> Selected, List<(OperationMethodModel Winner, OperationMethodModel Loser)> Collisions)
      SelectNamedDispatchMethods(EquatableArray<OperationMethodModel> methods)
    {
      var selected = new List<OperationMethodModel>();
      var collisions = new List<(OperationMethodModel, OperationMethodModel)>();
      foreach (var group in methods.Where(m => m.CanDispatchByName).GroupBy(m => m.OperationName))
      {
        var ordered = group.ToList();
        var winner = ordered[0];
        foreach (var candidate in ordered.Skip(1))
        {
          if (candidate.InjectCount > winner.InjectCount)
            winner = candidate;
        }
        selected.Add(winner);
        foreach (var loser in ordered.Where(m => !ReferenceEquals(m, winner)))
          collisions.Add((winner, loser));
      }
      return (selected, collisions);
    }

    private static Dictionary<OperationMethodModel, string> GetInterfaceMemberNames(EquatableArray<OperationMethodModel> methods)
    {
      var result = new Dictionary<OperationMethodModel, string>(ReferenceEqualityComparer.Instance);
      var signatures = new HashSet<string>();
      foreach (var method in methods)
      {
        var parameterTypes = string.Join(",", method.Parameters.Select(p => p.RefKindPrefix + p.PatternTypeDisplay + (p.IsNullableValueType ? "?" : string.Empty)));
        var name = method.OperationName;
        var suffix = 1;
        while (!signatures.Add($"{name}({parameterTypes})"))
        {
          suffix++;
          name = $"{method.OperationName}_{suffix}";
        }
        result[method] = name;
      }
      return result;
    }

    private static void AppendOperationsInterface(IndentedTextWriter writer, OperationTypeModel model, Dictionary<OperationMethodModel, string> memberNames)
    {
      writer.WriteLine("/// <summary>");
      writer.WriteLine("/// Data portal operation methods declared by this type.");
      writer.WriteLine("/// Generated by CSLA .NET so the methods are statically referenced.");
      writer.WriteLine("/// </summary>");
      writer.WriteLine("[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]");
      var modifiers = model.Type.HidesInheritedOperationsInterface ? "internal new interface" : "internal interface";
      writer.WriteLine($"{modifiers} {OperationDiscovery.OperationsInterfaceName}");
      OpenBlock(writer);
      foreach (var method in model.Methods)
        writer.WriteLine($"{method.ReturnTypeDisplay} {memberNames[method]}({FormatParameters(method)});");
      CloseBlock(writer);
    }

    private static void AppendExplicitImplementations(IndentedTextWriter writer, OperationTypeModel model, Dictionary<OperationMethodModel, string> memberNames)
    {
      foreach (var method in model.Methods)
      {
        var arguments = string.Join(", ", method.Parameters.Select(p => ArgumentPrefix(p) + p.Name));
        writer.WriteLine($"{method.ReturnTypeDisplay} {OperationDiscovery.OperationsInterfaceName}.{memberNames[method]}({FormatParameters(method)}) => {method.MethodName}({arguments});");
      }
    }

    private static void AppendInvokeOperationAsync(IndentedTextWriter writer, OperationTypeModel model, Dictionary<OperationMethodModel, string> memberNames)
    {
      writer.WriteLine("async global::System.Threading.Tasks.Task global::Csla.Server.IDataPortalOperationMapping.InvokeOperationAsync(");
      writer.Indent++;
      writer.WriteLine("global::System.Type operationType, bool isSync, object?[]? criteria, global::System.IServiceProvider serviceProvider)");
      writer.Indent--;
      OpenBlock(writer);

      // Methods sharing an operation name differ only in injected parameters;
      // only the one the runtime would select takes part in dispatch.
      var (_, collisions) = SelectNamedDispatchMethods(model.Methods);
      var losers = new HashSet<OperationMethodModel>(collisions.Select(c => c.Loser), ReferenceEqualityComparer.Instance);
      var dispatchable = model.Methods.Where(m => m.CanDispatch && !losers.Contains(m)).ToList();
      if (dispatchable.Count > 0)
        writer.WriteLine($"var {OperationsLocal} = ({OperationDiscovery.OperationsInterfaceName})this;");

      var candidateIndex = 0;
      var isFirst = true;
      foreach (var kind in OperationDiscovery.OperationKinds)
      {
        var methods = dispatchable.Where(m => m.Kind == kind).ToList();
        if (methods.Count == 0)
          continue;

        writer.WriteLine($"{(isFirst ? "if" : "else if")} (operationType == typeof(global::Csla.{kind}Attribute))");
        isFirst = false;
        OpenBlock(writer);
        foreach (var method in methods)
        {
          // When several methods of this kind take the same number of criteria,
          // require exact runtime types so a less specific overload declared
          // first cannot capture the call; anything else falls back to reflection.
          var requireExactTypes = methods.Count(m => m.CriteriaCount == method.CriteriaCount) > 1;
          AppendDispatch(writer, method, memberNames[method], candidateIndex++, byName: false, requireExactTypes);
        }
        CloseBlock(writer);
      }

      writer.WriteLine("throw new global::Csla.Server.DataPortalOperationNotSupportedException(operationType, criteria);");
      CloseBlock(writer);
    }

    private static void AppendInvokeNamedOperationAsync(IndentedTextWriter writer, OperationTypeModel model, Dictionary<OperationMethodModel, string> memberNames)
    {
      writer.WriteLine("async global::System.Threading.Tasks.Task global::Csla.Server.IDataPortalOperationNamedMapping.InvokeNamedOperationAsync(");
      writer.Indent++;
      writer.WriteLine("string operationName, bool isSync, object?[]? criteria, global::System.IServiceProvider serviceProvider)");
      writer.Indent--;
      OpenBlock(writer);

      var (selected, _) = SelectNamedDispatchMethods(model.Methods);
      if (selected.Count > 0)
      {
        writer.WriteLine($"var {OperationsLocal} = ({OperationDiscovery.OperationsInterfaceName})this;");
        writer.WriteLine("switch (operationName)");
        OpenBlock(writer);
        var candidateIndex = 0;
        foreach (var method in selected)
        {
          writer.WriteLine($"case \"{method.OperationName}\":");
          writer.Indent++;
          AppendDispatch(writer, method, memberNames[method], candidateIndex++, byName: true, requireExactTypes: false);
          writer.WriteLine("break;");
          writer.Indent--;
        }
        CloseBlock(writer);
      }

      writer.WriteLine("throw new global::Csla.Server.DataPortalOperationNotSupportedException(operationName, criteria);");
      CloseBlock(writer);
    }

    private static void AppendDispatch(IndentedTextWriter writer, OperationMethodModel method, string memberName, int candidateIndex, bool byName, bool requireExactTypes)
    {
      var criteria = method.CriteriaParameters.ToList();
      var conditions = new List<string>();
      if (criteria.Count == 0)
      {
        conditions.Add("criteria is null or { Length: 0 }");
      }
      else
      {
        conditions.Add($"criteria is {{ Length: {criteria.Count} }}");
        for (var i = 0; i < criteria.Count; i++)
        {
          var parameter = criteria[i];
          var variable = CriteriaVariable(candidateIndex, i);
          if (byName && parameter.AcceptsNull)
          {
            conditions.Add($"(criteria[{i}] is null || criteria[{i}] is {parameter.PatternTypeDisplay})");
          }
          else
          {
            conditions.Add($"criteria[{i}] is {parameter.PatternTypeDisplay} {variable}");
            if (requireExactTypes && !parameter.IsExactTypeMatch)
              conditions.Add($"{variable}.GetType() == typeof({parameter.PatternTypeDisplay})");
          }
        }
      }

      writer.WriteLine($"if ({string.Join(" && ", conditions)})");
      OpenBlock(writer);

      if (method.IsAsync)
        writer.WriteLine($"{HelperType}.ThrowIfAsyncMethodOnSyncClient(this, isSync, serviceProvider, \"{method.MethodName.TrimStart('@')}\");");

      var arguments = new List<string>();
      var criteriaIndex = 0;
      var injectIndex = 0;
      foreach (var parameter in method.Parameters)
      {
        if (parameter.IsInjected)
        {
          var variable = $"__c{candidateIndex}i{injectIndex++}";
          writer.WriteLine($"var {variable} = {FormatServiceResolution(parameter)};");
          arguments.Add(ArgumentPrefix(parameter) + variable);
        }
        else
        {
          var i = criteriaIndex++;
          string argument;
          if (byName && parameter.AcceptsNull)
          {
            argument = parameter.IsNullableValueType
              ? $"({parameter.TypeDisplay})criteria[{i}]"
              : $"({parameter.TypeDisplay})criteria[{i}]!";
            // An explicit 'in' argument must be a variable, not a cast expression.
            if (parameter.RefKindPrefix == "in ")
            {
              var variable = CriteriaVariable(candidateIndex, i);
              writer.WriteLine($"var {variable} = {argument};");
              argument = variable;
            }
          }
          else
          {
            argument = CriteriaVariable(candidateIndex, i);
          }
          arguments.Add(ArgumentPrefix(parameter) + argument);
        }
      }

      // Like reflection-based dispatch, exceptions thrown by the operation
      // method are wrapped in CallMethodException. This also keeps an operation
      // method throwing DataPortalOperationNotSupportedException from being
      // treated as an unmatched operation and invoked again through reflection.
      var call = $"{OperationsLocal}.{memberName}({string.Join(", ", arguments)})";
      writer.WriteLine("try");
      OpenBlock(writer);
      writer.WriteLine(method.IsAsync ? $"await {call}.ConfigureAwait(false);" : $"{call};");
      CloseBlock(writer);
      writer.WriteLine($"catch (global::System.Exception {ExceptionLocal})");
      OpenBlock(writer);
      writer.WriteLine($"throw {HelperType}.CreateCallMethodException(this, \"{method.MethodName.TrimStart('@')}\", {ExceptionLocal});");
      CloseBlock(writer);
      writer.WriteLine("return;");
      CloseBlock(writer);
    }

    private static string FormatServiceResolution(OperationParameterModel parameter)
    {
      // Nullable<T> services are registered and resolved as Nullable<T>, as in reflection-based dispatch.
      var serviceType = parameter.IsNullableValueType
        ? $"typeof({parameter.PatternTypeDisplay}?)"
        : $"typeof({parameter.PatternTypeDisplay})";
      var resolution = parameter.ServiceKeyExpression is null
        ? $"{HelperType}.GetService(serviceProvider, {serviceType}, {(parameter.AllowNull ? "true" : "false")})"
        : $"{HelperType}.GetKeyedService(serviceProvider, {serviceType}, {parameter.ServiceKeyExpression}, {(parameter.AllowNull ? "true" : "false")})";
      return parameter.AllowNull
        ? $"({parameter.TypeDisplay})({resolution})"
        : $"({parameter.TypeDisplay})({resolution})!";
    }

    private static string CriteriaVariable(int candidateIndex, int criteriaIndex) => $"__c{candidateIndex}p{criteriaIndex}";

    private static string FormatParameters(OperationMethodModel method)
      => string.Join(", ", method.Parameters.Select(p => $"{p.RefKindPrefix}{p.TypeDisplay} {p.Name}"));

    private static string ArgumentPrefix(OperationParameterModel parameter) => parameter.RefKindPrefix;

    private static void OpenBlock(IndentedTextWriter writer)
    {
      writer.WriteLine("{");
      writer.Indent++;
    }

    private static void CloseBlock(IndentedTextWriter writer)
    {
      writer.Indent--;
      writer.WriteLine("}");
    }

    private sealed class ReferenceEqualityComparer : IEqualityComparer<OperationMethodModel>
    {
      public static readonly ReferenceEqualityComparer Instance = new();

      public bool Equals(OperationMethodModel? x, OperationMethodModel? y) => ReferenceEquals(x, y);

      public int GetHashCode(OperationMethodModel obj) => System.Runtime.CompilerServices.RuntimeHelpers.GetHashCode(obj);
    }
  }
}
