//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.42.
// 
#pragma warning disable 1591

namespace PTServiceClient.PTService {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="PTServiceSoap", Namespace="http://ws.lhotka.net/")]
    public partial class PTService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetProjectListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetProjectOperationCompleted;
        
        private CslaCredentials cslaCredentialsValueField;
        
        private System.Threading.SendOrPostCallback AddProjectOperationCompleted;
        
        private System.Threading.SendOrPostCallback EditProjectOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetResourceListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetResourceOperationCompleted;
        
        private System.Threading.SendOrPostCallback ChangeResourceNameOperationCompleted;
        
        private System.Threading.SendOrPostCallback AssignResourceOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRolesOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public PTService() {
            this.Url = global::PTServiceClient.Properties.Settings.Default.PTServiceClient_PTService_PTService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public CslaCredentials CslaCredentialsValue {
            get {
                return this.cslaCredentialsValueField;
            }
            set {
                this.cslaCredentialsValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetProjectListCompletedEventHandler GetProjectListCompleted;
        
        /// <remarks/>
        public event GetProjectCompletedEventHandler GetProjectCompleted;
        
        /// <remarks/>
        public event AddProjectCompletedEventHandler AddProjectCompleted;
        
        /// <remarks/>
        public event EditProjectCompletedEventHandler EditProjectCompleted;
        
        /// <remarks/>
        public event GetResourceListCompletedEventHandler GetResourceListCompleted;
        
        /// <remarks/>
        public event GetResourceCompletedEventHandler GetResourceCompleted;
        
        /// <remarks/>
        public event ChangeResourceNameCompletedEventHandler ChangeResourceNameCompleted;
        
        /// <remarks/>
        public event AssignResourceCompletedEventHandler AssignResourceCompleted;
        
        /// <remarks/>
        public event GetRolesCompletedEventHandler GetRolesCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.lhotka.net/GetProjectList", RequestNamespace="http://ws.lhotka.net/", ResponseNamespace="http://ws.lhotka.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ProjectInfo[] GetProjectList() {
            object[] results = this.Invoke("GetProjectList", new object[0]);
            return ((ProjectInfo[])(results[0]));
        }
        
        /// <remarks/>
        public void GetProjectListAsync() {
            this.GetProjectListAsync(null);
        }
        
        /// <remarks/>
        public void GetProjectListAsync(object userState) {
            if ((this.GetProjectListOperationCompleted == null)) {
                this.GetProjectListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetProjectListOperationCompleted);
            }
            this.InvokeAsync("GetProjectList", new object[0], this.GetProjectListOperationCompleted, userState);
        }
        
        private void OnGetProjectListOperationCompleted(object arg) {
            if ((this.GetProjectListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetProjectListCompleted(this, new GetProjectListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.lhotka.net/GetProject", RequestNamespace="http://ws.lhotka.net/", ResponseNamespace="http://ws.lhotka.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ProjectInfo GetProject(ProjectRequest request) {
            object[] results = this.Invoke("GetProject", new object[] {
                        request});
            return ((ProjectInfo)(results[0]));
        }
        
        /// <remarks/>
        public void GetProjectAsync(ProjectRequest request) {
            this.GetProjectAsync(request, null);
        }
        
        /// <remarks/>
        public void GetProjectAsync(ProjectRequest request, object userState) {
            if ((this.GetProjectOperationCompleted == null)) {
                this.GetProjectOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetProjectOperationCompleted);
            }
            this.InvokeAsync("GetProject", new object[] {
                        request}, this.GetProjectOperationCompleted, userState);
        }
        
        private void OnGetProjectOperationCompleted(object arg) {
            if ((this.GetProjectCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetProjectCompleted(this, new GetProjectCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("CslaCredentialsValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.lhotka.net/AddProject", RequestNamespace="http://ws.lhotka.net/", ResponseNamespace="http://ws.lhotka.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ProjectInfo AddProject(string name, string started, string ended, string description) {
            object[] results = this.Invoke("AddProject", new object[] {
                        name,
                        started,
                        ended,
                        description});
            return ((ProjectInfo)(results[0]));
        }
        
        /// <remarks/>
        public void AddProjectAsync(string name, string started, string ended, string description) {
            this.AddProjectAsync(name, started, ended, description, null);
        }
        
        /// <remarks/>
        public void AddProjectAsync(string name, string started, string ended, string description, object userState) {
            if ((this.AddProjectOperationCompleted == null)) {
                this.AddProjectOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddProjectOperationCompleted);
            }
            this.InvokeAsync("AddProject", new object[] {
                        name,
                        started,
                        ended,
                        description}, this.AddProjectOperationCompleted, userState);
        }
        
        private void OnAddProjectOperationCompleted(object arg) {
            if ((this.AddProjectCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddProjectCompleted(this, new AddProjectCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("CslaCredentialsValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.lhotka.net/EditProject", RequestNamespace="http://ws.lhotka.net/", ResponseNamespace="http://ws.lhotka.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ProjectInfo EditProject(System.Guid id, string name, string started, string ended, string description) {
            object[] results = this.Invoke("EditProject", new object[] {
                        id,
                        name,
                        started,
                        ended,
                        description});
            return ((ProjectInfo)(results[0]));
        }
        
        /// <remarks/>
        public void EditProjectAsync(System.Guid id, string name, string started, string ended, string description) {
            this.EditProjectAsync(id, name, started, ended, description, null);
        }
        
        /// <remarks/>
        public void EditProjectAsync(System.Guid id, string name, string started, string ended, string description, object userState) {
            if ((this.EditProjectOperationCompleted == null)) {
                this.EditProjectOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEditProjectOperationCompleted);
            }
            this.InvokeAsync("EditProject", new object[] {
                        id,
                        name,
                        started,
                        ended,
                        description}, this.EditProjectOperationCompleted, userState);
        }
        
        private void OnEditProjectOperationCompleted(object arg) {
            if ((this.EditProjectCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EditProjectCompleted(this, new EditProjectCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.lhotka.net/GetResourceList", RequestNamespace="http://ws.lhotka.net/", ResponseNamespace="http://ws.lhotka.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ResourceInfo[] GetResourceList() {
            object[] results = this.Invoke("GetResourceList", new object[0]);
            return ((ResourceInfo[])(results[0]));
        }
        
        /// <remarks/>
        public void GetResourceListAsync() {
            this.GetResourceListAsync(null);
        }
        
        /// <remarks/>
        public void GetResourceListAsync(object userState) {
            if ((this.GetResourceListOperationCompleted == null)) {
                this.GetResourceListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetResourceListOperationCompleted);
            }
            this.InvokeAsync("GetResourceList", new object[0], this.GetResourceListOperationCompleted, userState);
        }
        
        private void OnGetResourceListOperationCompleted(object arg) {
            if ((this.GetResourceListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetResourceListCompleted(this, new GetResourceListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.lhotka.net/GetResource", RequestNamespace="http://ws.lhotka.net/", ResponseNamespace="http://ws.lhotka.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ResourceInfo GetResource(ResourceRequest request) {
            object[] results = this.Invoke("GetResource", new object[] {
                        request});
            return ((ResourceInfo)(results[0]));
        }
        
        /// <remarks/>
        public void GetResourceAsync(ResourceRequest request) {
            this.GetResourceAsync(request, null);
        }
        
        /// <remarks/>
        public void GetResourceAsync(ResourceRequest request, object userState) {
            if ((this.GetResourceOperationCompleted == null)) {
                this.GetResourceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetResourceOperationCompleted);
            }
            this.InvokeAsync("GetResource", new object[] {
                        request}, this.GetResourceOperationCompleted, userState);
        }
        
        private void OnGetResourceOperationCompleted(object arg) {
            if ((this.GetResourceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetResourceCompleted(this, new GetResourceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("CslaCredentialsValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.lhotka.net/ChangeResourceName", RequestNamespace="http://ws.lhotka.net/", ResponseNamespace="http://ws.lhotka.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ResourceInfo ChangeResourceName(int id, string firstName, string lastName) {
            object[] results = this.Invoke("ChangeResourceName", new object[] {
                        id,
                        firstName,
                        lastName});
            return ((ResourceInfo)(results[0]));
        }
        
        /// <remarks/>
        public void ChangeResourceNameAsync(int id, string firstName, string lastName) {
            this.ChangeResourceNameAsync(id, firstName, lastName, null);
        }
        
        /// <remarks/>
        public void ChangeResourceNameAsync(int id, string firstName, string lastName, object userState) {
            if ((this.ChangeResourceNameOperationCompleted == null)) {
                this.ChangeResourceNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnChangeResourceNameOperationCompleted);
            }
            this.InvokeAsync("ChangeResourceName", new object[] {
                        id,
                        firstName,
                        lastName}, this.ChangeResourceNameOperationCompleted, userState);
        }
        
        private void OnChangeResourceNameOperationCompleted(object arg) {
            if ((this.ChangeResourceNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ChangeResourceNameCompleted(this, new ChangeResourceNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("CslaCredentialsValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.lhotka.net/AssignResource", RequestNamespace="http://ws.lhotka.net/", ResponseNamespace="http://ws.lhotka.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AssignResource(int resourceId, System.Guid projectId) {
            this.Invoke("AssignResource", new object[] {
                        resourceId,
                        projectId});
        }
        
        /// <remarks/>
        public void AssignResourceAsync(int resourceId, System.Guid projectId) {
            this.AssignResourceAsync(resourceId, projectId, null);
        }
        
        /// <remarks/>
        public void AssignResourceAsync(int resourceId, System.Guid projectId, object userState) {
            if ((this.AssignResourceOperationCompleted == null)) {
                this.AssignResourceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAssignResourceOperationCompleted);
            }
            this.InvokeAsync("AssignResource", new object[] {
                        resourceId,
                        projectId}, this.AssignResourceOperationCompleted, userState);
        }
        
        private void OnAssignResourceOperationCompleted(object arg) {
            if ((this.AssignResourceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AssignResourceCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.lhotka.net/GetRoles", RequestNamespace="http://ws.lhotka.net/", ResponseNamespace="http://ws.lhotka.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RoleInfo[] GetRoles() {
            object[] results = this.Invoke("GetRoles", new object[0]);
            return ((RoleInfo[])(results[0]));
        }
        
        /// <remarks/>
        public void GetRolesAsync() {
            this.GetRolesAsync(null);
        }
        
        /// <remarks/>
        public void GetRolesAsync(object userState) {
            if ((this.GetRolesOperationCompleted == null)) {
                this.GetRolesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRolesOperationCompleted);
            }
            this.InvokeAsync("GetRoles", new object[0], this.GetRolesOperationCompleted, userState);
        }
        
        private void OnGetRolesOperationCompleted(object arg) {
            if ((this.GetRolesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRolesCompleted(this, new GetRolesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.lhotka.net/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://ws.lhotka.net/", IsNullable=false)]
    public partial class CslaCredentials : System.Web.Services.Protocols.SoapHeader {
        
        private string usernameField;
        
        private string passwordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.lhotka.net/")]
    public partial class RoleInfo {
        
        private int idField;
        
        private string nameField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.lhotka.net/")]
    public partial class ResourceRequest {
        
        private int idField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.lhotka.net/")]
    public partial class ResourceAssignmentInfo {
        
        private System.Guid projectIdField;
        
        private string projectNameField;
        
        private string assignedField;
        
        private int roleField;
        
        /// <remarks/>
        public System.Guid ProjectId {
            get {
                return this.projectIdField;
            }
            set {
                this.projectIdField = value;
            }
        }
        
        /// <remarks/>
        public string ProjectName {
            get {
                return this.projectNameField;
            }
            set {
                this.projectNameField = value;
            }
        }
        
        /// <remarks/>
        public string Assigned {
            get {
                return this.assignedField;
            }
            set {
                this.assignedField = value;
            }
        }
        
        /// <remarks/>
        public int Role {
            get {
                return this.roleField;
            }
            set {
                this.roleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.lhotka.net/")]
    public partial class ResourceInfo {
        
        private int idField;
        
        private string nameField;
        
        private ResourceAssignmentInfo[] resourceAssignmentsField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public ResourceAssignmentInfo[] ResourceAssignments {
            get {
                return this.resourceAssignmentsField;
            }
            set {
                this.resourceAssignmentsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.lhotka.net/")]
    public partial class ProjectRequest {
        
        private System.Guid idField;
        
        /// <remarks/>
        public System.Guid Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.lhotka.net/")]
    public partial class ProjectResourceInfo {
        
        private int resourceIdField;
        
        private string firstNameField;
        
        private string lastNameField;
        
        private string assignedField;
        
        private int roleField;
        
        /// <remarks/>
        public int ResourceId {
            get {
                return this.resourceIdField;
            }
            set {
                this.resourceIdField = value;
            }
        }
        
        /// <remarks/>
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        public string Assigned {
            get {
                return this.assignedField;
            }
            set {
                this.assignedField = value;
            }
        }
        
        /// <remarks/>
        public int Role {
            get {
                return this.roleField;
            }
            set {
                this.roleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.lhotka.net/")]
    public partial class ProjectInfo {
        
        private System.Guid idField;
        
        private string nameField;
        
        private string startedField;
        
        private string endedField;
        
        private string descriptionField;
        
        private ProjectResourceInfo[] projectResourcesField;
        
        /// <remarks/>
        public System.Guid Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Started {
            get {
                return this.startedField;
            }
            set {
                this.startedField = value;
            }
        }
        
        /// <remarks/>
        public string Ended {
            get {
                return this.endedField;
            }
            set {
                this.endedField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public ProjectResourceInfo[] ProjectResources {
            get {
                return this.projectResourcesField;
            }
            set {
                this.projectResourcesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void GetProjectListCompletedEventHandler(object sender, GetProjectListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetProjectListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetProjectListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ProjectInfo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ProjectInfo[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void GetProjectCompletedEventHandler(object sender, GetProjectCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetProjectCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetProjectCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ProjectInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ProjectInfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void AddProjectCompletedEventHandler(object sender, AddProjectCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddProjectCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddProjectCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ProjectInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ProjectInfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void EditProjectCompletedEventHandler(object sender, EditProjectCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EditProjectCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EditProjectCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ProjectInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ProjectInfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void GetResourceListCompletedEventHandler(object sender, GetResourceListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetResourceListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetResourceListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResourceInfo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResourceInfo[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void GetResourceCompletedEventHandler(object sender, GetResourceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetResourceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetResourceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResourceInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResourceInfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void ChangeResourceNameCompletedEventHandler(object sender, ChangeResourceNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ChangeResourceNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ChangeResourceNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResourceInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResourceInfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void AssignResourceCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void GetRolesCompletedEventHandler(object sender, GetRolesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRolesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRolesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RoleInfo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RoleInfo[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591