<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\Directory.Package.props" />

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>Csla.Xaml</AssemblyName>
    <RootNamespace>Csla.Xaml</RootNamespace>
    <PackageId>Csla.Avalonia</PackageId>
    <Product>CSLA .NET Avalonia</Product>
    <Description>UI helpers for using CSLA .NET business types with Avalonia.</Description>
    <SignAssembly>true</SignAssembly>
    <BaseOutputPath>..\..\Bin</BaseOutputPath>
    <DefineConstants>$(DefineConstants);AVALONIA</DefineConstants>

    <Title>CSLA .NET Avalonia</Title>
    <PackageTags>CSLA;Avalonia;XAML</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="12.1.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Csla\Csla.csproj" />
  </ItemGroup>

  <Import Project="..\Csla.Xaml.Shared\Csla.Xaml.Shared.projitems" Label="Shared" />

</Project>
