using Csla;

public class IsBusinessObjectSerializableMakeSerializableCodeFixTests_VerifyGetFixesWhenNeitherUsingsExists
	: BusinessBase<IsBusinessObjectSerializableMakeSerializableCodeFixTests_VerifyGetFixesWhenNeitherUsingsExists>
{
	public void DataPortal_Fetch() { }
}