using Csla;

public class IsBusinessObjectSerializableMakeSerializableCodeFixTests_VerifyGetFixesWhenUsingSystemDoesNotExist
	: BusinessBase<IsBusinessObjectSerializableMakeSerializableCodeFixTests_VerifyGetFixesWhenUsingSystemDoesNotExist>
{ }