using Csla;
using System;

public class IsBusinessObjectSerializableMakeSerializableCodeFixTests_VerifyGetFixesWhenOnlyUsingSystemExists
	: BusinessBase<IsBusinessObjectSerializableMakeSerializableCodeFixTests_VerifyGetFixesWhenOnlyUsingSystemExists>
{
	public void DataPortal_Fetch() { }
}