var _asynchronous_business_rule_inheriting_from_business_rule_change_to_business_rule_async_code_fix_8cs =
[
    [ "Csla.Analyzers.AsynchronousBusinessRuleInheritingFromBusinessRuleChangeToBusinessRuleAsyncCodeFix", "class_csla_1_1_analyzers_1_1_asynchronous_business_rule_inheriting_from_business_rule_change_to_business_rule_async_code_fix.html", "class_csla_1_1_analyzers_1_1_asynchronous_business_rule_inheriting_from_business_rule_change_to_business_rule_async_code_fix" ]
];