var _auto_serialization_2_csla_8_generator_8_auto_serialization_8_c_sharp_2_auto_serializable_2_extr4a33db692d7f43868ae685a4614eda4a =
[
    [ "Csla.Generator.AutoSerialization.CSharp.AutoSerialization.ExtractedMemberTypeDefinition", "class_csla_1_1_generator_1_1_auto_serialization_1_1_c_sharp_1_1_auto_serialization_1_1_extracted_member_type_definition.html", "class_csla_1_1_generator_1_1_auto_serialization_1_1_c_sharp_1_1_auto_serialization_1_1_extracted_member_type_definition" ]
];