var _auto_serialization_2_csla_8_generator_8_auto_serialization_8_c_sharp_2_auto_serializable_2_i_member_definition_8cs =
[
    [ "Csla.Generator.AutoSerialization.CSharp.AutoSerialization.IMemberDefinition", "interface_csla_1_1_generator_1_1_auto_serialization_1_1_c_sharp_1_1_auto_serialization_1_1_i_member_definition.html", "interface_csla_1_1_generator_1_1_auto_serialization_1_1_c_sharp_1_1_auto_serialization_1_1_i_member_definition" ]
];