var _does_child_operation_have_run_local_remove_attribute_code_fix_8cs =
[
    [ "Csla.Analyzers.DoesChildOperationHaveRunLocalRemoveAttributeCodeFix", "class_csla_1_1_analyzers_1_1_does_child_operation_have_run_local_remove_attribute_code_fix.html", "class_csla_1_1_analyzers_1_1_does_child_operation_have_run_local_remove_attribute_code_fix" ]
];