var _revalidating_interceptor_options_8cs =
[
    [ "Csla.Server.Interceptors.ServerSide.RevalidatingInterceptorOptions", "class_csla_1_1_server_1_1_interceptors_1_1_server_side_1_1_revalidating_interceptor_options.html", "class_csla_1_1_server_1_1_interceptors_1_1_server_side_1_1_revalidating_interceptor_options" ]
];