var dir_04e895bb413f40e39343693ed95088c8 =
[
    [ "Configuration", "dir_755f611d1924b31701f14644e07a6133.html", "dir_755f611d1924b31701f14644e07a6133" ],
    [ "CustomSerializers", "dir_a80b9a4d4861f31c60d3ac436a70dd6f.html", "dir_a80b9a4d4861f31c60d3ac436a70dd6f" ],
    [ "AssemblyNameTranslator.cs", "_assembly_name_translator_8cs.html", null ],
    [ "BinaryValueHelper.cs", "_binary_value_helper_8cs.html", null ],
    [ "CslaBinaryReader.cs", "_csla_binary_reader_8cs.html", "_csla_binary_reader_8cs" ],
    [ "CslaBinaryWriter.cs", "_csla_binary_writer_8cs.html", "_csla_binary_writer_8cs" ],
    [ "CslaKnownTypes.cs", "_csla_known_types_8cs.html", "_csla_known_types_8cs" ],
    [ "CslaLegacyBinaryReader.cs", "_csla_legacy_binary_reader_8cs.html", "_csla_legacy_binary_reader_8cs" ],
    [ "CslaLegacyBinaryWriter.cs", "_csla_legacy_binary_writer_8cs.html", "_csla_legacy_binary_writer_8cs" ],
    [ "CslaNonClosingBinaryWriter.cs", "_csla_non_closing_binary_writer_8cs.html", "_csla_non_closing_binary_writer_8cs" ],
    [ "CslaReaderWriterFactory.cs", "_csla_reader_writer_factory_8cs.html", null ],
    [ "CslaXmlBinaryReader.cs", "_csla_xml_binary_reader_8cs.html", "_csla_xml_binary_reader_8cs" ],
    [ "CslaXmlBinaryWriter.cs", "_csla_xml_binary_writer_8cs.html", "_csla_xml_binary_writer_8cs" ],
    [ "CslaXmlReader.cs", "_csla_xml_reader_8cs.html", "_csla_xml_reader_8cs" ],
    [ "CslaXmlWriter.cs", "_csla_xml_writer_8cs.html", "_csla_xml_writer_8cs" ],
    [ "DictionaryCheckResult.cs", "_dictionary_check_result_8cs.html", null ],
    [ "ICslaReader.cs", "_i_csla_reader_8cs.html", "_i_csla_reader_8cs" ],
    [ "ICslaWriter.cs", "_i_csla_writer_8cs.html", "_i_csla_writer_8cs" ],
    [ "IMobileList.cs", "_i_mobile_list_8cs.html", "_i_mobile_list_8cs" ],
    [ "IMobileObject.cs", "_i_mobile_object_8cs.html", "_i_mobile_object_8cs" ],
    [ "IMobileObjectMetastate.cs", "_i_mobile_object_metastate_8cs.html", "_i_mobile_object_metastate_8cs" ],
    [ "IMobileSerializer.cs", "_i_mobile_serializer_8cs.html", "_i_mobile_serializer_8cs" ],
    [ "ISerializationNotification.cs", "_i_serialization_notification_8cs.html", "_i_serialization_notification_8cs" ],
    [ "ITypeMap.cs", "_i_type_map_8cs.html", "_i_type_map_8cs" ],
    [ "MobileFormatter.cs", "_mobile_formatter_8cs.html", "_mobile_formatter_8cs" ],
    [ "MobileFormatterException.cs", "_mobile_formatter_exception_8cs.html", "_mobile_formatter_exception_8cs" ],
    [ "NullPlaceholder.cs", "_null_placeholder_8cs.html", "_null_placeholder_8cs" ],
    [ "ReferenceComparer.cs", "_reference_comparer_8cs.html", "_reference_comparer_8cs" ],
    [ "SerializationInfo.cs", "_serialization_info_8cs.html", "_serialization_info_8cs" ],
    [ "TypeMap.cs", "_type_map_8cs.html", "_type_map_8cs" ]
];