var namespace_csla_1_1_generator_1_1_auto_serialization_1_1_c_sharp =
[
    [ "AutoSerialization", "namespace_csla_1_1_generator_1_1_auto_serialization_1_1_c_sharp_1_1_auto_serialization.html", "namespace_csla_1_1_generator_1_1_auto_serialization_1_1_c_sharp_1_1_auto_serialization" ]
];