var namespace_csla_1_1_analyzers_1_1_managed_backing_field_uses_nameof =
[
    [ "EvaluateManagedBackingFieldsNameofAnalyzer", "class_csla_1_1_analyzers_1_1_managed_backing_field_uses_nameof_1_1_evaluate_managed_backing_fields_nameof_analyzer.html", "class_csla_1_1_analyzers_1_1_managed_backing_field_uses_nameof_1_1_evaluate_managed_backing_fields_nameof_analyzer" ],
    [ "EvaluateManagedBackingFieldsNameofCodeFix", "class_csla_1_1_analyzers_1_1_managed_backing_field_uses_nameof_1_1_evaluate_managed_backing_fields_nameof_code_fix.html", "class_csla_1_1_analyzers_1_1_managed_backing_field_uses_nameof_1_1_evaluate_managed_backing_fields_nameof_code_fix" ]
];