#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ProjectTracker.AndroidUI.Resource", IsApplication=true)]

namespace ProjectTracker.AndroidUI
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Csla.Axml.Resource.String.ApplicationName = global::ProjectTracker.AndroidUI.Resource.String.ApplicationName;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int blue = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int green = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int grey = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int red = 2131034113;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060004
			public const int button_normalheight = 2131099652;
			
			// aapt resource value: 0x7f060003
			public const int button_normalwidth = 2131099651;
			
			// aapt resource value: 0x7f060000
			public const int phonetext_extralargestyle = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int phonetext_largestyle = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int phonetext_normalstyle = 2131099650;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int appbar_check_rest = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int appbar_close_rest = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int appbar_delete_rest = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int appbar_edit_rest = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int appbar_login_rest = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int appbar_refresh_rest = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int appbar_save_rest = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ApplicationIcon = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int Icon = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int SplashScreenImage = 2130837513;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080009
			public const int btnFour = 2131230729;
			
			// aapt resource value: 0x7f080006
			public const int btnOne = 2131230726;
			
			// aapt resource value: 0x7f08000e
			public const int btnProjectEnd = 2131230734;
			
			// aapt resource value: 0x7f08000c
			public const int btnProjectStart = 2131230732;
			
			// aapt resource value: 0x7f080008
			public const int btnThree = 2131230728;
			
			// aapt resource value: 0x7f080007
			public const int btnTwo = 2131230727;
			
			// aapt resource value: 0x7f080013
			public const int cboProjectAddResource = 2131230739;
			
			// aapt resource value: 0x7f080016
			public const int cboRole = 2131230742;
			
			// aapt resource value: 0x7f080002
			public const int fraLoginStatusContent = 2131230722;
			
			// aapt resource value: 0x7f080010
			public const int fraProjectEditStatusContent = 2131230736;
			
			// aapt resource value: 0x7f080012
			public const int fraProjectListContent = 2131230738;
			
			// aapt resource value: 0x7f080014
			public const int fraProjectResourceAddStatusContent = 2131230740;
			
			// aapt resource value: 0x7f080018
			public const int fraProjectResourceEditStatusContent = 2131230744;
			
			// aapt resource value: 0x7f08001a
			public const int fraProjectResourceListContent = 2131230746;
			
			// aapt resource value: 0x7f08001d
			public const int fraResourceEditStatusContent = 2131230749;
			
			// aapt resource value: 0x7f08001f
			public const int fraResourceListContent = 2131230751;
			
			// aapt resource value: 0x7f080021
			public const int fraRoleEditStatusContent = 2131230753;
			
			// aapt resource value: 0x7f080005
			public const int fraStatusContent = 2131230725;
			
			// aapt resource value: 0x7f080023
			public const int fraViewListEditContent = 2131230755;
			
			// aapt resource value: 0x7f080025
			public const int lblUser = 2131230757;
			
			// aapt resource value: 0x7f080004
			public const int lstMenuItems = 2131230724;
			
			// aapt resource value: 0x7f080019
			public const int lstProjectResources = 2131230745;
			
			// aapt resource value: 0x7f080011
			public const int lstProjects = 2131230737;
			
			// aapt resource value: 0x7f08001e
			public const int lstResources = 2131230750;
			
			// aapt resource value: 0x7f080022
			public const int lstRoles = 2131230754;
			
			// aapt resource value: 0x7f080001
			public const int txtLoginPassword = 2131230721;
			
			// aapt resource value: 0x7f080000
			public const int txtLoginUserId = 2131230720;
			
			// aapt resource value: 0x7f08000f
			public const int txtProjectDescription = 2131230735;
			
			// aapt resource value: 0x7f08000d
			public const int txtProjectEnded = 2131230733;
			
			// aapt resource value: 0x7f08000a
			public const int txtProjectName = 2131230730;
			
			// aapt resource value: 0x7f08000b
			public const int txtProjectStarted = 2131230731;
			
			// aapt resource value: 0x7f080017
			public const int txtResourceAssigned = 2131230743;
			
			// aapt resource value: 0x7f08001b
			public const int txtResourceFirstName = 2131230747;
			
			// aapt resource value: 0x7f08001c
			public const int txtResourceLastName = 2131230748;
			
			// aapt resource value: 0x7f080015
			public const int txtResourceName = 2131230741;
			
			// aapt resource value: 0x7f080020
			public const int txtRoleName = 2131230752;
			
			// aapt resource value: 0x7f080003
			public const int widget41 = 2131230723;
			
			// aapt resource value: 0x7f080024
			public const int widget49 = 2131230756;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Login = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int MainPage = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Menu = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ProjectDisplay = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int ProjectEdit = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int ProjectListEdit = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int ProjectResourceAdd = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int ProjectResourceEdit = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int ProjectResourceListEdit = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int ResourceEdit = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int ResourceListEdit = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int RoleEdit = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int RoleListEdit = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int Welcome = 2130903053;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int ApplicationName = 2130968576;
			
			// aapt resource value: 0x7f040017
			public const int AssignedField = 2130968599;
			
			// aapt resource value: 0x7f04001c
			public const int ButtonAddNew = 2130968604;
			
			// aapt resource value: 0x7f040021
			public const int ButtonApply = 2130968609;
			
			// aapt resource value: 0x7f04001b
			public const int ButtonBack = 2130968603;
			
			// aapt resource value: 0x7f040022
			public const int ButtonCancel = 2130968610;
			
			// aapt resource value: 0x7f04001d
			public const int ButtonDelete = 2130968605;
			
			// aapt resource value: 0x7f04001a
			public const int ButtonLogin = 2130968602;
			
			// aapt resource value: 0x7f040020
			public const int ButtonOk = 2130968608;
			
			// aapt resource value: 0x7f04001e
			public const int ButtonRoles = 2130968606;
			
			// aapt resource value: 0x7f04001f
			public const int ButtonSave = 2130968607;
			
			// aapt resource value: 0x7f040009
			public const int DataPortalURL = 2130968585;
			
			// aapt resource value: 0x7f040014
			public const int DescriptionField = 2130968596;
			
			// aapt resource value: 0x7f040013
			public const int EndedField = 2130968595;
			
			// aapt resource value: 0x7f040008
			public const int Error = 2130968584;
			
			// aapt resource value: 0x7f040018
			public const int FirstNameField = 2130968600;
			
			// aapt resource value: 0x7f040019
			public const int LastNameField = 2130968601;
			
			// aapt resource value: 0x7f04000c
			public const int Login = 2130968588;
			
			// aapt resource value: 0x7f04000e
			public const int LoginDefault = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public const int LoginPassword = 2130968591;
			
			// aapt resource value: 0x7f04000d
			public const int LoginUserName = 2130968589;
			
			// aapt resource value: 0x7f040010
			public const int Logout = 2130968592;
			
			// aapt resource value: 0x7f040029
			public const int MenuAssignments = 2130968617;
			
			// aapt resource value: 0x7f040028
			public const int MenuProjectResources = 2130968616;
			
			// aapt resource value: 0x7f040026
			public const int MenuProjects = 2130968614;
			
			// aapt resource value: 0x7f040027
			public const int MenuResources = 2130968615;
			
			// aapt resource value: 0x7f040025
			public const int MenuWelcome = 2130968613;
			
			// aapt resource value: 0x7f040024
			public const int MessageChangesSaved = 2130968612;
			
			// aapt resource value: 0x7f040023
			public const int MessageValidatingLogin = 2130968611;
			
			// aapt resource value: 0x7f040011
			public const int NameField = 2130968593;
			
			// aapt resource value: 0x7f040002
			public const int ProjectEdit = 2130968578;
			
			// aapt resource value: 0x7f040006
			public const int ProjectResourceAdd = 2130968582;
			
			// aapt resource value: 0x7f040005
			public const int ProjectResourceEdit = 2130968581;
			
			// aapt resource value: 0x7f040004
			public const int ResourceEdit = 2130968580;
			
			// aapt resource value: 0x7f040015
			public const int ResourceField = 2130968597;
			
			// aapt resource value: 0x7f040003
			public const int RoleEdit = 2130968579;
			
			// aapt resource value: 0x7f040016
			public const int RoleField = 2130968598;
			
			// aapt resource value: 0x7f040001
			public const int Roles = 2130968577;
			
			// aapt resource value: 0x7f040012
			public const int StartedField = 2130968594;
			
			// aapt resource value: 0x7f04000a
			public const int Welcome = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int WelcomeCreated = 2130968587;
			
			// aapt resource value: 0x7f04002a
			public const int elipse = 2130968618;
			
			// aapt resource value: 0x7f040007
			public const int phonetextextralargestyle = 2130968583;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int Theme_Splash = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
