<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CslaVersion>10.2.0</CslaVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Csla" Version="$(CslaVersion)" />
    <PackageVersion Include="Csla.Generator.AutoImplementProperties.CSharp" Version="$(CslaVersion)" />
    <PackageVersion Include="Csla.AspNetCore" Version="$(CslaVersion)" />
    <PackageVersion Include="Csla.Windows.Forms" Version="$(CslaVersion)" />

    <PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="10.0.0" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.0" />
  </ItemGroup>
</Project>