<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>..\..\Csla\CslaKey.snk</AssemblyOriginatorKeyFile>
    <RootNamespace>Csla.Testing.Tests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="MSTest.TestAdapter" Version="3.9.1" />
    <PackageReference Include="MSTest.TestFramework" Version="3.9.1" />
    <PackageReference Include="AwesomeAssertions" Version="8.2.0" />
    <PackageReference Include="AwesomeAssertions.Analyzers" Version="8.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Csla.Testing\Csla.Testing.csproj" />
    <ProjectReference Include="..\..\Csla\Csla.csproj" />
    <ProjectReference Include="..\Csla.TestHelpers\Csla.TestHelpers.csproj" />
  </ItemGroup>

</Project>
