var searchData=
[
  ['namevaluelistbase_0',['NameValueListBase',['../class_csla_1_1_name_value_list_base.html',1,'Csla']]],
  ['namevaluelistbase_3c_20int_2c_20string_20_3e_1',['NameValueListBase&lt; int, string &gt;',['../class_csla_1_1_name_value_list_base.html',1,'Csla']]],
  ['namevaluelistbase_3c_20int32_2c_20string_20_3e_2',['NameValueListBase&lt; Int32, string &gt;',['../class_csla_1_1_name_value_list_base.html',1,'Csla']]],
  ['namevaluelistobj_3',['NameValueListObj',['../class_csla_1_1_test_1_1_basic_1_1_name_value_list_obj.html',1,'Csla::Test::Basic']]],
  ['namevaluelisttests_4',['NameValueListTests',['../classcslalighttest_1_1_name_value_list_1_1_name_value_list_tests.html',1,'cslalighttest::NameValueList']]],
  ['namevaluepair_5',['NameValuePair',['../class_csla_1_1_name_value_list_base_1_1_name_value_pair.html',1,'Csla::NameValueListBase']]],
  ['nestedclass_6',['NestedClass',['../class_csla_1_1_analyzers_1_1_integration_tests_1_1_outer_class_1_1_nested_class.html',1,'Csla::Analyzers::IntegrationTests::OuterClass']]],
  ['nestingpoco_7',['NestingPOCO',['../class_csla_1_1_generators_1_1_c_sharp_1_1_test_objects_1_1_nesting_p_o_c_o.html',1,'Csla::Generators::CSharp::TestObjects']]],
  ['nestingpoco2_8',['NestingPOCO2',['../class_csla_1_1_generators_1_1_c_sharp_1_1_test_objects_1_1_nesting_p_o_c_o2.html',1,'Csla::Generators::CSharp::TestObjects']]],
  ['nestingpoco2tests_9',['NestingPOCO2Tests',['../class_csla_1_1_generators_1_1_c_sharp_1_1_tests_1_1_nesting_p_o_c_o2_tests.html',1,'Csla::Generators::CSharp::Tests']]],
  ['nestingpocotests_10',['NestingPOCOTests',['../class_csla_1_1_generators_1_1_c_sharp_1_1_tests_1_1_nesting_p_o_c_o_tests.html',1,'Csla::Generators::CSharp::Tests']]],
  ['netdatacontractserializerwrapper_11',['NetDataContractSerializerWrapper',['../class_csla_1_1_serialization_1_1_net_data_contract_serializer_wrapper.html',1,'Csla::Serialization']]],
  ['noerrorroot_12',['NoErrorRoot',['../class_csla_1_1_test_1_1_validation_rules_1_1_no_error_root.html',1,'Csla::Test::ValidationRules']]],
  ['noncslachild_13',['NonCslaChild',['../class_csla_1_1_test_1_1_serialization_1_1_non_csla_child.html',1,'Csla::Test::Serialization']]],
  ['nonpublic1_14',['NonPublic1',['../class_csla_1_1_test_1_1_method_caller_1_1_create_constructor_tests_1_1_non_public1.html',1,'Csla::Test::MethodCaller::CreateConstructorTests']]],
  ['nonserializableeventhandler_15',['nonSerializableEventHandler',['../class_csla_1_1_test_1_1_serialization_1_1non_serializable_event_handler.html',1,'Csla::Test::Serialization']]],
  ['nonserializedclass_16',['NonSerializedClass',['../class_csla_1_1_test_1_1_serialization_1_1_non_serialized_class.html',1,'Csla::Test::Serialization']]],
  ['nonserializedobject_17',['NonSerializedObject',['../class_csla_1_1_analyzers_1_1_integration_tests_1_1_non_serialized_object.html',1,'Csla::Analyzers::IntegrationTests']]],
  ['notastereotype_18',['NotAStereotype',['../class_csla_1_1_analyzers_1_1_integration_tests_1_1_not_a_stereotype.html',1,'Csla::Analyzers::IntegrationTests']]],
  ['notundoableattribute_19',['NotUndoableAttribute',['../class_csla_1_1_not_undoable_attribute.html',1,'Csla']]],
  ['nullableentity_20',['NullableEntity',['../class_csla_1_1_ios_1_1_test_1_1_nullable_entity.html',1,'Csla::Ios::Test']]],
  ['nullableobject_21',['NullableObject',['../class_csla_1_1_test_1_1_nullable_1_1_nullable_object.html',1,'Csla::Test::Nullable']]],
  ['nullabletests_22',['NullableTests',['../class_csla_1_1_ios_1_1_test_1_1_nullable_tests.html',1,'Csla.Ios.Test.NullableTests'],['../class_csla_1_1_test_1_1_nullable_1_1_nullable_tests.html',1,'Csla.Test.Nullable.NullableTests']]],
  ['nullauthorizer_23',['NullAuthorizer',['../class_csla_1_1_server_1_1_null_authorizer.html',1,'Csla::Server']]],
  ['nullcriteria_24',['NullCriteria',['../class_csla_1_1_server_1_1_null_criteria.html',1,'Csla::Server']]],
  ['nulldashboard_25',['NullDashboard',['../class_csla_1_1_server_1_1_dashboard_1_1_null_dashboard.html',1,'Csla::Server::Dashboard']]],
  ['nullplaceholder_26',['NullPlaceholder',['../class_csla_1_1_serialization_1_1_mobile_1_1_null_placeholder.html',1,'Csla::Serialization::Mobile']]]
];
