.TH "C:/Users/korye/source/repos/csla/Source/Csla.Xaml.Xamarin/obj/Release/netstandard2.0/.NETStandard,Version=v2.0.AssemblyAttributes.cs" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/korye/source/repos/csla/Source/Csla.Xaml.Xamarin/obj/Release/netstandard2.0/.NETStandard,Version=v2.0.AssemblyAttributes.cs
.SH SYNOPSIS
.br
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
