.TH "AppDomainProxy.cs" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AppDomainProxy.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCsla\&.Testing\&.Business\&.TestProxies\&.AppDomainProxy\fP"
.br
.RI "This is a test proxy used to test any type of calls that have to be send accross to a different AppDomain (non local styff) "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBCsla\fP"
.br
.ti -1c
.RI "namespace \fBCsla\&.Testing\fP"
.br
.ti -1c
.RI "namespace \fBCsla\&.Testing\&.Business\fP"
.br
.ti -1c
.RI "namespace \fBCsla\&.Testing\&.Business\&.TestProxies\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "using \fBDataPortalContext\fP = \fBCsla\&.Server\&.DataPortalContext\fP"
.br
.ti -1c
.RI "using \fBIDataPortalServer\fP = \fBCsla\&.Server\&.IDataPortalServer\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "using \fBDataPortalContext\fP =  \fBCsla\&.Server\&.DataPortalContext\fP"

.PP
Definition at line 13 of file AppDomainProxy\&.cs\&.
.SS "using \fBIDataPortalServer\fP =  \fBCsla\&.Server\&.IDataPortalServer\fP"

.PP
Definition at line 14 of file AppDomainProxy\&.cs\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
