.TH "C:/Users/korye/source/repos/csla/Source/Csla/Core/AsyncFactoryDelegates.cs" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/korye/source/repos/csla/Source/Csla/Core/AsyncFactoryDelegates.cs
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBCsla\fP"
.br
.ti -1c
.RI "namespace \fBCsla\&.Core\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "delegate void \fBCsla\&.Core\&.AsyncFactoryDelegate< R >\fP (EventHandler< DataPortalResult< R >> completed)"
.br
.RI "Delegate for an asynchronous business object factory method with n parameters\&. "
.ti -1c
.RI "delegate void \fBCsla\&.Core\&.AsyncFactoryDelegate< T, R >\fP (T arg, EventHandler< DataPortalResult< R >> completed)"
.br
.RI "Delegate for an asynchronous business object factory method with n parameters\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
