.TH "AuthorizationActions.cs" 3 "Thu Jul 22 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AuthorizationActions.cs
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBCsla\fP"
.br
.ti -1c
.RI "namespace \fBCsla\&.Rules\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum class \fBCsla\&.Rules\&.AuthorizationActions\fP { \fBCsla\&.Rules\&.WriteProperty\fP, \fBCsla\&.Rules\&.ReadProperty\fP, \fBCsla\&.Rules\&.ExecuteMethod\fP, \fBCsla\&.Rules\&.CreateObject\fP, \fBCsla\&.Rules\&.GetObject\fP, \fBCsla\&.Rules\&.EditObject\fP, \fBCsla\&.Rules\&.DeleteObject\fP }"
.br
.RI "Authorization actions\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
