.TH "AuthTests.cs" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AuthTests.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCsla\&.Test\&.Authorization\&.AuthTests\fP"
.br
.ti -1c
.RI "class \fBCsla\&.Test\&.Authorization\&.PerTypeAuthDPActivator\fP"
.br
.ti -1c
.RI "interface \fBCsla\&.Test\&.Authorization\&.IPerTypeAuthRoot\fP"
.br
.ti -1c
.RI "class \fBCsla\&.Test\&.Authorization\&.PerTypeAuthRoot\fP"
.br
.ti -1c
.RI "class \fBCsla\&.Test\&.Authorization\&.RootList\fP"
.br
.ti -1c
.RI "class \fBCsla\&.Test\&.Authorization\&.ChildItem\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBCsla\fP"
.br
.ti -1c
.RI "namespace \fBCsla\&.Test\fP"
.br
.ti -1c
.RI "namespace \fBCsla\&.Test\&.Authorization\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
