.TH "BackgroundWorkerTests.cs" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BackgroundWorkerTests.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCsla\&.Test\&.Threading\&.BackgroundWorkerTests\fP"
.br
.RI "This is a test class for BackgroundWorkerTest and is intended to contain all BackgroundWorkerTest Unit Tests /summary> "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBCsla\fP"
.br
.ti -1c
.RI "namespace \fBCsla\&.Test\fP"
.br
.ti -1c
.RI "namespace \fBCsla\&.Test\&.Threading\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "using \fBBackgroundWorker\fP = \fBCsla\&.Threading\&.BackgroundWorker\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "using \fBBackgroundWorker\fP =  \fBCsla\&.Threading\&.BackgroundWorker\fP"

.PP
Definition at line 18 of file BackgroundWorkerTests\&.cs\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
