.TH "BindingSourceRefresh.cs" 3 "Thu Jul 22 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BindingSourceRefresh.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCsla\&.Windows\&.BindingSourceRefresh\fP"
.br
.RI "\fBBindingSourceRefresh\fP contains functionality for refreshing the data bound to controls on Host as well as a mechinism for catching data binding errors that occur in Host\&. "
.ti -1c
.RI "class \fBCsla\&.Windows\&.BindingErrorEventArgs\fP"
.br
.RI "\fBBindingErrorEventArgs\fP defines the event arguments for reporting a data binding error due to a exception\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBCsla\fP"
.br
.ti -1c
.RI "namespace \fBCsla\&.Windows\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "delegate void \fBCsla\&.Windows\&.BindingErrorEventHandler\fP (object sender, BindingErrorEventArgs e)"
.br
.RI "BindingErrorEventHandler delegates is the event handling definition for handling data binding errors that occurred due to exceptions\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
