.TH "C:/Users/korye/source/repos/csla/Source/Csla.test/Silverlight/Server/EditableChildTests Directory Reference" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/korye/source/repos/csla/Source/Csla.test/Silverlight/Server/EditableChildTests Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBGrandChild\&.cs\fP"
.br
.ti -1c
.RI "file \fBGrandChild\&.partial\&.cs\fP"
.br
.ti -1c
.RI "file \fBGrandChildList\&.cs\fP"
.br
.ti -1c
.RI "file \fBGrandChildList\&.partial\&.cs\fP"
.br
.ti -1c
.RI "file \fBMockEditableChild\&.cs\fP"
.br
.ti -1c
.RI "file \fBMockEditableChild\&.partial\&.cs\fP"
.br
.ti -1c
.RI "file \fBMockList\&.cs\fP"
.br
.ti -1c
.RI "file \fBMockList\&.partial\&.cs\fP"
.br
.in -1c
