.TH "netcoreapp3.1 Directory Reference" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
netcoreapp3.1 Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBCsla\&.AspNetCore\&.NetCore3\&.0/obj/Release/netcoreapp3\&.1/\&.NETCoreApp,Version=v3\&.1\&.AssemblyAttributes\&.cs\fP"
.br
.ti -1c
.RI "file \fBRelease/netcoreapp3\&.1/Csla\&.AspNetCore\&.NetCore3\&.0\&.AssemblyInfo\&.cs\fP"
.br
.in -1c
