.TH "Csla.Data.EF6 Directory Reference" 3 "Thu Jul 22 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Data.EF6 Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBCsla\&.Data\&.EF6/DbContextManager\&.cs\fP"
.br
.ti -1c
.RI "file \fBCsla\&.Data\&.EF6/ObjectContextManager\&.cs\fP"
.br
.in -1c
