.TH "Serialization Directory Reference" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Serialization Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBClaimsPrincipalTests\&.cs\fP"
.br
.ti -1c
.RI "file \fBcsla\&.netcore\&.test/Serialization/SerializationTests\&.cs\fP"
.br
.in -1c
