.TH "Csla.Windows.Shared Directory Reference" 3 "Thu Jul 22 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Windows.Shared Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBCsla\&.Windows\&.Shared/ApplicationContextManager\&.cs\fP"
.br
.ti -1c
.RI "file \fBBindingSourceHelper\&.cs\fP"
.br
.ti -1c
.RI "file \fBBindingSourceNode\&.cs\fP"
.br
.ti -1c
.RI "file \fBBindingSourceRefresh\&.cs\fP"
.br
.ti -1c
.RI "file \fBCsla\&.Windows\&.Shared/BusyAnimation\&.cs\fP"
.br
.ti -1c
.RI "file \fBBusyAnimation\&.designer\&.cs\fP"
.br
.ti -1c
.RI "file \fBCsla\&.Windows\&.Shared/ConfigurationExtensions\&.cs\fP"
.br
.ti -1c
.RI "file \fBCslaActionCancelEventArgs\&.cs\fP"
.br
.ti -1c
.RI "file \fBCslaActionEventArgs\&.cs\fP"
.br
.ti -1c
.RI "file \fBCslaActionExtender\&.cs\fP"
.br
.ti -1c
.RI "file \fBCslaActionExtenderProperties\&.cs\fP"
.br
.ti -1c
.RI "file \fBCslaActionExtenderToolStrip\&.cs\fP"
.br
.ti -1c
.RI "file \fBEnums\&.cs\fP"
.br
.ti -1c
.RI "file \fBErrorEncounteredEventArgs\&.cs\fP"
.br
.ti -1c
.RI "file \fBHasBrokenRulesEventArgs\&.cs\fP"
.br
.ti -1c
.RI "file \fBHostPropertyAttribute\&.cs\fP"
.br
.ti -1c
.RI "file \fBObjectSaveException\&.cs\fP"
.br
.ti -1c
.RI "file \fBReadWriteAuthorization\&.cs\fP"
.br
.in -1c
