.TH "C:/Users/korye/source/repos/csla/Source/Csla/Core Directory Reference" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/korye/source/repos/csla/Source/Csla/Core Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBFieldManager\fP"
.br
.ti -1c
.RI "directory \fBLoadManager\fP"
.br
.ti -1c
.RI "directory \fBTypeConverters\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBAddedNewEventArgs\&.cs\fP"
.br
.ti -1c
.RI "file \fBApplicationContextManager\&.cs\fP"
.br
.ti -1c
.RI "file \fBApplicationContextManagerStatic\&.cs\fP"
.br
.ti -1c
.RI "file \fBApplicationContextManagerTls\&.cs\fP"
.br
.ti -1c
.RI "file \fBAsyncFactoryDelegates\&.cs\fP"
.br
.ti -1c
.RI "file \fBBindableBase\&.cs\fP"
.br
.ti -1c
.RI "file \fBBusinessBase\&.cs\fP"
.br
.ti -1c
.RI "file \fBBusyChangedEventArgs\&.cs\fP"
.br
.ti -1c
.RI "file \fBChildChangedEventArgs\&.cs\fP"
.br
.ti -1c
.RI "file \fBContextDictionary\&.cs\fP"
.br
.ti -1c
.RI "file \fBErrorEventArgs\&.cs\fP"
.br
.ti -1c
.RI "file \fBExtendedBindingList\&.cs\fP"
.br
.ti -1c
.RI "file \fBGraphMerger\&.cs\fP"
.br
.ti -1c
.RI "file \fBIBusinessObject\&.cs\fP"
.br
.ti -1c
.RI "file \fBICheckRules\&.cs\fP"
.br
.ti -1c
.RI "file \fBICommandObject\&.cs\fP"
.br
.ti -1c
.RI "file \fBIContextManager\&.cs\fP"
.br
.ti -1c
.RI "file \fBIdentityManager\&.cs\fP"
.br
.ti -1c
.RI "file \fBIEditableBusinessObject\&.cs\fP"
.br
.ti -1c
.RI "file \fBIEditableCollection\&.cs\fP"
.br
.ti -1c
.RI "file \fBIExtendedBindingList\&.cs\fP"
.br
.ti -1c
.RI "file \fBIManageProperties\&.cs\fP"
.br
.ti -1c
.RI "file \fBIMemberInfo\&.cs\fP"
.br
.ti -1c
.RI "file \fBINotifyBusy\&.cs\fP"
.br
.ti -1c
.RI "file \fBINotifyChildChanged\&.cs\fP"
.br
.ti -1c
.RI "file \fBINotifyUnhandledAsyncException\&.cs\fP"
.br
.ti -1c
.RI "file \fBInvalidQueryExpression\&.cs\fP"
.br
.ti -1c
.RI "file \fBIObservableBindingList\&.cs\fP"
.br
.ti -1c
.RI "file \fBIParent\&.cs\fP"
.br
.ti -1c
.RI "file \fBIPropertyInfo\&.cs\fP"
.br
.ti -1c
.RI "file \fBIPropertyInfoFactory\&.cs\fP"
.br
.ti -1c
.RI "file \fBIReadOnlyBindingList\&.cs\fP"
.br
.ti -1c
.RI "file \fBIReadOnlyCollection\&.cs\fP"
.br
.ti -1c
.RI "file \fBIReadOnlyObject\&.cs\fP"
.br
.ti -1c
.RI "file \fBIReportTotalRowCount\&.cs\fP"
.br
.ti -1c
.RI "file \fBISavable\&.cs\fP"
.br
.ti -1c
.RI "file \fBISavableT\&.cs\fP"
.br
.ti -1c
.RI "file \fBISmartField\&.cs\fP"
.br
.ti -1c
.RI "file \fBISupportUndo\&.cs\fP"
.br
.ti -1c
.RI "file \fBITrackStatus\&.cs\fP"
.br
.ti -1c
.RI "file \fBIUndoableObject\&.cs\fP"
.br
.ti -1c
.RI "file \fBManagedObjectBase\&.cs\fP"
.br
.ti -1c
.RI "file \fBMetaPropertyChangedEventArgs\&.cs\fP"
.br
.ti -1c
.RI "file \fBMobileBindingList\&.cs\fP"
.br
.ti -1c
.RI "file \fBMobileDictionary\&.cs\fP"
.br
.ti -1c
.RI "file \fBMobileList\&.cs\fP"
.br
.ti -1c
.RI "file \fBMobileObject\&.cs\fP"
.br
.ti -1c
.RI "file \fBMobileObservableCollection\&.cs\fP"
.br
.ti -1c
.RI "file \fBObjectCloner\&.cs\fP"
.br
.ti -1c
.RI "file \fBObservableBindingList\&.cs\fP"
.br
.ti -1c
.RI "file \fBReadOnlyBindingList\&.cs\fP"
.br
.ti -1c
.RI "file \fBReadOnlyObservableBindingList\&.cs\fP"
.br
.ti -1c
.RI "file \fBRemovingItemEventArgs\&.cs\fP"
.br
.ti -1c
.RI "file \fBSavedEventArgs\&.cs\fP"
.br
.ti -1c
.RI "file \fBStateMode\&.cs\fP"
.br
.ti -1c
.RI "file \fBTypeSystem\&.cs\fP"
.br
.ti -1c
.RI "file \fBUndoableBase\&.cs\fP"
.br
.ti -1c
.RI "file \fBUndoableHandler\&.cs\fP"
.br
.ti -1c
.RI "file \fBUndoException\&.cs\fP"
.br
.in -1c
