.TH "csla.netcore.test Directory Reference" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csla.netcore.test Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBBasic\fP"
.br
.ti -1c
.RI "directory \fBBasicModern\fP"
.br
.ti -1c
.RI "directory \fBConfiguration\fP"
.br
.ti -1c
.RI "directory \fBDataBinding\fP"
.br
.ti -1c
.RI "directory \fBDataPortal\fP"
.br
.ti -1c
.RI "directory \fBobj\fP"
.br
.ti -1c
.RI "directory \fBSerialization\fP"
.br
.in -1c
