.TH "Mobile Directory Reference" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Mobile Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBAssemblyNameTranslator\&.cs\fP"
.br
.ti -1c
.RI "file \fBCslaBinaryReader\&.cs\fP"
.br
.ti -1c
.RI "file \fBCslaBinaryWriter\&.cs\fP"
.br
.ti -1c
.RI "file \fBCslaKnownTypes\&.cs\fP"
.br
.ti -1c
.RI "file \fBCslaLegacyBinaryReader\&.cs\fP"
.br
.ti -1c
.RI "file \fBCslaLegacyBinaryWriter\&.cs\fP"
.br
.ti -1c
.RI "file \fBCslaNonClosingBinaryWriter\&.cs\fP"
.br
.ti -1c
.RI "file \fBCslaReaderWriterFactory\&.cs\fP"
.br
.ti -1c
.RI "file \fBCslaXmlBinaryReader\&.cs\fP"
.br
.ti -1c
.RI "file \fBCslaXmlBinaryWriter\&.cs\fP"
.br
.ti -1c
.RI "file \fBCslaXmlReader\&.cs\fP"
.br
.ti -1c
.RI "file \fBCslaXmlWriter\&.cs\fP"
.br
.ti -1c
.RI "file \fBDictionaryCheckResult\&.cs\fP"
.br
.ti -1c
.RI "file \fBICslaReader\&.cs\fP"
.br
.ti -1c
.RI "file \fBICslaWriter\&.cs\fP"
.br
.ti -1c
.RI "file \fBIMobileList\&.cs\fP"
.br
.ti -1c
.RI "file \fBIMobileObject\&.cs\fP"
.br
.ti -1c
.RI "file \fBISerializationNotification\&.cs\fP"
.br
.ti -1c
.RI "file \fBMobileFormatter\&.cs\fP"
.br
.ti -1c
.RI "file \fBNullPlaceholder\&.cs\fP"
.br
.ti -1c
.RI "file \fBReferenceComparer\&.cs\fP"
.br
.ti -1c
.RI "file \fBSerializationInfo\&.cs\fP"
.br
.in -1c
