.TH "DataPortalChild Directory Reference" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DataPortalChild Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBCsla\&.test/DataPortalChild/Child\&.cs\fP"
.br
.ti -1c
.RI "file \fBCsla\&.test/DataPortalChild/ChildList\&.cs\fP"
.br
.ti -1c
.RI "file \fBDataPortalChildTests\&.cs\fP"
.br
.ti -1c
.RI "file \fBCsla\&.test/DataPortalChild/Root\&.cs\fP"
.br
.in -1c
