.TH "PropertyGetSet Directory Reference" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PropertyGetSet Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBBadGetSet\&.cs\fP"
.br
.ti -1c
.RI "file \fBCsla\&.test/PropertyGetSet/ChildList\&.cs\fP"
.br
.ti -1c
.RI "file \fBEditableGetSet\&.cs\fP"
.br
.ti -1c
.RI "file \fBEditableGetSetBase\&.cs\fP"
.br
.ti -1c
.RI "file \fBEditableGetSetRuleValidation\&.cs\fP"
.br
.ti -1c
.RI "file \fBEditableGetSetRuleValidationTests\&.cs\fP"
.br
.ti -1c
.RI "file \fBEditableGetSetTopBase\&.cs\fP"
.br
.ti -1c
.RI "file \fBPropertyGetSetTests\&.cs\fP"
.br
.in -1c
