.TH "DataPortalClient Directory Reference" 3 "Thu Jul 22 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DataPortalClient Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBDataPortalProxy\&.cs\fP"
.br
.ti -1c
.RI "file \fBDataPortalProxyDescriptor\&.cs\fP"
.br
.ti -1c
.RI "file \fBDataPortalProxyFactory\&.cs\fP"
.br
.ti -1c
.RI "file \fBHttpCompressionProxy\&.cs\fP"
.br
.ti -1c
.RI "file \fBHttpProxy\&.cs\fP"
.br
.ti -1c
.RI "file \fBIDataPortalProxy\&.cs\fP"
.br
.ti -1c
.RI "file \fBIDataPortalProxyFactory\&.cs\fP"
.br
.ti -1c
.RI "file \fBDataPortalClient/IWcfPortal\&.cs\fP"
.br
.ti -1c
.RI "file \fBLocalProxy\&.cs\fP"
.br
.ti -1c
.RI "file \fBPrimitiveCriteria\&.cs\fP"
.br
.ti -1c
.RI "file \fBWcfProxy\&.cs\fP"
.br
.in -1c
