.TH "C:/Users/korye/source/repos/csla/Source/Csla.Web.Net4.6 Directory Reference" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/korye/source/repos/csla/Source/Csla.Web.Net4.6 Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBProperties\fP"
.br
.in -1c
