.TH "C:/Users/korye/source/repos/csla/Source/Csla/Security Directory Reference" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/korye/source/repos/csla/Source/Csla/Security Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBCslaClaimsPrincipal\&.cs\fP"
.br
.ti -1c
.RI "file \fBIAuthorizeReadWrite\&.cs\fP"
.br
.ti -1c
.RI "file \fBICheckRoles\&.cs\fP"
.br
.ti -1c
.RI "file \fBICslaIdentity\&.cs\fP"
.br
.ti -1c
.RI "file \fBICslaPrincipal\&.cs\fP"
.br
.ti -1c
.RI "file \fBNoAccessBehavior\&.cs\fP"
.br
.ti -1c
.RI "file \fBPrincipalCache\&.cs\fP"
.br
.ti -1c
.RI "file \fBSecurityException\&.cs\fP"
.br
.ti -1c
.RI "file \fBUsernameCriteria\&.cs\fP"
.br
.in -1c
