.TH "C:/Users/korye/source/repos/csla/Source/csla.netcore.test/Configuration Directory Reference" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/korye/source/repos/csla/Source/csla.netcore.test/Configuration Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBFluentConfigTests\&.cs\fP"
.br
.ti -1c
.RI "file \fBReadConfigFromDotnetCoreSubsystemTests\&.cs\fP"
.br
.in -1c
