.TH "obj Directory Reference" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
obj Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBDebug\fP"
.br
.ti -1c
.RI "directory \fBRelease\fP"
.br
.ti -1c
.RI "directory \fBTesting\fP"
.br
.in -1c
