.TH "GraphMerge Directory Reference" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GraphMerge Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBGraphMergerTests\&.cs\fP"
.br
.ti -1c
.RI "file \fBIdentityTests\&.cs\fP"
.br
.ti -1c
.RI "file \fBTestClasses\&.cs\fP"
.br
.in -1c
