.TH "Release Directory Reference" 3 "Thu Jul 22 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Release Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBCsla\&.Validation\&.Uwp/obj/x86/Release/\&.NETCore,Version=v5\&.0\&.AssemblyAttributes\&.cs\fP"
.br
.in -1c
