.TH "Mobile Directory Reference" 3 "Thu Jul 22 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Mobile Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBMobile/CriteriaRequest\&.cs\fP"
.br
.ti -1c
.RI "file \fBIMobileFactoryLoader\&.cs\fP"
.br
.ti -1c
.RI "file \fBIMobileRequest\&.cs\fP"
.br
.ti -1c
.RI "file \fBServer/Hosts/Mobile/IWcfPortal\&.cs\fP"
.br
.ti -1c
.RI "file \fBMobileCriteriaRequest\&.cs\fP"
.br
.ti -1c
.RI "file \fBMobileFactoryLoader\&.cs\fP"
.br
.ti -1c
.RI "file \fBMobileRequestProcessor\&.cs\fP"
.br
.ti -1c
.RI "file \fBMobileResponse\&.cs\fP"
.br
.ti -1c
.RI "file \fBMobileUpdateRequest\&.cs\fP"
.br
.ti -1c
.RI "file \fBMobile/UpdateRequest\&.cs\fP"
.br
.ti -1c
.RI "file \fBWcfErrorInfo\&.cs\fP"
.br
.ti -1c
.RI "file \fBMobile/WcfPortal\&.cs\fP"
.br
.ti -1c
.RI "file \fBMobile/WcfResponse\&.cs\fP"
.br
.in -1c
