.TH "Debug Directory Reference" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Debug Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBCsla\&.Validation\&.Test/obj/Debug/\&.NETFramework,Version=v4\&.6\&.1\&.AssemblyAttributes\&.cs\fP"
.br
.in -1c
