.TH "Authentication Directory Reference" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Authentication Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBCslaAuthenticationStateProvider\&.cs\fP"
.br
.ti -1c
.RI "file \fBCslaUserService\&.cs\fP"
.br
.in -1c
