.TH "C:/Users/korye/source/repos/csla/Source/Csla.test/Serialization Directory Reference" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/korye/source/repos/csla/Source/Csla.test/Serialization Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBBinaryReaderWriterTestClass\&.cs\fP"
.br
.ti -1c
.RI "file \fBCslaClaimsPrincipalSerializationTests\&.cs\fP"
.br
.ti -1c
.RI "file \fBDCRoot\&.cs\fP"
.br
.ti -1c
.RI "file \fBnonSerializableEventHandler\&.cs\fP"
.br
.ti -1c
.RI "file \fBNonSerializedClass\&.cs\fP"
.br
.ti -1c
.RI "file \fBOverrideSerializationRoot\&.cs\fP"
.br
.ti -1c
.RI "file \fBSerializationRoot\&.cs\fP"
.br
.ti -1c
.RI "file \fBSerializationTests\&.cs\fP"
.br
.ti -1c
.RI "file \fBTestEventSink\&.cs\fP"
.br
.in -1c
