.TH "netstandard2.0 Directory Reference" 3 "Thu Jul 22 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
netstandard2.0 Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBCsla\&.Data\&.SqlClient\&.Fx/obj/Debug/netstandard2\&.0/\&.NETStandard,Version=v2\&.0\&.AssemblyAttributes\&.cs\fP"
.br
.ti -1c
.RI "file \fBDebug/netstandard2\&.0/Csla\&.Data\&.SqlClient\&.Fx\&.AssemblyInfo\&.cs\fP"
.br
.in -1c
