.TH "ReadOnlyTests Directory Reference" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ReadOnlyTests Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBSilverlight/Server/ReadOnlyTests/ReadOnlyPerson\&.cs\fP"
.br
.ti -1c
.RI "file \fBReadOnlyPerson\&.partial\&.cs\fP"
.br
.ti -1c
.RI "file \fBServer/ReadOnlyTests/ReadOnlyPersonList\&.cs\fP"
.br
.in -1c
