.TH "Csla.Data.SqlClient.Fx Directory Reference" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Data.SqlClient.Fx Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBobj\fP"
.br
.ti -1c
.RI "directory \fBProperties\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBCsla\&.Data\&.SqlClient\&.Fx/ConnectionManager\&.cs\fP"
.br
.ti -1c
.RI "file \fBSafeSqlDataReader\&.cs\fP"
.br
.in -1c
