.TH "Csla.Blazor Directory Reference" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Blazor Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBClient\fP"
.br
.ti -1c
.RI "directory \fBProperties\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBCsla\&.Blazor/ConfigurationExtensions\&.cs\fP"
.br
.ti -1c
.RI "file \fBCsla\&.Blazor/CslaPermissionRequirement\&.cs\fP"
.br
.ti -1c
.RI "file \fBCslaPermissionsPolicyProvider\&.cs\fP"
.br
.ti -1c
.RI "file \fBCslaPolicy\&.cs\fP"
.br
.ti -1c
.RI "file \fBCslaValidationMessages\&.razor\&.cs\fP"
.br
.ti -1c
.RI "file \fBCslaValidator\&.cs\fP"
.br
.ti -1c
.RI "file \fBEditContextCslaExtensions\&.cs\fP"
.br
.ti -1c
.RI "file \fBCsla\&.Blazor/HasPermissionAttribute\&.cs\fP"
.br
.ti -1c
.RI "file \fBHasPermissionHandler\&.cs\fP"
.br
.ti -1c
.RI "file \fBCsla\&.Blazor/IPropertyInfo\&.cs\fP"
.br
.ti -1c
.RI "file \fBCsla\&.Blazor/PropertyInfo\&.cs\fP"
.br
.ti -1c
.RI "file \fBCsla\&.Blazor/ViewModel\&.cs\fP"
.br
.in -1c
