.TH "C:/Users/korye/source/repos/csla/Source/Csla.test/Silverlight/Server Directory Reference" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/korye/source/repos/csla/Source/Csla.test/Silverlight/Server Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBApplicationContext\fP"
.br
.ti -1c
.RI "directory \fBBusyStatus\fP"
.br
.ti -1c
.RI "directory \fBCommandBase\fP"
.br
.ti -1c
.RI "directory \fBCslaDataProvider\fP"
.br
.ti -1c
.RI "directory \fBDataPortal\fP"
.br
.ti -1c
.RI "directory \fBEditableChildTests\fP"
.br
.ti -1c
.RI "directory \fBEditableRootListTests\fP"
.br
.ti -1c
.RI "directory \fBEditableRootTests\fP"
.br
.ti -1c
.RI "directory \fBNameValueList\fP"
.br
.ti -1c
.RI "directory \fBobj\fP"
.br
.ti -1c
.RI "directory \fBObjectFactory\fP"
.br
.ti -1c
.RI "directory \fBProperties\fP"
.br
.ti -1c
.RI "directory \fBReadOnlyTests\fP"
.br
.ti -1c
.RI "directory \fBTestProxies\fP"
.br
.ti -1c
.RI "directory \fBValidation\fP"
.br
.ti -1c
.RI "directory \fBViewModelTests\fP"
.br
.in -1c
