.TH "Windows Directory Reference" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Windows Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBActionExtenderTests\&.cs\fP"
.br
.ti -1c
.RI "file \fBBindingRefreshTests\&.cs\fP"
.br
.ti -1c
.RI "file \fBEditablePerson\&.cs\fP"
.br
.ti -1c
.RI "file \fBPersonForm\&.cs\fP"
.br
.ti -1c
.RI "file \fBPersonForm\&.Designer\&.cs\fP"
.br
.ti -1c
.RI "file \fBReadWriteAuthorizationTests\&.cs\fP"
.br
.in -1c
