.TH "C:/Users/korye/source/repos/csla/Source/Csla.Xaml.Shared Directory Reference" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/korye/source/repos/csla/Source/Csla.Xaml.Shared Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBApplicationContextManager\&.cs\fP"
.br
.ti -1c
.RI "file \fBBrokenRulesSeverityConverter\&.cs\fP"
.br
.ti -1c
.RI "file \fBBusyAnimation\&.cs\fP"
.br
.ti -1c
.RI "file \fBCancellableViewModel\&.cs\fP"
.br
.ti -1c
.RI "file \fBConfigurationExtensions\&.cs\fP"
.br
.ti -1c
.RI "file \fBCslaDataProvider\&.cs\fP"
.br
.ti -1c
.RI "file \fBCslaDataProviderCommandManager\&.cs\fP"
.br
.ti -1c
.RI "file \fBDataDecoratorBase\&.cs\fP"
.br
.ti -1c
.RI "file \fBErrorDialog\&.cs\fP"
.br
.ti -1c
.RI "file \fBErrorEventArgs\&.cs\fP"
.br
.ti -1c
.RI "file \fBExecuteEventArgs\&.cs\fP"
.br
.ti -1c
.RI "file \fBIdentityConverter\&.cs\fP"
.br
.ti -1c
.RI "file \fBIErrorDialog\&.cs\fP"
.br
.ti -1c
.RI "file \fBInvokeMethod\&.cs\fP"
.br
.ti -1c
.RI "file \fBIsNotConverter\&.cs\fP"
.br
.ti -1c
.RI "file \fBIViewModel\&.cs\fP"
.br
.ti -1c
.RI "file \fBObjectStatus\&.cs\fP"
.br
.ti -1c
.RI "file \fBPropertyInfo\&.cs\fP"
.br
.ti -1c
.RI "file \fBPropertyStatus\&.cs\fP"
.br
.ti -1c
.RI "file \fBTriggerAction\&.cs\fP"
.br
.ti -1c
.RI "file \fBViewModel\&.cs\fP"
.br
.ti -1c
.RI "file \fBViewModelBase\&.cs\fP"
.br
.in -1c
