.TH "C:/Users/korye/source/repos/csla/Source/Csla.Blazor Directory Reference" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/korye/source/repos/csla/Source/Csla.Blazor Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBClient\fP"
.br
.ti -1c
.RI "directory \fBProperties\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBConfigurationExtensions\&.cs\fP"
.br
.ti -1c
.RI "file \fBCslaPermissionRequirement\&.cs\fP"
.br
.ti -1c
.RI "file \fBCslaPermissionsPolicyProvider\&.cs\fP"
.br
.ti -1c
.RI "file \fBCslaPolicy\&.cs\fP"
.br
.ti -1c
.RI "file \fBCslaValidationMessages\&.razor\&.cs\fP"
.br
.ti -1c
.RI "file \fBCslaValidator\&.cs\fP"
.br
.ti -1c
.RI "file \fBEditContextCslaExtensions\&.cs\fP"
.br
.ti -1c
.RI "file \fBHasPermissionAttribute\&.cs\fP"
.br
.ti -1c
.RI "file \fBHasPermissionHandler\&.cs\fP"
.br
.ti -1c
.RI "file \fBIPropertyInfo\&.cs\fP"
.br
.ti -1c
.RI "file \fBPropertyInfo\&.cs\fP"
.br
.ti -1c
.RI "file \fBViewModel\&.cs\fP"
.br
.in -1c
