.TH "DataPortal Directory Reference" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DataPortal Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBArrayTests\&.cs\fP"
.br
.ti -1c
.RI "file \fBAsynchDataPortalTest\&.cs\fP"
.br
.ti -1c
.RI "file \fBDataPortal/AuthorizeDataPortalTests\&.cs\fP"
.br
.ti -1c
.RI "file \fBCsla\&.test/DataPortal/ChildEntity\&.cs\fP"
.br
.ti -1c
.RI "file \fBCsla\&.test/DataPortal/ChildEntityList\&.cs\fP"
.br
.ti -1c
.RI "file \fBCustomDataPortalServer\&.cs\fP"
.br
.ti -1c
.RI "file \fBDataPortalExceptionTest\&.cs\fP"
.br
.ti -1c
.RI "file \fBDataPortalTests\&.cs\fP"
.br
.ti -1c
.RI "file \fBDisposeScopeTest\&.cs\fP"
.br
.ti -1c
.RI "file \fBDpRoot\&.cs\fP"
.br
.ti -1c
.RI "file \fBESTransactionalRoot\&.cs\fP"
.br
.ti -1c
.RI "file \fBInterceptorTests\&.cs\fP"
.br
.ti -1c
.RI "file \fBLegacy\&.cs\fP"
.br
.ti -1c
.RI "file \fBLegacySplit\&.cs\fP"
.br
.ti -1c
.RI "file \fBLegacySplitBase\&.cs\fP"
.br
.ti -1c
.RI "file \fBLegacySplitTest\&.cs\fP"
.br
.ti -1c
.RI "file \fBLegacyTest\&.cs\fP"
.br
.ti -1c
.RI "file \fBLogicalExecutionDataPortalTests\&.cs\fP"
.br
.ti -1c
.RI "file \fBMultipleDataAccess\&.cs\fP"
.br
.ti -1c
.RI "file \fBMultipleDataAccessBase\&.cs\fP"
.br
.ti -1c
.RI "file \fBMultipleDataAccessTest\&.cs\fP"
.br
.ti -1c
.RI "file \fBCsla\&.test/DataPortal/ParentEntity\&.cs\fP"
.br
.ti -1c
.RI "file \fBSingleOverload\&.cs\fP"
.br
.ti -1c
.RI "file \fBSingleOverloadTest\&.cs\fP"
.br
.ti -1c
.RI "file \fBSingleTest\&.cs\fP"
.br
.ti -1c
.RI "file \fBSplit\&.cs\fP"
.br
.ti -1c
.RI "file \fBSplitBase\&.cs\fP"
.br
.ti -1c
.RI "file \fBSplitOverload\&.cs\fP"
.br
.ti -1c
.RI "file \fBSplitOverloadBase\&.cs\fP"
.br
.ti -1c
.RI "file \fBSplitOverloadTest\&.cs\fP"
.br
.ti -1c
.RI "file \fBSplitTest\&.cs\fP"
.br
.ti -1c
.RI "file \fBStronglyTypedDP\&.cs\fP"
.br
.ti -1c
.RI "file \fBTransactionalRoot\&.cs\fP"
.br
.in -1c
