.TH "Data Directory Reference" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Data Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBContextTests\&.cs\fP"
.br
.ti -1c
.RI "file \fBTestEFContext\&.Designer\&.cs\fP"
.br
.ti -1c
.RI "file \fBTestLinqToSqlContext\&.designer\&.cs\fP"
.br
.ti -1c
.RI "file \fBTransactionContextUser\&.cs\fP"
.br
.ti -1c
.RI "file \fBTransactionContextUserList\&.cs\fP"
.br
.in -1c
