.TH "WcfChannel Directory Reference" 3 "Thu Jul 22 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WcfChannel Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBCreateRequest\&.cs\fP"
.br
.ti -1c
.RI "file \fBDeleteRequest\&.cs\fP"
.br
.ti -1c
.RI "file \fBFetchRequest\&.cs\fP"
.br
.ti -1c
.RI "file \fBNetDataContractOperationBehavior\&.cs\fP"
.br
.ti -1c
.RI "file \fBWcfChannel/UpdateRequest\&.cs\fP"
.br
.ti -1c
.RI "file \fBUseNetDataContractAttribute\&.cs\fP"
.br
.ti -1c
.RI "file \fBWcfChannel/WcfResponse\&.cs\fP"
.br
.in -1c
