.TH "C:/Users/korye/source/repos/csla/Source/Csla.test/Authorization Directory Reference" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/korye/source/repos/csla/Source/Csla.test/Authorization Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBAuthRuleExpectsCriteria\&.cs\fP"
.br
.ti -1c
.RI "file \fBAuthTests\&.cs\fP"
.br
.ti -1c
.RI "file \fBPermissionRootWithCriteria\&.cs\fP"
.br
.ti -1c
.RI "file \fBPermissionsRoot\&.cs\fP"
.br
.ti -1c
.RI "file \fBPermissionsRoot2\&.cs\fP"
.br
.ti -1c
.RI "file \fBPerTypeAuthClasses\&.cs\fP"
.br
.ti -1c
.RI "file \fBPerTypeAuthorization\&.cs\fP"
.br
.ti -1c
.RI "file \fBReadonlyAuthorizationTests\&.cs\fP"
.br
.ti -1c
.RI "file \fBReadOnlyPerson\&.cs\fP"
.br
.ti -1c
.RI "file \fBRootException\&.cs\fP"
.br
.in -1c
