.TH "Fluent Directory Reference" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Fluent Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBCslaConfiguration\&.cs\fP"
.br
.ti -1c
.RI "file \fBCslaDataConfiguration\&.cs\fP"
.br
.ti -1c
.RI "file \fBCslaDataPortalConfiguration\&.cs\fP"
.br
.ti -1c
.RI "file \fBCslaSecurityConfiguration\&.cs\fP"
.br
.ti -1c
.RI "file \fBCslaSerializationConfiguration\&.cs\fP"
.br
.ti -1c
.RI "file \fBICslaConfiguration\&.cs\fP"
.br
.in -1c
