.TH "Serialization Directory Reference" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Serialization Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBAddress\&.cs\fP"
.br
.ti -1c
.RI "file \fBAddressBase\&.cs\fP"
.br
.ti -1c
.RI "file \fBAddressList\&.cs\fP"
.br
.ti -1c
.RI "file \fBBindingListTests\&.cs\fP"
.br
.ti -1c
.RI "file \fBSilverlight/Serialization/Customer\&.cs\fP"
.br
.ti -1c
.RI "file \fBSerialization/CustomerContact\&.cs\fP"
.br
.ti -1c
.RI "file \fBCustomerWithEnum\&.cs\fP"
.br
.ti -1c
.RI "file \fBCustomMobileList\&.cs\fP"
.br
.ti -1c
.RI "file \fBMockMobileList\&.cs\fP"
.br
.ti -1c
.RI "file \fBMockNonBusinessObject\&.cs\fP"
.br
.ti -1c
.RI "file \fBSerialization/MockReadOnly\&.cs\fP"
.br
.ti -1c
.RI "file \fBSerialization/MockReadOnlyList\&.cs\fP"
.br
.ti -1c
.RI "file \fBPerson\&.cs\fP"
.br
.ti -1c
.RI "file \fBPersonWIthSmartDateField\&.cs\fP"
.br
.ti -1c
.RI "file \fBSilverlight/Serialization/ReadOnlyPerson\&.cs\fP"
.br
.ti -1c
.RI "file \fBSerialization/ReadOnlyPersonList\&.cs\fP"
.br
.ti -1c
.RI "file \fBCsla\&.test/Silverlight/Serialization/SerializationTests\&.cs\fP"
.br
.ti -1c
.RI "file \fBUndoTests\&.cs\fP"
.br
.in -1c
