.TH "C:/Users/korye/source/repos/csla/Source/Csla.Analyzers/Csla.Analyzers.Tests/Extensions Directory Reference" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/korye/source/repos/csla/Source/Csla.Analyzers/Csla.Analyzers.Tests/Extensions Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBDataPortalOperationQualificationTests\&.cs\fP"
.br
.ti -1c
.RI "file \fBIMethodSymbolExtensionsTests\&.cs\fP"
.br
.ti -1c
.RI "file \fBITypeSymbolExtensionsTests\&.cs\fP"
.br
.ti -1c
.RI "file \fBSyntaxNodeExtensionsTests\&.cs\fP"
.br
.in -1c
