.TH "C:/Users/korye/source/repos/csla/Source/Csla.Validation.Shared/CommonRules.cs" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/korye/source/repos/csla/Source/Csla.Validation.Shared/CommonRules.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCsla\&.Validation\&.CommonRules\fP"
.br
.RI "Implements common business rules\&. "
.ti -1c
.RI "class \fBCsla\&.Validation\&.CommonRules\&.MaxLengthRuleArgs\fP"
.br
.RI "Custom \fBRuleArgs\fP object required by the StringMaxLength rule method\&. "
.ti -1c
.RI "class \fBCsla\&.Validation\&.CommonRules\&.MinLengthRuleArgs\fP"
.br
.RI "Custom \fBRuleArgs\fP object required by the StringMinLength rule method\&. "
.ti -1c
.RI "class \fBCsla\&.Validation\&.CommonRules\&.IntegerMaxValueRuleArgs\fP"
.br
.RI "Custom \fBRuleArgs\fP object required by the IntegerMaxValue rule method\&. "
.ti -1c
.RI "class \fBCsla\&.Validation\&.CommonRules\&.IntegerMinValueRuleArgs\fP"
.br
.RI "Custom \fBRuleArgs\fP object required by the IntegerMinValue rule method\&. "
.ti -1c
.RI "class \fBCsla\&.Validation\&.CommonRules\&.MaxValueRuleArgs< T >\fP"
.br
.RI "Custom \fBRuleArgs\fP object required by the \fBMaxValue\fP rule method\&. "
.ti -1c
.RI "class \fBCsla\&.Validation\&.CommonRules\&.MinValueRuleArgs< T >\fP"
.br
.RI "Custom \fBRuleArgs\fP object required by the \fBMinValue\fP rule method\&. "
.ti -1c
.RI "class \fBCsla\&.Validation\&.CommonRules\&.RegExRuleArgs\fP"
.br
.RI "Custom \fBRuleArgs\fP object required by the RegExMatch rule method\&. "
.ti -1c
.RI "class \fBCsla\&.Validation\&.CommonRules\&.DataAnnotationRuleArgs\fP"
.br
.RI "Arguments provided to the DataAnnotation rule method "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBCsla\fP"
.br
.ti -1c
.RI "namespace \fBCsla\&.Validation\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
