.TH "ContextManager.cs" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ContextManager.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCsla\&.Data\&.ContextManager< C >\fP"
.br
.RI "Provides an automated way to reuse LINQ data context objects within the context of a single data portal operation\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBCsla\fP"
.br
.ti -1c
.RI "namespace \fBCsla\&.Data\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
