.TH "ContextBOVerifier.cs" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ContextBOVerifier.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCsla\&.Testing\&.Business\&.ApplicationContext\&.ContextBOVerifier< T >\fP"
.br
.ti -1c
.RI "class \fBCsla\&.Testing\&.Business\&.ApplicationContext\&.ContextMessageValues\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBCsla\fP"
.br
.ti -1c
.RI "namespace \fBCsla\&.Testing\fP"
.br
.ti -1c
.RI "namespace \fBCsla\&.Testing\&.Business\fP"
.br
.ti -1c
.RI "namespace \fBCsla\&.Testing\&.Business\&.ApplicationContext\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum class \fBCsla\&.Testing\&.Business\&.ApplicationContext\&.Contexts\fP { \fBCsla\&.Testing\&.Business\&.ApplicationContext\&.Client\fP, \fBCsla\&.Testing\&.Business\&.ApplicationContext\&.Global\fP }"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
