.TH "Csla.DataPortalClient.PrimitiveCriteria" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.DataPortalClient.PrimitiveCriteria \- Class used as a wrapper for criteria based requests that use primitives  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.Serialization\&.Mobile\&.IMobileObject\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPrimitiveCriteria\fP ()"
.br
.RI "Creates an instance of the object\&. "
.ti -1c
.RI "\fBPrimitiveCriteria\fP (object value)"
.br
.RI "New instance of the criteria "
.ti -1c
.RI "void \fBGetState\fP (\fBSerializationInfo\fP info)"
.br
.RI "Method called by MobileFormatter when an object should serialize its data\&. The data should be serialized into the SerializationInfo parameter\&. "
.ti -1c
.RI "void \fBGetChildren\fP (\fBSerializationInfo\fP info, \fBMobileFormatter\fP formatter)"
.br
.RI "Method called by MobileFormatter when an object should serialize its child references\&. The data should be serialized into the SerializationInfo parameter\&. "
.ti -1c
.RI "void \fBSetState\fP (\fBSerializationInfo\fP info)"
.br
.RI "Method called by MobileFormatter when an object should be deserialized\&. The data should be deserialized from the SerializationInfo parameter\&. "
.ti -1c
.RI "void \fBSetChildren\fP (\fBSerializationInfo\fP info, \fBMobileFormatter\fP formatter)"
.br
.RI "Method called by MobileFormatter when an object should deserialize its child references\&. The data should be deserialized from the SerializationInfo parameter\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "object \fBValue\fP\fC [get]\fP"
.br
.RI "Criteria value "
.in -1c
.SH "Detailed Description"
.PP 
Class used as a wrapper for criteria based requests that use primitives 


.PP
Definition at line 17 of file PrimitiveCriteria\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Csla\&.DataPortalClient\&.PrimitiveCriteria\&.PrimitiveCriteria ()"

.PP
Creates an instance of the object\&. 
.PP
Definition at line 22 of file PrimitiveCriteria\&.cs\&.
.SS "Csla\&.DataPortalClient\&.PrimitiveCriteria\&.PrimitiveCriteria (object value)"

.PP
New instance of the criteria 
.PP
\fBParameters\fP
.RS 4
\fIvalue\fP Criteria value
.RE
.PP

.PP
Definition at line 28 of file PrimitiveCriteria\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Csla\&.DataPortalClient\&.PrimitiveCriteria\&.GetChildren (\fBSerializationInfo\fP info, \fBMobileFormatter\fP formatter)"

.PP
Method called by MobileFormatter when an object should serialize its child references\&. The data should be serialized into the SerializationInfo parameter\&. 
.PP
\fBParameters\fP
.RS 4
\fIinfo\fP Object to contain the serialized data\&. 
.br
\fIformatter\fP Reference to the formatter performing the serialization\&. 
.RE
.PP

.PP
Implements \fBCsla\&.Serialization\&.Mobile\&.IMobileObject\fP\&.
.PP
Definition at line 69 of file PrimitiveCriteria\&.cs\&.
.SS "void Csla\&.DataPortalClient\&.PrimitiveCriteria\&.GetState (\fBSerializationInfo\fP info)"

.PP
Method called by MobileFormatter when an object should serialize its data\&. The data should be serialized into the SerializationInfo parameter\&. 
.PP
\fBParameters\fP
.RS 4
\fIinfo\fP Object to contain the serialized data\&. 
.RE
.PP

.PP
Implements \fBCsla\&.Serialization\&.Mobile\&.IMobileObject\fP\&.
.PP
Definition at line 53 of file PrimitiveCriteria\&.cs\&.
.SS "void Csla\&.DataPortalClient\&.PrimitiveCriteria\&.SetChildren (\fBSerializationInfo\fP info, \fBMobileFormatter\fP formatter)"

.PP
Method called by MobileFormatter when an object should deserialize its child references\&. The data should be deserialized from the SerializationInfo parameter\&. 
.PP
\fBParameters\fP
.RS 4
\fIinfo\fP Object containing the serialized data\&. 
.br
\fIformatter\fP Reference to the formatter performing the deserialization\&. 
.RE
.PP

.PP
Implements \fBCsla\&.Serialization\&.Mobile\&.IMobileObject\fP\&.
.PP
Definition at line 97 of file PrimitiveCriteria\&.cs\&.
.SS "void Csla\&.DataPortalClient\&.PrimitiveCriteria\&.SetState (\fBSerializationInfo\fP info)"

.PP
Method called by MobileFormatter when an object should be deserialized\&. The data should be deserialized from the SerializationInfo parameter\&. 
.PP
\fBParameters\fP
.RS 4
\fIinfo\fP Object containing the serialized data\&. 
.RE
.PP

.PP
Implements \fBCsla\&.Serialization\&.Mobile\&.IMobileObject\fP\&.
.PP
Definition at line 81 of file PrimitiveCriteria\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "object Csla\&.DataPortalClient\&.PrimitiveCriteria\&.Value\fC [get]\fP"

.PP
Criteria value 
.PP
Definition at line 37 of file PrimitiveCriteria\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
