.TH "Csla.Test.IO.TestBizObj" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.IO.TestBizObj
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.BusinessBase< TestBizObj >\fP\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBTestBizObj\fP \fBNewNoCriteria\fP ()"
.br
.ti -1c
.RI "static \fBTestBizObj\fP \fBNewCriteria\fP ()"
.br
.ti -1c
.RI "static \fBTestBizObj\fP \fBNewOtherCriteria\fP ()"
.br
.ti -1c
.RI "static \fBTestBizObj\fP \fBGetNoCriteria\fP ()"
.br
.ti -1c
.RI "static \fBTestBizObj\fP \fBGetNullCriteria\fP ()"
.br
.ti -1c
.RI "static \fBTestBizObj\fP \fBGetCriteria\fP ()"
.br
.ti -1c
.RI "static \fBTestBizObj\fP \fBGetOtherCriteria\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override object \fBGetIdValue\fP ()"
.br
.RI "Override this method to return a unique identifying value for this object\&. "
.ti -1c
.RI "void \fBDataPortal_Create\fP ()"
.br
.ti -1c
.RI "void \fBDataPortal_Fetch\fP (object criteria)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 121 of file DPMethodOverloadTests\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Csla\&.Test\&.IO\&.TestBizObj\&.DataPortal_Create ()\fC [protected]\fP"

.PP
Definition at line 174 of file DPMethodOverloadTests\&.cs\&.
.SS "void Csla\&.Test\&.IO\&.TestBizObj\&.DataPortal_Fetch (object criteria)\fC [protected]\fP"

.PP
Definition at line 203 of file DPMethodOverloadTests\&.cs\&.
.SS "static \fBTestBizObj\fP Csla\&.Test\&.IO\&.TestBizObj\&.GetCriteria ()\fC [static]\fP"

.PP
Definition at line 153 of file DPMethodOverloadTests\&.cs\&.
.SS "override object Csla\&.Test\&.IO\&.TestBizObj\&.GetIdValue ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Override this method to return a unique identifying value for this object\&. 
.PP
Reimplemented from \fBCsla\&.BusinessBase< TestBizObj >\fP\&.
.PP
Definition at line 123 of file DPMethodOverloadTests\&.cs\&.
.SS "static \fBTestBizObj\fP Csla\&.Test\&.IO\&.TestBizObj\&.GetNoCriteria ()\fC [static]\fP"

.PP
Definition at line 143 of file DPMethodOverloadTests\&.cs\&.
.SS "static \fBTestBizObj\fP Csla\&.Test\&.IO\&.TestBizObj\&.GetNullCriteria ()\fC [static]\fP"

.PP
Definition at line 148 of file DPMethodOverloadTests\&.cs\&.
.SS "static \fBTestBizObj\fP Csla\&.Test\&.IO\&.TestBizObj\&.GetOtherCriteria ()\fC [static]\fP"

.PP
Definition at line 158 of file DPMethodOverloadTests\&.cs\&.
.SS "static \fBTestBizObj\fP Csla\&.Test\&.IO\&.TestBizObj\&.NewCriteria ()\fC [static]\fP"

.PP
Definition at line 133 of file DPMethodOverloadTests\&.cs\&.
.SS "static \fBTestBizObj\fP Csla\&.Test\&.IO\&.TestBizObj\&.NewNoCriteria ()\fC [static]\fP"

.PP
Definition at line 128 of file DPMethodOverloadTests\&.cs\&.
.SS "static \fBTestBizObj\fP Csla\&.Test\&.IO\&.TestBizObj\&.NewOtherCriteria ()\fC [static]\fP"

.PP
Definition at line 138 of file DPMethodOverloadTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
