.TH "Csla.Channels.RabbitMq.RabbitMqProxy" 3 "Thu Jul 22 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Channels.RabbitMq.RabbitMqProxy \- Implements a data portal proxy to relay data portal calls to a remote application server by using RabbitMQ\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.DataPortalClient\&.DataPortalProxy\fP, and IDisposable\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRabbitMqProxy\fP ()"
.br
.RI "Creates an instance of the object, initializing it to use the DefaultUrl value\&. "
.ti -1c
.RI "\fBRabbitMqProxy\fP (string dataPortalUrl)"
.br
.RI "Creates an instance of the object, initializing it to use the supplied URL\&. "
.ti -1c
.RI "override async Task< \fBDataPortalResult\fP > \fBCreate\fP (Type objectType, object criteria, \fBDataPortalContext\fP context, bool isSync)"
.br
.RI "Called by \fBDataPortal\fP to create a new business object\&. "
.ti -1c
.RI "override async Task< \fBDataPortalResult\fP > \fBFetch\fP (Type objectType, object criteria, \fBDataPortalContext\fP context, bool isSync)"
.br
.RI "Called by \fBDataPortal\fP to load an existing business object\&. "
.ti -1c
.RI "override async Task< \fBDataPortalResult\fP > \fBUpdate\fP (object obj, \fBDataPortalContext\fP context, bool isSync)"
.br
.RI "Called by \fBDataPortal\fP to update a business object\&. "
.ti -1c
.RI "override async Task< \fBDataPortalResult\fP > \fBDelete\fP (Type objectType, object criteria, \fBDataPortalContext\fP context, bool isSync)"
.br
.RI "Called by \fBDataPortal\fP to delete a business object\&. "
.ti -1c
.RI "void \fBDispose\fP ()"
.br
.RI "Dispose this object and its resources\&. "
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBInitializeRabbitMQ\fP ()"
.br
.RI "Method responsible for creating the Connection, Channel, ReplyQueue, and DataPortalQueueName values used for bi-directional communication\&. "
.ti -1c
.RI "override async Task< byte[]> \fBCallDataPortalServer\fP (byte[] serialized, string operation, string routingToken, bool isSync)"
.br
.RI "Create message and send to Rabbit MQ server\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override int \fBTimeout\fP = 30\fC [get, set]\fP"
.br
.RI "Gets or sets the timeout for network operations in seconds (default is 30 seconds)\&. "
.ti -1c
.RI "IConnection \fBConnection\fP\fC [get, set]\fP"
.br
.RI "Gets or sets the connection to the RabbitMQ service\&. "
.ti -1c
.RI "IModel \fBChannel\fP\fC [get, set]\fP"
.br
.RI "Gets or sets the channel (model) for RabbitMQ\&. "
.ti -1c
.RI "string \fBDataPortalQueueName\fP\fC [get, set]\fP"
.br
.RI "Gets or sets the name of the data portal service queue\&. "
.in -1c
.SH "Detailed Description"
.PP 
Implements a data portal proxy to relay data portal calls to a remote application server by using RabbitMQ\&. 


.PP
Definition at line 24 of file RabbitMqProxy\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Csla\&.Channels\&.RabbitMq\&.RabbitMqProxy\&.RabbitMqProxy ()"

.PP
Creates an instance of the object, initializing it to use the DefaultUrl value\&. 
.PP
Definition at line 30 of file RabbitMqProxy\&.cs\&.
.SS "Csla\&.Channels\&.RabbitMq\&.RabbitMqProxy\&.RabbitMqProxy (string dataPortalUrl)"

.PP
Creates an instance of the object, initializing it to use the supplied URL\&. 
.PP
\fBParameters\fP
.RS 4
\fIdataPortalUrl\fP RabbitMQ service URL
.RE
.PP

.PP
Definition at line 39 of file RabbitMqProxy\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override async Task<byte[]> Csla\&.Channels\&.RabbitMq\&.RabbitMqProxy\&.CallDataPortalServer (byte[] serialized, string operation, string routingToken, bool isSync)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Create message and send to Rabbit MQ server\&. Return Response from server
.PP
\fBParameters\fP
.RS 4
\fIserialized\fP Serialised request
.br
\fIoperation\fP \fBDataPortal\fP operation
.br
\fIroutingToken\fP Routing Tag for server
.br
\fIisSync\fP True if the client-side proxy should synchronously invoke the server\&.
.RE
.PP
\fBReturns\fP
.RS 4
Serialised response from server
.RE
.PP

.PP
Implements \fBCsla\&.DataPortalClient\&.DataPortalProxy\fP\&.
.PP
Definition at line 191 of file RabbitMqProxy\&.cs\&.
.SS "override async Task<\fBDataPortalResult\fP> Csla\&.Channels\&.RabbitMq\&.RabbitMqProxy\&.Create (Type objectType, object criteria, \fBDataPortalContext\fP context, bool isSync)\fC [virtual]\fP"

.PP
Called by \fBDataPortal\fP to create a new business object\&. 
.PP
\fBParameters\fP
.RS 4
\fIobjectType\fP Type of business object to create\&.
.br
\fIcriteria\fP Criteria object describing business object\&.
.br
\fIcontext\fP DataPortalContext object passed to the server\&.
.br
\fIisSync\fP True if the client-side proxy should synchronously invoke the server\&.
.RE
.PP

.PP
Reimplemented from \fBCsla\&.DataPortalClient\&.DataPortalProxy\fP\&.
.PP
Definition at line 117 of file RabbitMqProxy\&.cs\&.
.SS "override async Task<\fBDataPortalResult\fP> Csla\&.Channels\&.RabbitMq\&.RabbitMqProxy\&.Delete (Type objectType, object criteria, \fBDataPortalContext\fP context, bool isSync)\fC [virtual]\fP"

.PP
Called by \fBDataPortal\fP to delete a business object\&. 
.PP
\fBParameters\fP
.RS 4
\fIobjectType\fP Type of business object to create\&.
.br
\fIcriteria\fP Criteria object describing business object\&.
.br
\fIcontext\fP \fBServer\&.DataPortalContext\fP object passed to the server\&. 
.br
\fIisSync\fP True if the client-side proxy should synchronously invoke the server\&.
.RE
.PP

.PP
Reimplemented from \fBCsla\&.DataPortalClient\&.DataPortalProxy\fP\&.
.PP
Definition at line 173 of file RabbitMqProxy\&.cs\&.
.SS "void Csla\&.Channels\&.RabbitMq\&.RabbitMqProxy\&.Dispose ()"

.PP
Dispose this object and its resources\&. 
.PP
Definition at line 223 of file RabbitMqProxy\&.cs\&.
.SS "override async Task<\fBDataPortalResult\fP> Csla\&.Channels\&.RabbitMq\&.RabbitMqProxy\&.Fetch (Type objectType, object criteria, \fBDataPortalContext\fP context, bool isSync)\fC [virtual]\fP"

.PP
Called by \fBDataPortal\fP to load an existing business object\&. 
.PP
\fBParameters\fP
.RS 4
\fIobjectType\fP Type of business object to create\&.
.br
\fIcriteria\fP Criteria object describing business object\&.
.br
\fIcontext\fP \fBServer\&.DataPortalContext\fP object passed to the server\&. 
.br
\fIisSync\fP True if the client-side proxy should synchronously invoke the server\&.
.RE
.PP

.PP
Reimplemented from \fBCsla\&.DataPortalClient\&.DataPortalProxy\fP\&.
.PP
Definition at line 136 of file RabbitMqProxy\&.cs\&.
.SS "virtual void Csla\&.Channels\&.RabbitMq\&.RabbitMqProxy\&.InitializeRabbitMQ ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Method responsible for creating the Connection, Channel, ReplyQueue, and DataPortalQueueName values used for bi-directional communication\&. 
.PP
Definition at line 77 of file RabbitMqProxy\&.cs\&.
.SS "override async Task<\fBDataPortalResult\fP> Csla\&.Channels\&.RabbitMq\&.RabbitMqProxy\&.Update (object obj, \fBDataPortalContext\fP context, bool isSync)\fC [virtual]\fP"

.PP
Called by \fBDataPortal\fP to update a business object\&. 
.PP
\fBParameters\fP
.RS 4
\fIobj\fP The business object to update\&.
.br
\fIcontext\fP \fBServer\&.DataPortalContext\fP object passed to the server\&. 
.br
\fIisSync\fP True if the client-side proxy should synchronously invoke the server\&.
.RE
.PP

.PP
Reimplemented from \fBCsla\&.DataPortalClient\&.DataPortalProxy\fP\&.
.PP
Definition at line 154 of file RabbitMqProxy\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "IModel Csla\&.Channels\&.RabbitMq\&.RabbitMqProxy\&.Channel\fC [get]\fP, \fC [set]\fP, \fC [protected]\fP"

.PP
Gets or sets the channel (model) for RabbitMQ\&. 
.PP
Definition at line 58 of file RabbitMqProxy\&.cs\&.
.SS "IConnection Csla\&.Channels\&.RabbitMq\&.RabbitMqProxy\&.Connection\fC [get]\fP, \fC [set]\fP, \fC [protected]\fP"

.PP
Gets or sets the connection to the RabbitMQ service\&. 
.PP
Definition at line 53 of file RabbitMqProxy\&.cs\&.
.SS "string Csla\&.Channels\&.RabbitMq\&.RabbitMqProxy\&.DataPortalQueueName\fC [get]\fP, \fC [set]\fP, \fC [protected]\fP"

.PP
Gets or sets the name of the data portal service queue\&. 
.PP
Definition at line 64 of file RabbitMqProxy\&.cs\&.
.SS "override int Csla\&.Channels\&.RabbitMq\&.RabbitMqProxy\&.Timeout = 30\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the timeout for network operations in seconds (default is 30 seconds)\&. 
.PP
Definition at line 48 of file RabbitMqProxy\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
