.TH "Csla.Analyzers.Tests.IsCompleteCalledInAsynchronousBusinessRuleRemoveCallCodeFixTests" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Analyzers.Tests.IsCompleteCalledInAsynchronousBusinessRuleRemoveCallCodeFixTests
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBVerifyGetFixableDiagnosticIds\fP ()"
.br
.ti -1c
.RI "async Task \fBVerifyGetFixes\fP ()"
.br
.ti -1c
.RI "async Task \fBVerifyGetFixesWithNameofCall\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 16 of file IsCompleteCalledInAsynchronousBusinessRuleRemoveCallCodeFixTests\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Csla\&.Analyzers\&.Tests\&.IsCompleteCalledInAsynchronousBusinessRuleRemoveCallCodeFixTests\&.VerifyGetFixableDiagnosticIds ()"

.PP
Definition at line 19 of file IsCompleteCalledInAsynchronousBusinessRuleRemoveCallCodeFixTests\&.cs\&.
.SS "async Task Csla\&.Analyzers\&.Tests\&.IsCompleteCalledInAsynchronousBusinessRuleRemoveCallCodeFixTests\&.VerifyGetFixes ()"

.PP
Definition at line 30 of file IsCompleteCalledInAsynchronousBusinessRuleRemoveCallCodeFixTests\&.cs\&.
.SS "async Task Csla\&.Analyzers\&.Tests\&.IsCompleteCalledInAsynchronousBusinessRuleRemoveCallCodeFixTests\&.VerifyGetFixesWithNameofCall ()"

.PP
Definition at line 68 of file IsCompleteCalledInAsynchronousBusinessRuleRemoveCallCodeFixTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
