.TH "Csla.Windows.CslaActionCancelEventArgs" 3 "Thu Jul 22 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Windows.CslaActionCancelEventArgs \- Event args providing information about a canceled action\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits CancelEventArgs\&.
.PP
Inherited by \fBCsla\&.Windows\&.HasBrokenRulesEventArgs\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCslaActionCancelEventArgs\fP (bool cancel, string commandName)"
.br
.RI "Creates an instance of the object\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBCommandName\fP\fC [get]\fP"
.br
.RI "Gets the name of the command\&. "
.in -1c
.SH "Detailed Description"
.PP 
Event args providing information about a canceled action\&. 


.PP
Definition at line 17 of file CslaActionCancelEventArgs\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Csla\&.Windows\&.CslaActionCancelEventArgs\&.CslaActionCancelEventArgs (bool cancel, string commandName)"

.PP
Creates an instance of the object\&. 
.PP
\fBParameters\fP
.RS 4
\fIcancel\fP Indicates whether a cancel should occur\&. 
.br
\fIcommandName\fP Name of the command\&. 
.RE
.PP

.PP
Definition at line 28 of file CslaActionCancelEventArgs\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "string Csla\&.Windows\&.CslaActionCancelEventArgs\&.CommandName\fC [get]\fP"

.PP
Gets the name of the command\&. 
.PP
Definition at line 39 of file CslaActionCancelEventArgs\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
