.TH "Csla.Core.InvalidQueryException" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Core.InvalidQueryException
.SH SYNOPSIS
.br
.PP
.PP
Inherits System\&.Exception\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBInvalidQueryException\fP (string message)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override string \fBMessage\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 13 of file InvalidQueryExpression\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Csla\&.Core\&.InvalidQueryException\&.InvalidQueryException (string message)"

.PP
Definition at line 17 of file InvalidQueryExpression\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "override string Csla\&.Core\&.InvalidQueryException\&.Message\fC [get]\fP"

.PP
Definition at line 22 of file InvalidQueryExpression\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
