.TH "Csla.Test.Serialization.DCRoot" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.Serialization.DCRoot
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.BusinessBase< DCRoot >\fP\&.
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBPropertyInfo\fP< int > \fBDataProperty\fP = RegisterProperty<int>(c => c\&.Data, \fBRelationshipTypes\&.PrivateField\fP)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBData\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBNonCslaChild\fP \fBChild\fP\fC [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 17 of file DCRoot\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBPropertyInfo\fP<int> Csla\&.Test\&.Serialization\&.DCRoot\&.DataProperty = RegisterProperty<int>(c => c\&.Data, \fBRelationshipTypes\&.PrivateField\fP)\fC [static]\fP"

.PP
Definition at line 21 of file DCRoot\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "\fBNonCslaChild\fP Csla\&.Test\&.Serialization\&.DCRoot\&.Child\fC [get]\fP"

.PP
Definition at line 29 of file DCRoot\&.cs\&.
.SS "int Csla\&.Test\&.Serialization\&.DCRoot\&.Data\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 22 of file DCRoot\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
