.TH "Csla.Test.SmartDate.SDtest" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.SmartDate.SDtest
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.BusinessBase< SDtest >\fP\&.
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBPropertyInfo\fP< \fBCsla\&.SmartDate\fP > \fBTextDateProperty\fP"
.br
.ti -1c
.RI "static \fBPropertyInfo\fP< \fBCsla\&.SmartDate\fP > \fBMyDateProperty\fP = RegisterProperty<\fBCsla\&.SmartDate\fP>(c => c\&.MyDate)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBTextDate\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBCsla\&.SmartDate\fP \fBMyDate\fP\fC [get, set]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 473 of file SmartDateTests\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBPropertyInfo\fP<\fBCsla\&.SmartDate\fP> Csla\&.Test\&.SmartDate\&.SDtest\&.MyDateProperty = RegisterProperty<\fBCsla\&.SmartDate\fP>(c => c\&.MyDate)\fC [static]\fP"

.PP
Definition at line 483 of file SmartDateTests\&.cs\&.
.SS "\fBPropertyInfo\fP<\fBCsla\&.SmartDate\fP> Csla\&.Test\&.SmartDate\&.SDtest\&.TextDateProperty\fC [static]\fP"
\fBInitial value:\fP
.PP
.nf
= 
      RegisterProperty<Csla\&.SmartDate>(c => c\&.TextDate, null, new Csla\&.SmartDate { FormatString = "g" })
.fi
.PP
Definition at line 475 of file SmartDateTests\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "\fBCsla\&.SmartDate\fP Csla\&.Test\&.SmartDate\&.SDtest\&.MyDate\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 484 of file SmartDateTests\&.cs\&.
.SS "string Csla\&.Test\&.SmartDate\&.SDtest\&.TextDate\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 477 of file SmartDateTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
