.TH "Csla.Server.Hosts.WcfChannel.FetchRequest" 3 "Thu Jul 22 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Server.Hosts.WcfChannel.FetchRequest \- Request message for retrieving an existing business object\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFetchRequest\fP (Type objectType, object criteria, \fBCsla\&.Server\&.DataPortalContext\fP context)"
.br
.RI "Create new instance of object\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "Type \fBObjectType\fP\fC [get, set]\fP"
.br
.RI "The type of the business object to be retrieved\&. "
.ti -1c
.RI "object \fBCriteria\fP\fC [get, set]\fP"
.br
.RI "Criteria object describing business object\&. "
.ti -1c
.RI "\fBCsla\&.Server\&.DataPortalContext\fP \fBContext\fP\fC [get, set]\fP"
.br
.RI "\fBData\fP portal context from client\&. "
.in -1c
.SH "Detailed Description"
.PP 
Request message for retrieving an existing business object\&. 


.PP
Definition at line 18 of file FetchRequest\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Csla\&.Server\&.Hosts\&.WcfChannel\&.FetchRequest\&.FetchRequest (Type objectType, object criteria, \fBCsla\&.Server\&.DataPortalContext\fP context)"

.PP
Create new instance of object\&. 
.PP
\fBParameters\fP
.RS 4
\fIobjectType\fP Type of business object to create\&.
.br
\fIcriteria\fP Criteria object describing business object\&.
.br
\fIcontext\fP \fBData\fP portal context from client\&.
.RE
.PP

.PP
Definition at line 33 of file FetchRequest\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "\fBCsla\&.Server\&.DataPortalContext\fP Csla\&.Server\&.Hosts\&.WcfChannel\&.FetchRequest\&.Context\fC [get]\fP, \fC [set]\fP"

.PP
\fBData\fP portal context from client\&. 
.PP
Definition at line 62 of file FetchRequest\&.cs\&.
.SS "object Csla\&.Server\&.Hosts\&.WcfChannel\&.FetchRequest\&.Criteria\fC [get]\fP, \fC [set]\fP"

.PP
Criteria object describing business object\&. 
.PP
Definition at line 53 of file FetchRequest\&.cs\&.
.SS "Type Csla\&.Server\&.Hosts\&.WcfChannel\&.FetchRequest\&.ObjectType\fC [get]\fP, \fC [set]\fP"

.PP
The type of the business object to be retrieved\&. 
.PP
Definition at line 44 of file FetchRequest\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
