.TH "Csla.Test.AppContext.SimpleRoot" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.AppContext.SimpleRoot
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.BusinessBase< SimpleRoot >\fP\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBSimpleRoot\fP \fBNewSimpleRoot\fP ()"
.br
.RI "Creates a new \fBSimpleRoot\fP object "
.ti -1c
.RI "static \fBSimpleRoot\fP \fBGetSimpleRoot\fP (string \fBData\fP)"
.br
.RI "Gets a \fBSimpleRoot\fP object "
.ti -1c
.RI "static void \fBDeleteSimpleRoot\fP (string \fBData\fP)"
.br
.RI "Deletes a \fBSimpleRoot\fP object "
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override object \fBGetIdValue\fP ()"
.br
.RI "The unique ID of this object "
.ti -1c
.RI "void \fBDataPortal_Fetch\fP (object criteria)"
.br
.RI "Handles \fBDataPortal\fP fetch calls "
.ti -1c
.RI "void \fBDataPortal_Update\fP ()"
.br
.ti -1c
.RI "void \fBDataPortal_Delete\fP (object criteria)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBData\fP\fC [get, set]\fP"
.br
.RI "The data value for this object "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 15 of file SimpleRoot\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Csla\&.Test\&.AppContext\&.SimpleRoot\&.DataPortal_Delete (object criteria)\fC [protected]\fP"

.PP

.PP
\fBParameters\fP
.RS 4
\fIcriteria\fP 
.RE
.PP

.PP
Definition at line 142 of file SimpleRoot\&.cs\&.
.SS "void Csla\&.Test\&.AppContext\&.SimpleRoot\&.DataPortal_Fetch (object criteria)\fC [protected]\fP"

.PP
Handles \fBDataPortal\fP fetch calls 
.PP
\fBParameters\fP
.RS 4
\fIcriteria\fP 
.RE
.PP

.PP
Definition at line 107 of file SimpleRoot\&.cs\&.
.SS "void Csla\&.Test\&.AppContext\&.SimpleRoot\&.DataPortal_Update ()\fC [protected]\fP"

.PP

.PP
Definition at line 119 of file SimpleRoot\&.cs\&.
.SS "static void Csla\&.Test\&.AppContext\&.SimpleRoot\&.DeleteSimpleRoot (string Data)\fC [static]\fP"

.PP
Deletes a \fBSimpleRoot\fP object 
.PP
\fBParameters\fP
.RS 4
\fI\fBData\fP\fP 
.RE
.PP

.PP
Definition at line 87 of file SimpleRoot\&.cs\&.
.SS "override object Csla\&.Test\&.AppContext\&.SimpleRoot\&.GetIdValue ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
The unique ID of this object 
.PP
\fBReturns\fP
.RS 4

.RE
.PP

.PP
Reimplemented from \fBCsla\&.BusinessBase< SimpleRoot >\fP\&.
.PP
Definition at line 22 of file SimpleRoot\&.cs\&.
.SS "static \fBSimpleRoot\fP Csla\&.Test\&.AppContext\&.SimpleRoot\&.GetSimpleRoot (string Data)\fC [static]\fP"

.PP
Gets a \fBSimpleRoot\fP object 
.PP
\fBParameters\fP
.RS 4
\fI\fBData\fP\fP 
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
Definition at line 79 of file SimpleRoot\&.cs\&.
.SS "static \fBSimpleRoot\fP Csla\&.Test\&.AppContext\&.SimpleRoot\&.NewSimpleRoot ()\fC [static]\fP"

.PP
Creates a new \fBSimpleRoot\fP object 
.PP
\fBReturns\fP
.RS 4

.RE
.PP

.PP
Definition at line 68 of file SimpleRoot\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "string Csla\&.Test\&.AppContext\&.SimpleRoot\&.Data\fC [get]\fP, \fC [set]\fP"

.PP
The data value for this object 
.PP
Definition at line 29 of file SimpleRoot\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
