.TH "Csla.Server.DataPortalContext" 3 "Thu Jul 22 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Server.DataPortalContext \- Provides consistent context information between the client and server \fBDataPortal\fP objects\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.Serialization\&.Mobile\&.IMobileObject\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDataPortalContext\fP (IPrincipal principal, bool isRemotePortal)"
.br
.RI "Creates a new \fBDataPortalContext\fP object\&. "
.ti -1c
.RI "\fBDataPortalContext\fP (IPrincipal principal, bool isRemotePortal, string clientCulture, string clientUICulture, \fBContextDictionary\fP clientContext, \fBContextDictionary\fP globalContext)"
.br
.RI "Creates a new \fBDataPortalContext\fP object\&. "
.ti -1c
.RI "\fBDataPortalContext\fP ()"
.br
.RI "Default constructor for use by SerializationFormatterFactory\&.GetFormatter()\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "IPrincipal \fBPrincipal\fP\fC [get]\fP"
.br
.RI "The current principal object if CSLA security is being used\&. "
.ti -1c
.RI "bool \fBIsRemotePortal\fP\fC [get]\fP"
.br
.RI "Returns true if the server-side \fBDataPortal\fP is running on a remote server via remoting\&. "
.ti -1c
.RI "string \fBClientCulture\fP\fC [get]\fP"
.br
.RI "The culture setting on the client workstation\&. "
.ti -1c
.RI "string \fBClientUICulture\fP\fC [get]\fP"
.br
.RI "The culture setting on the client workstation\&. "
.ti -1c
.RI "\fBTransactionalTypes\fP \fBTransactionalType\fP\fC [get, set]\fP"
.br
.RI "Gets the current transactional type\&. "
.ti -1c
.RI "\fBObjectFactoryAttribute\fP \fBFactoryInfo\fP\fC [get, set]\fP"
.br
.RI "Gets the current \fBObjectFactory\fP attribute value (if any)\&. "
.in -1c
.SH "Detailed Description"
.PP 
Provides consistent context information between the client and server \fBDataPortal\fP objects\&. 


.PP
Definition at line 20 of file DataPortalContext\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Csla\&.Server\&.DataPortalContext\&.DataPortalContext (IPrincipal principal, bool isRemotePortal)"

.PP
Creates a new \fBDataPortalContext\fP object\&. 
.PP
\fBParameters\fP
.RS 4
\fIprincipal\fP The current Principal object\&.
.br
\fIisRemotePortal\fP Indicates whether the \fBDataPortal\fP is remote\&.
.RE
.PP

.PP
Definition at line 107 of file DataPortalContext\&.cs\&.
.SS "Csla\&.Server\&.DataPortalContext\&.DataPortalContext (IPrincipal principal, bool isRemotePortal, string clientCulture, string clientUICulture, \fBContextDictionary\fP clientContext, \fBContextDictionary\fP globalContext)"

.PP
Creates a new \fBDataPortalContext\fP object\&. 
.PP
\fBParameters\fP
.RS 4
\fIprincipal\fP The current Principal object\&.
.br
\fIisRemotePortal\fP Indicates whether the \fBDataPortal\fP is remote\&.
.br
\fIclientContext\fP Client context\&.
.br
\fIclientCulture\fP Client culture\&.
.br
\fIclientUICulture\fP Client UI culture\&.
.br
\fIglobalContext\fP Global context\&.
.RE
.PP

.PP
Definition at line 141 of file DataPortalContext\&.cs\&.
.SS "Csla\&.Server\&.DataPortalContext\&.DataPortalContext ()"

.PP
Default constructor for use by SerializationFormatterFactory\&.GetFormatter()\&. 
.PP
Definition at line 154 of file DataPortalContext\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "string Csla\&.Server\&.DataPortalContext\&.ClientCulture\fC [get]\fP"

.PP
The culture setting on the client workstation\&. 
.PP
Definition at line 56 of file DataPortalContext\&.cs\&.
.SS "string Csla\&.Server\&.DataPortalContext\&.ClientUICulture\fC [get]\fP"

.PP
The culture setting on the client workstation\&. 
.PP
Definition at line 65 of file DataPortalContext\&.cs\&.
.SS "\fBObjectFactoryAttribute\fP Csla\&.Server\&.DataPortalContext\&.FactoryInfo\fC [get]\fP, \fC [set]\fP"

.PP
Gets the current \fBObjectFactory\fP attribute value (if any)\&. Only valid in the server-side data portal methods after the attribute value has been determined\&.
.PP
Definition at line 96 of file DataPortalContext\&.cs\&.
.SS "bool Csla\&.Server\&.DataPortalContext\&.IsRemotePortal\fC [get]\fP"

.PP
Returns true if the server-side \fBDataPortal\fP is running on a remote server via remoting\&. 
.PP
Definition at line 47 of file DataPortalContext\&.cs\&.
.SS "IPrincipal Csla\&.Server\&.DataPortalContext\&.Principal\fC [get]\fP"

.PP
The current principal object if CSLA security is being used\&. 
.PP
Definition at line 37 of file DataPortalContext\&.cs\&.
.SS "\fBTransactionalTypes\fP Csla\&.Server\&.DataPortalContext\&.TransactionalType\fC [get]\fP, \fC [set]\fP"

.PP
Gets the current transactional type\&. Only valid in the server-side data portal methods after the transactional type has been determined\&.
.PP
Definition at line 84 of file DataPortalContext\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
