.TH "Csla.Test.FieldManager.Child" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.FieldManager.Child
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.BusinessBase< Child >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBChild\fP ()"
.br
.ti -1c
.RI "void \fBDeleteChild\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBChild\fP \fBNewChild\fP ()"
.br
.ti -1c
.RI "static \fBChild\fP \fBGetChild\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBChild_Create\fP ()"
.br
.ti -1c
.RI "void \fBChild_Fetch\fP ()"
.br
.ti -1c
.RI "void \fBChild_Insert\fP ()"
.br
.ti -1c
.RI "void \fBChild_Update\fP ()"
.br
.ti -1c
.RI "void \fBChild_DeleteSelf\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBData\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBRootData\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBStatus\fP\fC [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 14 of file Csla\&.test/FieldManager/Child\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Csla\&.Test\&.FieldManager\&.Child\&.Child ()"

.PP
Definition at line 26 of file Csla\&.test/FieldManager/Child\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override void Csla\&.Test\&.FieldManager\&.Child\&.Child_Create ()\fC [protected]\fP"

.PP
Definition at line 56 of file Csla\&.test/FieldManager/Child\&.cs\&.
.SS "void Csla\&.Test\&.FieldManager\&.Child\&.Child_DeleteSelf ()\fC [protected]\fP"

.PP
Definition at line 76 of file Csla\&.test/FieldManager/Child\&.cs\&.
.SS "void Csla\&.Test\&.FieldManager\&.Child\&.Child_Fetch ()\fC [protected]\fP"

.PP
Definition at line 61 of file Csla\&.test/FieldManager/Child\&.cs\&.
.SS "void Csla\&.Test\&.FieldManager\&.Child\&.Child_Insert ()\fC [protected]\fP"

.PP
Definition at line 66 of file Csla\&.test/FieldManager/Child\&.cs\&.
.SS "void Csla\&.Test\&.FieldManager\&.Child\&.Child_Update ()\fC [protected]\fP"

.PP
Definition at line 71 of file Csla\&.test/FieldManager/Child\&.cs\&.
.SS "void Csla\&.Test\&.FieldManager\&.Child\&.DeleteChild ()"

.PP
Definition at line 51 of file Csla\&.test/FieldManager/Child\&.cs\&.
.SS "static \fBChild\fP Csla\&.Test\&.FieldManager\&.Child\&.GetChild ()\fC [static]\fP"

.PP
Definition at line 21 of file Csla\&.test/FieldManager/Child\&.cs\&.
.SS "static \fBChild\fP Csla\&.Test\&.FieldManager\&.Child\&.NewChild ()\fC [static]\fP"

.PP
Definition at line 16 of file Csla\&.test/FieldManager/Child\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "string Csla\&.Test\&.FieldManager\&.Child\&.Data\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 32 of file Csla\&.test/FieldManager/Child\&.cs\&.
.SS "string Csla\&.Test\&.FieldManager\&.Child\&.RootData\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 39 of file Csla\&.test/FieldManager/Child\&.cs\&.
.SS "string Csla\&.Test\&.FieldManager\&.Child\&.Status\fC [get]\fP"

.PP
Definition at line 46 of file Csla\&.test/FieldManager/Child\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
