.TH "Csla.ICommandBase" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.ICommandBase \- This is the base class from which command objects will be derived\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.Core\&.ICommandObject\fP, \fBCsla\&.Core\&.IBusinessObject\fP, \fBCsla\&.Serialization\&.Mobile\&.IMobileObject\fP, ICloneable, and INotifyPropertyChanged\&.
.PP
Inherited by \fBCsla\&.CommandBase< T >\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
This is the base class from which command objects will be derived\&. 


.PP
Definition at line 16 of file ICommandBase\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
