.TH "Csla.Test.Authorization.PerTypeAuthRoot" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.Authorization.PerTypeAuthRoot
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.BusinessBase< PerTypeAuthRoot >\fP, and \fBCsla\&.Test\&.Authorization\&.IPerTypeAuthRoot\fP\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBAddObjectAuthorizationRules\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 566 of file AuthTests\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "static void Csla\&.Test\&.Authorization\&.PerTypeAuthRoot\&.AddObjectAuthorizationRules ()\fC [static]\fP"

.PP
Definition at line 569 of file AuthTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
