.TH "Csla.Server.DataPortal" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Server.DataPortal \- Implements the server-side \fBDataPortal\fP message router as discussed in Chapter 4\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.Server\&.IDataPortalServer\fP\&.
.PP
Inherited by \fBCsla\&.Testing\&.Business\&.DataPortal\&.TestableDataPortal\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBNullAuthorizer\fP"
.br
.RI "Default implementation of the authorizer that allows all data portal calls to pass\&. "
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDataPortal\fP ()"
.br
.RI "Default constructor "
.ti -1c
.RI "async Task< \fBDataPortalResult\fP > \fBCreate\fP (Type objectType, object criteria, \fBDataPortalContext\fP context, bool isSync)"
.br
.RI "Create a new business object\&. "
.ti -1c
.RI "async Task< \fBDataPortalResult\fP > \fBFetch\fP (Type objectType, object criteria, \fBDataPortalContext\fP context, bool isSync)"
.br
.RI "Get an existing business object\&. "
.ti -1c
.RI "async Task< \fBDataPortalResult\fP > \fBUpdate\fP (object obj, \fBDataPortalContext\fP context, bool isSync)"
.br
.RI "Update a business object\&. "
.ti -1c
.RI "async Task< \fBDataPortalResult\fP > \fBDelete\fP (Type objectType, object criteria, \fBDataPortalContext\fP context, bool isSync)"
.br
.RI "Delete a business object\&. "
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static object \fBGetCriteriaFromArray\fP (params object[] criteria)"
.br
.RI "Converts a params array to a single serializable criteria value\&. "
.ti -1c
.RI "static object[] \fBGetCriteriaArray\fP (object criteria)"
.br
.RI "Converts a single serializable criteria value into an array of type object\&. "
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBDataPortal\fP (string cslaAuthorizationProviderAppSettingName)"
.br
.RI "This construcor accepts the App Setting name for the \fBCsla\fP Authorization Provider, therefore getting the provider type from configuration file "
.ti -1c
.RI "\fBDataPortal\fP (Type authProviderType)"
.br
.RI "This constructor accepts the Authorization Provider Type as a parameter\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "static \fBDashboard\&.IDashboard\fP \fBDashboard\fP\fC [get, set]\fP"
.br
.RI "Gets the data portal dashboard instance\&. "
.ti -1c
.RI "static Type \fBInterceptorType\fP\fC [get, set]\fP"
.br
.RI "Gets or sets the type of interceptor invoked by the data portal for pre- and post-processing of each data portal invocation\&. "
.ti -1c
.RI "static \fBIAuthorizeDataPortal\fP \fBAuthorizer\fP\fC [get, set]\fP"
.br
.RI "Gets or sets a reference to the current authorizer\&. "
.in -1c
.SH "Detailed Description"
.PP 
Implements the server-side \fBDataPortal\fP message router as discussed in Chapter 4\&. 


.PP
Definition at line 21 of file DataPortal\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Csla\&.Server\&.DataPortal\&.DataPortal ()"

.PP
Default constructor 
.PP
Definition at line 37 of file DataPortal\&.cs\&.
.SS "Csla\&.Server\&.DataPortal\&.DataPortal (string cslaAuthorizationProviderAppSettingName)\fC [protected]\fP"

.PP
This construcor accepts the App Setting name for the \fBCsla\fP Authorization Provider, therefore getting the provider type from configuration file 
.PP
\fBParameters\fP
.RS 4
\fIcslaAuthorizationProviderAppSettingName\fP 
.RE
.PP

.PP
Definition at line 48 of file DataPortal\&.cs\&.
.SS "Csla\&.Server\&.DataPortal\&.DataPortal (Type authProviderType)\fC [protected]\fP"

.PP
This constructor accepts the Authorization Provider Type as a parameter\&. 
.PP
\fBParameters\fP
.RS 4
\fIauthProviderType\fP 
.RE
.PP

.PP
Definition at line 57 of file DataPortal\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "async Task<\fBDataPortalResult\fP> Csla\&.Server\&.DataPortal\&.Create (Type objectType, object criteria, \fBDataPortalContext\fP context, bool isSync)"

.PP
Create a new business object\&. 
.PP
\fBParameters\fP
.RS 4
\fIobjectType\fP Type of business object to create\&.
.br
\fIcriteria\fP Criteria object describing business object\&.
.br
\fIcontext\fP \fBServer\&.DataPortalContext\fP object passed to the server\&. 
.br
\fIisSync\fP True if the client-side proxy should synchronously invoke the server\&.
.RE
.PP

.PP
Implements \fBCsla\&.Server\&.IDataPortalServer\fP\&.
.PP
Definition at line 138 of file DataPortal\&.cs\&.
.SS "async Task<\fBDataPortalResult\fP> Csla\&.Server\&.DataPortal\&.Delete (Type objectType, object criteria, \fBDataPortalContext\fP context, bool isSync)"

.PP
Delete a business object\&. 
.PP
\fBParameters\fP
.RS 4
\fIobjectType\fP Type of business object to create\&.
.br
\fIcriteria\fP Criteria object describing business object\&.
.br
\fIcontext\fP \fBServer\&.DataPortalContext\fP object passed to the server\&. 
.br
\fIisSync\fP True if the client-side proxy should synchronously invoke the server\&.
.RE
.PP

.PP
Implements \fBCsla\&.Server\&.IDataPortalServer\fP\&.
.PP
Definition at line 456 of file DataPortal\&.cs\&.
.SS "async Task<\fBDataPortalResult\fP> Csla\&.Server\&.DataPortal\&.Fetch (Type objectType, object criteria, \fBDataPortalContext\fP context, bool isSync)"

.PP
Get an existing business object\&. 
.PP
\fBParameters\fP
.RS 4
\fIobjectType\fP Type of business object to retrieve\&.
.br
\fIcriteria\fP Criteria object describing business object\&.
.br
\fIcontext\fP \fBServer\&.DataPortalContext\fP object passed to the server\&. 
.br
\fIisSync\fP True if the client-side proxy should synchronously invoke the server\&.
.RE
.PP

.PP
Implements \fBCsla\&.Server\&.IDataPortalServer\fP\&.
.PP
Definition at line 233 of file DataPortal\&.cs\&.
.SS "static object [] Csla\&.Server\&.DataPortal\&.GetCriteriaArray (object criteria)\fC [static]\fP"

.PP
Converts a single serializable criteria value into an array of type object\&. 
.PP
\fBParameters\fP
.RS 4
\fIcriteria\fP Single serializble criteria value
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
Definition at line 755 of file DataPortal\&.cs\&.
.SS "static object Csla\&.Server\&.DataPortal\&.GetCriteriaFromArray (params object[] criteria)\fC [static]\fP"

.PP
Converts a params array to a single serializable criteria value\&. 
.PP
\fBParameters\fP
.RS 4
\fIcriteria\fP Params array
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
Definition at line 730 of file DataPortal\&.cs\&.
.SS "async Task<\fBDataPortalResult\fP> Csla\&.Server\&.DataPortal\&.Update (object obj, \fBDataPortalContext\fP context, bool isSync)"

.PP
Update a business object\&. 
.PP
\fBParameters\fP
.RS 4
\fIobj\fP Business object to update\&.
.br
\fIcontext\fP \fBServer\&.DataPortalContext\fP object passed to the server\&. 
.br
\fIisSync\fP True if the client-side proxy should synchronously invoke the server\&.
.RE
.PP

.PP
Implements \fBCsla\&.Server\&.IDataPortalServer\fP\&.
.PP
Definition at line 325 of file DataPortal\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "\fBIAuthorizeDataPortal\fP Csla\&.Server\&.DataPortal\&.Authorizer\fC [static]\fP, \fC [get]\fP, \fC [set]\fP, \fC [protected]\fP"

.PP
Gets or sets a reference to the current authorizer\&. 
.PP
Definition at line 680 of file DataPortal\&.cs\&.
.SS "\fBDashboard\&.IDashboard\fP Csla\&.Server\&.DataPortal\&.Dashboard\fC [static]\fP, \fC [get]\fP, \fC [set]\fP"

.PP
Gets the data portal dashboard instance\&. 
.PP
Definition at line 26 of file DataPortal\&.cs\&.
.SS "Type Csla\&.Server\&.DataPortal\&.InterceptorType\fC [static]\fP, \fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the type of interceptor invoked by the data portal for pre- and post-processing of each data portal invocation\&. 
.PP
Definition at line 556 of file DataPortal\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
