.TH "Csla.Test.Serialization.ClaimsPrincipalTests" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.Serialization.ClaimsPrincipalTests
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBCloneClaimsPrincipal\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 24 of file ClaimsPrincipalTests\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Csla\&.Test\&.Serialization\&.ClaimsPrincipalTests\&.CloneClaimsPrincipal ()"

.PP
Definition at line 27 of file ClaimsPrincipalTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
