.TH "Csla.Test.ValidationRules.AsyncRuleTests" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.ValidationRules.AsyncRuleTests
.SH SYNOPSIS
.br
.PP
.PP
Inherits TestBase\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBTestAsyncRulesValid\fP ()"
.br
.ti -1c
.RI "void \fBTestAsyncRuleError\fP ()"
.br
.ti -1c
.RI "void \fBInvalidAsyncRule\fP ()"
.br
.ti -1c
.RI "void \fBValidateMultipleObjectsSimultaneously\fP ()"
.br
.ti -1c
.RI "void \fBTestAsyncRulesAndSyncRulesValid\fP ()"
.br
.ti -1c
.RI "async Task \fBTestAsyncAwaitRule\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 33 of file AsyncRuleTests\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Csla\&.Test\&.ValidationRules\&.AsyncRuleTests\&.InvalidAsyncRule ()"

.PP
Definition at line 71 of file AsyncRuleTests\&.cs\&.
.SS "async Task Csla\&.Test\&.ValidationRules\&.AsyncRuleTests\&.TestAsyncAwaitRule ()"

.PP
Definition at line 145 of file AsyncRuleTests\&.cs\&.
.SS "void Csla\&.Test\&.ValidationRules\&.AsyncRuleTests\&.TestAsyncRuleError ()"

.PP
Definition at line 53 of file AsyncRuleTests\&.cs\&.
.SS "void Csla\&.Test\&.ValidationRules\&.AsyncRuleTests\&.TestAsyncRulesAndSyncRulesValid ()"

.PP
Definition at line 121 of file AsyncRuleTests\&.cs\&.
.SS "void Csla\&.Test\&.ValidationRules\&.AsyncRuleTests\&.TestAsyncRulesValid ()"

.PP
Definition at line 36 of file AsyncRuleTests\&.cs\&.
.SS "void Csla\&.Test\&.ValidationRules\&.AsyncRuleTests\&.ValidateMultipleObjectsSimultaneously ()"

.PP
Definition at line 88 of file AsyncRuleTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
