.TH "Csla.Test.ChildChanged.SingleChild" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.ChildChanged.SingleChild
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.BusinessBase< SingleChild >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSingleChild\fP ()"
.br
.ti -1c
.RI "\fBSingleChild\fP (bool child)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBName\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBSingleRoot\fP \fBChild\fP\fC [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 18 of file SingleChild\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Csla\&.Test\&.ChildChanged\&.SingleChild\&.SingleChild ()"

.PP
Definition at line 20 of file SingleChild\&.cs\&.
.SS "Csla\&.Test\&.ChildChanged\&.SingleChild\&.SingleChild (bool child)"

.PP
Definition at line 23 of file SingleChild\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "\fBSingleRoot\fP Csla\&.Test\&.ChildChanged\&.SingleChild\&.Child\fC [get]\fP"

.PP
Definition at line 37 of file SingleChild\&.cs\&.
.SS "string Csla\&.Test\&.ChildChanged\&.SingleChild\&.Name\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 30 of file SingleChild\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
