.TH "Csla.Configuration.CslaConfiguration" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Configuration.CslaConfiguration \- Use this type to configure the settings for CSLA \&.NET\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.Configuration\&.ICslaConfiguration\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCslaConfiguration\fP \fBWebContextManager\fP (\fBIContextManager\fP contextManager)"
.br
.RI "Sets the web context manager\&. "
.ti -1c
.RI "\fBCslaConfiguration\fP \fBContextManager\fP (\fBIContextManager\fP contextManager)"
.br
.RI "Sets the context manager\&. "
.ti -1c
.RI "\fBCslaConfiguration\fP \fBContextManager\fP (Type contextManagerType)"
.br
.RI "Sets the context manager type\&. "
.ti -1c
.RI "\fBCslaConfiguration\fP \fBUseReflectionFallback\fP (bool value)"
.br
.RI "Sets a value indicating whether CSLA should fallback to using reflection instead of System\&.Linq\&.Expressions (true, default)\&. "
.ti -1c
.RI "\fBCslaConfiguration\fP \fBPropertyChangedMode\fP (ApplicationContext\&.PropertyChangedModes mode)"
.br
.RI "Sets a value specifying how CSLA \&.NET should raise PropertyChanged events\&. "
.ti -1c
.RI "\fBCslaConfiguration\fP \fBVersionRoutingTag\fP (string version)"
.br
.RI "Sets a value representing the application version for use in server-side data portal routing\&. "
.ti -1c
.RI "\fBCslaConfiguration\fP \fBRuleSet\fP (string ruleSet)"
.br
.RI "Sets the RuleSet name to use for static HasPermission calls\&. "
.ti -1c
.RI "\fBCslaConfiguration\fP \fBPropertyInfoFactory\fP (string typeName)"
.br
.RI "Sets the factory type that creates \fBPropertyInfo\fP objects\&. "
.ti -1c
.RI "\fBCslaConfiguration\fP \fBDefaultServiceProvider\fP (IServiceProvider defaultServiceProvider)"
.br
.RI "Sets the default service provider which \fBCsla\fP will use\&. "
.ti -1c
.RI "\fBCslaConfiguration\fP \fBSettingsChanged\fP ()"
.br
.RI "Resets any ApplicationContext settings so they re-read their configuration from AppSettings on next use\&. "
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBCslaConfiguration\fP \fBConfigure\fP ()"
.br
.RI "Gets an instance of the configuration root type\&. "
.in -1c
.SH "Detailed Description"
.PP 
Use this type to configure the settings for CSLA \&.NET\&. 


.PP
Definition at line 30 of file CslaConfiguration\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "static \fBCslaConfiguration\fP Csla\&.Configuration\&.CslaConfiguration\&.Configure ()\fC [static]\fP"

.PP
Gets an instance of the configuration root type\&. 
.PP
Definition at line 35 of file CslaConfiguration\&.cs\&.
.SS "\fBCslaConfiguration\fP Csla\&.Configuration\&.CslaConfiguration\&.ContextManager (\fBIContextManager\fP contextManager)"

.PP
Sets the context manager\&. 
.PP
\fBParameters\fP
.RS 4
\fIcontextManager\fP Context manager instance\&.
.RE
.PP
\fBReturns\fP
.RS 4
ContextManager normally defaults to the correct value\&. Override for non-standard or custom behaviors\&. 
.RE
.PP

.PP
Definition at line 65 of file CslaConfiguration\&.cs\&.
.SS "\fBCslaConfiguration\fP Csla\&.Configuration\&.CslaConfiguration\&.ContextManager (Type contextManagerType)"

.PP
Sets the context manager type\&. 
.PP
\fBParameters\fP
.RS 4
\fIcontextManagerType\fP Context manager type\&.
.RE
.PP
\fBReturns\fP
.RS 4
ContextManager normally defaults to the correct value\&. Override for non-standard or custom behaviors\&. 
.RE
.PP

.PP
Definition at line 79 of file CslaConfiguration\&.cs\&.
.SS "\fBCslaConfiguration\fP Csla\&.Configuration\&.CslaConfiguration\&.DefaultServiceProvider (IServiceProvider defaultServiceProvider)"

.PP
Sets the default service provider which \fBCsla\fP will use\&. 
.PP
\fBParameters\fP
.RS 4
\fIdefaultServiceProvider\fP IServiceProvider instance
.RE
.PP

.PP
Definition at line 157 of file CslaConfiguration\&.cs\&.
.SS "\fBCslaConfiguration\fP Csla\&.Configuration\&.CslaConfiguration\&.PropertyChangedMode (ApplicationContext\&.PropertyChangedModes mode)"

.PP
Sets a value specifying how CSLA \&.NET should raise PropertyChanged events\&. 
.PP
\fBParameters\fP
.RS 4
\fImode\fP Property changed mode
.RE
.PP

.PP
Definition at line 102 of file CslaConfiguration\&.cs\&.
.SS "\fBCslaConfiguration\fP Csla\&.Configuration\&.CslaConfiguration\&.PropertyInfoFactory (string typeName)"

.PP
Sets the factory type that creates \fBPropertyInfo\fP objects\&. 
.PP
\fBParameters\fP
.RS 4
\fItypeName\fP Factory type name
.RE
.PP

.PP
Definition at line 146 of file CslaConfiguration\&.cs\&.
.SS "\fBCslaConfiguration\fP Csla\&.Configuration\&.CslaConfiguration\&.RuleSet (string ruleSet)"

.PP
Sets the RuleSet name to use for static HasPermission calls\&. 
.PP
\fBParameters\fP
.RS 4
\fIruleSet\fP The rule set\&.
.RE
.PP

.PP
Definition at line 136 of file CslaConfiguration\&.cs\&.
.SS "\fBCslaConfiguration\fP Csla\&.Configuration\&.CslaConfiguration\&.SettingsChanged ()"

.PP
Resets any ApplicationContext settings so they re-read their configuration from AppSettings on next use\&. 
.PP
Definition at line 170 of file CslaConfiguration\&.cs\&.
.SS "\fBCslaConfiguration\fP Csla\&.Configuration\&.CslaConfiguration\&.UseReflectionFallback (bool value)"

.PP
Sets a value indicating whether CSLA should fallback to using reflection instead of System\&.Linq\&.Expressions (true, default)\&. 
.PP
\fBParameters\fP
.RS 4
\fIvalue\fP Value
.RE
.PP

.PP
Definition at line 91 of file CslaConfiguration\&.cs\&.
.SS "\fBCslaConfiguration\fP Csla\&.Configuration\&.CslaConfiguration\&.VersionRoutingTag (string version)"

.PP
Sets a value representing the application version for use in server-side data portal routing\&. 
.PP
\fBParameters\fP
.RS 4
\fIversion\fP Application version used to create data portal routing tag (can not contain '-')\&. 
.RE
.PP
.PP
If this value is set then you must use the \&.NET \fBCore\fP server-side Http data portal endpoint as a router so the request can be routed to another app server that is running the correct version of the application's assemblies\&. 
.PP
Definition at line 123 of file CslaConfiguration\&.cs\&.
.SS "\fBCslaConfiguration\fP Csla\&.Configuration\&.CslaConfiguration\&.WebContextManager (\fBIContextManager\fP contextManager)"

.PP
Sets the web context manager\&. 
.PP
\fBParameters\fP
.RS 4
\fIcontextManager\fP \fBWeb\fP context manager instance
.RE
.PP
.PP
Will use default WebContextManager\&. Only need to set for non-default WebContextManager\&. 
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
Definition at line 50 of file CslaConfiguration\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
