.TH "Csla.Test.DataBinding.ChildEntityList" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.DataBinding.ChildEntityList
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.BusinessBindingListBase< ChildEntityList, ChildEntity >\fP, and \fBCsla\&.BusinessBindingListBase< ChildEntityList, ChildEntity >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBChildEntityList\fP ()"
.br
.ti -1c
.RI "\fBChildEntityList\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBChildEntityList\fP \fBNewChildEntityList\fP ()"
.br
.ti -1c
.RI "static \fBChildEntityList\fP \fBGetList\fP ()"
.br
.ti -1c
.RI "static \fBChildEntityList\fP \fBNewChildEntityList\fP ()"
.br
.ti -1c
.RI "static \fBChildEntityList\fP \fBGetList\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 16 of file csla\&.netcore\&.test/DataBinding/ChildEntityList\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Csla\&.Test\&.DataBinding\&.ChildEntityList\&.ChildEntityList ()"

.PP
Definition at line 18 of file csla\&.netcore\&.test/DataBinding/ChildEntityList\&.cs\&.
.SS "Csla\&.Test\&.DataBinding\&.ChildEntityList\&.ChildEntityList ()"

.PP
Definition at line 18 of file Csla\&.test/DataPortal/ChildEntityList\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "static \fBChildEntityList\fP Csla\&.Test\&.DataBinding\&.ChildEntityList\&.GetList ()\fC [static]\fP"

.PP
Definition at line 50 of file csla\&.netcore\&.test/DataBinding/ChildEntityList\&.cs\&.
.SS "static \fBChildEntityList\fP Csla\&.Test\&.DataBinding\&.ChildEntityList\&.GetList ()\fC [static]\fP"

.PP
Definition at line 50 of file Csla\&.test/DataPortal/ChildEntityList\&.cs\&.
.SS "static \fBChildEntityList\fP Csla\&.Test\&.DataBinding\&.ChildEntityList\&.NewChildEntityList ()\fC [static]\fP"

.PP
Definition at line 25 of file csla\&.netcore\&.test/DataBinding/ChildEntityList\&.cs\&.
.SS "static \fBChildEntityList\fP Csla\&.Test\&.DataBinding\&.ChildEntityList\&.NewChildEntityList ()\fC [static]\fP"

.PP
Definition at line 25 of file Csla\&.test/DataPortal/ChildEntityList\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
