.TH "Csla.Test.ValidationRules.BrokenRulesMergeRoot" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.ValidationRules.BrokenRulesMergeRoot
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.BusinessBase< BrokenRulesMergeRoot >\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRuleBroken\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBValidate\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBPropertyInfo\fP< string > \fBTest1Property\fP = RegisterProperty<string>(c => c\&.Test1)"
.br
.ti -1c
.RI "static \fBPropertyInfo\fP< string > \fBTest2Property\fP = RegisterProperty<string>(c => c\&.Test2)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBAddBusinessRules\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBTest1\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBTest2\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "override \fBBrokenRulesCollection\fP \fBBrokenRulesCollection\fP\fC [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 17 of file BrokenRulesMergeRoot\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override void Csla\&.Test\&.ValidationRules\&.BrokenRulesMergeRoot\&.AddBusinessRules ()\fC [protected]\fP"

.PP
Definition at line 33 of file BrokenRulesMergeRoot\&.cs\&.
.SS "void Csla\&.Test\&.ValidationRules\&.BrokenRulesMergeRoot\&.Validate ()"

.PP
Definition at line 39 of file BrokenRulesMergeRoot\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBPropertyInfo\fP<string> Csla\&.Test\&.ValidationRules\&.BrokenRulesMergeRoot\&.Test1Property = RegisterProperty<string>(c => c\&.Test1)\fC [static]\fP"

.PP
Definition at line 19 of file BrokenRulesMergeRoot\&.cs\&.
.SS "\fBPropertyInfo\fP<string> Csla\&.Test\&.ValidationRules\&.BrokenRulesMergeRoot\&.Test2Property = RegisterProperty<string>(c => c\&.Test2)\fC [static]\fP"

.PP
Definition at line 26 of file BrokenRulesMergeRoot\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "override \fBBrokenRulesCollection\fP Csla\&.Test\&.ValidationRules\&.BrokenRulesMergeRoot\&.BrokenRulesCollection\fC [get]\fP"

.PP
Definition at line 56 of file BrokenRulesMergeRoot\&.cs\&.
.SS "string Csla\&.Test\&.ValidationRules\&.BrokenRulesMergeRoot\&.Test1\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 20 of file BrokenRulesMergeRoot\&.cs\&.
.SS "string Csla\&.Test\&.ValidationRules\&.BrokenRulesMergeRoot\&.Test2\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 27 of file BrokenRulesMergeRoot\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
