.TH "Csla.Blazor.Test.EditContextCslaExtensionsTests" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Blazor.Test.EditContextCslaExtensionsTests
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBValidateModel_EmptyLastName_OneValidationMessage\fP ()"
.br
.ti -1c
.RI "void \fBValidateModel_ShortFirstName_NoValidationMessages\fP ()"
.br
.ti -1c
.RI "void \fBValidateModel_ShortLastName_NoValidationMessages\fP ()"
.br
.ti -1c
.RI "void \fBValidateModel_ExcessiveFirstNameEmptyLastName_TwoValidationMessages\fP ()"
.br
.ti -1c
.RI "void \fBValidateModel_NeitherTelephoneProvided_TwoValidationMessages\fP ()"
.br
.ti -1c
.RI "void \fBValidateModel_EmptyChildEmailAddress_OneValidationMessage\fP ()"
.br
.ti -1c
.RI "void \fBValidateField_ExcessiveFirstNameEmptyLastName_OneValidationMessageForFirstName\fP ()"
.br
.ti -1c
.RI "void \fBValidateField_NeitherTelephoneProvided_OneValidationMessageForHomeTelephone\fP ()"
.br
.ti -1c
.RI "void \fBValidateField_ShortFirstName_NoValidationMessagesForFirstName\fP ()"
.br
.ti -1c
.RI "void \fBValidateField_ShortLastName_NoValidationMessagesForLastName\fP ()"
.br
.ti -1c
.RI "void \fBValidateField_MissingEmailAddress1_OneValidationMessageForEmailAddress1\fP ()"
.br
.ti -1c
.RI "void \fBValidateField_ValidEmailAddress1_NoValidationMessagesForEmailAddress1\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 10 of file EditContextCslaExtensionsTests\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Csla\&.Blazor\&.Test\&.EditContextCslaExtensionsTests\&.ValidateField_ExcessiveFirstNameEmptyLastName_OneValidationMessageForFirstName ()"

.PP
Definition at line 136 of file EditContextCslaExtensionsTests\&.cs\&.
.SS "void Csla\&.Blazor\&.Test\&.EditContextCslaExtensionsTests\&.ValidateField_MissingEmailAddress1_OneValidationMessageForEmailAddress1 ()"

.PP
Definition at line 218 of file EditContextCslaExtensionsTests\&.cs\&.
.SS "void Csla\&.Blazor\&.Test\&.EditContextCslaExtensionsTests\&.ValidateField_NeitherTelephoneProvided_OneValidationMessageForHomeTelephone ()"

.PP
Definition at line 157 of file EditContextCslaExtensionsTests\&.cs\&.
.SS "void Csla\&.Blazor\&.Test\&.EditContextCslaExtensionsTests\&.ValidateField_ShortFirstName_NoValidationMessagesForFirstName ()"

.PP
Definition at line 178 of file EditContextCslaExtensionsTests\&.cs\&.
.SS "void Csla\&.Blazor\&.Test\&.EditContextCslaExtensionsTests\&.ValidateField_ShortLastName_NoValidationMessagesForLastName ()"

.PP
Definition at line 198 of file EditContextCslaExtensionsTests\&.cs\&.
.SS "void Csla\&.Blazor\&.Test\&.EditContextCslaExtensionsTests\&.ValidateField_ValidEmailAddress1_NoValidationMessagesForEmailAddress1 ()"

.PP
Definition at line 239 of file EditContextCslaExtensionsTests\&.cs\&.
.SS "void Csla\&.Blazor\&.Test\&.EditContextCslaExtensionsTests\&.ValidateModel_EmptyChildEmailAddress_OneValidationMessage ()"

.PP
Definition at line 116 of file EditContextCslaExtensionsTests\&.cs\&.
.SS "void Csla\&.Blazor\&.Test\&.EditContextCslaExtensionsTests\&.ValidateModel_EmptyLastName_OneValidationMessage ()"

.PP
Definition at line 14 of file EditContextCslaExtensionsTests\&.cs\&.
.SS "void Csla\&.Blazor\&.Test\&.EditContextCslaExtensionsTests\&.ValidateModel_ExcessiveFirstNameEmptyLastName_TwoValidationMessages ()"

.PP
Definition at line 74 of file EditContextCslaExtensionsTests\&.cs\&.
.SS "void Csla\&.Blazor\&.Test\&.EditContextCslaExtensionsTests\&.ValidateModel_NeitherTelephoneProvided_TwoValidationMessages ()"

.PP
Definition at line 95 of file EditContextCslaExtensionsTests\&.cs\&.
.SS "void Csla\&.Blazor\&.Test\&.EditContextCslaExtensionsTests\&.ValidateModel_ShortFirstName_NoValidationMessages ()"

.PP
Definition at line 34 of file EditContextCslaExtensionsTests\&.cs\&.
.SS "void Csla\&.Blazor\&.Test\&.EditContextCslaExtensionsTests\&.ValidateModel_ShortLastName_NoValidationMessages ()"

.PP
Definition at line 54 of file EditContextCslaExtensionsTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
