.TH "Csla.Test.Windows" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.Windows
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBActionExtenderTests\fP"
.br
.ti -1c
.RI "class \fBBindingRefreshTests\fP"
.br
.ti -1c
.RI "class \fBEditablePerson\fP"
.br
.ti -1c
.RI "class \fBPersonForm\fP"
.br
.ti -1c
.RI "class \fBReadWriteAuthorizationTests\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
