.TH "Csla.Server.AuthorizeRequest" 3 "Thu Jul 22 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Server.AuthorizeRequest \- Object containing information about the client request to the data portal\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBCheckPermissions\fP ()"
.br
.RI "Checks that the current identity has permission to carry out this operation, and if not throws a \fCSecurityException\fP\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "Type \fBObjectType\fP\fC [get]\fP"
.br
.RI "Gets the type of business object affected by the client request\&. "
.ti -1c
.RI "object \fBRequestObject\fP\fC [get]\fP"
.br
.RI "Gets a reference to the criteria or business object passed from the client to the server\&. "
.ti -1c
.RI "\fBDataPortalOperations\fP \fBOperation\fP\fC [get]\fP"
.br
.RI "Gets the data portal operation requested by the client\&. "
.in -1c
.SH "Detailed Description"
.PP 
Object containing information about the client request to the data portal\&. 


.PP
Definition at line 19 of file AuthorizeRequest\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Csla\&.Server\&.AuthorizeRequest\&.CheckPermissions ()"

.PP
Checks that the current identity has permission to carry out this operation, and if not throws a \fCSecurityException\fP\&. 
.PP
\fBExceptions\fP
.RS 4
\fISecurityException\fP Thrown if the current principal does not have permission to carry out this operation\&.
.RE
.PP

.PP
Definition at line 51 of file AuthorizeRequest\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "Type Csla\&.Server\&.AuthorizeRequest\&.ObjectType\fC [get]\fP"

.PP
Gets the type of business object affected by the client request\&. 
.PP
Definition at line 25 of file AuthorizeRequest\&.cs\&.
.SS "\fBDataPortalOperations\fP Csla\&.Server\&.AuthorizeRequest\&.Operation\fC [get]\fP"

.PP
Gets the data portal operation requested by the client\&. 
.PP
Definition at line 36 of file AuthorizeRequest\&.cs\&.
.SS "object Csla\&.Server\&.AuthorizeRequest\&.RequestObject\fC [get]\fP"

.PP
Gets a reference to the criteria or business object passed from the client to the server\&. 
.PP
Definition at line 31 of file AuthorizeRequest\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
