.TH "Csla.Test.Threading.BackgroundWorkerSyncContextHelper" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.Threading.BackgroundWorkerSyncContextHelper \- Helps ensure the proper behaviour of the BackgroundWorker\&.  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBInit\fP ()"
.br
.ti -1c
.RI "static void \fBClearException\fP ()"
.br
.RI "clears any exceptions so as not to confuse other tests\&. "
.ti -1c
.RI "static void \fBDumpExceptionsAndThrow\fP ()"
.br
.RI "Dumps all the queued exceptions, and \fIthrows\fP the last exception that was thrown "
.ti -1c
.RI "static void \fBCleanup\fP ()"
.br
.RI "Shuts town the disptacher thread for a clean shutdown\&. "
.ti -1c
.RI "static void \fBDoTests\fP (Action test)"
.br
.ti -1c
.RI "static void \fBPumpDispatcher\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "static Dispatcher \fBDispatcher\fP\fC [get]\fP"
.br
.in -1c
.SS "Events"

.in +1c
.ti -1c
.RI "static ThreadStart \fBTestInitialize\fP"
.br
.ti -1c
.RI "static ThreadStart \fBTestCleanup\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Helps ensure the proper behaviour of the BackgroundWorker\&. 

Backgroundworker makes heavy use of the AsyncOperationManager & SynchronisationContext\&. When the default SynchronisationContext is used, it just invokes to callbacks on the current thread, not the UI thread\&.
.PP
To ensure real world testability of items using this class, we're using a dispatcher (a WPF, but UI Agnostic class) to provide the ability to call back into the thread that starts it\&.
.PP
Dispatchers are a message pump, so block on their RunMethod -- this means we need to spin up our own thread, an queue items into that as tests that are synchronously invoked\&.
.PP
Definition at line 27 of file BackgroundWorkerSyncContextHelper\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "static void Csla\&.Test\&.Threading\&.BackgroundWorkerSyncContextHelper\&.Cleanup ()\fC [static]\fP"

.PP
Shuts town the disptacher thread for a clean shutdown\&. 
.PP
Definition at line 122 of file BackgroundWorkerSyncContextHelper\&.cs\&.
.SS "static void Csla\&.Test\&.Threading\&.BackgroundWorkerSyncContextHelper\&.ClearException ()\fC [static]\fP"

.PP
clears any exceptions so as not to confuse other tests\&. 
.PP
Definition at line 87 of file BackgroundWorkerSyncContextHelper\&.cs\&.
.SS "static void Csla\&.Test\&.Threading\&.BackgroundWorkerSyncContextHelper\&.DoTests (Action test)\fC [static]\fP"

.PP
Definition at line 136 of file BackgroundWorkerSyncContextHelper\&.cs\&.
.SS "static void Csla\&.Test\&.Threading\&.BackgroundWorkerSyncContextHelper\&.DumpExceptionsAndThrow ()\fC [static]\fP"

.PP
Dumps all the queued exceptions, and \fIthrows\fP the last exception that was thrown 
.PP
Definition at line 95 of file BackgroundWorkerSyncContextHelper\&.cs\&.
.SS "static void Csla\&.Test\&.Threading\&.BackgroundWorkerSyncContextHelper\&.Init ()\fC [static]\fP"

.PP
Definition at line 34 of file BackgroundWorkerSyncContextHelper\&.cs\&.
.SS "static void Csla\&.Test\&.Threading\&.BackgroundWorkerSyncContextHelper\&.PumpDispatcher ()\fC [static]\fP"

.PP
Definition at line 162 of file BackgroundWorkerSyncContextHelper\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "Dispatcher Csla\&.Test\&.Threading\&.BackgroundWorkerSyncContextHelper\&.Dispatcher\fC [static]\fP, \fC [get]\fP"

.PP
Definition at line 127 of file BackgroundWorkerSyncContextHelper\&.cs\&.
.SH "Event Documentation"
.PP 
.SS "ThreadStart Csla\&.Test\&.Threading\&.BackgroundWorkerSyncContextHelper\&.TestCleanup\fC [static]\fP"

.PP
Definition at line 134 of file BackgroundWorkerSyncContextHelper\&.cs\&.
.SS "ThreadStart Csla\&.Test\&.Threading\&.BackgroundWorkerSyncContextHelper\&.TestInitialize\fC [static]\fP"

.PP
Definition at line 132 of file BackgroundWorkerSyncContextHelper\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
