.TH "Csla.Test.WellKnownValues" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.WellKnownValues
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static string \fBEntityConnectionWithMissingDBConnectionStringName\fP = 'DataPortalTestDatabaseEntitiesWithInvalidDBValue'"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "static string \fBEntityConnectionWithMissingDB\fP\fC [get]\fP"
.br
.ti -1c
.RI "static string \fBDataPortalTestDatabaseEntities\fP\fC [get]\fP"
.br
.ti -1c
.RI "static string \fBDataPortalTestDatabaseWithInvalidDBValue\fP\fC [get]\fP"
.br
.ti -1c
.RI "static string \fBDataPortalTestDatabase\fP\fC [get]\fP"
.br
.ti -1c
.RI "static string \fBTestLinqToSqlContextDataContext\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 11 of file WellKnownValues\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "string Csla\&.Test\&.WellKnownValues\&.EntityConnectionWithMissingDBConnectionStringName = 'DataPortalTestDatabaseEntitiesWithInvalidDBValue'\fC [static]\fP"

.PP
Definition at line 24 of file WellKnownValues\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "string Csla\&.Test\&.WellKnownValues\&.DataPortalTestDatabase\fC [static]\fP, \fC [get]\fP"

.PP
Definition at line 29 of file WellKnownValues\&.cs\&.
.SS "string Csla\&.Test\&.WellKnownValues\&.DataPortalTestDatabaseEntities\fC [static]\fP, \fC [get]\fP"

.PP
Definition at line 26 of file WellKnownValues\&.cs\&.
.SS "string Csla\&.Test\&.WellKnownValues\&.DataPortalTestDatabaseWithInvalidDBValue\fC [static]\fP, \fC [get]\fP"

.PP
Definition at line 27 of file WellKnownValues\&.cs\&.
.SS "string Csla\&.Test\&.WellKnownValues\&.EntityConnectionWithMissingDB\fC [static]\fP, \fC [get]\fP"

.PP
Definition at line 25 of file WellKnownValues\&.cs\&.
.SS "string Csla\&.Test\&.WellKnownValues\&.TestLinqToSqlContextDataContext\fC [static]\fP, \fC [get]\fP"

.PP
Definition at line 30 of file WellKnownValues\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
