.TH "Csla.Testing.Business.EditableRootListTests.RootSingleItemsList" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Testing.Business.EditableRootListTests.RootSingleItemsList
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.DynamicBindingListBase< SingleItem >\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFetchCriteria\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBDataPortal_Fetch\fP (\fBFetchCriteria\fP criteria)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 21 of file RootSingleItemsList\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Csla\&.Testing\&.Business\&.EditableRootListTests\&.RootSingleItemsList\&.DataPortal_Fetch (\fBFetchCriteria\fP criteria)\fC [protected]\fP"

.PP
Definition at line 51 of file RootSingleItemsList\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
