.TH "Csla.Validation.CommonRules.IntegerMaxValueRuleArgs" 3 "Thu Jul 22 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Validation.CommonRules.IntegerMaxValueRuleArgs \- Custom \fBRuleArgs\fP object required by the IntegerMaxValue rule method\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.Validation\&.DecoratedRuleArgs\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBIntegerMaxValueRuleArgs\fP (string propertyName, int maxValue)"
.br
.RI "Create a new object\&. "
.ti -1c
.RI "\fBIntegerMaxValueRuleArgs\fP (\fBCore\&.IPropertyInfo\fP propertyInfo, int maxValue)"
.br
.RI "Create a new object\&. "
.ti -1c
.RI "\fBIntegerMaxValueRuleArgs\fP (string propertyName, string friendlyName, int maxValue)"
.br
.RI "Create a new object\&. "
.ti -1c
.RI "\fBIntegerMaxValueRuleArgs\fP (string propertyName, int maxValue, string format)"
.br
.RI "Create a new object\&. "
.ti -1c
.RI "\fBIntegerMaxValueRuleArgs\fP (\fBCore\&.IPropertyInfo\fP propertyInfo, int maxValue, string format)"
.br
.RI "Create a new object\&. "
.ti -1c
.RI "\fBIntegerMaxValueRuleArgs\fP (string propertyName, string friendlyName, int maxValue, string format)"
.br
.RI "Create a new object\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBMaxValue\fP\fC [get]\fP"
.br
.RI "Get the max value for the property\&. "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Custom \fBRuleArgs\fP object required by the IntegerMaxValue rule method\&. 


.PP
Definition at line 377 of file Csla\&.Validation\&.Shared/CommonRules\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Csla\&.Validation\&.CommonRules\&.IntegerMaxValueRuleArgs\&.IntegerMaxValueRuleArgs (string propertyName, int maxValue)"

.PP
Create a new object\&. 
.PP
\fBParameters\fP
.RS 4
\fIpropertyName\fP Name of the property\&.
.br
\fImaxValue\fP Maximum allowed value for the property\&.
.RE
.PP

.PP
Definition at line 392 of file Csla\&.Validation\&.Shared/CommonRules\&.cs\&.
.SS "Csla\&.Validation\&.CommonRules\&.IntegerMaxValueRuleArgs\&.IntegerMaxValueRuleArgs (\fBCore\&.IPropertyInfo\fP propertyInfo, int maxValue)"

.PP
Create a new object\&. 
.PP
\fBParameters\fP
.RS 4
\fIpropertyInfo\fP Property to validate\&.
.br
\fImaxValue\fP Maximum allowed value for the property\&.
.RE
.PP

.PP
Definition at line 404 of file Csla\&.Validation\&.Shared/CommonRules\&.cs\&.
.SS "Csla\&.Validation\&.CommonRules\&.IntegerMaxValueRuleArgs\&.IntegerMaxValueRuleArgs (string propertyName, string friendlyName, int maxValue)"

.PP
Create a new object\&. 
.PP
\fBParameters\fP
.RS 4
\fIpropertyName\fP Name of the property\&.
.br
\fIfriendlyName\fP A friendly name for the property, which will be used in place of the property name when creating the broken rule description string\&.
.br
\fImaxValue\fP Maximum allowed value for the property\&.
.RE
.PP

.PP
Definition at line 419 of file Csla\&.Validation\&.Shared/CommonRules\&.cs\&.
.SS "Csla\&.Validation\&.CommonRules\&.IntegerMaxValueRuleArgs\&.IntegerMaxValueRuleArgs (string propertyName, int maxValue, string format)"

.PP
Create a new object\&. 
.PP
\fBParameters\fP
.RS 4
\fIpropertyName\fP Name of the property\&.
.br
\fImaxValue\fP Maximum allowed value for the property\&.
.br
\fIformat\fP Format string for the max value value in the broken rule string\&.
.RE
.PP

.PP
Definition at line 434 of file Csla\&.Validation\&.Shared/CommonRules\&.cs\&.
.SS "Csla\&.Validation\&.CommonRules\&.IntegerMaxValueRuleArgs\&.IntegerMaxValueRuleArgs (\fBCore\&.IPropertyInfo\fP propertyInfo, int maxValue, string format)"

.PP
Create a new object\&. 
.PP
\fBParameters\fP
.RS 4
\fIpropertyInfo\fP Property to validate\&.
.br
\fImaxValue\fP Maximum allowed value for the property\&.
.br
\fIformat\fP Format string for the max value value in the broken rule string\&.
.RE
.PP

.PP
Definition at line 448 of file Csla\&.Validation\&.Shared/CommonRules\&.cs\&.
.SS "Csla\&.Validation\&.CommonRules\&.IntegerMaxValueRuleArgs\&.IntegerMaxValueRuleArgs (string propertyName, string friendlyName, int maxValue, string format)"

.PP
Create a new object\&. 
.PP
\fBParameters\fP
.RS 4
\fIpropertyName\fP Name of the property\&.
.br
\fIfriendlyName\fP A friendly name for the property, which will be used in place of the property name when creating the broken rule description string\&.
.br
\fImaxValue\fP Maximum allowed value for the property\&.
.br
\fIformat\fP Format string for the max value value in the broken rule string\&.
.RE
.PP

.PP
Definition at line 465 of file Csla\&.Validation\&.Shared/CommonRules\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "int Csla\&.Validation\&.CommonRules\&.IntegerMaxValueRuleArgs\&.MaxValue\fC [get]\fP"

.PP
Get the max value for the property\&. 
.PP
Definition at line 382 of file Csla\&.Validation\&.Shared/CommonRules\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
