.TH "Csla.Test.PropertyGetSet.EditableGetSetBase< T >" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.PropertyGetSet.EditableGetSetBase< T >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.Test\&.PropertyGetSet\&.EditableGetSetTopBase< T >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEditableGetSetBase\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBBase\fP\fC [get, set]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
\fBType Constraints\fP
.TP
\fIT\fP : \fI\fBEditableGetSetBase\fP<T>\fP
.PP
Definition at line 18 of file EditableGetSetBase\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBCsla\&.Test\&.PropertyGetSet\&.EditableGetSetBase\fP< T >\&.\fBEditableGetSetBase\fP ()"

.PP
Definition at line 23 of file EditableGetSetBase\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "string \fBCsla\&.Test\&.PropertyGetSet\&.EditableGetSetBase\fP< T >\&.Base\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 29 of file EditableGetSetBase\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
