.TH "Csla.Test.SortedBindingList.MyChildren" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.SortedBindingList.MyChildren
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.BusinessBindingListBase< MyChildren, MyChild >\fP\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override object \fBAddNewCore\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 215 of file SortedBindingListTests\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override object Csla\&.Test\&.SortedBindingList\&.MyChildren\&.AddNewCore ()\fC [protected]\fP"

.PP
Definition at line 218 of file SortedBindingListTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
