.TH "Csla.Data" 3 "Thu Jul 22 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Data
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBEF6\fP"
.br
.ti -1c
.RI "namespace \fBEntityFrameworkCore\fP"
.br
.ti -1c
.RI "namespace \fBSqlClient\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBConnectionManager\fP"
.br
.RI "Provides an automated way to reuse open database connections within the context of a single data portal operation\&. "
.ti -1c
.RI "class \fBContextManager\fP"
.br
.RI "Provides an automated way to reuse LINQ data context objects within the context of a single data portal operation\&. "
.ti -1c
.RI "class \fBDataMap\fP"
.br
.RI "Defines a mapping between two sets of properties/fields for use by DataMapper\&. "
.ti -1c
.RI "class \fBDataMapper\fP"
.br
.RI "Map data from a source into a target object by copying public property values\&. "
.ti -1c
.RI "class \fBDataServiceContextManager\fP"
.br
.RI "Provides an automated way to reuse an ADO\&.NET \fBData\fP Services context object within the context of a single data portal operation\&. "
.ti -1c
.RI "class \fBObjectAdapter\fP"
.br
.RI "An \fBObjectAdapter\fP is used to convert data in an object or collection into a DataTable\&. "
.ti -1c
.RI "class \fBObjectContextManager\fP"
.br
.RI "Provides an automated way to reuse Entity Framework object context objects within the context of a single data portal operation\&. "
.ti -1c
.RI "class \fBSafeDataReader\fP"
.br
.RI "This is an IDataReader that 'fixes' any null values before they are returned to our business code\&. "
.ti -1c
.RI "class \fBServiceClientManager\fP"
.br
.RI "Provides an automated way to reuse a service client proxy objects within the context of a single data portal operation\&. "
.ti -1c
.RI "class \fBTransactionManager\fP"
.br
.RI "Provides an automated way to reuse open database connections and associated ADO\&.NET transactions within the context of a single data portal operation\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
