.TH "cslalighttest.Stereotypes.TestCriteria" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cslalighttest.Stereotypes.TestCriteria
.SH SYNOPSIS
.br
.PP
.PP
Inherits TestBase\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBCustomCriteria\fP ()"
.br
.ti -1c
.RI "void \fBSerializeCriteria\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 31 of file TestCriteria\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void cslalighttest\&.Stereotypes\&.TestCriteria\&.CustomCriteria ()"

.PP
Definition at line 34 of file TestCriteria\&.cs\&.
.SS "void cslalighttest\&.Stereotypes\&.TestCriteria\&.SerializeCriteria ()"

.PP
Definition at line 48 of file TestCriteria\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
