.TH "Csla.Test.LogicalExecutionLocation.LocationBusinessBase" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.LogicalExecutionLocation.LocationBusinessBase
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.BusinessBase< LocationBusinessBase >\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCheckRule\fP"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBLocationBusinessBase\fP \fBGetLocationBusinessBase\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBAddBusinessRules\fP ()"
.br
.ti -1c
.RI "void \fBDataPortal_Update\fP ()"
.br
.ti -1c
.RI "void \fBDataPortal_Fetch\fP ()"
.br
.ti -1c
.RI "void \fBDataPortal_Fetch\fP (int criteria)"
.br
.in -1c
.SS "Static Protected Attributes"

.in +1c
.ti -1c
.RI "static \fBPropertyInfo\fP< string > \fBDataProperty\fP = RegisterProperty<string>(new \fBPropertyInfo\fP<string>('Data'))"
.br
.ti -1c
.RI "static \fBPropertyInfo\fP< string > \fBRuleProperty\fP = RegisterProperty<string>(new \fBPropertyInfo\fP<string>('Rule'))"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBData\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBNestedData\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBRule\fP\fC [get, set]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 18 of file LocationBusinessBase\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override void Csla\&.Test\&.LogicalExecutionLocation\&.LocationBusinessBase\&.AddBusinessRules ()\fC [protected]\fP"

.PP
Definition at line 52 of file LocationBusinessBase\&.cs\&.
.SS "void Csla\&.Test\&.LogicalExecutionLocation\&.LocationBusinessBase\&.DataPortal_Fetch ()\fC [protected]\fP"

.PP
Definition at line 73 of file LocationBusinessBase\&.cs\&.
.SS "void Csla\&.Test\&.LogicalExecutionLocation\&.LocationBusinessBase\&.DataPortal_Fetch (int criteria)\fC [protected]\fP"

.PP
Definition at line 82 of file LocationBusinessBase\&.cs\&.
.SS "void Csla\&.Test\&.LogicalExecutionLocation\&.LocationBusinessBase\&.DataPortal_Update ()\fC [protected]\fP"

.PP
Definition at line 68 of file LocationBusinessBase\&.cs\&.
.SS "static \fBLocationBusinessBase\fP Csla\&.Test\&.LogicalExecutionLocation\&.LocationBusinessBase\&.GetLocationBusinessBase ()\fC [static]\fP"

.PP
Definition at line 44 of file LocationBusinessBase\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBPropertyInfo\fP<string> Csla\&.Test\&.LogicalExecutionLocation\&.LocationBusinessBase\&.DataProperty = RegisterProperty<string>(new \fBPropertyInfo\fP<string>('Data'))\fC [static]\fP, \fC [protected]\fP"

.PP
Definition at line 22 of file LocationBusinessBase\&.cs\&.
.SS "\fBPropertyInfo\fP<string> Csla\&.Test\&.LogicalExecutionLocation\&.LocationBusinessBase\&.RuleProperty = RegisterProperty<string>(new \fBPropertyInfo\fP<string>('Rule'))\fC [static]\fP, \fC [protected]\fP"

.PP
Definition at line 36 of file LocationBusinessBase\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "string Csla\&.Test\&.LogicalExecutionLocation\&.LocationBusinessBase\&.Data\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 23 of file LocationBusinessBase\&.cs\&.
.SS "string Csla\&.Test\&.LogicalExecutionLocation\&.LocationBusinessBase\&.NestedData\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 30 of file LocationBusinessBase\&.cs\&.
.SS "string Csla\&.Test\&.LogicalExecutionLocation\&.LocationBusinessBase\&.Rule\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 37 of file LocationBusinessBase\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
