.TH "Csla.Test.ValidationRules.CalculateFractionRule" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.ValidationRules.CalculateFractionRule
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.Rules\&.CommonRules\&.CommonBusinessRule\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCalculateFractionRule\fP (\fBPropertyInfo\fP< decimal > targetProperty, \fBPropertyInfo\fP< decimal > sourceProperty, decimal fraction)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBExecute\fP (\fBIRuleContext\fP context)"
.br
.RI "Business or validation rule implementation\&. "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 263 of file CascadeRoot\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Csla\&.Test\&.ValidationRules\&.CalculateFractionRule\&.CalculateFractionRule (\fBPropertyInfo\fP< decimal > targetProperty, \fBPropertyInfo\fP< decimal > sourceProperty, decimal fraction)"

.PP
Definition at line 268 of file CascadeRoot\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override void Csla\&.Test\&.ValidationRules\&.CalculateFractionRule\&.Execute (\fBIRuleContext\fP context)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Business or validation rule implementation\&. 
.PP
\fBParameters\fP
.RS 4
\fIcontext\fP Rule context object\&.
.RE
.PP

.PP
Reimplemented from \fBCsla\&.Rules\&.BusinessRule\fP\&.
.PP
Definition at line 279 of file CascadeRoot\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
