.TH "cslalighttest.Serialization.CustomMobileList" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cslalighttest.Serialization.CustomMobileList
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.Core\&.MobileBindingList< MockNonBusinessObject >\fP\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnGetChildren\fP (\fBSerializationInfo\fP info, \fBMobileFormatter\fP formatter)"
.br
.ti -1c
.RI "override void \fBOnSetChildren\fP (\fBSerializationInfo\fP info, \fBMobileFormatter\fP formatter)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 30 of file CustomMobileList\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override void cslalighttest\&.Serialization\&.CustomMobileList\&.OnGetChildren (\fBSerializationInfo\fP info, \fBMobileFormatter\fP formatter)\fC [protected]\fP"

.PP
Definition at line 64 of file CustomMobileList\&.cs\&.
.SS "override void cslalighttest\&.Serialization\&.CustomMobileList\&.OnSetChildren (\fBSerializationInfo\fP info, \fBMobileFormatter\fP formatter)\fC [protected]\fP"

.PP
Definition at line 68 of file CustomMobileList\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
