.TH "Csla.Security.UsernameCriteria" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Security.UsernameCriteria \- Criteria class for passing a username/password pair to a custom identity class\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.CriteriaBase< UsernameCriteria >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBUsernameCriteria\fP (string username, string password)"
.br
.RI "Creates a new instance of the object\&. "
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static readonly \fBPropertyInfo\fP< string > \fBUsernameProperty\fP = RegisterProperty<string>(c => c\&.Username)"
.br
.RI "Username property definition\&. "
.ti -1c
.RI "static readonly \fBPropertyInfo\fP< string > \fBPasswordProperty\fP = RegisterProperty<string>(c => c\&.Password)"
.br
.RI "Password property definition\&. "
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBUsernameCriteria\fP ()"
.br
.RI "Creates a new instance of the object\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBUsername\fP\fC [get]\fP"
.br
.RI "Username property definition\&. "
.ti -1c
.RI "string \fBPassword\fP\fC [get]\fP"
.br
.RI "Gets the password\&. "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Criteria class for passing a username/password pair to a custom identity class\&. 


.PP
Definition at line 19 of file UsernameCriteria\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Csla\&.Security\&.UsernameCriteria\&.UsernameCriteria (string username, string password)"

.PP
Creates a new instance of the object\&. 
.PP
\fBParameters\fP
.RS 4
\fIusername\fP Username value\&. 
.br
\fIpassword\fP Password value\&. 
.RE
.PP

.PP
Definition at line 56 of file UsernameCriteria\&.cs\&.
.SS "Csla\&.Security\&.UsernameCriteria\&.UsernameCriteria ()\fC [protected]\fP"

.PP
Creates a new instance of the object\&. 
.PP
Definition at line 69 of file UsernameCriteria\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "readonly \fBPropertyInfo\fP<string> Csla\&.Security\&.UsernameCriteria\&.PasswordProperty = RegisterProperty<string>(c => c\&.Password)\fC [static]\fP"

.PP
Password property definition\&. 
.PP
Definition at line 37 of file UsernameCriteria\&.cs\&.
.SS "readonly \fBPropertyInfo\fP<string> Csla\&.Security\&.UsernameCriteria\&.UsernameProperty = RegisterProperty<string>(c => c\&.Username)\fC [static]\fP"

.PP
Username property definition\&. 
.PP
Definition at line 24 of file UsernameCriteria\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "string Csla\&.Security\&.UsernameCriteria\&.Password\fC [get]\fP"

.PP
Gets the password\&. 
.PP
Definition at line 41 of file UsernameCriteria\&.cs\&.
.SS "string Csla\&.Security\&.UsernameCriteria\&.Username\fC [get]\fP"

.PP
Username property definition\&. 
.PP
Definition at line 28 of file UsernameCriteria\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
