.TH "Csla.Server.Hosts.WcfChannel.UseNetDataContractAttribute" 3 "Thu Jul 22 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Server.Hosts.WcfChannel.UseNetDataContractAttribute \- Specify that WCF should serialize objects in a \&.NET specific manner to as to preserve complex object references and to be able to deserialize the graph into the same type as the original objets\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Attribute, and IOperationBehavior\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBAddBindingParameters\fP (OperationDescription description, BindingParameterCollection parameters)"
.br
.RI "Not implemented\&. "
.ti -1c
.RI "void \fBApplyClientBehavior\fP (OperationDescription description, System\&.ServiceModel\&.Dispatcher\&.ClientOperation proxy)"
.br
.RI "Apply the client behavior by requiring the use of the NetDataContractSerializer\&. "
.ti -1c
.RI "void \fBApplyDispatchBehavior\fP (OperationDescription description, System\&.ServiceModel\&.Dispatcher\&.DispatchOperation dispatch)"
.br
.RI "Apply the dispatch behavior by requiring the use of the NetDataContractSerializer\&. "
.ti -1c
.RI "void \fBValidate\fP (OperationDescription description)"
.br
.RI "Not implemented\&. "
.in -1c
.SH "Detailed Description"
.PP 
Specify that WCF should serialize objects in a \&.NET specific manner to as to preserve complex object references and to be able to deserialize the graph into the same type as the original objets\&. 


.PP
Definition at line 21 of file UseNetDataContractAttribute\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Csla\&.Server\&.Hosts\&.WcfChannel\&.UseNetDataContractAttribute\&.AddBindingParameters (OperationDescription description, BindingParameterCollection parameters)"

.PP
Not implemented\&. 
.PP
\fBParameters\fP
.RS 4
\fIdescription\fP Not implemented\&.
.br
\fIparameters\fP Not implemented\&.
.RE
.PP

.PP
Definition at line 30 of file UseNetDataContractAttribute\&.cs\&.
.SS "void Csla\&.Server\&.Hosts\&.WcfChannel\&.UseNetDataContractAttribute\&.ApplyClientBehavior (OperationDescription description, System\&.ServiceModel\&.Dispatcher\&.ClientOperation proxy)"

.PP
Apply the client behavior by requiring the use of the NetDataContractSerializer\&. 
.PP
\fBParameters\fP
.RS 4
\fIdescription\fP Operation description\&.
.br
\fIproxy\fP Client operation object\&.
.RE
.PP

.PP
Definition at line 40 of file UseNetDataContractAttribute\&.cs\&.
.SS "void Csla\&.Server\&.Hosts\&.WcfChannel\&.UseNetDataContractAttribute\&.ApplyDispatchBehavior (OperationDescription description, System\&.ServiceModel\&.Dispatcher\&.DispatchOperation dispatch)"

.PP
Apply the dispatch behavior by requiring the use of the NetDataContractSerializer\&. 
.PP
\fBParameters\fP
.RS 4
\fIdescription\fP Operation description\&.
.br
\fIdispatch\fP Dispatch operation object\&.
.RE
.PP

.PP
Definition at line 51 of file UseNetDataContractAttribute\&.cs\&.
.SS "void Csla\&.Server\&.Hosts\&.WcfChannel\&.UseNetDataContractAttribute\&.Validate (OperationDescription description)"

.PP
Not implemented\&. 
.PP
\fBParameters\fP
.RS 4
\fIdescription\fP Not implemented\&.
.RE
.PP

.PP
Definition at line 60 of file UseNetDataContractAttribute\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
