.TH "csla.netcore.test.DataPortal.DashboardTests" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csla.netcore.test.DataPortal.DashboardTests
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBTestCleanup\fP ()"
.br
.ti -1c
.RI "void \fBDashboardDefaultIsNullDashboard\fP ()"
.br
.ti -1c
.RI "void \fBDashboardUseRealDashboard\fP ()"
.br
.ti -1c
.RI "async Task \fBDashboardSuccessCounter\fP ()"
.br
.ti -1c
.RI "async Task \fBDashboardFailureCounter\fP ()"
.br
.ti -1c
.RI "async Task \fBDashboardRecentActivity\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 28 of file DashboardTests\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void csla\&.netcore\&.test\&.DataPortal\&.DashboardTests\&.DashboardDefaultIsNullDashboard ()"

.PP
Definition at line 37 of file DashboardTests\&.cs\&.
.SS "async Task csla\&.netcore\&.test\&.DataPortal\&.DashboardTests\&.DashboardFailureCounter ()"

.PP
Definition at line 72 of file DashboardTests\&.cs\&.
.SS "async Task csla\&.netcore\&.test\&.DataPortal\&.DashboardTests\&.DashboardRecentActivity ()"

.PP
Definition at line 94 of file DashboardTests\&.cs\&.
.SS "async Task csla\&.netcore\&.test\&.DataPortal\&.DashboardTests\&.DashboardSuccessCounter ()"

.PP
Definition at line 54 of file DashboardTests\&.cs\&.
.SS "void csla\&.netcore\&.test\&.DataPortal\&.DashboardTests\&.DashboardUseRealDashboard ()"

.PP
Definition at line 45 of file DashboardTests\&.cs\&.
.SS "void csla\&.netcore\&.test\&.DataPortal\&.DashboardTests\&.TestCleanup ()"

.PP
Definition at line 31 of file DashboardTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
