.TH "Csla.Serialization.Mobile.CslaLegacyBinaryReader" 3 "Thu Jul 22 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Serialization.Mobile.CslaLegacyBinaryReader \- This is a legacy version of \fBCslaBinaryReader\fP\&. You should not use this type unless you have issues with the \fBCslaBinaryReader\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.Serialization\&.Mobile\&.ICslaReader\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCslaLegacyBinaryReader\fP ()"
.br
.RI "Creates new instance of \fBCslaLegacyBinaryReader\fP "
.ti -1c
.RI "List< \fBSerializationInfo\fP > \fBRead\fP (Stream serializationStream)"
.br
.RI "Read a data from a stream, typically MemoryStream, and convert it into a list of \fBSerializationInfo\fP objects "
.in -1c
.SH "Detailed Description"
.PP 
This is a legacy version of \fBCslaBinaryReader\fP\&. You should not use this type unless you have issues with the \fBCslaBinaryReader\fP\&. 


.PP
Definition at line 12 of file CslaLegacyBinaryReader\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Csla\&.Serialization\&.Mobile\&.CslaLegacyBinaryReader\&.CslaLegacyBinaryReader ()"

.PP
Creates new instance of \fBCslaLegacyBinaryReader\fP 
.PP
Definition at line 19 of file CslaLegacyBinaryReader\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "List<\fBSerializationInfo\fP> Csla\&.Serialization\&.Mobile\&.CslaLegacyBinaryReader\&.Read (Stream serializationStream)"

.PP
Read a data from a stream, typically MemoryStream, and convert it into a list of \fBSerializationInfo\fP objects 
.PP
\fBParameters\fP
.RS 4
\fIserializationStream\fP Stream to read the data from
.RE
.PP
\fBReturns\fP
.RS 4
List of \fBSerializationInfo\fP objects
.RE
.PP

.PP
Implements \fBCsla\&.Serialization\&.Mobile\&.ICslaReader\fP\&.
.PP
Definition at line 30 of file CslaLegacyBinaryReader\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
