.TH "Csla.Test.Authorization.IPerTypeAuthRoot" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.Authorization.IPerTypeAuthRoot
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBCsla\&.Test\&.Authorization\&.PerTypeAuthRoot\fP\&.
.SH "Detailed Description"
.PP 
Definition at line 562 of file AuthTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
