.TH "cslalighttest.CslaDataProvider.Customer" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cslalighttest.CslaDataProvider.Customer
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.BusinessBase< Customer >\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFetchCriteria\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBAddBusinessRules\fP ()"
.br
.ti -1c
.RI "void \fBDataPortal_Fetch\fP (int criteria)"
.br
.ti -1c
.RI "void \fBDataPortal_Create\fP (int criteria)"
.br
.ti -1c
.RI "void \fBDataPortal_DeleteSelf\fP ()"
.br
.ti -1c
.RI "void \fBDataPortal_Delete\fP (int criteria)"
.br
.ti -1c
.RI "void \fBDataPortal_Insert\fP ()"
.br
.ti -1c
.RI "void \fBDataPortal_Update\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBId\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBName\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBMethod\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBDateCreated\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "bool \fBThrowException\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "DateTimeOffset \fBDateTimeOffsetNull\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "DateTimeOffset \fBDateTimeOffsetNotNull\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "DateTimeOffset? \fBDateTimeOffsetNullable\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBCustomeType\fP \fBType\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBCustomerContactList\fP \fBContacts\fP\fC [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 27 of file Silverlight/Server/CslaDataProvider/Customer\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override void cslalighttest\&.CslaDataProvider\&.Customer\&.AddBusinessRules ()\fC [protected]\fP"

.PP
Definition at line 174 of file Silverlight/Server/CslaDataProvider/Customer\&.cs\&.
.SS "void cslalighttest\&.CslaDataProvider\&.Customer\&.DataPortal_Create (int criteria)\fC [protected]\fP"

.PP
Definition at line 236 of file Silverlight/Server/CslaDataProvider/Customer\&.cs\&.
.SS "void cslalighttest\&.CslaDataProvider\&.Customer\&.DataPortal_Delete (int criteria)\fC [protected]\fP"

.PP
Definition at line 252 of file Silverlight/Server/CslaDataProvider/Customer\&.cs\&.
.SS "void cslalighttest\&.CslaDataProvider\&.Customer\&.DataPortal_DeleteSelf ()\fC [protected]\fP"

.PP
Definition at line 246 of file Silverlight/Server/CslaDataProvider/Customer\&.cs\&.
.SS "void cslalighttest\&.CslaDataProvider\&.Customer\&.DataPortal_Fetch (int criteria)\fC [protected]\fP"

.PP
Definition at line 223 of file Silverlight/Server/CslaDataProvider/Customer\&.cs\&.
.SS "void cslalighttest\&.CslaDataProvider\&.Customer\&.DataPortal_Insert ()\fC [protected]\fP"

.PP
Definition at line 258 of file Silverlight/Server/CslaDataProvider/Customer\&.cs\&.
.SS "void cslalighttest\&.CslaDataProvider\&.Customer\&.DataPortal_Update ()\fC [protected]\fP"

.PP
Definition at line 265 of file Silverlight/Server/CslaDataProvider/Customer\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "\fBCustomerContactList\fP cslalighttest\&.CslaDataProvider\&.Customer\&.Contacts\fC [get]\fP"

.PP
Definition at line 166 of file Silverlight/Server/CslaDataProvider/Customer\&.cs\&.
.SS "string cslalighttest\&.CslaDataProvider\&.Customer\&.DateCreated\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 82 of file Silverlight/Server/CslaDataProvider/Customer\&.cs\&.
.SS "DateTimeOffset cslalighttest\&.CslaDataProvider\&.Customer\&.DateTimeOffsetNotNull\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 126 of file Silverlight/Server/CslaDataProvider/Customer\&.cs\&.
.SS "DateTimeOffset cslalighttest\&.CslaDataProvider\&.Customer\&.DateTimeOffsetNull\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 113 of file Silverlight/Server/CslaDataProvider/Customer\&.cs\&.
.SS "DateTimeOffset? cslalighttest\&.CslaDataProvider\&.Customer\&.DateTimeOffsetNullable\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 139 of file Silverlight/Server/CslaDataProvider/Customer\&.cs\&.
.SS "int cslalighttest\&.CslaDataProvider\&.Customer\&.Id\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 42 of file Silverlight/Server/CslaDataProvider/Customer\&.cs\&.
.SS "string cslalighttest\&.CslaDataProvider\&.Customer\&.Method\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 68 of file Silverlight/Server/CslaDataProvider/Customer\&.cs\&.
.SS "string cslalighttest\&.CslaDataProvider\&.Customer\&.Name\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 55 of file Silverlight/Server/CslaDataProvider/Customer\&.cs\&.
.SS "bool cslalighttest\&.CslaDataProvider\&.Customer\&.ThrowException\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 100 of file Silverlight/Server/CslaDataProvider/Customer\&.cs\&.
.SS "\fBCustomeType\fP cslalighttest\&.CslaDataProvider\&.Customer\&.Type\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 152 of file Silverlight/Server/CslaDataProvider/Customer\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
