.TH "Csla.Ios.Test.ResourceStrings.ResourceStringTests" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Ios.Test.ResourceStrings.ResourceStringTests
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBTestResourceStringsShouldNotThrow\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 7 of file ResourceStringTests\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Csla\&.Ios\&.Test\&.ResourceStrings\&.ResourceStringTests\&.TestResourceStringsShouldNotThrow ()"

.PP
Definition at line 10 of file ResourceStringTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
