.TH "Csla.Analyzers.Tests.DoesChildOperationHaveRunLocalAnalyzerTests" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Analyzers.Tests.DoesChildOperationHaveRunLocalAnalyzerTests
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBVerifySupportedDiagnostics\fP ()"
.br
.ti -1c
.RI "async Task \fBAnalyzeWhenClassIsNotMobileObject\fP ()"
.br
.ti -1c
.RI "async Task \fBAnalyzeWhenClassIsMobileObjectAndRootOperationHasRunLocal\fP ()"
.br
.ti -1c
.RI "async Task \fBAnalyzeWhenClassIsMobileObjectAndChildOperationDoesNotHaveRunLocal\fP ()"
.br
.ti -1c
.RI "async Task \fBAnalyzeWhenClassIsMobileObjectAndChildOperationHasRunLocal\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 9 of file DoesChildOperationHaveRunLocalAnalyzerTests\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "async Task Csla\&.Analyzers\&.Tests\&.DoesChildOperationHaveRunLocalAnalyzerTests\&.AnalyzeWhenClassIsMobileObjectAndChildOperationDoesNotHaveRunLocal ()"

.PP
Definition at line 59 of file DoesChildOperationHaveRunLocalAnalyzerTests\&.cs\&.
.SS "async Task Csla\&.Analyzers\&.Tests\&.DoesChildOperationHaveRunLocalAnalyzerTests\&.AnalyzeWhenClassIsMobileObjectAndChildOperationHasRunLocal ()"

.PP
Definition at line 74 of file DoesChildOperationHaveRunLocalAnalyzerTests\&.cs\&.
.SS "async Task Csla\&.Analyzers\&.Tests\&.DoesChildOperationHaveRunLocalAnalyzerTests\&.AnalyzeWhenClassIsMobileObjectAndRootOperationHasRunLocal ()"

.PP
Definition at line 43 of file DoesChildOperationHaveRunLocalAnalyzerTests\&.cs\&.
.SS "async Task Csla\&.Analyzers\&.Tests\&.DoesChildOperationHaveRunLocalAnalyzerTests\&.AnalyzeWhenClassIsNotMobileObject ()"

.PP
Definition at line 35 of file DoesChildOperationHaveRunLocalAnalyzerTests\&.cs\&.
.SS "void Csla\&.Analyzers\&.Tests\&.DoesChildOperationHaveRunLocalAnalyzerTests\&.VerifySupportedDiagnostics ()"

.PP
Definition at line 12 of file DoesChildOperationHaveRunLocalAnalyzerTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
