.TH "Csla.Testing.Business.EditableChildTests" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Testing.Business.EditableChildTests
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBGrandChild\fP"
.br
.ti -1c
.RI "class \fBGrandChildList\fP"
.br
.ti -1c
.RI "class \fBMockEditableChild\fP"
.br
.ti -1c
.RI "class \fBMockList\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
