.TH "Csla.Testing.Business.DataPortal.AsyncPortalWithCulture" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Testing.Business.DataPortal.AsyncPortalWithCulture
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.CommandBase< AsyncPortalWithCulture >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAsyncPortalWithCulture\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBPropertyInfo\fP< string > \fBCurrentUICultureProperty\fP"
.br
.ti -1c
.RI "static \fBPropertyInfo\fP< string > \fBCurrentCultureProperty\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBDataPortal_Execute\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBCurrentUICulture\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBCurrentCulture\fP\fC [get, set]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 19 of file AsyncPortalWithCulture\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Csla\&.Testing\&.Business\&.DataPortal\&.AsyncPortalWithCulture\&.AsyncPortalWithCulture ()"

.PP
Definition at line 49 of file AsyncPortalWithCulture\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Csla\&.Testing\&.Business\&.DataPortal\&.AsyncPortalWithCulture\&.DataPortal_Execute ()\fC [protected]\fP"

.PP
Definition at line 52 of file AsyncPortalWithCulture\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBPropertyInfo\fP<string> Csla\&.Testing\&.Business\&.DataPortal\&.AsyncPortalWithCulture\&.CurrentCultureProperty\fC [static]\fP"
\fBInitial value:\fP
.PP
.nf
=
      RegisterProperty<string>(new PropertyInfo<string>("CurrentCulture"))
.fi
.PP
Definition at line 46 of file AsyncPortalWithCulture\&.cs\&.
.SS "\fBPropertyInfo\fP<string> Csla\&.Testing\&.Business\&.DataPortal\&.AsyncPortalWithCulture\&.CurrentUICultureProperty\fC [static]\fP"
\fBInitial value:\fP
.PP
.nf
= 
      RegisterProperty<string>(new PropertyInfo<string>("CurrentUICulture"))
.fi
.PP
Definition at line 32 of file AsyncPortalWithCulture\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "string Csla\&.Testing\&.Business\&.DataPortal\&.AsyncPortalWithCulture\&.CurrentCulture\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 35 of file AsyncPortalWithCulture\&.cs\&.
.SS "string Csla\&.Testing\&.Business\&.DataPortal\&.AsyncPortalWithCulture\&.CurrentUICulture\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 21 of file AsyncPortalWithCulture\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
