.TH "Csla.Test.DataPortalTest.SingleTest" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.DataPortalTest.SingleTest
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBTestDpCreate\fP ()"
.br
.ti -1c
.RI "void \fBTestDpFetch\fP ()"
.br
.ti -1c
.RI "void \fBTestDpInsert\fP ()"
.br
.ti -1c
.RI "void \fBTestDpUpdate\fP ()"
.br
.ti -1c
.RI "void \fBTestDpDelete\fP ()"
.br
.ti -1c
.RI "void \fBTestDpDeleteSelf\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 26 of file SingleTest\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Csla\&.Test\&.DataPortalTest\&.SingleTest\&.TestDpCreate ()"

.PP
Definition at line 29 of file SingleTest\&.cs\&.
.SS "void Csla\&.Test\&.DataPortalTest\&.SingleTest\&.TestDpDelete ()"

.PP
Definition at line 67 of file SingleTest\&.cs\&.
.SS "void Csla\&.Test\&.DataPortalTest\&.SingleTest\&.TestDpDeleteSelf ()"

.PP
Definition at line 73 of file SingleTest\&.cs\&.
.SS "void Csla\&.Test\&.DataPortalTest\&.SingleTest\&.TestDpFetch ()"

.PP
Definition at line 35 of file SingleTest\&.cs\&.
.SS "void Csla\&.Test\&.DataPortalTest\&.SingleTest\&.TestDpInsert ()"

.PP
Definition at line 41 of file SingleTest\&.cs\&.
.SS "void Csla\&.Test\&.DataPortalTest\&.SingleTest\&.TestDpUpdate ()"

.PP
Definition at line 53 of file SingleTest\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
