.TH "Csla.Rules.CommonRules.Dependency" 3 "Thu Jul 22 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Rules.CommonRules.Dependency \- A rule that establishes a dependency between two properties\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.Rules\&.BusinessRule\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDependency\fP (\fBCsla\&.Core\&.IPropertyInfo\fP primaryProperty, params \fBCsla\&.Core\&.IPropertyInfo\fP[] dependencyProperty)"
.br
.RI "Creates an instance of the rule\&. "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
A rule that establishes a dependency between two properties\&. 


.PP
Definition at line 745 of file Csla/Rules/CommonRules\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Csla\&.Rules\&.CommonRules\&.Dependency\&.Dependency (\fBCsla\&.Core\&.IPropertyInfo\fP primaryProperty, params \fBCsla\&.Core\&.IPropertyInfo\fP[] dependencyProperty)"

.PP
Creates an instance of the rule\&. 
.PP
\fBParameters\fP
.RS 4
\fIprimaryProperty\fP Primary property for the rule\&.
.br
\fIdependencyProperty\fP Dependent property\&.
.RE
.PP
.PP
When rules are run for the primary property, they will also be run for the dependent property\&. Add a \fBDependency\fP rule to a property when changing that property should run rules on some other property, and you have no other rules that would establish this dependent or affected property relationship\&. 
.PP
Definition at line 758 of file Csla/Rules/CommonRules\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
