.TH "Csla.Analyzers.Tests.FindRefAndOutParametersInOperationsAnalyzerTests" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Analyzers.Tests.FindRefAndOutParametersInOperationsAnalyzerTests
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBVerifySupportedDiagnostics\fP ()"
.br
.ti -1c
.RI "async Task \fBAnalyzeWhenClassIsNotABusinessBase\fP ()"
.br
.ti -1c
.RI "async Task \fBAnalyzeWhenClassIsABusinessBaseAndHasNoParameters\fP ()"
.br
.ti -1c
.RI "async Task \fBAnalyzeWhenClassIsABusinessBaseAndHasParameterNotRefOrOut\fP ()"
.br
.ti -1c
.RI "async Task \fBAnalyzeWhenClassIsABusinessBaseAndHasRefParameter\fP ()"
.br
.ti -1c
.RI "async Task \fBAnalyzeWhenClassIsABusinessBaseAndHasOutParameter\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 9 of file FindRefAndOutParametersInOperationsAnalyzerTests\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "async Task Csla\&.Analyzers\&.Tests\&.FindRefAndOutParametersInOperationsAnalyzerTests\&.AnalyzeWhenClassIsABusinessBaseAndHasNoParameters ()"

.PP
Definition at line 43 of file FindRefAndOutParametersInOperationsAnalyzerTests\&.cs\&.
.SS "async Task Csla\&.Analyzers\&.Tests\&.FindRefAndOutParametersInOperationsAnalyzerTests\&.AnalyzeWhenClassIsABusinessBaseAndHasOutParameter ()"

.PP
Definition at line 97 of file FindRefAndOutParametersInOperationsAnalyzerTests\&.cs\&.
.SS "async Task Csla\&.Analyzers\&.Tests\&.FindRefAndOutParametersInOperationsAnalyzerTests\&.AnalyzeWhenClassIsABusinessBaseAndHasParameterNotRefOrOut ()"

.PP
Definition at line 61 of file FindRefAndOutParametersInOperationsAnalyzerTests\&.cs\&.
.SS "async Task Csla\&.Analyzers\&.Tests\&.FindRefAndOutParametersInOperationsAnalyzerTests\&.AnalyzeWhenClassIsABusinessBaseAndHasRefParameter ()"

.PP
Definition at line 79 of file FindRefAndOutParametersInOperationsAnalyzerTests\&.cs\&.
.SS "async Task Csla\&.Analyzers\&.Tests\&.FindRefAndOutParametersInOperationsAnalyzerTests\&.AnalyzeWhenClassIsNotABusinessBase ()"

.PP
Definition at line 35 of file FindRefAndOutParametersInOperationsAnalyzerTests\&.cs\&.
.SS "void Csla\&.Analyzers\&.Tests\&.FindRefAndOutParametersInOperationsAnalyzerTests\&.VerifySupportedDiagnostics ()"

.PP
Definition at line 12 of file FindRefAndOutParametersInOperationsAnalyzerTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
