.TH "Csla.Testing.Business.ApplicationContext.ContextMessageValues" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Testing.Business.ApplicationContext.ContextMessageValues
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "const string \fBINITIAL_VALUE\fP = 'Hello World!'"
.br
.ti -1c
.RI "const string \fBMODIFIED_VALUE\fP = 'Changed'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 78 of file ContextBOVerifier\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "const string Csla\&.Testing\&.Business\&.ApplicationContext\&.ContextMessageValues\&.INITIAL_VALUE = 'Hello World!'\fC [static]\fP"

.PP
Definition at line 80 of file ContextBOVerifier\&.cs\&.
.SS "const string Csla\&.Testing\&.Business\&.ApplicationContext\&.ContextMessageValues\&.MODIFIED_VALUE = 'Changed'\fC [static]\fP"

.PP
Definition at line 81 of file ContextBOVerifier\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
