.TH "Csla.Testing.Business.EditableRootListTests.SingleItem" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Testing.Business.EditableRootListTests.SingleItem
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.BusinessBase< SingleItem >\fP\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBSingleItem\fP \fBGetSingleItem\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBDataPortal_Insert\fP ()"
.br
.ti -1c
.RI "void \fBDataPortal_Update\fP ()"
.br
.ti -1c
.RI "void \fBDataPortal_Delete\fP (object criteria)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBId\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBName\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBDateCreated\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBMethodCalled\fP\fC [get, set]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 20 of file SingleItem\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Csla\&.Testing\&.Business\&.EditableRootListTests\&.SingleItem\&.DataPortal_Delete (object criteria)\fC [protected]\fP"

.PP
Definition at line 114 of file SingleItem\&.cs\&.
.SS "void Csla\&.Testing\&.Business\&.EditableRootListTests\&.SingleItem\&.DataPortal_Insert ()\fC [protected]\fP"

.PP
Definition at line 103 of file SingleItem\&.cs\&.
.SS "void Csla\&.Testing\&.Business\&.EditableRootListTests\&.SingleItem\&.DataPortal_Update ()\fC [protected]\fP"

.PP
Definition at line 109 of file SingleItem\&.cs\&.
.SS "static \fBSingleItem\fP Csla\&.Testing\&.Business\&.EditableRootListTests\&.SingleItem\&.GetSingleItem ()\fC [static]\fP"

.PP
Definition at line 24 of file SingleItem\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "string Csla\&.Testing\&.Business\&.EditableRootListTests\&.SingleItem\&.DateCreated\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 56 of file SingleItem\&.cs\&.
.SS "int Csla\&.Testing\&.Business\&.EditableRootListTests\&.SingleItem\&.Id\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 30 of file SingleItem\&.cs\&.
.SS "string Csla\&.Testing\&.Business\&.EditableRootListTests\&.SingleItem\&.MethodCalled\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 73 of file SingleItem\&.cs\&.
.SS "string Csla\&.Testing\&.Business\&.EditableRootListTests\&.SingleItem\&.Name\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 43 of file SingleItem\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
