.TH "Csla.Blazor.CslaPermissionRequirement" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Blazor.CslaPermissionRequirement \- CSLA permissions requirement\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits IAuthorizationRequirement\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCslaPermissionRequirement\fP (\fBRules\&.AuthorizationActions\fP action, Type objectType)"
.br
.RI "Creates an instance of the type\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBRules\&.AuthorizationActions\fP \fBAction\fP\fC [get, set]\fP"
.br
.RI "Gets or sets the authorization action "
.ti -1c
.RI "Type \fBObjectType\fP\fC [get, set]\fP"
.br
.RI "Gets or sets the business object type "
.in -1c
.SH "Detailed Description"
.PP 
CSLA permissions requirement\&. 


.PP
Definition at line 16 of file Csla\&.Blazor/CslaPermissionRequirement\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Csla\&.Blazor\&.CslaPermissionRequirement\&.CslaPermissionRequirement (\fBRules\&.AuthorizationActions\fP action, Type objectType)"

.PP
Creates an instance of the type\&. 
.PP
\fBParameters\fP
.RS 4
\fIaction\fP Authorization action
.br
\fIobjectType\fP Business object type
.RE
.PP

.PP
Definition at line 23 of file Csla\&.Blazor/CslaPermissionRequirement\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "\fBRules\&.AuthorizationActions\fP Csla\&.Blazor\&.CslaPermissionRequirement\&.Action\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the authorization action 
.PP
Definition at line 32 of file Csla\&.Blazor/CslaPermissionRequirement\&.cs\&.
.SS "Type Csla\&.Blazor\&.CslaPermissionRequirement\&.ObjectType\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the business object type 
.PP
Definition at line 36 of file Csla\&.Blazor/CslaPermissionRequirement\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
