.TH "Csla.Test.ChildChanged.SingleRoot" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.ChildChanged.SingleRoot
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.BusinessBase< SingleRoot >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSingleRoot\fP ()"
.br
.ti -1c
.RI "\fBSingleRoot\fP (bool child)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBName\fP\fC [get, set]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 18 of file SingleRoot\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Csla\&.Test\&.ChildChanged\&.SingleRoot\&.SingleRoot ()"

.PP
Definition at line 20 of file SingleRoot\&.cs\&.
.SS "Csla\&.Test\&.ChildChanged\&.SingleRoot\&.SingleRoot (bool child)"

.PP
Definition at line 23 of file SingleRoot\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "string Csla\&.Test\&.ChildChanged\&.SingleRoot\&.Name\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 30 of file SingleRoot\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
