.TH "Csla.Security.SecurityException" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Security.SecurityException \- \fBSecurity\fP exception\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits System\&.Exception\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSecurityException\fP ()"
.br
.RI "Creates an instance of the type\&. "
.ti -1c
.RI "\fBSecurityException\fP (string message)"
.br
.RI "Creates an instance of the type\&. "
.ti -1c
.RI "\fBSecurityException\fP (string message, Exception innerException)"
.br
.RI "Creates an instance of the type\&. "
.ti -1c
.RI "override void \fBGetObjectData\fP (System\&.Runtime\&.Serialization\&.SerializationInfo info, System\&.Runtime\&.Serialization\&.StreamingContext context)"
.br
.RI "Serializes the object\&. "
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBSecurityException\fP (System\&.Runtime\&.Serialization\&.SerializationInfo info, System\&.Runtime\&.Serialization\&.StreamingContext context)"
.br
.RI "Creates an instance of the object for serialization\&. "
.in -1c
.SH "Detailed Description"
.PP 
\fBSecurity\fP exception\&. 


.PP
Definition at line 16 of file SecurityException\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Csla\&.Security\&.SecurityException\&.SecurityException ()"

.PP
Creates an instance of the type\&. 
.PP
Definition at line 21 of file SecurityException\&.cs\&.
.SS "Csla\&.Security\&.SecurityException\&.SecurityException (string message)"

.PP
Creates an instance of the type\&. 
.PP
\fBParameters\fP
.RS 4
\fImessage\fP Exception text\&.
.RE
.PP

.PP
Definition at line 28 of file SecurityException\&.cs\&.
.SS "Csla\&.Security\&.SecurityException\&.SecurityException (string message, Exception innerException)"

.PP
Creates an instance of the type\&. 
.PP
\fBParameters\fP
.RS 4
\fImessage\fP Exception text\&.
.br
\fIinnerException\fP Inner exception\&.
.RE
.PP

.PP
Definition at line 37 of file SecurityException\&.cs\&.
.SS "Csla\&.Security\&.SecurityException\&.SecurityException (System\&.Runtime\&.Serialization\&.SerializationInfo info, System\&.Runtime\&.Serialization\&.StreamingContext context)\fC [protected]\fP"

.PP
Creates an instance of the object for serialization\&. 
.PP
\fBParameters\fP
.RS 4
\fIinfo\fP Serialiation info object\&.
.br
\fIcontext\fP \fBSerialization\fP context object\&.
.RE
.PP

.PP
Definition at line 47 of file SecurityException\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override void Csla\&.Security\&.SecurityException\&.GetObjectData (System\&.Runtime\&.Serialization\&.SerializationInfo info, System\&.Runtime\&.Serialization\&.StreamingContext context)"

.PP
Serializes the object\&. 
.PP
\fBParameters\fP
.RS 4
\fIinfo\fP Serialiation info object\&.
.br
\fIcontext\fP \fBSerialization\fP context object\&.
.RE
.PP

.PP
Definition at line 62 of file SecurityException\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
