.TH "Csla.Rules.RuleContext" 3 "Thu Jul 22 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Rules.RuleContext \- Context information provided to a business rule when it is invoked\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.Rules\&.IRuleContext\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBExecuteRule\fP (\fBIBusinessRuleBase\fP innerRule)"
.br
.RI "Executes the inner rule from the outer rules context\&. "
.ti -1c
.RI "\fBRuleContext\fP (Action< \fBIRuleContext\fP > completeHandler, \fBIBusinessRuleBase\fP rule, object target, Dictionary< \fBCsla\&.Core\&.IPropertyInfo\fP, object > inputPropertyValues)"
.br
.RI "Creates a \fBRuleContext\fP instance for testing\&. "
.ti -1c
.RI "\fBIRuleContext\fP \fBGetChainedContext\fP (\fBIBusinessRuleBase\fP rule)"
.br
.RI "Gets a new \fBRuleContext\fP object for a chained rule\&. "
.ti -1c
.RI "void \fBAddErrorResult\fP (string description)"
.br
.RI "Add a Error severity result to the Results list\&. "
.ti -1c
.RI "void \fBAddErrorResult\fP (string description, bool stopProcessing)"
.br
.RI "Add a Error severity result to the Results list\&. "
.ti -1c
.RI "void \fBAddErrorResult\fP (\fBCsla\&.Core\&.IPropertyInfo\fP property, string description)"
.br
.RI "Add a Error severity result to the Results list\&. "
.ti -1c
.RI "void \fBAddWarningResult\fP (string description)"
.br
.RI "Add a Warning severity result to the Results list\&. "
.ti -1c
.RI "void \fBAddWarningResult\fP (string description, bool stopProcessing)"
.br
.RI "Add a Warning severity result to the Results list\&. "
.ti -1c
.RI "void \fBAddWarningResult\fP (\fBCsla\&.Core\&.IPropertyInfo\fP property, string description)"
.br
.RI "Add a Warning severity result to the Results list\&. "
.ti -1c
.RI "void \fBAddInformationResult\fP (string description)"
.br
.RI "Add an Information severity result to the Results list\&. "
.ti -1c
.RI "void \fBAddInformationResult\fP (string description, bool stopProcessing)"
.br
.RI "Add an Information severity result to the Results list\&. "
.ti -1c
.RI "void \fBAddInformationResult\fP (\fBCsla\&.Core\&.IPropertyInfo\fP property, string description)"
.br
.RI "Add an Information severity result to the Results list\&. "
.ti -1c
.RI "void \fBAddSuccessResult\fP (bool stopProcessing)"
.br
.RI "Add a Success severity result to the Results list\&. "
.ti -1c
.RI "void \fBAddOutValue\fP (object value)"
.br
.RI "Add an outbound value to update the rule's primary property on the business object once the rule is complete\&. "
.ti -1c
.RI "void \fBAddOutValue\fP (\fBCsla\&.Core\&.IPropertyInfo\fP property, object value)"
.br
.RI "Add an outbound value to update a property on the business object once the rule is complete\&. "
.ti -1c
.RI "void \fBAddDirtyProperty\fP (\fBCsla\&.Core\&.IPropertyInfo\fP property)"
.br
.RI "Adds a property name as a dirty field (changed value)\&. "
.ti -1c
.RI "void \fBComplete\fP ()"
.br
.RI "Indicates that the rule processing is complete, so CSLA \&.NET will process the Results list\&. "
.ti -1c
.RI "T \fBGetInputValue< T >\fP (\fBPropertyInfo\fP< T > propertyInfo)"
.br
.RI "Gets the value\&. "
.ti -1c
.RI "T \fBGetInputValue< T >\fP (\fBIPropertyInfo\fP propertyInfo)"
.br
.RI "Gets the value with explicit cast "
.ti -1c
.RI "bool \fBTryGetInputValue< T >\fP (\fBPropertyInfo\fP< T > propertyInfo, ref T value)"
.br
.RI "Tries to get the value\&. "
.ti -1c
.RI "bool \fBTryGetInputValue< T >\fP (\fBIPropertyInfo\fP propertyInfo, ref T value)"
.br
.RI "Tries to get the value with explicit cast\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBIBusinessRuleBase\fP \fBRule\fP\fC [get, set]\fP"
.br
.RI "Gets the rule object\&. "
.ti -1c
.RI "object \fBTarget\fP\fC [get, set]\fP"
.br
.RI "Gets a reference to the target business object\&. "
.ti -1c
.RI "Dictionary< \fBCsla\&.Core\&.IPropertyInfo\fP, object > \fBInputPropertyValues\fP\fC [get, set]\fP"
.br
.RI "Gets a dictionary containing copies of property values from the target business object\&. "
.ti -1c
.RI "List< \fBIPropertyInfo\fP > \fBDirtyProperties\fP\fC [get]\fP"
.br
.RI "Gets a list of dirty properties (value was updated)\&. "
.ti -1c
.RI "Dictionary< \fBCsla\&.Core\&.IPropertyInfo\fP, object > \fBOutputPropertyValues\fP\fC [get]\fP"
.br
.RI "Gets a dictionary containing copies of property values that should be updated in the target object\&. "
.ti -1c
.RI "List< \fBRuleResult\fP > \fBResults\fP\fC [get]\fP"
.br
.RI "Gets a list of \fBRuleResult\fP objects containing the results of the rule\&. "
.ti -1c
.RI "string \fBOriginPropertyName\fP\fC [get, set]\fP"
.br
.RI "Gets or sets the name of the origin property\&. "
.ti -1c
.RI "\fBRuleContextModes\fP \fBExecuteContext\fP\fC [get, set]\fP"
.br
.RI "Gets the execution context\&. "
.ti -1c
.RI "bool \fBIsCascadeContext\fP\fC [get]\fP"
.br
.RI "Gets a value indicating whether this instance is cascade context as a result of AffectedProperties\&. "
.ti -1c
.RI "bool \fBIsPropertyChangedContext\fP\fC [get]\fP"
.br
.RI "Gets a value indicating whether this instance is property changed context\&. "
.ti -1c
.RI "bool \fBIsCheckRulesContext\fP\fC [get]\fP"
.br
.RI "Gets a value indicating whether this instance is check rules context\&. "
.ti -1c
.RI "bool \fBIsCheckObjectRulesContext\fP\fC [get]\fP"
.br
.RI "Gets a value indicating whether this instance is check object rules context\&. "
.in -1c
.SH "Detailed Description"
.PP 
Context information provided to a business rule when it is invoked\&. 


.PP
Definition at line 51 of file RuleContext\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Csla\&.Rules\&.RuleContext\&.RuleContext (Action< \fBIRuleContext\fP > completeHandler, \fBIBusinessRuleBase\fP rule, object target, Dictionary< \fBCsla\&.Core\&.IPropertyInfo\fP, object > inputPropertyValues)"

.PP
Creates a \fBRuleContext\fP instance for testing\&. 
.PP
\fBParameters\fP
.RS 4
\fIcompleteHandler\fP Callback for async rule\&.
.br
\fIrule\fP Reference to the rule object\&.
.br
\fItarget\fP Target business object\&.
.br
\fIinputPropertyValues\fP Input property values used by the rule\&.
.RE
.PP

.PP
Definition at line 238 of file RuleContext\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Csla\&.Rules\&.RuleContext\&.AddDirtyProperty (\fBCsla\&.Core\&.IPropertyInfo\fP property)"

.PP
Adds a property name as a dirty field (changed value)\&. 
.PP
\fBParameters\fP
.RS 4
\fIproperty\fP The property\&.
.RE
.PP
\fBExceptions\fP
.RS 4
\fISystem\&.ArgumentOutOfRangeException\fP 
.RE
.PP

.PP
Implements \fBCsla\&.Rules\&.IRuleContext\fP\&.
.PP
Definition at line 419 of file RuleContext\&.cs\&.
.SS "void Csla\&.Rules\&.RuleContext\&.AddErrorResult (\fBCsla\&.Core\&.IPropertyInfo\fP property, string description)"

.PP
Add a Error severity result to the Results list\&. This method is only allowed on 'object' level rules to allow an object level rule to set warning result on a field\&.
.PP
\fBParameters\fP
.RS 4
\fIproperty\fP Property to which the result applies\&.
.br
\fIdescription\fP Human-readable description of why the rule failed\&.
.RE
.PP
\fBExceptions\fP
.RS 4
\fISystem\&.ArgumentOutOfRangeException\fP When property is not defined in AffectedProperties list\&.
.RE
.PP

.br
 
.PP
Implements \fBCsla\&.Rules\&.IRuleContext\fP\&.
.PP
Definition at line 303 of file RuleContext\&.cs\&.
.SS "void Csla\&.Rules\&.RuleContext\&.AddErrorResult (string description)"

.PP
Add a Error severity result to the Results list\&. 
.PP
\fBParameters\fP
.RS 4
\fIdescription\fP Human-readable description of why the rule failed\&.
.RE
.PP

.PP
Implements \fBCsla\&.Rules\&.IRuleContext\fP\&.
.PP
Definition at line 278 of file RuleContext\&.cs\&.
.SS "void Csla\&.Rules\&.RuleContext\&.AddErrorResult (string description, bool stopProcessing)"

.PP
Add a Error severity result to the Results list\&. 
.PP
\fBParameters\fP
.RS 4
\fIdescription\fP Human-readable description of why the rule failed\&.
.br
\fIstopProcessing\fP True if no further rules should be processed for the current property\&.
.RE
.PP

.PP
Implements \fBCsla\&.Rules\&.IRuleContext\fP\&.
.PP
Definition at line 290 of file RuleContext\&.cs\&.
.SS "void Csla\&.Rules\&.RuleContext\&.AddInformationResult (\fBCsla\&.Core\&.IPropertyInfo\fP property, string description)"

.PP
Add an Information severity result to the Results list\&. This method is only allowed on 'object' level rules to allow an object level rule to set warning result on a field\&.
.PP
\fBParameters\fP
.RS 4
\fIproperty\fP Property to which the result applies\&.
.br
\fIdescription\fP Human-readable description of why the rule failed\&.
.RE
.PP
\fBExceptions\fP
.RS 4
\fISystem\&.ArgumentOutOfRangeException\fP When property is not defined in AffectedProperties list\&.
.RE
.PP

.br
 
.PP
Implements \fBCsla\&.Rules\&.IRuleContext\fP\&.
.PP
Definition at line 374 of file RuleContext\&.cs\&.
.SS "void Csla\&.Rules\&.RuleContext\&.AddInformationResult (string description)"

.PP
Add an Information severity result to the Results list\&. 
.PP
\fBParameters\fP
.RS 4
\fIdescription\fP Human-readable description of why the rule failed\&.
.RE
.PP

.PP
Implements \fBCsla\&.Rules\&.IRuleContext\fP\&.
.PP
Definition at line 352 of file RuleContext\&.cs\&.
.SS "void Csla\&.Rules\&.RuleContext\&.AddInformationResult (string description, bool stopProcessing)"

.PP
Add an Information severity result to the Results list\&. 
.PP
\fBParameters\fP
.RS 4
\fIdescription\fP Human-readable description of why the rule failed\&.
.br
\fIstopProcessing\fP True if no further rules should be processed for the current property\&.
.RE
.PP

.PP
Implements \fBCsla\&.Rules\&.IRuleContext\fP\&.
.PP
Definition at line 362 of file RuleContext\&.cs\&.
.SS "void Csla\&.Rules\&.RuleContext\&.AddOutValue (\fBCsla\&.Core\&.IPropertyInfo\fP property, object value)"

.PP
Add an outbound value to update a property on the business object once the rule is complete\&. 
.PP
\fBParameters\fP
.RS 4
\fIproperty\fP Property to update\&.
.br
\fIvalue\fP New property value\&.
.RE
.PP
\fBExceptions\fP
.RS 4
\fISystem\&.ArgumentOutOfRangeException\fP When property is not defined in AffectedProperties list\&.
.RE
.PP

.br
 
.PP
Implements \fBCsla\&.Rules\&.IRuleContext\fP\&.
.PP
Definition at line 407 of file RuleContext\&.cs\&.
.SS "void Csla\&.Rules\&.RuleContext\&.AddOutValue (object value)"

.PP
Add an outbound value to update the rule's primary property on the business object once the rule is complete\&. 
.PP
\fBParameters\fP
.RS 4
\fIvalue\fP New property value\&.
.RE
.PP

.PP
Implements \fBCsla\&.Rules\&.IRuleContext\fP\&.
.PP
Definition at line 395 of file RuleContext\&.cs\&.
.SS "void Csla\&.Rules\&.RuleContext\&.AddSuccessResult (bool stopProcessing)"

.PP
Add a Success severity result to the Results list\&. 
.PP
\fBParameters\fP
.RS 4
\fIstopProcessing\fP True if no further rules should be processed for the current property\&.
.RE
.PP

.PP
Implements \fBCsla\&.Rules\&.IRuleContext\fP\&.
.PP
Definition at line 385 of file RuleContext\&.cs\&.
.SS "void Csla\&.Rules\&.RuleContext\&.AddWarningResult (\fBCsla\&.Core\&.IPropertyInfo\fP property, string description)"

.PP
Add a Warning severity result to the Results list\&. This method is only allowed on 'object' level rules to allow an object level rule to set warning result on a field\&.
.PP
\fBParameters\fP
.RS 4
\fIproperty\fP Property to which the result applies\&.
.br
\fIdescription\fP Human-readable description of why the rule failed\&.
.RE
.PP
\fBExceptions\fP
.RS 4
\fISystem\&.ArgumentOutOfRangeException\fP When property is not defined in AffectedProperties list\&.
.RE
.PP

.br
 
.PP
Implements \fBCsla\&.Rules\&.IRuleContext\fP\&.
.PP
Definition at line 340 of file RuleContext\&.cs\&.
.SS "void Csla\&.Rules\&.RuleContext\&.AddWarningResult (string description)"

.PP
Add a Warning severity result to the Results list\&. 
.PP
\fBParameters\fP
.RS 4
\fIdescription\fP Human-readable description of why the rule failed\&.
.RE
.PP

.PP
Implements \fBCsla\&.Rules\&.IRuleContext\fP\&.
.PP
Definition at line 315 of file RuleContext\&.cs\&.
.SS "void Csla\&.Rules\&.RuleContext\&.AddWarningResult (string description, bool stopProcessing)"

.PP
Add a Warning severity result to the Results list\&. 
.PP
\fBParameters\fP
.RS 4
\fIdescription\fP Human-readable description of why the rule failed\&.
.br
\fIstopProcessing\fP True if no further rules should be processed for the current property\&.
.RE
.PP

.PP
Implements \fBCsla\&.Rules\&.IRuleContext\fP\&.
.PP
Definition at line 327 of file RuleContext\&.cs\&.
.SS "void Csla\&.Rules\&.RuleContext\&.Complete ()"

.PP
Indicates that the rule processing is complete, so CSLA \&.NET will process the Results list\&. This method must be invoked on the UI thread\&.
.PP
Implements \fBCsla\&.Rules\&.IRuleContext\fP\&.
.PP
Definition at line 431 of file RuleContext\&.cs\&.
.SS "void Csla\&.Rules\&.RuleContext\&.ExecuteRule (\fBIBusinessRuleBase\fP innerRule)"

.PP
Executes the inner rule from the outer rules context\&. Creates a chained context and if CanRunRule will execute the inner rule\&. 
.br
.PP
\fBParameters\fP
.RS 4
\fIinnerRule\fP The inner rule\&.
.RE
.PP

.PP
Implements \fBCsla\&.Rules\&.IRuleContext\fP\&.
.PP
Definition at line 149 of file RuleContext\&.cs\&.
.SS "\fBIRuleContext\fP Csla\&.Rules\&.RuleContext\&.GetChainedContext (\fBIBusinessRuleBase\fP rule)"

.PP
Gets a new \fBRuleContext\fP object for a chained rule\&. 
.PP
\fBParameters\fP
.RS 4
\fIrule\fP Chained rule that will use this new context\&.
.RE
.PP
.PP
The properties from the existing \fBRuleContext\fP will be used to create the new context, with the exception of the Rule property which is set using the supplied \fBIBusinessRule\fP value\&. 
.PP
Implements \fBCsla\&.Rules\&.IRuleContext\fP\&.
.PP
Definition at line 260 of file RuleContext\&.cs\&.
.SS "T Csla\&.Rules\&.RuleContext\&.GetInputValue< T > (\fBIPropertyInfo\fP propertyInfo)"

.PP
Gets the value with explicit cast 
.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP 
.RE
.PP
\fBParameters\fP
.RS 4
\fIpropertyInfo\fP The generic property info\&.
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
Implements \fBCsla\&.Rules\&.IRuleContext\fP\&.
.PP
Definition at line 455 of file RuleContext\&.cs\&.
.SS "T Csla\&.Rules\&.RuleContext\&.GetInputValue< T > (\fBPropertyInfo\fP< T > propertyInfo)"

.PP
Gets the value\&. 
.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP 
.RE
.PP
\fBParameters\fP
.RS 4
\fIpropertyInfo\fP The property info\&.
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
Implements \fBCsla\&.Rules\&.IRuleContext\fP\&.
.PP
Definition at line 444 of file RuleContext\&.cs\&.
.SS "bool Csla\&.Rules\&.RuleContext\&.TryGetInputValue< T > (\fBIPropertyInfo\fP propertyInfo, ref T value)"

.PP
Tries to get the value with explicit cast\&. Use this method on LazyLoaded properties to test if value has been provided or not\&.
.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP 
.RE
.PP
\fBParameters\fP
.RS 4
\fIpropertyInfo\fP The generic property info\&.
.br
\fIvalue\fP The value\&.
.RE
.PP
\fBReturns\fP
.RS 4
true if value exists else false
.RE
.PP

.PP
Implements \fBCsla\&.Rules\&.IRuleContext\fP\&.
.PP
Definition at line 486 of file RuleContext\&.cs\&.
.SS "bool Csla\&.Rules\&.RuleContext\&.TryGetInputValue< T > (\fBPropertyInfo\fP< T > propertyInfo, ref T value)"

.PP
Tries to get the value\&. Use this method on LazyLoaded properties to test if value has been provided or not\&.
.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP 
.RE
.PP
\fBParameters\fP
.RS 4
\fIpropertyInfo\fP The generic property info\&.
.br
\fIvalue\fP The value\&.
.RE
.PP
\fBReturns\fP
.RS 4
true if value exists else false
.RE
.PP

.PP
Implements \fBCsla\&.Rules\&.IRuleContext\fP\&.
.PP
Definition at line 467 of file RuleContext\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "List<\fBIPropertyInfo\fP> Csla\&.Rules\&.RuleContext\&.DirtyProperties\fC [get]\fP"

.PP
Gets a list of dirty properties (value was updated)\&. The dirty properties\&. 
.PP
Definition at line 78 of file RuleContext\&.cs\&.
.SS "\fBRuleContextModes\fP Csla\&.Rules\&.RuleContext\&.ExecuteContext\fC [get]\fP, \fC [set]\fP"

.PP
Gets the execution context\&. The execution context\&.
.PP
Definition at line 141 of file RuleContext\&.cs\&.
.SS "Dictionary<\fBCsla\&.Core\&.IPropertyInfo\fP, object> Csla\&.Rules\&.RuleContext\&.InputPropertyValues\fC [get]\fP, \fC [set]\fP"

.PP
Gets a dictionary containing copies of property values from the target business object\&. 
.PP
Definition at line 68 of file RuleContext\&.cs\&.
.SS "bool Csla\&.Rules\&.RuleContext\&.IsCascadeContext\fC [get]\fP"

.PP
Gets a value indicating whether this instance is cascade context as a result of AffectedProperties\&. \fCtrue\fP if this instance is cascade context; otherwise, \fCfalse\fP\&. 
.PP
Definition at line 170 of file RuleContext\&.cs\&.
.SS "bool Csla\&.Rules\&.RuleContext\&.IsCheckObjectRulesContext\fC [get]\fP"

.PP
Gets a value indicating whether this instance is check object rules context\&. \fCtrue\fP if this instance is check object rules context; otherwise, \fCfalse\fP\&. 
.PP
Definition at line 206 of file RuleContext\&.cs\&.
.SS "bool Csla\&.Rules\&.RuleContext\&.IsCheckRulesContext\fC [get]\fP"

.PP
Gets a value indicating whether this instance is check rules context\&. \fCtrue\fP if this instance is check rules context; otherwise, \fCfalse\fP\&. 
.PP
Definition at line 194 of file RuleContext\&.cs\&.
.SS "bool Csla\&.Rules\&.RuleContext\&.IsPropertyChangedContext\fC [get]\fP"

.PP
Gets a value indicating whether this instance is property changed context\&. \fCtrue\fP if this instance is property changed context; otherwise, \fCfalse\fP\&. 
.PP
Definition at line 182 of file RuleContext\&.cs\&.
.SS "string Csla\&.Rules\&.RuleContext\&.OriginPropertyName\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the name of the origin property\&. The name of the origin property\&.
.PP
Definition at line 135 of file RuleContext\&.cs\&.
.SS "Dictionary<\fBCsla\&.Core\&.IPropertyInfo\fP, object> Csla\&.Rules\&.RuleContext\&.OutputPropertyValues\fC [get]\fP"

.PP
Gets a dictionary containing copies of property values that should be updated in the target object\&. 
.PP
Definition at line 94 of file RuleContext\&.cs\&.
.SS "List<\fBRuleResult\fP> Csla\&.Rules\&.RuleContext\&.Results\fC [get]\fP"

.PP
Gets a list of \fBRuleResult\fP objects containing the results of the rule\&. 
.PP
Definition at line 114 of file RuleContext\&.cs\&.
.SS "\fBIBusinessRuleBase\fP Csla\&.Rules\&.RuleContext\&.Rule\fC [get]\fP, \fC [set]\fP"

.PP
Gets the rule object\&. 
.PP
Definition at line 57 of file RuleContext\&.cs\&.
.SS "object Csla\&.Rules\&.RuleContext\&.Target\fC [get]\fP, \fC [set]\fP"

.PP
Gets a reference to the target business object\&. 
.PP
Definition at line 62 of file RuleContext\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
