.TH "Csla.Windows.BusyAnimation" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Windows.BusyAnimation \- User control that displays busy animation  

.SH SYNOPSIS
.br
.PP
.PP
Inherits UserControl\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBusyAnimation\fP ()"
.br
.RI "new instance busy animation "
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBDispose\fP (bool disposing)"
.br
.RI "Clean up any resources being used\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "Color \fBProgressBarForeColor\fP\fC [get, set]\fP"
.br
.RI "Set or get foreground color for busy animation's progress bar "
.ti -1c
.RI "Color \fBProgressBarBackColor\fP\fC [get, set]\fP"
.br
.RI "Set or get background color for busy animation's progress bar "
.ti -1c
.RI "bool \fBIsRunning\fP\fC [get, set]\fP"
.br
.RI "Indicates if animation needs to be shown\&. Set to true to start progress bar animation "
.in -1c
.SH "Detailed Description"
.PP 
User control that displays busy animation 


.PP
Definition at line 23 of file Csla\&.Windows\&.Shared/BusyAnimation\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Csla\&.Windows\&.BusyAnimation\&.BusyAnimation ()"

.PP
new instance busy animation 
.PP
Definition at line 28 of file Csla\&.Windows\&.Shared/BusyAnimation\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override void Csla\&.Windows\&.BusyAnimation\&.Dispose (bool disposing)\fC [protected]\fP"

.PP
Clean up any resources being used\&. 
.PP
\fBParameters\fP
.RS 4
\fIdisposing\fP true if managed resources should be disposed; otherwise, false\&.
.RE
.PP

.PP
Definition at line 14 of file BusyAnimation\&.designer\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "bool Csla\&.Windows\&.BusyAnimation\&.IsRunning\fC [get]\fP, \fC [set]\fP"

.PP
Indicates if animation needs to be shown\&. Set to true to start progress bar animation 
.PP
Definition at line 90 of file Csla\&.Windows\&.Shared/BusyAnimation\&.cs\&.
.SS "Color Csla\&.Windows\&.BusyAnimation\&.ProgressBarBackColor\fC [get]\fP, \fC [set]\fP"

.PP
Set or get background color for busy animation's progress bar 
.PP
Definition at line 67 of file Csla\&.Windows\&.Shared/BusyAnimation\&.cs\&.
.SS "Color Csla\&.Windows\&.BusyAnimation\&.ProgressBarForeColor\fC [get]\fP, \fC [set]\fP"

.PP
Set or get foreground color for busy animation's progress bar 
.PP
Definition at line 45 of file Csla\&.Windows\&.Shared/BusyAnimation\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
