.TH "Csla.ExecuteChildAttribute" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.ExecuteChildAttribute \- Specifies a method used by the server-side data portal to execute a child command object during an update operation\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.DataPortalChildOperationAttribute\fP\&.
.SH "Detailed Description"
.PP 
Specifies a method used by the server-side data portal to execute a child command object during an update operation\&. 


.PP
Definition at line 158 of file DataPortalOperationAttributes\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
