.TH "Csla.Test.DataPortal.InterceptorTests" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.DataPortal.InterceptorTests
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetup\fP ()"
.br
.ti -1c
.RI "void \fBCleanup\fP ()"
.br
.ti -1c
.RI "void \fBCreateWithIntercept\fP ()"
.br
.ti -1c
.RI "void \fBFetchWithIntercept\fP ()"
.br
.ti -1c
.RI "void \fBFetchListWithIntercept\fP ()"
.br
.ti -1c
.RI "void \fBInterceptException\fP ()"
.br
.ti -1c
.RI "void \fBUpdateWithIntercept\fP ()"
.br
.ti -1c
.RI "void \fBUpdateListWithIntercept\fP ()"
.br
.ti -1c
.RI "void \fBExecuteCommandWithIntercept\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 19 of file InterceptorTests\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Csla\&.Test\&.DataPortal\&.InterceptorTests\&.Cleanup ()"

.PP
Definition at line 29 of file InterceptorTests\&.cs\&.
.SS "void Csla\&.Test\&.DataPortal\&.InterceptorTests\&.CreateWithIntercept ()"

.PP
Definition at line 36 of file InterceptorTests\&.cs\&.
.SS "void Csla\&.Test\&.DataPortal\&.InterceptorTests\&.ExecuteCommandWithIntercept ()"

.PP
Definition at line 131 of file InterceptorTests\&.cs\&.
.SS "void Csla\&.Test\&.DataPortal\&.InterceptorTests\&.FetchListWithIntercept ()"

.PP
Definition at line 61 of file InterceptorTests\&.cs\&.
.SS "void Csla\&.Test\&.DataPortal\&.InterceptorTests\&.FetchWithIntercept ()"

.PP
Definition at line 49 of file InterceptorTests\&.cs\&.
.SS "void Csla\&.Test\&.DataPortal\&.InterceptorTests\&.InterceptException ()"

.PP
Definition at line 76 of file InterceptorTests\&.cs\&.
.SS "void Csla\&.Test\&.DataPortal\&.InterceptorTests\&.Setup ()"

.PP
Definition at line 22 of file InterceptorTests\&.cs\&.
.SS "void Csla\&.Test\&.DataPortal\&.InterceptorTests\&.UpdateListWithIntercept ()"

.PP
Definition at line 111 of file InterceptorTests\&.cs\&.
.SS "void Csla\&.Test\&.DataPortal\&.InterceptorTests\&.UpdateWithIntercept ()"

.PP
Definition at line 92 of file InterceptorTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
