.TH "Csla.Web.Mvc.IViewModel" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Web.Mvc.IViewModel \- Defines a CSLA \&.NET MVC viewmodel object\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBCsla\&.Web\&.Mvc\&.ViewModelBase< T >\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "object \fBModelObject\fP\fC [get, set]\fP"
.br
.RI "Object property for the contained business object "
.in -1c
.SH "Detailed Description"
.PP 
Defines a CSLA \&.NET MVC viewmodel object\&. 


.PP
Definition at line 13 of file Csla\&.Web\&.Mvc\&.Shared/IViewModel\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "object Csla\&.Web\&.Mvc\&.IViewModel\&.ModelObject\fC [get]\fP, \fC [set]\fP"

.PP
Object property for the contained business object 
.PP
Definition at line 18 of file Csla\&.Web\&.Mvc\&.Shared/IViewModel\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
