.TH "cslalighttest.Serialization.SerializationTests.StringCriteria" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cslalighttest.Serialization.SerializationTests.StringCriteria
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.CriteriaBase< StringCriteria >\fP\&.
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static readonly \fBPropertyInfo\fP< string > \fBValueProperty\fP = RegisterProperty<string>(c => c\&.Value)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBValue\fP\fC [get, set]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 50 of file SerializationTests\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "readonly \fBPropertyInfo\fP<string> cslalighttest\&.Serialization\&.SerializationTests\&.StringCriteria\&.ValueProperty = RegisterProperty<string>(c => c\&.Value)\fC [static]\fP"

.PP
Definition at line 52 of file SerializationTests\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "string cslalighttest\&.Serialization\&.SerializationTests\&.StringCriteria\&.Value\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 53 of file SerializationTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
