.TH "Csla.Test.Windows.PersonForm" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.Windows.PersonForm
.SH SYNOPSIS
.br
.PP
.PP
Inherits Form\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPersonForm\fP ()"
.br
.ti -1c
.RI "void \fBBindUI\fP (\fBEditablePerson\fP person, bool useStandardActionExtender)"
.br
.ti -1c
.RI "void \fBBindUI\fP (\fBEditablePerson\fP person)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "System\&.Windows\&.Forms\&.TextBox \fBauthLevelTextBox\fP"
.br
.ti -1c
.RI "System\&.Windows\&.Forms\&.TextBox \fBfirstNameTextBox\fP"
.br
.ti -1c
.RI "System\&.Windows\&.Forms\&.TextBox \fBlastNameTextBox\fP"
.br
.ti -1c
.RI "System\&.Windows\&.Forms\&.TextBox \fBmiddleNameTextBox\fP"
.br
.ti -1c
.RI "System\&.Windows\&.Forms\&.TextBox \fBplaceOfBirthTextBox\fP"
.br
.ti -1c
.RI "\fBCsla\&.Windows\&.ReadWriteAuthorization\fP \fBreadWriteAuthorization1\fP"
.br
.ti -1c
.RI "System\&.Windows\&.Forms\&.Button \fBSaveButton\fP"
.br
.ti -1c
.RI "System\&.Windows\&.Forms\&.Button \fBCloseButton\fP"
.br
.ti -1c
.RI "System\&.Windows\&.Forms\&.Button \fBCancelButton\fP"
.br
.ti -1c
.RI "System\&.Windows\&.Forms\&.Button \fBValidateButton\fP"
.br
.ti -1c
.RI "\fBCsla\&.Windows\&.BindingSourceRefresh\fP \fBbindingSourceRefresh1\fP"
.br
.ti -1c
.RI "System\&.Windows\&.Forms\&.ToolStripButton \fBcloseToolStripButton\fP"
.br
.ti -1c
.RI "System\&.Windows\&.Forms\&.ToolStripButton \fBvalidateToolStripButton\fP"
.br
.ti -1c
.RI "System\&.Windows\&.Forms\&.ToolStripButton \fBsaveToolStripButton\fP"
.br
.ti -1c
.RI "System\&.Windows\&.Forms\&.ToolStripButton \fBcancelToolStripButton\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBDispose\fP (bool disposing)"
.br
.RI "Clean up any resources being used\&. "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 20 of file PersonForm\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Csla\&.Test\&.Windows\&.PersonForm\&.PersonForm ()"

.PP
Definition at line 22 of file PersonForm\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Csla\&.Test\&.Windows\&.PersonForm\&.BindUI (\fBEditablePerson\fP person)"

.PP
Definition at line 41 of file PersonForm\&.cs\&.
.SS "void Csla\&.Test\&.Windows\&.PersonForm\&.BindUI (\fBEditablePerson\fP person, bool useStandardActionExtender)"

.PP
Definition at line 27 of file PersonForm\&.cs\&.
.SS "override void Csla\&.Test\&.Windows\&.PersonForm\&.Dispose (bool disposing)\fC [protected]\fP"

.PP
Clean up any resources being used\&. 
.PP
\fBParameters\fP
.RS 4
\fIdisposing\fP true if managed resources should be disposed; otherwise, false\&.
.RE
.PP

.PP
Definition at line 14 of file PersonForm\&.Designer\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "System\&.Windows\&.Forms\&.TextBox Csla\&.Test\&.Windows\&.PersonForm\&.authLevelTextBox"

.PP
Definition at line 314 of file PersonForm\&.Designer\&.cs\&.
.SS "\fBCsla\&.Windows\&.BindingSourceRefresh\fP Csla\&.Test\&.Windows\&.PersonForm\&.bindingSourceRefresh1"

.PP
Definition at line 327 of file PersonForm\&.Designer\&.cs\&.
.SS "System\&.Windows\&.Forms\&.Button Csla\&.Test\&.Windows\&.PersonForm\&.CancelButton"

.PP
Definition at line 324 of file PersonForm\&.Designer\&.cs\&.
.SS "System\&.Windows\&.Forms\&.ToolStripButton Csla\&.Test\&.Windows\&.PersonForm\&.cancelToolStripButton"

.PP
Definition at line 333 of file PersonForm\&.Designer\&.cs\&.
.SS "System\&.Windows\&.Forms\&.Button Csla\&.Test\&.Windows\&.PersonForm\&.CloseButton"

.PP
Definition at line 322 of file PersonForm\&.Designer\&.cs\&.
.SS "System\&.Windows\&.Forms\&.ToolStripButton Csla\&.Test\&.Windows\&.PersonForm\&.closeToolStripButton"

.PP
Definition at line 330 of file PersonForm\&.Designer\&.cs\&.
.SS "System\&.Windows\&.Forms\&.TextBox Csla\&.Test\&.Windows\&.PersonForm\&.firstNameTextBox"

.PP
Definition at line 315 of file PersonForm\&.Designer\&.cs\&.
.SS "System\&.Windows\&.Forms\&.TextBox Csla\&.Test\&.Windows\&.PersonForm\&.lastNameTextBox"

.PP
Definition at line 316 of file PersonForm\&.Designer\&.cs\&.
.SS "System\&.Windows\&.Forms\&.TextBox Csla\&.Test\&.Windows\&.PersonForm\&.middleNameTextBox"

.PP
Definition at line 317 of file PersonForm\&.Designer\&.cs\&.
.SS "System\&.Windows\&.Forms\&.TextBox Csla\&.Test\&.Windows\&.PersonForm\&.placeOfBirthTextBox"

.PP
Definition at line 318 of file PersonForm\&.Designer\&.cs\&.
.SS "\fBCsla\&.Windows\&.ReadWriteAuthorization\fP Csla\&.Test\&.Windows\&.PersonForm\&.readWriteAuthorization1"

.PP
Definition at line 319 of file PersonForm\&.Designer\&.cs\&.
.SS "System\&.Windows\&.Forms\&.Button Csla\&.Test\&.Windows\&.PersonForm\&.SaveButton"

.PP
Definition at line 321 of file PersonForm\&.Designer\&.cs\&.
.SS "System\&.Windows\&.Forms\&.ToolStripButton Csla\&.Test\&.Windows\&.PersonForm\&.saveToolStripButton"

.PP
Definition at line 332 of file PersonForm\&.Designer\&.cs\&.
.SS "System\&.Windows\&.Forms\&.Button Csla\&.Test\&.Windows\&.PersonForm\&.ValidateButton"

.PP
Definition at line 326 of file PersonForm\&.Designer\&.cs\&.
.SS "System\&.Windows\&.Forms\&.ToolStripButton Csla\&.Test\&.Windows\&.PersonForm\&.validateToolStripButton"

.PP
Definition at line 331 of file PersonForm\&.Designer\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
