.TH "Csla.Test.ObjectFactory.ObjectFactoryTests" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.ObjectFactory.ObjectFactoryTests
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBCleanup\fP ()"
.br
.RI "Always make sure to cleanup after each test "
.ti -1c
.RI "void \fBCreate\fP ()"
.br
.ti -1c
.RI "void \fBCreateLocal\fP ()"
.br
.ti -1c
.RI "void \fBCreateWithParam\fP ()"
.br
.ti -1c
.RI "void \fBCreateMissing\fP ()"
.br
.ti -1c
.RI "void \fBFetchNoCriteria\fP ()"
.br
.ti -1c
.RI "void \fBFetchCriteria\fP ()"
.br
.ti -1c
.RI "void \fBUpdate\fP ()"
.br
.ti -1c
.RI "void \fBUpdateTransactionScope\fP ()"
.br
.ti -1c
.RI "void \fBUpdateTransactionScopeUsingCustomTransactionLevelAndTimeout\fP ()"
.br
.ti -1c
.RI "void \fBUpdateTransactionScopeUsingDefaultTransactionLevelAndTimeout\fP ()"
.br
.ti -1c
.RI "void \fBDelete\fP ()"
.br
.ti -1c
.RI "void \fBFetchLoadProperty\fP ()"
.br
.ti -1c
.RI "void \fBDataPortalExecute_OnCommandObjectWithLocalProxy_CallsFactoryExecute\fP ()"
.br
.ti -1c
.RI "void \fBDataPortalExecute_OnCommandObjectWithFalseExecuteMethod_ThrowsExeptionMehodNotFound\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 27 of file ObjectFactoryTests\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Csla\&.Test\&.ObjectFactory\&.ObjectFactoryTests\&.Cleanup ()"

.PP
Always make sure to cleanup after each test 
.PP
Definition at line 33 of file ObjectFactoryTests\&.cs\&.
.SS "void Csla\&.Test\&.ObjectFactory\&.ObjectFactoryTests\&.Create ()"

.PP
Definition at line 45 of file ObjectFactoryTests\&.cs\&.
.SS "void Csla\&.Test\&.ObjectFactory\&.ObjectFactoryTests\&.CreateLocal ()"

.PP
Definition at line 61 of file ObjectFactoryTests\&.cs\&.
.SS "void Csla\&.Test\&.ObjectFactory\&.ObjectFactoryTests\&.CreateMissing ()"

.PP
Definition at line 92 of file ObjectFactoryTests\&.cs\&.
.SS "void Csla\&.Test\&.ObjectFactory\&.ObjectFactoryTests\&.CreateWithParam ()"

.PP
Definition at line 74 of file ObjectFactoryTests\&.cs\&.
.SS "void Csla\&.Test\&.ObjectFactory\&.ObjectFactoryTests\&.DataPortalExecute_OnCommandObjectWithFalseExecuteMethod_ThrowsExeptionMehodNotFound ()"

.PP
Definition at line 277 of file ObjectFactoryTests\&.cs\&.
.SS "void Csla\&.Test\&.ObjectFactory\&.ObjectFactoryTests\&.DataPortalExecute_OnCommandObjectWithLocalProxy_CallsFactoryExecute ()"

.PP
Definition at line 266 of file ObjectFactoryTests\&.cs\&.
.SS "void Csla\&.Test\&.ObjectFactory\&.ObjectFactoryTests\&.Delete ()"

.PP
Definition at line 242 of file ObjectFactoryTests\&.cs\&.
.SS "void Csla\&.Test\&.ObjectFactory\&.ObjectFactoryTests\&.FetchCriteria ()"

.PP
Definition at line 120 of file ObjectFactoryTests\&.cs\&.
.SS "void Csla\&.Test\&.ObjectFactory\&.ObjectFactoryTests\&.FetchLoadProperty ()"

.PP
Definition at line 255 of file ObjectFactoryTests\&.cs\&.
.SS "void Csla\&.Test\&.ObjectFactory\&.ObjectFactoryTests\&.FetchNoCriteria ()"

.PP
Definition at line 109 of file ObjectFactoryTests\&.cs\&.
.SS "void Csla\&.Test\&.ObjectFactory\&.ObjectFactoryTests\&.Update ()"

.PP
Definition at line 131 of file ObjectFactoryTests\&.cs\&.
.SS "void Csla\&.Test\&.ObjectFactory\&.ObjectFactoryTests\&.UpdateTransactionScope ()"

.PP
Definition at line 145 of file ObjectFactoryTests\&.cs\&.
.SS "void Csla\&.Test\&.ObjectFactory\&.ObjectFactoryTests\&.UpdateTransactionScopeUsingCustomTransactionLevelAndTimeout ()"

.PP
Definition at line 162 of file ObjectFactoryTests\&.cs\&.
.SS "void Csla\&.Test\&.ObjectFactory\&.ObjectFactoryTests\&.UpdateTransactionScopeUsingDefaultTransactionLevelAndTimeout ()"

.PP
Definition at line 183 of file ObjectFactoryTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
