.TH "Csla.Configuration.CslaSerializationConfiguration" 3 "Thu Jul 22 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Configuration.CslaSerializationConfiguration \- Use this type to configure the settings for serialization\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCslaSerializationConfiguration\fP \fBSerializationFormatter\fP (string formatterName)"
.br
.RI "Sets the serialization formatter type used by CSLA \&.NET for all explicit object serialization (such as cloning, n-level undo, etc)\&. "
.ti -1c
.RI "\fBCslaSerializationConfiguration\fP \fBMobileWriter\fP (string typeName)"
.br
.RI "Sets type of the writer that is used to write data to serialization stream in SerializationFormatterFactory\&.GetFormatter()\&. "
.ti -1c
.RI "\fBCslaSerializationConfiguration\fP \fBMobileReader\fP (string typeName)"
.br
.RI "Sets type of the writer that is used to read data to serialization stream in SerializationFormatterFactory\&.GetFormatter()\&. "
.in -1c
.SH "Detailed Description"
.PP 
Use this type to configure the settings for serialization\&. 


.PP
Definition at line 27 of file CslaSerializationConfiguration\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBCslaSerializationConfiguration\fP Csla\&.Configuration\&.CslaSerializationConfiguration\&.MobileReader (string typeName)"

.PP
Sets type of the writer that is used to read data to serialization stream in SerializationFormatterFactory\&.GetFormatter()\&. 
.PP
\fBParameters\fP
.RS 4
\fItypeName\fP Assembly qualified type name
.RE
.PP

.PP
Definition at line 58 of file CslaSerializationConfiguration\&.cs\&.
.SS "\fBCslaSerializationConfiguration\fP Csla\&.Configuration\&.CslaSerializationConfiguration\&.MobileWriter (string typeName)"

.PP
Sets type of the writer that is used to write data to serialization stream in SerializationFormatterFactory\&.GetFormatter()\&. 
.PP
\fBParameters\fP
.RS 4
\fItypeName\fP Assembly qualified type name
.RE
.PP

.PP
Definition at line 47 of file CslaSerializationConfiguration\&.cs\&.
.SS "\fBCslaSerializationConfiguration\fP Csla\&.Configuration\&.CslaSerializationConfiguration\&.SerializationFormatter (string formatterName)"

.PP
Sets the serialization formatter type used by CSLA \&.NET for all explicit object serialization (such as cloning, n-level undo, etc)\&. 
.PP
\fBParameters\fP
.RS 4
\fIformatterName\fP Formatter name (one of MobileFormatter, BinaryFormatter, NetDataContractSerializer, or type name)
.RE
.PP

.PP
Definition at line 36 of file CslaSerializationConfiguration\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
