.TH "Csla.Ios.Test.NullableEntity" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Ios.Test.NullableEntity
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.BusinessBase< NullableEntity >\fP\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBNullableEntity\fP \fBNewNullableEntity\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static readonly \fBPropertyInfo\fP< string > \fBNameProperty\fP = RegisterProperty<string>(c => c\&.Name)"
.br
.ti -1c
.RI "static readonly \fBPropertyInfo\fP< int?> \fBNullableIntegerProperty\fP = RegisterProperty<int?>(c => c\&.NullableInteger)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBAddBusinessRules\fP ()"
.br
.ti -1c
.RI "override void \fBDataPortal_Create\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBName\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int? \fBNullableInteger\fP\fC [get, set]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 8 of file NullableEntity\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override void Csla\&.Ios\&.Test\&.NullableEntity\&.AddBusinessRules ()\fC [protected]\fP"

.PP
Definition at line 28 of file NullableEntity\&.cs\&.
.SS "override void Csla\&.Ios\&.Test\&.NullableEntity\&.DataPortal_Create ()\fC [protected]\fP"

.PP
Definition at line 66 of file NullableEntity\&.cs\&.
.SS "static \fBNullableEntity\fP Csla\&.Ios\&.Test\&.NullableEntity\&.NewNullableEntity ()\fC [static]\fP"

.PP
Definition at line 61 of file NullableEntity\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "readonly \fBPropertyInfo\fP<string> Csla\&.Ios\&.Test\&.NullableEntity\&.NameProperty = RegisterProperty<string>(c => c\&.Name)\fC [static]\fP"

.PP
Definition at line 10 of file NullableEntity\&.cs\&.
.SS "readonly \fBPropertyInfo\fP<int?> Csla\&.Ios\&.Test\&.NullableEntity\&.NullableIntegerProperty = RegisterProperty<int?>(c => c\&.NullableInteger)\fC [static]\fP"

.PP
Definition at line 18 of file NullableEntity\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "string Csla\&.Ios\&.Test\&.NullableEntity\&.Name\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 12 of file NullableEntity\&.cs\&.
.SS "int? Csla\&.Ios\&.Test\&.NullableEntity\&.NullableInteger\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 20 of file NullableEntity\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
