.TH "Csla.Test.ValidationRules.HasRulesManager" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.ValidationRules.HasRulesManager
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.BusinessBase< HasRulesManager >\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCriteria\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBPropertyInfo\fP< string > \fBNameProperty\fP = RegisterProperty<string>(c => c\&.Name)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBAddBusinessRules\fP ()"
.br
.ti -1c
.RI "void \fBDataPortal_Fetch\fP (object criteria)"
.br
.ti -1c
.RI "void \fBDataPortal_Update\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBName\fP\fC [get, set]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 18 of file HasRulesManager\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override void Csla\&.Test\&.ValidationRules\&.HasRulesManager\&.AddBusinessRules ()\fC [protected]\fP"

.PP
Definition at line 27 of file HasRulesManager\&.cs\&.
.SS "void Csla\&.Test\&.ValidationRules\&.HasRulesManager\&.DataPortal_Fetch (object criteria)\fC [protected]\fP"

.PP
Definition at line 28 of file HasRulesManager\&.partial\&.cs\&.
.SS "void Csla\&.Test\&.ValidationRules\&.HasRulesManager\&.DataPortal_Update ()\fC [protected]\fP"

.PP
Definition at line 38 of file HasRulesManager\&.partial\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBPropertyInfo\fP<string> Csla\&.Test\&.ValidationRules\&.HasRulesManager\&.NameProperty = RegisterProperty<string>(c => c\&.Name)\fC [static]\fP"

.PP
Definition at line 20 of file HasRulesManager\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "string Csla\&.Test\&.ValidationRules\&.HasRulesManager\&.Name\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 21 of file HasRulesManager\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
