.TH "Csla.Rules.CommonRules" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Rules.CommonRules
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBIsInRole\fP"
.br
.RI "\fBIsInRole\fP authorization rule\&. "
.ti -1c
.RI "class \fBIsNotInRole\fP"
.br
.RI "\fBIsNotInRole\fP authorization rule\&. "
.ti -1c
.RI "class \fBCommonBusinessRule\fP"
.br
.RI "Base class used to create common rules\&. "
.ti -1c
.RI "class \fBDataAnnotation\fP"
.br
.RI "Business rule that encapsulates a DataAnnotations ValidationAttribute rule\&. "
.ti -1c
.RI "class \fBRequired\fP"
.br
.RI "Business rule for a required string\&. "
.ti -1c
.RI "class \fBMaxLength\fP"
.br
.RI "Business rule for a maximum length string\&. "
.ti -1c
.RI "class \fBMinLength\fP"
.br
.RI "Business rule for a minimum length string\&. "
.ti -1c
.RI "class \fBMinValue\fP"
.br
.RI "Business rule for a minimum value\&. "
.ti -1c
.RI "class \fBMaxValue\fP"
.br
.RI "Business rule for a maximum value\&. "
.ti -1c
.RI "class \fBRegExMatch\fP"
.br
.RI "Business rule that evaluates a regular expression\&. "
.ti -1c
.RI "class \fBInfoMessage\fP"
.br
.RI "Adds an information message to a property\&. "
.ti -1c
.RI "class \fBLambda\fP"
.br
.RI "A business rule defined by a lambda expression\&. "
.ti -1c
.RI "class \fBDependency\fP"
.br
.RI "A rule that establishes a dependency between two properties\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
