.TH "Csla.Test.ChildrenByInterface" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.ChildrenByInterface
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBChildInterfaceTests\fP"
.br
.ti -1c
.RI "interface \fBIItem\fP"
.br
.ti -1c
.RI "class \fBItem1\fP"
.br
.ti -1c
.RI "class \fBItem2\fP"
.br
.ti -1c
.RI "class \fBItemList\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
