.TH "Csla.Test.DataPortalChild.Root" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.DataPortalChild.Root
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.BusinessBase< Root >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBFetchChild\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBDataPortal_Insert\fP ()"
.br
.ti -1c
.RI "void \fBDataPortal_Update\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBData\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBChild\fP \fBChild\fP\fC [get]\fP"
.br
.ti -1c
.RI "\fBChildList\fP \fBChildList\fP\fC [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 16 of file Root\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Csla\&.Test\&.DataPortalChild\&.Root\&.DataPortal_Insert ()\fC [protected]\fP"

.PP
Definition at line 53 of file Root\&.cs\&.
.SS "void Csla\&.Test\&.DataPortalChild\&.Root\&.DataPortal_Update ()\fC [protected]\fP"

.PP
Definition at line 59 of file Root\&.cs\&.
.SS "void Csla\&.Test\&.DataPortalChild\&.Root\&.FetchChild ()"

.PP
Definition at line 47 of file Root\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "\fBChild\fP Csla\&.Test\&.DataPortalChild\&.Root\&.Child\fC [get]\fP"

.PP
Definition at line 26 of file Root\&.cs\&.
.SS "\fBChildList\fP Csla\&.Test\&.DataPortalChild\&.Root\&.ChildList\fC [get]\fP"

.PP
Definition at line 37 of file Root\&.cs\&.
.SS "string Csla\&.Test\&.DataPortalChild\&.Root\&.Data\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 19 of file Root\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
