.TH "Csla.Testing.Business.EditableChildTests.MockList" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Testing.Business.EditableChildTests.MockList
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.BusinessListBase< MockList, MockEditableChild >\fP\&.
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static Guid \fBMockEditableChildId1\fP = new Guid('{4AF07634\-1D10\-4d09\-BBCB\-42396324C103}')"
.br
.ti -1c
.RI "static Guid \fBMockEditableChildId2\fP = new Guid('{402DB94B\-0D93\-4be2\-AFD0\-7D1587CDDBC2}')"
.br
.ti -1c
.RI "static Guid \fBMockEditableChildId3\fP = new Guid('{B2ADE99D\-7AB4\-4e70\-AEA1\-D70443BCC3B0}')"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBDataPortal_Update\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 14 of file MockList\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Csla\&.Testing\&.Business\&.EditableChildTests\&.MockList\&.DataPortal_Update ()\fC [protected]\fP"

.PP
Definition at line 32 of file MockList\&.partial\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "Guid Csla\&.Testing\&.Business\&.EditableChildTests\&.MockList\&.MockEditableChildId1 = new Guid('{4AF07634\-1D10\-4d09\-BBCB\-42396324C103}')\fC [static]\fP"

.PP
Definition at line 16 of file MockList\&.cs\&.
.SS "Guid Csla\&.Testing\&.Business\&.EditableChildTests\&.MockList\&.MockEditableChildId2 = new Guid('{402DB94B\-0D93\-4be2\-AFD0\-7D1587CDDBC2}')\fC [static]\fP"

.PP
Definition at line 17 of file MockList\&.cs\&.
.SS "Guid Csla\&.Testing\&.Business\&.EditableChildTests\&.MockList\&.MockEditableChildId3 = new Guid('{B2ADE99D\-7AB4\-4e70\-AEA1\-D70443BCC3B0}')\fC [static]\fP"

.PP
Definition at line 18 of file MockList\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
