.TH "Csla.Test.DataPortalTest.SingleOverloadTest" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.DataPortalTest.SingleOverloadTest
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBTestDpCreate\fP ()"
.br
.ti -1c
.RI "void \fBTestDpCreateWithCriteria\fP ()"
.br
.ti -1c
.RI "void \fBTestDpFetch\fP ()"
.br
.ti -1c
.RI "void \fBTestDpDelete\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 26 of file SingleOverloadTest\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Csla\&.Test\&.DataPortalTest\&.SingleOverloadTest\&.TestDpCreate ()"

.PP
Definition at line 29 of file SingleOverloadTest\&.cs\&.
.SS "void Csla\&.Test\&.DataPortalTest\&.SingleOverloadTest\&.TestDpCreateWithCriteria ()"

.PP
Definition at line 35 of file SingleOverloadTest\&.cs\&.
.SS "void Csla\&.Test\&.DataPortalTest\&.SingleOverloadTest\&.TestDpDelete ()"

.PP
Definition at line 47 of file SingleOverloadTest\&.cs\&.
.SS "void Csla\&.Test\&.DataPortalTest\&.SingleOverloadTest\&.TestDpFetch ()"

.PP
Definition at line 41 of file SingleOverloadTest\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
