.TH "Csla.Test.ObjectFactory.RootFactory" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.ObjectFactory.RootFactory
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "object \fBCreate\fP ()"
.br
.ti -1c
.RI "object \fBCreate\fP (int test)"
.br
.ti -1c
.RI "object \fBCreate\fP (string criteria)"
.br
.ti -1c
.RI "object \fBFetch\fP ()"
.br
.ti -1c
.RI "object \fBFetch\fP (string criteria)"
.br
.ti -1c
.RI "object \fBUpdate\fP (\fBRoot\fP obj)"
.br
.ti -1c
.RI "object \fBUpdate2\fP (\fBRoot\fP obj)"
.br
.ti -1c
.RI "object \fBUpdate3\fP (\fBRoot\fP obj)"
.br
.ti -1c
.RI "void \fBDelete\fP (string criteria)"
.br
.ti -1c
.RI "void \fBInvoke\fP (\fBCsla\&.DataPortalEventArgs\fP args)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 15 of file RootFactory\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "object Csla\&.Test\&.ObjectFactory\&.RootFactory\&.Create ()"

.PP
Definition at line 17 of file RootFactory\&.cs\&.
.SS "object Csla\&.Test\&.ObjectFactory\&.RootFactory\&.Create (int test)"

.PP
Definition at line 26 of file RootFactory\&.cs\&.
.SS "object Csla\&.Test\&.ObjectFactory\&.RootFactory\&.Create (string criteria)"

.PP
Definition at line 33 of file RootFactory\&.cs\&.
.SS "void Csla\&.Test\&.ObjectFactory\&.RootFactory\&.Delete (string criteria)"

.PP
Definition at line 84 of file RootFactory\&.cs\&.
.SS "object Csla\&.Test\&.ObjectFactory\&.RootFactory\&.Fetch ()"

.PP
Definition at line 42 of file RootFactory\&.cs\&.
.SS "object Csla\&.Test\&.ObjectFactory\&.RootFactory\&.Fetch (string criteria)"

.PP
Definition at line 50 of file RootFactory\&.cs\&.
.SS "void Csla\&.Test\&.ObjectFactory\&.RootFactory\&.Invoke (\fBCsla\&.DataPortalEventArgs\fP args)"

.PP
Definition at line 91 of file RootFactory\&.cs\&.
.SS "object Csla\&.Test\&.ObjectFactory\&.RootFactory\&.Update (\fBRoot\fP obj)"

.PP
Definition at line 58 of file RootFactory\&.cs\&.
.SS "object Csla\&.Test\&.ObjectFactory\&.RootFactory\&.Update2 (\fBRoot\fP obj)"

.PP
Definition at line 67 of file RootFactory\&.cs\&.
.SS "object Csla\&.Test\&.ObjectFactory\&.RootFactory\&.Update3 (\fBRoot\fP obj)"

.PP
Definition at line 76 of file RootFactory\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
