.TH "Csla.Test.DataPortal.AmbiguousNoCriteriaCreate" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.DataPortal.AmbiguousNoCriteriaCreate
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.BusinessBase< AmbiguousNoCriteriaCreate >\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 423 of file ServiceProviderMethodCallerTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
