.TH "Csla.Rules.CommonRules.IsNotInRole" 3 "Thu Jul 22 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Rules.CommonRules.IsNotInRole \- \fBIsNotInRole\fP authorization rule\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.Rules\&.AuthorizationRule\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBIsNotInRole\fP (\fBAuthorizationActions\fP action, List< string > roles)"
.br
.RI "Creates an instance of the rule\&. "
.ti -1c
.RI "\fBIsNotInRole\fP (\fBAuthorizationActions\fP action, params string[] roles)"
.br
.RI "Creates an instance of the rule\&. "
.ti -1c
.RI "\fBIsNotInRole\fP (\fBAuthorizationActions\fP action, \fBCsla\&.Core\&.IMemberInfo\fP element, List< string > roles)"
.br
.RI "Creates an instance of the rule\&. "
.ti -1c
.RI "\fBIsNotInRole\fP (\fBAuthorizationActions\fP action, \fBCsla\&.Core\&.IMemberInfo\fP element, params string[] roles)"
.br
.RI "Creates an instance of the rule\&. "
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBExecute\fP (\fBIAuthorizationContext\fP context)"
.br
.RI "Rule implementation\&. "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
\fBIsNotInRole\fP authorization rule\&. 


.PP
Definition at line 96 of file Csla/Rules/AuthorizationRules\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Csla\&.Rules\&.CommonRules\&.IsNotInRole\&.IsNotInRole (\fBAuthorizationActions\fP action, List< string > roles)"

.PP
Creates an instance of the rule\&. 
.PP
\fBParameters\fP
.RS 4
\fIaction\fP Action this rule will enforce\&.
.br
\fIroles\fP List of disallowed roles\&.
.RE
.PP

.PP
Definition at line 105 of file Csla/Rules/AuthorizationRules\&.cs\&.
.SS "Csla\&.Rules\&.CommonRules\&.IsNotInRole\&.IsNotInRole (\fBAuthorizationActions\fP action, params string[] roles)"

.PP
Creates an instance of the rule\&. 
.PP
\fBParameters\fP
.RS 4
\fIaction\fP Action this rule will enforce\&.
.br
\fIroles\fP List of disallowed roles\&.
.RE
.PP

.PP
Definition at line 116 of file Csla/Rules/AuthorizationRules\&.cs\&.
.SS "Csla\&.Rules\&.CommonRules\&.IsNotInRole\&.IsNotInRole (\fBAuthorizationActions\fP action, \fBCsla\&.Core\&.IMemberInfo\fP element, List< string > roles)"

.PP
Creates an instance of the rule\&. 
.PP
\fBParameters\fP
.RS 4
\fIaction\fP Action this rule will enforce\&.
.br
\fIelement\fP Member to be authorized\&.
.br
\fIroles\fP List of disallowed roles\&.
.RE
.PP

.PP
Definition at line 128 of file Csla/Rules/AuthorizationRules\&.cs\&.
.SS "Csla\&.Rules\&.CommonRules\&.IsNotInRole\&.IsNotInRole (\fBAuthorizationActions\fP action, \fBCsla\&.Core\&.IMemberInfo\fP element, params string[] roles)"

.PP
Creates an instance of the rule\&. 
.PP
\fBParameters\fP
.RS 4
\fIaction\fP Action this rule will enforce\&.
.br
\fIelement\fP Member to be authorized\&.
.br
\fIroles\fP List of disallowed roles\&.
.RE
.PP

.PP
Definition at line 140 of file Csla/Rules/AuthorizationRules\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override void Csla\&.Rules\&.CommonRules\&.IsNotInRole\&.Execute (\fBIAuthorizationContext\fP context)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Rule implementation\&. 
.PP
\fBParameters\fP
.RS 4
\fIcontext\fP Rule context\&.
.RE
.PP

.PP
Implements \fBCsla\&.Rules\&.AuthorizationRule\fP\&.
.PP
Definition at line 150 of file Csla/Rules/AuthorizationRules\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
