.TH "Csla.Analyzers.IntegrationTests.PublicConstructorWithArgumentsTest" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Analyzers.IntegrationTests.PublicConstructorWithArgumentsTest
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.BusinessBase< PublicConstructorWithArgumentsTest >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPublicConstructorWithArgumentsTest\fP (int x)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 34 of file ConstructorTests\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Csla\&.Analyzers\&.IntegrationTests\&.PublicConstructorWithArgumentsTest\&.PublicConstructorWithArgumentsTest (int x)"

.PP
Definition at line 37 of file ConstructorTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
