.TH "Csla.Xaml.CancellableViewModel< T >" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Xaml.CancellableViewModel< T > \- \fBViewModel\fP without multithreading (concurrency) bugs\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.Xaml\&.ViewModel< T >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBCancelRefresh\fP ()"
.br
.RI "Cancel refresh operation\&. "
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBCancellableViewModel\fP ()"
.br
.ti -1c
.RI "new void \fBBeginRefresh\fP (Action< EventHandler< \fBDataPortalResult\fP< T >>> factoryMethod)"
.br
.RI "Creates or retrieves a new instance of the Model by invoking a static factory method\&. "
.ti -1c
.RI "override void \fBBeginRefresh\fP (string factoryMethod, params object[] factoryParameters)"
.br
.RI "Creates or retrieves a new instance of the Model by invoking a static factory method\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "bool \fBIsConcurentRefreshesAllowed\fP\fC [get, set]\fP"
.br
.RI "Allows more than one refresh operations in one time\&. Anyway, only the last refresh request will set the Model\&. "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
\fBViewModel\fP without multithreading (concurrency) bugs\&. 


.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP 
.RE
.PP

.PP
Definition at line 21 of file CancellableViewModel\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBCsla\&.Xaml\&.CancellableViewModel\fP< T >\&.\fBCancellableViewModel\fP ()\fC [protected]\fP"

.PP

.PP
Definition at line 28 of file CancellableViewModel\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "new void \fBCsla\&.Xaml\&.CancellableViewModel\fP< T >\&.BeginRefresh (Action< EventHandler< \fBDataPortalResult\fP< T >>> factoryMethod)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Creates or retrieves a new instance of the Model by invoking a static factory method\&. 
.PP
\fBParameters\fP
.RS 4
\fIfactoryMethod\fP Static factory method action\&.
.RE
.PP
.PP
BeginRefresh(BusinessList\&.BeginGetList)
.PP
BeginRefresh(handler => BusinessList\&.BeginGetList(handler))
.PP
BeginRefresh(handler => BusinessList\&.BeginGetList(id, handler))
.PP
Reimplemented from \fBCsla\&.Xaml\&.ViewModelBase< T >\fP\&.
.PP
Definition at line 48 of file CancellableViewModel\&.cs\&.
.SS "override void \fBCsla\&.Xaml\&.CancellableViewModel\fP< T >\&.BeginRefresh (string factoryMethod, params object[] factoryParameters)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Creates or retrieves a new instance of the Model by invoking a static factory method\&. 
.PP
\fBParameters\fP
.RS 4
\fIfactoryMethod\fP Name of the static factory method\&.
.br
\fIfactoryParameters\fP Factory method parameters\&.
.RE
.PP

.PP
Reimplemented from \fBCsla\&.Xaml\&.ViewModelBase< T >\fP\&.
.PP
Definition at line 60 of file CancellableViewModel\&.cs\&.
.SS "virtual void \fBCsla\&.Xaml\&.CancellableViewModel\fP< T >\&.CancelRefresh ()\fC [virtual]\fP"

.PP
Cancel refresh operation\&. 
.PP
Definition at line 69 of file CancellableViewModel\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "bool \fBCsla\&.Xaml\&.CancellableViewModel\fP< T >\&.IsConcurentRefreshesAllowed\fC [get]\fP, \fC [set]\fP"

.PP
Allows more than one refresh operations in one time\&. Anyway, only the last refresh request will set the Model\&. 
.PP
Definition at line 37 of file CancellableViewModel\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
