.TH "Csla.Web.Mvc.Controller" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Web.Mvc.Controller \- Provides methods that respond to HTTP requests in an ASP\&.NET MVC web site\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits System\&.Web\&.Mvc\&.Controller\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "bool \fBSaveObject< T >\fP (T item, bool forceUpdate)"
.br
.RI "Performs a Save() operation on an editable business object, with appropriate validation and exception handling\&. "
.ti -1c
.RI "virtual bool \fBSaveObject< T >\fP (T item, Action< T > updateModel, bool forceUpdate)"
.br
.RI "Performs a Save() operation on an editable business object, with appropriate validation and exception handling\&. "
.ti -1c
.RI "void \fBLoadProperty< P >\fP (object obj, \fBPropertyInfo\fP< P > propertyInfo, P newValue)"
.br
.RI "Loads a property's managed field with the supplied value calling PropertyHasChanged if the value does change\&. "
.in -1c
.SH "Detailed Description"
.PP 
Provides methods that respond to HTTP requests in an ASP\&.NET MVC web site\&. 


.PP
Definition at line 30 of file Controller\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Csla\&.Web\&.Mvc\&.Controller\&.LoadProperty< P > (object obj, \fBPropertyInfo\fP< P > propertyInfo, P newValue)\fC [protected]\fP"

.PP
Loads a property's managed field with the supplied value calling PropertyHasChanged if the value does change\&. 
.PP
\fBTemplate Parameters\fP
.RS 4
\fIP\fP Type of the property\&. 
.RE
.PP
\fBParameters\fP
.RS 4
\fIobj\fP Object on which to call the method\&. 
.br
\fIpropertyInfo\fP \fBPropertyInfo\fP object containing property metadata\&.
.br
\fInewValue\fP The new value for the property\&.
.RE
.PP
.PP
No authorization checks occur when this method is called, and no PropertyChanging or PropertyChanged events are raised\&. Loading values does not cause validation rules to be invoked\&. 
.PP
Definition at line 192 of file Controller\&.cs\&.
.SS "virtual bool Csla\&.Web\&.Mvc\&.Controller\&.SaveObject< T > (T item, Action< T > updateModel, bool forceUpdate)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Performs a Save() operation on an editable business object, with appropriate validation and exception handling\&. 
.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP Type of business object\&.
.RE
.PP
\fBParameters\fP
.RS 4
\fIitem\fP The business object to insert\&.
.br
\fIupdateModel\fP Delegate that invokes the UpdateModel() method\&.
.br
\fIforceUpdate\fP true to force Save() to be an update\&.
.RE
.PP
\fBReturns\fP
.RS 4
true the Save() succeeds, false if not\&.
.RE
.PP

.PP
\fBType Constraints\fP
.TP
\fIT\fP : \fIclass\fP
.TP
\fIT\fP : \fICore\&.ISavable\fP
.PP
Definition at line 141 of file Controller\&.cs\&.
.SS "bool Csla\&.Web\&.Mvc\&.Controller\&.SaveObject< T > (T item, bool forceUpdate)\fC [protected]\fP"

.PP
Performs a Save() operation on an editable business object, with appropriate validation and exception handling\&. 
.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP Type of business object\&.
.RE
.PP
\fBParameters\fP
.RS 4
\fIitem\fP The business object to insert\&.
.br
\fIforceUpdate\fP true to force Save() to be an update\&.
.RE
.PP
\fBReturns\fP
.RS 4
true the Save() succeeds, false if not\&.
.RE
.PP

.PP
\fBType Constraints\fP
.TP
\fIT\fP : \fIclass\fP
.TP
\fIT\fP : \fICore\&.ISavable\fP
.PP
Definition at line 123 of file Controller\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
