.TH "Csla.Test.CommandBase.CommandBaseTest" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.CommandBase.CommandBaseTest \- Summary description for \fBCommandBaseTest\fP  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.Server\&.ObjectFactory\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCommandBaseTest\fP ()"
.br
.ti -1c
.RI "void \fBCommandBase_AssertDefaultValues\fP ()"
.br
.ti -1c
.RI "void \fBCommandBase_CanLoadProperties_WithObjectFactory\fP ()"
.br
.ti -1c
.RI "void \fBCommandBase_CanLoadPropertiesUsingNonGenericPropertyInfo_WithObjectFactory\fP ()"
.br
.ti -1c
.RI "void \fBCommandBase_CanReadProperties_WithObjectFactory\fP ()"
.br
.ti -1c
.RI "void \fBCommandBase_CanReadPropertiesUsingNonGenericPropertyInfo_WithObjectFactory\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "TestContext \fBTestContext\fP\fC [get, set]\fP"
.br
.RI "Gets or sets the test context which provides information about and functionality for the current test run\&. /summary> "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Summary description for \fBCommandBaseTest\fP 


.PP
Definition at line 14 of file CommandBaseTest\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Csla\&.Test\&.CommandBase\&.CommandBaseTest\&.CommandBaseTest ()"

.PP
Definition at line 16 of file CommandBaseTest\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Csla\&.Test\&.CommandBase\&.CommandBaseTest\&.CommandBase_AssertDefaultValues ()"

.PP
Definition at line 63 of file CommandBaseTest\&.cs\&.
.SS "void Csla\&.Test\&.CommandBase\&.CommandBaseTest\&.CommandBase_CanLoadProperties_WithObjectFactory ()"

.PP
Definition at line 72 of file CommandBaseTest\&.cs\&.
.SS "void Csla\&.Test\&.CommandBase\&.CommandBaseTest\&.CommandBase_CanLoadPropertiesUsingNonGenericPropertyInfo_WithObjectFactory ()"

.PP
Definition at line 85 of file CommandBaseTest\&.cs\&.
.SS "void Csla\&.Test\&.CommandBase\&.CommandBaseTest\&.CommandBase_CanReadProperties_WithObjectFactory ()"

.PP
Definition at line 101 of file CommandBaseTest\&.cs\&.
.SS "void Csla\&.Test\&.CommandBase\&.CommandBaseTest\&.CommandBase_CanReadPropertiesUsingNonGenericPropertyInfo_WithObjectFactory ()"

.PP
Definition at line 117 of file CommandBaseTest\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "TestContext Csla\&.Test\&.CommandBase\&.CommandBaseTest\&.TestContext\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the test context which provides information about and functionality for the current test run\&. /summary> 
.PP
Definition at line 26 of file CommandBaseTest\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
