.TH "Csla.Core.FieldManager.IFieldData< T >" 3 "Thu Jul 22 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Core.FieldManager.IFieldData< T > \- Defines the members required by a field data storage object\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.Core\&.ITrackStatus\fP, IMobileObject, and IFieldData\&.
.PP
Inherited by \fBCsla\&.Core\&.FieldManager\&.FieldData< T >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBMarkClean\fP ()"
.br
.RI "Marks the field as unchanged\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBName\fP\fC [get]\fP"
.br
.RI "Gets the name of the field\&. "
.ti -1c
.RI "object \fBValue\fP\fC [get, set]\fP"
.br
.RI "Gets or sets the field value\&. "
.ti -1c
.RI "new T \fBValue\fP\fC [get, set]\fP"
.br
.RI "Gets or sets the field value\&. "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Defines the members required by a field data storage object\&. 


.PP
Definition at line 14 of file IFieldDataT\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void \fBCsla\&.Core\&.FieldManager\&.IFieldData\fP< T >\&.MarkClean ()"

.PP
Marks the field as unchanged\&. 
.PP
Implemented in \fBCsla\&.Core\&.FieldManager\&.FieldData< T >\fP\&.
.SH "Property Documentation"
.PP 
.SS "string \fBCsla\&.Core\&.FieldManager\&.IFieldData\fP< T >\&.Name\fC [get]\fP"

.PP
Gets the name of the field\&. 
.PP
Definition at line 21 of file IFieldData\&.cs\&.
.SS "object \fBCsla\&.Core\&.FieldManager\&.IFieldData\fP< T >\&.Value\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the field value\&. The value of the field\&.
.PP
\fBReturns\fP
.RS 4
The value of the field\&.
.RE
.PP

.PP
Definition at line 27 of file IFieldData\&.cs\&.
.SS "new T \fBCsla\&.Core\&.FieldManager\&.IFieldData\fP< T >\&.Value\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the field value\&. The value of the field\&.
.PP
\fBReturns\fP
.RS 4
The value of the field\&.
.RE
.PP

.PP
Definition at line 21 of file IFieldDataT\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
