.TH "Csla.Server.Hosts.WcfChannel.UpdateRequest" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Server.Hosts.WcfChannel.UpdateRequest \- Request message for updating a business object\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBUpdateRequest\fP (object obj, \fBCsla\&.Server\&.DataPortalContext\fP context)"
.br
.RI "Create new instance of object\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "object \fBObject\fP\fC [get, set]\fP"
.br
.RI "Business object to be updated\&. "
.ti -1c
.RI "\fBCsla\&.Server\&.DataPortalContext\fP \fBContext\fP\fC [get, set]\fP"
.br
.RI "\fBData\fP portal context from client\&. "
.in -1c
.SH "Detailed Description"
.PP 
Request message for updating a business object\&. 


.PP
Definition at line 18 of file UpdateRequest\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Csla\&.Server\&.Hosts\&.WcfChannel\&.UpdateRequest\&.UpdateRequest (object obj, \fBCsla\&.Server\&.DataPortalContext\fP context)"

.PP
Create new instance of object\&. 
.PP
\fBParameters\fP
.RS 4
\fIobj\fP Business object to update\&.
.br
\fIcontext\fP \fBData\fP portal context from client\&.
.RE
.PP

.PP
Definition at line 30 of file UpdateRequest\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "\fBCsla\&.Server\&.DataPortalContext\fP Csla\&.Server\&.Hosts\&.WcfChannel\&.UpdateRequest\&.Context\fC [get]\fP, \fC [set]\fP"

.PP
\fBData\fP portal context from client\&. 
.PP
Definition at line 48 of file UpdateRequest\&.cs\&.
.SS "object Csla\&.Server\&.Hosts\&.WcfChannel\&.UpdateRequest\&.Object\fC [get]\fP, \fC [set]\fP"

.PP
Business object to be updated\&. 
.PP
Definition at line 39 of file UpdateRequest\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
