.TH "Csla.Web.Mvc.CslaModelBinder" 3 "Thu Jul 22 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Web.Mvc.CslaModelBinder \- Model binder for use with CSLA \&.NET editable business objects\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits DefaultModelBinder\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCslaModelBinder\fP (bool CheckRulesOnModelUpdated=true)"
.br
.RI "Creates an instance of the model binder\&. "
.ti -1c
.RI "override object \fBBindModel\fP (ControllerContext controllerContext, ModelBindingContext bindingContext)"
.br
.RI "Binds the model by using the specified controller context and binding context\&. "
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override object \fBCreateModel\fP (ControllerContext controllerContext, ModelBindingContext bindingContext, Type modelType)"
.br
.RI "Creates an instance of the model if the controller implements \fBIModelCreator\fP\&. "
.ti -1c
.RI "override void \fBOnModelUpdated\fP (ControllerContext controllerContext, ModelBindingContext bindingContext)"
.br
.RI "Checks the validation rules for properties after the Model has been updated\&. "
.ti -1c
.RI "override void \fBOnPropertyValidated\fP (ControllerContext controllerContext, ModelBindingContext bindingContext, System\&.ComponentModel\&.PropertyDescriptor propertyDescriptor, object value)"
.br
.RI "Prevents IDataErrorInfo validation from operating against editable objects\&. "
.in -1c
.SH "Detailed Description"
.PP 
Model binder for use with CSLA \&.NET editable business objects\&. 


.PP
Definition at line 236 of file CslaModelBinder\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Csla\&.Web\&.Mvc\&.CslaModelBinder\&.CslaModelBinder (bool CheckRulesOnModelUpdated = \fCtrue\fP)"

.PP
Creates an instance of the model binder\&. 
.PP
\fBParameters\fP
.RS 4
\fICheckRulesOnModelUpdated\fP Value indicating if business rules will be checked after the model is updated\&.
.RE
.PP

.PP
Definition at line 244 of file CslaModelBinder\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override object Csla\&.Web\&.Mvc\&.CslaModelBinder\&.BindModel (ControllerContext controllerContext, ModelBindingContext bindingContext)"

.PP
Binds the model by using the specified controller context and binding context\&. 
.PP
\fBParameters\fP
.RS 4
\fIcontrollerContext\fP \fBController\fP Context
.br
\fIbindingContext\fP Binding Context
.RE
.PP
\fBReturns\fP
.RS 4
Bound object
.RE
.PP

.PP
Definition at line 255 of file CslaModelBinder\&.cs\&.
.SS "override object Csla\&.Web\&.Mvc\&.CslaModelBinder\&.CreateModel (ControllerContext controllerContext, ModelBindingContext bindingContext, Type modelType)\fC [protected]\fP"

.PP
Creates an instance of the model if the controller implements \fBIModelCreator\fP\&. 
.PP
\fBParameters\fP
.RS 4
\fIcontrollerContext\fP \fBController\fP context
.br
\fIbindingContext\fP Binding context
.br
\fImodelType\fP Type of model object
.RE
.PP

.PP
Definition at line 318 of file CslaModelBinder\&.cs\&.
.SS "override void Csla\&.Web\&.Mvc\&.CslaModelBinder\&.OnModelUpdated (ControllerContext controllerContext, ModelBindingContext bindingContext)\fC [protected]\fP"

.PP
Checks the validation rules for properties after the Model has been updated\&. 
.PP
\fBParameters\fP
.RS 4
\fIcontrollerContext\fP \fBController\fP context
.br
\fIbindingContext\fP Binding context
.RE
.PP

.PP
Definition at line 333 of file CslaModelBinder\&.cs\&.
.SS "override void Csla\&.Web\&.Mvc\&.CslaModelBinder\&.OnPropertyValidated (ControllerContext controllerContext, ModelBindingContext bindingContext, System\&.ComponentModel\&.PropertyDescriptor propertyDescriptor, object value)\fC [protected]\fP"

.PP
Prevents IDataErrorInfo validation from operating against editable objects\&. 
.PP
\fBParameters\fP
.RS 4
\fIcontrollerContext\fP \fBController\fP context
.br
\fIbindingContext\fP Binding context
.br
\fIpropertyDescriptor\fP Property descriptor
.br
\fIvalue\fP Value
.RE
.PP

.PP
Definition at line 378 of file CslaModelBinder\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
