.TH "Csla.Windows.ErrorEncounteredEventArgs" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Windows.ErrorEncounteredEventArgs \- Event args indicating an error\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.Windows\&.CslaActionEventArgs\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBErrorEncounteredEventArgs\fP (string commandName, Exception ex)"
.br
.RI "Creates an instance of the object\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "Exception \fBEx\fP\fC [get]\fP"
.br
.RI "Gets a reference to the exception object\&. "
.in -1c
.SH "Detailed Description"
.PP 
Event args indicating an error\&. 


.PP
Definition at line 15 of file ErrorEncounteredEventArgs\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Csla\&.Windows\&.ErrorEncounteredEventArgs\&.ErrorEncounteredEventArgs (string commandName, Exception ex)"

.PP
Creates an instance of the object\&. 
.PP
\fBParameters\fP
.RS 4
\fIcommandName\fP Name of the command\&. 
.br
\fIex\fP Reference to the exception\&. 
.RE
.PP

.PP
Definition at line 26 of file ErrorEncounteredEventArgs\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "Exception Csla\&.Windows\&.ErrorEncounteredEventArgs\&.Ex\fC [get]\fP"

.PP
Gets a reference to the exception object\&. 
.PP
Definition at line 37 of file ErrorEncounteredEventArgs\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
