.TH "Csla.Core.ISupportUndo" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Core.ISupportUndo \- Define the common methods used by the UI to interact with n-level undo\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBCsla\&.Core\&.IEditableBusinessObject\fP, \fBCsla\&.Core\&.IEditableCollection\fP, and \fBCsla\&.IBusinessListBase< C >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBBeginEdit\fP ()"
.br
.RI "Starts a nested edit on the object\&. "
.ti -1c
.RI "void \fBCancelEdit\fP ()"
.br
.RI "Cancels the current edit process, restoring the object's state to its previous values\&. "
.ti -1c
.RI "void \fBApplyEdit\fP ()"
.br
.RI "Commits the current edit process\&. "
.in -1c
.SH "Detailed Description"
.PP 
Define the common methods used by the UI to interact with n-level undo\&. 

This interface is designed to help UI framework developers interact with editable business objects\&. The CSLA \&.NET editable base classes already implement this interface and the required n-level undo behaviors\&. 
.PP
Definition at line 24 of file ISupportUndo\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Csla\&.Core\&.ISupportUndo\&.ApplyEdit ()"

.PP
Commits the current edit process\&. 
.PP
Implemented in \fBCsla\&.Core\&.BusinessBase\fP, \fBCsla\&.BusinessListBase< T, C >\fP, and \fBCsla\&.BusinessBindingListBase< T, C >\fP\&.
.SS "void Csla\&.Core\&.ISupportUndo\&.BeginEdit ()"

.PP
Starts a nested edit on the object\&. 
.PP
Implemented in \fBCsla\&.Core\&.BusinessBase\fP, \fBCsla\&.BusinessListBase< T, C >\fP, and \fBCsla\&.BusinessBindingListBase< T, C >\fP\&.
.SS "void Csla\&.Core\&.ISupportUndo\&.CancelEdit ()"

.PP
Cancels the current edit process, restoring the object's state to its previous values\&. 
.PP
Implemented in \fBCsla\&.Core\&.BusinessBase\fP, \fBCsla\&.BusinessListBase< T, C >\fP, and \fBCsla\&.BusinessBindingListBase< T, C >\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
