.TH "Csla.WcfPortal.UpdateRequest" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.WcfPortal.UpdateRequest
.SH SYNOPSIS
.br
.PP
.PP
Inherits object, System\&.Runtime\&.Serialization\&.IExtensibleDataObject, and System\&.ComponentModel\&.INotifyPropertyChanged\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBRaisePropertyChanged\fP (string propertyName)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "System\&.Runtime\&.Serialization\&.ExtensionDataObject \fBExtensionData\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "byte[] \fBClientContext\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBClientCulture\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBClientUICulture\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "byte[] \fBGlobalContext\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "byte[] \fBObjectData\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "byte[] \fBPrincipal\fP\fC [get, set]\fP"
.br
.in -1c
.SS "Events"

.in +1c
.ti -1c
.RI "System\&.ComponentModel\&.PropertyChangedEventHandler \fBPropertyChanged\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 364 of file Reference\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Csla\&.WcfPortal\&.UpdateRequest\&.RaisePropertyChanged (string propertyName)\fC [protected]\fP"

.PP
Definition at line 477 of file Reference\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "byte [] Csla\&.WcfPortal\&.UpdateRequest\&.ClientContext\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 398 of file Reference\&.cs\&.
.SS "string Csla\&.WcfPortal\&.UpdateRequest\&.ClientCulture\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 411 of file Reference\&.cs\&.
.SS "string Csla\&.WcfPortal\&.UpdateRequest\&.ClientUICulture\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 424 of file Reference\&.cs\&.
.SS "System\&.Runtime\&.Serialization\&.ExtensionDataObject Csla\&.WcfPortal\&.UpdateRequest\&.ExtensionData\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 388 of file Reference\&.cs\&.
.SS "byte [] Csla\&.WcfPortal\&.UpdateRequest\&.GlobalContext\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 437 of file Reference\&.cs\&.
.SS "byte [] Csla\&.WcfPortal\&.UpdateRequest\&.ObjectData\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 450 of file Reference\&.cs\&.
.SS "byte [] Csla\&.WcfPortal\&.UpdateRequest\&.Principal\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 463 of file Reference\&.cs\&.
.SH "Event Documentation"
.PP 
.SS "System\&.ComponentModel\&.PropertyChangedEventHandler Csla\&.WcfPortal\&.UpdateRequest\&.PropertyChanged"

.PP
Definition at line 475 of file Reference\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
