.TH "Csla.Server.NullCriteria" 3 "Thu Jul 22 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Server.NullCriteria \- Null criteria used by the data portal as a placeholder for a create/fetch request that has a single null criteria parameter\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.Core\&.MobileObject\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "static \fBNullCriteria\fP \fBInstance\fP = new \fBNullCriteria\fP()\fC [get]\fP"
.br
.RI "Gets an instance of \fBNullCriteria\fP "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Null criteria used by the data portal as a placeholder for a create/fetch request that has a single null criteria parameter\&. 


.PP
Definition at line 18 of file NullCriteria\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "\fBNullCriteria\fP Csla\&.Server\&.NullCriteria\&.Instance = new \fBNullCriteria\fP()\fC [static]\fP, \fC [get]\fP"

.PP
Gets an instance of \fBNullCriteria\fP 
.PP
Definition at line 25 of file NullCriteria\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
