.TH "Csla.Test.RollBack.RollBackTests" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.RollBack.RollBackTests
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBNoFail\fP ()"
.br
.ti -1c
.RI "void \fBYesFail\fP ()"
.br
.ti -1c
.RI "void \fBYesFailCancel\fP ()"
.br
.ti -1c
.RI "void \fBEditParentEntity\fP ()"
.br
.ti -1c
.RI "void \fBp_PropertyChanged\fP (object sender, System\&.ComponentModel\&.PropertyChangedEventArgs e)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 25 of file RollBackTests\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Csla\&.Test\&.RollBack\&.RollBackTests\&.EditParentEntity ()"

.PP
Definition at line 133 of file RollBackTests\&.cs\&.
.SS "void Csla\&.Test\&.RollBack\&.RollBackTests\&.NoFail ()"

.PP
Definition at line 29 of file RollBackTests\&.cs\&.
.SS "void Csla\&.Test\&.RollBack\&.RollBackTests\&.p_PropertyChanged (object sender, System\&.ComponentModel\&.PropertyChangedEventArgs e)"

.PP
Definition at line 163 of file RollBackTests\&.cs\&.
.SS "void Csla\&.Test\&.RollBack\&.RollBackTests\&.YesFail ()"

.PP
Definition at line 57 of file RollBackTests\&.cs\&.
.SS "void Csla\&.Test\&.RollBack\&.RollBackTests\&.YesFailCancel ()"

.PP
Definition at line 94 of file RollBackTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
