.TH "Csla.Test.PropertyGetSet.EditableGetSetNFIBase< T >" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.PropertyGetSet.EditableGetSetNFIBase< T >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.Test\&.PropertyGetSet\&.EditableGetSetTopNFIBase< T >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEditableGetSetNFIBase\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBPropertyInfo\fP< string > \fBBaseProperty\fP = RegisterProperty<string>(new \fBPropertyInfo\fP<string>('Base', '\fBBase\fP'))"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBBase\fP\fC [get, set]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
\fBType Constraints\fP
.TP
\fIT\fP : \fI\fBEditableGetSetNFIBase\fP<T>\fP
.PP
Definition at line 37 of file EditableGetSetBase\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBCsla\&.Test\&.PropertyGetSet\&.EditableGetSetNFIBase\fP< T >\&.\fBEditableGetSetNFIBase\fP ()"

.PP
Definition at line 40 of file EditableGetSetBase\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBPropertyInfo\fP<string> \fBCsla\&.Test\&.PropertyGetSet\&.EditableGetSetNFIBase\fP< T >\&.BaseProperty = RegisterProperty<string>(new \fBPropertyInfo\fP<string>('Base', '\fBBase\fP'))\fC [static]\fP"

.PP
Definition at line 44 of file EditableGetSetBase\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "string \fBCsla\&.Test\&.PropertyGetSet\&.EditableGetSetNFIBase\fP< T >\&.Base\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 45 of file EditableGetSetBase\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
