.TH "Csla.Test.DataPortal.AsynchDataPortalTest" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.DataPortal.AsynchDataPortalTest
.SH SYNOPSIS
.br
.PP
.PP
Inherits TestBase\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetup\fP ()"
.br
.ti -1c
.RI "void \fBCleanup\fP ()"
.br
.ti -1c
.RI "async Task \fBBeginCreate_overload_without_parameters\fP ()"
.br
.ti -1c
.RI "async Task \fBBeginCreate_overload_with_Criteria_passed_and_Id_set\fP ()"
.br
.ti -1c
.RI "async Task \fBBeginCreate_with_exception\fP ()"
.br
.ti -1c
.RI "async Task \fBCreateAsync_NoCriteria\fP ()"
.br
.ti -1c
.RI "async Task \fBCreateAsync_WithCriteria\fP ()"
.br
.ti -1c
.RI "void \fBCreateAsync_WithException\fP ()"
.br
.ti -1c
.RI "async Task \fBCreateAsync_Parrallel\fP ()"
.br
.ti -1c
.RI "async Task \fBFetchAsync_NoCriteria\fP ()"
.br
.ti -1c
.RI "async Task \fBFetchAsync_WithCriteria\fP ()"
.br
.ti -1c
.RI "void \fBFetchAsync_WithException\fP ()"
.br
.ti -1c
.RI "async Task \fBFetchAsync_Parrallel\fP ()"
.br
.ti -1c
.RI "async Task \fBExecuteCommand_called_without_UserState_results_in_UserState_defaulted_to_Null_server\fP ()"
.br
.ti -1c
.RI "async Task \fBExecuteAsync\fP ()"
.br
.ti -1c
.RI "void \fBExecuteAsyncWithException\fP ()"
.br
.ti -1c
.RI "async Task \fBBeginCreate_Calling_BO_Without_DP_CREATE_Returns_no_Error_info\fP ()"
.br
.RI "Create is an exception , if BO does not have DP_Create() overload with that signature, ends up calling parameterless DP_Create() - this is by design "
.ti -1c
.RI "async Task \fBBeginFetch_sends_cultureinfo_to_dataportal\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 37 of file AsynchDataPortalTest\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "async Task Csla\&.Test\&.DataPortal\&.AsynchDataPortalTest\&.BeginCreate_Calling_BO_Without_DP_CREATE_Returns_no_Error_info ()"

.PP
Create is an exception , if BO does not have DP_Create() overload with that signature, ends up calling parameterless DP_Create() - this is by design 
.PP
Definition at line 310 of file AsynchDataPortalTest\&.cs\&.
.SS "async Task Csla\&.Test\&.DataPortal\&.AsynchDataPortalTest\&.BeginCreate_overload_with_Criteria_passed_and_Id_set ()"

.PP
Definition at line 68 of file AsynchDataPortalTest\&.cs\&.
.SS "async Task Csla\&.Test\&.DataPortal\&.AsynchDataPortalTest\&.BeginCreate_overload_without_parameters ()"

.PP
Definition at line 60 of file AsynchDataPortalTest\&.cs\&.
.SS "async Task Csla\&.Test\&.DataPortal\&.AsynchDataPortalTest\&.BeginCreate_with_exception ()"

.PP
Definition at line 77 of file AsynchDataPortalTest\&.cs\&.
.SS "async Task Csla\&.Test\&.DataPortal\&.AsynchDataPortalTest\&.BeginFetch_sends_cultureinfo_to_dataportal ()"

.PP
Definition at line 317 of file AsynchDataPortalTest\&.cs\&.
.SS "void Csla\&.Test\&.DataPortal\&.AsynchDataPortalTest\&.Cleanup ()"

.PP
Definition at line 50 of file AsynchDataPortalTest\&.cs\&.
.SS "async Task Csla\&.Test\&.DataPortal\&.AsynchDataPortalTest\&.CreateAsync_NoCriteria ()"

.PP
Definition at line 84 of file AsynchDataPortalTest\&.cs\&.
.SS "async Task Csla\&.Test\&.DataPortal\&.AsynchDataPortalTest\&.CreateAsync_Parrallel ()"

.PP
Definition at line 128 of file AsynchDataPortalTest\&.cs\&.
.SS "async Task Csla\&.Test\&.DataPortal\&.AsynchDataPortalTest\&.CreateAsync_WithCriteria ()"

.PP
Definition at line 93 of file AsynchDataPortalTest\&.cs\&.
.SS "void Csla\&.Test\&.DataPortal\&.AsynchDataPortalTest\&.CreateAsync_WithException ()"

.PP
Definition at line 103 of file AsynchDataPortalTest\&.cs\&.
.SS "async Task Csla\&.Test\&.DataPortal\&.AsynchDataPortalTest\&.ExecuteAsync ()"

.PP
Definition at line 270 of file AsynchDataPortalTest\&.cs\&.
.SS "void Csla\&.Test\&.DataPortal\&.AsynchDataPortalTest\&.ExecuteAsyncWithException ()"

.PP
Definition at line 280 of file AsynchDataPortalTest\&.cs\&.
.SS "async Task Csla\&.Test\&.DataPortal\&.AsynchDataPortalTest\&.ExecuteCommand_called_without_UserState_results_in_UserState_defaulted_to_Null_server ()"

.PP
Definition at line 261 of file AsynchDataPortalTest\&.cs\&.
.SS "async Task Csla\&.Test\&.DataPortal\&.AsynchDataPortalTest\&.FetchAsync_NoCriteria ()"

.PP
Definition at line 146 of file AsynchDataPortalTest\&.cs\&.
.SS "async Task Csla\&.Test\&.DataPortal\&.AsynchDataPortalTest\&.FetchAsync_Parrallel ()"

.PP
Definition at line 190 of file AsynchDataPortalTest\&.cs\&.
.SS "async Task Csla\&.Test\&.DataPortal\&.AsynchDataPortalTest\&.FetchAsync_WithCriteria ()"

.PP
Definition at line 155 of file AsynchDataPortalTest\&.cs\&.
.SS "void Csla\&.Test\&.DataPortal\&.AsynchDataPortalTest\&.FetchAsync_WithException ()"

.PP
Definition at line 165 of file AsynchDataPortalTest\&.cs\&.
.SS "void Csla\&.Test\&.DataPortal\&.AsynchDataPortalTest\&.Setup ()"

.PP
Definition at line 43 of file AsynchDataPortalTest\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
