.TH "Csla.Test.DataPortalTest.SingleWithFactoryFactory" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.DataPortalTest.SingleWithFactoryFactory
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.Server\&.ObjectFactory\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "async Task< object > \fBFetch\fP ()"
.br
.ti -1c
.RI "async Task< object > \fBCreate\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 155 of file Single\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "async Task<object> Csla\&.Test\&.DataPortalTest\&.SingleWithFactoryFactory\&.Create ()"

.PP
Definition at line 162 of file Single\&.cs\&.
.SS "async Task<object> Csla\&.Test\&.DataPortalTest\&.SingleWithFactoryFactory\&.Fetch ()"

.PP
Definition at line 157 of file Single\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
