.TH "Csla.Server.Hosts.DataPortalChannel.DataPortalErrorInfo" 3 "Thu Jul 22 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Server.Hosts.DataPortalChannel.DataPortalErrorInfo \- Message containing details about any server-side exception\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.ReadOnlyBase< DataPortalErrorInfo >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDataPortalErrorInfo\fP (Exception ex)"
.br
.RI "Creates an instance of the object\&. "
.ti -1c
.RI "\fBDataPortalErrorInfo\fP ()"
.br
.RI "Creates an empty instance of the type\&. "
.ti -1c
.RI "\fBDataPortalErrorInfo\fP (\fBCsla\&.WcfPortal\&.WcfErrorInfo\fP info)"
.br
.RI "Creates an instance of the type by copying the WcfErrorInfo data\&. "
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static readonly \fBPropertyInfo\fP< string > \fBExceptionTypeNameProperty\fP = RegisterProperty<string>(c => c\&.ExceptionTypeName)"
.br
.RI "Type name of the exception object\&. "
.ti -1c
.RI "static readonly \fBPropertyInfo\fP< string > \fBMessageProperty\fP = RegisterProperty<string>(c => c\&.Message)"
.br
.RI "Message from the exception object\&. "
.ti -1c
.RI "static readonly \fBPropertyInfo\fP< string > \fBStackTraceProperty\fP = RegisterProperty<string>(c => c\&.StackTrace)"
.br
.RI "Stack trace from the exception object\&. "
.ti -1c
.RI "static readonly \fBPropertyInfo\fP< string > \fBSourceProperty\fP = RegisterProperty<string>(c => c\&.Source)"
.br
.RI "Source of the exception object\&. "
.ti -1c
.RI "static readonly \fBPropertyInfo\fP< string > \fBTargetSiteNameProperty\fP = RegisterProperty<string>(c => c\&.TargetSiteName)"
.br
.RI "TargetSiteName of the exception object\&. "
.ti -1c
.RI "static readonly \fBPropertyInfo\fP< \fBDataPortalErrorInfo\fP > \fBInnerErrorProperty\fP = RegisterProperty<\fBDataPortalErrorInfo\fP>(c => c\&.InnerError)"
.br
.RI "HttpErrorInfo object containing information about any inner exception of the original exception\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBExceptionTypeName\fP\fC [get]\fP"
.br
.RI "Type name of the exception object\&. "
.ti -1c
.RI "string \fBMessage\fP\fC [get]\fP"
.br
.RI "Message from the exception object\&. "
.ti -1c
.RI "string \fBStackTrace\fP\fC [get]\fP"
.br
.RI "Stack trace from the exception object\&. "
.ti -1c
.RI "string \fBSource\fP\fC [get]\fP"
.br
.RI "Source of the exception object\&. "
.ti -1c
.RI "string \fBTargetSiteName\fP\fC [get]\fP"
.br
.RI "TargetSiteName of the exception object\&. "
.ti -1c
.RI "\fBDataPortalErrorInfo\fP \fBInnerError\fP\fC [get]\fP"
.br
.RI "HttpErrorInfo object containing information about any inner exception of the original exception\&. "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Message containing details about any server-side exception\&. 


.PP
Definition at line 18 of file DataPortalErrorInfo\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Csla\&.Server\&.Hosts\&.DataPortalChannel\&.DataPortalErrorInfo\&.DataPortalErrorInfo (Exception ex)"

.PP
Creates an instance of the object\&. 
.PP
\fBParameters\fP
.RS 4
\fIex\fP The Exception to encapusulate\&. 
.RE
.PP

.PP
Definition at line 114 of file DataPortalErrorInfo\&.cs\&.
.SS "Csla\&.Server\&.Hosts\&.DataPortalChannel\&.DataPortalErrorInfo\&.DataPortalErrorInfo ()"

.PP
Creates an empty instance of the type\&. 
.PP
Definition at line 129 of file DataPortalErrorInfo\&.cs\&.
.SS "Csla\&.Server\&.Hosts\&.DataPortalChannel\&.DataPortalErrorInfo\&.DataPortalErrorInfo (\fBCsla\&.WcfPortal\&.WcfErrorInfo\fP info)"

.PP
Creates an instance of the type by copying the WcfErrorInfo data\&. 
.PP
\fBParameters\fP
.RS 4
\fIinfo\fP WcfErrorInfo object\&.
.RE
.PP

.PP
Definition at line 138 of file DataPortalErrorInfo\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "readonly \fBPropertyInfo\fP<string> Csla\&.Server\&.Hosts\&.DataPortalChannel\&.DataPortalErrorInfo\&.ExceptionTypeNameProperty = RegisterProperty<string>(c => c\&.ExceptionTypeName)\fC [static]\fP"

.PP
Type name of the exception object\&. 
.PP
Definition at line 23 of file DataPortalErrorInfo\&.cs\&.
.SS "readonly \fBPropertyInfo\fP<\fBDataPortalErrorInfo\fP> Csla\&.Server\&.Hosts\&.DataPortalChannel\&.DataPortalErrorInfo\&.InnerErrorProperty = RegisterProperty<\fBDataPortalErrorInfo\fP>(c => c\&.InnerError)\fC [static]\fP"

.PP
HttpErrorInfo object containing information about any inner exception of the original exception\&. 
.PP
Definition at line 95 of file DataPortalErrorInfo\&.cs\&.
.SS "readonly \fBPropertyInfo\fP<string> Csla\&.Server\&.Hosts\&.DataPortalChannel\&.DataPortalErrorInfo\&.MessageProperty = RegisterProperty<string>(c => c\&.Message)\fC [static]\fP"

.PP
Message from the exception object\&. 
.PP
Definition at line 37 of file DataPortalErrorInfo\&.cs\&.
.SS "readonly \fBPropertyInfo\fP<string> Csla\&.Server\&.Hosts\&.DataPortalChannel\&.DataPortalErrorInfo\&.SourceProperty = RegisterProperty<string>(c => c\&.Source)\fC [static]\fP"

.PP
Source of the exception object\&. 
.PP
Definition at line 65 of file DataPortalErrorInfo\&.cs\&.
.SS "readonly \fBPropertyInfo\fP<string> Csla\&.Server\&.Hosts\&.DataPortalChannel\&.DataPortalErrorInfo\&.StackTraceProperty = RegisterProperty<string>(c => c\&.StackTrace)\fC [static]\fP"

.PP
Stack trace from the exception object\&. 
.PP
Definition at line 51 of file DataPortalErrorInfo\&.cs\&.
.SS "readonly \fBPropertyInfo\fP<string> Csla\&.Server\&.Hosts\&.DataPortalChannel\&.DataPortalErrorInfo\&.TargetSiteNameProperty = RegisterProperty<string>(c => c\&.TargetSiteName)\fC [static]\fP"

.PP
TargetSiteName of the exception object\&. 
.PP
Definition at line 79 of file DataPortalErrorInfo\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "string Csla\&.Server\&.Hosts\&.DataPortalChannel\&.DataPortalErrorInfo\&.ExceptionTypeName\fC [get]\fP"

.PP
Type name of the exception object\&. 
.PP
Definition at line 28 of file DataPortalErrorInfo\&.cs\&.
.SS "\fBDataPortalErrorInfo\fP Csla\&.Server\&.Hosts\&.DataPortalChannel\&.DataPortalErrorInfo\&.InnerError\fC [get]\fP"

.PP
HttpErrorInfo object containing information about any inner exception of the original exception\&. 
.PP
Definition at line 102 of file DataPortalErrorInfo\&.cs\&.
.SS "string Csla\&.Server\&.Hosts\&.DataPortalChannel\&.DataPortalErrorInfo\&.Message\fC [get]\fP"

.PP
Message from the exception object\&. 
.PP
Definition at line 42 of file DataPortalErrorInfo\&.cs\&.
.SS "string Csla\&.Server\&.Hosts\&.DataPortalChannel\&.DataPortalErrorInfo\&.Source\fC [get]\fP"

.PP
Source of the exception object\&. 
.PP
Definition at line 70 of file DataPortalErrorInfo\&.cs\&.
.SS "string Csla\&.Server\&.Hosts\&.DataPortalChannel\&.DataPortalErrorInfo\&.StackTrace\fC [get]\fP"

.PP
Stack trace from the exception object\&. 
.PP
Definition at line 56 of file DataPortalErrorInfo\&.cs\&.
.SS "string Csla\&.Server\&.Hosts\&.DataPortalChannel\&.DataPortalErrorInfo\&.TargetSiteName\fC [get]\fP"

.PP
TargetSiteName of the exception object\&. 
.PP
Definition at line 84 of file DataPortalErrorInfo\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
