.TH "Csla.Server.Hosts.WcfPortal" 3 "Thu Jul 22 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Server.Hosts.WcfPortal \- Exposes server-side \fBDataPortal\fP functionality through WCF\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.Server\&.Hosts\&.IWcfPortal\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "async Task< \fBWcfResponse\fP > \fBCreate\fP (\fBCreateRequest\fP request)"
.br
.RI "Create a new business object\&. "
.ti -1c
.RI "async Task< \fBWcfResponse\fP > \fBFetch\fP (\fBFetchRequest\fP request)"
.br
.RI "Get an existing business object\&. "
.ti -1c
.RI "async Task< \fBWcfResponse\fP > \fBUpdate\fP (\fBUpdateRequest\fP request)"
.br
.RI "Update a business object\&. "
.ti -1c
.RI "async Task< \fBWcfResponse\fP > \fBDelete\fP (\fBDeleteRequest\fP request)"
.br
.RI "Delete a business object\&. "
.in -1c
.SH "Detailed Description"
.PP 
Exposes server-side \fBDataPortal\fP functionality through WCF\&. 


.PP
Definition at line 23 of file WcfPortal\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "async Task<\fBWcfResponse\fP> Csla\&.Server\&.Hosts\&.WcfPortal\&.Create (\fBCreateRequest\fP request)"

.PP
Create a new business object\&. 
.PP
\fBParameters\fP
.RS 4
\fIrequest\fP The request parameter object\&.
.RE
.PP

.PP
Implements \fBCsla\&.Server\&.Hosts\&.IWcfPortal\fP\&.
.PP
Definition at line 30 of file WcfPortal\&.cs\&.
.SS "async Task<\fBWcfResponse\fP> Csla\&.Server\&.Hosts\&.WcfPortal\&.Delete (\fBDeleteRequest\fP request)"

.PP
Delete a business object\&. 
.PP
\fBParameters\fP
.RS 4
\fIrequest\fP The request parameter object\&.
.RE
.PP

.PP
Implements \fBCsla\&.Server\&.Hosts\&.IWcfPortal\fP\&.
.PP
Definition at line 90 of file WcfPortal\&.cs\&.
.SS "async Task<\fBWcfResponse\fP> Csla\&.Server\&.Hosts\&.WcfPortal\&.Fetch (\fBFetchRequest\fP request)"

.PP
Get an existing business object\&. 
.PP
\fBParameters\fP
.RS 4
\fIrequest\fP The request parameter object\&.
.RE
.PP

.PP
Implements \fBCsla\&.Server\&.Hosts\&.IWcfPortal\fP\&.
.PP
Definition at line 50 of file WcfPortal\&.cs\&.
.SS "async Task<\fBWcfResponse\fP> Csla\&.Server\&.Hosts\&.WcfPortal\&.Update (\fBUpdateRequest\fP request)"

.PP
Update a business object\&. 
.PP
\fBParameters\fP
.RS 4
\fIrequest\fP The request parameter object\&.
.RE
.PP

.PP
Implements \fBCsla\&.Server\&.Hosts\&.IWcfPortal\fP\&.
.PP
Definition at line 70 of file WcfPortal\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
