.TH "Csla.NotUndoableAttribute" 3 "Thu Jul 22 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.NotUndoableAttribute \- Marks a field to indicate that the value should not be copied as part of the undo process\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Attribute\&.
.SH "Detailed Description"
.PP 
Marks a field to indicate that the value should not be copied as part of the undo process\&. 

Marking a variable with this attribute will cause the n-level undo process to ignore that variable's value\&. The value will not be included in a snapshot when BeginEdit is called, nor will it be restored when CancelEdit is called\&. 
.PP
Definition at line 23 of file NotUndoableAttribute\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
