.TH "Csla.Analyzers.Tests.Extensions.IMethodSymbolExtensionsTests" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Analyzers.Tests.Extensions.IMethodSymbolExtensionsTests
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBIsPropertyInfoManagementMethodWhenSymbolIsNull\fP ()"
.br
.ti -1c
.RI "async Task \fBIsPropertyInfoManagementMethodForMethodThatIsNotAPropertyInfoManagementMethod\fP ()"
.br
.ti -1c
.RI "async Task \fBIsPropertyInfoManagementMethodForSetProperty\fP ()"
.br
.ti -1c
.RI "async Task \fBIsPropertyInfoManagementMethodForSetPropertyConvert\fP ()"
.br
.ti -1c
.RI "async Task \fBIsPropertyInfoManagementMethodForGetProperty\fP ()"
.br
.ti -1c
.RI "async Task \fBIsPropertyInfoManagementMethodForGetPropertyConvert\fP ()"
.br
.ti -1c
.RI "async Task \fBIsPropertyInfoManagementMethodForLazyGetProperty\fP ()"
.br
.ti -1c
.RI "async Task \fBIsPropertyInfoManagementMethodForLazyGetPropertyAsync\fP ()"
.br
.ti -1c
.RI "async Task \fBIsPropertyInfoManagementMethodForLazyReadProperty\fP ()"
.br
.ti -1c
.RI "async Task \fBIsPropertyInfoManagementMethodForLazyReadPropertyAsync\fP ()"
.br
.ti -1c
.RI "async Task \fBIsPropertyInfoManagementMethodForLoadPropertyAsync\fP ()"
.br
.ti -1c
.RI "async Task \fBIsPropertyInfoManagementMethodForLoadPropertyMarkDirty\fP ()"
.br
.ti -1c
.RI "async Task \fBIsPropertyInfoManagementMethodForReadProperty\fP ()"
.br
.ti -1c
.RI "async Task \fBIsPropertyInfoManagementMethodForReadPropertyConvert\fP ()"
.br
.ti -1c
.RI "async Task \fBIsPropertyInfoManagementMethodForLoadProperty\fP ()"
.br
.ti -1c
.RI "async Task \fBIsPropertyInfoManagementMethodForLoadPropertyConvert\fP ()"
.br
.ti -1c
.RI "void \fBIsDataPortalOperationWhenSymbolIsNull\fP ()"
.br
.ti -1c
.RI "void \fBIsRootDataPortalOperationWhenSymbolIsNull\fP ()"
.br
.ti -1c
.RI "void \fBIsChildDataPortalOperationWhenSymbolIsNull\fP ()"
.br
.ti -1c
.RI "async Task \fBIsDataPortalOperationForMethodThatIsNotADataPortalOperation\fP ()"
.br
.ti -1c
.RI "async Task \fBIsRootDataPortalOperationForMethodThatIsNotADataPortalOperation\fP ()"
.br
.ti -1c
.RI "async Task \fBIsChildDataPortalOperationForMethodThatIsNotADataPortalOperation\fP ()"
.br
.ti -1c
.RI "async Task \fBIsDataPortalOperationForDataPortalCreate\fP ()"
.br
.ti -1c
.RI "async Task \fBIsRootDataPortalOperationForDataPortalCreate\fP ()"
.br
.ti -1c
.RI "async Task \fBIsChildDataPortalOperationForDataPortalCreate\fP ()"
.br
.ti -1c
.RI "async Task \fBIsDataPortalOperationForDataPortalCreateWithAttribute\fP ()"
.br
.ti -1c
.RI "async Task \fBIsRootDataPortalOperationForDataPortalCreateWithAttribute\fP ()"
.br
.ti -1c
.RI "async Task \fBIsChildDataPortalOperationForDataPortalCreateWithAttribute\fP ()"
.br
.ti -1c
.RI "async Task \fBIsDataPortalOperationForDataPortalFetch\fP ()"
.br
.ti -1c
.RI "async Task \fBIsRootDataPortalOperationForDataPortalFetch\fP ()"
.br
.ti -1c
.RI "async Task \fBIsChildDataPortalOperationForDataPortalFetch\fP ()"
.br
.ti -1c
.RI "async Task \fBIsDataPortalOperationForDataPortalFetchWithAttribute\fP ()"
.br
.ti -1c
.RI "async Task \fBIsRootDataPortalOperationForDataPortalFetchWithAttribute\fP ()"
.br
.ti -1c
.RI "async Task \fBIsChildDataPortalOperationForDataPortalFetchWithAttribute\fP ()"
.br
.ti -1c
.RI "async Task \fBIsDataPortalOperationForDataPortalInsert\fP ()"
.br
.ti -1c
.RI "async Task \fBIsRootDataPortalOperationForDataPortalInsert\fP ()"
.br
.ti -1c
.RI "async Task \fBIsChildDataPortalOperationForDataPortalInsert\fP ()"
.br
.ti -1c
.RI "async Task \fBIsDataPortalOperationForDataPortalInsertWithAttribute\fP ()"
.br
.ti -1c
.RI "async Task \fBIsRootDataPortalOperationForDataPortalInsertWithAttribute\fP ()"
.br
.ti -1c
.RI "async Task \fBIsChildDataPortalOperationForDataPortalInsertWithAttribute\fP ()"
.br
.ti -1c
.RI "async Task \fBIsDataPortalOperationForDataPortalUpdate\fP ()"
.br
.ti -1c
.RI "async Task \fBIsRootDataPortalOperationForDataPortalUpdate\fP ()"
.br
.ti -1c
.RI "async Task \fBIsChildDataPortalOperationForDataPortalUpdate\fP ()"
.br
.ti -1c
.RI "async Task \fBIsDataPortalOperationForDataPortalUpdateWithAttribute\fP ()"
.br
.ti -1c
.RI "async Task \fBIsRootDataPortalOperationForDataPortalUpdateWithAttribute\fP ()"
.br
.ti -1c
.RI "async Task \fBIsChildDataPortalOperationForDataPortalUpdateWithAttribute\fP ()"
.br
.ti -1c
.RI "async Task \fBIsDataPortalOperationForDataPortalDelete\fP ()"
.br
.ti -1c
.RI "async Task \fBIsRootDataPortalOperationForDataPortalDelete\fP ()"
.br
.ti -1c
.RI "async Task \fBIsChildDataPortalOperationForDataPortalDelete\fP ()"
.br
.ti -1c
.RI "async Task \fBIsDataPortalOperationForDataPortalDeleteWithAttribute\fP ()"
.br
.ti -1c
.RI "async Task \fBIsRootDataPortalOperationForDataPortalDeleteWithAttribute\fP ()"
.br
.ti -1c
.RI "async Task \fBIsChildDataPortalOperationForDataPortalDeleteWithAttribute\fP ()"
.br
.ti -1c
.RI "async Task \fBIsDataPortalOperationForDataPortalDeleteSelf\fP ()"
.br
.ti -1c
.RI "async Task \fBIsRootDataPortalOperationForDataPortalDeleteSelf\fP ()"
.br
.ti -1c
.RI "async Task \fBIsChildDataPortalOperationForDataPortalDeleteSelf\fP ()"
.br
.ti -1c
.RI "async Task \fBIsDataPortalOperationForDataPortalDeleteSelfWithAttribute\fP ()"
.br
.ti -1c
.RI "async Task \fBIsRootDataPortalOperationForDataPortalDeleteSelfWithAttribute\fP ()"
.br
.ti -1c
.RI "async Task \fBIsChildDataPortalOperationForDataPortalDeleteSelfWithAttribute\fP ()"
.br
.ti -1c
.RI "async Task \fBIsDataPortalOperationForDataPortalExecute\fP ()"
.br
.ti -1c
.RI "async Task \fBIsRootDataPortalOperationForDataPortalExecute\fP ()"
.br
.ti -1c
.RI "async Task \fBIsChildDataPortalOperationForDataPortalExecute\fP ()"
.br
.ti -1c
.RI "async Task \fBIsDataPortalOperationForDataPortalExecuteWithAttribute\fP ()"
.br
.ti -1c
.RI "async Task \fBIsRootDataPortalOperationForDataPortalExecuteWithAttribute\fP ()"
.br
.ti -1c
.RI "async Task \fBIsChildDataPortalOperationForDataPortalExecuteWithAttribute\fP ()"
.br
.ti -1c
.RI "async Task \fBIsDataPortalOperationForChildCreate\fP ()"
.br
.ti -1c
.RI "async Task \fBIsRootDataPortalOperationForChildCreate\fP ()"
.br
.ti -1c
.RI "async Task \fBIsChildDataPortalOperationForChildCreate\fP ()"
.br
.ti -1c
.RI "async Task \fBIsDataPortalOperationForChildCreateWithAttribute\fP ()"
.br
.ti -1c
.RI "async Task \fBIsRootDataPortalOperationForChildCreateWithAttribute\fP ()"
.br
.ti -1c
.RI "async Task \fBIsChildDataPortalOperationForChildCreateWithAttribute\fP ()"
.br
.ti -1c
.RI "async Task \fBIsDataPortalOperationForChildFetch\fP ()"
.br
.ti -1c
.RI "async Task \fBIsRootDataPortalOperationForChildFetch\fP ()"
.br
.ti -1c
.RI "async Task \fBIsChildDataPortalOperationForChildFetch\fP ()"
.br
.ti -1c
.RI "async Task \fBIsDataPortalOperationForChildFetchWithAttribute\fP ()"
.br
.ti -1c
.RI "async Task \fBIsRootDataPortalOperationForChildFetchWithAttribute\fP ()"
.br
.ti -1c
.RI "async Task \fBIsChildDataPortalOperationForChildFetchWithAttribute\fP ()"
.br
.ti -1c
.RI "async Task \fBIsDataPortalOperationForChildInsert\fP ()"
.br
.ti -1c
.RI "async Task \fBIsRootDataPortalOperationForChildInsert\fP ()"
.br
.ti -1c
.RI "async Task \fBIsChildDataPortalOperationForChildInsert\fP ()"
.br
.ti -1c
.RI "async Task \fBIsDataPortalOperationForChildInsertWithAttribute\fP ()"
.br
.ti -1c
.RI "async Task \fBIsRootDataPortalOperationForChildInsertWithAttribute\fP ()"
.br
.ti -1c
.RI "async Task \fBIsChildDataPortalOperationForChildInsertWithAttribute\fP ()"
.br
.ti -1c
.RI "async Task \fBIsDataPortalOperationForChildUpdate\fP ()"
.br
.ti -1c
.RI "async Task \fBIsRootDataPortalOperationForChildUpdate\fP ()"
.br
.ti -1c
.RI "async Task \fBIsChildDataPortalOperationForChildUpdate\fP ()"
.br
.ti -1c
.RI "async Task \fBIsDataPortalOperationForChildUpdateWithAttribute\fP ()"
.br
.ti -1c
.RI "async Task \fBIsRootDataPortalOperationForChildUpdateWithAttribute\fP ()"
.br
.ti -1c
.RI "async Task \fBIsChildDataPortalOperationForChildUpdateWithAttribute\fP ()"
.br
.ti -1c
.RI "async Task \fBIsDataPortalOperationForChildDeleteSelf\fP ()"
.br
.ti -1c
.RI "async Task \fBIsRootDataPortalOperationForChildDeleteSelf\fP ()"
.br
.ti -1c
.RI "async Task \fBIsChildDataPortalOperationForChildDeleteSelf\fP ()"
.br
.ti -1c
.RI "async Task \fBIsDataPortalOperationForChildExecute\fP ()"
.br
.ti -1c
.RI "async Task \fBIsRootDataPortalOperationForChildExecute\fP ()"
.br
.ti -1c
.RI "async Task \fBIsChildDataPortalOperationForChildExecute\fP ()"
.br
.ti -1c
.RI "async Task \fBIsDataPortalOperationForChildExecuteWithAttribute\fP ()"
.br
.ti -1c
.RI "async Task \fBIsRootDataPortalOperationForChildExecuteWithAttribute\fP ()"
.br
.ti -1c
.RI "async Task \fBIsChildDataPortalOperationForChildExecuteWithAttribute\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 13 of file IMethodSymbolExtensionsTests\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "async Task Csla\&.Analyzers\&.Tests\&.Extensions\&.IMethodSymbolExtensionsTests\&.IsChildDataPortalOperationForChildCreate ()"

.SS "async Task Csla\&.Analyzers\&.Tests\&.Extensions\&.IMethodSymbolExtensionsTests\&.IsChildDataPortalOperationForChildCreateWithAttribute ()"

.SS "async Task Csla\&.Analyzers\&.Tests\&.Extensions\&.IMethodSymbolExtensionsTests\&.IsChildDataPortalOperationForChildDeleteSelf ()"

.SS "async Task Csla\&.Analyzers\&.Tests\&.Extensions\&.IMethodSymbolExtensionsTests\&.IsChildDataPortalOperationForChildExecute ()"

.SS "async Task Csla\&.Analyzers\&.Tests\&.Extensions\&.IMethodSymbolExtensionsTests\&.IsChildDataPortalOperationForChildExecuteWithAttribute ()"

.SS "async Task Csla\&.Analyzers\&.Tests\&.Extensions\&.IMethodSymbolExtensionsTests\&.IsChildDataPortalOperationForChildFetch ()"

.SS "async Task Csla\&.Analyzers\&.Tests\&.Extensions\&.IMethodSymbolExtensionsTests\&.IsChildDataPortalOperationForChildFetchWithAttribute ()"

.SS "async Task Csla\&.Analyzers\&.Tests\&.Extensions\&.IMethodSymbolExtensionsTests\&.IsChildDataPortalOperationForChildInsert ()"

.SS "async Task Csla\&.Analyzers\&.Tests\&.Extensions\&.IMethodSymbolExtensionsTests\&.IsChildDataPortalOperationForChildInsertWithAttribute ()"

.SS "async Task Csla\&.Analyzers\&.Tests\&.Extensions\&.IMethodSymbolExtensionsTests\&.IsChildDataPortalOperationForChildUpdate ()"

.SS "async Task Csla\&.Analyzers\&.Tests\&.Extensions\&.IMethodSymbolExtensionsTests\&.IsChildDataPortalOperationForChildUpdateWithAttribute ()"

.SS "async Task Csla\&.Analyzers\&.Tests\&.Extensions\&.IMethodSymbolExtensionsTests\&.IsChildDataPortalOperationForDataPortalCreate ()"

.SS "async Task Csla\&.Analyzers\&.Tests\&.Extensions\&.IMethodSymbolExtensionsTests\&.IsChildDataPortalOperationForDataPortalCreateWithAttribute ()"

.SS "async Task Csla\&.Analyzers\&.Tests\&.Extensions\&.IMethodSymbolExtensionsTests\&.IsChildDataPortalOperationForDataPortalDelete ()"

.SS "async Task Csla\&.Analyzers\&.Tests\&.Extensions\&.IMethodSymbolExtensionsTests\&.IsChildDataPortalOperationForDataPortalDeleteSelf ()"

.SS "async Task Csla\&.Analyzers\&.Tests\&.Extensions\&.IMethodSymbolExtensionsTests\&.IsChildDataPortalOperationForDataPortalDeleteSelfWithAttribute ()"

.SS "async Task Csla\&.Analyzers\&.Tests\&.Extensions\&.IMethodSymbolExtensionsTests\&.IsChildDataPortalOperationForDataPortalDeleteWithAttribute ()"

.SS "async Task Csla\&.Analyzers\&.Tests\&.Extensions\&.IMethodSymbolExtensionsTests\&.IsChildDataPortalOperationForDataPortalExecute ()"

.SS "async Task Csla\&.Analyzers\&.Tests\&.Extensions\&.IMethodSymbolExtensionsTests\&.IsChildDataPortalOperationForDataPortalExecuteWithAttribute ()"

.SS "async Task Csla\&.Analyzers\&.Tests\&.Extensions\&.IMethodSymbolExtensionsTests\&.IsChildDataPortalOperationForDataPortalFetch ()"

.SS "async Task Csla\&.Analyzers\&.Tests\&.Extensions\&.IMethodSymbolExtensionsTests\&.IsChildDataPortalOperationForDataPortalFetchWithAttribute ()"

.SS "async Task Csla\&.Analyzers\&.Tests\&.Extensions\&.IMethodSymbolExtensionsTests\&.IsChildDataPortalOperationForDataPortalInsert ()"

.SS "async Task Csla\&.Analyzers\&.Tests\&.Extensions\&.IMethodSymbolExtensionsTests\&.IsChildDataPortalOperationForDataPortalInsertWithAttribute ()"

.SS "async Task Csla\&.Analyzers\&.Tests\&.Extensions\&.IMethodSymbolExtensionsTests\&.IsChildDataPortalOperationForDataPortalUpdate ()"

.SS "async Task Csla\&.Analyzers\&.Tests\&.Extensions\&.IMethodSymbolExtensionsTests\&.IsChildDataPortalOperationForDataPortalUpdateWithAttribute ()"

.SS "async Task Csla\&.Analyzers\&.Tests\&.Extensions\&.IMethodSymbolExtensionsTests\&.IsChildDataPortalOperationForMethodThatIsNotADataPortalOperation ()"

.SS "void Csla\&.Analyzers\&.Tests\&.Extensions\&.IMethodSymbolExtensionsTests\&.IsChildDataPortalOperationWhenSymbolIsNull ()"

.SS "async Task Csla\&.Analyzers\&.Tests\&.Extensions\&.IMethodSymbolExtensionsTests\&.IsDataPortalOperationForChildCreate ()"

.SS "async Task Csla\&.Analyzers\&.Tests\&.Extensions\&.IMethodSymbolExtensionsTests\&.IsDataPortalOperationForChildCreateWithAttribute ()"

.SS "async Task Csla\&.Analyzers\&.Tests\&.Extensions\&.IMethodSymbolExtensionsTests\&.IsDataPortalOperationForChildDeleteSelf ()"

.SS "async Task Csla\&.Analyzers\&.Tests\&.Extensions\&.IMethodSymbolExtensionsTests\&.IsDataPortalOperationForChildExecute ()"

.SS "async Task Csla\&.Analyzers\&.Tests\&.Extensions\&.IMethodSymbolExtensionsTests\&.IsDataPortalOperationForChildExecuteWithAttribute ()"

.SS "async Task Csla\&.Analyzers\&.Tests\&.Extensions\&.IMethodSymbolExtensionsTests\&.IsDataPortalOperationForChildFetch ()"

.SS "async Task Csla\&.Analyzers\&.Tests\&.Extensions\&.IMethodSymbolExtensionsTests\&.IsDataPortalOperationForChildFetchWithAttribute ()"

.SS "async Task Csla\&.Analyzers\&.Tests\&.Extensions\&.IMethodSymbolExtensionsTests\&.IsDataPortalOperationForChildInsert ()"

.SS "async Task Csla\&.Analyzers\&.Tests\&.Extensions\&.IMethodSymbolExtensionsTests\&.IsDataPortalOperationForChildInsertWithAttribute ()"

.SS "async Task Csla\&.Analyzers\&.Tests\&.Extensions\&.IMethodSymbolExtensionsTests\&.IsDataPortalOperationForChildUpdate ()"

.SS "async Task Csla\&.Analyzers\&.Tests\&.Extensions\&.IMethodSymbolExtensionsTests\&.IsDataPortalOperationForChildUpdateWithAttribute ()"

.SS "async Task Csla\&.Analyzers\&.Tests\&.Extensions\&.IMethodSymbolExtensionsTests\&.IsDataPortalOperationForDataPortalCreate ()"

.SS "async Task Csla\&.Analyzers\&.Tests\&.Extensions\&.IMethodSymbolExtensionsTests\&.IsDataPortalOperationForDataPortalCreateWithAttribute ()"

.SS "async Task Csla\&.Analyzers\&.Tests\&.Extensions\&.IMethodSymbolExtensionsTests\&.IsDataPortalOperationForDataPortalDelete ()"

.SS "async Task Csla\&.Analyzers\&.Tests\&.Extensions\&.IMethodSymbolExtensionsTests\&.IsDataPortalOperationForDataPortalDeleteSelf ()"

.SS "async Task Csla\&.Analyzers\&.Tests\&.Extensions\&.IMethodSymbolExtensionsTests\&.IsDataPortalOperationForDataPortalDeleteSelfWithAttribute ()"

.SS "async Task Csla\&.Analyzers\&.Tests\&.Extensions\&.IMethodSymbolExtensionsTests\&.IsDataPortalOperationForDataPortalDeleteWithAttribute ()"

.SS "async Task Csla\&.Analyzers\&.Tests\&.Extensions\&.IMethodSymbolExtensionsTests\&.IsDataPortalOperationForDataPortalExecute ()"

.SS "async Task Csla\&.Analyzers\&.Tests\&.Extensions\&.IMethodSymbolExtensionsTests\&.IsDataPortalOperationForDataPortalExecuteWithAttribute ()"

.SS "async Task Csla\&.Analyzers\&.Tests\&.Extensions\&.IMethodSymbolExtensionsTests\&.IsDataPortalOperationForDataPortalFetch ()"

.SS "async Task Csla\&.Analyzers\&.Tests\&.Extensions\&.IMethodSymbolExtensionsTests\&.IsDataPortalOperationForDataPortalFetchWithAttribute ()"

.SS "async Task Csla\&.Analyzers\&.Tests\&.Extensions\&.IMethodSymbolExtensionsTests\&.IsDataPortalOperationForDataPortalInsert ()"

.SS "async Task Csla\&.Analyzers\&.Tests\&.Extensions\&.IMethodSymbolExtensionsTests\&.IsDataPortalOperationForDataPortalInsertWithAttribute ()"

.SS "async Task Csla\&.Analyzers\&.Tests\&.Extensions\&.IMethodSymbolExtensionsTests\&.IsDataPortalOperationForDataPortalUpdate ()"

.SS "async Task Csla\&.Analyzers\&.Tests\&.Extensions\&.IMethodSymbolExtensionsTests\&.IsDataPortalOperationForDataPortalUpdateWithAttribute ()"

.SS "async Task Csla\&.Analyzers\&.Tests\&.Extensions\&.IMethodSymbolExtensionsTests\&.IsDataPortalOperationForMethodThatIsNotADataPortalOperation ()"

.SS "void Csla\&.Analyzers\&.Tests\&.Extensions\&.IMethodSymbolExtensionsTests\&.IsDataPortalOperationWhenSymbolIsNull ()"

.SS "async Task Csla\&.Analyzers\&.Tests\&.Extensions\&.IMethodSymbolExtensionsTests\&.IsPropertyInfoManagementMethodForGetProperty ()"

.PP
Definition at line 125 of file IMethodSymbolExtensionsTests\&.cs\&.
.SS "async Task Csla\&.Analyzers\&.Tests\&.Extensions\&.IMethodSymbolExtensionsTests\&.IsPropertyInfoManagementMethodForGetPropertyConvert ()"

.PP
Definition at line 135 of file IMethodSymbolExtensionsTests\&.cs\&.
.SS "async Task Csla\&.Analyzers\&.Tests\&.Extensions\&.IMethodSymbolExtensionsTests\&.IsPropertyInfoManagementMethodForLazyGetProperty ()"

.PP
Definition at line 145 of file IMethodSymbolExtensionsTests\&.cs\&.
.SS "async Task Csla\&.Analyzers\&.Tests\&.Extensions\&.IMethodSymbolExtensionsTests\&.IsPropertyInfoManagementMethodForLazyGetPropertyAsync ()"

.PP
Definition at line 155 of file IMethodSymbolExtensionsTests\&.cs\&.
.SS "async Task Csla\&.Analyzers\&.Tests\&.Extensions\&.IMethodSymbolExtensionsTests\&.IsPropertyInfoManagementMethodForLazyReadProperty ()"

.PP
Definition at line 165 of file IMethodSymbolExtensionsTests\&.cs\&.
.SS "async Task Csla\&.Analyzers\&.Tests\&.Extensions\&.IMethodSymbolExtensionsTests\&.IsPropertyInfoManagementMethodForLazyReadPropertyAsync ()"

.PP
Definition at line 175 of file IMethodSymbolExtensionsTests\&.cs\&.
.SS "async Task Csla\&.Analyzers\&.Tests\&.Extensions\&.IMethodSymbolExtensionsTests\&.IsPropertyInfoManagementMethodForLoadProperty ()"

.PP
Definition at line 231 of file IMethodSymbolExtensionsTests\&.cs\&.
.SS "async Task Csla\&.Analyzers\&.Tests\&.Extensions\&.IMethodSymbolExtensionsTests\&.IsPropertyInfoManagementMethodForLoadPropertyAsync ()"

.PP
Definition at line 185 of file IMethodSymbolExtensionsTests\&.cs\&.
.SS "async Task Csla\&.Analyzers\&.Tests\&.Extensions\&.IMethodSymbolExtensionsTests\&.IsPropertyInfoManagementMethodForLoadPropertyConvert ()"

.PP
Definition at line 244 of file IMethodSymbolExtensionsTests\&.cs\&.
.SS "async Task Csla\&.Analyzers\&.Tests\&.Extensions\&.IMethodSymbolExtensionsTests\&.IsPropertyInfoManagementMethodForLoadPropertyMarkDirty ()"

.PP
Definition at line 195 of file IMethodSymbolExtensionsTests\&.cs\&.
.SS "async Task Csla\&.Analyzers\&.Tests\&.Extensions\&.IMethodSymbolExtensionsTests\&.IsPropertyInfoManagementMethodForMethodThatIsNotAPropertyInfoManagementMethod ()"

.PP
Definition at line 104 of file IMethodSymbolExtensionsTests\&.cs\&.
.SS "async Task Csla\&.Analyzers\&.Tests\&.Extensions\&.IMethodSymbolExtensionsTests\&.IsPropertyInfoManagementMethodForReadProperty ()"

.PP
Definition at line 205 of file IMethodSymbolExtensionsTests\&.cs\&.
.SS "async Task Csla\&.Analyzers\&.Tests\&.Extensions\&.IMethodSymbolExtensionsTests\&.IsPropertyInfoManagementMethodForReadPropertyConvert ()"

.PP
Definition at line 218 of file IMethodSymbolExtensionsTests\&.cs\&.
.SS "async Task Csla\&.Analyzers\&.Tests\&.Extensions\&.IMethodSymbolExtensionsTests\&.IsPropertyInfoManagementMethodForSetProperty ()"

.PP
Definition at line 111 of file IMethodSymbolExtensionsTests\&.cs\&.
.SS "async Task Csla\&.Analyzers\&.Tests\&.Extensions\&.IMethodSymbolExtensionsTests\&.IsPropertyInfoManagementMethodForSetPropertyConvert ()"

.PP
Definition at line 118 of file IMethodSymbolExtensionsTests\&.cs\&.
.SS "void Csla\&.Analyzers\&.Tests\&.Extensions\&.IMethodSymbolExtensionsTests\&.IsPropertyInfoManagementMethodWhenSymbolIsNull ()"

.PP
Definition at line 98 of file IMethodSymbolExtensionsTests\&.cs\&.
.SS "async Task Csla\&.Analyzers\&.Tests\&.Extensions\&.IMethodSymbolExtensionsTests\&.IsRootDataPortalOperationForChildCreate ()"

.SS "async Task Csla\&.Analyzers\&.Tests\&.Extensions\&.IMethodSymbolExtensionsTests\&.IsRootDataPortalOperationForChildCreateWithAttribute ()"

.SS "async Task Csla\&.Analyzers\&.Tests\&.Extensions\&.IMethodSymbolExtensionsTests\&.IsRootDataPortalOperationForChildDeleteSelf ()"

.SS "async Task Csla\&.Analyzers\&.Tests\&.Extensions\&.IMethodSymbolExtensionsTests\&.IsRootDataPortalOperationForChildExecute ()"

.SS "async Task Csla\&.Analyzers\&.Tests\&.Extensions\&.IMethodSymbolExtensionsTests\&.IsRootDataPortalOperationForChildExecuteWithAttribute ()"

.SS "async Task Csla\&.Analyzers\&.Tests\&.Extensions\&.IMethodSymbolExtensionsTests\&.IsRootDataPortalOperationForChildFetch ()"

.SS "async Task Csla\&.Analyzers\&.Tests\&.Extensions\&.IMethodSymbolExtensionsTests\&.IsRootDataPortalOperationForChildFetchWithAttribute ()"

.SS "async Task Csla\&.Analyzers\&.Tests\&.Extensions\&.IMethodSymbolExtensionsTests\&.IsRootDataPortalOperationForChildInsert ()"

.SS "async Task Csla\&.Analyzers\&.Tests\&.Extensions\&.IMethodSymbolExtensionsTests\&.IsRootDataPortalOperationForChildInsertWithAttribute ()"

.SS "async Task Csla\&.Analyzers\&.Tests\&.Extensions\&.IMethodSymbolExtensionsTests\&.IsRootDataPortalOperationForChildUpdate ()"

.SS "async Task Csla\&.Analyzers\&.Tests\&.Extensions\&.IMethodSymbolExtensionsTests\&.IsRootDataPortalOperationForChildUpdateWithAttribute ()"

.SS "async Task Csla\&.Analyzers\&.Tests\&.Extensions\&.IMethodSymbolExtensionsTests\&.IsRootDataPortalOperationForDataPortalCreate ()"

.SS "async Task Csla\&.Analyzers\&.Tests\&.Extensions\&.IMethodSymbolExtensionsTests\&.IsRootDataPortalOperationForDataPortalCreateWithAttribute ()"

.SS "async Task Csla\&.Analyzers\&.Tests\&.Extensions\&.IMethodSymbolExtensionsTests\&.IsRootDataPortalOperationForDataPortalDelete ()"

.SS "async Task Csla\&.Analyzers\&.Tests\&.Extensions\&.IMethodSymbolExtensionsTests\&.IsRootDataPortalOperationForDataPortalDeleteSelf ()"

.SS "async Task Csla\&.Analyzers\&.Tests\&.Extensions\&.IMethodSymbolExtensionsTests\&.IsRootDataPortalOperationForDataPortalDeleteSelfWithAttribute ()"

.SS "async Task Csla\&.Analyzers\&.Tests\&.Extensions\&.IMethodSymbolExtensionsTests\&.IsRootDataPortalOperationForDataPortalDeleteWithAttribute ()"

.SS "async Task Csla\&.Analyzers\&.Tests\&.Extensions\&.IMethodSymbolExtensionsTests\&.IsRootDataPortalOperationForDataPortalExecute ()"

.SS "async Task Csla\&.Analyzers\&.Tests\&.Extensions\&.IMethodSymbolExtensionsTests\&.IsRootDataPortalOperationForDataPortalExecuteWithAttribute ()"

.SS "async Task Csla\&.Analyzers\&.Tests\&.Extensions\&.IMethodSymbolExtensionsTests\&.IsRootDataPortalOperationForDataPortalFetch ()"

.SS "async Task Csla\&.Analyzers\&.Tests\&.Extensions\&.IMethodSymbolExtensionsTests\&.IsRootDataPortalOperationForDataPortalFetchWithAttribute ()"

.SS "async Task Csla\&.Analyzers\&.Tests\&.Extensions\&.IMethodSymbolExtensionsTests\&.IsRootDataPortalOperationForDataPortalInsert ()"

.SS "async Task Csla\&.Analyzers\&.Tests\&.Extensions\&.IMethodSymbolExtensionsTests\&.IsRootDataPortalOperationForDataPortalInsertWithAttribute ()"

.SS "async Task Csla\&.Analyzers\&.Tests\&.Extensions\&.IMethodSymbolExtensionsTests\&.IsRootDataPortalOperationForDataPortalUpdate ()"

.SS "async Task Csla\&.Analyzers\&.Tests\&.Extensions\&.IMethodSymbolExtensionsTests\&.IsRootDataPortalOperationForDataPortalUpdateWithAttribute ()"

.SS "async Task Csla\&.Analyzers\&.Tests\&.Extensions\&.IMethodSymbolExtensionsTests\&.IsRootDataPortalOperationForMethodThatIsNotADataPortalOperation ()"

.SS "void Csla\&.Analyzers\&.Tests\&.Extensions\&.IMethodSymbolExtensionsTests\&.IsRootDataPortalOperationWhenSymbolIsNull ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
