.TH "Csla.Test.ValidationRules.ShortCircuitTests" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.ValidationRules.ShortCircuitTests
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBShortCircuitOnNew\fP ()"
.br
.ti -1c
.RI "void \fBShortCircuitOnPropertySet\fP ()"
.br
.ti -1c
.RI "void \fBHigherThreshold\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 26 of file ShortCircuitTests\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Csla\&.Test\&.ValidationRules\&.ShortCircuitTests\&.HigherThreshold ()"

.PP
Definition at line 51 of file ShortCircuitTests\&.cs\&.
.SS "void Csla\&.Test\&.ValidationRules\&.ShortCircuitTests\&.ShortCircuitOnNew ()"

.PP
Definition at line 29 of file ShortCircuitTests\&.cs\&.
.SS "void Csla\&.Test\&.ValidationRules\&.ShortCircuitTests\&.ShortCircuitOnPropertySet ()"

.PP
Definition at line 38 of file ShortCircuitTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
