.TH "Csla.Test.Data.Table2" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.Data.Table2 \- No Metadata Documentation available\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits EntityObject\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBTable2\fP \fBCreateTable2\fP (global::System\&.String firstName, global::System\&.String lastName, global::System\&.String smallColumn)"
.br
.RI "Create a new \fBTable2\fP object\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "global::System\&.String \fBFirstName\fP\fC [get, set]\fP"
.br
.RI "No Metadata Documentation available\&. "
.ti -1c
.RI "global::System\&.String \fBLastName\fP\fC [get, set]\fP"
.br
.RI "No Metadata Documentation available\&. "
.ti -1c
.RI "global::System\&.String \fBSmallColumn\fP\fC [get, set]\fP"
.br
.RI "No Metadata Documentation available\&. "
.in -1c
.SH "Detailed Description"
.PP 
No Metadata Documentation available\&. 


.PP
Definition at line 107 of file TestEFContext\&.Designer\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "static \fBTable2\fP Csla\&.Test\&.Data\&.Table2\&.CreateTable2 (global::System\&.String firstName, global::System\&.String lastName, global::System\&.String smallColumn)\fC [static]\fP"

.PP
Create a new \fBTable2\fP object\&. 
.PP
\fBParameters\fP
.RS 4
\fIfirstName\fP Initial value of the FirstName property\&.
.br
\fIlastName\fP Initial value of the LastName property\&.
.br
\fIsmallColumn\fP Initial value of the SmallColumn property\&.
.RE
.PP

.PP
Definition at line 117 of file TestEFContext\&.Designer\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "global\&.System\&.String Csla\&.Test\&.Data\&.Table2\&.FirstName\fC [get]\fP, \fC [set]\fP"

.PP
No Metadata Documentation available\&. 
.PP
Definition at line 135 of file TestEFContext\&.Designer\&.cs\&.
.SS "global\&.System\&.String Csla\&.Test\&.Data\&.Table2\&.LastName\fC [get]\fP, \fC [set]\fP"

.PP
No Metadata Documentation available\&. 
.PP
Definition at line 162 of file TestEFContext\&.Designer\&.cs\&.
.SS "global\&.System\&.String Csla\&.Test\&.Data\&.Table2\&.SmallColumn\fC [get]\fP, \fC [set]\fP"

.PP
No Metadata Documentation available\&. 
.PP
Definition at line 189 of file TestEFContext\&.Designer\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
