.TH "Csla.Analyzers.Extensions.DataPortalOperationQualification" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Analyzers.Extensions.DataPortalOperationQualification
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDataPortalOperationQualification\fP (bool byNamingConvention, bool byAttribute)"
.br
.ti -1c
.RI "\fBDataPortalOperationQualification\fP \fBCombine\fP (\fBDataPortalOperationQualification\fP qualification)"
.br
.ti -1c
.RI "void \fBDeconstruct\fP (out bool byNamingConvention, out bool byAttribute)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static implicit \fBoperator bool\fP (\fBDataPortalOperationQualification\fP qualification)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "bool \fBByAttribute\fP\fC [get]\fP"
.br
.ti -1c
.RI "bool \fBByNamingConvention\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 3 of file DataPortalOperationQualification\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Csla\&.Analyzers\&.Extensions\&.DataPortalOperationQualification\&.DataPortalOperationQualification (bool byNamingConvention, bool byAttribute)"

.SH "Member Function Documentation"
.PP 
.SS "\fBDataPortalOperationQualification\fP Csla\&.Analyzers\&.Extensions\&.DataPortalOperationQualification\&.Combine (\fBDataPortalOperationQualification\fP qualification)"

.SS "void Csla\&.Analyzers\&.Extensions\&.DataPortalOperationQualification\&.Deconstruct (out bool byNamingConvention, out bool byAttribute)"

.SS "static implicit Csla\&.Analyzers\&.Extensions\&.DataPortalOperationQualification\&.operator bool (\fBDataPortalOperationQualification\fP qualification)\fC [static]\fP"

.SH "Property Documentation"
.PP 
.SS "bool Csla\&.Analyzers\&.Extensions\&.DataPortalOperationQualification\&.ByAttribute\fC [get]\fP"

.PP
Definition at line 19 of file DataPortalOperationQualification\&.cs\&.
.SS "bool Csla\&.Analyzers\&.Extensions\&.DataPortalOperationQualification\&.ByNamingConvention\fC [get]\fP"

.PP
Definition at line 20 of file DataPortalOperationQualification\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
