.TH "BindingManager.cs" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BindingManager.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCsla\&.Iosui\&.Binding\&.BindingManager\fP"
.br
.RI "Provides the ability to bing properties on iOS UI controls to properties on CSLA objects\&. Bindings update normally when the control looses focus\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBCsla\fP"
.br
.ti -1c
.RI "namespace \fBCsla\&.Iosui\fP"
.br
.ti -1c
.RI "namespace \fBCsla\&.Iosui\&.Binding\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
