.TH "csla.netcore.test.DataPortal" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csla.netcore.test.DataPortal
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDashboardTests\fP"
.br
.ti -1c
.RI "class \fBSimpleType\fP"
.br
.ti -1c
.RI "class \fBDataPortalClientTests\fP"
.br
.ti -1c
.RI "class \fBDefaultType\fP"
.br
.ti -1c
.RI "class \fBTestType\fP"
.br
.ti -1c
.RI "class \fBResourceType\fP"
.br
.ti -1c
.RI "class \fBRoutingTagTests\fP"
.br
.ti -1c
.RI "class \fBRoutingTest\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum class \fBServerResources\fP { \fBLotsOfMemory\fP, \fBAccessToLegacyDatabase\fP, \fBSpecializedAlgorithm\fP }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBcsla\&.netcore\&.test\&.DataPortal\&.ServerResources\fP\fC [strong]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fILotsOfMemory \fP\fP
.TP
\fB\fIAccessToLegacyDatabase \fP\fP
.TP
\fB\fISpecializedAlgorithm \fP\fP
.PP
Definition at line 124 of file DataPortalClientTests\&.cs\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
