.TH "Csla.Server.IDataPortalExceptionInspector" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Server.IDataPortalExceptionInspector \- Implement this interface to check a \fBDataPortalException\fP before returning Exception to the client\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBInspectException\fP (Type objectType, object businessObject, object criteria, string methodName, Exception ex)"
.br
.RI "Inspects the exception that occurred during \fBDataPortal\fP call If you want to transform to/return another Exception to the client you must throw the new Exception in this method\&. "
.in -1c
.SH "Detailed Description"
.PP 
Implement this interface to check a \fBDataPortalException\fP before returning Exception to the client\&. 

Make sure to rethrow a new exception if you want to transfrom to new exception\&.
.PP
Definition at line 17 of file IDataPortalExceptionInspector\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Csla\&.Server\&.IDataPortalExceptionInspector\&.InspectException (Type objectType, object businessObject, object criteria, string methodName, Exception ex)"

.PP
Inspects the exception that occurred during \fBDataPortal\fP call If you want to transform to/return another Exception to the client you must throw the new Exception in this method\&. 
.PP
\fBParameters\fP
.RS 4
\fIobjectType\fP Type of the object\&.
.br
\fIbusinessObject\fP The business object , if available\&.
.br
\fIcriteria\fP The criteria\&.
.br
\fImethodName\fP Name of the method\&.
.br
\fIex\fP The exception\&.
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
