.TH "Csla.Xaml" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Xaml
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBApplicationContextManager\fP"
.br
.RI "\fBApplicationContextManager\fP for WPF applications "
.ti -1c
.RI "class \fBBrokenRuleSeverityConverter\fP"
.br
.RI "Converts validation severity values into corresponding images\&. "
.ti -1c
.RI "class \fBBusyAnimation\fP"
.br
.RI "Displays a busy animation\&. "
.ti -1c
.RI "class \fBCancellableViewModel\fP"
.br
.RI "\fBViewModel\fP without multithreading (concurrency) bugs\&. "
.ti -1c
.RI "class \fBCslaOperation\fP"
.br
.ti -1c
.RI "class \fBCslaDataProvider\fP"
.br
.RI "Wraps and creates a CSLA \&.NET-style object that you can use as a binding source\&. "
.ti -1c
.RI "class \fBCslaDataProviderCommandManager\fP"
.br
.RI "Implements support for RoutedCommands that can be executed by the \fBCslaDataProvider\fP control\&. "
.ti -1c
.RI "class \fBDataDecoratorBase\fP"
.br
.RI "Base class for creating WPF panel controls that react when the DataContext, data object and data property values are changed\&. "
.ti -1c
.RI "class \fBErrorDialog\fP"
.br
.RI "Displays an error dialog for any exceptions that occur in a \fBCslaDataProvider\fP\&. "
.ti -1c
.RI "class \fBErrorEventArgs\fP"
.br
.RI "Contains information about the error that has occurred\&. "
.ti -1c
.RI "class \fBExecuteEventArgs\fP"
.br
.RI "Arguments passed to a method invoked by the Execute trigger action\&. "
.ti -1c
.RI "class \fBIdentityConverter\fP"
.br
.RI "Provides the functionality of a WPF value converter without affecting the value as it flows to and from the UI\&. "
.ti -1c
.RI "interface \fBIErrorDialog\fP"
.br
.RI "Interface defining the interaction between a CslaDataSource and an error dialog control\&. "
.ti -1c
.RI "class \fBInvokeMethod\fP"
.br
.RI "Invokes a method on a target object when a trigger event is raised from the attached UI control\&. "
.ti -1c
.RI "class \fBIsNotConverter\fP"
.br
.RI "Converts a Boolean value into its inverse\&. "
.ti -1c
.RI "interface \fBIViewModel\fP"
.br
.RI "Defines a CSLA \&.NET viewmodel object\&. "
.ti -1c
.RI "class \fBObjectStatus\fP"
.br
.RI "Container for other UI controls that exposes various status values from the CSLA \&.NET business object acting as DataContext\&. "
.ti -1c
.RI "class \fBPropertyInfo\fP"
.br
.RI "Expose metastate information about a property\&. "
.ti -1c
.RI "class \fBPropertyStatus\fP"
.br
.RI "Displays validation information for a business object property, and manipulates an associated UI control based on the business object's authorization rules\&. "
.ti -1c
.RI "class \fBTriggerAction\fP"
.br
.RI "Control used to invoke a method on the DataContext based on an event being raised by a UI control\&. "
.ti -1c
.RI "class \fBViewModel\fP"
.br
.RI "Base class used to create \fBViewModel\fP objects, with pre-existing verbs for use by \fBInvokeMethod\fP or Invoke\&. "
.ti -1c
.RI "class \fBViewModelBase\fP"
.br
.RI "Base class used to create \fBViewModel\fP objects that implement their own commands/verbs/actions\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
