.TH "Csla.Security.ICslaIdentity" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Security.ICslaIdentity \- Provides a base type to simplify creation of a \&.NET identity object for use with \fBICslaPrincipal\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.IReadOnlyBase\fP, IIdentity, and \fBCsla\&.Security\&.ICheckRoles\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBMobileList\fP< string > \fBRoles\fP\fC [get]\fP"
.br
.RI "Gets the list of roles for this user\&. "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Provides a base type to simplify creation of a \&.NET identity object for use with \fBICslaPrincipal\fP\&. 


.PP
Definition at line 17 of file ICslaIdentity\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "\fBMobileList\fP<string> Csla\&.Security\&.ICslaIdentity\&.Roles\fC [get]\fP"

.PP
Gets the list of roles for this user\&. 
.PP
Definition at line 23 of file ICslaIdentity\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
