.TH "Csla.Server.Hosts.Mobile.IWcfPortal" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Server.Hosts.Mobile.IWcfPortal \- Defines the service contract for the WCF data portal\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBCsla\&.Server\&.Hosts\&.Mobile\&.WcfPortal\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "Task< \fBWcfResponse\fP > \fBCreate\fP (\fBCriteriaRequest\fP request)"
.br
.RI "Create a new business object\&. "
.ti -1c
.RI "Task< \fBWcfResponse\fP > \fBFetch\fP (\fBCriteriaRequest\fP request)"
.br
.RI "Get an existing business object\&. "
.ti -1c
.RI "Task< \fBWcfResponse\fP > \fBUpdate\fP (\fBUpdateRequest\fP request)"
.br
.RI "Update a business object\&. "
.ti -1c
.RI "Task< \fBWcfResponse\fP > \fBDelete\fP (\fBCriteriaRequest\fP request)"
.br
.RI "Delete a business object\&. "
.in -1c
.SH "Detailed Description"
.PP 
Defines the service contract for the WCF data portal\&. 


.PP
Definition at line 19 of file Server/Hosts/Mobile/IWcfPortal\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "Task<\fBWcfResponse\fP> Csla\&.Server\&.Hosts\&.Mobile\&.IWcfPortal\&.Create (\fBCriteriaRequest\fP request)"

.PP
Create a new business object\&. 
.PP
\fBParameters\fP
.RS 4
\fIrequest\fP The request parameter object\&.
.RE
.PP

.PP
Implemented in \fBCsla\&.Server\&.Hosts\&.Mobile\&.WcfPortal\fP\&.
.SS "Task<\fBWcfResponse\fP> Csla\&.Server\&.Hosts\&.Mobile\&.IWcfPortal\&.Delete (\fBCriteriaRequest\fP request)"

.PP
Delete a business object\&. 
.PP
\fBParameters\fP
.RS 4
\fIrequest\fP The request parameter object\&.
.RE
.PP

.PP
Implemented in \fBCsla\&.Server\&.Hosts\&.Mobile\&.WcfPortal\fP\&.
.SS "Task<\fBWcfResponse\fP> Csla\&.Server\&.Hosts\&.Mobile\&.IWcfPortal\&.Fetch (\fBCriteriaRequest\fP request)"

.PP
Get an existing business object\&. 
.PP
\fBParameters\fP
.RS 4
\fIrequest\fP The request parameter object\&.
.RE
.PP

.PP
Implemented in \fBCsla\&.Server\&.Hosts\&.Mobile\&.WcfPortal\fP\&.
.SS "Task<\fBWcfResponse\fP> Csla\&.Server\&.Hosts\&.Mobile\&.IWcfPortal\&.Update (\fBUpdateRequest\fP request)"

.PP
Update a business object\&. 
.PP
\fBParameters\fP
.RS 4
\fIrequest\fP The request parameter object\&.
.RE
.PP

.PP
Implemented in \fBCsla\&.Server\&.Hosts\&.Mobile\&.WcfPortal\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
