.TH "Csla.Test.PropertyGetSet" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.PropertyGetSet
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBadGetSet\fP"
.br
.ti -1c
.RI "class \fBBadGetSetTwo\fP"
.br
.ti -1c
.RI "class \fBChildList\fP"
.br
.ti -1c
.RI "class \fBEditableGetSet\fP"
.br
.ti -1c
.RI "class \fBEditableGetSetNFI\fP"
.br
.ti -1c
.RI "class \fBEditableGetSetBase\fP"
.br
.ti -1c
.RI "class \fBEditableGetSetNFIBase\fP"
.br
.ti -1c
.RI "class \fBEditableGetSetRuleValidation\fP"
.br
.ti -1c
.RI "class \fBEditableGetSetRuleValidationTests\fP"
.br
.ti -1c
.RI "class \fBEditableGetSetTopBase\fP"
.br
.ti -1c
.RI "class \fBEditableGetSetTopNFIBase\fP"
.br
.ti -1c
.RI "class \fBPropertyGetSetTests\fP"
.br
.ti -1c
.RI "class \fBCommand\fP"
.br
.ti -1c
.RI "class \fBReadOnly\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
