.TH "Csla.Test.EditableRootList.ERlist" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.EditableRootList.ERlist
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.DynamicBindingListBase< ERitem >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBERlist\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override object \fBAddNewCore\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 14 of file ERlist\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Csla\&.Test\&.EditableRootList\&.ERlist\&.ERlist ()"

.PP
Definition at line 16 of file ERlist\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override object Csla\&.Test\&.EditableRootList\&.ERlist\&.AddNewCore ()\fC [protected]\fP"

.PP
Definition at line 23 of file ERlist\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
