.TH "Csla.Server.Hosts.Mobile.MobileFactoryLoader" 3 "Thu Jul 22 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Server.Hosts.Mobile.MobileFactoryLoader \- Class containing the default implementation for the FactoryLoader delegate used by the data portal host\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.Server\&.Hosts\&.Mobile\&.IMobileFactoryLoader\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "object \fBGetFactory\fP (string factoryName)"
.br
.RI "Creates an instance of a mobile factory object for use by the data portal\&. "
.in -1c
.SH "Detailed Description"
.PP 
Class containing the default implementation for the FactoryLoader delegate used by the data portal host\&. 


.PP
Definition at line 21 of file MobileFactoryLoader\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "object Csla\&.Server\&.Hosts\&.Mobile\&.MobileFactoryLoader\&.GetFactory (string factoryName)"

.PP
Creates an instance of a mobile factory object for use by the data portal\&. 
.PP
\fBParameters\fP
.RS 4
\fIfactoryName\fP Type assembly qualified type name for the mobile factory class as provided from the MobileFactory attribute on the business object\&. 
.RE
.PP
\fBReturns\fP
.RS 4
An instance of the type specified by the type name parameter\&. 
.RE
.PP

.PP
Implements \fBCsla\&.Server\&.Hosts\&.Mobile\&.IMobileFactoryLoader\fP\&.
.PP
Definition at line 37 of file MobileFactoryLoader\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
