.TH "Csla.Test.Serialization.CslaClaimsPrincipalSerializationTests" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.Serialization.CslaClaimsPrincipalSerializationTests
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSerializeCslaClaimsPrincipal\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 33 of file CslaClaimsPrincipalSerializationTests\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Csla\&.Test\&.Serialization\&.CslaClaimsPrincipalSerializationTests\&.SerializeCslaClaimsPrincipal ()"

.PP
Definition at line 36 of file CslaClaimsPrincipalSerializationTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
