.TH "Csla.Validation.CommonRules.MinLengthRuleArgs" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Validation.CommonRules.MinLengthRuleArgs \- Custom \fBRuleArgs\fP object required by the StringMinLength rule method\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.Validation\&.DecoratedRuleArgs\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMinLengthRuleArgs\fP (string propertyName, int minLength)"
.br
.RI "Create a new object\&. "
.ti -1c
.RI "\fBMinLengthRuleArgs\fP (\fBCore\&.IPropertyInfo\fP propertyInfo, int minLength)"
.br
.RI "Create a new object\&. "
.ti -1c
.RI "\fBMinLengthRuleArgs\fP (string propertyName, string friendlyName, int minLength)"
.br
.RI "Create a new object\&. "
.ti -1c
.RI "\fBMinLengthRuleArgs\fP (string propertyName, int minLength, string format)"
.br
.RI "Create a new object\&. "
.ti -1c
.RI "\fBMinLengthRuleArgs\fP (\fBCore\&.IPropertyInfo\fP propertyInfo, int minLength, string format)"
.br
.RI "Create a new object\&. "
.ti -1c
.RI "\fBMinLengthRuleArgs\fP (string propertyName, string friendlyName, int minLength, string format)"
.br
.RI "Create a new object\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBMinLength\fP\fC [get]\fP"
.br
.RI "Get the min length for the string\&. "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Custom \fBRuleArgs\fP object required by the StringMinLength rule method\&. 


.PP
Definition at line 240 of file Csla\&.Validation\&.Shared/CommonRules\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Csla\&.Validation\&.CommonRules\&.MinLengthRuleArgs\&.MinLengthRuleArgs (string propertyName, int minLength)"

.PP
Create a new object\&. 
.PP
\fBParameters\fP
.RS 4
\fIpropertyName\fP Name of the property to validate\&.
.br
\fIminLength\fP min length of characters allowed\&.
.RE
.PP

.PP
Definition at line 255 of file Csla\&.Validation\&.Shared/CommonRules\&.cs\&.
.SS "Csla\&.Validation\&.CommonRules\&.MinLengthRuleArgs\&.MinLengthRuleArgs (\fBCore\&.IPropertyInfo\fP propertyInfo, int minLength)"

.PP
Create a new object\&. 
.PP
\fBParameters\fP
.RS 4
\fIpropertyInfo\fP Property to validate\&.
.br
\fIminLength\fP min length of characters allowed\&.
.RE
.PP

.PP
Definition at line 268 of file Csla\&.Validation\&.Shared/CommonRules\&.cs\&.
.SS "Csla\&.Validation\&.CommonRules\&.MinLengthRuleArgs\&.MinLengthRuleArgs (string propertyName, string friendlyName, int minLength)"

.PP
Create a new object\&. 
.PP
\fBParameters\fP
.RS 4
\fIpropertyName\fP Name of the property to validate\&.
.br
\fIfriendlyName\fP A friendly name for the property, which will be used in place of the property name when creating the broken rule description string\&.
.br
\fIminLength\fP min length of characters allowed\&.
.RE
.PP

.PP
Definition at line 284 of file Csla\&.Validation\&.Shared/CommonRules\&.cs\&.
.SS "Csla\&.Validation\&.CommonRules\&.MinLengthRuleArgs\&.MinLengthRuleArgs (string propertyName, int minLength, string format)"

.PP
Create a new object\&. 
.PP
\fBParameters\fP
.RS 4
\fIpropertyName\fP Name of the property to validate\&.
.br
\fIminLength\fP min length of characters allowed\&.
.br
\fIformat\fP Format string for the min length value in the broken rule string\&.
.RE
.PP

.PP
Definition at line 299 of file Csla\&.Validation\&.Shared/CommonRules\&.cs\&.
.SS "Csla\&.Validation\&.CommonRules\&.MinLengthRuleArgs\&.MinLengthRuleArgs (\fBCore\&.IPropertyInfo\fP propertyInfo, int minLength, string format)"

.PP
Create a new object\&. 
.PP
\fBParameters\fP
.RS 4
\fIpropertyInfo\fP Property to validate\&.
.br
\fIminLength\fP min length of characters allowed\&.
.br
\fIformat\fP Format string for the min length value in the broken rule string\&.
.RE
.PP

.PP
Definition at line 314 of file Csla\&.Validation\&.Shared/CommonRules\&.cs\&.
.SS "Csla\&.Validation\&.CommonRules\&.MinLengthRuleArgs\&.MinLengthRuleArgs (string propertyName, string friendlyName, int minLength, string format)"

.PP
Create a new object\&. 
.PP
\fBParameters\fP
.RS 4
\fIpropertyName\fP Name of the property to validate\&.
.br
\fIfriendlyName\fP A friendly name for the property, which will be used in place of the property name when creating the broken rule description string\&.
.br
\fIminLength\fP min length of characters allowed\&.
.br
\fIformat\fP Format string for the min length value in the broken rule string\&.
.RE
.PP

.PP
Definition at line 332 of file Csla\&.Validation\&.Shared/CommonRules\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "int Csla\&.Validation\&.CommonRules\&.MinLengthRuleArgs\&.MinLength\fC [get]\fP"

.PP
Get the min length for the string\&. 
.PP
Definition at line 245 of file Csla\&.Validation\&.Shared/CommonRules\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
