.TH "cslalighttest.ViewModelTests.TestBusinessBindingList" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cslalighttest.ViewModelTests.TestBusinessBindingList
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.BusinessBindingListBase< TestBusinessBindingList, TestChild >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTestBusinessBindingList\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBTestBusinessBindingList\fP \fBNewEditableList\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 8 of file TestBusinessBindingList\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "cslalighttest\&.ViewModelTests\&.TestBusinessBindingList\&.TestBusinessBindingList ()"

.PP
Definition at line 13 of file TestBusinessBindingList\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "static \fBTestBusinessBindingList\fP cslalighttest\&.ViewModelTests\&.TestBusinessBindingList\&.NewEditableList ()\fC [static]\fP"

.PP
Definition at line 18 of file TestBusinessBindingList\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
