.TH "Csla.Test.ChildChanged.ContainsList" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.ChildChanged.ContainsList
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.BusinessBase< ContainsList >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBContainsList\fP ()"
.br
.ti -1c
.RI "\fBContainsList\fP (bool child)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBSingleList\fP \fBList\fP\fC [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 18 of file ContainsList\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Csla\&.Test\&.ChildChanged\&.ContainsList\&.ContainsList ()"

.PP
Definition at line 20 of file ContainsList\&.cs\&.
.SS "Csla\&.Test\&.ChildChanged\&.ContainsList\&.ContainsList (bool child)"

.PP
Definition at line 23 of file ContainsList\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "\fBSingleList\fP Csla\&.Test\&.ChildChanged\&.ContainsList\&.List\fC [get]\fP"

.PP
Definition at line 30 of file ContainsList\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
