.TH "Csla.BrokeredDataPortalHost" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.BrokeredDataPortalHost
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBrokeredHost\fP"
.br
.RI "Brokered assembly entry point for the data portal\&. For use by side-loaded WinRT client apps\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
