.TH "Csla.Xaml.ViewModel< T >" 3 "Thu Jul 22 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Xaml.ViewModel< T > \- Base class used to create \fBViewModel\fP objects, with pre-existing verbs for use by \fBInvokeMethod\fP or Invoke\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.Xaml\&.ViewModelBase< T >\fP\&.
.PP
Inherited by \fBCsla\&.Xaml\&.CancellableViewModel< T >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBSave\fP (object sender, \fBExecuteEventArgs\fP e)"
.br
.RI "Saves the Model, first committing changes if ManagedObjectLifetime is true\&. "
.ti -1c
.RI "virtual async void \fBSaveAsync\fP (object sender, \fBExecuteEventArgs\fP e)"
.br
.RI "Saves the Model, first committing changes if ManagedObjectLifetime is true\&. "
.ti -1c
.RI "virtual void \fBCancel\fP (object sender, \fBExecuteEventArgs\fP e)"
.br
.RI "Cancels changes made to the model if ManagedObjectLifetime is true\&. "
.ti -1c
.RI "virtual void \fBAddNew\fP (object sender, \fBExecuteEventArgs\fP e)"
.br
.RI "Adds a new item to the Model (if it is a collection)\&. "
.ti -1c
.RI "virtual void \fBRemove\fP (object sender, \fBExecuteEventArgs\fP e)"
.br
.RI "Removes an item from the Model (if it is a collection)\&. "
.ti -1c
.RI "virtual void \fBDelete\fP (object sender, \fBExecuteEventArgs\fP e)"
.br
.RI "Marks the Model for deletion (if it is an editable root object)\&. "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Base class used to create \fBViewModel\fP objects, with pre-existing verbs for use by \fBInvokeMethod\fP or Invoke\&. 


.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP Type of the Model object\&.
.RE
.PP

.PP
Definition at line 30 of file Csla\&.Xaml\&.Shared/ViewModel\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual void \fBCsla\&.Xaml\&.ViewModel\fP< T >\&.AddNew (object sender, \fBExecuteEventArgs\fP e)\fC [virtual]\fP"

.PP
Adds a new item to the Model (if it is a collection)\&. 
.PP
Definition at line 64 of file Csla\&.Xaml\&.Shared/ViewModel\&.cs\&.
.SS "virtual void \fBCsla\&.Xaml\&.ViewModel\fP< T >\&.Cancel (object sender, \fBExecuteEventArgs\fP e)\fC [virtual]\fP"

.PP
Cancels changes made to the model if ManagedObjectLifetime is true\&. 
.PP
Definition at line 55 of file Csla\&.Xaml\&.Shared/ViewModel\&.cs\&.
.SS "virtual void \fBCsla\&.Xaml\&.ViewModel\fP< T >\&.Delete (object sender, \fBExecuteEventArgs\fP e)\fC [virtual]\fP"

.PP
Marks the Model for deletion (if it is an editable root object)\&. 
.PP
Definition at line 86 of file Csla\&.Xaml\&.Shared/ViewModel\&.cs\&.
.SS "virtual void \fBCsla\&.Xaml\&.ViewModel\fP< T >\&.Remove (object sender, \fBExecuteEventArgs\fP e)\fC [virtual]\fP"

.PP
Removes an item from the Model (if it is a collection)\&. 
.PP
Definition at line 77 of file Csla\&.Xaml\&.Shared/ViewModel\&.cs\&.
.SS "virtual void \fBCsla\&.Xaml\&.ViewModel\fP< T >\&.Save (object sender, \fBExecuteEventArgs\fP e)\fC [virtual]\fP"

.PP
Saves the Model, first committing changes if ManagedObjectLifetime is true\&. 
.PP
Definition at line 37 of file Csla\&.Xaml\&.Shared/ViewModel\&.cs\&.
.SS "virtual async void \fBCsla\&.Xaml\&.ViewModel\fP< T >\&.SaveAsync (object sender, \fBExecuteEventArgs\fP e)\fC [virtual]\fP"

.PP
Saves the Model, first committing changes if ManagedObjectLifetime is true\&. 
.PP
Definition at line 46 of file Csla\&.Xaml\&.Shared/ViewModel\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
