.TH "Csla.Test.PropertyGetSet.Command" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.PropertyGetSet.Command
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.CommandBase< Command >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBLoad\fP (string name)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static readonly \fBPropertyInfo\fP< string > \fBNameProperty\fP = RegisterProperty<string>(c => c\&.Name)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBName\fP\fC [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 756 of file PropertyGetSetTests\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Csla\&.Test\&.PropertyGetSet\&.Command\&.Load (string name)"

.PP
Definition at line 764 of file PropertyGetSetTests\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "readonly \fBPropertyInfo\fP<string> Csla\&.Test\&.PropertyGetSet\&.Command\&.NameProperty = RegisterProperty<string>(c => c\&.Name)\fC [static]\fP"

.PP
Definition at line 758 of file PropertyGetSetTests\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "string Csla\&.Test\&.PropertyGetSet\&.Command\&.Name\fC [get]\fP"

.PP
Definition at line 759 of file PropertyGetSetTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
