.TH "Csla.Ios.Test.Application" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Ios.Test.Application
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Definition at line 10 of file Main\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
