.TH "Csla.Test.DataPortal.ClassB" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.DataPortal.ClassB
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.BusinessBase< ClassB >\fP\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBClassB\fP \fBGetClassB\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBDisposableClass\fP \fBDisposableClass\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "Guid \fBId\fP\fC [get, set]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 72 of file DisposeScopeTest\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "static \fBClassB\fP Csla\&.Test\&.DataPortal\&.ClassB\&.GetClassB ()\fC [static]\fP"

.PP
Definition at line 77 of file DisposeScopeTest\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "\fBDisposableClass\fP Csla\&.Test\&.DataPortal\&.ClassB\&.DisposableClass\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 74 of file DisposeScopeTest\&.cs\&.
.SS "Guid Csla\&.Test\&.DataPortal\&.ClassB\&.Id\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 75 of file DisposeScopeTest\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
