.TH "Csla.Xaml.ExecuteEventArgs" 3 "Thu Jul 22 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Xaml.ExecuteEventArgs \- Arguments passed to a method invoked by the Execute trigger action\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits EventArgs\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "FrameworkElement \fBTriggerSource\fP\fC [get, set]\fP"
.br
.RI "The control that raised the event that triggered invocation of this method\&. "
.ti -1c
.RI "object \fBMethodParameter\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "object \fBTriggerParameter\fP\fC [get, set]\fP"
.br
.RI "The EventArgs parameter from the event that triggered invocation of this method\&. "
.in -1c
.SH "Detailed Description"
.PP 
Arguments passed to a method invoked by the Execute trigger action\&. 


.PP
Definition at line 24 of file ExecuteEventArgs\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "object Csla\&.Xaml\&.ExecuteEventArgs\&.MethodParameter\fC [get]\fP, \fC [set]\fP"

.PP
The MethodParameter value provided by the designer\&.
.PP
Definition at line 37 of file ExecuteEventArgs\&.cs\&.
.SS "object Csla\&.Xaml\&.ExecuteEventArgs\&.TriggerParameter\fC [get]\fP, \fC [set]\fP"

.PP
The EventArgs parameter from the event that triggered invocation of this method\&. 
.PP
Definition at line 42 of file ExecuteEventArgs\&.cs\&.
.SS "FrameworkElement Csla\&.Xaml\&.ExecuteEventArgs\&.TriggerSource\fC [get]\fP, \fC [set]\fP"

.PP
The control that raised the event that triggered invocation of this method\&. 
.PP
Definition at line 31 of file ExecuteEventArgs\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
