.TH "Csla.Rules.IBusinessRule" 3 "Thu Jul 22 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Rules.IBusinessRule \- Interface defining a business/validation rule implementation\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.Rules\&.IBusinessRuleBase\fP\&.
.PP
Inherited by \fBCsla\&.Rules\&.BusinessRule\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBExecute\fP (\fBIRuleContext\fP context)"
.br
.RI "Business or validation rule implementation\&. "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Interface defining a business/validation rule implementation\&. 


.PP
Definition at line 91 of file IBusinessRule\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Csla\&.Rules\&.IBusinessRule\&.Execute (\fBIRuleContext\fP context)"

.PP
Business or validation rule implementation\&. 
.PP
\fBParameters\fP
.RS 4
\fIcontext\fP Rule context object\&.
.RE
.PP

.PP
Implemented in \fBCsla\&.Rules\&.CommonRules\&.Lambda\fP, \fBCsla\&.Rules\&.CommonRules\&.InfoMessage\fP, \fBCsla\&.Rules\&.CommonRules\&.RegExMatch\fP, \fBCsla\&.Rules\&.CommonRules\&.MaxValue< T >\fP, \fBCsla\&.Rules\&.CommonRules\&.MinValue< T >\fP, \fBCsla\&.Rules\&.CommonRules\&.MinLength\fP, \fBCsla\&.Rules\&.CommonRules\&.MaxLength\fP, \fBCsla\&.Rules\&.CommonRules\&.Required\fP, \fBCsla\&.Rules\&.CommonRules\&.DataAnnotation\fP, and \fBCsla\&.Rules\&.BusinessRule\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
