.TH "Csla.Test.ValidationRules.RuleContextTests" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.ValidationRules.RuleContextTests
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBAddErrorResultThrowsErrorWhenMessageIsEmpty\fP ()"
.br
.ti -1c
.RI "void \fBAddErrorResultOnPropertyThrowsErrorWhenMessageIsEmpty\fP ()"
.br
.ti -1c
.RI "void \fBAddWarningResultThrowsErrorWhenMessageIsEmpty\fP ()"
.br
.ti -1c
.RI "void \fBAddWarningResultOnPropertyThrowsErrorWhenMessageIsEmpty\fP ()"
.br
.ti -1c
.RI "void \fBAddInformationResultThrowsErrorWhenMessageIsEmpty\fP ()"
.br
.ti -1c
.RI "void \fBAddInformationResultOnPropertyThrowsErrorWhenMessageIsEmpty\fP ()"
.br
.ti -1c
.RI "void \fBAddSuccessResultDoesNotFail\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 805 of file ValidationTests\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Csla\&.Test\&.ValidationRules\&.RuleContextTests\&.AddErrorResultOnPropertyThrowsErrorWhenMessageIsEmpty ()"

.PP
Definition at line 826 of file ValidationTests\&.cs\&.
.SS "void Csla\&.Test\&.ValidationRules\&.RuleContextTests\&.AddErrorResultThrowsErrorWhenMessageIsEmpty ()"

.PP
Definition at line 809 of file ValidationTests\&.cs\&.
.SS "void Csla\&.Test\&.ValidationRules\&.RuleContextTests\&.AddInformationResultOnPropertyThrowsErrorWhenMessageIsEmpty ()"

.PP
Definition at line 894 of file ValidationTests\&.cs\&.
.SS "void Csla\&.Test\&.ValidationRules\&.RuleContextTests\&.AddInformationResultThrowsErrorWhenMessageIsEmpty ()"

.PP
Definition at line 877 of file ValidationTests\&.cs\&.
.SS "void Csla\&.Test\&.ValidationRules\&.RuleContextTests\&.AddSuccessResultDoesNotFail ()"

.PP
Definition at line 911 of file ValidationTests\&.cs\&.
.SS "void Csla\&.Test\&.ValidationRules\&.RuleContextTests\&.AddWarningResultOnPropertyThrowsErrorWhenMessageIsEmpty ()"

.PP
Definition at line 860 of file ValidationTests\&.cs\&.
.SS "void Csla\&.Test\&.ValidationRules\&.RuleContextTests\&.AddWarningResultThrowsErrorWhenMessageIsEmpty ()"

.PP
Definition at line 843 of file ValidationTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
