.TH "cslalighttest.Serialization.MockMobileList" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cslalighttest.Serialization.MockMobileList
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.Core\&.MobileBindingList< MockReadOnly >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMockMobileList\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "bool \fBHasRaisedOnListChanged\fP\fC [get, set]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 26 of file MockMobileList\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "cslalighttest\&.Serialization\&.MockMobileList\&.MockMobileList ()"

.PP
Definition at line 28 of file MockMobileList\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "bool cslalighttest\&.Serialization\&.MockMobileList\&.HasRaisedOnListChanged\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 33 of file MockMobileList\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
