.TH "Csla.MethodInfo" 3 "Thu Jul 22 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.MethodInfo \- Maintains metadata about a method\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.Core\&.IMemberInfo\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMethodInfo\fP (string name)"
.br
.RI "Creates an instance of the object\&. "
.ti -1c
.RI "override bool \fBEquals\fP (object obj)"
.br
.RI "Determines the equality of two objects\&. "
.ti -1c
.RI "override int \fBGetHashCode\fP ()"
.br
.RI "Gets the hash code of this object\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBName\fP\fC [get]\fP"
.br
.RI "Gets the member name value\&. "
.in -1c
.SH "Detailed Description"
.PP 
Maintains metadata about a method\&. 


.PP
Definition at line 18 of file MethodInfo\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Csla\&.MethodInfo\&.MethodInfo (string name)"

.PP
Creates an instance of the object\&. 
.PP
\fBParameters\fP
.RS 4
\fIname\fP Name of the method\&.
.RE
.PP

.PP
Definition at line 24 of file MethodInfo\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override bool Csla\&.MethodInfo\&.Equals (object obj)"

.PP
Determines the equality of two objects\&. 
.PP
\fBParameters\fP
.RS 4
\fIobj\fP Object to compare\&.
.RE
.PP

.PP
Definition at line 38 of file MethodInfo\&.cs\&.
.SS "override int Csla\&.MethodInfo\&.GetHashCode ()"

.PP
Gets the hash code of this object\&. 
.PP
Definition at line 50 of file MethodInfo\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "string Csla\&.MethodInfo\&.Name\fC [get]\fP"

.PP
Gets the member name value\&. 
.PP
Definition at line 32 of file MethodInfo\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
