.TH "Csla.Core.IReadOnlyCollection" 3 "Thu Jul 22 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Core.IReadOnlyCollection \- Interface implemented by all read-only collection classes\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.Core\&.IBusinessObject\fP\&.
.PP
Inherited by \fBCsla\&.IReadOnlyListBase< C >\fP, \fBCsla\&.ReadOnlyBindingListBase< T, C >\fP, and \fBCsla\&.ReadOnlyListBase< T, C >\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Interface implemented by all read-only collection classes\&. 


.PP
Definition at line 16 of file IReadOnlyCollection\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
