.TH "Csla.Xaml.ErrorDialog" 3 "Thu Jul 22 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Xaml.ErrorDialog \- Displays an error dialog for any exceptions that occur in a \fBCslaDataProvider\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Control, and \fBCsla\&.Xaml\&.IErrorDialog\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBErrorDialog\fP ()"
.br
.RI "Creates a new instance of the control\&. "
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static readonly DependencyProperty \fBDialogTitleProperty\fP"
.br
.RI "Gets or sets the title of the error dialog\&. "
.ti -1c
.RI "static readonly DependencyProperty \fBDialogFirstLineProperty\fP"
.br
.RI "Gets or sets the first line of text displayed within the error dialog (before the exception message)\&. "
.ti -1c
.RI "static readonly DependencyProperty \fBShowExceptionDetailProperty\fP"
.br
.RI "Gets or sets a value indicating whether the dialog should include exception details or just the exception summary message\&. "
.ti -1c
.RI "static readonly DependencyProperty \fBDialogIconProperty\fP"
.br
.RI "Gets or sets a value indicating whether the dialog should include exception details or just the exception summary message\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBDialogTitle\fP\fC [get, set]\fP"
.br
.RI "Gets or sets the title of the error dialog\&. "
.ti -1c
.RI "string \fBDialogFirstLine\fP\fC [get, set]\fP"
.br
.RI "Gets or sets the first line of text displayed within the error dialog (before the exception message)\&. "
.ti -1c
.RI "bool \fBShowExceptionDetail\fP\fC [get, set]\fP"
.br
.RI "Gets or sets the first line of text displayed within the error dialog (before the exception message)\&. "
.ti -1c
.RI "MessageBoxImage \fBDialogIcon\fP\fC [get, set]\fP"
.br
.RI "Gets or sets the icon displayed in the dialog\&. "
.in -1c
.SH "Detailed Description"
.PP 
Displays an error dialog for any exceptions that occur in a \fBCslaDataProvider\fP\&. 


.PP
Definition at line 19 of file ErrorDialog\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Csla\&.Xaml\&.ErrorDialog\&.ErrorDialog ()"

.PP
Creates a new instance of the control\&. 
.PP
Definition at line 24 of file ErrorDialog\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "readonly DependencyProperty Csla\&.Xaml\&.ErrorDialog\&.DialogFirstLineProperty\fC [static]\fP"
\fBInitial value:\fP
.PP
.nf
= DependencyProperty\&.Register(
      "DialogFirstLine",
      typeof(string),
      typeof(ErrorDialog),
      null)
.fi
.PP
Gets or sets the first line of text displayed within the error dialog (before the exception message)\&. 
.PP
Definition at line 61 of file ErrorDialog\&.cs\&.
.SS "readonly DependencyProperty Csla\&.Xaml\&.ErrorDialog\&.DialogIconProperty\fC [static]\fP"
\fBInitial value:\fP
.PP
.nf
= DependencyProperty\&.Register(
      "DialogIcon",
      typeof(MessageBoxImage),
      typeof(ErrorDialog),
      null)
.fi
.PP
Gets or sets a value indicating whether the dialog should include exception details or just the exception summary message\&. 
.PP
Definition at line 105 of file ErrorDialog\&.cs\&.
.SS "readonly DependencyProperty Csla\&.Xaml\&.ErrorDialog\&.DialogTitleProperty\fC [static]\fP"
\fBInitial value:\fP
.PP
.nf
= DependencyProperty\&.Register(
      "DialogTitle",
      typeof(string),
      typeof(ErrorDialog),
      null)
.fi
.PP
Gets or sets the title of the error dialog\&. 
.PP
Definition at line 40 of file ErrorDialog\&.cs\&.
.SS "readonly DependencyProperty Csla\&.Xaml\&.ErrorDialog\&.ShowExceptionDetailProperty\fC [static]\fP"
\fBInitial value:\fP
.PP
.nf
= DependencyProperty\&.Register(
      "ShowExceptionDetail",
      typeof(bool),
      typeof(ErrorDialog),
      null)
.fi
.PP
Gets or sets a value indicating whether the dialog should include exception details or just the exception summary message\&. 
.PP
Definition at line 83 of file ErrorDialog\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "string Csla\&.Xaml\&.ErrorDialog\&.DialogFirstLine\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the first line of text displayed within the error dialog (before the exception message)\&. 
.PP
Definition at line 72 of file ErrorDialog\&.cs\&.
.SS "MessageBoxImage Csla\&.Xaml\&.ErrorDialog\&.DialogIcon\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the icon displayed in the dialog\&. 
.PP
Definition at line 115 of file ErrorDialog\&.cs\&.
.SS "string Csla\&.Xaml\&.ErrorDialog\&.DialogTitle\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the title of the error dialog\&. 
.PP
Definition at line 50 of file ErrorDialog\&.cs\&.
.SS "bool Csla\&.Xaml\&.ErrorDialog\&.ShowExceptionDetail\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the first line of text displayed within the error dialog (before the exception message)\&. 
.PP
Definition at line 94 of file ErrorDialog\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
