.TH "Csla.Windows" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Windows
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBApplicationContextManager\fP"
.br
.RI "\fBApplicationContextManager\fP for \fBWindows\fP Forms applications "
.ti -1c
.RI "class \fBBindingSourceHelper\fP"
.br
.RI "Helper methods for dealing with BindingSource objects and data binding\&. "
.ti -1c
.RI "class \fBBindingSourceNode\fP"
.br
.RI "Maintains a reference to a BindingSource object on the form\&. "
.ti -1c
.RI "class \fBBindingSourceRefresh\fP"
.br
.RI "\fBBindingSourceRefresh\fP contains functionality for refreshing the data bound to controls on Host as well as a mechinism for catching data binding errors that occur in Host\&. "
.ti -1c
.RI "class \fBBindingErrorEventArgs\fP"
.br
.RI "\fBBindingErrorEventArgs\fP defines the event arguments for reporting a data binding error due to a exception\&. "
.ti -1c
.RI "class \fBBusyAnimation\fP"
.br
.RI "User control that displays busy animation "
.ti -1c
.RI "class \fBCslaActionCancelEventArgs\fP"
.br
.RI "Event args providing information about a canceled action\&. "
.ti -1c
.RI "class \fBCslaActionEventArgs\fP"
.br
.RI "Event args for an action\&. "
.ti -1c
.RI "class \fBCslaActionExtender\fP"
.br
.RI "Extender control providing automation around data binding to CSLA \&.NET business objects\&. "
.ti -1c
.RI "class \fBCslaActionExtenderProperties\fP"
.br
.ti -1c
.RI "class \fBCslaActionExtenderToolStrip\fP"
.br
.RI "Extender control (for ToolStripButton only) providing automation around data binding to CSLA \&.NET business objects\&. "
.ti -1c
.RI "class \fBErrorEncounteredEventArgs\fP"
.br
.RI "Event args indicating an error\&. "
.ti -1c
.RI "class \fBHasBrokenRulesEventArgs\fP"
.br
.RI "Event args object containing information about a broken rule\&. "
.ti -1c
.RI "class \fBHostPropertyAttribute\fP"
.br
.RI "\fBHostPropertyAttribute\fP is used on components to indicate the property on the component that is to be used as the parent container control in conjunction with HostComponentDesigner\&. "
.ti -1c
.RI "class \fBObjectSaveException\fP"
.br
.RI "Exception indicating a failure during an object save operation\&. "
.ti -1c
.RI "class \fBReadWriteAuthorization\fP"
.br
.RI "\fBWindows\fP Forms extender control that automatically enables and disables detail form controls based on the authorization settings from a CSLA \&.NET business object\&. "
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum class \fBCslaFormAction\fP { \fBNone\fP, \fBSave\fP, \fBCancel\fP, \fBClose\fP, \fBValidate\fP }"
.br
.RI "The possible form actions\&. "
.ti -1c
.RI "enum class \fBPostSaveActionType\fP { \fBNone\fP, \fBAndClose\fP, \fBAndNew\fP }"
.br
.RI "The possible actions for post save\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "delegate void \fBBindingErrorEventHandler\fP (object sender, \fBBindingErrorEventArgs\fP e)"
.br
.RI "BindingErrorEventHandler delegates is the event handling definition for handling data binding errors that occurred due to exceptions\&. "
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBCsla\&.Windows\&.CslaFormAction\fP\fC [strong]\fP"

.PP
The possible form actions\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fINone \fP\fP
No action\&. 
.TP
\fB\fISave \fP\fP
Perform a save\&. 
.TP
\fB\fICancel \fP\fP
Undo changes\&. 
.TP
\fB\fIClose \fP\fP
Close the form\&. 
.TP
\fB\fIValidate \fP\fP
Display a message box with any broken rules 
.PP
Definition at line 13 of file Enums\&.cs\&.
.SS "enum \fBCsla\&.Windows\&.PostSaveActionType\fP\fC [strong]\fP"

.PP
The possible actions for post save\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fINone \fP\fP
No action\&. 
.TP
\fB\fIAndClose \fP\fP
Also close the form\&. 
.TP
\fB\fIAndNew \fP\fP
Also create a new object\&. 
.PP
Definition at line 40 of file Enums\&.cs\&.
.SH "Function Documentation"
.PP 
.SS "delegate void Csla\&.Windows\&.BindingErrorEventHandler (object sender, \fBBindingErrorEventArgs\fP e)"

.PP
BindingErrorEventHandler delegates is the event handling definition for handling data binding errors that occurred due to exceptions\&. 
.PP
\fBParameters\fP
.RS 4
\fIsender\fP The object that triggered the event\&.
.br
\fIe\fP The event arguments\&.
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
