.TH "Csla.Web.InsertObjectArgs" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Web.InsertObjectArgs \- Argument object used in the InsertObject event\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits EventArgs\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBInsertObjectArgs\fP (System\&.Collections\&.IDictionary values)"
.br
.RI "Create an instance of the object\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBRowsAffected\fP\fC [get, set]\fP"
.br
.RI "Gets or sets the number of rows affected while handling this event\&. "
.ti -1c
.RI "System\&.Collections\&.IDictionary \fBValues\fP\fC [get]\fP"
.br
.RI "The list of data values entered by the user\&. "
.in -1c
.SH "Detailed Description"
.PP 
Argument object used in the InsertObject event\&. 


.PP
Definition at line 15 of file InsertObjectArgs\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Csla\&.Web\&.InsertObjectArgs\&.InsertObjectArgs (System\&.Collections\&.IDictionary values)"

.PP
Create an instance of the object\&. 
.PP
Definition at line 53 of file InsertObjectArgs\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "int Csla\&.Web\&.InsertObjectArgs\&.RowsAffected\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the number of rows affected while handling this event\&. 
.PP
\fBReturns\fP
.RS 4

.RE
.PP
.PP
The code handling the event should set this value to indicate the number of rows affected by the operation\&. 
.PP
Definition at line 32 of file InsertObjectArgs\&.cs\&.
.SS "System\&.Collections\&.IDictionary Csla\&.Web\&.InsertObjectArgs\&.Values\fC [get]\fP"

.PP
The list of data values entered by the user\&. It is up to the event handler in the web page to take the list of values, put them into a business object and to save that object into the database\&.
.PP
Definition at line 45 of file InsertObjectArgs\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
