.TH "Csla.Test.DataPortal.DataPortalTests" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.DataPortal.DataPortalTests
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBClearDataBase\fP ()"
.br
.ti -1c
.RI "void \fBTestEnterpriseServicesTransactionalUpdate\fP ()"
.br
.ti -1c
.RI "void \fBStronglyTypedDataPortalMethods\fP ()"
.br
.ti -1c
.RI "void \fBEncapsulatedIsBusyFails\fP ()"
.br
.ti -1c
.RI "void \fBFactoryIsBusyFails\fP ()"
.br
.ti -1c
.RI "void \fBDataPortalEvents\fP ()"
.br
.ti -1c
.RI "void \fBDataPortalBrokerTests\fP ()"
.br
.ti -1c
.RI "void \fBCallDataPortalOverrides\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 29 of file DataPortalTests\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Csla\&.Test\&.DataPortal\&.DataPortalTests\&.CallDataPortalOverrides ()"

.PP
Definition at line 342 of file DataPortalTests\&.cs\&.
.SS "void Csla\&.Test\&.DataPortal\&.DataPortalTests\&.ClearDataBase ()"

.PP
Definition at line 32 of file DataPortalTests\&.cs\&.
.SS "void Csla\&.Test\&.DataPortal\&.DataPortalTests\&.DataPortalBrokerTests ()"

.PP
Definition at line 293 of file DataPortalTests\&.cs\&.
.SS "void Csla\&.Test\&.DataPortal\&.DataPortalTests\&.DataPortalEvents ()"

.PP
Definition at line 265 of file DataPortalTests\&.cs\&.
.SS "void Csla\&.Test\&.DataPortal\&.DataPortalTests\&.EncapsulatedIsBusyFails ()"

.PP
Definition at line 233 of file DataPortalTests\&.cs\&.
.SS "void Csla\&.Test\&.DataPortal\&.DataPortalTests\&.FactoryIsBusyFails ()"

.PP
Definition at line 249 of file DataPortalTests\&.cs\&.
.SS "void Csla\&.Test\&.DataPortal\&.DataPortalTests\&.StronglyTypedDataPortalMethods ()"

.PP
Definition at line 208 of file DataPortalTests\&.cs\&.
.SS "void Csla\&.Test\&.DataPortal\&.DataPortalTests\&.TestEnterpriseServicesTransactionalUpdate ()"

.PP
Definition at line 54 of file DataPortalTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
