.TH "Csla.Axml.Binding" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Axml.Binding
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBinding\fP"
.br
.RI "Contains an individual binding to tie a property on an \fBAxml\fP view to the property on a supplied object\&. "
.ti -1c
.RI "class \fBBindingManager\fP"
.br
.RI "Provides the ability to bing properties on \fBAxml\fP controls to properties on CSLA objects\&. Bindinds update normally when the control looses focus\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
