.TH "Csla.Analyzers.IntegrationTests" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Analyzers.IntegrationTests
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBExecuteWithoutAdd\fP"
.br
.ti -1c
.RI "class \fBExecuteWithAdd\fP"
.br
.ti -1c
.RI "class \fBExecuteWithAddAndNameof\fP"
.br
.ti -1c
.RI "class \fBAsynchronousRuleOldSchool\fP"
.br
.ti -1c
.RI "class \fBAsynchronousRuleNewSchool\fP"
.br
.ti -1c
.RI "class \fBCallingComplete\fP"
.br
.ti -1c
.RI "class \fBCallingCompleteWithNameof\fP"
.br
.ti -1c
.RI "class \fBBusyProperties\fP"
.br
.ti -1c
.RI "class \fBA\fP"
.br
.ti -1c
.RI "class \fBB\fP"
.br
.ti -1c
.RI "class \fBC\fP"
.br
.ti -1c
.RI "class \fBOuterClass\fP"
.br
.ti -1c
.RI "class \fBPrivateConstructorTest\fP"
.br
.ti -1c
.RI "class \fBPublicConstructorWithArgumentsTest\fP"
.br
.ti -1c
.RI "class \fBInternalConstructorTest\fP"
.br
.ti -1c
.RI "class \fBPrivateConstructorTestNoArguments\fP"
.br
.ti -1c
.RI "class \fBPublicConstructorExplicitNoArgumentTest\fP"
.br
.ti -1c
.RI "class \fBPublicConstructorTest\fP"
.br
.ti -1c
.RI "class \fBNotAStereotype\fP"
.br
.ti -1c
.RI "class \fBStaticOperation\fP"
.br
.ti -1c
.RI "class \fBUsedByCallingMethods\fP"
.br
.ti -1c
.RI "class \fBCallingMethods\fP"
.br
.ti -1c
.RI "class \fBOperationReturnValues\fP"
.br
.ti -1c
.RI "class \fBOperationReturnValuesNotCsla\fP"
.br
.ti -1c
.RI "class \fBOperationsAndAttributes\fP"
.br
.ti -1c
.RI "class \fBPropertiesAndRegions\fP"
.br
.ti -1c
.RI "class \fBPropertyDefinitionTests\fP"
.br
.ti -1c
.RI "interface \fBPublicForInterface\fP"
.br
.ti -1c
.RI "class \fBPublicOperation\fP"
.br
.ti -1c
.RI "class \fBRefAndOutOperationParameters\fP"
.br
.ti -1c
.RI "class \fBRunningChildrenLocally\fP"
.br
.ti -1c
.RI "class \fBSerializableArgumentTests\fP"
.br
.ti -1c
.RI "class \fBNonSerializedObject\fP"
.br
.ti -1c
.RI "class \fBSerializedObject\fP"
.br
.ti -1c
.RI "class \fBSomeCriteria\fP"
.br
.ti -1c
.RI "class \fBMyCommandBase\fP"
.br
.ti -1c
.RI "class \fBClassIsStereotypeAndIsNotSerializable\fP"
.br
.ti -1c
.RI "class \fBClassIsNotStereotype\fP"
.br
.ti -1c
.RI "class \fBClassIsStereotypeAndIsSerializable\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
