.TH "Csla.Test.CslaDataProvider.ProviderList" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.CslaDataProvider.ProviderList
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.BusinessBindingListBase< ProviderList, ProviderChild >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBProviderList\fP ()"
.br
.ti -1c
.RI "new \fBProviderList\fP \fBSave\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBProviderList\fP \fBGetList\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override object \fBAddNewCore\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 15 of file ProviderList\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Csla\&.Test\&.CslaDataProvider\&.ProviderList\&.ProviderList ()"

.PP
Definition at line 17 of file ProviderList\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override object Csla\&.Test\&.CslaDataProvider\&.ProviderList\&.AddNewCore ()\fC [protected]\fP"

.PP
Definition at line 32 of file ProviderList\&.cs\&.
.SS "static \fBProviderList\fP Csla\&.Test\&.CslaDataProvider\&.ProviderList\&.GetList ()\fC [static]\fP"

.PP
Definition at line 24 of file ProviderList\&.cs\&.
.SS "new \fBProviderList\fP Csla\&.Test\&.CslaDataProvider\&.ProviderList\&.Save ()"

.PP
Definition at line 40 of file ProviderList\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
