.TH "Csla.Analyzers.Extensions" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Analyzers.Extensions
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBDataPortalOperationQualification\fP"
.br
.ti -1c
.RI "class \fBIMethodSymbolExtensions\fP"
.br
.ti -1c
.RI "class \fBISymbolExtensions\fP"
.br
.ti -1c
.RI "class \fBITypeSymbolExtensions\fP"
.br
.ti -1c
.RI "class \fBSyntaxNodeExtensions\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
