.TH "Csla.Serialization.BinaryFormatterWrapper" 3 "Thu Jul 22 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Serialization.BinaryFormatterWrapper \- Wraps the BinaryFormatter in the \fBISerializationFormatter\fP interface so it can be used in a standardized manner\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.Serialization\&.ISerializationFormatter\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "object \fBDeserialize\fP (System\&.IO\&.Stream serializationStream)"
.br
.RI "Converts a serialization stream into an object graph\&. "
.ti -1c
.RI "object \fBDeserialize\fP (byte[] buffer)"
.br
.RI "Converts a serialization stream into an object graph\&. "
.ti -1c
.RI "void \fBSerialize\fP (System\&.IO\&.Stream serializationStream, object graph)"
.br
.RI "Converts an object graph into a byte stream\&. "
.ti -1c
.RI "byte[] \fBSerialize\fP (object graph)"
.br
.RI "Converts an object graph into a byte stream\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "BinaryFormatter \fBFormatter\fP\fC [get]\fP"
.br
.RI "Gets a reference to the underlying BinaryFormatter object\&. "
.in -1c
.SH "Detailed Description"
.PP 
Wraps the BinaryFormatter in the \fBISerializationFormatter\fP interface so it can be used in a standardized manner\&. 


.PP
Definition at line 21 of file BinaryFormatterWrapper\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "object Csla\&.Serialization\&.BinaryFormatterWrapper\&.Deserialize (byte[] buffer)"

.PP
Converts a serialization stream into an object graph\&. 
.PP
\fBParameters\fP
.RS 4
\fIbuffer\fP Byte stream containing the serialized data\&.
.RE
.PP
\fBReturns\fP
.RS 4
A deserialized object graph\&.
.RE
.PP

.PP
Implements \fBCsla\&.Serialization\&.ISerializationFormatter\fP\&.
.PP
Definition at line 45 of file BinaryFormatterWrapper\&.cs\&.
.SS "object Csla\&.Serialization\&.BinaryFormatterWrapper\&.Deserialize (System\&.IO\&.Stream serializationStream)"

.PP
Converts a serialization stream into an object graph\&. 
.PP
\fBParameters\fP
.RS 4
\fIserializationStream\fP Byte stream containing the serialized data\&.
.RE
.PP
\fBReturns\fP
.RS 4
A deserialized object graph\&.
.RE
.PP

.PP
Implements \fBCsla\&.Serialization\&.ISerializationFormatter\fP\&.
.PP
Definition at line 33 of file BinaryFormatterWrapper\&.cs\&.
.SS "byte [] Csla\&.Serialization\&.BinaryFormatterWrapper\&.Serialize (object graph)"

.PP
Converts an object graph into a byte stream\&. 
.PP
\fBParameters\fP
.RS 4
\fIgraph\fP Object graph to be serialized\&.
.RE
.PP

.PP
Implements \fBCsla\&.Serialization\&.ISerializationFormatter\fP\&.
.PP
Definition at line 66 of file BinaryFormatterWrapper\&.cs\&.
.SS "void Csla\&.Serialization\&.BinaryFormatterWrapper\&.Serialize (System\&.IO\&.Stream serializationStream, object graph)"

.PP
Converts an object graph into a byte stream\&. 
.PP
\fBParameters\fP
.RS 4
\fIserializationStream\fP Stream that will contain the the serialized data\&.
.br
\fIgraph\fP Object graph to be serialized\&.
.RE
.PP

.PP
Implements \fBCsla\&.Serialization\&.ISerializationFormatter\fP\&.
.PP
Definition at line 57 of file BinaryFormatterWrapper\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "BinaryFormatter Csla\&.Serialization\&.BinaryFormatterWrapper\&.Formatter\fC [get]\fP"

.PP
Gets a reference to the underlying BinaryFormatter object\&. 
.PP
Definition at line 79 of file BinaryFormatterWrapper\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
