.TH "Csla.AspNetCore" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.AspNetCore
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBMvc\fP"
.br
.ti -1c
.RI "namespace \fBRazorPages\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBApplicationContextManager\fP"
.br
.RI "Application context manager that uses HttpContextAccessor when resolving HttpContext to store context values\&. "
.ti -1c
.RI "class \fBPropertyInfo\fP"
.br
.RI "Exposes metastate for a property\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
