.TH "Csla.Configuration.ConfigurationErrorsException" 3 "Thu Jul 22 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Configuration.ConfigurationErrorsException \- Exception thrown due to configuration errors\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Exception\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBConfigurationErrorsException\fP ()"
.br
.RI "Creates an instance of the object\&. "
.ti -1c
.RI "\fBConfigurationErrorsException\fP (string message)"
.br
.RI "Creates an instance of the object\&. "
.ti -1c
.RI "\fBConfigurationErrorsException\fP (string message, Exception innerException)"
.br
.RI "Creates an instance of the object\&. "
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBConfigurationErrorsException\fP (System\&.Runtime\&.Serialization\&.SerializationInfo info, System\&.Runtime\&.Serialization\&.StreamingContext context)"
.br
.RI "Creates an instance of the object for serialization\&. "
.in -1c
.SH "Detailed Description"
.PP 
Exception thrown due to configuration errors\&. 


.PP
Definition at line 16 of file ConfigurationErrorsException\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Csla\&.Configuration\&.ConfigurationErrorsException\&.ConfigurationErrorsException ()"

.PP
Creates an instance of the object\&. 
.PP
Definition at line 21 of file ConfigurationErrorsException\&.cs\&.
.SS "Csla\&.Configuration\&.ConfigurationErrorsException\&.ConfigurationErrorsException (string message)"

.PP
Creates an instance of the object\&. 
.PP
\fBParameters\fP
.RS 4
\fImessage\fP Message describing the exception\&.
.RE
.PP

.PP
Definition at line 30 of file ConfigurationErrorsException\&.cs\&.
.SS "Csla\&.Configuration\&.ConfigurationErrorsException\&.ConfigurationErrorsException (string message, Exception innerException)"

.PP
Creates an instance of the object\&. 
.PP
\fBParameters\fP
.RS 4
\fImessage\fP Message describing the exception\&.
.br
\fIinnerException\fP Inner exception object\&.
.RE
.PP

.PP
Definition at line 41 of file ConfigurationErrorsException\&.cs\&.
.SS "Csla\&.Configuration\&.ConfigurationErrorsException\&.ConfigurationErrorsException (System\&.Runtime\&.Serialization\&.SerializationInfo info, System\&.Runtime\&.Serialization\&.StreamingContext context)\fC [protected]\fP"

.PP
Creates an instance of the object for serialization\&. 
.PP
\fBParameters\fP
.RS 4
\fIcontext\fP \fBSerialization\fP context\&.
.br
\fIinfo\fP \fBSerialization\fP info\&.
.RE
.PP

.PP
Definition at line 52 of file ConfigurationErrorsException\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
