.TH "Csla.Test.SortedBindingList.SortedBindingListTests" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.SortedBindingList.SortedBindingListTests
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBAscendingSort\fP ()"
.br
.ti -1c
.RI "void \fBsortedList_ListChanged\fP (object sender, ListChangedEventArgs e)"
.br
.ti -1c
.RI "void \fBDescendingSort\fP ()"
.br
.ti -1c
.RI "void \fBCopyTo\fP ()"
.br
.ti -1c
.RI "void \fBIndexOf\fP ()"
.br
.ti -1c
.RI "void \fBSourceList\fP ()"
.br
.ti -1c
.RI "void \fBApplySort_ThrowException_WhenPropertyNameNotFound\fP ()"
.br
.ti -1c
.RI "void \fBFind_ThrowException_WhenPropertyNameNotFound\fP ()"
.br
.ti -1c
.RI "void \fBSimulateDataBindingAdd\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 26 of file SortedBindingListTests\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Csla\&.Test\&.SortedBindingList\&.SortedBindingListTests\&.ApplySort_ThrowException_WhenPropertyNameNotFound ()"

.PP
Definition at line 184 of file SortedBindingListTests\&.cs\&.
.SS "void Csla\&.Test\&.SortedBindingList\&.SortedBindingListTests\&.AscendingSort ()"

.PP
Definition at line 29 of file SortedBindingListTests\&.cs\&.
.SS "void Csla\&.Test\&.SortedBindingList\&.SortedBindingListTests\&.CopyTo ()"

.PP
Definition at line 123 of file SortedBindingListTests\&.cs\&.
.SS "void Csla\&.Test\&.SortedBindingList\&.SortedBindingListTests\&.DescendingSort ()"

.PP
Definition at line 67 of file SortedBindingListTests\&.cs\&.
.SS "void Csla\&.Test\&.SortedBindingList\&.SortedBindingListTests\&.Find_ThrowException_WhenPropertyNameNotFound ()"

.PP
Definition at line 193 of file SortedBindingListTests\&.cs\&.
.SS "void Csla\&.Test\&.SortedBindingList\&.SortedBindingListTests\&.IndexOf ()"

.PP
Definition at line 147 of file SortedBindingListTests\&.cs\&.
.SS "void Csla\&.Test\&.SortedBindingList\&.SortedBindingListTests\&.SimulateDataBindingAdd ()"

.PP
Definition at line 201 of file SortedBindingListTests\&.cs\&.
.SS "void Csla\&.Test\&.SortedBindingList\&.SortedBindingListTests\&.sortedList_ListChanged (object sender, ListChangedEventArgs e)"

.PP
Definition at line 60 of file SortedBindingListTests\&.cs\&.
.SS "void Csla\&.Test\&.SortedBindingList\&.SortedBindingListTests\&.SourceList ()"

.PP
Definition at line 167 of file SortedBindingListTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
