.TH "Csla.Testing.Business.ApplicationContext.GlobalContextBOVerifier" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Testing.Business.ApplicationContext.GlobalContextBOVerifier
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.Testing\&.Business\&.ApplicationContext\&.ContextBOVerifier< GlobalContextBOVerifier >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGlobalContextBOVerifier\fP (bool isNew)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBDataPortal_Insert\fP ()"
.br
.ti -1c
.RI "void \fBDataPortal_Update\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 46 of file ContextBOVerifier\&.server\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Csla\&.Testing\&.Business\&.ApplicationContext\&.GlobalContextBOVerifier\&.GlobalContextBOVerifier (bool isNew)"

.PP
Definition at line 48 of file ContextBOVerifier\&.server\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Csla\&.Testing\&.Business\&.ApplicationContext\&.GlobalContextBOVerifier\&.DataPortal_Insert ()\fC [protected]\fP"

.PP
Definition at line 51 of file ContextBOVerifier\&.server\&.cs\&.
.SS "void Csla\&.Testing\&.Business\&.ApplicationContext\&.GlobalContextBOVerifier\&.DataPortal_Update ()\fC [protected]\fP"

.PP
Definition at line 59 of file ContextBOVerifier\&.server\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
