.TH "Csla.Server.Hosts.Mobile.IMobileFactoryLoader" 3 "Thu Jul 22 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Server.Hosts.Mobile.IMobileFactoryLoader \- Defines an interface to be implemented by a factory object that returns MobileFactory objects based on the MobileFactory attributes used to decorate CSLA Light business objects\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBCsla\&.Server\&.Hosts\&.Mobile\&.MobileFactoryLoader\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "object \fBGetFactory\fP (string factoryName)"
.br
.RI "Returns a MobileFactory object\&. "
.in -1c
.SH "Detailed Description"
.PP 
Defines an interface to be implemented by a factory object that returns MobileFactory objects based on the MobileFactory attributes used to decorate CSLA Light business objects\&. 


.PP
Definition at line 21 of file IMobileFactoryLoader\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "object Csla\&.Server\&.Hosts\&.Mobile\&.IMobileFactoryLoader\&.GetFactory (string factoryName)"

.PP
Returns a MobileFactory object\&. 
.PP
\fBParameters\fP
.RS 4
\fIfactoryName\fP Name of the factory to create, typically an assembly qualified type name\&. 
.RE
.PP

.PP
Implemented in \fBCsla\&.Server\&.Hosts\&.Mobile\&.MobileFactoryLoader\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
