.TH "Csla.Analyzers" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Analyzers
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBExtensions\fP"
.br
.ti -1c
.RI "namespace \fBIntegrationTests\fP"
.br
.ti -1c
.RI "namespace \fBTests\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAsynchronousBusinessRuleInheritingFromBusinessRuleAnalyzer\fP"
.br
.ti -1c
.RI "class \fBAsynchronousBusinessRuleInheritingFromBusinessRuleAnalyzerConstants\fP"
.br
.ti -1c
.RI "class \fBAsynchronousBusinessRuleInheritingFromBusinessRuleChangeToBusinessRuleAsyncCodeFixConstants\fP"
.br
.ti -1c
.RI "class \fBAsynchronousBusinessRuleInheritingFromBusinessRuleChangeToBusinessRuleAsyncCodeFix\fP"
.br
.ti -1c
.RI "class \fBBusinessRuleDoesNotUseAddMethodsOnContextAnalyzer\fP"
.br
.ti -1c
.RI "class \fBBusinessRuleDoesNotUseAddMethodsOnContextAnalyzerConstants\fP"
.br
.ti -1c
.RI "class \fBCheckConstructorsAnalyzer\fP"
.br
.ti -1c
.RI "class \fBPublicNoArgumentConstructorIsMissingConstants\fP"
.br
.ti -1c
.RI "class \fBConstructorHasParametersConstants\fP"
.br
.ti -1c
.RI "class \fBFindBusinessObjectCreationConstants\fP"
.br
.ti -1c
.RI "class \fBCheckConstructorsAnalyzerPublicConstructorCodeFixConstants\fP"
.br
.ti -1c
.RI "class \fBCheckConstructorsAnalyzerPublicConstructorCodeFix\fP"
.br
.ti -1c
.RI "class \fBConstants\fP"
.br
.ti -1c
.RI "class \fBContainsInvocationExpressionWalker\fP"
.br
.ti -1c
.RI "class \fBCslaMemberConstants\fP"
.br
.ti -1c
.RI "class \fBDoesChildOperationHaveRunLocalAnalyzer\fP"
.br
.ti -1c
.RI "class \fBDoesChildOperationHaveRunLocalAnalyzerConstants\fP"
.br
.ti -1c
.RI "class \fBDoesChildOperationHaveRunLocalRemoveAttributeCodeFixConstants\fP"
.br
.ti -1c
.RI "class \fBDoesChildOperationHaveRunLocalRemoveAttributeCodeFix\fP"
.br
.ti -1c
.RI "class \fBDoesOperationHaveAttributeAddAttributeCodeFix\fP"
.br
.ti -1c
.RI "class \fBDoesOperationHaveAttributeAnalyzer\fP"
.br
.ti -1c
.RI "class \fBDoesOperationHaveAttributeAnalyzerConstants\fP"
.br
.ti -1c
.RI "class \fBDoesOperationHaveAttributeAnalyzerAddAttributeCodeFixConstants\fP"
.br
.ti -1c
.RI "class \fBEvaluateManagedBackingFieldsAnalayzer\fP"
.br
.ti -1c
.RI "class \fBEvaluateManagedBackingFieldsAnalayzerConstants\fP"
.br
.ti -1c
.RI "class \fBEvaluateManagedBackingFieldsCodeFixConstants\fP"
.br
.ti -1c
.RI "class \fBEvaluateManagedBackingFieldsCodeFix\fP"
.br
.ti -1c
.RI "class \fBEvaluateManagedBackingFieldsWalker\fP"
.br
.ti -1c
.RI "class \fBEvaluateOperationAttributeUsageAnalyzer\fP"
.br
.ti -1c
.RI "class \fBEvaluateOperationAttributeUsageAnalyzerConstants\fP"
.br
.ti -1c
.RI "class \fBEvaluatePropertiesForSimplicityAnalyzer\fP"
.br
.ti -1c
.RI "class \fBOnlyUseCslaPropertyMethodsInGetSetRuleConstants\fP"
.br
.ti -1c
.RI "class \fBFindBusinessObjectCreationAnalyzer\fP"
.br
.ti -1c
.RI "class \fBFindGetOrReadInvocationsWalker\fP"
.br
.ti -1c
.RI "class \fBFindOperationsWithIncorrectReturnTypeResolveCorrectTypeCodeFix\fP"
.br
.ti -1c
.RI "class \fBFindOperationsWithIncorrectReturnTypesAnalyzer\fP"
.br
.ti -1c
.RI "class \fBFindOperationsWithIncorrectReturnTypesAnalyzerConstants\fP"
.br
.ti -1c
.RI "class \fBFindOperationsWithIncorrectReturnTypeResolveCorrectTypeCodeFixConstants\fP"
.br
.ti -1c
.RI "class \fBFindOperationsWithNonSerializableArgumentsAnalyzer\fP"
.br
.ti -1c
.RI "class \fBFindOperationsWithNonSerializableArgumentsConstants\fP"
.br
.ti -1c
.RI "class \fBFindRefAndOutParametersInOperationsAnalyzer\fP"
.br
.ti -1c
.RI "class \fBFindRefAndOutParametersInOperationsAnalyzerConstants\fP"
.br
.ti -1c
.RI "class \fBFindSaveAssignmentIssueAnalyzer\fP"
.br
.ti -1c
.RI "class \fBFindSaveAssignmentIssueAnalyzerAddAssignmentCodeFix\fP"
.br
.ti -1c
.RI "class \fBFindSaveAssignmentIssueAnalyzerAddAsyncAssignmentCodeFix\fP"
.br
.ti -1c
.RI "class \fBFindSaveAssignmentIssueAnalyzerConstants\fP"
.br
.ti -1c
.RI "class \fBFindSaveAsyncAssignmentIssueAnalyzerConstants\fP"
.br
.ti -1c
.RI "class \fBFindSaveAssignmentIssueAnalyzerAddAssignmentCodeFixConstants\fP"
.br
.ti -1c
.RI "class \fBFindSaveAssignmentIssueAnalyzerAddAsyncAssignmentCodeFixConstants\fP"
.br
.ti -1c
.RI "class \fBFindSetOrLoadInvocationsWalker\fP"
.br
.ti -1c
.RI "class \fBHelpUrlBuilder\fP"
.br
.ti -1c
.RI "class \fBIsBusinessObjectSerializableAnalyzer\fP"
.br
.ti -1c
.RI "class \fBIsBusinessObjectSerializableConstants\fP"
.br
.ti -1c
.RI "class \fBIsBusinessObjectSerializableMakeSerializableCodeFixConstants\fP"
.br
.ti -1c
.RI "class \fBIsBusinessObjectSerializableMakeSerializableCodeFix\fP"
.br
.ti -1c
.RI "class \fBIsCompleteCalledInAsynchronousBusinessRuleAnalyzer\fP"
.br
.ti -1c
.RI "class \fBIsCompleteCalledInAsynchronousBusinessRuleConstants\fP"
.br
.ti -1c
.RI "class \fBIsCompleteCalledInAsynchronousBusinessRuleCodeFixConstants\fP"
.br
.ti -1c
.RI "class \fBIsCompleteCalledInAsynchronousBusinessRuleRemoveCallCodeFix\fP"
.br
.ti -1c
.RI "class \fBIsOperationMethodPublicAnalyzer\fP"
.br
.ti -1c
.RI "class \fBIsOperationMethodPublicAnalyzerConstants\fP"
.br
.ti -1c
.RI "class \fBIsOperationMethodPublicAnalyzerMakeNonPublicCodeFixConstants\fP"
.br
.ti -1c
.RI "class \fBIsOperationMethodPublicMakeNonPublicCodeFix\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
