.TH "Csla.Security.IAuthorizeReadWrite" 3 "Thu Jul 22 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Security.IAuthorizeReadWrite \- Defines the authorization interface through which an object can indicate which properties the current user can read and write\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBCsla\&.Core\&.BusinessBase\fP, \fBCsla\&.IBusinessBase\fP, \fBCsla\&.IReadOnlyBase\fP, and \fBCsla\&.ReadOnlyBase< T >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBCanWriteProperty\fP (string propertyName)"
.br
.RI "Returns true if the user is allowed to write the to the specified property\&. "
.ti -1c
.RI "bool \fBCanWriteProperty\fP (\fBCsla\&.Core\&.IPropertyInfo\fP property)"
.br
.RI "Returns true if the user is allowed to write the to the specified property\&. "
.ti -1c
.RI "bool \fBCanReadProperty\fP (string propertyName)"
.br
.RI "Returns true if the user is allowed to read the specified property\&. "
.ti -1c
.RI "bool \fBCanReadProperty\fP (\fBCsla\&.Core\&.IPropertyInfo\fP property)"
.br
.RI "Returns true if the user is allowed to read the specified property\&. "
.ti -1c
.RI "bool \fBCanExecuteMethod\fP (string methodName)"
.br
.RI "Returns true if the user is allowed to execute the specified method\&. "
.ti -1c
.RI "bool \fBCanExecuteMethod\fP (\fBCsla\&.Core\&.IMemberInfo\fP method)"
.br
.RI "Returns true if the user is allowed to execute the specified method\&. "
.in -1c
.SH "Detailed Description"
.PP 
Defines the authorization interface through which an object can indicate which properties the current user can read and write\&. 


.PP
Definition at line 17 of file IAuthorizeReadWrite\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "bool Csla\&.Security\&.IAuthorizeReadWrite\&.CanExecuteMethod (\fBCsla\&.Core\&.IMemberInfo\fP method)"

.PP
Returns true if the user is allowed to execute the specified method\&. 
.PP
\fBReturns\fP
.RS 4
true if execute is allowed\&.
.RE
.PP
\fBParameters\fP
.RS 4
\fImethod\fP Method to execute\&.
.RE
.PP

.SS "bool Csla\&.Security\&.IAuthorizeReadWrite\&.CanExecuteMethod (string methodName)"

.PP
Returns true if the user is allowed to execute the specified method\&. 
.PP
\fBReturns\fP
.RS 4
true if execute is allowed\&.
.RE
.PP
\fBParameters\fP
.RS 4
\fImethodName\fP Name of the method to execute\&.
.RE
.PP

.PP
Implemented in \fBCsla\&.ReadOnlyBase< T >\fP, and \fBCsla\&.Core\&.BusinessBase\fP\&.
.SS "bool Csla\&.Security\&.IAuthorizeReadWrite\&.CanReadProperty (\fBCsla\&.Core\&.IPropertyInfo\fP property)"

.PP
Returns true if the user is allowed to read the specified property\&. 
.PP
\fBReturns\fP
.RS 4
true if read is allowed\&.
.RE
.PP
\fBParameters\fP
.RS 4
\fIproperty\fP Property to read\&.
.RE
.PP

.SS "bool Csla\&.Security\&.IAuthorizeReadWrite\&.CanReadProperty (string propertyName)"

.PP
Returns true if the user is allowed to read the specified property\&. 
.PP
\fBReturns\fP
.RS 4
true if read is allowed\&.
.RE
.PP
\fBParameters\fP
.RS 4
\fIpropertyName\fP Name of the property to read\&.
.RE
.PP

.PP
Implemented in \fBCsla\&.ReadOnlyBase< T >\fP, and \fBCsla\&.Core\&.BusinessBase\fP\&.
.SS "bool Csla\&.Security\&.IAuthorizeReadWrite\&.CanWriteProperty (\fBCsla\&.Core\&.IPropertyInfo\fP property)"

.PP
Returns true if the user is allowed to write the to the specified property\&. 
.PP
\fBReturns\fP
.RS 4
true if write is allowed\&.
.RE
.PP
\fBParameters\fP
.RS 4
\fIproperty\fP Property to write\&.
.RE
.PP

.SS "bool Csla\&.Security\&.IAuthorizeReadWrite\&.CanWriteProperty (string propertyName)"

.PP
Returns true if the user is allowed to write the to the specified property\&. 
.PP
\fBReturns\fP
.RS 4
true if write is allowed\&.
.RE
.PP
\fBParameters\fP
.RS 4
\fIpropertyName\fP Name of the property to write\&.
.RE
.PP

.PP
Implemented in \fBCsla\&.Core\&.BusinessBase\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
