.TH "Csla.Test.DataPortal.MultipleDataAccessBase< T >" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.DataPortal.MultipleDataAccessBase< T >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.BusinessBase< T >\fP\&.
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static readonly \fBPropertyInfo\fP< int > \fBIdProperty\fP = RegisterProperty<int>(c => c\&.Id)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBFetch\fP ()"
.br
.ti -1c
.RI "void \fBFetch\fP (int id)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBId\fP\fC [get, set]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
\fBType Constraints\fP
.TP
\fIT\fP : \fI\fBMultipleDataAccessBase\fP<T>\fP
.PP
Definition at line 10 of file MultipleDataAccessBase\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void \fBCsla\&.Test\&.DataPortal\&.MultipleDataAccessBase\fP< T >\&.Fetch ()\fC [protected]\fP"

.PP
Definition at line 22 of file MultipleDataAccessBase\&.cs\&.
.SS "void \fBCsla\&.Test\&.DataPortal\&.MultipleDataAccessBase\fP< T >\&.Fetch (int id)\fC [protected]\fP"

.PP
Definition at line 31 of file MultipleDataAccessBase\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "readonly \fBPropertyInfo\fP<int> \fBCsla\&.Test\&.DataPortal\&.MultipleDataAccessBase\fP< T >\&.IdProperty = RegisterProperty<int>(c => c\&.Id)\fC [static]\fP"

.PP
Definition at line 14 of file MultipleDataAccessBase\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "int \fBCsla\&.Test\&.DataPortal\&.MultipleDataAccessBase\fP< T >\&.Id\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 15 of file MultipleDataAccessBase\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
