.TH "Csla.Test.Authorization.PerTypeAuthorization" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.Authorization.PerTypeAuthorization
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.BusinessBase< PerTypeAuthorization >\fP\&.
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBPropertyInfo\fP< string > \fBTestProperty\fP = RegisterProperty<string>(c => c\&.Test)"
.br
.ti -1c
.RI "static \fBPropertyInfo\fP< string > \fBNameProperty\fP = RegisterProperty<string>(c => c\&.Name)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBAddBusinessRules\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBTest\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBName\fP\fC [get, set]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 18 of file PerTypeAuthClasses\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override void Csla\&.Test\&.Authorization\&.PerTypeAuthorization\&.AddBusinessRules ()\fC [protected]\fP"

.PP
Definition at line 34 of file PerTypeAuthClasses\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBPropertyInfo\fP<string> Csla\&.Test\&.Authorization\&.PerTypeAuthorization\&.NameProperty = RegisterProperty<string>(c => c\&.Name)\fC [static]\fP"

.PP
Definition at line 27 of file PerTypeAuthClasses\&.cs\&.
.SS "\fBPropertyInfo\fP<string> Csla\&.Test\&.Authorization\&.PerTypeAuthorization\&.TestProperty = RegisterProperty<string>(c => c\&.Test)\fC [static]\fP"

.PP
Definition at line 20 of file PerTypeAuthClasses\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "string Csla\&.Test\&.Authorization\&.PerTypeAuthorization\&.Name\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 28 of file PerTypeAuthClasses\&.cs\&.
.SS "string Csla\&.Test\&.Authorization\&.PerTypeAuthorization\&.Test\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 21 of file PerTypeAuthClasses\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
