.TH "Csla.Test.DataPortal.TestInterceptor" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.DataPortal.TestInterceptor
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.Server\&.IInterceptDataPortal\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBInitialize\fP (\fBServer\&.InterceptArgs\fP e)"
.br
.ti -1c
.RI "void \fBComplete\fP (\fBServer\&.InterceptArgs\fP e)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 222 of file InterceptorTests\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Csla\&.Test\&.DataPortal\&.TestInterceptor\&.Complete (\fBServer\&.InterceptArgs\fP e)"

.PP
Definition at line 230 of file InterceptorTests\&.cs\&.
.SS "void Csla\&.Test\&.DataPortal\&.TestInterceptor\&.Initialize (\fBServer\&.InterceptArgs\fP e)"

.PP
Definition at line 224 of file InterceptorTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
