.TH "cslalighttest.CommandBase.CommandBaseTests" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cslalighttest.CommandBase.CommandBaseTests
.SH SYNOPSIS
.br
.PP
.PP
Inherits TestBase\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "async Task \fBAsynch_Remote_call_wo_userState_passed_Results_parameters_passed_to_server_and_noException\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 28 of file CommandBaseTests\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "async Task cslalighttest\&.CommandBase\&.CommandBaseTests\&.Asynch_Remote_call_wo_userState_passed_Results_parameters_passed_to_server_and_noException ()"

.PP
Definition at line 37 of file CommandBaseTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
