.TH "Csla.Core.AddedNewEventArgs< T >" 3 "Thu Jul 22 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Core.AddedNewEventArgs< T > \- Object containing information about a newly added object\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits EventArgs\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAddedNewEventArgs\fP ()"
.br
.RI "Creates a new instance of the object\&. "
.ti -1c
.RI "\fBAddedNewEventArgs\fP (T newObject)"
.br
.RI "Creates a new instance of the object\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "T \fBNewObject\fP\fC [get, protected set]\fP"
.br
.RI "Gets a reference to the newly added object\&. "
.in -1c
.SH "Detailed Description"
.PP 
Object containing information about a newly added object\&. 


.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP Type of the object that was added\&. 
.RE
.PP

.PP
Definition at line 19 of file AddedNewEventArgs\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBCsla\&.Core\&.AddedNewEventArgs\fP< T >\&.\fBAddedNewEventArgs\fP ()"

.PP
Creates a new instance of the object\&. 
.PP
Definition at line 30 of file AddedNewEventArgs\&.cs\&.
.SS "\fBCsla\&.Core\&.AddedNewEventArgs\fP< T >\&.\fBAddedNewEventArgs\fP (T newObject)"

.PP
Creates a new instance of the object\&. 
.PP
\fBParameters\fP
.RS 4
\fInewObject\fP The newly added object\&. 
.RE
.PP

.PP
Definition at line 38 of file AddedNewEventArgs\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "T \fBCsla\&.Core\&.AddedNewEventArgs\fP< T >\&.NewObject\fC [get]\fP, \fC [protected set]\fP"

.PP
Gets a reference to the newly added object\&. 
.PP
Definition at line 25 of file AddedNewEventArgs\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
