.TH "Csla.Core.MobileBindingList< T >" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Core.MobileBindingList< T > \- Inherit from this base class to easily create a serializable list class\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits BindingList< T >, and \fBCsla\&.Serialization\&.Mobile\&.IMobileList\fP\&.
.PP
Inherited by \fBCsla\&.Core\&.ExtendedBindingList< T >\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBLoadListModeObject\fP"
.br
.RI "Class that allows setting of property values on current business object without raising PropertyChanged events and checking user rights\&. "
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBSetLoadListMode\fP (bool enabled)"
.br
.RI "Sets the load list mode for the list "
.ti -1c
.RI "virtual void \fBOnGetState\fP (\fBSerializationInfo\fP info)"
.br
.RI "Override this method to get custom field values from the serialization stream\&. "
.ti -1c
.RI "virtual void \fBOnGetChildren\fP (\fBSerializationInfo\fP info, \fBMobileFormatter\fP formatter)"
.br
.RI "Override this method to get custom child object values from the serialization stream\&. "
.ti -1c
.RI "virtual void \fBOnSetState\fP (\fBSerializationInfo\fP info)"
.br
.RI "Override this method to set custom field values into the serialization stream\&. "
.ti -1c
.RI "virtual void \fBOnSetChildren\fP (\fBSerializationInfo\fP info, \fBMobileFormatter\fP formatter)"
.br
.RI "Override this method to set custom child object values into the serialization stream\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBLoadListModeObject\fP \fBLoadListMode\fP\fC [get]\fP"
.br
.RI "By wrapping this property inside Using block you can set property values on current business object without raising PropertyChanged events and checking user rights\&. "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Inherit from this base class to easily create a serializable list class\&. 


.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP Type of the items contained in the list\&. 
.RE
.PP

.PP
Definition at line 30 of file MobileBindingList\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual void \fBCsla\&.Core\&.MobileBindingList\fP< T >\&.OnGetChildren (\fBSerializationInfo\fP info, \fBMobileFormatter\fP formatter)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Override this method to get custom child object values from the serialization stream\&. 
.PP
\fBParameters\fP
.RS 4
\fIinfo\fP \fBSerialization\fP info\&.
.br
\fIformatter\fP Reference to the SerializationFormatterFactory\&.GetFormatter()\&.
.RE
.PP

.PP
Definition at line 159 of file MobileBindingList\&.cs\&.
.SS "virtual void \fBCsla\&.Core\&.MobileBindingList\fP< T >\&.OnGetState (\fBSerializationInfo\fP info)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Override this method to get custom field values from the serialization stream\&. 
.PP
\fBParameters\fP
.RS 4
\fIinfo\fP \fBSerialization\fP info\&.
.RE
.PP

.PP
Reimplemented in \fBCsla\&.DynamicBindingListBase< T >\fP\&.
.PP
Definition at line 141 of file MobileBindingList\&.cs\&.
.SS "virtual void \fBCsla\&.Core\&.MobileBindingList\fP< T >\&.OnSetChildren (\fBSerializationInfo\fP info, \fBMobileFormatter\fP formatter)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Override this method to set custom child object values into the serialization stream\&. 
.PP
\fBParameters\fP
.RS 4
\fIinfo\fP \fBSerialization\fP info\&.
.br
\fIformatter\fP Reference to the SerializationFormatterFactory\&.GetFormatter()\&.
.RE
.PP

.PP
Definition at line 209 of file MobileBindingList\&.cs\&.
.SS "virtual void \fBCsla\&.Core\&.MobileBindingList\fP< T >\&.OnSetState (\fBSerializationInfo\fP info)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Override this method to set custom field values into the serialization stream\&. 
.PP
\fBParameters\fP
.RS 4
\fIinfo\fP \fBSerialization\fP info\&.
.RE
.PP

.PP
Reimplemented in \fBCsla\&.DynamicBindingListBase< T >\fP\&.
.PP
Definition at line 194 of file MobileBindingList\&.cs\&.
.SS "virtual void \fBCsla\&.Core\&.MobileBindingList\fP< T >\&.SetLoadListMode (bool enabled)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Sets the load list mode for the list 
.PP
\fBParameters\fP
.RS 4
\fIenabled\fP Enabled value
.RE
.PP

.PP
Implements \fBCsla\&.Serialization\&.Mobile\&.IMobileList\fP\&.
.PP
Definition at line 83 of file MobileBindingList\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "\fBLoadListModeObject\fP \fBCsla\&.Core\&.MobileBindingList\fP< T >\&.LoadListMode\fC [get]\fP, \fC [protected]\fP"

.PP
By wrapping this property inside Using block you can set property values on current business object without raising PropertyChanged events and checking user rights\&. 
.PP
Definition at line 45 of file MobileBindingList\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
