.TH "Csla.Serialization.Mobile.CslaBinaryWriter" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Serialization.Mobile.CslaBinaryWriter \- This is a class that is responsible for serializing \fBSerializationInfo\fP objects into a Stream for sending the data t client / server  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.Serialization\&.Mobile\&.ICslaWriter\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCslaBinaryWriter\fP ()"
.br
.RI "Create new instance of \fBCslaBinaryWriter\fP class "
.ti -1c
.RI "void \fBWrite\fP (Stream serializationStream, List< \fBSerializationInfo\fP > objectData)"
.br
.RI "Write a list of \fBSerializationInfo\fP objects into stream, typically MemoryStream\&. "
.in -1c
.SH "Detailed Description"
.PP 
This is a class that is responsible for serializing \fBSerializationInfo\fP objects into a Stream for sending the data t client / server 


.PP
Definition at line 13 of file CslaBinaryWriter\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Csla\&.Serialization\&.Mobile\&.CslaBinaryWriter\&.CslaBinaryWriter ()"

.PP
Create new instance of \fBCslaBinaryWriter\fP class 
.PP
Definition at line 20 of file CslaBinaryWriter\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Csla\&.Serialization\&.Mobile\&.CslaBinaryWriter\&.Write (Stream serializationStream, List< \fBSerializationInfo\fP > objectData)"

.PP
Write a list of \fBSerializationInfo\fP objects into stream, typically MemoryStream\&. 
.PP
\fBParameters\fP
.RS 4
\fIserializationStream\fP Stream to write the data into
.br
\fIobjectData\fP List of \fBSerializationInfo\fP objects to write to stream
.RE
.PP

.PP
Implements \fBCsla\&.Serialization\&.Mobile\&.ICslaWriter\fP\&.
.PP
Definition at line 31 of file CslaBinaryWriter\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
