.TH "Csla.Data.ServiceClientManager< C, T >" 3 "Thu Jul 22 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Data.ServiceClientManager< C, T > \- Provides an automated way to reuse a service client proxy objects within the context of a single data portal operation\&.  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBServiceClientManager\fP< C, T > \fBGetManager\fP (string name)"
.br
.RI "Gets the client proxy object for the specified name\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "C \fBClient\fP\fC [get]\fP"
.br
.RI "Gets a reference to the current client proxy object\&. "
.in -1c
.SH "Detailed Description"
.PP 
Provides an automated way to reuse a service client proxy objects within the context of a single data portal operation\&. 


.PP
\fBTemplate Parameters\fP
.RS 4
\fIC\fP Type of ClientBase object to use\&. 
.br
\fIT\fP Channel type for the ClientBase object\&. 
.RE
.PP

.PP
\fBType Constraints\fP
.TP
\fIC\fP : \fISystem\&.ServiceModel\&.ClientBase<T>\fP
.TP
\fIT\fP : \fIclass\fP
.PP
Definition at line 24 of file ServiceClientManager\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "static \fBServiceClientManager\fP<C,T > \fBCsla\&.Data\&.ServiceClientManager\fP< C, T >\&.GetManager (string name)\fC [static]\fP"

.PP
Gets the client proxy object for the specified name\&. 
.PP
\fBParameters\fP
.RS 4
\fIname\fP Unique name for the proxy object\&.
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
Definition at line 38 of file ServiceClientManager\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "C \fBCsla\&.Data\&.ServiceClientManager\fP< C, T >\&.Client\fC [get]\fP"

.PP
Gets a reference to the current client proxy object\&. 
.PP
Definition at line 62 of file ServiceClientManager\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
