.TH "Csla.Test.RollBack.RollbackRoot" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.RollBack.RollbackRoot
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.BusinessBase< RollbackRoot >\fP\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBRollbackRoot\fP \fBNewRoot\fP ()"
.br
.ti -1c
.RI "static \fBRollbackRoot\fP \fBGetRoot\fP (string data)"
.br
.ti -1c
.RI "static void \fBDeleteRoot\fP (string data)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override object \fBGetIdValue\fP ()"
.br
.RI "Override this method to return a unique identifying value for this object\&. "
.ti -1c
.RI "void \fBDataPortal_Fetch\fP (object criteria)"
.br
.ti -1c
.RI "void \fBDataPortal_Insert\fP ()"
.br
.ti -1c
.RI "void \fBDataPortal_Update\fP ()"
.br
.ti -1c
.RI "void \fBDataPortal_DeleteSelf\fP ()"
.br
.ti -1c
.RI "void \fBDataPortal_Delete\fP (object criteria)"
.br
.ti -1c
.RI "override void \fBOnDeserialized\fP (System\&.Runtime\&.Serialization\&.StreamingContext context)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBData\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "bool \fBFail\fP\fC [get, set]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 15 of file RollBack/RollbackRoot\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Csla\&.Test\&.RollBack\&.RollbackRoot\&.DataPortal_Delete (object criteria)\fC [protected]\fP"

.PP
Definition at line 120 of file RollBack/RollbackRoot\&.cs\&.
.SS "void Csla\&.Test\&.RollBack\&.RollbackRoot\&.DataPortal_DeleteSelf ()\fC [protected]\fP"

.PP
Definition at line 114 of file RollBack/RollbackRoot\&.cs\&.
.SS "void Csla\&.Test\&.RollBack\&.RollbackRoot\&.DataPortal_Fetch (object criteria)\fC [protected]\fP"

.PP
Definition at line 89 of file RollBack/RollbackRoot\&.cs\&.
.SS "void Csla\&.Test\&.RollBack\&.RollbackRoot\&.DataPortal_Insert ()\fC [protected]\fP"

.PP
Definition at line 98 of file RollBack/RollbackRoot\&.cs\&.
.SS "void Csla\&.Test\&.RollBack\&.RollbackRoot\&.DataPortal_Update ()\fC [protected]\fP"

.PP
Definition at line 104 of file RollBack/RollbackRoot\&.cs\&.
.SS "static void Csla\&.Test\&.RollBack\&.RollbackRoot\&.DeleteRoot (string data)\fC [static]\fP"

.PP
Definition at line 77 of file RollBack/RollbackRoot\&.cs\&.
.SS "override object Csla\&.Test\&.RollBack\&.RollbackRoot\&.GetIdValue ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Override this method to return a unique identifying value for this object\&. 
.PP
Reimplemented from \fBCsla\&.BusinessBase< RollbackRoot >\fP\&.
.PP
Definition at line 20 of file RollBack/RollbackRoot\&.cs\&.
.SS "static \fBRollbackRoot\fP Csla\&.Test\&.RollBack\&.RollbackRoot\&.GetRoot (string data)\fC [static]\fP"

.PP
Definition at line 72 of file RollBack/RollbackRoot\&.cs\&.
.SS "static \fBRollbackRoot\fP Csla\&.Test\&.RollBack\&.RollbackRoot\&.NewRoot ()\fC [static]\fP"

.PP
Definition at line 67 of file RollBack/RollbackRoot\&.cs\&.
.SS "override void Csla\&.Test\&.RollBack\&.RollbackRoot\&.OnDeserialized (System\&.Runtime\&.Serialization\&.StreamingContext context)\fC [protected]\fP"

.PP
Definition at line 126 of file RollBack/RollbackRoot\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "string Csla\&.Test\&.RollBack\&.RollbackRoot\&.Data\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 25 of file RollBack/RollbackRoot\&.cs\&.
.SS "bool Csla\&.Test\&.RollBack\&.RollbackRoot\&.Fail\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 38 of file RollBack/RollbackRoot\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
