.TH "Csla.Analyzers.Tests.FindOperationsWithNonSerializableArgumentsAnalyzerTests" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Analyzers.Tests.FindOperationsWithNonSerializableArgumentsAnalyzerTests
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBVerifySupportedDiagnostics\fP ()"
.br
.ti -1c
.RI "async Task \fBAnalyzeWithNotMobileObject\fP ()"
.br
.ti -1c
.RI "async Task \fBAnalyzeWithMobileObjectAndMethodIsNotOperation\fP ()"
.br
.ti -1c
.RI "async Task \fBAnalyzeWithMobileObjectAndMethodIsRootOperationWithNoArguments\fP ()"
.br
.ti -1c
.RI "async Task \fBAnalyzeWithMobileObjectAndMethodIsRootOperationWithSerializableArgument\fP ()"
.br
.ti -1c
.RI "async Task \fBAnalyzeWithMobileObjectAndMethodIsRootOperationWithNonSerializableArgument\fP ()"
.br
.ti -1c
.RI "async Task \fBAnalyzeWithMobileObjectAndMethodIsRootOperationWithMobileObjectArgument\fP ()"
.br
.ti -1c
.RI "async Task \fBAnalyzeWithMobileObjectAndMethodIsRootOperationWithNonSerializableArgumentThatIsInjectable\fP ()"
.br
.ti -1c
.RI "async Task \fBAnalyzeWithMobileObjectAndMethodIsRootOperationWithSerializableArgumentCustomType\fP ()"
.br
.ti -1c
.RI "async Task \fBAnalyzeWithMobileObjectAndMethodIsChildOperationWithNoArguments\fP ()"
.br
.ti -1c
.RI "async Task \fBAnalyzeWithMobileObjectAndMethodIsChildOperationWithSerializableArgument\fP ()"
.br
.ti -1c
.RI "async Task \fBAnalyzeWithMobileObjectAndMethodIsChildOperationWithNonSerializableArgument\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 9 of file FindOperationsWithNonSerializableArgumentsAnalyzerTests\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "async Task Csla\&.Analyzers\&.Tests\&.FindOperationsWithNonSerializableArgumentsAnalyzerTests\&.AnalyzeWithMobileObjectAndMethodIsChildOperationWithNoArguments ()"

.PP
Definition at line 158 of file FindOperationsWithNonSerializableArgumentsAnalyzerTests\&.cs\&.
.SS "async Task Csla\&.Analyzers\&.Tests\&.FindOperationsWithNonSerializableArgumentsAnalyzerTests\&.AnalyzeWithMobileObjectAndMethodIsChildOperationWithNonSerializableArgument ()"

.PP
Definition at line 188 of file FindOperationsWithNonSerializableArgumentsAnalyzerTests\&.cs\&.
.SS "async Task Csla\&.Analyzers\&.Tests\&.FindOperationsWithNonSerializableArgumentsAnalyzerTests\&.AnalyzeWithMobileObjectAndMethodIsChildOperationWithSerializableArgument ()"

.PP
Definition at line 173 of file FindOperationsWithNonSerializableArgumentsAnalyzerTests\&.cs\&.
.SS "async Task Csla\&.Analyzers\&.Tests\&.FindOperationsWithNonSerializableArgumentsAnalyzerTests\&.AnalyzeWithMobileObjectAndMethodIsNotOperation ()"

.PP
Definition at line 43 of file FindOperationsWithNonSerializableArgumentsAnalyzerTests\&.cs\&.
.SS "async Task Csla\&.Analyzers\&.Tests\&.FindOperationsWithNonSerializableArgumentsAnalyzerTests\&.AnalyzeWithMobileObjectAndMethodIsRootOperationWithMobileObjectArgument ()"

.PP
Definition at line 104 of file FindOperationsWithNonSerializableArgumentsAnalyzerTests\&.cs\&.
.SS "async Task Csla\&.Analyzers\&.Tests\&.FindOperationsWithNonSerializableArgumentsAnalyzerTests\&.AnalyzeWithMobileObjectAndMethodIsRootOperationWithNoArguments ()"

.PP
Definition at line 57 of file FindOperationsWithNonSerializableArgumentsAnalyzerTests\&.cs\&.
.SS "async Task Csla\&.Analyzers\&.Tests\&.FindOperationsWithNonSerializableArgumentsAnalyzerTests\&.AnalyzeWithMobileObjectAndMethodIsRootOperationWithNonSerializableArgument ()"

.PP
Definition at line 87 of file FindOperationsWithNonSerializableArgumentsAnalyzerTests\&.cs\&.
.SS "async Task Csla\&.Analyzers\&.Tests\&.FindOperationsWithNonSerializableArgumentsAnalyzerTests\&.AnalyzeWithMobileObjectAndMethodIsRootOperationWithNonSerializableArgumentThatIsInjectable ()"

.PP
Definition at line 121 of file FindOperationsWithNonSerializableArgumentsAnalyzerTests\&.cs\&.
.SS "async Task Csla\&.Analyzers\&.Tests\&.FindOperationsWithNonSerializableArgumentsAnalyzerTests\&.AnalyzeWithMobileObjectAndMethodIsRootOperationWithSerializableArgument ()"

.PP
Definition at line 72 of file FindOperationsWithNonSerializableArgumentsAnalyzerTests\&.cs\&.
.SS "async Task Csla\&.Analyzers\&.Tests\&.FindOperationsWithNonSerializableArgumentsAnalyzerTests\&.AnalyzeWithMobileObjectAndMethodIsRootOperationWithSerializableArgumentCustomType ()"

.PP
Definition at line 138 of file FindOperationsWithNonSerializableArgumentsAnalyzerTests\&.cs\&.
.SS "async Task Csla\&.Analyzers\&.Tests\&.FindOperationsWithNonSerializableArgumentsAnalyzerTests\&.AnalyzeWithNotMobileObject ()"

.PP
Definition at line 35 of file FindOperationsWithNonSerializableArgumentsAnalyzerTests\&.cs\&.
.SS "void Csla\&.Analyzers\&.Tests\&.FindOperationsWithNonSerializableArgumentsAnalyzerTests\&.VerifySupportedDiagnostics ()"

.PP
Definition at line 12 of file FindOperationsWithNonSerializableArgumentsAnalyzerTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
