.TH "Csla.Test.Utilities.CoerseValueTests" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.Utilities.CoerseValueTests
.SH SYNOPSIS
.br
.PP
.PP
Inherits TestBase\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBTestCoerseValue\fP ()"
.br
.ti -1c
.RI "void \fBSmartDateCoerseValue\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 28 of file CorerseValueTests\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Csla\&.Test\&.Utilities\&.CoerseValueTests\&.SmartDateCoerseValue ()"

.PP
Definition at line 59 of file CorerseValueTests\&.cs\&.
.SS "void Csla\&.Test\&.Utilities\&.CoerseValueTests\&.TestCoerseValue ()"

.PP
Definition at line 31 of file CorerseValueTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
