.TH "Csla.FetchAttribute" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.FetchAttribute \- Specifies a method used by the server-side data portal to load existing data into the domain object\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.DataPortalRootOperationAttribute\fP\&.
.SH "Detailed Description"
.PP 
Specifies a method used by the server-side data portal to load existing data into the domain object\&. 


.PP
Definition at line 59 of file DataPortalOperationAttributes\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
