.TH "Csla.Test.ChildChanged.OptimizeChildChangedTests" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.ChildChanged.OptimizeChildChangedTests
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBEventDetail\fP"
.br
.ti -1c
.RI "class \fBSimpleBO\fP"
.br
.ti -1c
.RI "class \fBSimpleBOList\fP"
.br
.in -1c
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum class \fBenumBO\fP { \fBSimpleBO\fP, \fBSimpleBOList\fP }"
.br
.ti -1c
.RI "enum class \fBenumEvent\fP { \fBOnPropertyChanged\fP, \fBOnChildChanged\fP, \fBPropertyChanged\fP, \fBChildChanged\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBOptimizeChildChangedTests_Fetch\fP ()"
.br
.ti -1c
.RI "void \fBOptimizeChildChangedTests_Name_Depth0\fP ()"
.br
.ti -1c
.RI "void \fBOptimizeChildChangedTests_Name_Depth1\fP ()"
.br
.ti -1c
.RI "void \fBOptimizeChildChangedTests_Name_Depth2\fP ()"
.br
.ti -1c
.RI "void \fBOptimizeChildChangedTests_Name_Depth3\fP ()"
.br
.ti -1c
.RI "void \fBOptimizeChildChangedTests_List_Name_Depth1\fP ()"
.br
.ti -1c
.RI "void \fBOptimizeChildChangedTests_List_Name_Depth2\fP ()"
.br
.ti -1c
.RI "void \fBOptimizeChildChangedTests_List_Name_Depth3\fP ()"
.br
.in -1c
.SS "Static Protected Member Functions"

.in +1c
.ti -1c
.RI "static int \fBNextUniqueID\fP ()"
.br
.in -1c
.SS "Static Protected Attributes"

.in +1c
.ti -1c
.RI "static List< \fBEventDetail\fP > \fBEventDetails\fP = new List<\fBEventDetail\fP>()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "static int \fBNextSequenceID\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 14 of file OptimizeChildChangedTests\&.cs\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBCsla\&.Test\&.ChildChanged\&.OptimizeChildChangedTests\&.enumBO\fP\fC [strong]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fISimpleBO \fP\fP
.TP
\fB\fISimpleBOList \fP\fP
.PP
Definition at line 19 of file OptimizeChildChangedTests\&.cs\&.
.SS "enum \fBCsla\&.Test\&.ChildChanged\&.OptimizeChildChangedTests\&.enumEvent\fP\fC [strong]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIOnPropertyChanged \fP\fP
.TP
\fB\fIOnChildChanged \fP\fP
.TP
\fB\fIPropertyChanged \fP\fP
.TP
\fB\fIChildChanged \fP\fP
.PP
Definition at line 20 of file OptimizeChildChangedTests\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "static int Csla\&.Test\&.ChildChanged\&.OptimizeChildChangedTests\&.NextUniqueID ()\fC [static]\fP, \fC [protected]\fP"

.SS "void Csla\&.Test\&.ChildChanged\&.OptimizeChildChangedTests\&.OptimizeChildChangedTests_Fetch ()"

.PP
Definition at line 196 of file OptimizeChildChangedTests\&.cs\&.
.SS "void Csla\&.Test\&.ChildChanged\&.OptimizeChildChangedTests\&.OptimizeChildChangedTests_List_Name_Depth1 ()"

.PP
Definition at line 289 of file OptimizeChildChangedTests\&.cs\&.
.SS "void Csla\&.Test\&.ChildChanged\&.OptimizeChildChangedTests\&.OptimizeChildChangedTests_List_Name_Depth2 ()"

.PP
Definition at line 307 of file OptimizeChildChangedTests\&.cs\&.
.SS "void Csla\&.Test\&.ChildChanged\&.OptimizeChildChangedTests\&.OptimizeChildChangedTests_List_Name_Depth3 ()"

.PP
Definition at line 325 of file OptimizeChildChangedTests\&.cs\&.
.SS "void Csla\&.Test\&.ChildChanged\&.OptimizeChildChangedTests\&.OptimizeChildChangedTests_Name_Depth0 ()"

.PP
Definition at line 217 of file OptimizeChildChangedTests\&.cs\&.
.SS "void Csla\&.Test\&.ChildChanged\&.OptimizeChildChangedTests\&.OptimizeChildChangedTests_Name_Depth1 ()"

.PP
Definition at line 232 of file OptimizeChildChangedTests\&.cs\&.
.SS "void Csla\&.Test\&.ChildChanged\&.OptimizeChildChangedTests\&.OptimizeChildChangedTests_Name_Depth2 ()"

.PP
Definition at line 249 of file OptimizeChildChangedTests\&.cs\&.
.SS "void Csla\&.Test\&.ChildChanged\&.OptimizeChildChangedTests\&.OptimizeChildChangedTests_Name_Depth3 ()"

.PP
Definition at line 267 of file OptimizeChildChangedTests\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "List<\fBEventDetail\fP> Csla\&.Test\&.ChildChanged\&.OptimizeChildChangedTests\&.EventDetails = new List<\fBEventDetail\fP>()\fC [static]\fP, \fC [protected]\fP"

.PP
Definition at line 42 of file OptimizeChildChangedTests\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "int Csla\&.Test\&.ChildChanged\&.OptimizeChildChangedTests\&.NextSequenceID\fC [static]\fP, \fC [get]\fP, \fC [protected]\fP"

.PP
Definition at line 40 of file OptimizeChildChangedTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
