.TH "Csla.Testing.Business.DataPortal.TestBO" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Testing.Business.DataPortal.TestBO
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.BusinessBase< TestBO >\fP\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBDataPortal_Create\fP ()"
.br
.ti -1c
.RI "void \fBDataPortal_Fetch\fP (int criteria)"
.br
.ti -1c
.RI "void \fBDataPortal_Fetch\fP (object citeria)"
.br
.ti -1c
.RI "void \fBDataPortal_Fetch\fP ()"
.br
.ti -1c
.RI "void \fBDataPortal_Insert\fP ()"
.br
.ti -1c
.RI "void \fBDataPortal_Delete\fP (object criteria)"
.br
.ti -1c
.RI "void \fBDataPortal_Delete\fP (int criteria)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 14 of file TestBO\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Csla\&.Testing\&.Business\&.DataPortal\&.TestBO\&.DataPortal_Create ()\fC [protected]\fP"

.PP
Definition at line 17 of file TestBO\&.cs\&.
.SS "void Csla\&.Testing\&.Business\&.DataPortal\&.TestBO\&.DataPortal_Delete (int criteria)\fC [protected]\fP"

.PP
Definition at line 50 of file TestBO\&.cs\&.
.SS "void Csla\&.Testing\&.Business\&.DataPortal\&.TestBO\&.DataPortal_Delete (object criteria)\fC [protected]\fP"

.PP
Definition at line 44 of file TestBO\&.cs\&.
.SS "void Csla\&.Testing\&.Business\&.DataPortal\&.TestBO\&.DataPortal_Fetch ()\fC [protected]\fP"

.PP
Definition at line 32 of file TestBO\&.cs\&.
.SS "void Csla\&.Testing\&.Business\&.DataPortal\&.TestBO\&.DataPortal_Fetch (int criteria)\fC [protected]\fP"

.PP
Definition at line 22 of file TestBO\&.cs\&.
.SS "void Csla\&.Testing\&.Business\&.DataPortal\&.TestBO\&.DataPortal_Fetch (object citeria)\fC [protected]\fP"

.PP
Definition at line 27 of file TestBO\&.cs\&.
.SS "void Csla\&.Testing\&.Business\&.DataPortal\&.TestBO\&.DataPortal_Insert ()\fC [protected]\fP"

.PP
Definition at line 38 of file TestBO\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
