.TH "Csla.Test.CslaDataProvider.Customer.FetchCriteria" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.CslaDataProvider.Customer.FetchCriteria
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.CriteriaBase< FetchCriteria >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFetchCriteria\fP ()"
.br
.ti -1c
.RI "\fBFetchCriteria\fP (int customerID)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnGetState\fP (\fBCsla\&.Serialization\&.Mobile\&.SerializationInfo\fP info, \fBStateMode\fP mode)"
.br
.ti -1c
.RI "override void \fBOnSetState\fP (\fBCsla\&.Serialization\&.Mobile\&.SerializationInfo\fP info, \fBStateMode\fP mode)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBCustomerID\fP\fC [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 111 of file Customer\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Csla\&.Test\&.CslaDataProvider\&.Customer\&.FetchCriteria\&.FetchCriteria ()"

.PP
Definition at line 113 of file Customer\&.cs\&.
.SS "Csla\&.Test\&.CslaDataProvider\&.Customer\&.FetchCriteria\&.FetchCriteria (int customerID)"

.PP
Definition at line 115 of file Customer\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override void Csla\&.Test\&.CslaDataProvider\&.Customer\&.FetchCriteria\&.OnGetState (\fBCsla\&.Serialization\&.Mobile\&.SerializationInfo\fP info, \fBStateMode\fP mode)\fC [protected]\fP"

.PP
Definition at line 130 of file Customer\&.cs\&.
.SS "override void Csla\&.Test\&.CslaDataProvider\&.Customer\&.FetchCriteria\&.OnSetState (\fBCsla\&.Serialization\&.Mobile\&.SerializationInfo\fP info, \fBStateMode\fP mode)\fC [protected]\fP"

.PP
Definition at line 135 of file Customer\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "int Csla\&.Test\&.CslaDataProvider\&.Customer\&.FetchCriteria\&.CustomerID\fC [get]\fP"

.PP
Definition at line 122 of file Customer\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
