.TH "Csla.Analyzers.Tests.EvaluateManagedBackingFieldsCodeFixTests" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Analyzers.Tests.EvaluateManagedBackingFieldsCodeFixTests
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBVerifyGetFixableDiagnosticIds\fP ()"
.br
.ti -1c
.RI "async Task \fBVerifyGetFixes\fP ()"
.br
.ti -1c
.RI "async Task \fBVerifyGetFixesWithTrivia\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 17 of file EvaluateManagedBackingFieldsCodeFixTests\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Csla\&.Analyzers\&.Tests\&.EvaluateManagedBackingFieldsCodeFixTests\&.VerifyGetFixableDiagnosticIds ()"

.PP
Definition at line 20 of file EvaluateManagedBackingFieldsCodeFixTests\&.cs\&.
.SS "async Task Csla\&.Analyzers\&.Tests\&.EvaluateManagedBackingFieldsCodeFixTests\&.VerifyGetFixes ()"

.PP
Definition at line 31 of file EvaluateManagedBackingFieldsCodeFixTests\&.cs\&.
.SS "async Task Csla\&.Analyzers\&.Tests\&.EvaluateManagedBackingFieldsCodeFixTests\&.VerifyGetFixesWithTrivia ()"

.PP
Definition at line 76 of file EvaluateManagedBackingFieldsCodeFixTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
