.TH "Csla.Axml" 3 "Thu Jul 22 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Axml
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBBinding\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBActivityBase\fP"
.br
.RI "CSLA helper to be used in place of the normal Xamarin Android activity that contains a reference to a CSLA ViewModel and a BindingManager\&. "
.ti -1c
.RI "class \fBResource\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
