.TH "Csla.Test.LazyLoad.AChild" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.LazyLoad.AChild
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.BusinessBase< AChild >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAChild\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBPropertyInfo\fP< Guid > \fBIdProperty\fP = RegisterProperty<Guid>(c => c\&.Id)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "Guid \fBId\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "new int \fBEditLevel\fP\fC [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 15 of file AChild\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Csla\&.Test\&.LazyLoad\&.AChild\&.AChild ()"

.PP
Definition at line 29 of file AChild\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBPropertyInfo\fP<Guid> Csla\&.Test\&.LazyLoad\&.AChild\&.IdProperty = RegisterProperty<Guid>(c => c\&.Id)\fC [static]\fP"

.PP
Definition at line 17 of file AChild\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "new int Csla\&.Test\&.LazyLoad\&.AChild\&.EditLevel\fC [get]\fP"

.PP
Definition at line 24 of file AChild\&.cs\&.
.SS "Guid Csla\&.Test\&.LazyLoad\&.AChild\&.Id\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 18 of file AChild\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
