.TH "Csla.Windows.CslaActionEventArgs" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Windows.CslaActionEventArgs \- Event args for an action\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits EventArgs\&.
.PP
Inherited by \fBCsla\&.Windows\&.ErrorEncounteredEventArgs\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCslaActionEventArgs\fP (string commandName)"
.br
.RI "Creates an instance of the object\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBCommandName\fP\fC [get]\fP"
.br
.RI "Gets the name of the command\&. "
.in -1c
.SH "Detailed Description"
.PP 
Event args for an action\&. 


.PP
Definition at line 15 of file CslaActionEventArgs\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Csla\&.Windows\&.CslaActionEventArgs\&.CslaActionEventArgs (string commandName)"

.PP
Creates an instance of the object\&. 
.PP
\fBParameters\fP
.RS 4
\fIcommandName\fP Name of the command\&. 
.RE
.PP

.PP
Definition at line 23 of file CslaActionEventArgs\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "string Csla\&.Windows\&.CslaActionEventArgs\&.CommandName\fC [get]\fP"

.PP
Gets the name of the command\&. 
.PP
Definition at line 33 of file CslaActionEventArgs\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
