.TH "Csla.Test.DataPortalTest.Legacy" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.DataPortalTest.Legacy
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.BusinessBase< Legacy >\fP\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBLegacy\fP \fBNewObject\fP ()"
.br
.ti -1c
.RI "static \fBLegacy\fP \fBGetObject\fP (int id)"
.br
.ti -1c
.RI "static void \fBDeleteObject\fP (int id)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBPropertyInfo\fP< int > \fBIdProperty\fP = RegisterProperty<int>(c => c\&.Id, \fBRelationshipTypes\&.PrivateField\fP)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBDataPortal_Create\fP ()"
.br
.ti -1c
.RI "void \fBDataPortal_Fetch\fP (object criteria)"
.br
.ti -1c
.RI "void \fBDataPortal_Insert\fP ()"
.br
.ti -1c
.RI "void \fBDataPortal_Update\fP ()"
.br
.ti -1c
.RI "void \fBDataPortal_Delete\fP (object criteria)"
.br
.ti -1c
.RI "void \fBDataPortal_DeleteSelf\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBId\fP\fC [get, set]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 15 of file Legacy\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Csla\&.Test\&.DataPortalTest\&.Legacy\&.DataPortal_Create ()\fC [protected]\fP"

.PP
Definition at line 64 of file Legacy\&.cs\&.
.SS "void Csla\&.Test\&.DataPortalTest\&.Legacy\&.DataPortal_Delete (object criteria)\fC [protected]\fP"

.PP
Definition at line 93 of file Legacy\&.cs\&.
.SS "void Csla\&.Test\&.DataPortalTest\&.Legacy\&.DataPortal_DeleteSelf ()\fC [protected]\fP"

.PP
Definition at line 100 of file Legacy\&.cs\&.
.SS "void Csla\&.Test\&.DataPortalTest\&.Legacy\&.DataPortal_Fetch (object criteria)\fC [protected]\fP"

.PP
Definition at line 71 of file Legacy\&.cs\&.
.SS "void Csla\&.Test\&.DataPortalTest\&.Legacy\&.DataPortal_Insert ()\fC [protected]\fP"

.PP
Definition at line 79 of file Legacy\&.cs\&.
.SS "void Csla\&.Test\&.DataPortalTest\&.Legacy\&.DataPortal_Update ()\fC [protected]\fP"

.PP
Definition at line 86 of file Legacy\&.cs\&.
.SS "static void Csla\&.Test\&.DataPortalTest\&.Legacy\&.DeleteObject (int id)\fC [static]\fP"

.PP
Definition at line 42 of file Legacy\&.cs\&.
.SS "static \fBLegacy\fP Csla\&.Test\&.DataPortalTest\&.Legacy\&.GetObject (int id)\fC [static]\fP"

.PP
Definition at line 37 of file Legacy\&.cs\&.
.SS "static \fBLegacy\fP Csla\&.Test\&.DataPortalTest\&.Legacy\&.NewObject ()\fC [static]\fP"

.PP
Definition at line 32 of file Legacy\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBPropertyInfo\fP<int> Csla\&.Test\&.DataPortalTest\&.Legacy\&.IdProperty = RegisterProperty<int>(c => c\&.Id, \fBRelationshipTypes\&.PrivateField\fP)\fC [static]\fP"

.PP
Definition at line 19 of file Legacy\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "int Csla\&.Test\&.DataPortalTest\&.Legacy\&.Id\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 21 of file Legacy\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
