.TH "Csla.Core.FieldManager" 3 "Thu Jul 22 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Core.FieldManager
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDefaultPropertyInfoFactory\fP"
.br
.RI "Creates \fBPropertyInfo\fP objects\&. "
.ti -1c
.RI "class \fBFieldData\fP"
.br
.RI "Contains a field value and related metadata\&. "
.ti -1c
.RI "class \fBFieldDataList\fP"
.br
.ti -1c
.RI "class \fBFieldDataManager\fP"
.br
.RI "Manages properties and property data for a business object\&. "
.ti -1c
.RI "interface \fBIFieldData\fP"
.br
.RI "Defines the members required by a field data storage object\&. "
.ti -1c
.RI "class \fBPropertyInfoFactory\fP"
.br
.RI "Creates the factory object that creates \fBPropertyInfo\fP objects\&. "
.ti -1c
.RI "class \fBPropertyInfoList\fP"
.br
.RI "List of \fBIPropertyInfo\fP objects for a business object type\&. "
.ti -1c
.RI "class \fBPropertyComparer\fP"
.br
.RI "Compare to \fBPropertyInfo\fP x with y for sorting "
.ti -1c
.RI "class \fBPropertyInfoManager\fP"
.br
.RI "Manages the \fBPropertyInfo\fP data for business object types\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
