.TH "Csla.Testing.Business.ObjectFactory.ObjectFactoryBusinessItem" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Testing.Business.ObjectFactory.ObjectFactoryBusinessItem
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.BusinessBase< ObjectFactoryBusinessItem >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBObjectFactoryBusinessItem\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBId\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBOperationResult\fP\fC [get, set]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 18 of file ObjectFactoryBusinessItem\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Csla\&.Testing\&.Business\&.ObjectFactory\&.ObjectFactoryBusinessItem\&.ObjectFactoryBusinessItem ()"

.PP
Definition at line 20 of file ObjectFactoryBusinessItem\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "string Csla\&.Testing\&.Business\&.ObjectFactory\&.ObjectFactoryBusinessItem\&.Id\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 23 of file ObjectFactoryBusinessItem\&.cs\&.
.SS "string Csla\&.Testing\&.Business\&.ObjectFactory\&.ObjectFactoryBusinessItem\&.OperationResult\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 37 of file ObjectFactoryBusinessItem\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
