.TH "Csla.Test.Basic.FormSimulator" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.Basic.FormSimulator
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFormSimulator\fP (\fBCore\&.BusinessBase\fP obj)"
.br
.ti -1c
.RI "\fBFormSimulator\fP (\fBCore\&.BusinessBase\fP obj)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 464 of file BasicTests\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Csla\&.Test\&.Basic\&.FormSimulator\&.FormSimulator (\fBCore\&.BusinessBase\fP obj)"

.PP
Definition at line 468 of file BasicTests\&.cs\&.
.SS "Csla\&.Test\&.Basic\&.FormSimulator\&.FormSimulator (\fBCore\&.BusinessBase\fP obj)"

.PP
Definition at line 400 of file BasicTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
