.TH "Csla.Web.Mvc.Test.ModelBinderTest.RootWithChildren" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Web.Mvc.Test.ModelBinderTest.RootWithChildren
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.BusinessBase< RootWithChildren >\fP\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBRootWithChildren\fP \fBGet\fP (int childCount)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static readonly \fBPropertyInfo\fP< int > \fBIdProperty\fP = RegisterProperty<int>(p => p\&.ID)"
.br
.ti -1c
.RI "static readonly \fBPropertyInfo\fP< string > \fBNameProperty\fP = RegisterProperty<string>(p => p\&.Name)"
.br
.ti -1c
.RI "static readonly \fBPropertyInfo\fP< \fBChildList\fP > \fBChildrenProperty\fP = RegisterProperty<\fBChildList\fP>(p => p\&.Children)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBID\fP\fC [get]\fP"
.br
.ti -1c
.RI "string \fBName\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBChildList\fP \fBChildren\fP\fC [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 15 of file RootWithChildren\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "static \fBRootWithChildren\fP Csla\&.Web\&.Mvc\&.Test\&.ModelBinderTest\&.RootWithChildren\&.Get (int childCount)\fC [static]\fP"

.PP
Definition at line 36 of file RootWithChildren\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "readonly \fBPropertyInfo\fP<\fBChildList\fP> Csla\&.Web\&.Mvc\&.Test\&.ModelBinderTest\&.RootWithChildren\&.ChildrenProperty = RegisterProperty<\fBChildList\fP>(p => p\&.Children)\fC [static]\fP"

.PP
Definition at line 30 of file RootWithChildren\&.cs\&.
.SS "readonly \fBPropertyInfo\fP<int> Csla\&.Web\&.Mvc\&.Test\&.ModelBinderTest\&.RootWithChildren\&.IdProperty = RegisterProperty<int>(p => p\&.ID)\fC [static]\fP"

.PP
Definition at line 17 of file RootWithChildren\&.cs\&.
.SS "readonly \fBPropertyInfo\fP<string> Csla\&.Web\&.Mvc\&.Test\&.ModelBinderTest\&.RootWithChildren\&.NameProperty = RegisterProperty<string>(p => p\&.Name)\fC [static]\fP"

.PP
Definition at line 24 of file RootWithChildren\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "\fBChildList\fP Csla\&.Web\&.Mvc\&.Test\&.ModelBinderTest\&.RootWithChildren\&.Children\fC [get]\fP"

.PP
Definition at line 31 of file RootWithChildren\&.cs\&.
.SS "int Csla\&.Web\&.Mvc\&.Test\&.ModelBinderTest\&.RootWithChildren\&.ID\fC [get]\fP"

.PP
Definition at line 18 of file RootWithChildren\&.cs\&.
.SS "string Csla\&.Web\&.Mvc\&.Test\&.ModelBinderTest\&.RootWithChildren\&.Name\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 25 of file RootWithChildren\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
