.TH "Csla.Test.Data.Table1" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.Data.Table1
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTable1\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBName\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "System\&.Nullable< System\&.DateTime > \fBDate\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "System\&.Nullable< int > \fBAge\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 75 of file TestLinqToSqlContext\&.designer\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Csla\&.Test\&.Data\&.Table1\&.Table1 ()"

.PP
Definition at line 84 of file TestLinqToSqlContext\&.designer\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "System\&.Nullable<int> Csla\&.Test\&.Data\&.Table1\&.Age\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 121 of file TestLinqToSqlContext\&.designer\&.cs\&.
.SS "System\&.Nullable<System\&.DateTime> Csla\&.Test\&.Data\&.Table1\&.Date\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 105 of file TestLinqToSqlContext\&.designer\&.cs\&.
.SS "string Csla\&.Test\&.Data\&.Table1\&.Name\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 89 of file TestLinqToSqlContext\&.designer\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
