.TH "Csla.Test.Basic.CommandObject" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.Basic.CommandObject
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.CommandBase< CommandObject >\fP, and \fBCsla\&.CommandBase< CommandObject >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCommandObject\fP \fBExecuteServerCode\fP ()"
.br
.ti -1c
.RI "void \fBExecuteServerCodeAsunch\fP (EventHandler< \fBDataPortalResult\fP< \fBCommandObject\fP >> handler)"
.br
.ti -1c
.RI "void \fBExecuteServerCodeAsunch\fP (EventHandler< \fBDataPortalResult\fP< \fBCommandObject\fP >> handler, object userState)"
.br
.ti -1c
.RI "\fBCommandObject\fP ()"
.br
.ti -1c
.RI "\fBCommandObject\fP \fBExecuteServerCode\fP ()"
.br
.ti -1c
.RI "\fBCommandObject\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBDataPortal_Execute\fP ()"
.br
.ti -1c
.RI "void \fBDataPortal_Execute\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBAProperty\fP\fC [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 16 of file csla\&.netcore\&.test/Basic/CommandObject\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Csla\&.Test\&.Basic\&.CommandObject\&.CommandObject ()"

.PP
Definition at line 57 of file csla\&.netcore\&.test/Basic/CommandObject\&.cs\&.
.SS "Csla\&.Test\&.Basic\&.CommandObject\&.CommandObject ()"

.PP
Definition at line 44 of file Csla\&.test/Basic/CommandObject\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Csla\&.Test\&.Basic\&.CommandObject\&.DataPortal_Execute ()\fC [protected]\fP"

.PP
Definition at line 48 of file csla\&.netcore\&.test/Basic/CommandObject\&.cs\&.
.SS "void Csla\&.Test\&.Basic\&.CommandObject\&.DataPortal_Execute ()\fC [protected]\fP"

.PP
Definition at line 36 of file Csla\&.test/Basic/CommandObject\&.cs\&.
.SS "\fBCommandObject\fP Csla\&.Test\&.Basic\&.CommandObject\&.ExecuteServerCode ()"

.PP
Definition at line 21 of file csla\&.netcore\&.test/Basic/CommandObject\&.cs\&.
.SS "\fBCommandObject\fP Csla\&.Test\&.Basic\&.CommandObject\&.ExecuteServerCode ()"

.PP
Definition at line 21 of file Csla\&.test/Basic/CommandObject\&.cs\&.
.SS "void Csla\&.Test\&.Basic\&.CommandObject\&.ExecuteServerCodeAsunch (EventHandler< \fBDataPortalResult\fP< \fBCommandObject\fP >> handler)"

.PP
Definition at line 27 of file csla\&.netcore\&.test/Basic/CommandObject\&.cs\&.
.SS "void Csla\&.Test\&.Basic\&.CommandObject\&.ExecuteServerCodeAsunch (EventHandler< \fBDataPortalResult\fP< \fBCommandObject\fP >> handler, object userState)"

.PP
Definition at line 33 of file csla\&.netcore\&.test/Basic/CommandObject\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "string Csla\&.Test\&.Basic\&.CommandObject\&.AProperty\fC [get]\fP"

.PP
Definition at line 39 of file csla\&.netcore\&.test/Basic/CommandObject\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
