.TH "Csla.Rules.BusinessRuleAsync" 3 "Thu Jul 22 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Rules.BusinessRuleAsync \- Base class used to create async business and validation rules\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.Rules\&.BusinessRuleBase\fP, and \fBCsla\&.Rules\&.IBusinessRuleAsync\fP\&.
.PP
Inherited by \fBCsla\&.Rules\&.ObjectRuleAsync\fP, and \fBCsla\&.Rules\&.PropertyRuleAsync\fP\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBBusinessRuleAsync\fP ()"
.br
.RI "Creates an instance of the rule that applies to a business object as a whole\&. "
.ti -1c
.RI "\fBBusinessRuleAsync\fP (\fBCsla\&.Core\&.IPropertyInfo\fP primaryProperty)"
.br
.RI "Creates an instance of the rule that applies to a specfic property\&. "
.ti -1c
.RI "virtual Task \fBExecuteAsync\fP (\fBIRuleContext\fP context)"
.br
.RI "Business or validation rule implementation\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override bool \fBIsAsync\fP\fC [get, protected set]\fP"
.br
.RI "Gets a value indicating whether the rule will run on a background thread\&. "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Base class used to create async business and validation rules\&. 


.PP
Definition at line 21 of file BusinessRuleAsync\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Csla\&.Rules\&.BusinessRuleAsync\&.BusinessRuleAsync ()\fC [protected]\fP"

.PP
Creates an instance of the rule that applies to a business object as a whole\&. 
.PP
Definition at line 37 of file BusinessRuleAsync\&.cs\&.
.SS "Csla\&.Rules\&.BusinessRuleAsync\&.BusinessRuleAsync (\fBCsla\&.Core\&.IPropertyInfo\fP primaryProperty)\fC [protected]\fP"

.PP
Creates an instance of the rule that applies to a specfic property\&. 
.PP
\fBParameters\fP
.RS 4
\fIprimaryProperty\fP Primary property for this rule\&.
.RE
.PP

.PP
Definition at line 46 of file BusinessRuleAsync\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual Task Csla\&.Rules\&.BusinessRuleAsync\&.ExecuteAsync (\fBIRuleContext\fP context)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Business or validation rule implementation\&. 
.PP
\fBParameters\fP
.RS 4
\fIcontext\fP Rule context object\&.
.RE
.PP

.PP
Implements \fBCsla\&.Rules\&.IBusinessRuleAsync\fP\&.
.PP
Definition at line 54 of file BusinessRuleAsync\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "override bool Csla\&.Rules\&.BusinessRuleAsync\&.IsAsync\fC [get]\fP, \fC [protected set]\fP"

.PP
Gets a value indicating whether the rule will run on a background thread\&. 
.PP
Definition at line 27 of file BusinessRuleAsync\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
