.TH "Csla.Test.Authorization.AuthRuleExpectsCriteria" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.Authorization.AuthRuleExpectsCriteria
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.Rules\&.AuthorizationRule\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAuthRuleExpectsCriteria\fP (\fBAuthorizationActions\fP action)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBExecute\fP (\fBIAuthorizationContext\fP context)"
.br
.RI "\fBAuthorization\fP rule implementation\&. "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 14 of file AuthRuleExpectsCriteria\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Csla\&.Test\&.Authorization\&.AuthRuleExpectsCriteria\&.AuthRuleExpectsCriteria (\fBAuthorizationActions\fP action)"

.PP
Definition at line 16 of file AuthRuleExpectsCriteria\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override void Csla\&.Test\&.Authorization\&.AuthRuleExpectsCriteria\&.Execute (\fBIAuthorizationContext\fP context)\fC [protected]\fP, \fC [virtual]\fP"

.PP
\fBAuthorization\fP rule implementation\&. 
.PP
\fBParameters\fP
.RS 4
\fIcontext\fP Rule context object\&.
.RE
.PP

.PP
Implements \fBCsla\&.Rules\&.AuthorizationRule\fP\&.
.PP
Definition at line 20 of file AuthRuleExpectsCriteria\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
