.TH "Csla.Server.Hosts.Mobile.IMobileRequest" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Server.Hosts.Mobile.IMobileRequest \- Interface for all requests from client  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBCsla\&.Server\&.Hosts\&.Mobile\&.MobileCriteriaRequest\fP, and \fBCsla\&.Server\&.Hosts\&.Mobile\&.MobileUpdateRequest\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "IPrincipal \fBPrincipal\fP\fC [get, set]\fP"
.br
.RI "Principal that will be set for the request "
.ti -1c
.RI "\fBContextDictionary\fP \fBGlobalContext\fP\fC [get, set]\fP"
.br
.RI "Global context object\&. "
.ti -1c
.RI "\fBContextDictionary\fP \fBClientContext\fP\fC [get, set]\fP"
.br
.RI "Client context object\&. "
.ti -1c
.RI "string \fBClientCulture\fP\fC [get, set]\fP"
.br
.RI "The client culture\&. "
.ti -1c
.RI "string \fBClientUICulture\fP\fC [get, set]\fP"
.br
.RI "The client UI culture\&. "
.in -1c
.SH "Detailed Description"
.PP 
Interface for all requests from client 


.PP
Definition at line 17 of file IMobileRequest\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "\fBContextDictionary\fP Csla\&.Server\&.Hosts\&.Mobile\&.IMobileRequest\&.ClientContext\fC [get]\fP, \fC [set]\fP"

.PP
Client context object\&. 
.PP
Definition at line 30 of file IMobileRequest\&.cs\&.
.SS "string Csla\&.Server\&.Hosts\&.Mobile\&.IMobileRequest\&.ClientCulture\fC [get]\fP, \fC [set]\fP"

.PP
The client culture\&. 
.PP
Definition at line 34 of file IMobileRequest\&.cs\&.
.SS "string Csla\&.Server\&.Hosts\&.Mobile\&.IMobileRequest\&.ClientUICulture\fC [get]\fP, \fC [set]\fP"

.PP
The client UI culture\&. 
.PP
Definition at line 38 of file IMobileRequest\&.cs\&.
.SS "\fBContextDictionary\fP Csla\&.Server\&.Hosts\&.Mobile\&.IMobileRequest\&.GlobalContext\fC [get]\fP, \fC [set]\fP"

.PP
Global context object\&. 
.PP
Definition at line 26 of file IMobileRequest\&.cs\&.
.SS "IPrincipal Csla\&.Server\&.Hosts\&.Mobile\&.IMobileRequest\&.Principal\fC [get]\fP, \fC [set]\fP"

.PP
Principal that will be set for the request 
.PP
Definition at line 22 of file IMobileRequest\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
