.TH "Csla.Core.ObservableBindingList< T >" 3 "Thu Jul 22 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Core.ObservableBindingList< T > \- Extends ObservableCollection with behaviors required by CSLA \&.NET collections\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.Core\&.MobileObservableCollection< T >\fP, \fBCsla\&.Core\&.IObservableBindingList\fP, \fBCsla\&.Core\&.INotifyBusy\fP, \fBCsla\&.Core\&.INotifyChildChanged\fP, and \fBCsla\&.Serialization\&.Mobile\&.ISerializationNotification\fP\&.
.PP
Inherited by \fBCsla\&.DynamicListBase< T >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "T \fBAddNew\fP ()"
.br
.RI "Adds a new item to this collection\&. "
.ti -1c
.RI "void \fBAddRange\fP (System\&.Collections\&.Generic\&.IEnumerable< T > range)"
.br
.RI "Add a range of items to the list\&. "
.ti -1c
.RI "virtual void \fBOnAddedNew\fP (T item)"
.br
.RI "Raises the AddedNew event\&. "
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBOnRemovingItem\fP (T removedItem)"
.br
.RI "Raise the RemovingItem event\&. "
.ti -1c
.RI "override void \fBRemoveItem\fP (int index)"
.br
.RI "Remove the item at the specified index\&. "
.ti -1c
.RI "virtual void \fBOnBusyChanged\fP (\fBBusyChangedEventArgs\fP args)"
.br
.RI "Override this method to be notified when the IsBusy property has changed\&. "
.ti -1c
.RI "void \fBOnBusyChanged\fP (string propertyName, bool busy)"
.br
.RI "Raises the BusyChanged event for a specific property\&. "
.ti -1c
.RI "virtual void \fBOnUnhandledAsyncException\fP (\fBErrorEventArgs\fP error)"
.br
.RI "Method invoked when an unhandled async exception has occurred\&. "
.ti -1c
.RI "void \fBOnUnhandledAsyncException\fP (object originalSender, Exception error)"
.br
.RI "Raises the UnhandledAsyncException event\&. "
.ti -1c
.RI "override void \fBInsertItem\fP (int index, T item)"
.br
.RI "Invoked when an item is inserted into the list\&. "
.ti -1c
.RI "virtual void \fBOnAddEventHooks\fP (T item)"
.br
.RI "Method invoked when events are hooked for a child object\&. "
.ti -1c
.RI "virtual void \fBOnRemoveEventHooks\fP (T item)"
.br
.RI "Method invoked when events are unhooked for a child object\&. "
.ti -1c
.RI "virtual void \fBOnDeserialized\fP ()"
.br
.RI "This method is called on a newly deserialized object after deserialization is complete\&. "
.ti -1c
.RI "virtual void \fBOnChildChanged\fP (\fBChildChangedEventArgs\fP e)"
.br
.RI "Raises the ChildChanged event, indicating that a child object has been changed\&. "
.ti -1c
.RI "virtual void \fBChild_PropertyChanged\fP (object sender, PropertyChangedEventArgs e)"
.br
.RI "Handles any PropertyChanged event from a child object and echoes it up as a ChildChanged event\&. "
.ti -1c
.RI "virtual T \fBAddNewCore\fP ()"
.br
.RI "Override this method to create a new object that is added to the collection\&. "
.ti -1c
.RI "override void \fBOnCollectionChanged\fP (NotifyCollectionChangedEventArgs e)"
.br
.RI "Raises the CollectionChanged event\&. "
.ti -1c
.RI "override void \fBOnGetState\fP (\fBSerializationInfo\fP info)"
.br
.RI "Override this method to get custom field values from the serialization stream\&. "
.ti -1c
.RI "override void \fBOnSetState\fP (\fBSerializationInfo\fP info)"
.br
.RI "Override this method to set custom field values into the serialization stream\&. "
.ti -1c
.RI "override void \fBSetLoadListMode\fP (bool enabled)"
.br
.RI "Sets the load list mode for the list "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "virtual bool \fBSupportsChangeNotificationCore\fP\fC [get]\fP"
.br
.RI "Gets a value indicating whether this object supports change notification\&. "
.ti -1c
.RI "bool \fBAllowEdit\fP\fC [get, protected set]\fP"
.br
.RI "Gets or sets a value indicating whether data binding can automatically edit items in this collection\&. "
.ti -1c
.RI "bool \fBAllowNew\fP\fC [get, protected set]\fP"
.br
.RI "Gets or sets a value indicating whether data binding can automatically add new items to this collection\&. "
.ti -1c
.RI "bool \fBAllowRemove\fP\fC [get, protected set]\fP"
.br
.RI "Gets or sets a value indicating whether data binding can automatically remove items from this collection\&. "
.ti -1c
.RI "bool \fBRaiseListChangedEvents\fP\fC [get, set]\fP"
.br
.RI "Gets or sets a value indicating whether the collection should raise changed events\&. "
.ti -1c
.RI "EventHandler< \fBRemovingItemEventArgs\fP > \fBRemovingItem\fP"
.br
.RI "Implements a serialization-safe RemovingItem event\&. "
.ti -1c
.RI "\fBBusyChangedEventHandler\fP \fBBusyChanged\fP"
.br
.RI "Event indicating that the busy status of the object has changed\&. "
.ti -1c
.RI "virtual bool \fBIsBusy\fP\fC [get]\fP"
.br
.RI "Gets the busy status for this object and its child objects\&. "
.ti -1c
.RI "virtual bool \fBIsSelfBusy\fP\fC [get]\fP"
.br
.RI "Gets the busy status for this object\&. "
.ti -1c
.RI "EventHandler< \fBErrorEventArgs\fP > \fBUnhandledAsyncException\fP"
.br
.RI "Event indicating that an exception occurred during an async operation\&. "
.ti -1c
.RI "EventHandler< \fBCsla\&.Core\&.ChildChangedEventArgs\fP > \fBChildChanged\fP"
.br
.RI "Event raised when a child object has been changed\&. "
.ti -1c
.RI "EventHandler< \fBAddedNewEventArgs\fP< T > > \fBAddedNew\fP"
.br
.RI "Event raised when a new object has been added to the collection\&. "
.ti -1c
.RI "IDisposable \fBSuppressListChangedEvents\fP\fC [get]\fP"
.br
.RI "Use this object to suppress ListChangedEvents for an entire code block\&. May be nested in multiple levels for the same object\&. "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Extends ObservableCollection with behaviors required by CSLA \&.NET collections\&. 


.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP 
.RE
.PP

.PP
Definition at line 31 of file ObservableBindingList\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "T \fBCsla\&.Core\&.ObservableBindingList\fP< T >\&.AddNew ()"

.PP
Adds a new item to this collection\&. 
.PP
Implements \fBCsla\&.Core\&.IObservableBindingList\fP\&.
.PP
Definition at line 95 of file ObservableBindingList\&.cs\&.
.SS "virtual T \fBCsla\&.Core\&.ObservableBindingList\fP< T >\&.AddNewCore ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Override this method to create a new object that is added to the collection\&. 
.PP
Reimplemented in \fBCsla\&.DynamicListBase< T >\fP, and \fBCsla\&.BusinessListBase< T, C >\fP\&.
.PP
Definition at line 530 of file ObservableBindingList\&.cs\&.
.SS "void \fBCsla\&.Core\&.ObservableBindingList\fP< T >\&.AddRange (System\&.Collections\&.Generic\&.IEnumerable< T > range)"

.PP
Add a range of items to the list\&. 
.PP
\fBParameters\fP
.RS 4
\fIrange\fP List of items to add\&.
.RE
.PP

.PP
Definition at line 173 of file ObservableBindingList\&.cs\&.
.SS "virtual void \fBCsla\&.Core\&.ObservableBindingList\fP< T >\&.Child_PropertyChanged (object sender, PropertyChangedEventArgs e)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Handles any PropertyChanged event from a child object and echoes it up as a ChildChanged event\&. 
.PP
\fBParameters\fP
.RS 4
\fIsender\fP Object that raised the event\&.
.br
\fIe\fP Property changed args\&.
.RE
.PP

.PP
Definition at line 451 of file ObservableBindingList\&.cs\&.
.SS "override void \fBCsla\&.Core\&.ObservableBindingList\fP< T >\&.InsertItem (int index, T item)\fC [protected]\fP"

.PP
Invoked when an item is inserted into the list\&. 
.PP
\fBParameters\fP
.RS 4
\fIindex\fP Index of new item\&.
.br
\fIitem\fP Reference to new item\&.
.RE
.PP

.PP
Definition at line 298 of file ObservableBindingList\&.cs\&.
.SS "virtual void \fBCsla\&.Core\&.ObservableBindingList\fP< T >\&.OnAddedNew (T item)\fC [virtual]\fP"

.PP
Raises the AddedNew event\&. 
.PP
\fBParameters\fP
.RS 4
\fIitem\fP 
.RE
.PP

.PP
Definition at line 507 of file ObservableBindingList\&.cs\&.
.SS "virtual void \fBCsla\&.Core\&.ObservableBindingList\fP< T >\&.OnAddEventHooks (T item)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Method invoked when events are hooked for a child object\&. 
.PP
\fBParameters\fP
.RS 4
\fIitem\fP Reference to child object\&.
.RE
.PP

.PP
Definition at line 310 of file ObservableBindingList\&.cs\&.
.SS "virtual void \fBCsla\&.Core\&.ObservableBindingList\fP< T >\&.OnBusyChanged (\fBBusyChangedEventArgs\fP args)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Override this method to be notified when the IsBusy property has changed\&. 
.PP
\fBParameters\fP
.RS 4
\fIargs\fP Event arguments\&.
.RE
.PP

.PP
Definition at line 202 of file ObservableBindingList\&.cs\&.
.SS "void \fBCsla\&.Core\&.ObservableBindingList\fP< T >\&.OnBusyChanged (string propertyName, bool busy)\fC [protected]\fP"

.PP
Raises the BusyChanged event for a specific property\&. 
.PP
\fBParameters\fP
.RS 4
\fIpropertyName\fP Name of the property\&.
.br
\fIbusy\fP New busy value\&.
.RE
.PP

.PP
Definition at line 213 of file ObservableBindingList\&.cs\&.
.SS "virtual void \fBCsla\&.Core\&.ObservableBindingList\fP< T >\&.OnChildChanged (\fBChildChangedEventArgs\fP e)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Raises the ChildChanged event, indicating that a child object has been changed\&. 
.PP
\fBParameters\fP
.RS 4
\fIe\fP \fBChildChangedEventArgs\fP object\&. 
.RE
.PP

.PP
Definition at line 427 of file ObservableBindingList\&.cs\&.
.SS "override void \fBCsla\&.Core\&.ObservableBindingList\fP< T >\&.OnCollectionChanged (NotifyCollectionChangedEventArgs e)\fC [protected]\fP"

.PP
Raises the CollectionChanged event\&. 
.PP
\fBParameters\fP
.RS 4
\fIe\fP Event arguments\&.
.RE
.PP

.PP
Definition at line 545 of file ObservableBindingList\&.cs\&.
.SS "virtual void \fBCsla\&.Core\&.ObservableBindingList\fP< T >\&.OnDeserialized ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
This method is called on a newly deserialized object after deserialization is complete\&. 
.PP
Reimplemented in \fBCsla\&.DynamicListBase< T >\fP, and \fBCsla\&.BusinessListBase< T, C >\fP\&.
.PP
Definition at line 371 of file ObservableBindingList\&.cs\&.
.SS "override void \fBCsla\&.Core\&.ObservableBindingList\fP< T >\&.OnGetState (\fBSerializationInfo\fP info)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Override this method to get custom field values from the serialization stream\&. 
.PP
\fBParameters\fP
.RS 4
\fIinfo\fP \fBSerialization\fP info\&.
.RE
.PP

.PP
Reimplemented from \fBCsla\&.Core\&.MobileObservableCollection< T >\fP\&.
.PP
Reimplemented in \fBCsla\&.DynamicListBase< T >\fP\&.
.PP
Definition at line 561 of file ObservableBindingList\&.cs\&.
.SS "virtual void \fBCsla\&.Core\&.ObservableBindingList\fP< T >\&.OnRemoveEventHooks (T item)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Method invoked when events are unhooked for a child object\&. 
.PP
\fBParameters\fP
.RS 4
\fIitem\fP Reference to child object\&.
.RE
.PP

.PP
Definition at line 339 of file ObservableBindingList\&.cs\&.
.SS "void \fBCsla\&.Core\&.ObservableBindingList\fP< T >\&.OnRemovingItem (T removedItem)\fC [protected]\fP"

.PP
Raise the RemovingItem event\&. 
.PP
\fBParameters\fP
.RS 4
\fIremovedItem\fP A reference to the item that is being removed\&. 
.RE
.PP

.PP
Definition at line 139 of file ObservableBindingList\&.cs\&.
.SS "override void \fBCsla\&.Core\&.ObservableBindingList\fP< T >\&.OnSetState (\fBSerializationInfo\fP info)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Override this method to set custom field values into the serialization stream\&. 
.PP
\fBParameters\fP
.RS 4
\fIinfo\fP \fBSerialization\fP info\&.
.RE
.PP

.PP
Reimplemented from \fBCsla\&.Core\&.MobileObservableCollection< T >\fP\&.
.PP
Reimplemented in \fBCsla\&.DynamicListBase< T >\fP\&.
.PP
Definition at line 577 of file ObservableBindingList\&.cs\&.
.SS "virtual void \fBCsla\&.Core\&.ObservableBindingList\fP< T >\&.OnUnhandledAsyncException (\fBErrorEventArgs\fP error)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Method invoked when an unhandled async exception has occurred\&. 
.PP
\fBParameters\fP
.RS 4
\fIerror\fP Event arguments\&.
.RE
.PP

.PP
Definition at line 268 of file ObservableBindingList\&.cs\&.
.SS "void \fBCsla\&.Core\&.ObservableBindingList\fP< T >\&.OnUnhandledAsyncException (object originalSender, Exception error)\fC [protected]\fP"

.PP
Raises the UnhandledAsyncException event\&. 
.PP
\fBParameters\fP
.RS 4
\fIoriginalSender\fP Original sender of event\&.
.br
\fIerror\fP Exception that occurred\&.
.RE
.PP

.PP
Definition at line 279 of file ObservableBindingList\&.cs\&.
.SS "override void \fBCsla\&.Core\&.ObservableBindingList\fP< T >\&.RemoveItem (int index)\fC [protected]\fP"

.PP
Remove the item at the specified index\&. 
.PP
\fBParameters\fP
.RS 4
\fIindex\fP The zero-based index of the item to remove\&. 
.RE
.PP

.PP
Definition at line 158 of file ObservableBindingList\&.cs\&.
.SS "override void \fBCsla\&.Core\&.ObservableBindingList\fP< T >\&.SetLoadListMode (bool enabled)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Sets the load list mode for the list 
.PP
\fBParameters\fP
.RS 4
\fIenabled\fP Enabled value
.RE
.PP

.PP
Reimplemented from \fBCsla\&.Core\&.MobileObservableCollection< T >\fP\&.
.PP
Definition at line 633 of file ObservableBindingList\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "EventHandler<\fBAddedNewEventArgs\fP<T> > \fBCsla\&.Core\&.ObservableBindingList\fP< T >\&.AddedNew\fC [add]\fP, \fC [remove]\fP"

.PP
Event raised when a new object has been added to the collection\&. 
.PP
Definition at line 488 of file ObservableBindingList\&.cs\&.
.SS "bool \fBCsla\&.Core\&.ObservableBindingList\fP< T >\&.AllowEdit\fC [get]\fP, \fC [protected set]\fP"

.PP
Gets or sets a value indicating whether data binding can automatically edit items in this collection\&. 
.PP
Definition at line 56 of file ObservableBindingList\&.cs\&.
.SS "bool \fBCsla\&.Core\&.ObservableBindingList\fP< T >\&.AllowNew\fC [get]\fP, \fC [protected set]\fP"

.PP
Gets or sets a value indicating whether data binding can automatically add new items to this collection\&. 
.PP
Definition at line 66 of file ObservableBindingList\&.cs\&.
.SS "bool \fBCsla\&.Core\&.ObservableBindingList\fP< T >\&.AllowRemove\fC [get]\fP, \fC [protected set]\fP"

.PP
Gets or sets a value indicating whether data binding can automatically remove items from this collection\&. 
.PP
Definition at line 76 of file ObservableBindingList\&.cs\&.
.SS "\fBBusyChangedEventHandler\fP \fBCsla\&.Core\&.ObservableBindingList\fP< T >\&.BusyChanged\fC [add]\fP, \fC [remove]\fP"

.PP
Event indicating that the busy status of the object has changed\&. 
.PP
Definition at line 191 of file ObservableBindingList\&.cs\&.
.SS "EventHandler<\fBCsla\&.Core\&.ChildChangedEventArgs\fP> \fBCsla\&.Core\&.ObservableBindingList\fP< T >\&.ChildChanged\fC [add]\fP, \fC [remove]\fP"

.PP
Event raised when a child object has been changed\&. 
.PP
Definition at line 405 of file ObservableBindingList\&.cs\&.
.SS "virtual bool \fBCsla\&.Core\&.ObservableBindingList\fP< T >\&.IsBusy\fC [get]\fP"

.PP
Gets the busy status for this object and its child objects\&. 
.PP
Definition at line 224 of file ObservableBindingList\&.cs\&.
.SS "virtual bool \fBCsla\&.Core\&.ObservableBindingList\fP< T >\&.IsSelfBusy\fC [get]\fP"

.PP
Gets the busy status for this object\&. 
.PP
Definition at line 235 of file ObservableBindingList\&.cs\&.
.SS "bool \fBCsla\&.Core\&.ObservableBindingList\fP< T >\&.RaiseListChangedEvents\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets a value indicating whether the collection should raise changed events\&. 
.PP
Definition at line 86 of file ObservableBindingList\&.cs\&.
.SS "EventHandler<\fBRemovingItemEventArgs\fP> \fBCsla\&.Core\&.ObservableBindingList\fP< T >\&.RemovingItem\fC [add]\fP, \fC [remove]\fP"

.PP
Implements a serialization-safe RemovingItem event\&. 
.PP
Definition at line 117 of file ObservableBindingList\&.cs\&.
.SS "virtual bool \fBCsla\&.Core\&.ObservableBindingList\fP< T >\&.SupportsChangeNotificationCore\fC [get]\fP, \fC [protected]\fP"

.PP
Gets a value indicating whether this object supports change notification\&. 
.PP
Definition at line 44 of file ObservableBindingList\&.cs\&.
.SS "IDisposable \fBCsla\&.Core\&.ObservableBindingList\fP< T >\&.SuppressListChangedEvents\fC [get]\fP"

.PP
Use this object to suppress ListChangedEvents for an entire code block\&. May be nested in multiple levels for the same object\&. 
.PP
Definition at line 595 of file ObservableBindingList\&.cs\&.
.SS "EventHandler<\fBErrorEventArgs\fP> \fBCsla\&.Core\&.ObservableBindingList\fP< T >\&.UnhandledAsyncException\fC [add]\fP, \fC [remove]\fP"

.PP
Event indicating that an exception occurred during an async operation\&. 
.PP
Definition at line 257 of file ObservableBindingList\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
