.TH "Csla.Test.CommandBase.CommandObject" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.CommandBase.CommandObject
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.CommandBase< CommandObject >\fP\&.
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static readonly \fBPropertyInfo\fP< string > \fBNameProperty\fP = RegisterProperty<string>(c => c\&.Name)"
.br
.ti -1c
.RI "static readonly \fBPropertyInfo\fP< int > \fBNumProperty\fP = RegisterProperty<int>(c => c\&.Num)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBName\fP\fC [get]\fP"
.br
.ti -1c
.RI "int \fBNum\fP\fC [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 7 of file CommandObject\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "readonly \fBPropertyInfo\fP<string> Csla\&.Test\&.CommandBase\&.CommandObject\&.NameProperty = RegisterProperty<string>(c => c\&.Name)\fC [static]\fP"

.PP
Definition at line 9 of file CommandObject\&.cs\&.
.SS "readonly \fBPropertyInfo\fP<int> Csla\&.Test\&.CommandBase\&.CommandObject\&.NumProperty = RegisterProperty<int>(c => c\&.Num)\fC [static]\fP"

.PP
Definition at line 16 of file CommandObject\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "string Csla\&.Test\&.CommandBase\&.CommandObject\&.Name\fC [get]\fP"

.PP
Definition at line 10 of file CommandObject\&.cs\&.
.SS "int Csla\&.Test\&.CommandBase\&.CommandObject\&.Num\fC [get]\fP"

.PP
Definition at line 17 of file CommandObject\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
