.TH "cslalighttest.Serialization.SerializationTests" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cslalighttest.Serialization.SerializationTests
.SH SYNOPSIS
.br
.PP
.PP
Inherits TestBase\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBStringCriteria\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSerializeWithNullArgumentShouldNotThrowException\fP ()"
.br
.ti -1c
.RI "void \fBSerializeCriteriaSuccess\fP ()"
.br
.ti -1c
.RI "void \fBBusinessObjectWithoutChildList\fP ()"
.br
.ti -1c
.RI "void \fBBusinessObjectWithChildList\fP ()"
.br
.ti -1c
.RI "void \fBSerializeAndDeserializeReadOnly\fP ()"
.br
.ti -1c
.RI "void \fBSerializeMobileListWithPrimitiveTypes\fP ()"
.br
.ti -1c
.RI "void \fBMobileListWithNonBusinessObjectReferenceType\fP ()"
.br
.ti -1c
.RI "void \fBReadOnlyBaseTest\fP ()"
.br
.ti -1c
.RI "void \fBReadOnlyListBaseTest\fP ()"
.br
.ti -1c
.RI "void \fBMobileListSerializationSuccess\fP ()"
.br
.ti -1c
.RI "void \fBMobileListEmptySerializationSuccess\fP ()"
.br
.ti -1c
.RI "void \fBMobileListOfMobileObjectsSerializationSuccess\fP ()"
.br
.ti -1c
.RI "void \fBMobileDictionary_PrimitiveKey_PrimitiveValue\fP ()"
.br
.ti -1c
.RI "void \fBMobileDictionary_PrimitiveKey_PrimitiveValue_BF\fP ()"
.br
.ti -1c
.RI "void \fBMobileDictionary_PrimitiveKey_MobileValue\fP ()"
.br
.ti -1c
.RI "void \fBMobileDictionary_MobileKey_PrimitiveValue\fP ()"
.br
.ti -1c
.RI "void \fBMobileDictionary_MobileKey_MobileValue\fP ()"
.br
.ti -1c
.RI "void \fBLogicallyIdenticalChildObjects\fP ()"
.br
.RI "Verifies that serializing an object graph with sibling complex objects that implement Equals and are logically identical, produces an identical object graph upon deserialization (eg\&. the two siblings are separate instances post-deserialization)\&. It should also be noted that the tested objects implement custom serialization methods\&. "
.ti -1c
.RI "void \fBNullChildObject\fP ()"
.br
.RI "Verifies that serializing/deserializing an object graph with null references of a type that is complex (eg\&. is a separate child object) works\&. It should also be noted that the tested objects implement custom serialization methods\&. "
.ti -1c
.RI "void \fBBusinessObjectWithEnum\fP ()"
.br
.RI "Verifies that serialization/deserialization works for business objects that have an property storing an enum\&. "
.ti -1c
.RI "void \fBTestSerializationCslaBinaryReaderWriterList\fP ()"
.br
.ti -1c
.RI "void \fBTestSerializationCslaBinaryReaderWriter\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 33 of file SerializationTests\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void cslalighttest\&.Serialization\&.SerializationTests\&.BusinessObjectWithChildList ()"

.PP
Definition at line 106 of file SerializationTests\&.cs\&.
.SS "void cslalighttest\&.Serialization\&.SerializationTests\&.BusinessObjectWithEnum ()"

.PP
Verifies that serialization/deserialization works for business objects that have an property storing an enum\&. 
.PP
Definition at line 490 of file SerializationTests\&.cs\&.
.SS "void cslalighttest\&.Serialization\&.SerializationTests\&.BusinessObjectWithoutChildList ()"

.PP
Definition at line 75 of file SerializationTests\&.cs\&.
.SS "void cslalighttest\&.Serialization\&.SerializationTests\&.LogicallyIdenticalChildObjects ()"

.PP
Verifies that serializing an object graph with sibling complex objects that implement Equals and are logically identical, produces an identical object graph upon deserialization (eg\&. the two siblings are separate instances post-deserialization)\&. It should also be noted that the tested objects implement custom serialization methods\&. 
.PP
Definition at line 417 of file SerializationTests\&.cs\&.
.SS "void cslalighttest\&.Serialization\&.SerializationTests\&.MobileDictionary_MobileKey_MobileValue ()"

.PP
Definition at line 391 of file SerializationTests\&.cs\&.
.SS "void cslalighttest\&.Serialization\&.SerializationTests\&.MobileDictionary_MobileKey_PrimitiveValue ()"

.PP
Definition at line 371 of file SerializationTests\&.cs\&.
.SS "void cslalighttest\&.Serialization\&.SerializationTests\&.MobileDictionary_PrimitiveKey_MobileValue ()"

.PP
Definition at line 342 of file SerializationTests\&.cs\&.
.SS "void cslalighttest\&.Serialization\&.SerializationTests\&.MobileDictionary_PrimitiveKey_PrimitiveValue ()"

.PP
Definition at line 281 of file SerializationTests\&.cs\&.
.SS "void cslalighttest\&.Serialization\&.SerializationTests\&.MobileDictionary_PrimitiveKey_PrimitiveValue_BF ()"

.PP
Definition at line 310 of file SerializationTests\&.cs\&.
.SS "void cslalighttest\&.Serialization\&.SerializationTests\&.MobileListEmptySerializationSuccess ()"

.PP
Definition at line 249 of file SerializationTests\&.cs\&.
.SS "void cslalighttest\&.Serialization\&.SerializationTests\&.MobileListOfMobileObjectsSerializationSuccess ()"

.PP
Definition at line 263 of file SerializationTests\&.cs\&.
.SS "void cslalighttest\&.Serialization\&.SerializationTests\&.MobileListSerializationSuccess ()"

.PP
Definition at line 231 of file SerializationTests\&.cs\&.
.SS "void cslalighttest\&.Serialization\&.SerializationTests\&.MobileListWithNonBusinessObjectReferenceType ()"

.PP
Definition at line 190 of file SerializationTests\&.cs\&.
.SS "void cslalighttest\&.Serialization\&.SerializationTests\&.NullChildObject ()"

.PP
Verifies that serializing/deserializing an object graph with null references of a type that is complex (eg\&. is a separate child object) works\&. It should also be noted that the tested objects implement custom serialization methods\&. 
.PP
Definition at line 459 of file SerializationTests\&.cs\&.
.SS "void cslalighttest\&.Serialization\&.SerializationTests\&.ReadOnlyBaseTest ()"

.PP
Definition at line 202 of file SerializationTests\&.cs\&.
.SS "void cslalighttest\&.Serialization\&.SerializationTests\&.ReadOnlyListBaseTest ()"

.PP
Definition at line 216 of file SerializationTests\&.cs\&.
.SS "void cslalighttest\&.Serialization\&.SerializationTests\&.SerializeAndDeserializeReadOnly ()"

.PP
Definition at line 157 of file SerializationTests\&.cs\&.
.SS "void cslalighttest\&.Serialization\&.SerializationTests\&.SerializeCriteriaSuccess ()"

.PP
Definition at line 61 of file SerializationTests\&.cs\&.
.SS "void cslalighttest\&.Serialization\&.SerializationTests\&.SerializeMobileListWithPrimitiveTypes ()"

.PP
Definition at line 177 of file SerializationTests\&.cs\&.
.SS "void cslalighttest\&.Serialization\&.SerializationTests\&.SerializeWithNullArgumentShouldNotThrowException ()"

.PP
Definition at line 36 of file SerializationTests\&.cs\&.
.SS "void cslalighttest\&.Serialization\&.SerializationTests\&.TestSerializationCslaBinaryReaderWriter ()"

.PP
Definition at line 577 of file SerializationTests\&.cs\&.
.SS "void cslalighttest\&.Serialization\&.SerializationTests\&.TestSerializationCslaBinaryReaderWriterList ()"

.PP
Definition at line 512 of file SerializationTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
