.TH "Csla.Test.GraphMerge.Foo" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.GraphMerge.Foo
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.BusinessBase< Foo >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFoo\fP ()"
.br
.ti -1c
.RI "void \fBAddChild\fP ()"
.br
.ti -1c
.RI "void \fBMockUpdated\fP ()"
.br
.ti -1c
.RI "void \fBMarkForDelete\fP ()"
.br
.ti -1c
.RI "void \fBMockDeleted\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static readonly \fBPropertyInfo\fP< string > \fBNameProperty\fP"
.br
.ti -1c
.RI "static readonly \fBPropertyInfo\fP< \fBFoo\fP > \fBChildProperty\fP = RegisterProperty<\fBFoo\fP>(c => c\&.Child)"
.br
.ti -1c
.RI "static readonly \fBPropertyInfo\fP< \fBFooList\fP > \fBChildListProperty\fP = RegisterProperty<\fBFooList\fP>(c => c\&.ChildList)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBAddBusinessRules\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBName\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBFoo\fP \fBChild\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBFooList\fP \fBChildList\fP\fC [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 12 of file TestClasses\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Csla\&.Test\&.GraphMerge\&.Foo\&.Foo ()"

.PP
Definition at line 14 of file TestClasses\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override void Csla\&.Test\&.GraphMerge\&.Foo\&.AddBusinessRules ()\fC [protected]\fP"

.PP
Definition at line 72 of file TestClasses\&.cs\&.
.SS "void Csla\&.Test\&.GraphMerge\&.Foo\&.AddChild ()"

.PP
Definition at line 41 of file TestClasses\&.cs\&.
.SS "void Csla\&.Test\&.GraphMerge\&.Foo\&.MarkForDelete ()"

.PP
Definition at line 56 of file TestClasses\&.cs\&.
.SS "void Csla\&.Test\&.GraphMerge\&.Foo\&.MockDeleted ()"

.PP
Definition at line 64 of file TestClasses\&.cs\&.
.SS "void Csla\&.Test\&.GraphMerge\&.Foo\&.MockUpdated ()"

.PP
Definition at line 48 of file TestClasses\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "readonly \fBPropertyInfo\fP<\fBFooList\fP> Csla\&.Test\&.GraphMerge\&.Foo\&.ChildListProperty = RegisterProperty<\fBFooList\fP>(c => c\&.ChildList)\fC [static]\fP"

.PP
Definition at line 34 of file TestClasses\&.cs\&.
.SS "readonly \fBPropertyInfo\fP<\fBFoo\fP> Csla\&.Test\&.GraphMerge\&.Foo\&.ChildProperty = RegisterProperty<\fBFoo\fP>(c => c\&.Child)\fC [static]\fP"

.PP
Definition at line 27 of file TestClasses\&.cs\&.
.SS "readonly \fBPropertyInfo\fP<string> Csla\&.Test\&.GraphMerge\&.Foo\&.NameProperty\fC [static]\fP"
\fBInitial value:\fP
.PP
.nf
= 
      RegisterProperty<string>(c => c\&.Name)
.fi
.PP
Definition at line 19 of file TestClasses\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "\fBFoo\fP Csla\&.Test\&.GraphMerge\&.Foo\&.Child\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 28 of file TestClasses\&.cs\&.
.SS "\fBFooList\fP Csla\&.Test\&.GraphMerge\&.Foo\&.ChildList\fC [get]\fP"

.PP
Definition at line 35 of file TestClasses\&.cs\&.
.SS "string Csla\&.Test\&.GraphMerge\&.Foo\&.Name\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 21 of file TestClasses\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
