.TH "Csla.Test.Data.DataPortalTestDatabaseEntities" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.Data.DataPortalTestDatabaseEntities \- No Metadata Documentation available\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits ObjectContext\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDataPortalTestDatabaseEntities\fP ()"
.br
.RI "Initializes a new \fBDataPortalTestDatabaseEntities\fP object using the connection string found in the '\fBDataPortalTestDatabaseEntities\fP' section of the application configuration file\&. "
.ti -1c
.RI "\fBDataPortalTestDatabaseEntities\fP (string connectionString)"
.br
.RI "Initialize a new \fBDataPortalTestDatabaseEntities\fP object\&. "
.ti -1c
.RI "\fBDataPortalTestDatabaseEntities\fP (EntityConnection connection)"
.br
.RI "Initialize a new \fBDataPortalTestDatabaseEntities\fP object\&. "
.ti -1c
.RI "void \fBAddToTable2\fP (\fBTable2\fP table2)"
.br
.RI "Deprecated Method for adding a new object to the \fBTable2\fP EntitySet\&. Consider using the \&.Add method of the associated ObjectSet<T> property instead\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "ObjectSet< \fBTable2\fP > \fBTable2\fP\fC [get]\fP"
.br
.RI "No Metadata Documentation available\&. "
.in -1c
.SH "Detailed Description"
.PP 
No Metadata Documentation available\&. 


.PP
Definition at line 27 of file TestEFContext\&.Designer\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Csla\&.Test\&.Data\&.DataPortalTestDatabaseEntities\&.DataPortalTestDatabaseEntities ()"

.PP
Initializes a new \fBDataPortalTestDatabaseEntities\fP object using the connection string found in the '\fBDataPortalTestDatabaseEntities\fP' section of the application configuration file\&. 
.PP
Definition at line 34 of file TestEFContext\&.Designer\&.cs\&.
.SS "Csla\&.Test\&.Data\&.DataPortalTestDatabaseEntities\&.DataPortalTestDatabaseEntities (string connectionString)"

.PP
Initialize a new \fBDataPortalTestDatabaseEntities\fP object\&. 
.PP
Definition at line 42 of file TestEFContext\&.Designer\&.cs\&.
.SS "Csla\&.Test\&.Data\&.DataPortalTestDatabaseEntities\&.DataPortalTestDatabaseEntities (EntityConnection connection)"

.PP
Initialize a new \fBDataPortalTestDatabaseEntities\fP object\&. 
.PP
Definition at line 50 of file TestEFContext\&.Designer\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Csla\&.Test\&.Data\&.DataPortalTestDatabaseEntities\&.AddToTable2 (\fBTable2\fP table2)"

.PP
Deprecated Method for adding a new object to the \fBTable2\fP EntitySet\&. Consider using the \&.Add method of the associated ObjectSet<T> property instead\&. 
.PP
Definition at line 88 of file TestEFContext\&.Designer\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "ObjectSet<\fBTable2\fP> Csla\&.Test\&.Data\&.DataPortalTestDatabaseEntities\&.Table2\fC [get]\fP"

.PP
No Metadata Documentation available\&. 
.PP
Definition at line 68 of file TestEFContext\&.Designer\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
