.TH "Csla.Test.ValidationRules.HasPerTypeRules2" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.ValidationRules.HasPerTypeRules2
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.BusinessBase< HasPerTypeRules2 >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBValidate\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBPropertyInfo\fP< string > \fBTestProperty\fP = RegisterProperty<string>(c => c\&.Test)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBAddBusinessRules\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBTest\fP\fC [get, set]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 38 of file HasPerTypeClasses\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override void Csla\&.Test\&.ValidationRules\&.HasPerTypeRules2\&.AddBusinessRules ()\fC [protected]\fP"

.PP
Definition at line 47 of file HasPerTypeClasses\&.cs\&.
.SS "void Csla\&.Test\&.ValidationRules\&.HasPerTypeRules2\&.Validate ()"

.PP
Definition at line 56 of file HasPerTypeClasses\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBPropertyInfo\fP<string> Csla\&.Test\&.ValidationRules\&.HasPerTypeRules2\&.TestProperty = RegisterProperty<string>(c => c\&.Test)\fC [static]\fP"

.PP
Definition at line 40 of file HasPerTypeClasses\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "string Csla\&.Test\&.ValidationRules\&.HasPerTypeRules2\&.Test\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 41 of file HasPerTypeClasses\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
