.TH "Csla.Threading.AsyncManualResetEvent" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Threading.AsyncManualResetEvent \- Async/await implementation of a ManualResetEvent  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "Task \fBWaitAsync\fP ()"
.br
.RI "Get awaitable task for the event "
.ti -1c
.RI "void \fBSet\fP ()"
.br
.RI "Set the event, unblocking any code awaiting the event "
.ti -1c
.RI "void \fBReset\fP ()"
.br
.RI "Reset the event, preparing it for reuse "
.in -1c
.SH "Detailed Description"
.PP 
Async/await implementation of a ManualResetEvent 


.PP
Definition at line 19 of file AsyncManualResetEvent\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Csla\&.Threading\&.AsyncManualResetEvent\&.Reset ()"

.PP
Reset the event, preparing it for reuse 
.PP
Definition at line 36 of file AsyncManualResetEvent\&.cs\&.
.SS "void Csla\&.Threading\&.AsyncManualResetEvent\&.Set ()"

.PP
Set the event, unblocking any code awaiting the event 
.PP
Definition at line 31 of file AsyncManualResetEvent\&.cs\&.
.SS "Task Csla\&.Threading\&.AsyncManualResetEvent\&.WaitAsync ()"

.PP
Get awaitable task for the event 
.PP
Definition at line 26 of file AsyncManualResetEvent\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
