.TH "Csla.Analyzers.Tests.DoesChildOperationHaveRunLocalRemoveAttributeCodeFixTests" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Analyzers.Tests.DoesChildOperationHaveRunLocalRemoveAttributeCodeFixTests
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBVerifyGetFixableDiagnosticIds\fP ()"
.br
.ti -1c
.RI "async Task \fBVerifyGetFixesWhenRunLocalIsStandalone\fP ()"
.br
.ti -1c
.RI "async Task \fBVerifyGetFixesWhenRunLocalIsEmbeddedInList\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 16 of file DoesChildOperationHaveRunLocalRemoveAttributeCodeFixTests\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Csla\&.Analyzers\&.Tests\&.DoesChildOperationHaveRunLocalRemoveAttributeCodeFixTests\&.VerifyGetFixableDiagnosticIds ()"

.PP
Definition at line 19 of file DoesChildOperationHaveRunLocalRemoveAttributeCodeFixTests\&.cs\&.
.SS "async Task Csla\&.Analyzers\&.Tests\&.DoesChildOperationHaveRunLocalRemoveAttributeCodeFixTests\&.VerifyGetFixesWhenRunLocalIsEmbeddedInList ()"

.PP
Definition at line 66 of file DoesChildOperationHaveRunLocalRemoveAttributeCodeFixTests\&.cs\&.
.SS "async Task Csla\&.Analyzers\&.Tests\&.DoesChildOperationHaveRunLocalRemoveAttributeCodeFixTests\&.VerifyGetFixesWhenRunLocalIsStandalone ()"

.PP
Definition at line 30 of file DoesChildOperationHaveRunLocalRemoveAttributeCodeFixTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
