.TH "Csla.Core.MetaPropertyChangedEventArgs" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Core.MetaPropertyChangedEventArgs \- Used to distinguish Meta \fBProperties\fP  

.SH SYNOPSIS
.br
.PP
.PP
Inherits PropertyChangedEventArgs\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMetaPropertyChangedEventArgs\fP (string propertyName)"
.br
.RI "Property changed event args "
.in -1c
.SH "Detailed Description"
.PP 
Used to distinguish Meta \fBProperties\fP 


.PP
Definition at line 12 of file MetaPropertyChangedEventArgs\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Csla\&.Core\&.MetaPropertyChangedEventArgs\&.MetaPropertyChangedEventArgs (string propertyName)"

.PP
Property changed event args 
.PP
\fBParameters\fP
.RS 4
\fIpropertyName\fP Name of changed property\&.
.RE
.PP

.PP
Definition at line 18 of file MetaPropertyChangedEventArgs\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
