.TH "Csla.Test.MethodCaller.PropertyTests" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.MethodCaller.PropertyTests
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBPropertyGetNoSetSuccess\fP ()"
.br
.ti -1c
.RI "void \fBPropertyGetWithSetSuccess\fP ()"
.br
.ti -1c
.RI "void \fBPropertyGetOnlySetFail\fP ()"
.br
.ti -1c
.RI "void \fBPropertySetOnlyGetFail\fP ()"
.br
.ti -1c
.RI "void \fBPropertySetWithGetSuccess\fP ()"
.br
.ti -1c
.RI "void \fBPropertySetNoGetSuccess\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBTest1\fP\fC [get]\fP"
.br
.ti -1c
.RI "string \fBTest2\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBTest3\fP\fC [set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 28 of file PropertyTests\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Csla\&.Test\&.MethodCaller\&.PropertyTests\&.PropertyGetNoSetSuccess ()"

.PP
Definition at line 40 of file PropertyTests\&.cs\&.
.SS "void Csla\&.Test\&.MethodCaller\&.PropertyTests\&.PropertyGetOnlySetFail ()"

.PP
Definition at line 57 of file PropertyTests\&.cs\&.
.SS "void Csla\&.Test\&.MethodCaller\&.PropertyTests\&.PropertyGetWithSetSuccess ()"

.PP
Definition at line 48 of file PropertyTests\&.cs\&.
.SS "void Csla\&.Test\&.MethodCaller\&.PropertyTests\&.PropertySetNoGetSuccess ()"

.PP
Definition at line 78 of file PropertyTests\&.cs\&.
.SS "void Csla\&.Test\&.MethodCaller\&.PropertyTests\&.PropertySetOnlyGetFail ()"

.PP
Definition at line 64 of file PropertyTests\&.cs\&.
.SS "void Csla\&.Test\&.MethodCaller\&.PropertyTests\&.PropertySetWithGetSuccess ()"

.PP
Definition at line 70 of file PropertyTests\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "string Csla\&.Test\&.MethodCaller\&.PropertyTests\&.Test1\fC [get]\fP"

.PP
Definition at line 33 of file PropertyTests\&.cs\&.
.SS "string Csla\&.Test\&.MethodCaller\&.PropertyTests\&.Test2\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 35 of file PropertyTests\&.cs\&.
.SS "string Csla\&.Test\&.MethodCaller\&.PropertyTests\&.Test3\fC [set]\fP"

.PP
Definition at line 37 of file PropertyTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
