.TH "Csla.Test.PropertyGetSet.EditableGetSetNFI" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.PropertyGetSet.EditableGetSetNFI
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.Test\&.PropertyGetSet\&.EditableGetSetNFIBase< EditableGetSetNFI >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "new void \fBMarkClean\fP ()"
.br
.ti -1c
.RI "\fBEditableGetSetNFI\fP ()"
.br
.ti -1c
.RI "\fBEditableGetSetNFI\fP (bool isChild)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBEditableGetSet\fP \fBGetObject\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBPropertyInfo\fP< string > \fBDataProperty\fP = RegisterProperty(new \fBPropertyInfo\fP<string>('Data', '\fBData\fP'))"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBDataPortal_Insert\fP ()"
.br
.ti -1c
.RI "void \fBDataPortal_Update\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBData\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "new int \fBEditLevel\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 291 of file EditableGetSet\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Csla\&.Test\&.PropertyGetSet\&.EditableGetSetNFI\&.EditableGetSetNFI ()"

.PP
Definition at line 310 of file EditableGetSet\&.cs\&.
.SS "Csla\&.Test\&.PropertyGetSet\&.EditableGetSetNFI\&.EditableGetSetNFI (bool isChild)"

.PP
Definition at line 316 of file EditableGetSet\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Csla\&.Test\&.PropertyGetSet\&.EditableGetSetNFI\&.DataPortal_Insert ()\fC [protected]\fP"

.PP
Definition at line 341 of file EditableGetSet\&.cs\&.
.SS "void Csla\&.Test\&.PropertyGetSet\&.EditableGetSetNFI\&.DataPortal_Update ()\fC [protected]\fP"

.PP
Definition at line 346 of file EditableGetSet\&.cs\&.
.SS "static \fBEditableGetSet\fP Csla\&.Test\&.PropertyGetSet\&.EditableGetSetNFI\&.GetObject ()\fC [static]\fP"

.PP
Definition at line 327 of file EditableGetSet\&.cs\&.
.SS "new void Csla\&.Test\&.PropertyGetSet\&.EditableGetSetNFI\&.MarkClean ()"

.PP
Definition at line 305 of file EditableGetSet\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBPropertyInfo\fP<string> Csla\&.Test\&.PropertyGetSet\&.EditableGetSetNFI\&.DataProperty = RegisterProperty(new \fBPropertyInfo\fP<string>('Data', '\fBData\fP'))\fC [static]\fP"

.PP
Definition at line 293 of file EditableGetSet\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "string Csla\&.Test\&.PropertyGetSet\&.EditableGetSetNFI\&.Data\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 294 of file EditableGetSet\&.cs\&.
.SS "new int Csla\&.Test\&.PropertyGetSet\&.EditableGetSetNFI\&.EditLevel\fC [get]\fP"

.PP
Definition at line 300 of file EditableGetSet\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
