.TH "Csla.Core.MobileObservableCollection< T >.LoadListModeObject" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Core.MobileObservableCollection< T >.LoadListModeObject \- Class that allows setting of property values on current business object without raising PropertyChanged events and checking user rights\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits IDisposable\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLoadListModeObject\fP (\fBIMobileList\fP target)"
.br
.RI "Create instance of type "
.ti -1c
.RI "void \fBDispose\fP ()"
.br
.RI "Disposes the object\&. "
.in -1c
.SH "Detailed Description"
.PP 
Class that allows setting of property values on current business object without raising PropertyChanged events and checking user rights\&. 


.PP
Definition at line 75 of file MobileObservableCollection\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBCsla\&.Core\&.MobileObservableCollection\fP< T >\&.LoadListModeObject\&.LoadListModeObject (\fBIMobileList\fP target)"

.PP
Create instance of type 
.PP
\fBParameters\fP
.RS 4
\fItarget\fP List object
.RE
.PP

.PP
Definition at line 83 of file MobileObservableCollection\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void \fBCsla\&.Core\&.MobileObservableCollection\fP< T >\&.LoadListModeObject\&.Dispose ()"

.PP
Disposes the object\&. 
.PP
Definition at line 93 of file MobileObservableCollection\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
