.TH "Csla.Test.DataPortalChild.ChildList" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.DataPortalChild.ChildList
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.BusinessBindingListBase< ChildList, Child >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBChildList\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBChildList\fP \fBGetList\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBChild_Fetch\fP ()"
.br
.ti -1c
.RI "override void \fBChild_Update\fP (params object[] p)"
.br
.RI "Saves all items in the list, automatically performing insert, update or delete operations as necessary\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "object \fBMyParent\fP\fC [get]\fP"
.br
.ti -1c
.RI "string \fBStatus\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 16 of file Csla\&.test/DataPortalChild/ChildList\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Csla\&.Test\&.DataPortalChild\&.ChildList\&.ChildList ()"

.PP
Definition at line 23 of file Csla\&.test/DataPortalChild/ChildList\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Csla\&.Test\&.DataPortalChild\&.ChildList\&.Child_Fetch ()\fC [protected]\fP"

.PP
Definition at line 39 of file Csla\&.test/DataPortalChild/ChildList\&.cs\&.
.SS "override void Csla\&.Test\&.DataPortalChild\&.ChildList\&.Child_Update (params object[] parameters)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Saves all items in the list, automatically performing insert, update or delete operations as necessary\&. 
.PP
\fBParameters\fP
.RS 4
\fIparameters\fP Optional parameters passed to child update methods\&. 
.RE
.PP

.PP
Reimplemented from \fBCsla\&.BusinessBindingListBase< ChildList, Child >\fP\&.
.PP
Definition at line 44 of file Csla\&.test/DataPortalChild/ChildList\&.cs\&.
.SS "static \fBChildList\fP Csla\&.Test\&.DataPortalChild\&.ChildList\&.GetList ()\fC [static]\fP"

.PP
Definition at line 18 of file Csla\&.test/DataPortalChild/ChildList\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "object Csla\&.Test\&.DataPortalChild\&.ChildList\&.MyParent\fC [get]\fP"

.PP
Definition at line 28 of file Csla\&.test/DataPortalChild/ChildList\&.cs\&.
.SS "string Csla\&.Test\&.DataPortalChild\&.ChildList\&.Status\fC [get]\fP"

.PP
Definition at line 34 of file Csla\&.test/DataPortalChild/ChildList\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
