.TH "Csla.Test.Basic.GenRootBase" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.Basic.GenRootBase
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.BusinessBase< GenRoot >\fP, and \fBCsla\&.BusinessBase< GenRoot >\fP\&.
.PP
Inherited by \fBCsla\&.Test\&.Basic\&.GenRoot\fP, and \fBCsla\&.Test\&.Basic\&.GenRoot\fP\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBGenRoot\fP \fBNewRoot\fP ()"
.br
.ti -1c
.RI "static \fBGenRoot\fP \fBGetRoot\fP (string data)"
.br
.ti -1c
.RI "static void \fBDeleteRoot\fP (string data)"
.br
.ti -1c
.RI "static \fBGenRoot\fP \fBNewRoot\fP ()"
.br
.ti -1c
.RI "static \fBGenRoot\fP \fBGetRoot\fP (string data)"
.br
.ti -1c
.RI "static void \fBDeleteRoot\fP (string data)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override object \fBGetIdValue\fP ()"
.br
.RI "Override this method to return a unique identifying value for this object\&. "
.ti -1c
.RI "void \fBDataPortal_Fetch\fP (object criteria)"
.br
.ti -1c
.RI "void \fBDataPortal_Update\fP ()"
.br
.ti -1c
.RI "void \fBDataPortal_Delete\fP (object Criteria)"
.br
.ti -1c
.RI "override object \fBGetIdValue\fP ()"
.br
.RI "Override this method to return a unique identifying value for this object\&. "
.ti -1c
.RI "void \fBDataPortal_Fetch\fP (object criteria)"
.br
.ti -1c
.RI "void \fBDataPortal_Update\fP ()"
.br
.ti -1c
.RI "void \fBDataPortal_Delete\fP (object Criteria)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBData\fP\fC [get, set]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 15 of file csla\&.netcore\&.test/Basic/GenRootBase\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Csla\&.Test\&.Basic\&.GenRootBase\&.DataPortal_Delete (object Criteria)\fC [protected]\fP"

.PP
Definition at line 121 of file csla\&.netcore\&.test/Basic/GenRootBase\&.cs\&.
.SS "void Csla\&.Test\&.Basic\&.GenRootBase\&.DataPortal_Delete (object Criteria)\fC [protected]\fP"

.PP
Definition at line 108 of file Csla\&.test/Basic/GenRootBase\&.cs\&.
.SS "void Csla\&.Test\&.Basic\&.GenRootBase\&.DataPortal_Fetch (object criteria)\fC [protected]\fP"

.PP
Definition at line 79 of file csla\&.netcore\&.test/Basic/GenRootBase\&.cs\&.
.SS "void Csla\&.Test\&.Basic\&.GenRootBase\&.DataPortal_Fetch (object criteria)\fC [protected]\fP"

.PP
Definition at line 74 of file Csla\&.test/Basic/GenRootBase\&.cs\&.
.SS "void Csla\&.Test\&.Basic\&.GenRootBase\&.DataPortal_Update ()\fC [protected]\fP"

.PP
Definition at line 90 of file csla\&.netcore\&.test/Basic/GenRootBase\&.cs\&.
.SS "void Csla\&.Test\&.Basic\&.GenRootBase\&.DataPortal_Update ()\fC [protected]\fP"

.PP
Definition at line 83 of file Csla\&.test/Basic/GenRootBase\&.cs\&.
.SS "static void Csla\&.Test\&.Basic\&.GenRootBase\&.DeleteRoot (string data)\fC [static]\fP"

.PP
Definition at line 63 of file csla\&.netcore\&.test/Basic/GenRootBase\&.cs\&.
.SS "static void Csla\&.Test\&.Basic\&.GenRootBase\&.DeleteRoot (string data)\fC [static]\fP"

.PP
Definition at line 62 of file Csla\&.test/Basic/GenRootBase\&.cs\&.
.SS "override object Csla\&.Test\&.Basic\&.GenRootBase\&.GetIdValue ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Override this method to return a unique identifying value for this object\&. 
.PP
Reimplemented from \fBCsla\&.BusinessBase< GenRoot >\fP\&.
.PP
Definition at line 19 of file csla\&.netcore\&.test/Basic/GenRootBase\&.cs\&.
.SS "override object Csla\&.Test\&.Basic\&.GenRootBase\&.GetIdValue ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Override this method to return a unique identifying value for this object\&. 
.PP
Reimplemented from \fBCsla\&.BusinessBase< GenRoot >\fP\&.
.PP
Definition at line 19 of file Csla\&.test/Basic/GenRootBase\&.cs\&.
.SS "static \fBGenRoot\fP Csla\&.Test\&.Basic\&.GenRootBase\&.GetRoot (string data)\fC [static]\fP"

.PP
Definition at line 58 of file csla\&.netcore\&.test/Basic/GenRootBase\&.cs\&.
.SS "static \fBGenRoot\fP Csla\&.Test\&.Basic\&.GenRootBase\&.GetRoot (string data)\fC [static]\fP"

.PP
Definition at line 57 of file Csla\&.test/Basic/GenRootBase\&.cs\&.
.SS "static \fBGenRoot\fP Csla\&.Test\&.Basic\&.GenRootBase\&.NewRoot ()\fC [static]\fP"

.PP
Definition at line 53 of file csla\&.netcore\&.test/Basic/GenRootBase\&.cs\&.
.SS "static \fBGenRoot\fP Csla\&.Test\&.Basic\&.GenRootBase\&.NewRoot ()\fC [static]\fP"

.PP
Definition at line 52 of file Csla\&.test/Basic/GenRootBase\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "string Csla\&.Test\&.Basic\&.GenRootBase\&.Data\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 24 of file csla\&.netcore\&.test/Basic/GenRootBase\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
