.TH "Csla.Windows.ReadWriteAuthorization" 3 "Thu Jul 22 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Windows.ReadWriteAuthorization \- \fBWindows\fP Forms extender control that automatically enables and disables detail form controls based on the authorization settings from a CSLA \&.NET business object\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits System\&.ComponentModel\&.Component, and IExtenderProvider\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBReadWriteAuthorization\fP (IContainer container)"
.br
.RI "Creates an instance of the object\&. "
.ti -1c
.RI "bool \fBCanExtend\fP (object extendee)"
.br
.RI "Gets a value indicating whether the extender control can extend the specified control\&. "
.ti -1c
.RI "bool \fBGetApplyAuthorization\fP (Control source)"
.br
.RI "Gets the custom ApplyAuthorization extender property added to extended controls\&. "
.ti -1c
.RI "void \fBSetApplyAuthorization\fP (Control source, bool value)"
.br
.RI "Sets the custom ApplyAuthorization extender property added to extended controls\&. "
.ti -1c
.RI "void \fBResetControlAuthorization\fP ()"
.br
.RI "Causes the \fBReadWriteAuthorization\fP control to apply authorization rules from the business object to all extended controls on the form\&. "
.in -1c
.SH "Detailed Description"
.PP 
\fBWindows\fP Forms extender control that automatically enables and disables detail form controls based on the authorization settings from a CSLA \&.NET business object\&. 


.PP
Definition at line 26 of file ReadWriteAuthorization\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Csla\&.Windows\&.ReadWriteAuthorization\&.ReadWriteAuthorization (IContainer container)"

.PP
Creates an instance of the object\&. 
.PP
\fBParameters\fP
.RS 4
\fIcontainer\fP The container of the control\&.
.RE
.PP

.PP
Definition at line 42 of file ReadWriteAuthorization\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "bool Csla\&.Windows\&.ReadWriteAuthorization\&.CanExtend (object extendee)"

.PP
Gets a value indicating whether the extender control can extend the specified control\&. 
.PP
\fBParameters\fP
.RS 4
\fIextendee\fP The control to be extended\&.
.RE
.PP
.PP
Any control implementing either a ReadOnly property or Enabled property can be extended\&. 
.PP
Definition at line 54 of file ReadWriteAuthorization\&.cs\&.
.SS "bool Csla\&.Windows\&.ReadWriteAuthorization\&.GetApplyAuthorization (Control source)"

.PP
Gets the custom ApplyAuthorization extender property added to extended controls\&. 
.PP
\fBParameters\fP
.RS 4
\fIsource\fP Control being extended\&.
.RE
.PP

.PP
Definition at line 69 of file ReadWriteAuthorization\&.cs\&.
.SS "void Csla\&.Windows\&.ReadWriteAuthorization\&.ResetControlAuthorization ()"

.PP
Causes the \fBReadWriteAuthorization\fP control to apply authorization rules from the business object to all extended controls on the form\&. Call this method to refresh the display of detail controls on the form any time the authorization rules may have changed\&. Examples include: after a user logs in or out, and after an object has been updated, inserted, deleted or retrieved from the database\&. 
.PP
Definition at line 109 of file ReadWriteAuthorization\&.cs\&.
.SS "void Csla\&.Windows\&.ReadWriteAuthorization\&.SetApplyAuthorization (Control source, bool value)"

.PP
Sets the custom ApplyAuthorization extender property added to extended controls\&. 
.PP
\fBParameters\fP
.RS 4
\fIsource\fP Control being extended\&.
.br
\fIvalue\fP New value of property\&.
.RE
.PP

.PP
Definition at line 85 of file ReadWriteAuthorization\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
