.TH "BusinessBase.cs" 3 "Thu Jul 22 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BusinessBase.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCsla\&.Core\&.BusinessBase\fP"
.br
.RI "This is the non-generic base class from which most business objects will be derived\&. "
.ti -1c
.RI "class \fBCsla\&.Core\&.BusinessBase\&.BypassPropertyChecksObject\fP"
.br
.RI "Class that allows setting of property values on current business object without raising PropertyChanged events and checking user rights\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBCsla\fP"
.br
.ti -1c
.RI "namespace \fBCsla\&.Core\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
