.TH "Csla.Core.MobileObject" 3 "Thu Jul 22 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Core.MobileObject \- Inherit from this base class to easily create a serializable class\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.Serialization\&.Mobile\&.IMobileObject\fP\&.
.PP
Inherited by \fBCsla\&.Core\&.BindableBase\fP, \fBCsla\&.Core\&.FieldManager\&.FieldDataManager\fP, \fBCsla\&.Core\&.ManagedObjectBase\fP, \fBCsla\&.NameValueListBase< K, V >\&.NameValuePair\fP, \fBCsla\&.Rules\&.BrokenRule\fP, \fBCsla\&.Rules\&.BusinessRules\fP, \fBCsla\&.Server\&.EmptyCriteria\fP, and \fBCsla\&.Server\&.NullCriteria\fP\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBOnGetState\fP (\fBSerializationInfo\fP info, \fBStateMode\fP mode)"
.br
.RI "Override this method to insert your field values into the MobileFormatter serialzation stream\&. "
.ti -1c
.RI "virtual void \fBOnGetChildren\fP (\fBSerializationInfo\fP info, \fBMobileFormatter\fP formatter)"
.br
.RI "Override this method to insert your child object references into the MobileFormatter serialzation stream\&. "
.ti -1c
.RI "virtual void \fBOnSetState\fP (\fBSerializationInfo\fP info, \fBStateMode\fP mode)"
.br
.RI "Override this method to retrieve your field values from the MobileFormatter serialzation stream\&. "
.ti -1c
.RI "virtual void \fBOnSetChildren\fP (\fBSerializationInfo\fP info, \fBMobileFormatter\fP formatter)"
.br
.RI "Override this method to retrieve your child object references from the MobileFormatter serialzation stream\&. "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Inherit from this base class to easily create a serializable class\&. 


.PP
Definition at line 19 of file MobileObject\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual void Csla\&.Core\&.MobileObject\&.OnGetChildren (\fBSerializationInfo\fP info, \fBMobileFormatter\fP formatter)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Override this method to insert your child object references into the MobileFormatter serialzation stream\&. 
.PP
\fBParameters\fP
.RS 4
\fIinfo\fP Object containing the data to serialize\&. 
.br
\fIformatter\fP Reference to MobileFormatter instance\&. Use this to convert child references to/from reference id values\&. 
.RE
.PP

.PP
Reimplemented in \fBCsla\&.Rules\&.BusinessRules\fP, \fBCsla\&.Core\&.ManagedObjectBase\fP, and \fBCsla\&.Core\&.FieldManager\&.FieldDataManager\fP\&.
.PP
Definition at line 59 of file MobileObject\&.cs\&.
.SS "virtual void Csla\&.Core\&.MobileObject\&.OnGetState (\fBSerializationInfo\fP info, \fBStateMode\fP mode)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Override this method to insert your field values into the MobileFormatter serialzation stream\&. 
.PP
\fBParameters\fP
.RS 4
\fIinfo\fP Object containing the data to serialize\&. 
.br
\fImode\fP The StateMode indicating why this method was invoked\&. 
.RE
.PP

.PP
Reimplemented in \fBCsla\&.Rules\&.BusinessRules\fP, \fBCsla\&.Rules\&.BrokenRule\fP, \fBCsla\&.NameValueListBase< K, V >\&.NameValuePair\fP, \fBCsla\&.Core\&.UndoableBase\fP, and \fBCsla\&.Core\&.FieldManager\&.FieldDataManager\fP\&.
.PP
Definition at line 44 of file MobileObject\&.cs\&.
.SS "virtual void Csla\&.Core\&.MobileObject\&.OnSetChildren (\fBSerializationInfo\fP info, \fBMobileFormatter\fP formatter)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Override this method to retrieve your child object references from the MobileFormatter serialzation stream\&. 
.PP
\fBParameters\fP
.RS 4
\fIinfo\fP Object containing the data to serialize\&. 
.br
\fIformatter\fP Reference to MobileFormatter instance\&. Use this to convert child references to/from reference id values\&. 
.RE
.PP

.PP
Reimplemented in \fBCsla\&.Rules\&.BusinessRules\fP, \fBCsla\&.Core\&.ManagedObjectBase\fP, and \fBCsla\&.Core\&.FieldManager\&.FieldDataManager\fP\&.
.PP
Definition at line 102 of file MobileObject\&.cs\&.
.SS "virtual void Csla\&.Core\&.MobileObject\&.OnSetState (\fBSerializationInfo\fP info, \fBStateMode\fP mode)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Override this method to retrieve your field values from the MobileFormatter serialzation stream\&. 
.PP
\fBParameters\fP
.RS 4
\fIinfo\fP Object containing the data to serialize\&. 
.br
\fImode\fP The StateMode indicating why this method was invoked\&. 
.RE
.PP

.PP
Reimplemented in \fBCsla\&.Rules\&.BusinessRules\fP, \fBCsla\&.Rules\&.BrokenRule\fP, \fBCsla\&.NameValueListBase< K, V >\&.NameValuePair\fP, \fBCsla\&.Core\&.UndoableBase\fP, and \fBCsla\&.Core\&.FieldManager\&.FieldDataManager\fP\&.
.PP
Definition at line 87 of file MobileObject\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
