.TH "Csla.Test.DataPortalTest.PrimitiveCriteriaSingle" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.DataPortalTest.PrimitiveCriteriaSingle
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.BusinessBase< PrimitiveCriteriaSingle >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPrimitiveCriteriaSingle\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static readonly \fBPropertyInfo\fP< int > \fBIdProperty\fP = RegisterProperty<int>(c => c\&.Id)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override object \fBGetIdValue\fP ()"
.br
.RI "Override this method to return a unique identifying value for this object\&. "
.ti -1c
.RI "void \fBDataPortal_Create\fP (int id)"
.br
.ti -1c
.RI "void \fBDataPortal_Insert\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBId\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBMethodCalled\fP\fC [get, set]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 21 of file PrimitiveCriteriaSingle\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Csla\&.Test\&.DataPortalTest\&.PrimitiveCriteriaSingle\&.PrimitiveCriteriaSingle ()"

.PP
Definition at line 46 of file PrimitiveCriteriaSingle\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Csla\&.Test\&.DataPortalTest\&.PrimitiveCriteriaSingle\&.DataPortal_Create (int id)\fC [protected]\fP"

.PP
Definition at line 53 of file PrimitiveCriteriaSingle\&.cs\&.
.SS "void Csla\&.Test\&.DataPortalTest\&.PrimitiveCriteriaSingle\&.DataPortal_Insert ()\fC [protected]\fP"

.PP
Definition at line 107 of file PrimitiveCriteriaSingle\&.cs\&.
.SS "override object Csla\&.Test\&.DataPortalTest\&.PrimitiveCriteriaSingle\&.GetIdValue ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Override this method to return a unique identifying value for this object\&. 
.PP
Reimplemented from \fBCsla\&.BusinessBase< PrimitiveCriteriaSingle >\fP\&.
.PP
Definition at line 39 of file PrimitiveCriteriaSingle\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "readonly \fBPropertyInfo\fP<int> Csla\&.Test\&.DataPortalTest\&.PrimitiveCriteriaSingle\&.IdProperty = RegisterProperty<int>(c => c\&.Id)\fC [static]\fP"

.PP
Definition at line 25 of file PrimitiveCriteriaSingle\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "int Csla\&.Test\&.DataPortalTest\&.PrimitiveCriteriaSingle\&.Id\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 26 of file PrimitiveCriteriaSingle\&.cs\&.
.SS "string Csla\&.Test\&.DataPortalTest\&.PrimitiveCriteriaSingle\&.MethodCalled\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 33 of file PrimitiveCriteriaSingle\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
