.TH "Csla.Test.ObjectFactory.ObjectFactoryLoader" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.ObjectFactory.ObjectFactoryLoader
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.Server\&.IObjectFactoryLoader\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBObjectFactoryLoader\fP ()"
.br
.ti -1c
.RI "\fBObjectFactoryLoader\fP (int mode)"
.br
.ti -1c
.RI "Type \fBGetFactoryType\fP (string factoryName)"
.br
.RI "Returns the type of the factory object\&. "
.ti -1c
.RI "object \fBGetFactory\fP (string factoryName)"
.br
.RI "Returns an \fBObjectFactory\fP object\&. "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 15 of file ObjectFactoryLoader\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Csla\&.Test\&.ObjectFactory\&.ObjectFactoryLoader\&.ObjectFactoryLoader ()"

.PP
Definition at line 19 of file ObjectFactoryLoader\&.cs\&.
.SS "Csla\&.Test\&.ObjectFactory\&.ObjectFactoryLoader\&.ObjectFactoryLoader (int mode)"

.PP
Definition at line 22 of file ObjectFactoryLoader\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "object Csla\&.Test\&.ObjectFactory\&.ObjectFactoryLoader\&.GetFactory (string factoryName)"

.PP
Returns an \fBObjectFactory\fP object\&. 
.PP
\fBParameters\fP
.RS 4
\fIfactoryName\fP Name of the factory to create, typically an assembly qualified type name\&. 
.RE
.PP

.PP
Implements \fBCsla\&.Server\&.IObjectFactoryLoader\fP\&.
.PP
Definition at line 57 of file ObjectFactoryLoader\&.cs\&.
.SS "Type Csla\&.Test\&.ObjectFactory\&.ObjectFactoryLoader\&.GetFactoryType (string factoryName)"

.PP
Returns the type of the factory object\&. 
.PP
\fBParameters\fP
.RS 4
\fIfactoryName\fP Name of the factory to create, typically an assembly qualified type name\&. 
.RE
.PP

.PP
Implements \fBCsla\&.Server\&.IObjectFactoryLoader\fP\&.
.PP
Definition at line 27 of file ObjectFactoryLoader\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
