.TH "Csla.Test.ValidationRules.HasRulesManager2.Criteria" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.ValidationRules.HasRulesManager2.Criteria
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.CriteriaBase< Criteria >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCriteria\fP ()"
.br
.ti -1c
.RI "\fBCriteria\fP (string name)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fB_name\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnGetState\fP (\fBSerializationInfo\fP info, \fBStateMode\fP mode)"
.br
.ti -1c
.RI "override void \fBOnSetState\fP (\fBCsla\&.Serialization\&.Mobile\&.SerializationInfo\fP info, \fBCsla\&.Core\&.StateMode\fP mode)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 34 of file HasRulesManager2\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Csla\&.Test\&.ValidationRules\&.HasRulesManager2\&.Criteria\&.Criteria ()"

.PP
Definition at line 38 of file HasRulesManager2\&.cs\&.
.SS "Csla\&.Test\&.ValidationRules\&.HasRulesManager2\&.Criteria\&.Criteria (string name)"

.PP
Definition at line 43 of file HasRulesManager2\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override void Csla\&.Test\&.ValidationRules\&.HasRulesManager2\&.Criteria\&.OnGetState (\fBSerializationInfo\fP info, \fBStateMode\fP mode)\fC [protected]\fP"

.PP
Definition at line 48 of file HasRulesManager2\&.cs\&.
.SS "override void Csla\&.Test\&.ValidationRules\&.HasRulesManager2\&.Criteria\&.OnSetState (\fBCsla\&.Serialization\&.Mobile\&.SerializationInfo\fP info, \fBCsla\&.Core\&.StateMode\fP mode)\fC [protected]\fP"

.PP
Definition at line 54 of file HasRulesManager2\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "string Csla\&.Test\&.ValidationRules\&.HasRulesManager2\&.Criteria\&._name"

.PP
Definition at line 36 of file HasRulesManager2\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
