.TH "Csla.Test.MethodCaller.MethodCallerTests" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.MethodCaller.MethodCallerTests
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBCallSuccess\fP ()"
.br
.ti -1c
.RI "void \fBCallException\fP ()"
.br
.ti -1c
.RI "void \fBCallInnerException\fP ()"
.br
.ti -1c
.RI "void \fBCallSuccessArrayParameters\fP ()"
.br
.ti -1c
.RI "void \fBCallSuccessParams\fP ()"
.br
.ti -1c
.RI "void \fBCallSuccessInheritedMethods\fP ()"
.br
.ti -1c
.RI "void \fBCallWithInvalidParameterTypeFails\fP ()"
.br
.ti -1c
.RI "void \fBCallWithValidParameterTypeSucceeds\fP ()"
.br
.ti -1c
.RI "void \fBfoo\fP (MemoryStream ms)"
.br
.ti -1c
.RI "void \fBDoSuccess\fP ()"
.br
.ti -1c
.RI "void \fBDoException\fP ()"
.br
.ti -1c
.RI "void \fBDoInnerException\fP ()"
.br
.ti -1c
.RI "int \fBGetData\fP (object rows)"
.br
.ti -1c
.RI "int \fBGetData\fP (params int[] rows)"
.br
.ti -1c
.RI "int \fBGetData\fP (params string[] rows)"
.br
.ti -1c
.RI "int \fBGetData\fP (int x, Dictionary< string, List< int >> rows)"
.br
.ti -1c
.RI "int \fBGetData\fP (int x, params string[] rows)"
.br
.ti -1c
.RI "int \fBMethodWithParams\fP (params object[] e)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 28 of file MethodCallerTests\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Csla\&.Test\&.MethodCaller\&.MethodCallerTests\&.CallException ()"

.PP
Definition at line 37 of file MethodCallerTests\&.cs\&.
.SS "void Csla\&.Test\&.MethodCaller\&.MethodCallerTests\&.CallInnerException ()"

.PP
Definition at line 50 of file MethodCallerTests\&.cs\&.
.SS "void Csla\&.Test\&.MethodCaller\&.MethodCallerTests\&.CallSuccess ()"

.PP
Definition at line 31 of file MethodCallerTests\&.cs\&.
.SS "void Csla\&.Test\&.MethodCaller\&.MethodCallerTests\&.CallSuccessArrayParameters ()"

.PP
Definition at line 71 of file MethodCallerTests\&.cs\&.
.SS "void Csla\&.Test\&.MethodCaller\&.MethodCallerTests\&.CallSuccessInheritedMethods ()"

.PP
Definition at line 102 of file MethodCallerTests\&.cs\&.
.SS "void Csla\&.Test\&.MethodCaller\&.MethodCallerTests\&.CallSuccessParams ()"

.PP
Definition at line 91 of file MethodCallerTests\&.cs\&.
.SS "void Csla\&.Test\&.MethodCaller\&.MethodCallerTests\&.CallWithInvalidParameterTypeFails ()"

.PP
Definition at line 153 of file MethodCallerTests\&.cs\&.
.SS "void Csla\&.Test\&.MethodCaller\&.MethodCallerTests\&.CallWithValidParameterTypeSucceeds ()"

.PP
Definition at line 162 of file MethodCallerTests\&.cs\&.
.SS "void Csla\&.Test\&.MethodCaller\&.MethodCallerTests\&.DoException ()"

.PP
Definition at line 185 of file MethodCallerTests\&.cs\&.
.SS "void Csla\&.Test\&.MethodCaller\&.MethodCallerTests\&.DoInnerException ()"

.PP
Definition at line 190 of file MethodCallerTests\&.cs\&.
.SS "void Csla\&.Test\&.MethodCaller\&.MethodCallerTests\&.DoSuccess ()"

.PP
Definition at line 181 of file MethodCallerTests\&.cs\&.
.SS "void Csla\&.Test\&.MethodCaller\&.MethodCallerTests\&.foo (MemoryStream ms)"

.PP
Definition at line 170 of file MethodCallerTests\&.cs\&.
.SS "int Csla\&.Test\&.MethodCaller\&.MethodCallerTests\&.GetData (int x, Dictionary< string, List< int >> rows)"

.PP
Definition at line 217 of file MethodCallerTests\&.cs\&.
.SS "int Csla\&.Test\&.MethodCaller\&.MethodCallerTests\&.GetData (int x, params string[] rows)"

.PP
Definition at line 222 of file MethodCallerTests\&.cs\&.
.SS "int Csla\&.Test\&.MethodCaller\&.MethodCallerTests\&.GetData (object rows)"

.PP
Definition at line 202 of file MethodCallerTests\&.cs\&.
.SS "int Csla\&.Test\&.MethodCaller\&.MethodCallerTests\&.GetData (params int[] rows)"

.PP
Definition at line 207 of file MethodCallerTests\&.cs\&.
.SS "int Csla\&.Test\&.MethodCaller\&.MethodCallerTests\&.GetData (params string[] rows)"

.PP
Definition at line 212 of file MethodCallerTests\&.cs\&.
.SS "int Csla\&.Test\&.MethodCaller\&.MethodCallerTests\&.MethodWithParams (params object[] e)"

.PP
Definition at line 227 of file MethodCallerTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
