.TH "Csla.Testing.Business.ReadOnlyTest.ReadOnlyPersonList" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Testing.Business.ReadOnlyTest.ReadOnlyPersonList
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.ReadOnlyBindingListBase< ReadOnlyPersonList, ReadOnlyPerson >\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 13 of file Server/ReadOnlyTests/ReadOnlyPersonList\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
