.TH "Csla.Test.ChildChanged.OptimizeChildChangedTests.SimpleBOList" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.ChildChanged.OptimizeChildChangedTests.SimpleBOList
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.BusinessListBase< SimpleBOList, SimpleBO >\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBUniqueID\fP = \fBNextUniqueID\fP()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnPropertyChanged\fP (PropertyChangedEventArgs e)"
.br
.ti -1c
.RI "override void \fBOnChildChanged\fP (\fBChildChangedEventArgs\fP e)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBDepth\fP\fC [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 121 of file OptimizeChildChangedTests\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override void Csla\&.Test\&.ChildChanged\&.OptimizeChildChangedTests\&.SimpleBOList\&.OnChildChanged (\fBChildChangedEventArgs\fP e)\fC [protected]\fP"

.PP
Definition at line 139 of file OptimizeChildChangedTests\&.cs\&.
.SS "override void Csla\&.Test\&.ChildChanged\&.OptimizeChildChangedTests\&.SimpleBOList\&.OnPropertyChanged (PropertyChangedEventArgs e)\fC [protected]\fP"

.PP
Definition at line 133 of file OptimizeChildChangedTests\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "int Csla\&.Test\&.ChildChanged\&.OptimizeChildChangedTests\&.SimpleBOList\&.UniqueID = \fBNextUniqueID\fP()"

.PP
Definition at line 125 of file OptimizeChildChangedTests\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "int Csla\&.Test\&.ChildChanged\&.OptimizeChildChangedTests\&.SimpleBOList\&.Depth\fC [get]\fP"

.PP
Definition at line 124 of file OptimizeChildChangedTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
