.TH "Csla.Validation" 3 "Thu Jul 22 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Validation
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBResource\fP"
.br
.ti -1c
.RI "class \fBBusinessBase\fP"
.br
.RI "Intermediate base class for \fBBusinessBase\fP "
.ti -1c
.RI "class \fBCommonRules\fP"
.br
.RI "Implements common business rules\&. "
.ti -1c
.RI "class \fBDecoratedRuleArgs\fP"
.br
.RI "Object providing extra information to methods that implement business rules\&. "
.ti -1c
.RI "class \fBObjectAccessor\fP"
.br
.ti -1c
.RI "class \fBPropertyHelper\fP"
.br
.ti -1c
.RI "class \fBReadOnlyBase\fP"
.br
.RI "Intermediate base class for \fBReadOnlyBase\fP "
.ti -1c
.RI "class \fBRuleArgs\fP"
.br
.RI "Object providing extra information to methods that implement business rules\&. "
.ti -1c
.RI "class \fBRuleExtensions\fP"
.br
.RI "Helper class for wrapping old style (\fBCsla\fP 3\&.8x and earlier) rules with a lambda rule in \fBCsla\fP 4\&.x to simplify migration of older style apps\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "delegate bool \fBRuleHandler\fP (object target, \fBRuleArgs\fP e)"
.br
.RI "The delegate definition for CSLA 3\&.8 rule handler "
.ti -1c
.RI "delegate bool \fBRuleHandler< T, R >\fP (T target, R e)"
.br
.RI "The delegate definition for CSLA 3\&.8 generic rule handler "
.in -1c
.SH "Function Documentation"
.PP 
.SS "delegate bool Csla\&.Validation\&.RuleHandler (object target, \fBRuleArgs\fP e)"

.PP
The delegate definition for CSLA 3\&.8 rule handler 
.PP
\fBParameters\fP
.RS 4
\fItarget\fP Target object\&.
.br
\fIe\fP \fBRuleArgs\fP parameter\&.
.RE
.PP
\fBReturns\fP
.RS 4
false if broken, true if passed
.RE
.PP

.SS "delegate bool \fBCsla\&.Validation\&.RuleHandler\fP< T, R > (T target, R e)"

.PP
The delegate definition for CSLA 3\&.8 generic rule handler 
.PP
\fBParameters\fP
.RS 4
\fItarget\fP Target object\&.
.br
\fIe\fP \fBRuleArgs\fP parameter\&.
.RE
.PP
\fBReturns\fP
.RS 4
false if broken, true if passed
.RE
.PP

.PP
\fBType Constraints\fP
.TP
\fIR\fP : \fIRuleArgs\fP
.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
