.TH "Csla.Web.Mvc.Test.ModelBinderTest.RootList" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Web.Mvc.Test.ModelBinderTest.RootList
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.BusinessListBase< RootList, Child >\fP\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBRootList\fP \fBGet\fP (int itemsCount)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 16 of file Csla\&.Web\&.Mvc\&.Test/ModelBinderTest/RootList\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "static \fBRootList\fP Csla\&.Web\&.Mvc\&.Test\&.ModelBinderTest\&.RootList\&.Get (int itemsCount)\fC [static]\fP"

.PP
Definition at line 21 of file Csla\&.Web\&.Mvc\&.Test/ModelBinderTest/RootList\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
