.TH "Csla.Test.DataPortal.PersonListBase" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.DataPortal.PersonListBase
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.BusinessBindingListBase< PersonList, PersonEdit >\fP\&.
.PP
Inherited by \fBCsla\&.Test\&.DataPortal\&.PersonList\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCriteria\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 55 of file InheritedOperationTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
