.TH "Csla.Blazor.Client.Authentication.CslaUserService" 3 "Thu Jul 22 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Blazor.Client.Authentication.CslaUserService \- Expose Csla\&.ApplicationContext\&.User for use in \fBBlazor\fP authentication pages\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCurrentUserChangedEventArgs\fP"
.br
.RI "Event args for CurrentUserChanged event\&. "
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCslaUserService\fP ()"
.br
.RI "Creates an instance of the type, setting the current user to an unauthenticated ClaimsPrincipal\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "ClaimsPrincipal? \fBCurrentUser\fP\fC [get, set]\fP"
.br
.RI "Gets or sets the current user\&. "
.in -1c
.SS "Events"

.in +1c
.ti -1c
.RI "EventHandler< \fBCurrentUserChangedEventArgs\fP > \fBCurrentUserChanged\fP"
.br
.RI "Event raised when the current user is changed\&. "
.in -1c
.SH "Detailed Description"
.PP 
Expose Csla\&.ApplicationContext\&.User for use in \fBBlazor\fP authentication pages\&. 

For use with \fBCslaAuthenticationStateProvider\fP\&.
.PP
Definition at line 11 of file CslaUserService\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Csla\&.Blazor\&.Client\&.Authentication\&.CslaUserService\&.CslaUserService ()"

.PP
Creates an instance of the type, setting the current user to an unauthenticated ClaimsPrincipal\&. 
.PP
Definition at line 22 of file CslaUserService\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "ClaimsPrincipal? Csla\&.Blazor\&.Client\&.Authentication\&.CslaUserService\&.CurrentUser\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the current user\&. 
.PP
Definition at line 30 of file CslaUserService\&.cs\&.
.SH "Event Documentation"
.PP 
.SS "EventHandler<\fBCurrentUserChangedEventArgs\fP> Csla\&.Blazor\&.Client\&.Authentication\&.CslaUserService\&.CurrentUserChanged"

.PP
Event raised when the current user is changed\&. 
.PP
Definition at line 16 of file CslaUserService\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
