.TH "Csla.Test.ValidationRules.LessThan" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.ValidationRules.LessThan \- Implements a rule to compare 2 property values and make sure property1 is less than property2  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.Rules\&.PropertyRule\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLessThan\fP (\fBIPropertyInfo\fP primaryProperty, \fBIPropertyInfo\fP compareToProperty)"
.br
.RI "Initializes a new instance of the \fBLessThan\fP class\&. "
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBExecute\fP (\fBIRuleContext\fP context)"
.br
.RI "Does the check for primary propert less than compareTo property "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Implements a rule to compare 2 property values and make sure property1 is less than property2 


.PP
Definition at line 208 of file RuleBaseClassesRoot\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Csla\&.Test\&.ValidationRules\&.LessThan\&.LessThan (\fBIPropertyInfo\fP primaryProperty, \fBIPropertyInfo\fP compareToProperty)"

.PP
Initializes a new instance of the \fBLessThan\fP class\&. 
.PP
\fBParameters\fP
.RS 4
\fIprimaryProperty\fP The primary property\&.
.br
\fIcompareToProperty\fP The compare to property\&.
.RE
.PP

.PP
Definition at line 217 of file RuleBaseClassesRoot\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override void Csla\&.Test\&.ValidationRules\&.LessThan\&.Execute (\fBIRuleContext\fP context)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Does the check for primary propert less than compareTo property 
.PP
\fBParameters\fP
.RS 4
\fIcontext\fP Rule context object\&.
.RE
.PP

.PP
Reimplemented from \fBCsla\&.Rules\&.BusinessRule\fP\&.
.PP
Definition at line 229 of file RuleBaseClassesRoot\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
