.TH "Csla.Blazor" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Blazor
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBClient\fP"
.br
.ti -1c
.RI "namespace \fBTest\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCslaPermissionRequirement\fP"
.br
.RI "CSLA permissions requirement\&. "
.ti -1c
.RI "class \fBCslaPermissionsPolicyProvider\fP"
.br
.RI "CSLA permissions policy provider\&. "
.ti -1c
.RI "class \fBCslaPolicy\fP"
.br
.RI "Contains methods to manage CSLA permission policy information\&. "
.ti -1c
.RI "class \fBCslaValidationMessageBase\fP"
.br
.RI "\fBValidation\fP message base type "
.ti -1c
.RI "class \fBCslaValidator\fP"
.br
.RI "Class offering integration of CSLA validation into \fBBlazor\fP edit forms This is a component with no visible behaviour; it simply requests hook up of validation "
.ti -1c
.RI "class \fBEditContextCslaExtensions\fP"
.br
.RI "Implements extension methods for edit context\&. "
.ti -1c
.RI "class \fBHasPermissionAttribute\fP"
.br
.RI "Authorizes user if they have permission\&. "
.ti -1c
.RI "class \fBCslaPermissionsHandler\fP"
.br
.RI "Authorization handler for CSLA permissions\&. "
.ti -1c
.RI "interface \fBIPropertyInfo\fP"
.br
.RI "Exposes metastate for a property\&. "
.ti -1c
.RI "class \fBPropertyInfo\fP"
.br
.RI "Exposes metastate for a property\&. "
.ti -1c
.RI "class \fBViewModel\fP"
.br
.RI "Base type for creating your own viewmodel\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
