.TH "Csla.Test.ValidationRules.RuleBaseClassesRoot" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.ValidationRules.RuleBaseClassesRoot
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.BusinessBase< RuleBaseClassesRoot >\fP\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBRuleBaseClassesRoot\fP \fBNewEditableRoot\fP (string ruleSet)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static readonly \fBPropertyInfo\fP< int > \fBCustomerIdProperty\fP = RegisterProperty<int>(c => c\&.CustomerId)"
.br
.ti -1c
.RI "static readonly \fBPropertyInfo\fP< string > \fBNameProperty\fP = RegisterProperty<string>(c => c\&.Name)"
.br
.ti -1c
.RI "static readonly \fBPropertyInfo\fP< int > \fBNum1Property\fP = RegisterProperty<int>(c => c\&.Num1)"
.br
.ti -1c
.RI "static readonly \fBPropertyInfo\fP< int > \fBNum2Property\fP = RegisterProperty<int>(c => c\&.Num2)"
.br
.ti -1c
.RI "static readonly \fBPropertyInfo\fP< int > \fBSumProperty\fP = RegisterProperty<int>(c => c\&.Sum)"
.br
.ti -1c
.RI "static readonly \fBPropertyInfo\fP< string > \fBCountryProperty\fP = RegisterProperty<string>(c => c\&.Country)"
.br
.ti -1c
.RI "static readonly \fBPropertyInfo\fP< string > \fBStateProperty\fP = RegisterProperty<string>(c => c\&.State)"
.br
.ti -1c
.RI "static readonly \fBPropertyInfo\fP< \fBCsla\&.SmartDate\fP > \fBStartDateProperty\fP = RegisterProperty<\fBCsla\&.SmartDate\fP>(c => c\&.StartDate, null, new \fBCsla\&.SmartDate\fP())"
.br
.ti -1c
.RI "static readonly \fBPropertyInfo\fP< \fBCsla\&.SmartDate\fP > \fBEndDateProperty\fP = RegisterProperty<\fBCsla\&.SmartDate\fP>(c => c\&.EndDate, null, new \fBCsla\&.SmartDate\fP())"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBPropertyHasChanged\fP (\fBIPropertyInfo\fP property)"
.br
.ti -1c
.RI "override void \fBAddBusinessRules\fP ()"
.br
.ti -1c
.RI "void \fBDataPortal_Create\fP (string ruleSet)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBCustomerId\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBName\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBNum1\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBNum2\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBSum\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBCountry\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBState\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBStartDate\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBEndDate\fP\fC [get, set]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 13 of file RuleBaseClassesRoot\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override void Csla\&.Test\&.ValidationRules\&.RuleBaseClassesRoot\&.AddBusinessRules ()\fC [protected]\fP"

.PP
Definition at line 90 of file RuleBaseClassesRoot\&.cs\&.
.SS "void Csla\&.Test\&.ValidationRules\&.RuleBaseClassesRoot\&.DataPortal_Create (string ruleSet)\fC [protected]\fP"

.PP
Definition at line 129 of file RuleBaseClassesRoot\&.cs\&.
.SS "static \fBRuleBaseClassesRoot\fP Csla\&.Test\&.ValidationRules\&.RuleBaseClassesRoot\&.NewEditableRoot (string ruleSet)\fC [static]\fP"

.PP
Definition at line 121 of file RuleBaseClassesRoot\&.cs\&.
.SS "override void Csla\&.Test\&.ValidationRules\&.RuleBaseClassesRoot\&.PropertyHasChanged (\fBIPropertyInfo\fP property)\fC [protected]\fP"

.PP
Definition at line 82 of file RuleBaseClassesRoot\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "readonly \fBPropertyInfo\fP<string> Csla\&.Test\&.ValidationRules\&.RuleBaseClassesRoot\&.CountryProperty = RegisterProperty<string>(c => c\&.Country)\fC [static]\fP"

.PP
Definition at line 52 of file RuleBaseClassesRoot\&.cs\&.
.SS "readonly \fBPropertyInfo\fP<int> Csla\&.Test\&.ValidationRules\&.RuleBaseClassesRoot\&.CustomerIdProperty = RegisterProperty<int>(c => c\&.CustomerId)\fC [static]\fP"

.PP
Definition at line 17 of file RuleBaseClassesRoot\&.cs\&.
.SS "readonly \fBPropertyInfo\fP<\fBCsla\&.SmartDate\fP> Csla\&.Test\&.ValidationRules\&.RuleBaseClassesRoot\&.EndDateProperty = RegisterProperty<\fBCsla\&.SmartDate\fP>(c => c\&.EndDate, null, new \fBCsla\&.SmartDate\fP())\fC [static]\fP"

.PP
Definition at line 73 of file RuleBaseClassesRoot\&.cs\&.
.SS "readonly \fBPropertyInfo\fP<string> Csla\&.Test\&.ValidationRules\&.RuleBaseClassesRoot\&.NameProperty = RegisterProperty<string>(c => c\&.Name)\fC [static]\fP"

.PP
Definition at line 24 of file RuleBaseClassesRoot\&.cs\&.
.SS "readonly \fBPropertyInfo\fP<int> Csla\&.Test\&.ValidationRules\&.RuleBaseClassesRoot\&.Num1Property = RegisterProperty<int>(c => c\&.Num1)\fC [static]\fP"

.PP
Definition at line 31 of file RuleBaseClassesRoot\&.cs\&.
.SS "readonly \fBPropertyInfo\fP<int> Csla\&.Test\&.ValidationRules\&.RuleBaseClassesRoot\&.Num2Property = RegisterProperty<int>(c => c\&.Num2)\fC [static]\fP"

.PP
Definition at line 38 of file RuleBaseClassesRoot\&.cs\&.
.SS "readonly \fBPropertyInfo\fP<\fBCsla\&.SmartDate\fP> Csla\&.Test\&.ValidationRules\&.RuleBaseClassesRoot\&.StartDateProperty = RegisterProperty<\fBCsla\&.SmartDate\fP>(c => c\&.StartDate, null, new \fBCsla\&.SmartDate\fP())\fC [static]\fP"

.PP
Definition at line 66 of file RuleBaseClassesRoot\&.cs\&.
.SS "readonly \fBPropertyInfo\fP<string> Csla\&.Test\&.ValidationRules\&.RuleBaseClassesRoot\&.StateProperty = RegisterProperty<string>(c => c\&.State)\fC [static]\fP"

.PP
Definition at line 59 of file RuleBaseClassesRoot\&.cs\&.
.SS "readonly \fBPropertyInfo\fP<int> Csla\&.Test\&.ValidationRules\&.RuleBaseClassesRoot\&.SumProperty = RegisterProperty<int>(c => c\&.Sum)\fC [static]\fP"

.PP
Definition at line 45 of file RuleBaseClassesRoot\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "string Csla\&.Test\&.ValidationRules\&.RuleBaseClassesRoot\&.Country\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 53 of file RuleBaseClassesRoot\&.cs\&.
.SS "int Csla\&.Test\&.ValidationRules\&.RuleBaseClassesRoot\&.CustomerId\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 18 of file RuleBaseClassesRoot\&.cs\&.
.SS "string Csla\&.Test\&.ValidationRules\&.RuleBaseClassesRoot\&.EndDate\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 74 of file RuleBaseClassesRoot\&.cs\&.
.SS "string Csla\&.Test\&.ValidationRules\&.RuleBaseClassesRoot\&.Name\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 25 of file RuleBaseClassesRoot\&.cs\&.
.SS "int Csla\&.Test\&.ValidationRules\&.RuleBaseClassesRoot\&.Num1\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 32 of file RuleBaseClassesRoot\&.cs\&.
.SS "int Csla\&.Test\&.ValidationRules\&.RuleBaseClassesRoot\&.Num2\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 39 of file RuleBaseClassesRoot\&.cs\&.
.SS "string Csla\&.Test\&.ValidationRules\&.RuleBaseClassesRoot\&.StartDate\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 67 of file RuleBaseClassesRoot\&.cs\&.
.SS "string Csla\&.Test\&.ValidationRules\&.RuleBaseClassesRoot\&.State\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 60 of file RuleBaseClassesRoot\&.cs\&.
.SS "int Csla\&.Test\&.ValidationRules\&.RuleBaseClassesRoot\&.Sum\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 46 of file RuleBaseClassesRoot\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
