.TH "cslalighttest.NameValueList.BasicNameValueList" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cslalighttest.NameValueList.BasicNameValueList
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.NameValueListBase< Int32, string >\fP\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBBasicNameValueList\fP \fBGetBasicNameValueList\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBDataPortal_Fetch\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 14 of file BasicNameValueList\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void cslalighttest\&.NameValueList\&.BasicNameValueList\&.DataPortal_Fetch ()\fC [protected]\fP"

.PP
Definition at line 21 of file BasicNameValueList\&.cs\&.
.SS "static \fBBasicNameValueList\fP cslalighttest\&.NameValueList\&.BasicNameValueList\&.GetBasicNameValueList ()\fC [static]\fP"

.PP
Definition at line 16 of file BasicNameValueList\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
