.TH "Csla.DataPortalServerRoutingTagAttribute" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.DataPortalServerRoutingTagAttribute \- Specifies a routing tag for use by the server-side data portal\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Attribute\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDataPortalServerRoutingTagAttribute\fP (string tag)"
.br
.RI "Creates an instance of this attribute\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBRoutingTag\fP\fC [get, set]\fP"
.br
.RI "Gets or sets the routing tag (can not contain '-')\&. "
.in -1c
.SH "Detailed Description"
.PP 
Specifies a routing tag for use by the server-side data portal\&. 


.PP
Definition at line 16 of file DataPortalServerRoutingTagAttribute\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Csla\&.DataPortalServerRoutingTagAttribute\&.DataPortalServerRoutingTagAttribute (string tag)"

.PP
Creates an instance of this attribute\&. 
.PP
\fBParameters\fP
.RS 4
\fItag\fP Routing tag value (can not contain '-')
.RE
.PP

.PP
Definition at line 39 of file DataPortalServerRoutingTagAttribute\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "string Csla\&.DataPortalServerRoutingTagAttribute\&.RoutingTag\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the routing tag (can not contain '-')\&. 
.PP
Definition at line 23 of file DataPortalServerRoutingTagAttribute\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
