.TH "Csla.Test.Basic.RootListChild" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.Basic.RootListChild
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.BusinessBase< RootListChild >\fP, and \fBCsla\&.BusinessBase< RootListChild >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "string[] \fBGetRuleDescriptions\fP ()"
.br
.ti -1c
.RI "\fBRootListChild\fP ()"
.br
.ti -1c
.RI "string[] \fBGetRuleDescriptions\fP ()"
.br
.ti -1c
.RI "\fBRootListChild\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBPropertyInfo\fP< int > \fBDataProperty\fP = RegisterProperty<int>(c => c\&.Data)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBData\fP\fC [get, set]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 39 of file RootList\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Csla\&.Test\&.Basic\&.RootListChild\&.RootListChild ()"

.PP
Definition at line 56 of file RootList\&.cs\&.
.SS "Csla\&.Test\&.Basic\&.RootListChild\&.RootListChild ()"

.PP
Definition at line 51 of file RootList\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "string [] Csla\&.Test\&.Basic\&.RootListChild\&.GetRuleDescriptions ()"

.PP
Definition at line 48 of file RootList\&.cs\&.
.SS "string [] Csla\&.Test\&.Basic\&.RootListChild\&.GetRuleDescriptions ()"

.PP
Definition at line 43 of file RootList\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "static \fBPropertyInfo\fP< int > Csla\&.Test\&.Basic\&.RootListChild\&.DataProperty = RegisterProperty<int>(c => c\&.Data)\fC [static]\fP"

.PP
Definition at line 41 of file RootList\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "int Csla\&.Test\&.Basic\&.RootListChild\&.Data\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 42 of file RootList\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
