.TH "Csla.Test.DataPortal.ChildDataPortalTests" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.DataPortal.ChildDataPortalTests
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "async Task \fBCreateChildNoCriteria\fP ()"
.br
.ti -1c
.RI "async Task \fBCreateChildInt32Criteria\fP ()"
.br
.ti -1c
.RI "async Task \fBCreateChildMultipleCriteria\fP ()"
.br
.ti -1c
.RI "async Task \fBFetchChildNoCriteria\fP ()"
.br
.ti -1c
.RI "async Task \fBFetchChildInt32Criteria\fP ()"
.br
.ti -1c
.RI "async Task \fBFetchChildMultipleCriteria\fP ()"
.br
.ti -1c
.RI "async Task \fBUpdateChild\fP ()"
.br
.ti -1c
.RI "async Task \fBDeleteSelfChild\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 28 of file ChildDataPortalTests\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "async Task Csla\&.Test\&.DataPortal\&.ChildDataPortalTests\&.CreateChildInt32Criteria ()"

.PP
Definition at line 38 of file ChildDataPortalTests\&.cs\&.
.SS "async Task Csla\&.Test\&.DataPortal\&.ChildDataPortalTests\&.CreateChildMultipleCriteria ()"

.PP
Definition at line 46 of file ChildDataPortalTests\&.cs\&.
.SS "async Task Csla\&.Test\&.DataPortal\&.ChildDataPortalTests\&.CreateChildNoCriteria ()"

.PP
Definition at line 31 of file ChildDataPortalTests\&.cs\&.
.SS "async Task Csla\&.Test\&.DataPortal\&.ChildDataPortalTests\&.DeleteSelfChild ()"

.PP
Definition at line 86 of file ChildDataPortalTests\&.cs\&.
.SS "async Task Csla\&.Test\&.DataPortal\&.ChildDataPortalTests\&.FetchChildInt32Criteria ()"

.PP
Definition at line 61 of file ChildDataPortalTests\&.cs\&.
.SS "async Task Csla\&.Test\&.DataPortal\&.ChildDataPortalTests\&.FetchChildMultipleCriteria ()"

.PP
Definition at line 69 of file ChildDataPortalTests\&.cs\&.
.SS "async Task Csla\&.Test\&.DataPortal\&.ChildDataPortalTests\&.FetchChildNoCriteria ()"

.PP
Definition at line 54 of file ChildDataPortalTests\&.cs\&.
.SS "async Task Csla\&.Test\&.DataPortal\&.ChildDataPortalTests\&.UpdateChild ()"

.PP
Definition at line 77 of file ChildDataPortalTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
