.TH "Csla.Test.DataBinding.ParentEntity" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.DataBinding.ParentEntity
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.BusinessBase< ParentEntity >\fP, and \fBCsla\&.BusinessBase< ParentEntity >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBParentEntity\fP ()"
.br
.RI "DO NOT USE in UI - use the factory method instead "
.ti -1c
.RI "\fBParentEntity\fP ()"
.br
.RI "DO NOT USE in UI - use the factory method instead "
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBParentEntity\fP \fBNewParentEntity\fP ()"
.br
.ti -1c
.RI "static \fBParentEntity\fP \fBGetParentEntity\fP (int \fBID\fP)"
.br
.ti -1c
.RI "static void \fBDeleteParentEntity\fP (int \fBID\fP)"
.br
.ti -1c
.RI "static \fBParentEntity\fP \fBNewParentEntity\fP ()"
.br
.ti -1c
.RI "static \fBParentEntity\fP \fBGetParentEntity\fP (int \fBID\fP)"
.br
.ti -1c
.RI "static void \fBDeleteParentEntity\fP (int \fBID\fP)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBPropertyInfo\fP< int > \fBIDProperty\fP = RegisterProperty<int>(c => c\&.ID)"
.br
.ti -1c
.RI "static \fBPropertyInfo\fP< string > \fBDataProperty\fP = RegisterProperty<string>(c => c\&.Data)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBAddBusinessRules\fP ()"
.br
.ti -1c
.RI "void \fBDataPortal_Create\fP ()"
.br
.ti -1c
.RI "void \fBDataPortal_Fetch\fP (object criteria)"
.br
.ti -1c
.RI "void \fBDataPortal_Insert\fP ()"
.br
.ti -1c
.RI "void \fBDataPortal_Update\fP ()"
.br
.ti -1c
.RI "void \fBDataPortal_DeleteSelf\fP ()"
.br
.ti -1c
.RI "void \fBDataPortal_Delete\fP (object criteria)"
.br
.ti -1c
.RI "override void \fBAddBusinessRules\fP ()"
.br
.ti -1c
.RI "void \fBDataPortal_Create\fP ()"
.br
.ti -1c
.RI "void \fBDataPortal_Fetch\fP (object criteria)"
.br
.ti -1c
.RI "void \fBDataPortal_Insert\fP ()"
.br
.ti -1c
.RI "void \fBDataPortal_Update\fP ()"
.br
.ti -1c
.RI "void \fBDataPortal_DeleteSelf\fP ()"
.br
.ti -1c
.RI "void \fBDataPortal_Delete\fP (object criteria)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBNotUndoable\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBID\fP\fC [get]\fP"
.br
.ti -1c
.RI "string \fBData\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBChildEntityList\fP \fBChildren\fP\fC [get]\fP"
.br
.ti -1c
.RI "override bool \fBIsDirty\fP\fC [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 17 of file ParentEntity\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Csla\&.Test\&.DataBinding\&.ParentEntity\&.ParentEntity ()"

.PP
DO NOT USE in UI - use the factory method instead <remaks> this constructor is public only to support web forms databinding /remaks> 
.PP
Definition at line 74 of file ParentEntity\&.cs\&.
.SS "Csla\&.Test\&.DataBinding\&.ParentEntity\&.ParentEntity ()"

.PP
DO NOT USE in UI - use the factory method instead <remaks> this constructor is public only to support web forms databinding /remaks> 
.PP
Definition at line 74 of file ParentEntity\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override void Csla\&.Test\&.DataBinding\&.ParentEntity\&.AddBusinessRules ()\fC [protected]\fP"

.PP
Definition at line 60 of file ParentEntity\&.cs\&.
.SS "override void Csla\&.Test\&.DataBinding\&.ParentEntity\&.AddBusinessRules ()\fC [protected]\fP"

.PP
Definition at line 60 of file ParentEntity\&.cs\&.
.SS "void Csla\&.Test\&.DataBinding\&.ParentEntity\&.DataPortal_Create ()\fC [protected]\fP"

.PP
Definition at line 121 of file ParentEntity\&.cs\&.
.SS "void Csla\&.Test\&.DataBinding\&.ParentEntity\&.DataPortal_Create ()\fC [protected]\fP"

.PP
Definition at line 121 of file ParentEntity\&.cs\&.
.SS "void Csla\&.Test\&.DataBinding\&.ParentEntity\&.DataPortal_Delete (object criteria)\fC [protected]\fP"

.PP
Definition at line 173 of file ParentEntity\&.cs\&.
.SS "void Csla\&.Test\&.DataBinding\&.ParentEntity\&.DataPortal_Delete (object criteria)\fC [protected]\fP"

.PP
Definition at line 162 of file ParentEntity\&.cs\&.
.SS "void Csla\&.Test\&.DataBinding\&.ParentEntity\&.DataPortal_DeleteSelf ()\fC [protected]\fP"

.PP
Definition at line 163 of file ParentEntity\&.cs\&.
.SS "void Csla\&.Test\&.DataBinding\&.ParentEntity\&.DataPortal_DeleteSelf ()\fC [protected]\fP"

.PP
Definition at line 154 of file ParentEntity\&.cs\&.
.SS "void Csla\&.Test\&.DataBinding\&.ParentEntity\&.DataPortal_Fetch (object criteria)\fC [protected]\fP"

.PP
Definition at line 132 of file ParentEntity\&.cs\&.
.SS "void Csla\&.Test\&.DataBinding\&.ParentEntity\&.DataPortal_Fetch (object criteria)\fC [protected]\fP"

.PP
Definition at line 129 of file ParentEntity\&.cs\&.
.SS "void Csla\&.Test\&.DataBinding\&.ParentEntity\&.DataPortal_Insert ()\fC [protected]\fP"

.PP
Definition at line 143 of file ParentEntity\&.cs\&.
.SS "void Csla\&.Test\&.DataBinding\&.ParentEntity\&.DataPortal_Insert ()\fC [protected]\fP"

.PP
Definition at line 138 of file ParentEntity\&.cs\&.
.SS "void Csla\&.Test\&.DataBinding\&.ParentEntity\&.DataPortal_Update ()\fC [protected]\fP"

.PP
Definition at line 153 of file ParentEntity\&.cs\&.
.SS "void Csla\&.Test\&.DataBinding\&.ParentEntity\&.DataPortal_Update ()\fC [protected]\fP"

.PP
Definition at line 146 of file ParentEntity\&.cs\&.
.SS "static void Csla\&.Test\&.DataBinding\&.ParentEntity\&.DeleteParentEntity (int ID)\fC [static]\fP"

.PP
Definition at line 95 of file ParentEntity\&.cs\&.
.SS "static void Csla\&.Test\&.DataBinding\&.ParentEntity\&.DeleteParentEntity (int ID)\fC [static]\fP"

.PP
Definition at line 95 of file ParentEntity\&.cs\&.
.SS "static \fBParentEntity\fP Csla\&.Test\&.DataBinding\&.ParentEntity\&.GetParentEntity (int ID)\fC [static]\fP"

.PP
Definition at line 90 of file ParentEntity\&.cs\&.
.SS "static \fBParentEntity\fP Csla\&.Test\&.DataBinding\&.ParentEntity\&.GetParentEntity (int ID)\fC [static]\fP"

.PP
Definition at line 90 of file ParentEntity\&.cs\&.
.SS "static \fBParentEntity\fP Csla\&.Test\&.DataBinding\&.ParentEntity\&.NewParentEntity ()\fC [static]\fP"

.PP
Definition at line 85 of file ParentEntity\&.cs\&.
.SS "static \fBParentEntity\fP Csla\&.Test\&.DataBinding\&.ParentEntity\&.NewParentEntity ()\fC [static]\fP"

.PP
Definition at line 85 of file ParentEntity\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "static \fBPropertyInfo\fP< string > Csla\&.Test\&.DataBinding\&.ParentEntity\&.DataProperty = RegisterProperty<string>(c => c\&.Data)\fC [static]\fP"

.PP
Definition at line 38 of file ParentEntity\&.cs\&.
.SS "static \fBPropertyInfo\fP< int > Csla\&.Test\&.DataBinding\&.ParentEntity\&.IDProperty = RegisterProperty<int>(c => c\&.ID)\fC [static]\fP"

.PP
Definition at line 31 of file ParentEntity\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "\fBChildEntityList\fP Csla\&.Test\&.DataBinding\&.ParentEntity\&.Children\fC [get]\fP"

.PP
Definition at line 45 of file ParentEntity\&.cs\&.
.SS "string Csla\&.Test\&.DataBinding\&.ParentEntity\&.Data\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 39 of file ParentEntity\&.cs\&.
.SS "int Csla\&.Test\&.DataBinding\&.ParentEntity\&.ID\fC [get]\fP"

.PP
Definition at line 32 of file ParentEntity\&.cs\&.
.SS "override bool Csla\&.Test\&.DataBinding\&.ParentEntity\&.IsDirty\fC [get]\fP"

.PP
Definition at line 50 of file ParentEntity\&.cs\&.
.SS "string Csla\&.Test\&.DataBinding\&.ParentEntity\&.NotUndoable\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 25 of file ParentEntity\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
