.TH "csla.netcore.test.Configuration.DefaultType" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csla.netcore.test.Configuration.DefaultType
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.BusinessBase< DefaultType >\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 203 of file FluentConfigTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
