.TH "Csla.Test.DataPortal" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.DataPortal
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBChildDataPortalTests\fP"
.br
.ti -1c
.RI "class \fBTestChild\fP"
.br
.ti -1c
.RI "class \fBCriteriaMappingTests\fP"
.br
.ti -1c
.RI "class \fBInheritedOperationTests\fP"
.br
.ti -1c
.RI "class \fBPersonList\fP"
.br
.ti -1c
.RI "class \fBPersonListBase\fP"
.br
.ti -1c
.RI "class \fBPersonEdit\fP"
.br
.ti -1c
.RI "class \fBPersonEditBase\fP"
.br
.ti -1c
.RI "class \fBServiceProviderInvocationTests\fP"
.br
.ti -1c
.RI "interface \fBISpeak\fP"
.br
.ti -1c
.RI "class \fBDog\fP"
.br
.ti -1c
.RI "class \fBTestMethods\fP"
.br
.ti -1c
.RI "class \fBServiceProviderMethodCallerTests\fP"
.br
.ti -1c
.RI "class \fBOldStyleNoOverride\fP"
.br
.ti -1c
.RI "class \fBPrivateMethodBase\fP"
.br
.ti -1c
.RI "class \fBPrivateMethod\fP"
.br
.ti -1c
.RI "class \fBOldStyleCreate\fP"
.br
.ti -1c
.RI "class \fBOldStyleCriteria\fP"
.br
.ti -1c
.RI "class \fBOldStyleCriteriaBase\fP"
.br
.ti -1c
.RI "interface \fBICriteria\fP"
.br
.ti -1c
.RI "class \fBMyCriteria\fP"
.br
.ti -1c
.RI "class \fBInterfaceCriteria\fP"
.br
.ti -1c
.RI "class \fBSimpleNoCriteriaCreate\fP"
.br
.ti -1c
.RI "class \fBSimpleCriteriaCreate\fP"
.br
.ti -1c
.RI "class \fBObjectCriteriaCreate\fP"
.br
.ti -1c
.RI "class \fBObjectCriteriaCreateSubtype\fP"
.br
.ti -1c
.RI "class \fBAmbiguousNoCriteriaCreate\fP"
.br
.ti -1c
.RI "class \fBCriteriaCreateWithDI\fP"
.br
.ti -1c
.RI "class \fBMultipleCriteriaCreateWithDI\fP"
.br
.ti -1c
.RI "class \fBCriteriaCreateWithMultipleDI\fP"
.br
.ti -1c
.RI "class \fBCriteriaCreateWithMultipleAmbiguousDI\fP"
.br
.ti -1c
.RI "class \fBMultipleCriteriaCreateWithDIInterleaved\fP"
.br
.ti -1c
.RI "class \fBBasicChild\fP"
.br
.ti -1c
.RI "class \fBParamsChild\fP"
.br
.ti -1c
.RI "class \fBModernChild\fP"
.br
.ti -1c
.RI "class \fBNullableCriteria\fP"
.br
.ti -1c
.RI "class \fBMultipleOverlappingCriteria\fP"
.br
.ti -1c
.RI "class \fBIssue2109List\fP"
.br
.ti -1c
.RI "class \fBIssue2109\fP"
.br
.ti -1c
.RI "interface \fBICriteriaBase\fP"
.br
.ti -1c
.RI "class \fBMy2109Criteria\fP"
.br
.ti -1c
.RI "class \fBIssue2287List\fP"
.br
.ti -1c
.RI "class \fBIssue2287ListBase\fP"
.br
.ti -1c
.RI "class \fBIssue2287Edit\fP"
.br
.ti -1c
.RI "class \fBIssue2287EditBase\fP"
.br
.ti -1c
.RI "class \fBArrayTests\fP"
.br
.ti -1c
.RI "class \fBArrayDataPortalClass\fP"
.br
.ti -1c
.RI "class \fBAsynchDataPortalTest\fP"
.br
.ti -1c
.RI "class \fBAuthorizeDataPortalTests\fP"
.br
.ti -1c
.RI "class \fBCustomDataPortalServer\fP"
.br
.ti -1c
.RI "class \fBDataPortalExceptionTests\fP"
.br
.ti -1c
.RI "class \fBEditableRoot1\fP"
.br
.ti -1c
.RI "class \fBEditableChild1\fP"
.br
.ti -1c
.RI "class \fBDataPortalTests\fP"
.br
.ti -1c
.RI "class \fBEncapsulatedBusy\fP"
.br
.ti -1c
.RI "class \fBFactoryBusy\fP"
.br
.ti -1c
.RI "class \fBFactoryBusyFactory\fP"
.br
.ti -1c
.RI "class \fBDisposeScopeTest\fP"
.br
.ti -1c
.RI "class \fBDisposableClass\fP"
.br
.ti -1c
.RI "class \fBClassA\fP"
.br
.ti -1c
.RI "class \fBClassB\fP"
.br
.ti -1c
.RI "class \fBDpRoot\fP"
.br
.ti -1c
.RI "class \fBESTransactionalRoot\fP"
.br
.ti -1c
.RI "class \fBInterceptorTests\fP"
.br
.ti -1c
.RI "class \fBInitializeRoot\fP"
.br
.ti -1c
.RI "class \fBInitializeListRoot\fP"
.br
.ti -1c
.RI "class \fBInterceptorCommand\fP"
.br
.ti -1c
.RI "class \fBTestInterceptor\fP"
.br
.ti -1c
.RI "class \fBTestActivator\fP"
.br
.ti -1c
.RI "class \fBLogicalExecutionDataPortalTests\fP"
.br
.ti -1c
.RI "class \fBMultipleDataAccess\fP"
.br
.ti -1c
.RI "class \fBMultipleDataAccessBase\fP"
.br
.ti -1c
.RI "class \fBMultipleDataAccessTest\fP"
.br
.ti -1c
.RI "class \fBStronglyTypedDP\fP"
.br
.ti -1c
.RI "class \fBTransactionalRoot\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
