.TH "Csla.Analyzers.Tests.ContainsInvocationExpressionWalkerTests" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Analyzers.Tests.ContainsInvocationExpressionWalkerTests
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "async Task \fBWalkWhenNodeHasNoInvocations\fP ()"
.br
.ti -1c
.RI "async Task \fBWalkWhenNodeHasInvocation\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 7 of file ContainsInvocationExpressionWalkerTests\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "async Task Csla\&.Analyzers\&.Tests\&.ContainsInvocationExpressionWalkerTests\&.WalkWhenNodeHasInvocation ()"

.PP
Definition at line 26 of file ContainsInvocationExpressionWalkerTests\&.cs\&.
.SS "async Task Csla\&.Analyzers\&.Tests\&.ContainsInvocationExpressionWalkerTests\&.WalkWhenNodeHasNoInvocations ()"

.PP
Definition at line 18 of file ContainsInvocationExpressionWalkerTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
