.TH "Csla.Analyzers.Tests.CheckConstructorsAnalyzerTests" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Analyzers.Tests.CheckConstructorsAnalyzerTests
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBVerifySupportedDiagnostics\fP ()"
.br
.ti -1c
.RI "async Task \fBAnalyzeWhenClassIsNotStereotype\fP ()"
.br
.ti -1c
.RI "async Task \fBAnalyzeWhenClassIsStereotypeAndHasPublicNoArgumentConstructor\fP ()"
.br
.ti -1c
.RI "async Task \fBAnalyzeWhenClassIsStereotypeAndHasPrivateNoArgumentConstructor\fP ()"
.br
.ti -1c
.RI "async Task \fBAnalyzeWhenClassIsStereotypeAndHasPrivateConstructorWithArguments\fP ()"
.br
.ti -1c
.RI "async Task \fBAnalyzeWhenClassIsStereotypeAndHasPublicNoArgumentConstructorAndPublicConstructorWithArguments\fP ()"
.br
.ti -1c
.RI "async Task \fBAnalyzeWhenClassIsStereotypeAndHasNoPublicNoArgumentConstructorAndPublicConstructorWithArguments\fP ()"
.br
.ti -1c
.RI "async Task \fBAnalyzeWhenClassIsStereotypeAndHasStaticConstructor\fP ()"
.br
.ti -1c
.RI "async Task \fBAnalyzeWhenClassIsBusinessListBaseAndHasPublicConstructorWithArguments\fP ()"
.br
.ti -1c
.RI "async Task \fBAnalyzeWhenClassIsDynamicListBaseAndHasPublicConstructorWithArguments\fP ()"
.br
.ti -1c
.RI "async Task \fBAnalyzeWhenClassIsBusinessBindingListBaseAndHasPublicConstructorWithArguments\fP ()"
.br
.ti -1c
.RI "async Task \fBAnalyzeWhenClassIsCommandBaseAndHasPublicConstructorWithArguments\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 10 of file CheckConstructorsAnalyzerTests\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "async Task Csla\&.Analyzers\&.Tests\&.CheckConstructorsAnalyzerTests\&.AnalyzeWhenClassIsBusinessBindingListBaseAndHasPublicConstructorWithArguments ()"

.PP
Definition at line 180 of file CheckConstructorsAnalyzerTests\&.cs\&.
.SS "async Task Csla\&.Analyzers\&.Tests\&.CheckConstructorsAnalyzerTests\&.AnalyzeWhenClassIsBusinessListBaseAndHasPublicConstructorWithArguments ()"

.PP
Definition at line 142 of file CheckConstructorsAnalyzerTests\&.cs\&.
.SS "async Task Csla\&.Analyzers\&.Tests\&.CheckConstructorsAnalyzerTests\&.AnalyzeWhenClassIsCommandBaseAndHasPublicConstructorWithArguments ()"

.PP
Definition at line 200 of file CheckConstructorsAnalyzerTests\&.cs\&.
.SS "async Task Csla\&.Analyzers\&.Tests\&.CheckConstructorsAnalyzerTests\&.AnalyzeWhenClassIsDynamicListBaseAndHasPublicConstructorWithArguments ()"

.PP
Definition at line 161 of file CheckConstructorsAnalyzerTests\&.cs\&.
.SS "async Task Csla\&.Analyzers\&.Tests\&.CheckConstructorsAnalyzerTests\&.AnalyzeWhenClassIsNotStereotype ()"

.PP
Definition at line 47 of file CheckConstructorsAnalyzerTests\&.cs\&.
.SS "async Task Csla\&.Analyzers\&.Tests\&.CheckConstructorsAnalyzerTests\&.AnalyzeWhenClassIsStereotypeAndHasNoPublicNoArgumentConstructorAndPublicConstructorWithArguments ()"

.PP
Definition at line 110 of file CheckConstructorsAnalyzerTests\&.cs\&.
.SS "async Task Csla\&.Analyzers\&.Tests\&.CheckConstructorsAnalyzerTests\&.AnalyzeWhenClassIsStereotypeAndHasPrivateConstructorWithArguments ()"

.PP
Definition at line 79 of file CheckConstructorsAnalyzerTests\&.cs\&.
.SS "async Task Csla\&.Analyzers\&.Tests\&.CheckConstructorsAnalyzerTests\&.AnalyzeWhenClassIsStereotypeAndHasPrivateNoArgumentConstructor ()"

.PP
Definition at line 64 of file CheckConstructorsAnalyzerTests\&.cs\&.
.SS "async Task Csla\&.Analyzers\&.Tests\&.CheckConstructorsAnalyzerTests\&.AnalyzeWhenClassIsStereotypeAndHasPublicNoArgumentConstructor ()"

.PP
Definition at line 54 of file CheckConstructorsAnalyzerTests\&.cs\&.
.SS "async Task Csla\&.Analyzers\&.Tests\&.CheckConstructorsAnalyzerTests\&.AnalyzeWhenClassIsStereotypeAndHasPublicNoArgumentConstructorAndPublicConstructorWithArguments ()"

.PP
Definition at line 94 of file CheckConstructorsAnalyzerTests\&.cs\&.
.SS "async Task Csla\&.Analyzers\&.Tests\&.CheckConstructorsAnalyzerTests\&.AnalyzeWhenClassIsStereotypeAndHasStaticConstructor ()"

.PP
Definition at line 125 of file CheckConstructorsAnalyzerTests\&.cs\&.
.SS "void Csla\&.Analyzers\&.Tests\&.CheckConstructorsAnalyzerTests\&.VerifySupportedDiagnostics ()"

.PP
Definition at line 13 of file CheckConstructorsAnalyzerTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
