.TH "Csla.NameValueListBase< K, V >" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.NameValueListBase< K, V > \- This is the base class from which readonly name/value collections should be derived\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.Core\&.ReadOnlyBindingList< NameValueListBase< K, V >\&.NameValuePair >\fP, ICloneable, \fBCsla\&.Core\&.IBusinessObject\fP, and Csla\&.Server\&.IDataPortalTarget\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBNameValuePair\fP"
.br
.RI "Contains a key and value pair\&. "
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "V \fBValue\fP (K key)"
.br
.RI "Returns the value corresponding to the specified key\&. "
.ti -1c
.RI "K \fBKey\fP (V value)"
.br
.RI "Returns the key corresponding to the first occurance of the specified value in the list\&. "
.ti -1c
.RI "bool \fBContainsKey\fP (K key)"
.br
.RI "Gets a value indicating whether the list contains the specified key\&. "
.ti -1c
.RI "bool \fBContainsValue\fP (V value)"
.br
.RI "Gets a value indicating whether the list contains the specified value\&. "
.ti -1c
.RI "\fBNameValuePair\fP \fBGetItemByValue\fP (V value)"
.br
.RI "Get the item for the first matching value in the collection\&. "
.ti -1c
.RI "\fBNameValuePair\fP \fBGetItemByKey\fP (K key)"
.br
.RI "Get the item for the first matching key in the collection\&. "
.ti -1c
.RI "\fBNameValueListBase\fP< K, V > \fBClone\fP ()"
.br
.RI "Creates a clone of the object\&. "
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBNameValueListBase\fP ()"
.br
.RI "Creates an instance of the object\&. "
.ti -1c
.RI "virtual void \fBInitialize\fP ()"
.br
.RI "Override this method to set up event handlers so user code in a partial class can respond to events raised by generated code\&. "
.ti -1c
.RI "virtual object \fBGetClone\fP ()"
.br
.RI "Creates a clone of the object\&. "
.ti -1c
.RI "virtual void \fBDataPortal_OnDataPortalInvoke\fP (\fBDataPortalEventArgs\fP e)"
.br
.RI "Called by the server-side \fBDataPortal\fP prior to calling the requested DataPortal_XYZ method\&. "
.ti -1c
.RI "virtual void \fBDataPortal_OnDataPortalInvokeComplete\fP (\fBDataPortalEventArgs\fP e)"
.br
.RI "Called by the server-side \fBDataPortal\fP after calling the requested DataPortal_XYZ method\&. "
.ti -1c
.RI "virtual void \fBDataPortal_OnDataPortalException\fP (\fBDataPortalEventArgs\fP e, Exception ex)"
.br
.RI "Called by the server-side \fBDataPortal\fP if an exception occurs during data access\&. "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
This is the base class from which readonly name/value collections should be derived\&. 


.PP
\fBTemplate Parameters\fP
.RS 4
\fIK\fP Type of the key values\&.
.br
\fIV\fP Type of the values\&.
.RE
.PP

.PP
Definition at line 25 of file NameValueListBase\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBCsla\&.NameValueListBase\fP< K, V >\&.\fBNameValueListBase\fP ()\fC [protected]\fP"

.PP
Creates an instance of the object\&. 
.PP
Definition at line 134 of file NameValueListBase\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBNameValueListBase\fP<K, V> \fBCsla\&.NameValueListBase\fP< K, V >\&.Clone ()"

.PP
Creates a clone of the object\&. 
.PP
Definition at line 258 of file NameValueListBase\&.cs\&.
.SS "bool \fBCsla\&.NameValueListBase\fP< K, V >\&.ContainsKey (K key)"

.PP
Gets a value indicating whether the list contains the specified key\&. 
.PP
\fBParameters\fP
.RS 4
\fIkey\fP Key value for which to search\&.
.RE
.PP

.PP
Definition at line 64 of file NameValueListBase\&.cs\&.
.SS "bool \fBCsla\&.NameValueListBase\fP< K, V >\&.ContainsValue (V value)"

.PP
Gets a value indicating whether the list contains the specified value\&. 
.PP
\fBParameters\fP
.RS 4
\fIvalue\fP Value for which to search\&.
.RE
.PP

.PP
Definition at line 77 of file NameValueListBase\&.cs\&.
.SS "virtual void \fBCsla\&.NameValueListBase\fP< K, V >\&.DataPortal_OnDataPortalException (\fBDataPortalEventArgs\fP e, Exception ex)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Called by the server-side \fBDataPortal\fP if an exception occurs during data access\&. 
.PP
\fBParameters\fP
.RS 4
\fIe\fP The DataPortalContext object passed to the \fBDataPortal\fP\&.
.br
\fIex\fP The Exception thrown during data access\&.
.RE
.PP

.PP
Definition at line 311 of file NameValueListBase\&.cs\&.
.SS "virtual void \fBCsla\&.NameValueListBase\fP< K, V >\&.DataPortal_OnDataPortalInvoke (\fBDataPortalEventArgs\fP e)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Called by the server-side \fBDataPortal\fP prior to calling the requested DataPortal_XYZ method\&. 
.PP
\fBParameters\fP
.RS 4
\fIe\fP The DataPortalContext object passed to the \fBDataPortal\fP\&.
.RE
.PP

.PP
Definition at line 286 of file NameValueListBase\&.cs\&.
.SS "virtual void \fBCsla\&.NameValueListBase\fP< K, V >\&.DataPortal_OnDataPortalInvokeComplete (\fBDataPortalEventArgs\fP e)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Called by the server-side \fBDataPortal\fP after calling the requested DataPortal_XYZ method\&. 
.PP
\fBParameters\fP
.RS 4
\fIe\fP The DataPortalContext object passed to the \fBDataPortal\fP\&.
.RE
.PP

.PP
Definition at line 298 of file NameValueListBase\&.cs\&.
.SS "virtual object \fBCsla\&.NameValueListBase\fP< K, V >\&.GetClone ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Creates a clone of the object\&. 
.PP
\fBReturns\fP
.RS 4
A new object containing the exact data of the original object\&.
.RE
.PP

.PP
Definition at line 250 of file NameValueListBase\&.cs\&.
.SS "\fBNameValuePair\fP \fBCsla\&.NameValueListBase\fP< K, V >\&.GetItemByKey (K key)"

.PP
Get the item for the first matching key in the collection\&. 
.PP
\fBParameters\fP
.RS 4
\fIkey\fP Key to search for in the list\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Item from the list\&.
.RE
.PP

.PP
Definition at line 115 of file NameValueListBase\&.cs\&.
.SS "\fBNameValuePair\fP \fBCsla\&.NameValueListBase\fP< K, V >\&.GetItemByValue (V value)"

.PP
Get the item for the first matching value in the collection\&. 
.PP
\fBParameters\fP
.RS 4
\fIvalue\fP Value to search for in the list\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Item from the list\&.
.RE
.PP

.PP
Definition at line 93 of file NameValueListBase\&.cs\&.
.SS "virtual void \fBCsla\&.NameValueListBase\fP< K, V >\&.Initialize ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Override this method to set up event handlers so user code in a partial class can respond to events raised by generated code\&. 
.PP
Definition at line 146 of file NameValueListBase\&.cs\&.
.SS "K \fBCsla\&.NameValueListBase\fP< K, V >\&.Key (V value)"

.PP
Returns the key corresponding to the first occurance of the specified value in the list\&. 
.PP
\fBParameters\fP
.RS 4
\fIvalue\fP Value for which to retrieve the key\&.
.RE
.PP

.PP
Definition at line 51 of file NameValueListBase\&.cs\&.
.SS "V \fBCsla\&.NameValueListBase\fP< K, V >\&.Value (K key)"

.PP
Returns the value corresponding to the specified key\&. 
.PP
\fBParameters\fP
.RS 4
\fIkey\fP Key value for which to retrieve a value\&.
.RE
.PP

.PP
Definition at line 37 of file NameValueListBase\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
