.TH "Csla.Iosui.ViewControllerBase< T, Z >" 3 "Thu Jul 22 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Iosui.ViewControllerBase< T, Z > \- CSLA helper to be used in place of the normal Xamarin Android activity that contains a reference to a CSLA ViewModel and a BindingManager\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits UIViewController\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "byte[] \fBSerilizeModelForParameter\fP ()"
.br
.RI "Serializes the ViewModel's model property using the SerializationFormatterFactory\&.GetFormatter()\&. Used to serialize and transfer models between activities\&. "
.ti -1c
.RI "byte[] \fBSerilizeModelForParameter\fP (object model)"
.br
.RI "Serialized the provided model using the SerializationFormatterFactory\&.GetFormatter()\&. Used to serialize and transfer models between activities\&. "
.ti -1c
.RI "object \fBDeserializeFromParameter\fP (byte[] parameter)"
.br
.RI "Takes a byte array and uses the MobileFormatter to reconstitute it into a model reference\&. "
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "T \fBviewModel\fP = null"
.br
.RI "A reference to the view model\&. "
.ti -1c
.RI "\fBBindingManager\fP \fBBindings\fP = null"
.br
.RI "The BindingManager for this Activity\&. "
.in -1c
.SH "Detailed Description"
.PP 
CSLA helper to be used in place of the normal Xamarin Android activity that contains a reference to a CSLA ViewModel and a BindingManager\&. 


.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP A type that inherits from the ViewModel\&.
.br
\fIZ\fP The type that is defined as used by T\&.
.RE
.PP

.PP
\fBType Constraints\fP
.TP
\fIT\fP : \fIViewModel<Z>\fP
.PP
Definition at line 25 of file ViewControllerBase\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "object \fBCsla\&.Iosui\&.ViewControllerBase\fP< T, Z >\&.DeserializeFromParameter (byte[] parameter)\fC [protected]\fP"

.PP
Takes a byte array and uses the MobileFormatter to reconstitute it into a model reference\&. 
.PP
\fBParameters\fP
.RS 4
\fIparameter\fP An array of bytes to deserialized\&.
.RE
.PP
\fBReturns\fP
.RS 4
A reference to the deserialized object\&. An exception will be thrown if the supplied byte array is not valid for deserializaiton\&.
.RE
.PP

.PP
Definition at line 61 of file ViewControllerBase\&.cs\&.
.SS "byte [] \fBCsla\&.Iosui\&.ViewControllerBase\fP< T, Z >\&.SerilizeModelForParameter ()\fC [protected]\fP"

.PP
Serializes the ViewModel's model property using the SerializationFormatterFactory\&.GetFormatter()\&. Used to serialize and transfer models between activities\&. 
.PP
\fBReturns\fP
.RS 4
An array of bytes that contains the serialized model\&.
.RE
.PP

.PP
Definition at line 41 of file ViewControllerBase\&.cs\&.
.SS "byte [] \fBCsla\&.Iosui\&.ViewControllerBase\fP< T, Z >\&.SerilizeModelForParameter (object model)\fC [protected]\fP"

.PP
Serialized the provided model using the SerializationFormatterFactory\&.GetFormatter()\&. Used to serialize and transfer models between activities\&. 
.PP
\fBParameters\fP
.RS 4
\fImodel\fP A reference to the model to serialize\&.
.RE
.PP
\fBReturns\fP
.RS 4
An array of bytes that contains the serialized model\&.
.RE
.PP

.PP
Definition at line 51 of file ViewControllerBase\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBBindingManager\fP \fBCsla\&.Iosui\&.ViewControllerBase\fP< T, Z >\&.Bindings = null\fC [protected]\fP"

.PP
The BindingManager for this Activity\&. 
.PP
Definition at line 35 of file ViewControllerBase\&.cs\&.
.SS "T \fBCsla\&.Iosui\&.ViewControllerBase\fP< T, Z >\&.viewModel = null\fC [protected]\fP"

.PP
A reference to the view model\&. 
.PP
Definition at line 30 of file ViewControllerBase\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
