.TH "Csla.Test.ObjectFactory.MissingRoot" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.ObjectFactory.MissingRoot
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.BusinessBase< Root >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBMarkAsNew\fP ()"
.br
.ti -1c
.RI "void \fBMarkAsOld\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBData\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "Csla\&.ApplicationContext\&.ExecutionLocations \fBLocation\fP\fC [get, set]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 18 of file MissingRoot\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Csla\&.Test\&.ObjectFactory\&.MissingRoot\&.MarkAsNew ()"

.PP
Definition at line 34 of file MissingRoot\&.cs\&.
.SS "void Csla\&.Test\&.ObjectFactory\&.MissingRoot\&.MarkAsOld ()"

.PP
Definition at line 39 of file MissingRoot\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "string Csla\&.Test\&.ObjectFactory\&.MissingRoot\&.Data\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 21 of file MissingRoot\&.cs\&.
.SS "Csla\&.ApplicationContext\&.ExecutionLocations Csla\&.Test\&.ObjectFactory\&.MissingRoot\&.Location\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 28 of file MissingRoot\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
