.TH "csla.netcore.test.DataPortal.SimpleType" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csla.netcore.test.DataPortal.SimpleType
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.BusinessBase< SimpleType >\fP\&.
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static readonly \fBPropertyInfo\fP< int > \fBIdProperty\fP = RegisterProperty<int>(c => c\&.Id)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBDataPortal_Insert\fP ()"
.br
.ti -1c
.RI "void \fBDataPortal_Update\fP ()"
.br
.ti -1c
.RI "void \fBDataPortal_DeleteSelf\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBId\fP\fC [get, set]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 117 of file DashboardTests\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void csla\&.netcore\&.test\&.DataPortal\&.SimpleType\&.DataPortal_DeleteSelf ()\fC [protected]\fP"

.PP
Definition at line 152 of file DashboardTests\&.cs\&.
.SS "void csla\&.netcore\&.test\&.DataPortal\&.SimpleType\&.DataPortal_Insert ()\fC [protected]\fP"

.PP
Definition at line 140 of file DashboardTests\&.cs\&.
.SS "void csla\&.netcore\&.test\&.DataPortal\&.SimpleType\&.DataPortal_Update ()\fC [protected]\fP"

.PP
Definition at line 146 of file DashboardTests\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "readonly \fBPropertyInfo\fP<int> csla\&.netcore\&.test\&.DataPortal\&.SimpleType\&.IdProperty = RegisterProperty<int>(c => c\&.Id)\fC [static]\fP"

.PP
Definition at line 119 of file DashboardTests\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "int csla\&.netcore\&.test\&.DataPortal\&.SimpleType\&.Id\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 120 of file DashboardTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
