.TH "Csla.Ios.Test" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Ios.Test
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBResourceStrings\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBApplication\fP"
.br
.ti -1c
.RI "class \fBNullableEntity\fP"
.br
.ti -1c
.RI "class \fBNullableTests\fP"
.br
.ti -1c
.RI "class \fBUnitTestAppDelegate\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
