.TH "Csla.Test.DataPortalTest" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.DataPortalTest
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBLegacy\fP"
.br
.ti -1c
.RI "class \fBLegacySplit\fP"
.br
.ti -1c
.RI "class \fBLegacySplitBase\fP"
.br
.ti -1c
.RI "class \fBLegacySplitTest\fP"
.br
.ti -1c
.RI "class \fBLegacyTest\fP"
.br
.ti -1c
.RI "class \fBSingleOverload\fP"
.br
.ti -1c
.RI "class \fBSingleOverloadTest\fP"
.br
.ti -1c
.RI "class \fBSingleTest\fP"
.br
.ti -1c
.RI "class \fBSplit\fP"
.br
.ti -1c
.RI "class \fBSplitBase\fP"
.br
.ti -1c
.RI "class \fBSplitOverload\fP"
.br
.ti -1c
.RI "class \fBSplitOverloadBase\fP"
.br
.ti -1c
.RI "class \fBSplitOverloadTest\fP"
.br
.ti -1c
.RI "class \fBSplitTest\fP"
.br
.ti -1c
.RI "class \fBPrimitiveCriteriaSingle\fP"
.br
.ti -1c
.RI "class \fBSingle\fP"
.br
.ti -1c
.RI "class \fBSingleWithFactory\fP"
.br
.ti -1c
.RI "class \fBSingleWithFactoryFactory\fP"
.br
.ti -1c
.RI "class \fBSingle2\fP"
.br
.ti -1c
.RI "class \fBSingleCommand\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
