.TH "Csla.Test.DataPortal.EditableChild1" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.DataPortal.EditableChild1
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.BusinessBase< EditableChild1 >\fP\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBChild_Create\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 67 of file DataPortalExceptionTest\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override void Csla\&.Test\&.DataPortal\&.EditableChild1\&.Child_Create ()\fC [protected]\fP"

.PP
Definition at line 80 of file DataPortalExceptionTest\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
