.TH "Csla.Test.ValidationRules.HasInvalidAsyncRule" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.ValidationRules.HasInvalidAsyncRule
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.BusinessBase< HasInvalidAsyncRule >\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBInvalidAsyncValidationRule\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "new \fBRules\&.BrokenRulesCollection\fP \fBGetBrokenRules\fP ()"
.br
.ti -1c
.RI "void \fBValidate\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBPropertyInfo\fP< string > \fBNameProperty\fP = RegisterProperty<string>(c => c\&.Name)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBAddBusinessRules\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBName\fP\fC [get, set]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 21 of file HasInvalidAsyncRule\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override void Csla\&.Test\&.ValidationRules\&.HasInvalidAsyncRule\&.AddBusinessRules ()\fC [protected]\fP"

.PP
Definition at line 30 of file HasInvalidAsyncRule\&.cs\&.
.SS "new \fBRules\&.BrokenRulesCollection\fP Csla\&.Test\&.ValidationRules\&.HasInvalidAsyncRule\&.GetBrokenRules ()"

.PP
Definition at line 36 of file HasInvalidAsyncRule\&.cs\&.
.SS "void Csla\&.Test\&.ValidationRules\&.HasInvalidAsyncRule\&.Validate ()"

.PP
Definition at line 41 of file HasInvalidAsyncRule\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBPropertyInfo\fP<string> Csla\&.Test\&.ValidationRules\&.HasInvalidAsyncRule\&.NameProperty = RegisterProperty<string>(c => c\&.Name)\fC [static]\fP"

.PP
Definition at line 23 of file HasInvalidAsyncRule\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "string Csla\&.Test\&.ValidationRules\&.HasInvalidAsyncRule\&.Name\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 24 of file HasInvalidAsyncRule\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
