.TH "Csla.Test.ValidationRules.Child" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.ValidationRules.Child
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.BusinessBase< Child >\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBId\fP\fC [get, set]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 19 of file Child\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "int Csla\&.Test\&.ValidationRules\&.Child\&.Id\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 22 of file Child\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
