.TH "cslalighttest.BusyStatus.BusyStatusTests" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cslalighttest.BusyStatus.BusyStatusTests
.SH SYNOPSIS
.br
.PP
.PP
Inherits TestBase\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "async Task \fBTestBusy\fP ()"
.br
.ti -1c
.RI "void \fBListTestBusy\fP ()"
.br
.ti -1c
.RI "async Task \fBTestSaveWhileBusy\fP ()"
.br
.ti -1c
.RI "async Task \fBListTestSaveWhileBusy\fP ()"
.br
.ti -1c
.RI "async Task \fBTestNotBusy\fP ()"
.br
.ti -1c
.RI "void \fBListTestNotBusy\fP ()"
.br
.ti -1c
.RI "void \fBListTestSaveWhileNotBusy\fP ()"
.br
.ti -1c
.RI "async Task \fBTestSaveWhileBusyNetOnly\fP ()"
.br
.ti -1c
.RI "void \fBListTestSaveWhileBusyNetOnly\fP ()"
.br
.ti -1c
.RI "async Task \fBTestSaveWhileNotBusyNetOnly\fP ()"
.br
.ti -1c
.RI "void \fBListTestSaveWhileNotBusyNetOnly\fP ()"
.br
.ti -1c
.RI "async Task \fBTestSaveWhileNotBusyNoActiveRuleNetOnly\fP ()"
.br
.ti -1c
.RI "void \fBListTestSaveWhileNotBusyNoActiveRuleNetOnly\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 30 of file BusyStatusTests\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void cslalighttest\&.BusyStatus\&.BusyStatusTests\&.ListTestBusy ()"

.PP
Definition at line 47 of file BusyStatusTests\&.cs\&.
.SS "void cslalighttest\&.BusyStatus\&.BusyStatusTests\&.ListTestNotBusy ()"

.PP
Definition at line 126 of file BusyStatusTests\&.cs\&.
.SS "async Task cslalighttest\&.BusyStatus\&.BusyStatusTests\&.ListTestSaveWhileBusy ()"

.PP
Definition at line 84 of file BusyStatusTests\&.cs\&.
.SS "void cslalighttest\&.BusyStatus\&.BusyStatusTests\&.ListTestSaveWhileBusyNetOnly ()"

.PP
Definition at line 181 of file BusyStatusTests\&.cs\&.
.SS "void cslalighttest\&.BusyStatus\&.BusyStatusTests\&.ListTestSaveWhileNotBusy ()"

.PP
Definition at line 144 of file BusyStatusTests\&.cs\&.
.SS "void cslalighttest\&.BusyStatus\&.BusyStatusTests\&.ListTestSaveWhileNotBusyNetOnly ()"

.PP
Definition at line 228 of file BusyStatusTests\&.cs\&.
.SS "void cslalighttest\&.BusyStatus\&.BusyStatusTests\&.ListTestSaveWhileNotBusyNoActiveRuleNetOnly ()"

.PP
Definition at line 270 of file BusyStatusTests\&.cs\&.
.SS "async Task cslalighttest\&.BusyStatus\&.BusyStatusTests\&.TestBusy ()"

.PP
Definition at line 34 of file BusyStatusTests\&.cs\&.
.SS "async Task cslalighttest\&.BusyStatus\&.BusyStatusTests\&.TestNotBusy ()"

.PP
Definition at line 109 of file BusyStatusTests\&.cs\&.
.SS "async Task cslalighttest\&.BusyStatus\&.BusyStatusTests\&.TestSaveWhileBusy ()"

.PP
Definition at line 60 of file BusyStatusTests\&.cs\&.
.SS "async Task cslalighttest\&.BusyStatus\&.BusyStatusTests\&.TestSaveWhileBusyNetOnly ()"

.PP
Definition at line 167 of file BusyStatusTests\&.cs\&.
.SS "async Task cslalighttest\&.BusyStatus\&.BusyStatusTests\&.TestSaveWhileNotBusyNetOnly ()"

.PP
Definition at line 208 of file BusyStatusTests\&.cs\&.
.SS "async Task cslalighttest\&.BusyStatus\&.BusyStatusTests\&.TestSaveWhileNotBusyNoActiveRuleNetOnly ()"

.PP
Definition at line 254 of file BusyStatusTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
