.TH "Csla.Analyzers.IntegrationTests.OperationsAndAttributes" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Analyzers.IntegrationTests.OperationsAndAttributes
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.BusinessBase< OperationsAndAttributes >\fP\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBDataPortal_Update\fP ()"
.br
.ti -1c
.RI "override void \fBChild_Create\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 6 of file OperationsAndAttributes\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override void Csla\&.Analyzers\&.IntegrationTests\&.OperationsAndAttributes\&.Child_Create ()\fC [protected]\fP"

.PP
Definition at line 12 of file OperationsAndAttributes\&.cs\&.
.SS "override void Csla\&.Analyzers\&.IntegrationTests\&.OperationsAndAttributes\&.DataPortal_Update ()\fC [protected]\fP"

.PP
Definition at line 10 of file OperationsAndAttributes\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
