.TH "Csla.Test.DPException.DataPortalExceptionTests" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.DPException.DataPortalExceptionTests
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBCheckInnerExceptionsOnDelete\fP ()"
.br
.ti -1c
.RI "void \fBCheckInnerExceptionsOnFetch\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 29 of file DataPortalExceptionTests\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Csla\&.Test\&.DPException\&.DataPortalExceptionTests\&.CheckInnerExceptionsOnDelete ()"

.PP
Definition at line 80 of file DataPortalExceptionTests\&.cs\&.
.SS "void Csla\&.Test\&.DPException\&.DataPortalExceptionTests\&.CheckInnerExceptionsOnFetch ()"

.PP
Definition at line 111 of file DataPortalExceptionTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
