.TH "csla.netcore.test.Configuration.ReadConfigFromDotnetCoreSubsystemTests" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csla.netcore.test.Configuration.ReadConfigFromDotnetCoreSubsystemTests
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBReadConfigCore\fP ()"
.br
.ti -1c
.RI "void \fBClearContextsAfterEachTest\fP ()"
.br
.ti -1c
.RI "void \fBCleanupConfigurationBeforeEachTest\fP ()"
.br
.ti -1c
.RI "void \fBDataPortalConfigCore\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 35 of file ReadConfigFromDotnetCoreSubsystemTests\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void csla\&.netcore\&.test\&.Configuration\&.ReadConfigFromDotnetCoreSubsystemTests\&.CleanupConfigurationBeforeEachTest ()"

.PP
Definition at line 98 of file ReadConfigFromDotnetCoreSubsystemTests\&.cs\&.
.SS "void csla\&.netcore\&.test\&.Configuration\&.ReadConfigFromDotnetCoreSubsystemTests\&.ClearContextsAfterEachTest ()"

.PP
Definition at line 58 of file ReadConfigFromDotnetCoreSubsystemTests\&.cs\&.
.SS "void csla\&.netcore\&.test\&.Configuration\&.ReadConfigFromDotnetCoreSubsystemTests\&.DataPortalConfigCore ()"

.PP
Definition at line 104 of file ReadConfigFromDotnetCoreSubsystemTests\&.cs\&.
.SS "void csla\&.netcore\&.test\&.Configuration\&.ReadConfigFromDotnetCoreSubsystemTests\&.ReadConfigCore ()"

.PP
Definition at line 38 of file ReadConfigFromDotnetCoreSubsystemTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
