.TH "Csla.Xaml.ErrorEventArgs" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Xaml.ErrorEventArgs \- Contains information about the error that has occurred\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits EventArgs\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "Exception \fBError\fP\fC [get, set]\fP"
.br
.RI "Gets the Exception object for the error that occurred\&. "
.in -1c
.SH "Detailed Description"
.PP 
Contains information about the error that has occurred\&. 


.PP
Definition at line 19 of file ErrorEventArgs\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "Exception Csla\&.Xaml\&.ErrorEventArgs\&.Error\fC [get]\fP, \fC [set]\fP"

.PP
Gets the Exception object for the error that occurred\&. 
.PP
Definition at line 25 of file ErrorEventArgs\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
