.TH "cslalighttest.Serialization.AddressBase" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cslalighttest.Serialization.AddressBase
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.BusinessBase< AddressBase >\fP\&.
.PP
Inherited by \fBcslalighttest\&.Serialization\&.Address\fP\&.
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static readonly \fBPropertyInfo\fP< string > \fBCityProperty\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBCity\fP\fC [get, set]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 15 of file AddressBase\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "readonly \fBPropertyInfo\fP<string> cslalighttest\&.Serialization\&.AddressBase\&.CityProperty\fC [static]\fP"
\fBInitial value:\fP
.PP
.nf
= RegisterProperty<string>(
      typeof(AddressBase),
      new PropertyInfo<string>("City"))
.fi
.PP
Definition at line 17 of file AddressBase\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "string cslalighttest\&.Serialization\&.AddressBase\&.City\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 21 of file AddressBase\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
