.TH "Csla.IDataPortalResult" 3 "Thu Jul 22 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.IDataPortalResult \- \fBIDataPortalResult\fP defines the results of \fBDataPortal\fP operation  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by Csla\&.Core\&.LoadManager\&.TaskDataPortalResult, and \fBCsla\&.DataPortalResult< T >\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "object \fBObject\fP\fC [get]\fP"
.br
.RI "Gets the resulting object\&. "
.ti -1c
.RI "Exception \fBError\fP\fC [get]\fP"
.br
.RI "Gets any resulting error information\&. "
.ti -1c
.RI "object \fBUserState\fP\fC [get]\fP"
.br
.RI "Gets the user state, pass through object "
.in -1c
.SH "Detailed Description"
.PP 
\fBIDataPortalResult\fP defines the results of \fBDataPortal\fP operation 


.PP
Definition at line 15 of file IDataPortalResult\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "Exception Csla\&.IDataPortalResult\&.Error\fC [get]\fP"

.PP
Gets any resulting error information\&. 
.PP
Definition at line 24 of file IDataPortalResult\&.cs\&.
.SS "object Csla\&.IDataPortalResult\&.Object\fC [get]\fP"

.PP
Gets the resulting object\&. 
.PP
Definition at line 20 of file IDataPortalResult\&.cs\&.
.SS "object Csla\&.IDataPortalResult\&.UserState\fC [get]\fP"

.PP
Gets the user state, pass through object The user state\&. 
.PP
Definition at line 31 of file IDataPortalResult\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
