.TH "Csla.Server.Hosts.HttpPortalController" 3 "Thu Jul 22 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Server.Hosts.HttpPortalController \- Exposes server-side \fBDataPortal\fP functionality through HTTP request/response\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits ApiController\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual async Task< HttpResponseMessage > \fBPostAsync\fP (string operation)"
.br
.RI "Entry point for all data portal operations\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBHttpPortal\fP \fBPortal\fP\fC [get, set]\fP"
.br
.RI "Gets or sets the \fBHttpPortal\fP implementation used to coordinate the data portal operations\&. "
.in -1c
.SH "Detailed Description"
.PP 
Exposes server-side \fBDataPortal\fP functionality through HTTP request/response\&. 


.PP
Definition at line 140 of file HttpPortalController\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual async Task<HttpResponseMessage> Csla\&.Server\&.Hosts\&.HttpPortalController\&.PostAsync (string operation)\fC [virtual]\fP"

.PP
Entry point for all data portal operations\&. 
.PP
\fBParameters\fP
.RS 4
\fIoperation\fP Name of the data portal operation to perform\&.
.RE
.PP
\fBReturns\fP
.RS 4
Results from the server-side data portal\&.
.RE
.PP

.PP
Definition at line 147 of file HttpPortalController\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "\fBHttpPortal\fP Csla\&.Server\&.Hosts\&.HttpPortalController\&.Portal\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the \fBHttpPortal\fP implementation used to coordinate the data portal operations\&. 
.PP
Definition at line 164 of file HttpPortalController\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
