.TH "Csla.Test.PropertyGetSet.EditableGetSetRuleValidation" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.PropertyGetSet.EditableGetSetRuleValidation
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.BusinessBase< EditableGetSetRuleValidation >\fP\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBEditableGetSetRuleValidation\fP \fBNewEditableGetSetValidation\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static readonly \fBPropertyInfo\fP< System\&.String > \fB_memberBackedIdProperty\fP = RegisterProperty<System\&.String>(p => p\&.MemberBackedId, \fBRelationshipTypes\&.PrivateField\fP)"
.br
.ti -1c
.RI "static readonly \fBPropertyInfo\fP< System\&.String > \fB_memberBackedIdWithNoRelationshipTypesProperty\fP = RegisterProperty<System\&.String>(p => p\&.MemberBackedIdWithNoRelationshipTypes, string\&.Empty)"
.br
.ti -1c
.RI "static readonly \fBPropertyInfo\fP< System\&.String > \fB_idProperty\fP = RegisterProperty<System\&.String>(p => p\&.Id, string\&.Empty)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBAddBusinessRules\fP ()"
.br
.ti -1c
.RI "void \fBDataPortal_Create\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "System\&.String \fBMemberBackedId\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "System\&.String \fBMemberBackedIdWithNoRelationshipTypes\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "System\&.String \fBId\fP\fC [get, set]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 16 of file EditableGetSetRuleValidation\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override void Csla\&.Test\&.PropertyGetSet\&.EditableGetSetRuleValidation\&.AddBusinessRules ()\fC [protected]\fP"

.PP
Definition at line 20 of file EditableGetSetRuleValidation\&.cs\&.
.SS "void Csla\&.Test\&.PropertyGetSet\&.EditableGetSetRuleValidation\&.DataPortal_Create ()\fC [protected]\fP"

.PP
Definition at line 65 of file EditableGetSetRuleValidation\&.cs\&.
.SS "static \fBEditableGetSetRuleValidation\fP Csla\&.Test\&.PropertyGetSet\&.EditableGetSetRuleValidation\&.NewEditableGetSetValidation ()\fC [static]\fP"

.PP
Definition at line 74 of file EditableGetSetRuleValidation\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "readonly \fBPropertyInfo\fP<System\&.String> Csla\&.Test\&.PropertyGetSet\&.EditableGetSetRuleValidation\&._idProperty = RegisterProperty<System\&.String>(p => p\&.Id, string\&.Empty)\fC [static]\fP"

.PP
Definition at line 52 of file EditableGetSetRuleValidation\&.cs\&.
.SS "readonly \fBPropertyInfo\fP<System\&.String> Csla\&.Test\&.PropertyGetSet\&.EditableGetSetRuleValidation\&._memberBackedIdProperty = RegisterProperty<System\&.String>(p => p\&.MemberBackedId, \fBRelationshipTypes\&.PrivateField\fP)\fC [static]\fP"

.PP
Definition at line 36 of file EditableGetSetRuleValidation\&.cs\&.
.SS "readonly \fBPropertyInfo\fP<System\&.String> Csla\&.Test\&.PropertyGetSet\&.EditableGetSetRuleValidation\&._memberBackedIdWithNoRelationshipTypesProperty = RegisterProperty<System\&.String>(p => p\&.MemberBackedIdWithNoRelationshipTypes, string\&.Empty)\fC [static]\fP"

.PP
Definition at line 44 of file EditableGetSetRuleValidation\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "System\&.String Csla\&.Test\&.PropertyGetSet\&.EditableGetSetRuleValidation\&.Id\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 53 of file EditableGetSetRuleValidation\&.cs\&.
.SS "System\&.String Csla\&.Test\&.PropertyGetSet\&.EditableGetSetRuleValidation\&.MemberBackedId\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 38 of file EditableGetSetRuleValidation\&.cs\&.
.SS "System\&.String Csla\&.Test\&.PropertyGetSet\&.EditableGetSetRuleValidation\&.MemberBackedIdWithNoRelationshipTypes\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 46 of file EditableGetSetRuleValidation\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
