.TH "Csla.Ios.Test.UnitTestAppDelegate" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Ios.Test.UnitTestAppDelegate
.SH SYNOPSIS
.br
.PP
.PP
Inherits UIApplicationDelegate\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override bool \fBFinishedLaunching\fP (UIApplication app, NSDictionary options)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 15 of file UnitTestAppDelegate\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override bool Csla\&.Ios\&.Test\&.UnitTestAppDelegate\&.FinishedLaunching (UIApplication app, NSDictionary options)"

.PP
Definition at line 28 of file UnitTestAppDelegate\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
