.TH "CslaBinaryWriter.cs" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CslaBinaryWriter.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCsla\&.Serialization\&.Mobile\&.CslaBinaryWriter\fP"
.br
.RI "This is a class that is responsible for serializing \fBSerializationInfo\fP objects into a Stream for sending the data t client / server "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBCsla\fP"
.br
.ti -1c
.RI "namespace \fBCsla\&.Serialization\fP"
.br
.ti -1c
.RI "namespace \fBCsla\&.Serialization\&.Mobile\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
