.TH "Csla.UpdateAttribute" 3 "Thu Jul 22 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.UpdateAttribute \- Specifies a method used by the server-side data portal to update domain object data during an update operation\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.DataPortalRootOperationAttribute\fP\&.
.SH "Detailed Description"
.PP 
Specifies a method used by the server-side data portal to update domain object data during an update operation\&. 


.PP
Definition at line 77 of file DataPortalOperationAttributes\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
