.TH "Csla.Blazor.CslaPermissionsPolicyProvider" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Blazor.CslaPermissionsPolicyProvider \- CSLA permissions policy provider\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits IAuthorizationPolicyProvider\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCslaPermissionsPolicyProvider\fP (IOptions< AuthorizationOptions > options)"
.br
.RI "Creates an instance of the type "
.ti -1c
.RI "Task< AuthorizationPolicy > \fBGetDefaultPolicyAsync\fP ()"
.br
.RI "Gets the default policy "
.ti -1c
.RI "Task< AuthorizationPolicy > \fBGetFallbackPolicyAsync\fP ()"
.br
.RI "Gets the fallback policy "
.ti -1c
.RI "Task< AuthorizationPolicy > \fBGetPolicyAsync\fP (string policyName)"
.br
.RI "Gets the authorization policy "
.in -1c
.SH "Detailed Description"
.PP 
CSLA permissions policy provider\&. 


.PP
Definition at line 19 of file CslaPermissionsPolicyProvider\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Csla\&.Blazor\&.CslaPermissionsPolicyProvider\&.CslaPermissionsPolicyProvider (IOptions< AuthorizationOptions > options)"

.PP
Creates an instance of the type 
.PP
\fBParameters\fP
.RS 4
\fIoptions\fP Authorization options
.RE
.PP

.PP
Definition at line 27 of file CslaPermissionsPolicyProvider\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "Task<AuthorizationPolicy> Csla\&.Blazor\&.CslaPermissionsPolicyProvider\&.GetDefaultPolicyAsync ()"

.PP
Gets the default policy 
.PP
\fBReturns\fP
.RS 4

.RE
.PP

.SS "Task<AuthorizationPolicy> Csla\&.Blazor\&.CslaPermissionsPolicyProvider\&.GetFallbackPolicyAsync ()"

.PP
Gets the fallback policy 
.PP
\fBReturns\fP
.RS 4

.RE
.PP

.SS "Task<AuthorizationPolicy> Csla\&.Blazor\&.CslaPermissionsPolicyProvider\&.GetPolicyAsync (string policyName)"

.PP
Gets the authorization policy 
.PP
\fBParameters\fP
.RS 4
\fIpolicyName\fP String representing the policy
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP
.PP
Gets a CSLA permissions policy if the policy name corresponds to a CSLA policy, otherwise gets a policy from the fallback provider\&. 
.PP
Definition at line 58 of file CslaPermissionsPolicyProvider\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
