.TH "Csla.Test.ValidationRules.RuleURITests" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.ValidationRules.RuleURITests
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBRuleURIWithGenericObjectRule\fP ()"
.br
.ti -1c
.RI "void \fBRuleURIWithNonGenericType\fP ()"
.br
.ti -1c
.RI "void \fBRuleURIWithGenericType\fP ()"
.br
.ti -1c
.RI "void \fBRuleURIWithObjectRule\fP ()"
.br
.ti -1c
.RI "void \fBLambdaRuleExtensionsAddUniueURIs\fP ()"
.br
.ti -1c
.RI "void \fBRuleWithCyrillicNameMustHaveValidURI\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 25 of file RuleURITests\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Csla\&.Test\&.ValidationRules\&.RuleURITests\&.LambdaRuleExtensionsAddUniueURIs ()"

.PP
Definition at line 59 of file RuleURITests\&.cs\&.
.SS "void Csla\&.Test\&.ValidationRules\&.RuleURITests\&.RuleURIWithGenericObjectRule ()"

.PP
Definition at line 29 of file RuleURITests\&.cs\&.
.SS "void Csla\&.Test\&.ValidationRules\&.RuleURITests\&.RuleURIWithGenericType ()"

.PP
Definition at line 44 of file RuleURITests\&.cs\&.
.SS "void Csla\&.Test\&.ValidationRules\&.RuleURITests\&.RuleURIWithNonGenericType ()"

.PP
Definition at line 36 of file RuleURITests\&.cs\&.
.SS "void Csla\&.Test\&.ValidationRules\&.RuleURITests\&.RuleURIWithObjectRule ()"

.PP
Definition at line 52 of file RuleURITests\&.cs\&.
.SS "void Csla\&.Test\&.ValidationRules\&.RuleURITests\&.RuleWithCyrillicNameMustHaveValidURI ()"

.PP
Definition at line 70 of file RuleURITests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
