.TH "Csla.Testing.Business.ReadOnlyTest.ReadOnlyPerson" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Testing.Business.ReadOnlyTest.ReadOnlyPerson
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.ReadOnlyBase< ReadOnlyPerson >\fP\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBReadOnlyPerson\fP \fBGetReadOnlyPersonForList\fP (string personName, int year)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "const string \fBDataPortalUrl\fP = 'http://localhost:4832/WcfPortal\&.svc'"
.br
.ti -1c
.RI "static readonly \fBPropertyInfo\fP< Guid > \fBIdProperty\fP = RegisterProperty<Guid>(typeof(\fBReadOnlyPerson\fP), new \fBPropertyInfo\fP<Guid>('Id'))"
.br
.ti -1c
.RI "static readonly \fBPropertyInfo\fP< string > \fBNameProperty\fP = RegisterProperty<string>(typeof(\fBReadOnlyPerson\fP), new \fBPropertyInfo\fP<string>('Name'))"
.br
.ti -1c
.RI "static readonly \fBPropertyInfo\fP< DateTime > \fBBirthdateProperty\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "Guid \fBId\fP\fC [get]\fP"
.br
.ti -1c
.RI "string \fBName\fP\fC [get]\fP"
.br
.ti -1c
.RI "DateTime \fBBirthdate\fP\fC [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 13 of file Silverlight/Server/ReadOnlyTests/ReadOnlyPerson\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "static \fBReadOnlyPerson\fP Csla\&.Testing\&.Business\&.ReadOnlyTest\&.ReadOnlyPerson\&.GetReadOnlyPersonForList (string personName, int year)\fC [static]\fP"

.PP
Definition at line 43 of file Silverlight/Server/ReadOnlyTests/ReadOnlyPerson\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "readonly \fBPropertyInfo\fP<DateTime> Csla\&.Testing\&.Business\&.ReadOnlyTest\&.ReadOnlyPerson\&.BirthdateProperty\fC [static]\fP"
\fBInitial value:\fP
.PP
.nf
= RegisterProperty<DateTime>(
      typeof(ReadOnlyPerson),
      new PropertyInfo<DateTime>("Birthdate"))
.fi
.PP
Definition at line 23 of file Silverlight/Server/ReadOnlyTests/ReadOnlyPerson\&.cs\&.
.SS "const string Csla\&.Testing\&.Business\&.ReadOnlyTest\&.ReadOnlyPerson\&.DataPortalUrl = 'http://localhost:4832/WcfPortal\&.svc'\fC [static]\fP"

.PP
Definition at line 15 of file Silverlight/Server/ReadOnlyTests/ReadOnlyPerson\&.cs\&.
.SS "readonly \fBPropertyInfo\fP<Guid> Csla\&.Testing\&.Business\&.ReadOnlyTest\&.ReadOnlyPerson\&.IdProperty = RegisterProperty<Guid>(typeof(\fBReadOnlyPerson\fP), new \fBPropertyInfo\fP<Guid>('Id'))\fC [static]\fP"

.PP
Definition at line 19 of file Silverlight/Server/ReadOnlyTests/ReadOnlyPerson\&.cs\&.
.SS "readonly \fBPropertyInfo\fP<string> Csla\&.Testing\&.Business\&.ReadOnlyTest\&.ReadOnlyPerson\&.NameProperty = RegisterProperty<string>(typeof(\fBReadOnlyPerson\fP), new \fBPropertyInfo\fP<string>('Name'))\fC [static]\fP"

.PP
Definition at line 21 of file Silverlight/Server/ReadOnlyTests/ReadOnlyPerson\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "DateTime Csla\&.Testing\&.Business\&.ReadOnlyTest\&.ReadOnlyPerson\&.Birthdate\fC [get]\fP"

.PP
Definition at line 38 of file Silverlight/Server/ReadOnlyTests/ReadOnlyPerson\&.cs\&.
.SS "Guid Csla\&.Testing\&.Business\&.ReadOnlyTest\&.ReadOnlyPerson\&.Id\fC [get]\fP"

.PP
Definition at line 27 of file Silverlight/Server/ReadOnlyTests/ReadOnlyPerson\&.cs\&.
.SS "string Csla\&.Testing\&.Business\&.ReadOnlyTest\&.ReadOnlyPerson\&.Name\fC [get]\fP"

.PP
Definition at line 33 of file Silverlight/Server/ReadOnlyTests/ReadOnlyPerson\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
