.TH "Csla.WcfPortal.IWcfPortal" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.WcfPortal.IWcfPortal
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBCsla\&.WcfPortal\&.IWcfPortalChannel\fP, and \fBCsla\&.WcfPortal\&.WcfPortalClient\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCsla\&.WcfPortal\&.WcfResponse\fP \fBCreate\fP (\fBCsla\&.WcfPortal\&.CriteriaRequest\fP request)"
.br
.ti -1c
.RI "System\&.Threading\&.Tasks\&.Task< \fBCsla\&.WcfPortal\&.WcfResponse\fP > \fBCreateAsync\fP (\fBCsla\&.WcfPortal\&.CriteriaRequest\fP request)"
.br
.ti -1c
.RI "\fBCsla\&.WcfPortal\&.WcfResponse\fP \fBFetch\fP (\fBCsla\&.WcfPortal\&.CriteriaRequest\fP request)"
.br
.ti -1c
.RI "System\&.Threading\&.Tasks\&.Task< \fBCsla\&.WcfPortal\&.WcfResponse\fP > \fBFetchAsync\fP (\fBCsla\&.WcfPortal\&.CriteriaRequest\fP request)"
.br
.ti -1c
.RI "\fBCsla\&.WcfPortal\&.WcfResponse\fP \fBUpdate\fP (\fBCsla\&.WcfPortal\&.UpdateRequest\fP request)"
.br
.ti -1c
.RI "System\&.Threading\&.Tasks\&.Task< \fBCsla\&.WcfPortal\&.WcfResponse\fP > \fBUpdateAsync\fP (\fBCsla\&.WcfPortal\&.UpdateRequest\fP request)"
.br
.ti -1c
.RI "\fBCsla\&.WcfPortal\&.WcfResponse\fP \fBDelete\fP (\fBCsla\&.WcfPortal\&.CriteriaRequest\fP request)"
.br
.ti -1c
.RI "System\&.Threading\&.Tasks\&.Task< \fBCsla\&.WcfPortal\&.WcfResponse\fP > \fBDeleteAsync\fP (\fBCsla\&.WcfPortal\&.CriteriaRequest\fP request)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 487 of file Reference\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBCsla\&.WcfPortal\&.WcfResponse\fP Csla\&.WcfPortal\&.IWcfPortal\&.Create (\fBCsla\&.WcfPortal\&.CriteriaRequest\fP request)"

.PP
Implemented in \fBCsla\&.WcfPortal\&.WcfPortalClient\fP\&.
.SS "System\&.Threading\&.Tasks\&.Task<\fBCsla\&.WcfPortal\&.WcfResponse\fP> Csla\&.WcfPortal\&.IWcfPortal\&.CreateAsync (\fBCsla\&.WcfPortal\&.CriteriaRequest\fP request)"

.PP
Implemented in \fBCsla\&.WcfPortal\&.WcfPortalClient\fP\&.
.SS "\fBCsla\&.WcfPortal\&.WcfResponse\fP Csla\&.WcfPortal\&.IWcfPortal\&.Delete (\fBCsla\&.WcfPortal\&.CriteriaRequest\fP request)"

.PP
Implemented in \fBCsla\&.WcfPortal\&.WcfPortalClient\fP\&.
.SS "System\&.Threading\&.Tasks\&.Task<\fBCsla\&.WcfPortal\&.WcfResponse\fP> Csla\&.WcfPortal\&.IWcfPortal\&.DeleteAsync (\fBCsla\&.WcfPortal\&.CriteriaRequest\fP request)"

.PP
Implemented in \fBCsla\&.WcfPortal\&.WcfPortalClient\fP\&.
.SS "\fBCsla\&.WcfPortal\&.WcfResponse\fP Csla\&.WcfPortal\&.IWcfPortal\&.Fetch (\fBCsla\&.WcfPortal\&.CriteriaRequest\fP request)"

.PP
Implemented in \fBCsla\&.WcfPortal\&.WcfPortalClient\fP\&.
.SS "System\&.Threading\&.Tasks\&.Task<\fBCsla\&.WcfPortal\&.WcfResponse\fP> Csla\&.WcfPortal\&.IWcfPortal\&.FetchAsync (\fBCsla\&.WcfPortal\&.CriteriaRequest\fP request)"

.PP
Implemented in \fBCsla\&.WcfPortal\&.WcfPortalClient\fP\&.
.SS "\fBCsla\&.WcfPortal\&.WcfResponse\fP Csla\&.WcfPortal\&.IWcfPortal\&.Update (\fBCsla\&.WcfPortal\&.UpdateRequest\fP request)"

.PP
Implemented in \fBCsla\&.WcfPortal\&.WcfPortalClient\fP\&.
.SS "System\&.Threading\&.Tasks\&.Task<\fBCsla\&.WcfPortal\&.WcfResponse\fP> Csla\&.WcfPortal\&.IWcfPortal\&.UpdateAsync (\fBCsla\&.WcfPortal\&.UpdateRequest\fP request)"

.PP
Implemented in \fBCsla\&.WcfPortal\&.WcfPortalClient\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
