.TH "Csla.Test.PropertyGetSet.ChildList" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.PropertyGetSet.ChildList
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.BusinessListBase< ChildList, EditableGetSet >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBChildList\fP ()"
.br
.ti -1c
.RI "\fBChildList\fP (bool isChild)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "new int \fBEditLevel\fP\fC [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 17 of file ChildList\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Csla\&.Test\&.PropertyGetSet\&.ChildList\&.ChildList ()"

.PP
Definition at line 19 of file ChildList\&.cs\&.
.SS "Csla\&.Test\&.PropertyGetSet\&.ChildList\&.ChildList (bool isChild)"

.PP
Definition at line 22 of file ChildList\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "new int Csla\&.Test\&.PropertyGetSet\&.ChildList\&.EditLevel\fC [get]\fP"

.PP
Definition at line 27 of file ChildList\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
