.TH "Csla.Test.DataPortal.FactoryBusyFactory" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.DataPortal.FactoryBusyFactory
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.Server\&.ObjectFactory\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFactoryBusy\fP \fBFetch\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 431 of file DataPortalTests\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBFactoryBusy\fP Csla\&.Test\&.DataPortal\&.FactoryBusyFactory\&.Fetch ()"

.PP
Definition at line 433 of file DataPortalTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
