.TH "Csla.Server.ServicedDataPortalRepeatableRead" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Server.ServicedDataPortalRepeatableRead \- Implements the server-side Serviced \fBDataPortal\fP described in Chapter 4\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits ServicedComponent, and \fBCsla\&.Server\&.IDataPortalServer\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "async Task< \fBDataPortalResult\fP > \fBCreate\fP (Type objectType, object criteria, \fBDataPortalContext\fP context, bool isSync)"
.br
.RI "Wraps a Create call in a ServicedComponent\&. "
.ti -1c
.RI "async Task< \fBDataPortalResult\fP > \fBFetch\fP (Type objectType, object criteria, \fBDataPortalContext\fP context, bool isSync)"
.br
.RI "Wraps a Fetch call in a ServicedComponent\&. "
.ti -1c
.RI "async Task< \fBDataPortalResult\fP > \fBUpdate\fP (object obj, \fBDataPortalContext\fP context, bool isSync)"
.br
.RI "Wraps an Update call in a ServicedComponent\&. "
.ti -1c
.RI "async Task< \fBDataPortalResult\fP > \fBDelete\fP (Type objectType, object criteria, \fBDataPortalContext\fP context, bool isSync)"
.br
.RI "Wraps a Delete call in a ServicedComponent\&. "
.in -1c
.SH "Detailed Description"
.PP 
Implements the server-side Serviced \fBDataPortal\fP described in Chapter 4\&. 


.PP
Definition at line 23 of file ServicedDataPortalRepeatableRead\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "async Task<\fBDataPortalResult\fP> Csla\&.Server\&.ServicedDataPortalRepeatableRead\&.Create (Type objectType, object criteria, \fBDataPortalContext\fP context, bool isSync)"

.PP
Wraps a Create call in a ServicedComponent\&. This method delegates to \fBSimpleDataPortal\fP but wraps that call within a COM+ transaction to provide transactional support\&. 
.PP
\fBParameters\fP
.RS 4
\fIobjectType\fP A \fBType\fP object indicating the type of business object to be created\&.
.br
\fIcriteria\fP A custom criteria object providing any extra information that may be required to properly create the object\&.
.br
\fIcontext\fP Context data from the client\&.
.br
\fIisSync\fP True if the client-side proxy should synchronously invoke the server\&.
.RE
.PP
\fBReturns\fP
.RS 4
A populated business object\&.
.RE
.PP

.PP
Implements \fBCsla\&.Server\&.IDataPortalServer\fP\&.
.PP
Definition at line 43 of file ServicedDataPortalRepeatableRead\&.cs\&.
.SS "async Task<\fBDataPortalResult\fP> Csla\&.Server\&.ServicedDataPortalRepeatableRead\&.Delete (Type objectType, object criteria, \fBDataPortalContext\fP context, bool isSync)"

.PP
Wraps a Delete call in a ServicedComponent\&. This method delegates to \fBSimpleDataPortal\fP but wraps that call within a COM+ transaction to provide transactional support\&. 
.PP
\fBParameters\fP
.RS 4
\fIobjectType\fP Type of business object to create\&.
.br
\fIcriteria\fP Object-specific criteria\&.
.br
\fIcontext\fP Context data from the client\&.
.br
\fIisSync\fP True if the client-side proxy should synchronously invoke the server\&.
.RE
.PP

.PP
Implements \fBCsla\&.Server\&.IDataPortalServer\fP\&.
.PP
Definition at line 105 of file ServicedDataPortalRepeatableRead\&.cs\&.
.SS "async Task<\fBDataPortalResult\fP> Csla\&.Server\&.ServicedDataPortalRepeatableRead\&.Fetch (Type objectType, object criteria, \fBDataPortalContext\fP context, bool isSync)"

.PP
Wraps a Fetch call in a ServicedComponent\&. This method delegates to \fBSimpleDataPortal\fP but wraps that call within a COM+ transaction to provide transactional support\&. 
.PP
\fBParameters\fP
.RS 4
\fIobjectType\fP Type of business object to retrieve\&.
.br
\fIcriteria\fP Object-specific criteria\&.
.br
\fIcontext\fP Object containing context data from client\&.
.br
\fIisSync\fP True if the client-side proxy should synchronously invoke the server\&.
.RE
.PP
\fBReturns\fP
.RS 4
A populated business object\&.
.RE
.PP

.PP
Implements \fBCsla\&.Server\&.IDataPortalServer\fP\&.
.PP
Definition at line 65 of file ServicedDataPortalRepeatableRead\&.cs\&.
.SS "async Task<\fBDataPortalResult\fP> Csla\&.Server\&.ServicedDataPortalRepeatableRead\&.Update (object obj, \fBDataPortalContext\fP context, bool isSync)"

.PP
Wraps an Update call in a ServicedComponent\&. This method delegates to \fBSimpleDataPortal\fP but wraps that call within a COM+ transaction to provide transactional support\&. 
.PP
\fBParameters\fP
.RS 4
\fIobj\fP A reference to the object being updated\&.
.br
\fIcontext\fP Context data from the client\&.
.br
\fIisSync\fP True if the client-side proxy should synchronously invoke the server\&.
.RE
.PP
\fBReturns\fP
.RS 4
A reference to the newly updated object\&.
.RE
.PP

.PP
Implements \fBCsla\&.Server\&.IDataPortalServer\fP\&.
.PP
Definition at line 85 of file ServicedDataPortalRepeatableRead\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
