.TH "Csla.Test.Nullable.NullableTests" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.Nullable.NullableTests
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBTestNullableProperty\fP ()"
.br
.ti -1c
.RI "void \fBTestNullableField\fP ()"
.br
.ti -1c
.RI "void \fBTestNullableAfterClone\fP ()"
.br
.ti -1c
.RI "void \fBTestNullableAfterEditCycle\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 26 of file Csla\&.test/Nullable/NullableTests\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Csla\&.Test\&.Nullable\&.NullableTests\&.TestNullableAfterClone ()"

.PP
Definition at line 52 of file Csla\&.test/Nullable/NullableTests\&.cs\&.
.SS "void Csla\&.Test\&.Nullable\&.NullableTests\&.TestNullableAfterEditCycle ()"

.PP
Definition at line 65 of file Csla\&.test/Nullable/NullableTests\&.cs\&.
.SS "void Csla\&.Test\&.Nullable\&.NullableTests\&.TestNullableField ()"

.PP
Definition at line 42 of file Csla\&.test/Nullable/NullableTests\&.cs\&.
.SS "void Csla\&.Test\&.Nullable\&.NullableTests\&.TestNullableProperty ()"

.PP
Definition at line 30 of file Csla\&.test/Nullable/NullableTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
