.TH "Csla.Ios.Test.NullableTests" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Ios.Test.NullableTests
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBTestEditNullableWithValueProperty\fP ()"
.br
.ti -1c
.RI "void \fBTestEditNullableWithNullProperty\fP ()"
.br
.ti -1c
.RI "void \fBTestEditNullableViaBusinessRuleProperty\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 8 of file Csla\&.Ios\&.Test/Nullable/NullableTests\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Csla\&.Ios\&.Test\&.NullableTests\&.TestEditNullableViaBusinessRuleProperty ()"

.PP
Definition at line 30 of file Csla\&.Ios\&.Test/Nullable/NullableTests\&.cs\&.
.SS "void Csla\&.Ios\&.Test\&.NullableTests\&.TestEditNullableWithNullProperty ()"

.PP
Definition at line 20 of file Csla\&.Ios\&.Test/Nullable/NullableTests\&.cs\&.
.SS "void Csla\&.Ios\&.Test\&.NullableTests\&.TestEditNullableWithValueProperty ()"

.PP
Definition at line 11 of file Csla\&.Ios\&.Test/Nullable/NullableTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
