.TH "cslalighttest.ReadOnly" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cslalighttest.ReadOnly
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMockReadOnly\fP"
.br
.ti -1c
.RI "class \fBMockReadOnlyList\fP"
.br
.ti -1c
.RI "class \fBReadOnlyTests\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
