.TH "Csla.Analyzers.Tests.FindGetOrReadInvocationsWalkerTests" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Analyzers.Tests.FindGetOrReadInvocationsWalkerTests
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "async Task \fBWalkWhenContainingTypeIsNotBusinessBase\fP ()"
.br
.ti -1c
.RI "async Task \fBWalkWhenContainingTypeIsBusinessBaseAndInvocationIsNotCslaMethod\fP ()"
.br
.ti -1c
.RI "async Task \fBWalkWhenContainingTypeIsBusinessBaseAndInvocationIsGetProperty\fP ()"
.br
.ti -1c
.RI "async Task \fBWalkWhenContainingTypeIsBusinessBaseAndInvocationIsGetPropertyConvert\fP ()"
.br
.ti -1c
.RI "async Task \fBWalkWhenContainingTypeIsBusinessBaseAndInvocationIsReadProperty\fP ()"
.br
.ti -1c
.RI "async Task \fBWalkWhenContainingTypeIsBusinessBaseAndInvocationIsReadPropertyConvert\fP ()"
.br
.ti -1c
.RI "async Task \fBWalkWhenContainingTypeIsBusinessBaseAndInvocationIsLazyGetProperty\fP ()"
.br
.ti -1c
.RI "async Task \fBWalkWhenContainingTypeIsBusinessBaseAndInvocationIsLazyGetPropertyAsync\fP ()"
.br
.ti -1c
.RI "async Task \fBWalkWhenContainingTypeIsBusinessBaseAndInvocationIsLazyReadProperty\fP ()"
.br
.ti -1c
.RI "async Task \fBWalkWhenContainingTypeIsBusinessBaseAndInvocationIsLazyReadPropertyAsync\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 7 of file FindGetOrReadInvocationsWalkerTests\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "async Task Csla\&.Analyzers\&.Tests\&.FindGetOrReadInvocationsWalkerTests\&.WalkWhenContainingTypeIsBusinessBaseAndInvocationIsGetProperty ()"

.PP
Definition at line 41 of file FindGetOrReadInvocationsWalkerTests\&.cs\&.
.SS "async Task Csla\&.Analyzers\&.Tests\&.FindGetOrReadInvocationsWalkerTests\&.WalkWhenContainingTypeIsBusinessBaseAndInvocationIsGetPropertyConvert ()"

.PP
Definition at line 55 of file FindGetOrReadInvocationsWalkerTests\&.cs\&.
.SS "async Task Csla\&.Analyzers\&.Tests\&.FindGetOrReadInvocationsWalkerTests\&.WalkWhenContainingTypeIsBusinessBaseAndInvocationIsLazyGetProperty ()"

.PP
Definition at line 97 of file FindGetOrReadInvocationsWalkerTests\&.cs\&.
.SS "async Task Csla\&.Analyzers\&.Tests\&.FindGetOrReadInvocationsWalkerTests\&.WalkWhenContainingTypeIsBusinessBaseAndInvocationIsLazyGetPropertyAsync ()"

.PP
Definition at line 111 of file FindGetOrReadInvocationsWalkerTests\&.cs\&.
.SS "async Task Csla\&.Analyzers\&.Tests\&.FindGetOrReadInvocationsWalkerTests\&.WalkWhenContainingTypeIsBusinessBaseAndInvocationIsLazyReadProperty ()"

.PP
Definition at line 125 of file FindGetOrReadInvocationsWalkerTests\&.cs\&.
.SS "async Task Csla\&.Analyzers\&.Tests\&.FindGetOrReadInvocationsWalkerTests\&.WalkWhenContainingTypeIsBusinessBaseAndInvocationIsLazyReadPropertyAsync ()"

.PP
Definition at line 139 of file FindGetOrReadInvocationsWalkerTests\&.cs\&.
.SS "async Task Csla\&.Analyzers\&.Tests\&.FindGetOrReadInvocationsWalkerTests\&.WalkWhenContainingTypeIsBusinessBaseAndInvocationIsNotCslaMethod ()"

.PP
Definition at line 27 of file FindGetOrReadInvocationsWalkerTests\&.cs\&.
.SS "async Task Csla\&.Analyzers\&.Tests\&.FindGetOrReadInvocationsWalkerTests\&.WalkWhenContainingTypeIsBusinessBaseAndInvocationIsReadProperty ()"

.PP
Definition at line 69 of file FindGetOrReadInvocationsWalkerTests\&.cs\&.
.SS "async Task Csla\&.Analyzers\&.Tests\&.FindGetOrReadInvocationsWalkerTests\&.WalkWhenContainingTypeIsBusinessBaseAndInvocationIsReadPropertyConvert ()"

.PP
Definition at line 83 of file FindGetOrReadInvocationsWalkerTests\&.cs\&.
.SS "async Task Csla\&.Analyzers\&.Tests\&.FindGetOrReadInvocationsWalkerTests\&.WalkWhenContainingTypeIsNotBusinessBase ()"

.PP
Definition at line 19 of file FindGetOrReadInvocationsWalkerTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
