.TH "Csla.Test.Silverlight.PropertyGetSet.InheritedLoadPropertySet" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.Silverlight.PropertyGetSet.InheritedLoadPropertySet
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.Test\&.Silverlight\&.PropertyGetSet\&.AbstractGetSet< InheritedLoadPropertySet >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBInheritedLoadPropertySet\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnDeserialized\fP (System\&.Runtime\&.Serialization\&.StreamingContext context)"
.br
.ti -1c
.RI "void \fBDataPortal_Insert\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 13 of file InheritedLoadPropertySet\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Csla\&.Test\&.Silverlight\&.PropertyGetSet\&.InheritedLoadPropertySet\&.InheritedLoadPropertySet ()"

.PP
Definition at line 19 of file InheritedLoadPropertySet\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Csla\&.Test\&.Silverlight\&.PropertyGetSet\&.InheritedLoadPropertySet\&.DataPortal_Insert ()\fC [protected]\fP"

.PP
Definition at line 37 of file InheritedLoadPropertySet\&.cs\&.
.SS "override void Csla\&.Test\&.Silverlight\&.PropertyGetSet\&.InheritedLoadPropertySet\&.OnDeserialized (System\&.Runtime\&.Serialization\&.StreamingContext context)\fC [protected]\fP"

.PP
Definition at line 30 of file InheritedLoadPropertySet\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
