.TH "Csla.Test.ValidationRules.NoErrorRoot" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.ValidationRules.NoErrorRoot
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.BusinessBase< NoErrorRoot >\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAlwaysInfo\fP"
.br
.ti -1c
.RI "class \fBAlwaysWarns\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBValidate\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBPropertyInfo\fP< string > \fBTestProperty\fP = RegisterProperty<string>(c => c\&.Test)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBAddBusinessRules\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBTest\fP\fC [get, set]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 60 of file SeverityClasses\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override void Csla\&.Test\&.ValidationRules\&.NoErrorRoot\&.AddBusinessRules ()\fC [protected]\fP"

.PP
Definition at line 74 of file SeverityClasses\&.cs\&.
.SS "void Csla\&.Test\&.ValidationRules\&.NoErrorRoot\&.Validate ()"

.PP
Definition at line 69 of file SeverityClasses\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBPropertyInfo\fP<string> Csla\&.Test\&.ValidationRules\&.NoErrorRoot\&.TestProperty = RegisterProperty<string>(c => c\&.Test)\fC [static]\fP"

.PP
Definition at line 62 of file SeverityClasses\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "string Csla\&.Test\&.ValidationRules\&.NoErrorRoot\&.Test\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 63 of file SeverityClasses\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
