.TH "Csla.Analyzers.AsynchronousBusinessRuleInheritingFromBusinessRuleChangeToBusinessRuleAsyncCodeFix" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Analyzers.AsynchronousBusinessRuleInheritingFromBusinessRuleChangeToBusinessRuleAsyncCodeFix
.SH SYNOPSIS
.br
.PP
.PP
Inherits CodeFixProvider\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "sealed override FixAllProvider \fBGetFixAllProvider\fP ()"
.br
.ti -1c
.RI "override async Task \fBRegisterCodeFixesAsync\fP (CodeFixContext context)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override ImmutableArray< string > \fBFixableDiagnosticIds\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 17 of file AsynchronousBusinessRuleInheritingFromBusinessRuleChangeToBusinessRuleAsyncCodeFix\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "sealed override FixAllProvider Csla\&.Analyzers\&.AsynchronousBusinessRuleInheritingFromBusinessRuleChangeToBusinessRuleAsyncCodeFix\&.GetFixAllProvider ()"

.SS "override async Task Csla\&.Analyzers\&.AsynchronousBusinessRuleInheritingFromBusinessRuleChangeToBusinessRuleAsyncCodeFix\&.RegisterCodeFixesAsync (CodeFixContext context)"

.PP
Definition at line 25 of file AsynchronousBusinessRuleInheritingFromBusinessRuleChangeToBusinessRuleAsyncCodeFix\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "override ImmutableArray<string> Csla\&.Analyzers\&.AsynchronousBusinessRuleInheritingFromBusinessRuleChangeToBusinessRuleAsyncCodeFix\&.FixableDiagnosticIds\fC [get]\fP"

.PP
Definition at line 20 of file AsynchronousBusinessRuleInheritingFromBusinessRuleChangeToBusinessRuleAsyncCodeFix\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
