.TH "Csla.Xaml.BrokenRuleSeverityConverter" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Xaml.BrokenRuleSeverityConverter \- Converts validation severity values into corresponding images\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits IValueConverter\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "object \fBConvert\fP (object value, Type targetType, object parameter, System\&.Globalization\&.CultureInfo culture)"
.br
.RI "Converts validation severity values into corresponding images\&. "
.ti -1c
.RI "object \fBConvertBack\fP (object value, Type targetType, object parameter, System\&.Globalization\&.CultureInfo culture)"
.br
.RI "Returns the original value\&. "
.in -1c
.SH "Detailed Description"
.PP 
Converts validation severity values into corresponding images\&. 


.PP
Definition at line 22 of file BrokenRulesSeverityConverter\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "object Csla\&.Xaml\&.BrokenRuleSeverityConverter\&.Convert (object value, Type targetType, object parameter, System\&.Globalization\&.CultureInfo culture)"

.PP
Converts validation severity values into corresponding images\&. 
.PP
\fBParameters\fP
.RS 4
\fIvalue\fP Original value\&.
.br
\fItargetType\fP Desired output type (ignored)\&.
.br
\fIparameter\fP Extra parameter (ignored)\&.
.br
\fIculture\fP Desired culture (ignored)\&.
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
Definition at line 33 of file BrokenRulesSeverityConverter\&.cs\&.
.SS "object Csla\&.Xaml\&.BrokenRuleSeverityConverter\&.ConvertBack (object value, Type targetType, object parameter, System\&.Globalization\&.CultureInfo culture)"

.PP
Returns the original value\&. 
.PP
\fBParameters\fP
.RS 4
\fIvalue\fP Original value\&.
.br
\fItargetType\fP Desired output type (ignored)\&.
.br
\fIparameter\fP Extra parameter (ignored)\&.
.br
\fIculture\fP Desired culture (ignored)\&.
.RE
.PP

.PP
Definition at line 53 of file BrokenRulesSeverityConverter\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
