.TH "cslalighttest.ReadOnly.ReadOnlyTests" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cslalighttest.ReadOnly.ReadOnlyTests
.SH SYNOPSIS
.br
.PP
.PP
Inherits TestBase\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBAddItemToReadOnlyFail\fP ()"
.br
.ti -1c
.RI "void \fBInsertItemToReadOnlyFail\fP ()"
.br
.ti -1c
.RI "void \fBIndexInsertItemToReadOnlyFail\fP ()"
.br
.ti -1c
.RI "void \fBAddNewToReadOnlyFail\fP ()"
.br
.ti -1c
.RI "void \fBClearReadOnlyFail\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 39 of file ReadOnlyTests\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void cslalighttest\&.ReadOnly\&.ReadOnlyTests\&.AddItemToReadOnlyFail ()"

.PP
Definition at line 43 of file ReadOnlyTests\&.cs\&.
.SS "void cslalighttest\&.ReadOnly\&.ReadOnlyTests\&.AddNewToReadOnlyFail ()"

.PP
Definition at line 75 of file ReadOnlyTests\&.cs\&.
.SS "void cslalighttest\&.ReadOnly\&.ReadOnlyTests\&.ClearReadOnlyFail ()"

.PP
Definition at line 85 of file ReadOnlyTests\&.cs\&.
.SS "void cslalighttest\&.ReadOnly\&.ReadOnlyTests\&.IndexInsertItemToReadOnlyFail ()"

.PP
Definition at line 65 of file ReadOnlyTests\&.cs\&.
.SS "void cslalighttest\&.ReadOnly\&.ReadOnlyTests\&.InsertItemToReadOnlyFail ()"

.PP
Definition at line 54 of file ReadOnlyTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
