.TH "Csla.Configuration.CslaDataConfiguration" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Configuration.CslaDataConfiguration \- Use this type to configure the settings for the CSLA \&.NET data portal\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCslaDataConfiguration\fP \fBDefaultTransactionIsolationLevel\fP (\fBTransactionIsolationLevel\fP level)"
.br
.RI "Sets the default transaction isolation level\&. "
.ti -1c
.RI "\fBCslaDataConfiguration\fP \fBDefaultTransactionTimeoutInSeconds\fP (int seconds)"
.br
.RI "Sets the default transaction timeout in seconds\&. "
.ti -1c
.RI "\fBCslaDataConfiguration\fP \fBDefaultTransactionAsyncFlowOption\fP (System\&.Transactions\&.TransactionScopeAsyncFlowOption asyncFlowOption)"
.br
.RI "Sets the default transaction async flow option used to create new TransactionScope objects\&. "
.in -1c
.SH "Detailed Description"
.PP 
Use this type to configure the settings for the CSLA \&.NET data portal\&. 


.PP
Definition at line 28 of file CslaDataConfiguration\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBCslaDataConfiguration\fP Csla\&.Configuration\&.CslaDataConfiguration\&.DefaultTransactionAsyncFlowOption (System\&.Transactions\&.TransactionScopeAsyncFlowOption asyncFlowOption)"

.PP
Sets the default transaction async flow option used to create new TransactionScope objects\&. 
.PP
\fBParameters\fP
.RS 4
\fIasyncFlowOption\fP Async flow option
.RE
.PP

.PP
Definition at line 55 of file CslaDataConfiguration\&.cs\&.
.SS "\fBCslaDataConfiguration\fP Csla\&.Configuration\&.CslaDataConfiguration\&.DefaultTransactionIsolationLevel (\fBTransactionIsolationLevel\fP level)"

.PP
Sets the default transaction isolation level\&. 
.PP
\fBParameters\fP
.RS 4
\fIlevel\fP The default transaction isolation level
.RE
.PP

.PP
Definition at line 34 of file CslaDataConfiguration\&.cs\&.
.SS "\fBCslaDataConfiguration\fP Csla\&.Configuration\&.CslaDataConfiguration\&.DefaultTransactionTimeoutInSeconds (int seconds)"

.PP
Sets the default transaction timeout in seconds\&. 
.PP
\fBParameters\fP
.RS 4
\fIseconds\fP The default transaction timeout in seconds
.RE
.PP

.PP
Definition at line 44 of file CslaDataConfiguration\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
