.TH "Csla.Test.DataPortal.InterceptorCommand" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.DataPortal.InterceptorCommand
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.CommandBase< InterceptorCommand >\fP\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBDataPortal_Execute\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 213 of file InterceptorTests\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Csla\&.Test\&.DataPortal\&.InterceptorCommand\&.DataPortal_Execute ()\fC [protected]\fP"

.PP
Definition at line 216 of file InterceptorTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
