.TH "Csla.Test.LazyLoad.LazyLoadTests" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.LazyLoad.LazyLoadTests
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBNullApplyEdit\fP ()"
.br
.ti -1c
.RI "void \fBNullCancelEdit\fP ()"
.br
.ti -1c
.RI "void \fBNewChildEditLevel\fP ()"
.br
.ti -1c
.RI "void \fBNewChildEditLevelCancel\fP ()"
.br
.ti -1c
.RI "void \fBNewChildEditLevelApply\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 26 of file LazyLoadTests\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Csla\&.Test\&.LazyLoad\&.LazyLoadTests\&.NewChildEditLevel ()"

.PP
Definition at line 67 of file LazyLoadTests\&.cs\&.
.SS "void Csla\&.Test\&.LazyLoad\&.LazyLoadTests\&.NewChildEditLevelApply ()"

.PP
Definition at line 108 of file LazyLoadTests\&.cs\&.
.SS "void Csla\&.Test\&.LazyLoad\&.LazyLoadTests\&.NewChildEditLevelCancel ()"

.PP
Definition at line 88 of file LazyLoadTests\&.cs\&.
.SS "void Csla\&.Test\&.LazyLoad\&.LazyLoadTests\&.NullApplyEdit ()"

.PP
Definition at line 29 of file LazyLoadTests\&.cs\&.
.SS "void Csla\&.Test\&.LazyLoad\&.LazyLoadTests\&.NullCancelEdit ()"

.PP
Definition at line 44 of file LazyLoadTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
