.TH "Csla.Testing.Business.CommandBase.TestCommandBase" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Testing.Business.CommandBase.TestCommandBase
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.CommandBase< TestCommandBase >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTestCommandBase\fP (string parameter)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "const string \fBExecutionSignal\fP = 'Executed command with parameter: '"
.br
.ti -1c
.RI "static readonly \fBPropertyInfo\fP< string > \fBParameterProperty\fP"
.br
.ti -1c
.RI "static readonly \fBPropertyInfo\fP< string > \fBExecutionResultProperty\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBTestCommandBase\fP ()"
.br
.ti -1c
.RI "void \fBDataPortal_Execute\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBParameter\fP\fC [get, protected set]\fP"
.br
.ti -1c
.RI "string \fBExecutionResult\fP\fC [get, protected set]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 15 of file TestCommandBase\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Csla\&.Testing\&.Business\&.CommandBase\&.TestCommandBase\&.TestCommandBase (string parameter)"

.PP
Definition at line 39 of file TestCommandBase\&.cs\&.
.SS "Csla\&.Testing\&.Business\&.CommandBase\&.TestCommandBase\&.TestCommandBase ()\fC [protected]\fP"

.PP
Definition at line 44 of file TestCommandBase\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Csla\&.Testing\&.Business\&.CommandBase\&.TestCommandBase\&.DataPortal_Execute ()\fC [protected]\fP"

.PP
Definition at line 48 of file TestCommandBase\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "readonly \fBPropertyInfo\fP<string> Csla\&.Testing\&.Business\&.CommandBase\&.TestCommandBase\&.ExecutionResultProperty\fC [static]\fP"
\fBInitial value:\fP
.PP
.nf
= RegisterProperty(
      typeof(TestCommandBase),
      new PropertyInfo<string>("ExecutionResult"))
.fi
.PP
Definition at line 23 of file TestCommandBase\&.cs\&.
.SS "const string Csla\&.Testing\&.Business\&.CommandBase\&.TestCommandBase\&.ExecutionSignal = 'Executed command with parameter: '\fC [static]\fP"

.PP
Definition at line 17 of file TestCommandBase\&.cs\&.
.SS "readonly \fBPropertyInfo\fP<string> Csla\&.Testing\&.Business\&.CommandBase\&.TestCommandBase\&.ParameterProperty\fC [static]\fP"
\fBInitial value:\fP
.PP
.nf
= RegisterProperty(
      typeof(TestCommandBase),
      new PropertyInfo<string>("Parameter"))
.fi
.PP
Definition at line 19 of file TestCommandBase\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "string Csla\&.Testing\&.Business\&.CommandBase\&.TestCommandBase\&.ExecutionResult\fC [get]\fP, \fC [protected set]\fP"

.PP
Definition at line 33 of file TestCommandBase\&.cs\&.
.SS "string Csla\&.Testing\&.Business\&.CommandBase\&.TestCommandBase\&.Parameter\fC [get]\fP, \fC [protected set]\fP"

.PP
Definition at line 27 of file TestCommandBase\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
