.TH "Csla.Serialization.Mobile.CslaBinaryReader" 3 "Thu Jul 22 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Serialization.Mobile.CslaBinaryReader \- This is a class that is responsible for deserializing \fBSerializationInfo\fP objects for receiving the data from client / server\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.Serialization\&.Mobile\&.ICslaReader\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCslaBinaryReader\fP ()"
.br
.RI "Creates new instance of \fBCslaBinaryReader\fP "
.ti -1c
.RI "List< \fBSerializationInfo\fP > \fBRead\fP (Stream serializationStream)"
.br
.RI "Read a data from a stream, typically MemoryStream, and convert it into a list of \fBSerializationInfo\fP objects "
.in -1c
.SH "Detailed Description"
.PP 
This is a class that is responsible for deserializing \fBSerializationInfo\fP objects for receiving the data from client / server\&. 


.PP
Definition at line 12 of file CslaBinaryReader\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Csla\&.Serialization\&.Mobile\&.CslaBinaryReader\&.CslaBinaryReader ()"

.PP
Creates new instance of \fBCslaBinaryReader\fP 
.PP
Definition at line 19 of file CslaBinaryReader\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "List<\fBSerializationInfo\fP> Csla\&.Serialization\&.Mobile\&.CslaBinaryReader\&.Read (Stream serializationStream)"

.PP
Read a data from a stream, typically MemoryStream, and convert it into a list of \fBSerializationInfo\fP objects 
.PP
\fBParameters\fP
.RS 4
\fIserializationStream\fP Stream to read the data from
.RE
.PP
\fBReturns\fP
.RS 4
List of \fBSerializationInfo\fP objects
.RE
.PP

.PP
Implements \fBCsla\&.Serialization\&.Mobile\&.ICslaReader\fP\&.
.PP
Definition at line 30 of file CslaBinaryReader\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
