.TH "Csla.Test.ChildrenByInterface.ChildInterfaceTests" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.ChildrenByInterface.ChildInterfaceTests
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBAddItems\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 26 of file ChildInterfaceTests\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Csla\&.Test\&.ChildrenByInterface\&.ChildInterfaceTests\&.AddItems ()"

.PP
Definition at line 29 of file ChildInterfaceTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
