.TH "Csla.Test.DataPortal.Issue2287Edit" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.DataPortal.Issue2287Edit
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.Test\&.DataPortal\&.Issue2287EditBase< Issue2287Edit >\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 629 of file ServiceProviderMethodCallerTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
