.TH "Csla.DataPortalChildOperationAttribute" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.DataPortalChildOperationAttribute \- Base type for data portal child operation attributes\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.DataPortalOperationAttribute\fP\&.
.PP
Inherited by \fBCsla\&.CreateChildAttribute\fP, \fBCsla\&.DeleteSelfChildAttribute\fP, \fBCsla\&.ExecuteChildAttribute\fP, \fBCsla\&.FetchChildAttribute\fP, \fBCsla\&.InsertChildAttribute\fP, and \fBCsla\&.UpdateChildAttribute\fP\&.
.SH "Detailed Description"
.PP 
Base type for data portal child operation attributes\&. 


.PP
Definition at line 41 of file DataPortalOperationAttributes\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
