.TH "Csla.Web.Design.CslaDataSourceConfiguration" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Web.Design.CslaDataSourceConfiguration \- \fBCslaDataSource\fP configuration form\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Form\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCslaDataSourceConfiguration\fP ()"
.br
.RI "Create instance of object\&. "
.ti -1c
.RI "\fBCslaDataSourceConfiguration\fP (DataSourceControl control, string oldTypeName)"
.br
.RI "Create instance of object\&. "
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBDispose\fP (bool disposing)"
.br
.RI "Clean up any resources being used\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBTypeName\fP\fC [get]\fP"
.br
.RI "Gets the type name entered by the user\&. "
.in -1c
.SH "Detailed Description"
.PP 
\fBCslaDataSource\fP configuration form\&. 


.PP
Definition at line 19 of file CslaDataSourceConfiguration\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Csla\&.Web\&.Design\&.CslaDataSourceConfiguration\&.CslaDataSourceConfiguration ()"

.PP
Create instance of object\&. 
.PP
Definition at line 26 of file CslaDataSourceConfiguration\&.cs\&.
.SS "Csla\&.Web\&.Design\&.CslaDataSourceConfiguration\&.CslaDataSourceConfiguration (DataSourceControl control, string oldTypeName)"

.PP
Create instance of object\&. 
.PP
\fBParameters\fP
.RS 4
\fIcontrol\fP Reference to the data source control\&.
.br
\fIoldTypeName\fP Existing type name\&.
.RE
.PP

.PP
Definition at line 36 of file CslaDataSourceConfiguration\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override void Csla\&.Web\&.Design\&.CslaDataSourceConfiguration\&.Dispose (bool disposing)\fC [protected]\fP"

.PP
Clean up any resources being used\&. 
.PP
\fBParameters\fP
.RS 4
\fIdisposing\fP true if managed resources should be disposed; otherwise, false\&.
.RE
.PP

.PP
Definition at line 14 of file CslaDataSourceConfiguration\&.designer\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "string Csla\&.Web\&.Design\&.CslaDataSourceConfiguration\&.TypeName\fC [get]\fP"

.PP
Gets the type name entered by the user\&. 
.PP
Definition at line 47 of file CslaDataSourceConfiguration\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
