.TH "Csla.Rules.AuthorizationRule" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Rules.AuthorizationRule \- Base class providing basic authorization rule implementation\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.Rules\&.IAuthorizationRule\fP\&.
.PP
Inherited by \fBCsla\&.Rules\&.CommonRules\&.IsInRole\fP, \fBCsla\&.Rules\&.CommonRules\&.IsNotInRole\fP, and \fBCsla\&.Test\&.Authorization\&.AuthRuleExpectsCriteria\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAuthorizationRule\fP (\fBAuthorizationActions\fP action)"
.br
.RI "Creates an instance of the rule\&. "
.ti -1c
.RI "\fBAuthorizationRule\fP (\fBAuthorizationActions\fP action, \fBCsla\&.Core\&.IMemberInfo\fP element)"
.br
.RI "Creates an instance of the rule\&. "
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "abstract void \fBExecute\fP (\fBIAuthorizationContext\fP context)"
.br
.RI "Authorization rule implementation\&. "
.ti -1c
.RI "object \fBReadProperty\fP (object obj, \fBCsla\&.Core\&.IPropertyInfo\fP propertyInfo)"
.br
.RI "Reads a property's field value\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "bool \fBCacheResult\fP\fC [get, protected set]\fP"
.br
.RI "Gets a value indicating whether the results of this rule can be cached at the business object level\&. "
.ti -1c
.RI "\fBCsla\&.Core\&.IMemberInfo\fP \fBElement\fP\fC [get, set]\fP"
.br
.RI "Gets the name of the element (property/method) to which this rule is associated\&. "
.ti -1c
.RI "\fBAuthorizationActions\fP \fBAction\fP\fC [get, set]\fP"
.br
.RI "Gets the authorization action this rule will enforce\&. "
.in -1c
.SH "Detailed Description"
.PP 
Base class providing basic authorization rule implementation\&. 


.PP
Definition at line 20 of file AuthorizationRule\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Csla\&.Rules\&.AuthorizationRule\&.AuthorizationRule (\fBAuthorizationActions\fP action)"

.PP
Creates an instance of the rule\&. 
.PP
\fBParameters\fP
.RS 4
\fIaction\fP Action this rule will enforce\&.
.RE
.PP

.PP
Definition at line 31 of file AuthorizationRule\&.cs\&.
.SS "Csla\&.Rules\&.AuthorizationRule\&.AuthorizationRule (\fBAuthorizationActions\fP action, \fBCsla\&.Core\&.IMemberInfo\fP element)"

.PP
Creates an instance of the rule\&. 
.PP
\fBParameters\fP
.RS 4
\fIaction\fP Action this rule will enforce\&.
.br
\fIelement\fP Method or property\&.
.RE
.PP

.PP
Definition at line 40 of file AuthorizationRule\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "abstract void Csla\&.Rules\&.AuthorizationRule\&.Execute (\fBIAuthorizationContext\fP context)\fC [protected]\fP, \fC [pure virtual]\fP"

.PP
Authorization rule implementation\&. 
.PP
\fBParameters\fP
.RS 4
\fIcontext\fP Rule context object\&.
.RE
.PP

.PP
Implements \fBCsla\&.Rules\&.IAuthorizationRule\fP\&.
.PP
Implemented in \fBCsla\&.Rules\&.CommonRules\&.IsNotInRole\fP, \fBCsla\&.Rules\&.CommonRules\&.IsInRole\fP, and \fBCsla\&.Test\&.Authorization\&.AuthRuleExpectsCriteria\fP\&.
.SS "object Csla\&.Rules\&.AuthorizationRule\&.ReadProperty (object obj, \fBCsla\&.Core\&.IPropertyInfo\fP propertyInfo)\fC [protected]\fP"

.PP
Reads a property's field value\&. 
.PP
\fBParameters\fP
.RS 4
\fIobj\fP Object on which to call the method\&. 
.br
\fIpropertyInfo\fP \fBPropertyInfo\fP object containing property metadata\&.
.RE
.PP
.PP
No authorization checks occur when this method is called\&. 
.PP
Definition at line 138 of file AuthorizationRule\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "\fBAuthorizationActions\fP Csla\&.Rules\&.AuthorizationRule\&.Action\fC [get]\fP, \fC [set]\fP"

.PP
Gets the authorization action this rule will enforce\&. 
.PP
Definition at line 85 of file AuthorizationRule\&.cs\&.
.SS "bool Csla\&.Rules\&.AuthorizationRule\&.CacheResult\fC [get]\fP, \fC [protected set]\fP"

.PP
Gets a value indicating whether the results of this rule can be cached at the business object level\&. 
.PP
\fBReturns\fP
.RS 4
bool, true by default to allow cache result\&.
.RE
.PP

.PP
Definition at line 58 of file AuthorizationRule\&.cs\&.
.SS "\fBCsla\&.Core\&.IMemberInfo\fP Csla\&.Rules\&.AuthorizationRule\&.Element\fC [get]\fP, \fC [set]\fP, \fC [protected]\fP"

.PP
Gets the name of the element (property/method) to which this rule is associated\&. 
.PP
Definition at line 72 of file AuthorizationRule\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
