.TH "Csla.Web.Mvc.Test.ModelBinderTest.CslaModelBinderTest" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Web.Mvc.Test.ModelBinderTest.CslaModelBinderTest
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBCanBind_To_SingleRoot\fP ()"
.br
.ti -1c
.RI "void \fBCanBind_WithPrefix_To_SingleRoot\fP ()"
.br
.ti -1c
.RI "void \fBBind_InvalidValues_ModelState_Returns_Errors\fP ()"
.br
.ti -1c
.RI "void \fBBind_InvalidValues_WithPrefix_ModelState_Returns_Errors\fP ()"
.br
.ti -1c
.RI "void \fBCanBind_To_RootList\fP ()"
.br
.ti -1c
.RI "void \fBCanBind_WithPrefix_To_RootList\fP ()"
.br
.ti -1c
.RI "void \fBBind_RootList_WithInvalidValues_ModelState_ReturnsErrors\fP ()"
.br
.ti -1c
.RI "void \fBCanBind_To_RootWithChildren\fP ()"
.br
.ti -1c
.RI "void \fBCanBind_WithPrefix_To_RootWithChildren\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBInitialize\fP (TestContext testContext)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 20 of file CslaModelBinderTest\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Csla\&.Web\&.Mvc\&.Test\&.ModelBinderTest\&.CslaModelBinderTest\&.Bind_InvalidValues_ModelState_Returns_Errors ()"

.PP
Definition at line 70 of file CslaModelBinderTest\&.cs\&.
.SS "void Csla\&.Web\&.Mvc\&.Test\&.ModelBinderTest\&.CslaModelBinderTest\&.Bind_InvalidValues_WithPrefix_ModelState_Returns_Errors ()"

.PP
Definition at line 97 of file CslaModelBinderTest\&.cs\&.
.SS "void Csla\&.Web\&.Mvc\&.Test\&.ModelBinderTest\&.CslaModelBinderTest\&.Bind_RootList_WithInvalidValues_ModelState_ReturnsErrors ()"

.PP
Definition at line 180 of file CslaModelBinderTest\&.cs\&.
.SS "void Csla\&.Web\&.Mvc\&.Test\&.ModelBinderTest\&.CslaModelBinderTest\&.CanBind_To_RootList ()"

.PP
Definition at line 125 of file CslaModelBinderTest\&.cs\&.
.SS "void Csla\&.Web\&.Mvc\&.Test\&.ModelBinderTest\&.CslaModelBinderTest\&.CanBind_To_RootWithChildren ()"

.PP
Definition at line 202 of file CslaModelBinderTest\&.cs\&.
.SS "void Csla\&.Web\&.Mvc\&.Test\&.ModelBinderTest\&.CslaModelBinderTest\&.CanBind_To_SingleRoot ()"

.PP
Definition at line 29 of file CslaModelBinderTest\&.cs\&.
.SS "void Csla\&.Web\&.Mvc\&.Test\&.ModelBinderTest\&.CslaModelBinderTest\&.CanBind_WithPrefix_To_RootList ()"

.PP
Definition at line 154 of file CslaModelBinderTest\&.cs\&.
.SS "void Csla\&.Web\&.Mvc\&.Test\&.ModelBinderTest\&.CslaModelBinderTest\&.CanBind_WithPrefix_To_RootWithChildren ()"

.PP
Definition at line 230 of file CslaModelBinderTest\&.cs\&.
.SS "void Csla\&.Web\&.Mvc\&.Test\&.ModelBinderTest\&.CslaModelBinderTest\&.CanBind_WithPrefix_To_SingleRoot ()"

.PP
Definition at line 50 of file CslaModelBinderTest\&.cs\&.
.SS "static void Csla\&.Web\&.Mvc\&.Test\&.ModelBinderTest\&.CslaModelBinderTest\&.Initialize (TestContext testContext)\fC [static]\fP"

.PP
Definition at line 23 of file CslaModelBinderTest\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
