.TH "Csla.DataPortalOperationAttribute" 3 "Thu Jul 22 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.DataPortalOperationAttribute \- Base type for data portal operation attributes\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Attribute\&.
.PP
Inherited by \fBCsla\&.DataPortalChildOperationAttribute\fP, and \fBCsla\&.DataPortalRootOperationAttribute\fP\&.
.SH "Detailed Description"
.PP 
Base type for data portal operation attributes\&. 


.PP
Definition at line 25 of file DataPortalOperationAttributes\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
