.TH "Csla.Analyzers.Tests.IsBusinessObjectSerializableAnalyzerTests" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Analyzers.Tests.IsBusinessObjectSerializableAnalyzerTests
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBVerifySupportedDiagnostics\fP ()"
.br
.ti -1c
.RI "async Task \fBAnalyzeWhenClassIsNotMobileObject\fP ()"
.br
.ti -1c
.RI "async Task \fBAnalyzeWhenClassIsMobileObjectAndIsSerializable\fP ()"
.br
.ti -1c
.RI "async Task \fBAnalyzeWhenClassIsMobileObjectAndIsNotSerializable\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 9 of file IsBusinessObjectSerializableAnalyzerTests\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "async Task Csla\&.Analyzers\&.Tests\&.IsBusinessObjectSerializableAnalyzerTests\&.AnalyzeWhenClassIsMobileObjectAndIsNotSerializable ()"

.PP
Definition at line 56 of file IsBusinessObjectSerializableAnalyzerTests\&.cs\&.
.SS "async Task Csla\&.Analyzers\&.Tests\&.IsBusinessObjectSerializableAnalyzerTests\&.AnalyzeWhenClassIsMobileObjectAndIsSerializable ()"

.PP
Definition at line 43 of file IsBusinessObjectSerializableAnalyzerTests\&.cs\&.
.SS "async Task Csla\&.Analyzers\&.Tests\&.IsBusinessObjectSerializableAnalyzerTests\&.AnalyzeWhenClassIsNotMobileObject ()"

.PP
Definition at line 35 of file IsBusinessObjectSerializableAnalyzerTests\&.cs\&.
.SS "void Csla\&.Analyzers\&.Tests\&.IsBusinessObjectSerializableAnalyzerTests\&.VerifySupportedDiagnostics ()"

.PP
Definition at line 12 of file IsBusinessObjectSerializableAnalyzerTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
