.TH "Csla.Rules.BrokenRulesCollection" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Rules.BrokenRulesCollection \- A collection of currently broken rules\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.Core\&.ReadOnlyObservableBindingList< BrokenRule >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBrokenRulesCollection\fP ()"
.br
.RI "Creates a read-write instance of the collection\&. "
.ti -1c
.RI "\fBBrokenRule\fP \fBGetFirstBrokenRule\fP (\fBCsla\&.Core\&.IPropertyInfo\fP property)"
.br
.RI "Returns the first \fBBrokenRule\fP object corresponding to the specified property\&. "
.ti -1c
.RI "\fBBrokenRule\fP \fBGetFirstBrokenRule\fP (string property)"
.br
.RI "Returns the first \fBBrokenRule\fP object corresponding to the specified property\&. "
.ti -1c
.RI "\fBBrokenRule\fP \fBGetFirstMessage\fP (\fBCsla\&.Core\&.IPropertyInfo\fP property)"
.br
.RI "Returns the first \fBBrokenRule\fP object corresponding to the specified property\&. "
.ti -1c
.RI "\fBBrokenRule\fP \fBGetFirstMessage\fP (\fBCsla\&.Core\&.IPropertyInfo\fP property, \fBRuleSeverity\fP severity)"
.br
.RI "Returns the first \fBBrokenRule\fP object corresponding to the specified property and severity\&. "
.ti -1c
.RI "\fBBrokenRule\fP \fBGetFirstMessage\fP (string property, \fBRuleSeverity\fP severity)"
.br
.RI "Returns the first \fBBrokenRule\fP object corresponding to the specified property and severity\&. "
.ti -1c
.RI "override string \fBToString\fP ()"
.br
.RI "Returns the text of all broken rule descriptions, each separated by a Environment\&.NewLine\&. "
.ti -1c
.RI "string \fBToString\fP (\fBRuleSeverity\fP severity)"
.br
.RI "Returns the text of all broken rule descriptions for a specific severity, each separated by a Environment\&.NewLine\&. "
.ti -1c
.RI "string \fBToString\fP (string separator)"
.br
.RI "Returns the text of all broken rule descriptions\&. "
.ti -1c
.RI "string \fBToString\fP (string separator, \fBRuleSeverity\fP severity)"
.br
.RI "Returns the text of all broken rule descriptions for a specific severity\&. "
.ti -1c
.RI "string \fBToString\fP (string separator, \fBRuleSeverity\fP severity, string propertyName)"
.br
.RI "Returns the text of all broken rule descriptions for a specific severity and property\&. "
.ti -1c
.RI "string[] \fBToArray\fP ()"
.br
.RI "Returns a string array containing all broken rule descriptions\&. "
.ti -1c
.RI "string[] \fBToArray\fP (\fBRuleSeverity\fP severity)"
.br
.RI "Returns a string array containing all broken rule descriptions\&. "
.ti -1c
.RI "void \fBAddRange\fP (List< \fBBrokenRule\fP > list)"
.br
.RI "Merges a list of items into the collection\&. "
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnGetState\fP (\fBSerializationInfo\fP info)"
.br
.RI "Override this method to insert your field values into the MobileFormatter serialzation stream\&. "
.ti -1c
.RI "override void \fBOnSetState\fP (\fBSerializationInfo\fP info)"
.br
.RI "Override this method to retrieve your field values from the MobileFormatter serialzation stream\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBErrorCount\fP\fC [get]\fP"
.br
.RI "Gets the number of broken rules in the collection that have a severity of Error\&. "
.ti -1c
.RI "int \fBWarningCount\fP\fC [get]\fP"
.br
.RI "Gets the number of broken rules in the collection that have a severity of Warning\&. "
.ti -1c
.RI "int \fBInformationCount\fP\fC [get]\fP"
.br
.RI "Gets the number of broken rules in the collection that have a severity of Information\&. "
.in -1c
.SH "Detailed Description"
.PP 
A collection of currently broken rules\&. 

This collection is readonly and can be safely made available to code outside the business object such as the UI\&. This allows external code, such as a UI, to display the list of broken rules to the user\&. 
.PP
Definition at line 26 of file BrokenRulesCollection\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Csla\&.Rules\&.BrokenRulesCollection\&.BrokenRulesCollection ()"

.PP
Creates a read-write instance of the collection\&. 
.PP
Definition at line 39 of file BrokenRulesCollection\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Csla\&.Rules\&.BrokenRulesCollection\&.AddRange (List< \fBBrokenRule\fP > list)"

.PP
Merges a list of items into the collection\&. 
.PP
\fBParameters\fP
.RS 4
\fIlist\fP List of items to add\&.
.RE
.PP

.PP
Definition at line 434 of file BrokenRulesCollection\&.cs\&.
.SS "\fBBrokenRule\fP Csla\&.Rules\&.BrokenRulesCollection\&.GetFirstBrokenRule (\fBCsla\&.Core\&.IPropertyInfo\fP property)"

.PP
Returns the first \fBBrokenRule\fP object corresponding to the specified property\&. Code in a business object or UI can also use this value to retrieve the first broken rule in \fBBrokenRulesCollection\fP that corresponds to a specfic property on the object\&. 
.PP
\fBParameters\fP
.RS 4
\fIproperty\fP The property affected by the rule\&.
.RE
.PP
\fBReturns\fP
.RS 4
The first \fBBrokenRule\fP object corresponding to the specified property, or null if there are no rules defined for the property\&. 
.RE
.PP

.PP
Definition at line 226 of file BrokenRulesCollection\&.cs\&.
.SS "\fBBrokenRule\fP Csla\&.Rules\&.BrokenRulesCollection\&.GetFirstBrokenRule (string property)"

.PP
Returns the first \fBBrokenRule\fP object corresponding to the specified property\&. Code in a business object or UI can also use this value to retrieve the first broken rule in \fBBrokenRulesCollection\fP that corresponds to a specfic property on the object\&. 
.PP
\fBParameters\fP
.RS 4
\fIproperty\fP The name of the property affected by the rule\&.
.RE
.PP
\fBReturns\fP
.RS 4
The first \fBBrokenRule\fP object corresponding to the specified property, or null if there are no rules defined for the property\&. 
.RE
.PP

.PP
Definition at line 245 of file BrokenRulesCollection\&.cs\&.
.SS "\fBBrokenRule\fP Csla\&.Rules\&.BrokenRulesCollection\&.GetFirstMessage (\fBCsla\&.Core\&.IPropertyInfo\fP property)"

.PP
Returns the first \fBBrokenRule\fP object corresponding to the specified property\&. Code in a business object or UI can also use this value to retrieve the first broken rule in \fBBrokenRulesCollection\fP that corresponds to a specfic property\&. 
.PP
\fBParameters\fP
.RS 4
\fIproperty\fP The name of the property affected by the rule\&.
.RE
.PP
\fBReturns\fP
.RS 4
The first \fBBrokenRule\fP object corresponding to the specified property, or Nothing (null in C#) if there are no rules defined for the property\&. 
.RE
.PP

.PP
Definition at line 264 of file BrokenRulesCollection\&.cs\&.
.SS "\fBBrokenRule\fP Csla\&.Rules\&.BrokenRulesCollection\&.GetFirstMessage (\fBCsla\&.Core\&.IPropertyInfo\fP property, \fBRuleSeverity\fP severity)"

.PP
Returns the first \fBBrokenRule\fP object corresponding to the specified property and severity\&. 
.PP
\fBParameters\fP
.RS 4
\fIproperty\fP The property affected by the rule\&.
.br
\fIseverity\fP The severity of broken rule to return\&.
.RE
.PP
\fBReturns\fP
.RS 4
The first \fBBrokenRule\fP object corresponding to the specified property, or Nothing (null in C#) if there are no rules defined for the property\&. 
.RE
.PP

.PP
Definition at line 280 of file BrokenRulesCollection\&.cs\&.
.SS "\fBBrokenRule\fP Csla\&.Rules\&.BrokenRulesCollection\&.GetFirstMessage (string property, \fBRuleSeverity\fP severity)"

.PP
Returns the first \fBBrokenRule\fP object corresponding to the specified property and severity\&. 
.PP
\fBParameters\fP
.RS 4
\fIproperty\fP The name of the property affected by the rule\&.
.br
\fIseverity\fP The severity of broken rule to return\&.
.RE
.PP
\fBReturns\fP
.RS 4
The first \fBBrokenRule\fP object corresponding to the specified property, or Nothing (null in C#) if there are no rules defined for the property\&. 
.RE
.PP

.PP
Definition at line 296 of file BrokenRulesCollection\&.cs\&.
.SS "override void Csla\&.Rules\&.BrokenRulesCollection\&.OnGetState (\fBSerializationInfo\fP info)\fC [protected]\fP"

.PP
Override this method to insert your field values into the MobileFormatter serialzation stream\&. 
.PP
\fBParameters\fP
.RS 4
\fIinfo\fP Object containing the data to serialize\&. 
.RE
.PP

.PP
Definition at line 447 of file BrokenRulesCollection\&.cs\&.
.SS "override void Csla\&.Rules\&.BrokenRulesCollection\&.OnSetState (\fBSerializationInfo\fP info)\fC [protected]\fP"

.PP
Override this method to retrieve your field values from the MobileFormatter serialzation stream\&. 
.PP
\fBParameters\fP
.RS 4
\fIinfo\fP Object containing the data to serialize\&. 
.RE
.PP

.PP
Definition at line 462 of file BrokenRulesCollection\&.cs\&.
.SS "string [] Csla\&.Rules\&.BrokenRulesCollection\&.ToArray ()"

.PP
Returns a string array containing all broken rule descriptions\&. 
.PP
\fBReturns\fP
.RS 4
The text of all broken rule descriptions matching the specified severtiy\&.
.RE
.PP

.PP
Definition at line 412 of file BrokenRulesCollection\&.cs\&.
.SS "string [] Csla\&.Rules\&.BrokenRulesCollection\&.ToArray (\fBRuleSeverity\fP severity)"

.PP
Returns a string array containing all broken rule descriptions\&. 
.PP
\fBParameters\fP
.RS 4
\fIseverity\fP The severity of rules to include in the result\&.
.RE
.PP
\fBReturns\fP
.RS 4
The text of all broken rule descriptions matching the specified severtiy\&.
.RE
.PP

.PP
Definition at line 425 of file BrokenRulesCollection\&.cs\&.
.SS "override string Csla\&.Rules\&.BrokenRulesCollection\&.ToString ()"

.PP
Returns the text of all broken rule descriptions, each separated by a Environment\&.NewLine\&. 
.PP
\fBReturns\fP
.RS 4
The text of all broken rule descriptions\&.
.RE
.PP

.PP
Definition at line 306 of file BrokenRulesCollection\&.cs\&.
.SS "string Csla\&.Rules\&.BrokenRulesCollection\&.ToString (\fBRuleSeverity\fP severity)"

.PP
Returns the text of all broken rule descriptions for a specific severity, each separated by a Environment\&.NewLine\&. 
.PP
\fBParameters\fP
.RS 4
\fIseverity\fP The severity of rules to include in the result\&.
.RE
.PP
\fBReturns\fP
.RS 4
The text of all broken rule descriptions matching the specified severtiy\&.
.RE
.PP

.PP
Definition at line 320 of file BrokenRulesCollection\&.cs\&.
.SS "string Csla\&.Rules\&.BrokenRulesCollection\&.ToString (string separator)"

.PP
Returns the text of all broken rule descriptions\&. 
.PP
\fBParameters\fP
.RS 4
\fIseparator\fP String to place between each broken rule description\&. 
.RE
.PP
\fBReturns\fP
.RS 4
The text of all broken rule descriptions\&.
.RE
.PP

.PP
Definition at line 332 of file BrokenRulesCollection\&.cs\&.
.SS "string Csla\&.Rules\&.BrokenRulesCollection\&.ToString (string separator, \fBRuleSeverity\fP severity)"

.PP
Returns the text of all broken rule descriptions for a specific severity\&. 
.PP
\fBParameters\fP
.RS 4
\fIseparator\fP String to place between each broken rule description\&. 
.br
\fIseverity\fP The severity of rules to include in the result\&.
.RE
.PP
\fBReturns\fP
.RS 4
The text of all broken rule descriptions matching the specified severtiy\&.
.RE
.PP

.PP
Definition at line 358 of file BrokenRulesCollection\&.cs\&.
.SS "string Csla\&.Rules\&.BrokenRulesCollection\&.ToString (string separator, \fBRuleSeverity\fP severity, string propertyName)"

.PP
Returns the text of all broken rule descriptions for a specific severity and property\&. 
.PP
\fBParameters\fP
.RS 4
\fIseparator\fP String to place between each broken rule description\&. 
.br
\fIseverity\fP The severity of rules to include in the result\&.
.br
\fIpropertyName\fP Property name
.RE
.PP
\fBReturns\fP
.RS 4
The text of all broken rule descriptions matching the specified severtiy\&.
.RE
.PP

.PP
Definition at line 388 of file BrokenRulesCollection\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "int Csla\&.Rules\&.BrokenRulesCollection\&.ErrorCount\fC [get]\fP"

.PP
Gets the number of broken rules in the collection that have a severity of Error\&. An integer value\&.
.PP
Definition at line 185 of file BrokenRulesCollection\&.cs\&.
.SS "int Csla\&.Rules\&.BrokenRulesCollection\&.InformationCount\fC [get]\fP"

.PP
Gets the number of broken rules in the collection that have a severity of Information\&. An integer value\&.
.PP
Definition at line 207 of file BrokenRulesCollection\&.cs\&.
.SS "int Csla\&.Rules\&.BrokenRulesCollection\&.WarningCount\fC [get]\fP"

.PP
Gets the number of broken rules in the collection that have a severity of Warning\&. An integer value\&.
.PP
Definition at line 196 of file BrokenRulesCollection\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
