.TH "Csla.Test.ValidationRules.RootThrowsException" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.ValidationRules.RootThrowsException
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.BusinessBase< RootThrowsException >\fP\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBAddBusinessRules\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "static int \fBCounter\fP\fC [get, set]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 11 of file RootThrowsException\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override void Csla\&.Test\&.ValidationRules\&.RootThrowsException\&.AddBusinessRules ()\fC [protected]\fP"

.PP
Definition at line 20 of file RootThrowsException\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "int Csla\&.Test\&.ValidationRules\&.RootThrowsException\&.Counter\fC [static]\fP, \fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 14 of file RootThrowsException\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
