.TH "Csla.Test.DataPortal.ServiceProviderMethodCallerTests" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.DataPortal.ServiceProviderMethodCallerTests
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBNoTarget\fP ()"
.br
.ti -1c
.RI "void \fBFindMethodInterfaceCriteria\fP ()"
.br
.ti -1c
.RI "void \fBFindMethodNullableCriteria\fP ()"
.br
.ti -1c
.RI "async Task \fBFindMethodNullableCriteriaWithValueViaDataPortal\fP ()"
.br
.ti -1c
.RI "async Task \fBFindMethodNullableCriteriaWithNullViaDataPortal\fP ()"
.br
.ti -1c
.RI "void \fBFindMethodNoCriteriaNoDI\fP ()"
.br
.ti -1c
.RI "void \fBFindMethodCriteriaDI\fP ()"
.br
.ti -1c
.RI "void \fBFindMethodBadCriteriaDI\fP ()"
.br
.ti -1c
.RI "void \fBFindMethodMultipleCriteriaDI\fP ()"
.br
.ti -1c
.RI "void \fBFindMethodMultipleCriteriaDIInterleaved\fP ()"
.br
.ti -1c
.RI "void \fBFindMethodCriteriaMultipleDI\fP ()"
.br
.ti -1c
.RI "void \fBFindMethodCriteriaMultipleAmbiguousDI\fP ()"
.br
.ti -1c
.RI "void \fBFindMethodSingleCriteriaInvalid\fP ()"
.br
.ti -1c
.RI "void \fBFindMethodSingleCriteriaValid\fP ()"
.br
.ti -1c
.RI "void \fBFindMethodObjectCriteriaValid\fP ()"
.br
.ti -1c
.RI "void \fBFindMethodObjectCriteriaSubtype\fP ()"
.br
.ti -1c
.RI "void \fBFindMethodSingleCriteriaBadType\fP ()"
.br
.ti -1c
.RI "void \fBFindMethod_PrivateBase\fP ()"
.br
.ti -1c
.RI "void \fBFindMethod_PrivateBase_Invoke\fP ()"
.br
.ti -1c
.RI "void \fBFindMethodDataPortal_CreateBase\fP ()"
.br
.ti -1c
.RI "void \fBFindMethodDataPortal_CreateCriteria\fP ()"
.br
.ti -1c
.RI "void \fBFindMethodDataPortal_CreateCriteriaBase\fP ()"
.br
.ti -1c
.RI "void \fBFindMethodDataPortal_Create\fP ()"
.br
.ti -1c
.RI "void \fBFindMethodDataPortal_Create_Criteria\fP ()"
.br
.ti -1c
.RI "void \fBFindMethodAmbiguousCriteria\fP ()"
.br
.ti -1c
.RI "void \fBFindChildLegacyUpdate\fP ()"
.br
.ti -1c
.RI "void \fBFindChildParamsUpdate\fP ()"
.br
.ti -1c
.RI "void \fBFindChildIntUpdate\fP ()"
.br
.ti -1c
.RI "void \fBFindOverlappingCriteriaInt\fP ()"
.br
.ti -1c
.RI "void \fBIssue2109\fP ()"
.br
.ti -1c
.RI "void \fBIssue2287BusinessBindingListFetch\fP ()"
.br
.ti -1c
.RI "void \fBIssue2287BusinessBaseFetch\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 27 of file ServiceProviderMethodCallerTests\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Csla\&.Test\&.DataPortal\&.ServiceProviderMethodCallerTests\&.FindChildIntUpdate ()"

.PP
Definition at line 254 of file ServiceProviderMethodCallerTests\&.cs\&.
.SS "void Csla\&.Test\&.DataPortal\&.ServiceProviderMethodCallerTests\&.FindChildLegacyUpdate ()"

.PP
Definition at line 238 of file ServiceProviderMethodCallerTests\&.cs\&.
.SS "void Csla\&.Test\&.DataPortal\&.ServiceProviderMethodCallerTests\&.FindChildParamsUpdate ()"

.PP
Definition at line 246 of file ServiceProviderMethodCallerTests\&.cs\&.
.SS "void Csla\&.Test\&.DataPortal\&.ServiceProviderMethodCallerTests\&.FindMethod_PrivateBase ()"

.PP
Definition at line 171 of file ServiceProviderMethodCallerTests\&.cs\&.
.SS "void Csla\&.Test\&.DataPortal\&.ServiceProviderMethodCallerTests\&.FindMethod_PrivateBase_Invoke ()"

.PP
Definition at line 180 of file ServiceProviderMethodCallerTests\&.cs\&.
.SS "void Csla\&.Test\&.DataPortal\&.ServiceProviderMethodCallerTests\&.FindMethodAmbiguousCriteria ()"

.PP
Definition at line 228 of file ServiceProviderMethodCallerTests\&.cs\&.
.SS "void Csla\&.Test\&.DataPortal\&.ServiceProviderMethodCallerTests\&.FindMethodBadCriteriaDI ()"

.PP
Definition at line 87 of file ServiceProviderMethodCallerTests\&.cs\&.
.SS "void Csla\&.Test\&.DataPortal\&.ServiceProviderMethodCallerTests\&.FindMethodCriteriaDI ()"

.PP
Definition at line 78 of file ServiceProviderMethodCallerTests\&.cs\&.
.SS "void Csla\&.Test\&.DataPortal\&.ServiceProviderMethodCallerTests\&.FindMethodCriteriaMultipleAmbiguousDI ()"

.PP
Definition at line 122 of file ServiceProviderMethodCallerTests\&.cs\&.
.SS "void Csla\&.Test\&.DataPortal\&.ServiceProviderMethodCallerTests\&.FindMethodCriteriaMultipleDI ()"

.PP
Definition at line 111 of file ServiceProviderMethodCallerTests\&.cs\&.
.SS "void Csla\&.Test\&.DataPortal\&.ServiceProviderMethodCallerTests\&.FindMethodDataPortal_Create ()"

.PP
Definition at line 212 of file ServiceProviderMethodCallerTests\&.cs\&.
.SS "void Csla\&.Test\&.DataPortal\&.ServiceProviderMethodCallerTests\&.FindMethodDataPortal_Create_Criteria ()"

.PP
Definition at line 220 of file ServiceProviderMethodCallerTests\&.cs\&.
.SS "void Csla\&.Test\&.DataPortal\&.ServiceProviderMethodCallerTests\&.FindMethodDataPortal_CreateBase ()"

.PP
Definition at line 188 of file ServiceProviderMethodCallerTests\&.cs\&.
.SS "void Csla\&.Test\&.DataPortal\&.ServiceProviderMethodCallerTests\&.FindMethodDataPortal_CreateCriteria ()"

.PP
Definition at line 196 of file ServiceProviderMethodCallerTests\&.cs\&.
.SS "void Csla\&.Test\&.DataPortal\&.ServiceProviderMethodCallerTests\&.FindMethodDataPortal_CreateCriteriaBase ()"

.PP
Definition at line 204 of file ServiceProviderMethodCallerTests\&.cs\&.
.SS "void Csla\&.Test\&.DataPortal\&.ServiceProviderMethodCallerTests\&.FindMethodInterfaceCriteria ()"

.PP
Definition at line 37 of file ServiceProviderMethodCallerTests\&.cs\&.
.SS "void Csla\&.Test\&.DataPortal\&.ServiceProviderMethodCallerTests\&.FindMethodMultipleCriteriaDI ()"

.PP
Definition at line 95 of file ServiceProviderMethodCallerTests\&.cs\&.
.SS "void Csla\&.Test\&.DataPortal\&.ServiceProviderMethodCallerTests\&.FindMethodMultipleCriteriaDIInterleaved ()"

.PP
Definition at line 103 of file ServiceProviderMethodCallerTests\&.cs\&.
.SS "void Csla\&.Test\&.DataPortal\&.ServiceProviderMethodCallerTests\&.FindMethodNoCriteriaNoDI ()"

.PP
Definition at line 70 of file ServiceProviderMethodCallerTests\&.cs\&.
.SS "void Csla\&.Test\&.DataPortal\&.ServiceProviderMethodCallerTests\&.FindMethodNullableCriteria ()"

.PP
Definition at line 46 of file ServiceProviderMethodCallerTests\&.cs\&.
.SS "async Task Csla\&.Test\&.DataPortal\&.ServiceProviderMethodCallerTests\&.FindMethodNullableCriteriaWithNullViaDataPortal ()"

.PP
Definition at line 63 of file ServiceProviderMethodCallerTests\&.cs\&.
.SS "async Task Csla\&.Test\&.DataPortal\&.ServiceProviderMethodCallerTests\&.FindMethodNullableCriteriaWithValueViaDataPortal ()"

.PP
Definition at line 56 of file ServiceProviderMethodCallerTests\&.cs\&.
.SS "void Csla\&.Test\&.DataPortal\&.ServiceProviderMethodCallerTests\&.FindMethodObjectCriteriaSubtype ()"

.PP
Definition at line 154 of file ServiceProviderMethodCallerTests\&.cs\&.
.SS "void Csla\&.Test\&.DataPortal\&.ServiceProviderMethodCallerTests\&.FindMethodObjectCriteriaValid ()"

.PP
Definition at line 146 of file ServiceProviderMethodCallerTests\&.cs\&.
.SS "void Csla\&.Test\&.DataPortal\&.ServiceProviderMethodCallerTests\&.FindMethodSingleCriteriaBadType ()"

.PP
Definition at line 163 of file ServiceProviderMethodCallerTests\&.cs\&.
.SS "void Csla\&.Test\&.DataPortal\&.ServiceProviderMethodCallerTests\&.FindMethodSingleCriteriaInvalid ()"

.PP
Definition at line 130 of file ServiceProviderMethodCallerTests\&.cs\&.
.SS "void Csla\&.Test\&.DataPortal\&.ServiceProviderMethodCallerTests\&.FindMethodSingleCriteriaValid ()"

.PP
Definition at line 138 of file ServiceProviderMethodCallerTests\&.cs\&.
.SS "void Csla\&.Test\&.DataPortal\&.ServiceProviderMethodCallerTests\&.FindOverlappingCriteriaInt ()"

.PP
Definition at line 270 of file ServiceProviderMethodCallerTests\&.cs\&.
.SS "void Csla\&.Test\&.DataPortal\&.ServiceProviderMethodCallerTests\&.Issue2109 ()"

.PP
Definition at line 278 of file ServiceProviderMethodCallerTests\&.cs\&.
.SS "void Csla\&.Test\&.DataPortal\&.ServiceProviderMethodCallerTests\&.Issue2287BusinessBaseFetch ()"

.PP
Definition at line 305 of file ServiceProviderMethodCallerTests\&.cs\&.
.SS "void Csla\&.Test\&.DataPortal\&.ServiceProviderMethodCallerTests\&.Issue2287BusinessBindingListFetch ()"

.PP
Definition at line 296 of file ServiceProviderMethodCallerTests\&.cs\&.
.SS "void Csla\&.Test\&.DataPortal\&.ServiceProviderMethodCallerTests\&.NoTarget ()"

.PP
Definition at line 31 of file ServiceProviderMethodCallerTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
