.TH "Csla.Server.Hosts.Mobile" 3 "Thu Jul 22 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Server.Hosts.Mobile
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCriteriaRequest\fP"
.br
.RI "Message sent to the WCF data portal\&. "
.ti -1c
.RI "interface \fBIMobileFactoryLoader\fP"
.br
.RI "Defines an interface to be implemented by a factory object that returns MobileFactory objects based on the MobileFactory attributes used to decorate CSLA Light business objects\&. "
.ti -1c
.RI "interface \fBIMobileRequest\fP"
.br
.RI "Interface for all requests from client "
.ti -1c
.RI "interface \fBIWcfPortal\fP"
.br
.RI "Defines the service contract for the WCF data portal\&. "
.ti -1c
.RI "class \fBMobileCriteriaRequest\fP"
.br
.RI "Class that will be used to execute a request from a client\&. This will inlcude Execute, Fetch, Create and Delete requests "
.ti -1c
.RI "class \fBMobileFactoryLoader\fP"
.br
.RI "Class containing the default implementation for the FactoryLoader delegate used by the data portal host\&. "
.ti -1c
.RI "class \fBMobileRequestProcessor\fP"
.br
.RI "Object that processes all the requests from a client "
.ti -1c
.RI "class \fBMobileResponse\fP"
.br
.RI "Object that encompasses the resut of the request from a client "
.ti -1c
.RI "class \fBMobileUpdateRequest\fP"
.br
.RI "Class that will be used to execute an Update request from a client\&. "
.ti -1c
.RI "class \fBUpdateRequest\fP"
.br
.RI "Message sent to the WCF data portal\&. "
.ti -1c
.RI "class \fBWcfErrorInfo\fP"
.br
.RI "Message containing details about any server-side exception\&. "
.ti -1c
.RI "class \fBWcfPortal\fP"
.br
.RI "Exposes server-side \fBDataPortal\fP functionality through WCF\&. "
.ti -1c
.RI "class \fBWcfResponse\fP"
.br
.RI "Response message returned from the WCF data portal methods\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
