.TH "csla.netcore.test.Configuration.TestCslaWriter" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csla.netcore.test.Configuration.TestCslaWriter
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.Serialization\&.Mobile\&.ICslaWriter\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBWrite\fP (Stream serializationStream, List< \fBSerializationInfo\fP > objectData)"
.br
.RI "Write a list of SerializationInfo objects into a stream, typically MemoryStream "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 146 of file ReadConfigFromDotnetCoreSubsystemTests\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void csla\&.netcore\&.test\&.Configuration\&.TestCslaWriter\&.Write (Stream serializationStream, List< \fBSerializationInfo\fP > objectData)"

.PP
Write a list of SerializationInfo objects into a stream, typically MemoryStream 
.PP
\fBParameters\fP
.RS 4
\fIserializationStream\fP Stream to write the data into
.br
\fIobjectData\fP List of SerializationInfo objects to write
.RE
.PP

.PP
Implements \fBCsla\&.Serialization\&.Mobile\&.ICslaWriter\fP\&.
.PP
Definition at line 148 of file ReadConfigFromDotnetCoreSubsystemTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
