.TH "Csla.Core.IObservableBindingList" 3 "Thu Jul 22 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Core.IObservableBindingList \- Defines additional elements for an ObservableCollection as required by CSLA \&.NET\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBCsla\&.Core\&.ObservableBindingList< T >\fP, \fBCsla\&.IBusinessListBase< C >\fP, and \fBCsla\&.IReadOnlyListBase< C >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "object \fBAddNew\fP ()"
.br
.RI "Creates and adds a new item to the collection\&. "
.in -1c
.SS "Events"

.in +1c
.ti -1c
.RI "EventHandler< \fBRemovingItemEventArgs\fP > \fBRemovingItem\fP"
.br
.RI "Event indicating that an item is being removed from the list\&. "
.in -1c
.SH "Detailed Description"
.PP 
Defines additional elements for an ObservableCollection as required by CSLA \&.NET\&. 


.PP
Definition at line 17 of file IObservableBindingList\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "object Csla\&.Core\&.IObservableBindingList\&.AddNew ()"

.PP
Creates and adds a new item to the collection\&. 
.PP
Implemented in \fBCsla\&.Core\&.ObservableBindingList< T >\fP\&.
.SH "Event Documentation"
.PP 
.SS "EventHandler<\fBRemovingItemEventArgs\fP> Csla\&.Core\&.IObservableBindingList\&.RemovingItem"

.PP
Event indicating that an item is being removed from the list\&. 
.PP
Definition at line 27 of file IObservableBindingList\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
