.TH "Csla.Test.DataPortal.FactoryBusy" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.DataPortal.FactoryBusy
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.BusinessBase< FactoryBusy >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBMarkObjectBusy\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 423 of file DataPortalTests\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Csla\&.Test\&.DataPortal\&.FactoryBusy\&.MarkObjectBusy ()"

.PP
Definition at line 425 of file DataPortalTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
