.TH "Csla.Validation.CommonRules.MaxLengthRuleArgs" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Validation.CommonRules.MaxLengthRuleArgs \- Custom \fBRuleArgs\fP object required by the StringMaxLength rule method\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.Validation\&.DecoratedRuleArgs\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMaxLengthRuleArgs\fP (string propertyName, int maxLength)"
.br
.RI "Create a new object\&. "
.ti -1c
.RI "\fBMaxLengthRuleArgs\fP (\fBCore\&.IPropertyInfo\fP propertyInfo, int maxLength)"
.br
.RI "Create a new object\&. "
.ti -1c
.RI "\fBMaxLengthRuleArgs\fP (string propertyName, string friendlyName, int maxLength)"
.br
.RI "Create a new object\&. "
.ti -1c
.RI "\fBMaxLengthRuleArgs\fP (string propertyName, int maxLength, string format)"
.br
.RI "Create a new object\&. "
.ti -1c
.RI "\fBMaxLengthRuleArgs\fP (\fBCore\&.IPropertyInfo\fP propertyInfo, int maxLength, string format)"
.br
.RI "Create a new object\&. "
.ti -1c
.RI "\fBMaxLengthRuleArgs\fP (string propertyName, string friendlyName, int maxLength, string format)"
.br
.RI "Create a new object\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBMaxLength\fP\fC [get]\fP"
.br
.RI "Get the max length for the string\&. "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Custom \fBRuleArgs\fP object required by the StringMaxLength rule method\&. 


.PP
Definition at line 97 of file Csla\&.Validation\&.Shared/CommonRules\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Csla\&.Validation\&.CommonRules\&.MaxLengthRuleArgs\&.MaxLengthRuleArgs (string propertyName, int maxLength)"

.PP
Create a new object\&. 
.PP
\fBParameters\fP
.RS 4
\fIpropertyName\fP Name of the property to validate\&.
.br
\fImaxLength\fP Max length of characters allowed\&.
.RE
.PP

.PP
Definition at line 112 of file Csla\&.Validation\&.Shared/CommonRules\&.cs\&.
.SS "Csla\&.Validation\&.CommonRules\&.MaxLengthRuleArgs\&.MaxLengthRuleArgs (\fBCore\&.IPropertyInfo\fP propertyInfo, int maxLength)"

.PP
Create a new object\&. 
.PP
\fBParameters\fP
.RS 4
\fIpropertyInfo\fP \fBPropertyInfo\fP for the property to validate\&.
.br
\fImaxLength\fP Max length of characters allowed\&.
.RE
.PP

.PP
Definition at line 125 of file Csla\&.Validation\&.Shared/CommonRules\&.cs\&.
.SS "Csla\&.Validation\&.CommonRules\&.MaxLengthRuleArgs\&.MaxLengthRuleArgs (string propertyName, string friendlyName, int maxLength)"

.PP
Create a new object\&. 
.PP
\fBParameters\fP
.RS 4
\fIpropertyName\fP Name of the property to validate\&.
.br
\fIfriendlyName\fP A friendly name for the property, which will be used in place of the property name when creating the broken rule description string\&.
.br
\fImaxLength\fP Max length of characters allowed\&.
.RE
.PP

.PP
Definition at line 140 of file Csla\&.Validation\&.Shared/CommonRules\&.cs\&.
.SS "Csla\&.Validation\&.CommonRules\&.MaxLengthRuleArgs\&.MaxLengthRuleArgs (string propertyName, int maxLength, string format)"

.PP
Create a new object\&. 
.PP
\fBParameters\fP
.RS 4
\fIpropertyName\fP Name of the property to validate\&.
.br
\fImaxLength\fP Max length of characters allowed\&.
.br
\fIformat\fP Format string for the max length value in the broken rule string\&.
.RE
.PP

.PP
Definition at line 155 of file Csla\&.Validation\&.Shared/CommonRules\&.cs\&.
.SS "Csla\&.Validation\&.CommonRules\&.MaxLengthRuleArgs\&.MaxLengthRuleArgs (\fBCore\&.IPropertyInfo\fP propertyInfo, int maxLength, string format)"

.PP
Create a new object\&. 
.PP
\fBParameters\fP
.RS 4
\fIpropertyInfo\fP \fBPropertyInfo\fP for the property to validate\&.
.br
\fImaxLength\fP Max length of characters allowed\&.
.br
\fIformat\fP Format string for the max length value in the broken rule string\&.
.RE
.PP

.PP
Definition at line 170 of file Csla\&.Validation\&.Shared/CommonRules\&.cs\&.
.SS "Csla\&.Validation\&.CommonRules\&.MaxLengthRuleArgs\&.MaxLengthRuleArgs (string propertyName, string friendlyName, int maxLength, string format)"

.PP
Create a new object\&. 
.PP
\fBParameters\fP
.RS 4
\fIpropertyName\fP Name of the property to validate\&.
.br
\fIfriendlyName\fP A friendly name for the property, which will be used in place of the property name when creating the broken rule description string\&.
.br
\fImaxLength\fP Max length of characters allowed\&.
.br
\fIformat\fP Format string for the max length value in the broken rule string\&.
.RE
.PP

.PP
Definition at line 187 of file Csla\&.Validation\&.Shared/CommonRules\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "int Csla\&.Validation\&.CommonRules\&.MaxLengthRuleArgs\&.MaxLength\fC [get]\fP"

.PP
Get the max length for the string\&. 
.PP
Definition at line 102 of file Csla\&.Validation\&.Shared/CommonRules\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
