.TH "Csla.Testing.Business.ObjectFactory.BusinessItem" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Testing.Business.ObjectFactory.BusinessItem
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.BusinessBase< BusinessItem >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBusinessItem\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBId\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBOperationResult\fP\fC [get, set]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 13 of file BusinessItem\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Csla\&.Testing\&.Business\&.ObjectFactory\&.BusinessItem\&.BusinessItem ()"

.PP
Definition at line 15 of file BusinessItem\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "string Csla\&.Testing\&.Business\&.ObjectFactory\&.BusinessItem\&.Id\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 18 of file BusinessItem\&.cs\&.
.SS "string Csla\&.Testing\&.Business\&.ObjectFactory\&.BusinessItem\&.OperationResult\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 32 of file BusinessItem\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
