.TH "Csla.Web.Mvc.Test.ModelBinderTest.SingleRoot" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Web.Mvc.Test.ModelBinderTest.SingleRoot
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.BusinessBase< SingleRoot >\fP\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBSingleRoot\fP \fBGetSingleRoot\fP (int id)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static readonly \fBPropertyInfo\fP< int > \fBIdProperty\fP = RegisterProperty<int>(p => p\&.ID)"
.br
.ti -1c
.RI "static readonly \fBPropertyInfo\fP< string > \fBNameProperty\fP = RegisterProperty<string>(p => p\&.Name)"
.br
.ti -1c
.RI "static readonly \fBPropertyInfo\fP< \fBSmartDate\fP > \fBDOBProperty\fP = RegisterProperty<\fBSmartDate\fP>(p => p\&.DOB)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBDataPortal_Create\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBID\fP\fC [get]\fP"
.br
.ti -1c
.RI "string \fBName\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBSmartDate\fP \fBDOB\fP\fC [get, set]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 16 of file Csla\&.Web\&.Mvc\&.Test/ModelBinderTest/SingleRoot\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override void Csla\&.Web\&.Mvc\&.Test\&.ModelBinderTest\&.SingleRoot\&.DataPortal_Create ()\fC [protected]\fP"

.PP
Definition at line 44 of file Csla\&.Web\&.Mvc\&.Test/ModelBinderTest/SingleRoot\&.cs\&.
.SS "static \fBSingleRoot\fP Csla\&.Web\&.Mvc\&.Test\&.ModelBinderTest\&.SingleRoot\&.GetSingleRoot (int id)\fC [static]\fP"

.PP
Definition at line 40 of file Csla\&.Web\&.Mvc\&.Test/ModelBinderTest/SingleRoot\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "readonly \fBPropertyInfo\fP<\fBSmartDate\fP> Csla\&.Web\&.Mvc\&.Test\&.ModelBinderTest\&.SingleRoot\&.DOBProperty = RegisterProperty<\fBSmartDate\fP>(p => p\&.DOB)\fC [static]\fP"

.PP
Definition at line 31 of file Csla\&.Web\&.Mvc\&.Test/ModelBinderTest/SingleRoot\&.cs\&.
.SS "readonly \fBPropertyInfo\fP<int> Csla\&.Web\&.Mvc\&.Test\&.ModelBinderTest\&.SingleRoot\&.IdProperty = RegisterProperty<int>(p => p\&.ID)\fC [static]\fP"

.PP
Definition at line 18 of file Csla\&.Web\&.Mvc\&.Test/ModelBinderTest/SingleRoot\&.cs\&.
.SS "readonly \fBPropertyInfo\fP<string> Csla\&.Web\&.Mvc\&.Test\&.ModelBinderTest\&.SingleRoot\&.NameProperty = RegisterProperty<string>(p => p\&.Name)\fC [static]\fP"

.PP
Definition at line 25 of file Csla\&.Web\&.Mvc\&.Test/ModelBinderTest/SingleRoot\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "\fBSmartDate\fP Csla\&.Web\&.Mvc\&.Test\&.ModelBinderTest\&.SingleRoot\&.DOB\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 32 of file Csla\&.Web\&.Mvc\&.Test/ModelBinderTest/SingleRoot\&.cs\&.
.SS "int Csla\&.Web\&.Mvc\&.Test\&.ModelBinderTest\&.SingleRoot\&.ID\fC [get]\fP"

.PP
Definition at line 19 of file Csla\&.Web\&.Mvc\&.Test/ModelBinderTest/SingleRoot\&.cs\&.
.SS "string Csla\&.Web\&.Mvc\&.Test\&.ModelBinderTest\&.SingleRoot\&.Name\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 26 of file Csla\&.Web\&.Mvc\&.Test/ModelBinderTest/SingleRoot\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
