.TH "Csla.Test.Authorization.PermissionRootWithCriteria" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.Authorization.PermissionRootWithCriteria
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.BusinessBase< PermissionRootWithCriteria >\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCriteria\fP"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBAddObjectAuthorizationRules\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 14 of file PermissionRootWithCriteria\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "static void Csla\&.Test\&.Authorization\&.PermissionRootWithCriteria\&.AddObjectAuthorizationRules ()\fC [static]\fP"

.PP
Definition at line 16 of file PermissionRootWithCriteria\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
