.TH "Csla.DataPortalClient.HttpProxy" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.DataPortalClient.HttpProxy \- Implements a data portal proxy to relay data portal calls to a remote application server by using http\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.DataPortalClient\&.DataPortalProxy\fP\&.
.PP
Inherited by \fBCsla\&.DataPortalClient\&.HttpCompressionProxy\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHttpProxy\fP ()"
.br
.RI "Creates an instance of the object, initializing it to use the DefaultUrl values\&. "
.ti -1c
.RI "\fBHttpProxy\fP (string dataPortalUrl)"
.br
.RI "Creates an instance of the object, initializing it to use the supplied URL\&. "
.ti -1c
.RI "\fBHttpProxy\fP (HttpClient httpClient)"
.br
.RI "Creates an instance of the object, initializing it to use the supplied HttpClient object\&. "
.ti -1c
.RI "\fBHttpProxy\fP (HttpClient httpClient, string dataPortalUrl)"
.br
.RI "Creates an instance of the object, initializing it to use the supplied HttpClient object and URL\&. "
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual HttpClientHandler \fBGetHttpClientHandler\fP ()"
.br
.RI "Gets an HttpClientHandler for use in initializing the HttpClient instance\&. "
.ti -1c
.RI "virtual HttpClient \fBGetHttpClient\fP ()"
.br
.RI "Gets an HttpClient object for use in communication with the server\&. "
.ti -1c
.RI "virtual WebClient \fBGetWebClient\fP ()"
.br
.RI "Gets an WebClient object for use in communication with the server\&. "
.ti -1c
.RI "override async Task< byte[]> \fBCallDataPortalServer\fP (byte[] serialized, string operation, string routingToken, bool isSync)"
.br
.RI "Select client to make request based on isSync parameter and return response from server "
.ti -1c
.RI "virtual void \fBSetHttpRequestHeaders\fP (HttpRequestMessage request)"
.br
.RI "Override to set headers or other properties of the HttpRequestMessage before it is sent to the server\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "static bool \fBUseTextSerialization\fP = false\fC [get, set]\fP"
.br
.RI "Gets or sets a value indicating whether to use text/string serialization instead of the default binary serialization\&. "
.in -1c
.SH "Detailed Description"
.PP 
Implements a data portal proxy to relay data portal calls to a remote application server by using http\&. 


.PP
Definition at line 26 of file HttpProxy\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Csla\&.DataPortalClient\&.HttpProxy\&.HttpProxy ()"

.PP
Creates an instance of the object, initializing it to use the DefaultUrl values\&. 
.PP
Definition at line 33 of file HttpProxy\&.cs\&.
.SS "Csla\&.DataPortalClient\&.HttpProxy\&.HttpProxy (string dataPortalUrl)"

.PP
Creates an instance of the object, initializing it to use the supplied URL\&. 
.PP
\fBParameters\fP
.RS 4
\fIdataPortalUrl\fP \fBServer\fP endpoint URL
.RE
.PP

.PP
Definition at line 42 of file HttpProxy\&.cs\&.
.SS "Csla\&.DataPortalClient\&.HttpProxy\&.HttpProxy (HttpClient httpClient)"

.PP
Creates an instance of the object, initializing it to use the supplied HttpClient object\&. 
.PP
\fBParameters\fP
.RS 4
\fIhttpClient\fP HttpClient instance
.RE
.PP

.PP
Definition at line 52 of file HttpProxy\&.cs\&.
.SS "Csla\&.DataPortalClient\&.HttpProxy\&.HttpProxy (HttpClient httpClient, string dataPortalUrl)"

.PP
Creates an instance of the object, initializing it to use the supplied HttpClient object and URL\&. 
.PP
\fBParameters\fP
.RS 4
\fIhttpClient\fP HttpClient instance
.br
\fIdataPortalUrl\fP \fBServer\fP endpoint URL
.RE
.PP

.PP
Definition at line 63 of file HttpProxy\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override async Task<byte[]> Csla\&.DataPortalClient\&.HttpProxy\&.CallDataPortalServer (byte[] serialized, string operation, string routingToken, bool isSync)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Select client to make request based on isSync parameter and return response from server 
.PP
\fBParameters\fP
.RS 4
\fIserialized\fP Serialised request
.br
\fIoperation\fP \fBDataPortal\fP operation
.br
\fIroutingToken\fP Routing Tag for server
.br
\fIisSync\fP True if the client-side proxy should synchronously invoke the server\&.
.RE
.PP
\fBReturns\fP
.RS 4
Serialised response from server
.RE
.PP

.PP
Implements \fBCsla\&.DataPortalClient\&.DataPortalProxy\fP\&.
.PP
Definition at line 134 of file HttpProxy\&.cs\&.
.SS "virtual HttpClient Csla\&.DataPortalClient\&.HttpProxy\&.GetHttpClient ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Gets an HttpClient object for use in communication with the server\&. 
.PP
Definition at line 84 of file HttpProxy\&.cs\&.
.SS "virtual HttpClientHandler Csla\&.DataPortalClient\&.HttpProxy\&.GetHttpClientHandler ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Gets an HttpClientHandler for use in initializing the HttpClient instance\&. 
.PP
Reimplemented in \fBCsla\&.DataPortalClient\&.HttpCompressionProxy\fP\&.
.PP
Definition at line 75 of file HttpProxy\&.cs\&.
.SS "virtual WebClient Csla\&.DataPortalClient\&.HttpProxy\&.GetWebClient ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Gets an WebClient object for use in communication with the server\&. 
.PP
Reimplemented in \fBCsla\&.DataPortalClient\&.HttpCompressionProxy\fP\&.
.PP
Definition at line 114 of file HttpProxy\&.cs\&.
.SS "virtual void Csla\&.DataPortalClient\&.HttpProxy\&.SetHttpRequestHeaders (HttpRequestMessage request)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Override to set headers or other properties of the HttpRequestMessage before it is sent to the server\&. 
.PP
\fBParameters\fP
.RS 4
\fIrequest\fP HttpRequestMessage instance
.RE
.PP

.PP
Reimplemented in \fBCsla\&.DataPortalClient\&.HttpCompressionProxy\fP\&.
.PP
Definition at line 146 of file HttpProxy\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "bool Csla\&.DataPortalClient\&.HttpProxy\&.UseTextSerialization = false\fC [static]\fP, \fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets a value indicating whether to use text/string serialization instead of the default binary serialization\&. 
.PP
Definition at line 124 of file HttpProxy\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
