.TH "Csla.Core.BusyChangedEventArgs" 3 "Thu Jul 22 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Core.BusyChangedEventArgs \- Event arguments for the BusyChanged event\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits EventArgs\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBusyChangedEventArgs\fP (string propertyName, bool busy)"
.br
.RI "Creates a new instance of the object\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "bool \fBBusy\fP\fC [get, protected set]\fP"
.br
.RI "New busy value\&. "
.ti -1c
.RI "string \fBPropertyName\fP\fC [get, protected set]\fP"
.br
.RI "Property for which the Busy value has changed\&. "
.in -1c
.SH "Detailed Description"
.PP 
Event arguments for the BusyChanged event\&. 


.PP
Definition at line 29 of file BusyChangedEventArgs\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Csla\&.Core\&.BusyChangedEventArgs\&.BusyChangedEventArgs (string propertyName, bool busy)"

.PP
Creates a new instance of the object\&. 
.PP
\fBParameters\fP
.RS 4
\fIpropertyName\fP Property for which the Busy value has changed\&. 
.br
\fIbusy\fP New Busy value\&. 
.RE
.PP

.PP
Definition at line 49 of file BusyChangedEventArgs\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "bool Csla\&.Core\&.BusyChangedEventArgs\&.Busy\fC [get]\fP, \fC [protected set]\fP"

.PP
New busy value\&. 
.PP
Definition at line 34 of file BusyChangedEventArgs\&.cs\&.
.SS "string Csla\&.Core\&.BusyChangedEventArgs\&.PropertyName\fC [get]\fP, \fC [protected set]\fP"

.PP
Property for which the Busy value has changed\&. 
.PP
Definition at line 38 of file BusyChangedEventArgs\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
