.TH "Csla.DataPortalEventArgs" 3 "Thu Jul 22 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.DataPortalEventArgs \- Provides information about the \fBDataPortal\fP call\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits EventArgs\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDataPortalEventArgs\fP (\fBServer\&.DataPortalContext\fP dataPortalContext, Type objectType, object obj, \fBDataPortalOperations\fP operation)"
.br
.RI "Creates an instance of the object\&. "
.ti -1c
.RI "\fBDataPortalEventArgs\fP (\fBServer\&.DataPortalContext\fP dataPortalContext, Type objectType, object obj, \fBDataPortalOperations\fP operation, \fBException\fP exception)"
.br
.RI "Creates an instance of the object\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBServer\&.DataPortalContext\fP \fBDataPortalContext\fP\fC [get]\fP"
.br
.RI "The DataPortalContext object passed to the server-side \fBDataPortal\fP\&. "
.ti -1c
.RI "\fBDataPortalOperations\fP \fBOperation\fP\fC [get]\fP"
.br
.RI "Gets the requested data portal operation\&. "
.ti -1c
.RI "Exception \fBException\fP\fC [get]\fP"
.br
.RI "Gets a reference to any exception that occurred during the data portal call\&. "
.ti -1c
.RI "Type \fBObjectType\fP\fC [get]\fP"
.br
.RI "Gets the object type being processed by the data portal\&. "
.ti -1c
.RI "object \fBObject\fP\fC [get]\fP"
.br
.RI "Gets the criteria object or business object being processed by the data portal\&. "
.in -1c
.SH "Detailed Description"
.PP 
Provides information about the \fBDataPortal\fP call\&. 


.PP
Definition at line 16 of file DataPortalEventArgs\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Csla\&.DataPortalEventArgs\&.DataPortalEventArgs (\fBServer\&.DataPortalContext\fP dataPortalContext, Type objectType, object obj, \fBDataPortalOperations\fP operation)"

.PP
Creates an instance of the object\&. 
.PP
\fBParameters\fP
.RS 4
\fIdataPortalContext\fP \fBData\fP portal context object\&. 
.br
\fIobjectType\fP Business object type\&. 
.br
\fIobj\fP Criteria or business object for request\&. 
.br
\fIoperation\fP \fBData\fP portal operation being performed\&. 
.RE
.PP

.PP
Definition at line 88 of file DataPortalEventArgs\&.cs\&.
.SS "Csla\&.DataPortalEventArgs\&.DataPortalEventArgs (\fBServer\&.DataPortalContext\fP dataPortalContext, Type objectType, object obj, \fBDataPortalOperations\fP operation, \fBException\fP exception)"

.PP
Creates an instance of the object\&. 
.PP
\fBParameters\fP
.RS 4
\fIdataPortalContext\fP \fBData\fP portal context object\&. 
.br
\fIobjectType\fP Business object type\&. 
.br
\fIobj\fP Criteria or business object for request\&. 
.br
\fIoperation\fP \fBData\fP portal operation being performed\&. 
.br
\fIexception\fP Exception encountered during processing\&. 
.RE
.PP

.PP
Definition at line 114 of file DataPortalEventArgs\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "\fBServer\&.DataPortalContext\fP Csla\&.DataPortalEventArgs\&.DataPortalContext\fC [get]\fP"

.PP
The DataPortalContext object passed to the server-side \fBDataPortal\fP\&. 
.PP
Definition at line 28 of file DataPortalEventArgs\&.cs\&.
.SS "Exception Csla\&.DataPortalEventArgs\&.Exception\fC [get]\fP"

.PP
Gets a reference to any exception that occurred during the data portal call\&. This property will return Nothing (null in C#) if no exception occurred\&. Exceptions are returned only as part of a data portal complete event or method\&. 
.PP
Definition at line 50 of file DataPortalEventArgs\&.cs\&.
.SS "object Csla\&.DataPortalEventArgs\&.Object\fC [get]\fP"

.PP
Gets the criteria object or business object being processed by the data portal\&. 
.PP
Definition at line 68 of file DataPortalEventArgs\&.cs\&.
.SS "Type Csla\&.DataPortalEventArgs\&.ObjectType\fC [get]\fP"

.PP
Gets the object type being processed by the data portal\&. 
.PP
Definition at line 59 of file DataPortalEventArgs\&.cs\&.
.SS "\fBDataPortalOperations\fP Csla\&.DataPortalEventArgs\&.Operation\fC [get]\fP"

.PP
Gets the requested data portal operation\&. 
.PP
Definition at line 36 of file DataPortalEventArgs\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
