.TH "Csla.Test" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBAppContext\fP"
.br
.ti -1c
.RI "namespace \fBAppDomainTests\fP"
.br
.ti -1c
.RI "namespace \fBAuthorization\fP"
.br
.ti -1c
.RI "namespace \fBBasic\fP"
.br
.ti -1c
.RI "namespace \fBBasicModern\fP"
.br
.ti -1c
.RI "namespace \fBBusinessListBase\fP"
.br
.ti -1c
.RI "namespace \fBBypassPropertyChecks\fP"
.br
.ti -1c
.RI "namespace \fBChildChanged\fP"
.br
.ti -1c
.RI "namespace \fBChildrenByInterface\fP"
.br
.ti -1c
.RI "namespace \fBCommandBase\fP"
.br
.ti -1c
.RI "namespace \fBCslaDataProvider\fP"
.br
.ti -1c
.RI "namespace \fBData\fP"
.br
.ti -1c
.RI "namespace \fBDataAnnotations\fP"
.br
.ti -1c
.RI "namespace \fBDataBinding\fP"
.br
.ti -1c
.RI "namespace \fBDataMapper\fP"
.br
.ti -1c
.RI "namespace \fBDataPortal\fP"
.br
.ti -1c
.RI "namespace \fBDataPortalChild\fP"
.br
.ti -1c
.RI "namespace \fBDataPortalTest\fP"
.br
.ti -1c
.RI "namespace \fBDPException\fP"
.br
.ti -1c
.RI "namespace \fBEditableRootList\fP"
.br
.ti -1c
.RI "namespace \fBFieldManager\fP"
.br
.ti -1c
.RI "namespace \fBGraphMerge\fP"
.br
.ti -1c
.RI "namespace \fBIdentityConverter\fP"
.br
.ti -1c
.RI "namespace \fBIO\fP"
.br
.ti -1c
.RI "namespace \fBLazyLoad\fP"
.br
.ti -1c
.RI "namespace \fBLazySingelton\fP"
.br
.ti -1c
.RI "namespace \fBLinq\fP"
.br
.ti -1c
.RI "namespace \fBLogicalExecutionLocation\fP"
.br
.ti -1c
.RI "namespace \fBMethodCaller\fP"
.br
.ti -1c
.RI "namespace \fBNullable\fP"
.br
.ti -1c
.RI "namespace \fBObjectFactory\fP"
.br
.ti -1c
.RI "namespace \fBProperties\fP"
.br
.ti -1c
.RI "namespace \fBPropertyGetSet\fP"
.br
.ti -1c
.RI "namespace \fBPropertyInfo\fP"
.br
.ti -1c
.RI "namespace \fBReflection\fP"
.br
.ti -1c
.RI "namespace \fBRollBack\fP"
.br
.ti -1c
.RI "namespace \fBSecurity\fP"
.br
.ti -1c
.RI "namespace \fBSerialization\fP"
.br
.ti -1c
.RI "namespace \fBSilverlight\fP"
.br
.ti -1c
.RI "namespace \fBSmartDate\fP"
.br
.ti -1c
.RI "namespace \fBSortedBindingList\fP"
.br
.ti -1c
.RI "namespace \fBSourceLink\fP"
.br
.ti -1c
.RI "namespace \fBThreading\fP"
.br
.ti -1c
.RI "namespace \fBUtilities\fP"
.br
.ti -1c
.RI "namespace \fBValidationRules\fP"
.br
.ti -1c
.RI "namespace \fBViewModelTests\fP"
.br
.ti -1c
.RI "namespace \fBWindows\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDataPortalTestDatabaseDataSet\fP"
.br
.RI "Represents a strongly typed in-memory cache of data\&. /summary> "
.ti -1c
.RI "class \fBWellKnownValues\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
