.TH "Csla.Server.Hosts.Mobile.MobileCriteriaRequest" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Server.Hosts.Mobile.MobileCriteriaRequest \- Class that will be used to execute a request from a client\&. This will inlcude Execute, Fetch, Create and Delete requests  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.Server\&.Hosts\&.Mobile\&.IMobileRequest\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMobileCriteriaRequest\fP (string typeName, object criteria, IPrincipal principal, \fBContextDictionary\fP globalContext, \fBContextDictionary\fP clientContext, string clientCulture, string clientUICulture)"
.br
.RI "New instance of criteria object "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBTypeName\fP\fC [get, set]\fP"
.br
.RI "Type of object that is the target of the request "
.ti -1c
.RI "object \fBCriteria\fP\fC [get, set]\fP"
.br
.RI "Criteria object\&. "
.ti -1c
.RI "IPrincipal \fBPrincipal\fP\fC [get, set]\fP"
.br
.RI "Principal that will be set for the request "
.ti -1c
.RI "\fBContextDictionary\fP \fBGlobalContext\fP\fC [get, set]\fP"
.br
.RI "Global context object\&. "
.ti -1c
.RI "\fBContextDictionary\fP \fBClientContext\fP\fC [get, set]\fP"
.br
.RI "Client context object\&. "
.ti -1c
.RI "string \fBClientCulture\fP\fC [get, set]\fP"
.br
.RI "The client culture\&. "
.ti -1c
.RI "string \fBClientUICulture\fP\fC [get, set]\fP"
.br
.RI "The client UI culture\&. "
.in -1c
.SH "Detailed Description"
.PP 
Class that will be used to execute a request from a client\&. This will inlcude Execute, Fetch, Create and Delete requests 


.PP
Definition at line 18 of file MobileCriteriaRequest\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Csla\&.Server\&.Hosts\&.Mobile\&.MobileCriteriaRequest\&.MobileCriteriaRequest (string typeName, object criteria, IPrincipal principal, \fBContextDictionary\fP globalContext, \fBContextDictionary\fP clientContext, string clientCulture, string clientUICulture)"

.PP
New instance of criteria object 
.PP
\fBParameters\fP
.RS 4
\fItypeName\fP Type of object that is the target of the request
.br
\fIcriteria\fP Criteria object\&.
.br
\fIprincipal\fP Principal that will be set for the request
.br
\fIglobalContext\fP Global context object\&.
.br
\fIclientContext\fP Client context object\&.
.br
\fIclientCulture\fP The client culture\&.
.br
\fIclientUICulture\fP The client UI culture\&.
.RE
.PP

.PP
Definition at line 59 of file MobileCriteriaRequest\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "\fBContextDictionary\fP Csla\&.Server\&.Hosts\&.Mobile\&.MobileCriteriaRequest\&.ClientContext\fC [get]\fP, \fC [set]\fP"

.PP
Client context object\&. 
.PP
Definition at line 39 of file MobileCriteriaRequest\&.cs\&.
.SS "string Csla\&.Server\&.Hosts\&.Mobile\&.MobileCriteriaRequest\&.ClientCulture\fC [get]\fP, \fC [set]\fP"

.PP
The client culture\&. 
.PP
Definition at line 43 of file MobileCriteriaRequest\&.cs\&.
.SS "string Csla\&.Server\&.Hosts\&.Mobile\&.MobileCriteriaRequest\&.ClientUICulture\fC [get]\fP, \fC [set]\fP"

.PP
The client UI culture\&. 
.PP
Definition at line 47 of file MobileCriteriaRequest\&.cs\&.
.SS "object Csla\&.Server\&.Hosts\&.Mobile\&.MobileCriteriaRequest\&.Criteria\fC [get]\fP, \fC [set]\fP"

.PP
Criteria object\&. 
.PP
Definition at line 27 of file MobileCriteriaRequest\&.cs\&.
.SS "\fBContextDictionary\fP Csla\&.Server\&.Hosts\&.Mobile\&.MobileCriteriaRequest\&.GlobalContext\fC [get]\fP, \fC [set]\fP"

.PP
Global context object\&. 
.PP
Definition at line 35 of file MobileCriteriaRequest\&.cs\&.
.SS "IPrincipal Csla\&.Server\&.Hosts\&.Mobile\&.MobileCriteriaRequest\&.Principal\fC [get]\fP, \fC [set]\fP"

.PP
Principal that will be set for the request 
.PP
Definition at line 31 of file MobileCriteriaRequest\&.cs\&.
.SS "string Csla\&.Server\&.Hosts\&.Mobile\&.MobileCriteriaRequest\&.TypeName\fC [get]\fP, \fC [set]\fP"

.PP
Type of object that is the target of the request 
.PP
Definition at line 23 of file MobileCriteriaRequest\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
