.TH "Csla.Test.DataPortal.Issue2109List" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.DataPortal.Issue2109List
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.ReadOnlyListBase< Issue2109List, Issue2109 >\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 560 of file ServiceProviderMethodCallerTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
