.TH "Csla.Test.DataPortal.DisposableClass" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.DataPortal.DisposableClass
.SH SYNOPSIS
.br
.PP
.PP
Inherits IDisposable\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBDispose\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "Guid \fBId\fP = Guid\&.NewGuid()\fC [get]\fP"
.br
.ti -1c
.RI "bool \fBIsDisposed\fP = false\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 32 of file DisposeScopeTest\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Csla\&.Test\&.DataPortal\&.DisposableClass\&.Dispose ()"

.PP
Definition at line 37 of file DisposeScopeTest\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "Guid Csla\&.Test\&.DataPortal\&.DisposableClass\&.Id = Guid\&.NewGuid()\fC [get]\fP"

.PP
Definition at line 35 of file DisposeScopeTest\&.cs\&.
.SS "bool Csla\&.Test\&.DataPortal\&.DisposableClass\&.IsDisposed = false\fC [get]\fP"

.PP
Definition at line 36 of file DisposeScopeTest\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
