.TH "Csla.Server.Hosts.Mobile.CriteriaRequest" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Server.Hosts.Mobile.CriteriaRequest \- Message sent to the WCF data portal\&.  

.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBTypeName\fP\fC [get, set]\fP"
.br
.RI "Assembly qualified name of the business object type to create\&. "
.ti -1c
.RI "byte[] \fBCriteriaData\fP\fC [get, set]\fP"
.br
.RI "Serialized data for the criteria object\&. "
.ti -1c
.RI "byte[] \fBPrincipal\fP\fC [get, set]\fP"
.br
.RI "Serialized data for the principal object\&. "
.ti -1c
.RI "byte[] \fBGlobalContext\fP\fC [get, set]\fP"
.br
.RI "Serialized data for the global context object\&. "
.ti -1c
.RI "byte[] \fBClientContext\fP\fC [get, set]\fP"
.br
.RI "Serialized data for the client context object\&. "
.ti -1c
.RI "string \fBClientCulture\fP\fC [get, set]\fP"
.br
.RI "Serialized client culture\&. "
.ti -1c
.RI "string \fBClientUICulture\fP\fC [get, set]\fP"
.br
.RI "Serialized client UI culture\&. "
.in -1c
.SH "Detailed Description"
.PP 
Message sent to the WCF data portal\&. 


.PP
Definition at line 19 of file CriteriaRequest\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "byte [] Csla\&.Server\&.Hosts\&.Mobile\&.CriteriaRequest\&.ClientContext\fC [get]\fP, \fC [set]\fP"

.PP
Serialized data for the client context object\&. 
.PP
Definition at line 50 of file CriteriaRequest\&.cs\&.
.SS "string Csla\&.Server\&.Hosts\&.Mobile\&.CriteriaRequest\&.ClientCulture\fC [get]\fP, \fC [set]\fP"

.PP
Serialized client culture\&. The client culture\&.
.PP
Definition at line 57 of file CriteriaRequest\&.cs\&.
.SS "string Csla\&.Server\&.Hosts\&.Mobile\&.CriteriaRequest\&.ClientUICulture\fC [get]\fP, \fC [set]\fP"

.PP
Serialized client UI culture\&. The client UI culture\&.
.PP
Definition at line 64 of file CriteriaRequest\&.cs\&.
.SS "byte [] Csla\&.Server\&.Hosts\&.Mobile\&.CriteriaRequest\&.CriteriaData\fC [get]\fP, \fC [set]\fP"

.PP
Serialized data for the criteria object\&. 
.PP
Definition at line 32 of file CriteriaRequest\&.cs\&.
.SS "byte [] Csla\&.Server\&.Hosts\&.Mobile\&.CriteriaRequest\&.GlobalContext\fC [get]\fP, \fC [set]\fP"

.PP
Serialized data for the global context object\&. 
.PP
Definition at line 44 of file CriteriaRequest\&.cs\&.
.SS "byte [] Csla\&.Server\&.Hosts\&.Mobile\&.CriteriaRequest\&.Principal\fC [get]\fP, \fC [set]\fP"

.PP
Serialized data for the principal object\&. 
.PP
Definition at line 38 of file CriteriaRequest\&.cs\&.
.SS "string Csla\&.Server\&.Hosts\&.Mobile\&.CriteriaRequest\&.TypeName\fC [get]\fP, \fC [set]\fP"

.PP
Assembly qualified name of the business object type to create\&. 
.PP
Definition at line 26 of file CriteriaRequest\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
