.TH "Csla.Server.GenericBusinessException" 3 "Thu Jul 22 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Server.GenericBusinessException \- This exception is returned as BusinessException in \fBDataPortalException\fP when the serverside/inner exception is not serializable  

.SH SYNOPSIS
.br
.PP
.PP
Inherits System\&.Exception\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGenericBusinessException\fP (Exception wrappedException)"
.br
.RI "Initializes a new instance of the \fBGenericBusinessException\fP class\&. Reads information for a NonSerializable excpeption into \fBGenericBusinessException\fP "
.ti -1c
.RI "\fBGenericBusinessException\fP (Exception wrappedException, Exception innerException)"
.br
.RI "Initializes a new instance of the \fBGenericBusinessException\fP class\&. "
.ti -1c
.RI "\fBGenericBusinessException\fP (SerializationInfo info, StreamingContext context)"
.br
.RI "Initializes a new instance of the \fBGenericBusinessException\fP class\&. "
.ti -1c
.RI "override void \fBGetObjectData\fP (SerializationInfo info, StreamingContext context)"
.br
.RI "When overridden in a derived class, sets the T:System\&.Runtime\&.Serialization\&.SerializationInfo with information about the exception\&. "
.ti -1c
.RI "override string \fBToString\fP ()"
.br
.RI "Returns a System\&.String that represents this instance\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override string \fBStackTrace\fP\fC [get]\fP"
.br
.RI "Gets a string representation of the immediate frames on the call stack\&. "
.ti -1c
.RI "override IDictionary \fBData\fP\fC [get]\fP"
.br
.RI "Gets a collection of key/value pairs that provide additional user-defined information about the exception\&. "
.ti -1c
.RI "string \fBTypeName\fP\fC [get]\fP"
.br
.RI "Gets the name of the type\&. "
.in -1c
.SH "Detailed Description"
.PP 
This exception is returned as BusinessException in \fBDataPortalException\fP when the serverside/inner exception is not serializable 


.PP
Definition at line 21 of file GenericBusinessException\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Csla\&.Server\&.GenericBusinessException\&.GenericBusinessException (Exception wrappedException)"

.PP
Initializes a new instance of the \fBGenericBusinessException\fP class\&. Reads information for a NonSerializable excpeption into \fBGenericBusinessException\fP 
.PP
\fBParameters\fP
.RS 4
\fIwrappedException\fP The wrapped exception\&.
.RE
.PP

.PP
Definition at line 74 of file GenericBusinessException\&.cs\&.
.SS "Csla\&.Server\&.GenericBusinessException\&.GenericBusinessException (Exception wrappedException, Exception innerException)"

.PP
Initializes a new instance of the \fBGenericBusinessException\fP class\&. 
.PP
\fBParameters\fP
.RS 4
\fIwrappedException\fP The wrapped exception\&.
.br
\fIinnerException\fP The inner exception\&.
.RE
.PP

.PP
Definition at line 89 of file GenericBusinessException\&.cs\&.
.SS "Csla\&.Server\&.GenericBusinessException\&.GenericBusinessException (SerializationInfo info, StreamingContext context)"

.PP
Initializes a new instance of the \fBGenericBusinessException\fP class\&. 
.PP
\fBParameters\fP
.RS 4
\fIinfo\fP The T:System\&.Runtime\&.Serialization\&.SerializationInfo that holds the serialized object data about the exception being thrown\&.
.br
\fIcontext\fP The T:System\&.Runtime\&.Serialization\&.StreamingContext that contains contextual information about the source or destination\&.
.RE
.PP
\fBExceptions\fP
.RS 4
\fIT:System\&.ArgumentNullException\fP The \fIinfo\fP  parameter is null\&. 
.br
\fIT:System\&.Runtime\&.Serialization\&.SerializationException\fP The class name is null or P:System\&.Exception\&.HResult is zero (0)\&. 
.RE
.PP

.PP
Definition at line 107 of file GenericBusinessException\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override void Csla\&.Server\&.GenericBusinessException\&.GetObjectData (SerializationInfo info, StreamingContext context)"

.PP
When overridden in a derived class, sets the T:System\&.Runtime\&.Serialization\&.SerializationInfo with information about the exception\&. 
.PP
\fBParameters\fP
.RS 4
\fIinfo\fP The T:System\&.Runtime\&.Serialization\&.SerializationInfo that holds the serialized object data about the exception being thrown\&.
.br
\fIcontext\fP The T:System\&.Runtime\&.Serialization\&.StreamingContext that contains contextual information about the source or destination\&.
.RE
.PP
\fBExceptions\fP
.RS 4
\fIT:System\&.ArgumentNullException\fP The \fIinfo\fP  parameter is a null reference (Nothing in Visual Basic)\&. 
.RE
.PP
<PermissionSet> <IPermission class='System\&.Security\&.Permissions\&.FileIOPermission, mscorlib, Version=2\&.0\&.3600\&.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' version='1' Read='*AllFiles*' PathDiscovery='*AllFiles*'> <IPermission class='System\&.Security\&.Permissions\&.SecurityPermission, mscorlib, Version=2\&.0\&.3600\&.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' version='1' Flags='SerializationFormatter'> </PermissionSet> 
.PP
Definition at line 131 of file GenericBusinessException\&.cs\&.
.SS "override string Csla\&.Server\&.GenericBusinessException\&.ToString ()"

.PP
Returns a System\&.String that represents this instance\&. 
.PP
\fBReturns\fP
.RS 4
A System\&.String that represents this instance\&. 
.RE
.PP
<PermissionSet> <IPermission class='System\&.Security\&.Permissions\&.FileIOPermission, mscorlib, Version=2\&.0\&.3600\&.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' version='1' PathDiscovery='*AllFiles*'> </PermissionSet> 
.PP
Definition at line 149 of file GenericBusinessException\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "override IDictionary Csla\&.Server\&.GenericBusinessException\&.Data\fC [get]\fP"

.PP
Gets a collection of key/value pairs that provide additional user-defined information about the exception\&. 
.PP
\fBReturns\fP
.RS 4
An object that implements the T:System\&.Collections\&.IDictionary interface and contains a collection of user-defined key/value pairs\&. The default is an empty collection\&.
.RE
.PP

.PP
Definition at line 49 of file GenericBusinessException\&.cs\&.
.SS "override string Csla\&.Server\&.GenericBusinessException\&.StackTrace\fC [get]\fP"

.PP
Gets a string representation of the immediate frames on the call stack\&. 
.PP
\fBReturns\fP
.RS 4
A string that describes the immediate frames of the call stack\&.
.RE
.PP
<PermissionSet> <IPermission class='System\&.Security\&.Permissions\&.FileIOPermission, mscorlib, Version=2\&.0\&.3600\&.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' version='1' PathDiscovery='*AllFiles*'> </PermissionSet> 
.PP
Definition at line 36 of file GenericBusinessException\&.cs\&.
.SS "string Csla\&.Server\&.GenericBusinessException\&.TypeName\fC [get]\fP"

.PP
Gets the name of the type\&. The name of the type\&.
.PP
Definition at line 61 of file GenericBusinessException\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
