.TH "Csla.Core.FieldManager.PropertyInfoList" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Core.FieldManager.PropertyInfoList \- List of \fBIPropertyInfo\fP objects for a business object type\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits List< IPropertyInfo >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPropertyInfoList\fP ()"
.br
.RI "Creates an instance of the object\&. "
.ti -1c
.RI "\fBPropertyInfoList\fP (IList< \fBIPropertyInfo\fP > list)"
.br
.RI "Creates an instance of the object that contains the items in 'list'\&. "
.in -1c
.SH "Detailed Description"
.PP 
List of \fBIPropertyInfo\fP objects for a business object type\&. 


.PP
Definition at line 18 of file PropertyInfoList\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Csla\&.Core\&.FieldManager\&.PropertyInfoList\&.PropertyInfoList ()"

.PP
Creates an instance of the object\&. 
.PP
Definition at line 30 of file PropertyInfoList\&.cs\&.
.SS "Csla\&.Core\&.FieldManager\&.PropertyInfoList\&.PropertyInfoList (IList< \fBIPropertyInfo\fP > list)"

.PP
Creates an instance of the object that contains the items in 'list'\&. 
.PP
\fBParameters\fP
.RS 4
\fIlist\fP Source list\&.
.RE
.PP

.PP
Definition at line 38 of file PropertyInfoList\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
