.TH "Csla.Test.MethodCaller.FieldTests" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.MethodCaller.FieldTests
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBPrivateFieldGetSuccess\fP ()"
.br
.ti -1c
.RI "void \fBPrivateFieldSetFail\fP ()"
.br
.ti -1c
.RI "void \fBPublicFieldGetSuccess\fP ()"
.br
.ti -1c
.RI "void \fBPublicFieldSetSuccess\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 28 of file FieldTests\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Csla\&.Test\&.MethodCaller\&.FieldTests\&.PrivateFieldGetSuccess ()"

.PP
Definition at line 39 of file FieldTests\&.cs\&.
.SS "void Csla\&.Test\&.MethodCaller\&.FieldTests\&.PrivateFieldSetFail ()"

.PP
Definition at line 48 of file FieldTests\&.cs\&.
.SS "void Csla\&.Test\&.MethodCaller\&.FieldTests\&.PublicFieldGetSuccess ()"

.PP
Definition at line 58 of file FieldTests\&.cs\&.
.SS "void Csla\&.Test\&.MethodCaller\&.FieldTests\&.PublicFieldSetSuccess ()"

.PP
Definition at line 67 of file FieldTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
