.TH "cslalighttest.Stereotypes.ReadOnlyListTestsLocalAndRemote" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cslalighttest.Stereotypes.ReadOnlyListTestsLocalAndRemote
.SH SYNOPSIS
.br
.PP
.PP
Inherits TestBase\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "async Task \fBReadOnlyListFetchLocal\fP ()"
.br
.ti -1c
.RI "async Task \fBReadOnlyListFetchRemote\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 29 of file ReadOnlyListTestsLocalAndRemote\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "async Task cslalighttest\&.Stereotypes\&.ReadOnlyListTestsLocalAndRemote\&.ReadOnlyListFetchLocal ()"

.PP
Definition at line 32 of file ReadOnlyListTestsLocalAndRemote\&.cs\&.
.SS "async Task cslalighttest\&.Stereotypes\&.ReadOnlyListTestsLocalAndRemote\&.ReadOnlyListFetchRemote ()"

.PP
Definition at line 41 of file ReadOnlyListTestsLocalAndRemote\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
