.TH "Csla.Core.ISmartField" 3 "Thu Jul 22 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Core.ISmartField \- Defines members required for smart data types that understand the concept of being empty, and representing an empty value as an empty string\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBCsla\&.SmartDate\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBText\fP\fC [get, set]\fP"
.br
.RI "Sets or gets the text representation of the value\&. "
.ti -1c
.RI "bool \fBIsEmpty\fP\fC [get]\fP"
.br
.RI "Gets a value indicating whether the field's value is empty\&. "
.in -1c
.SH "Detailed Description"
.PP 
Defines members required for smart data types that understand the concept of being empty, and representing an empty value as an empty string\&. 


.PP
Definition at line 18 of file ISmartField\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "bool Csla\&.Core\&.ISmartField\&.IsEmpty\fC [get]\fP"

.PP
Gets a value indicating whether the field's value is empty\&. 
.PP
Definition at line 32 of file ISmartField\&.cs\&.
.SS "string Csla\&.Core\&.ISmartField\&.Text\fC [get]\fP, \fC [set]\fP"

.PP
Sets or gets the text representation of the value\&. An empty string indicates an empty value\&. 
.PP
Definition at line 27 of file ISmartField\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
