.TH "Csla.Rules.IBusinessRules" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Rules.IBusinessRules \- Public interfacefor \fBIBusinessRules\fP  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBCsla\&.Rules\&.BusinessRules\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "object \fBTarget\fP\fC [get]\fP"
.br
.RI "Gets the target business object "
.in -1c
.SH "Detailed Description"
.PP 
Public interfacefor \fBIBusinessRules\fP 


.PP
Definition at line 13 of file IBusinessRules\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "object Csla\&.Rules\&.IBusinessRules\&.Target\fC [get]\fP"

.PP
Gets the target business object The business object\&. 
.PP
Definition at line 21 of file IBusinessRules\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
