.TH "Csla.Channels.Grpc" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Channels.Grpc
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBGrpcPortal\fP"
.br
.RI "Exposes server-side \fBDataPortal\fP functionality through gRPC\&. "
.ti -1c
.RI "class \fBGrpcProxy\fP"
.br
.RI "Implements a data portal proxy to relay data portal calls to a remote application server by using gRPC\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
