.TH "Csla.Test.DataPortal.LogicalExecutionDataPortalTests" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.DataPortal.LogicalExecutionDataPortalTests
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBTest_LogicalExecution_Values\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 12 of file LogicalExecutionDataPortalTests\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Csla\&.Test\&.DataPortal\&.LogicalExecutionDataPortalTests\&.Test_LogicalExecution_Values ()"

.PP
Definition at line 15 of file LogicalExecutionDataPortalTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
