.TH "Csla.Test.ObjectFactory.RootFactory3" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.ObjectFactory.RootFactory3
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.Server\&.ObjectFactory\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "object \fBFetch\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 164 of file RootFactory\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "object Csla\&.Test\&.ObjectFactory\&.RootFactory3\&.Fetch ()"

.PP
Definition at line 166 of file RootFactory\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
