.TH "Csla.Windows.HostPropertyAttribute" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Windows.HostPropertyAttribute \- \fBHostPropertyAttribute\fP is used on components to indicate the property on the component that is to be used as the parent container control in conjunction with HostComponentDesigner\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Attribute\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHostPropertyAttribute\fP (string hostPropertyName)"
.br
.RI "Constructor creates a new \fBHostPropertyAttribute\fP object instance using the information supplied\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBHostPropertyName\fP\fC [get]\fP"
.br
.RI "HostPropertyName gets the host property name\&. "
.in -1c
.SH "Detailed Description"
.PP 
\fBHostPropertyAttribute\fP is used on components to indicate the property on the component that is to be used as the parent container control in conjunction with HostComponentDesigner\&. 


.PP
Definition at line 17 of file HostPropertyAttribute\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Csla\&.Windows\&.HostPropertyAttribute\&.HostPropertyAttribute (string hostPropertyName)"

.PP
Constructor creates a new \fBHostPropertyAttribute\fP object instance using the information supplied\&. 
.PP
\fBParameters\fP
.RS 4
\fIhostPropertyName\fP The name of the host property\&.
.RE
.PP

.PP
Definition at line 44 of file HostPropertyAttribute\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "string Csla\&.Windows\&.HostPropertyAttribute\&.HostPropertyName\fC [get]\fP"

.PP
HostPropertyName gets the host property name\&. 
.PP
Definition at line 31 of file HostPropertyAttribute\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
