.TH "Csla.Test.MethodCaller.CreateConstructorTests.TestStruct" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.MethodCaller.CreateConstructorTests.TestStruct
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Definition at line 68 of file CreateConstructorTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
