.TH "Csla.Test.ValidationRules.HasRegEx" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.ValidationRules.HasRegEx
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.BusinessBase< HasRegEx >\fP\&.
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBPropertyInfo\fP< string > \fBSsnProperty\fP = RegisterProperty<string>(c => c\&.Ssn)"
.br
.ti -1c
.RI "static \fBPropertyInfo\fP< string > \fBSsn2Property\fP = RegisterProperty<string>(c => c\&.Ssn2)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBAddBusinessRules\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBSsn\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBSsn2\fP\fC [get, set]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 14 of file HasRegEx\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override void Csla\&.Test\&.ValidationRules\&.HasRegEx\&.AddBusinessRules ()\fC [protected]\fP"

.PP
Definition at line 30 of file HasRegEx\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBPropertyInfo\fP<string> Csla\&.Test\&.ValidationRules\&.HasRegEx\&.Ssn2Property = RegisterProperty<string>(c => c\&.Ssn2)\fC [static]\fP"

.PP
Definition at line 23 of file HasRegEx\&.cs\&.
.SS "\fBPropertyInfo\fP<string> Csla\&.Test\&.ValidationRules\&.HasRegEx\&.SsnProperty = RegisterProperty<string>(c => c\&.Ssn)\fC [static]\fP"

.PP
Definition at line 16 of file HasRegEx\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "string Csla\&.Test\&.ValidationRules\&.HasRegEx\&.Ssn\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 17 of file HasRegEx\&.cs\&.
.SS "string Csla\&.Test\&.ValidationRules\&.HasRegEx\&.Ssn2\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 24 of file HasRegEx\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
