.TH "Csla.Test.ValidationRules" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.ValidationRules
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRootThrowsException\fP"
.br
.ti -1c
.RI "class \fBAsyncRuleRoot\fP"
.br
.ti -1c
.RI "class \fBAsyncRuleTests\fP"
.br
.ti -1c
.RI "class \fBBrokenRulesMergeRoot\fP"
.br
.ti -1c
.RI "class \fBCascadeRoot\fP"
.br
.ti -1c
.RI "class \fBCheckSumRule\fP"
.br
.ti -1c
.RI "class \fBIncrement\fP"
.br
.ti -1c
.RI "class \fBCopyValueRule\fP"
.br
.ti -1c
.RI "class \fBCalculateFractionRule\fP"
.br
.ti -1c
.RI "class \fBCalcSumRule\fP"
.br
.ti -1c
.RI "class \fBIncrementNotAffected\fP"
.br
.ti -1c
.RI "class \fBCascadeTests\fP"
.br
.ti -1c
.RI "class \fBChild\fP"
.br
.ti -1c
.RI "class \fBChildList\fP"
.br
.ti -1c
.RI "class \fBHasAsyncRule\fP"
.br
.ti -1c
.RI "class \fBHasBadSharedRule\fP"
.br
.ti -1c
.RI "class \fBHasChildren\fP"
.br
.ti -1c
.RI "class \fBHasInvalidAsyncRule\fP"
.br
.ti -1c
.RI "class \fBHasLambdaRules\fP"
.br
.ti -1c
.RI "class \fBHasPerTypeRules\fP"
.br
.ti -1c
.RI "class \fBHasPerTypeRules2\fP"
.br
.ti -1c
.RI "class \fBHasOnlyPerTypeRules\fP"
.br
.ti -1c
.RI "class \fBHasRuleSetRules\fP"
.br
.ti -1c
.RI "class \fBPerTypeTests\fP"
.br
.ti -1c
.RI "class \fBHasRegEx\fP"
.br
.ti -1c
.RI "class \fBHasRulesManager\fP"
.br
.ti -1c
.RI "class \fBHasRulesManager2\fP"
.br
.ti -1c
.RI "class \fBRuleBaseClassesRoot\fP"
.br
.ti -1c
.RI "class \fBCalcSum\fP"
.br
.RI "\fBCalcSum\fP rule will set primary property to the sum of all\&. "
.ti -1c
.RI "class \fBValidateRootObject\fP"
.br
.ti -1c
.RI "class \fBLessThan\fP"
.br
.RI "Implements a rule to compare 2 property values and make sure property1 is less than property2 "
.ti -1c
.RI "class \fBLookupCustomer\fP"
.br
.ti -1c
.RI "class \fBRuleBaseClassesTests\fP"
.br
.RI "This is a test class for RootTest and is intended to contain all RootTest Unit Tests /summary> "
.ti -1c
.RI "class \fBRuleDescriptionTests\fP"
.br
.ti -1c
.RI "class \fBRuleTestClass\fP"
.br
.ti -1c
.RI "class \fBMyRule\fP"
.br
.ti -1c
.RI "class \fBRuleTests\fP"
.br
.ti -1c
.RI "class \fBAddressEdit\fP"
.br
.ti -1c
.RI "class \fBGenericRule\fP"
.br
.ti -1c
.RI "class \fBRuleURITests\fP"
.br
.ti -1c
.RI "class \fBSeverityRoot\fP"
.br
.ti -1c
.RI "class \fBNoErrorRoot\fP"
.br
.ti -1c
.RI "class \fBSeverityTests\fP"
.br
.ti -1c
.RI "class \fBShortCircuit\fP"
.br
.ti -1c
.RI "class \fBShortCircuitTests\fP"
.br
.ti -1c
.RI "class \fBValidationTests\fP"
.br
.ti -1c
.RI "class \fBHasBadRule\fP"
.br
.ti -1c
.RI "class \fBHasPrivateFields\fP"
.br
.ti -1c
.RI "class \fBUsesCommonRules\fP"
.br
.ti -1c
.RI "class \fBMinMaxNullableRules\fP"
.br
.ti -1c
.RI "class \fBTwoPropertyRules\fP"
.br
.ti -1c
.RI "class \fBTwoProps\fP"
.br
.ti -1c
.RI "class \fBHasLazyField\fP"
.br
.ti -1c
.RI "class \fBDirtyAfterOutValueChangesProperty\fP"
.br
.ti -1c
.RI "class \fBCheckLazyInputFieldExists\fP"
.br
.ti -1c
.RI "class \fBRuleContextTests\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
