.TH "cslalighttest.CslaDataProvider" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cslalighttest.CslaDataProvider
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCustomer\fP"
.br
.ti -1c
.RI "class \fBCustomerWO_DP_XYZ\fP"
.br
.ti -1c
.RI "class \fBCustomerContact\fP"
.br
.ti -1c
.RI "class \fBCustomerContactList\fP"
.br
.ti -1c
.RI "class \fBCustomerList\fP"
.br
.ti -1c
.RI "class \fBCustomerWithError\fP"
.br
.ti -1c
.RI "class \fBCustomerWithErrorWO_DP_XYZ\fP"
.br
.ti -1c
.RI "class \fBCustomerWithErrorList\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum class \fBCustomeType\fP { \fBActive\fP, \fBInactive\fP }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBcslalighttest\&.CslaDataProvider\&.CustomeType\fP\fC [strong]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIActive \fP\fP
.TP
\fB\fIInactive \fP\fP
.PP
Definition at line 20 of file Customer\&.cs\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
