.TH "Csla.Test.DataAnnotations.TestRuleAttribute" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.DataAnnotations.TestRuleAttribute
.SH SYNOPSIS
.br
.PP
.PP
Inherits ValidationAttribute\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override ValidationResult \fBIsValid\fP (object value, ValidationContext validationContext)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 179 of file DataAnnotationsTests\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override ValidationResult Csla\&.Test\&.DataAnnotations\&.TestRuleAttribute\&.IsValid (object value, ValidationContext validationContext)\fC [protected]\fP"

.PP
Definition at line 181 of file DataAnnotationsTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
