.TH "Csla.Configuration.ConnectionStringSettings" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Configuration.ConnectionStringSettings \- Information about a connection string  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBConnectionStringSettings\fP ()"
.br
.RI "Creates an instance of the type\&. "
.ti -1c
.RI "\fBConnectionStringSettings\fP (System\&.Configuration\&.ConnectionStringSettings source)"
.br
.RI "Creates an instance of the type\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBName\fP\fC [get, set]\fP"
.br
.RI "Gets or sets the connection name\&. "
.ti -1c
.RI "string \fBConnectionString\fP\fC [get, set]\fP"
.br
.RI "Gets or sets the connection string text\&. "
.ti -1c
.RI "string \fBProviderName\fP\fC [get, set]\fP"
.br
.RI "Gets or sets the provider name\&. "
.in -1c
.SH "Detailed Description"
.PP 
Information about a connection string 


.PP
Definition at line 16 of file ConnectionStringSettings\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Csla\&.Configuration\&.ConnectionStringSettings\&.ConnectionStringSettings ()"

.PP
Creates an instance of the type\&. 
.PP
Definition at line 21 of file ConnectionStringSettings\&.cs\&.
.SS "Csla\&.Configuration\&.ConnectionStringSettings\&.ConnectionStringSettings (System\&.Configuration\&.ConnectionStringSettings source)"

.PP
Creates an instance of the type\&. 
.PP
Definition at line 28 of file ConnectionStringSettings\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "string Csla\&.Configuration\&.ConnectionStringSettings\&.ConnectionString\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the connection string text\&. 
.PP
Definition at line 43 of file ConnectionStringSettings\&.cs\&.
.SS "string Csla\&.Configuration\&.ConnectionStringSettings\&.Name\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the connection name\&. 
.PP
Definition at line 39 of file ConnectionStringSettings\&.cs\&.
.SS "string Csla\&.Configuration\&.ConnectionStringSettings\&.ProviderName\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the provider name\&. 
.PP
Definition at line 47 of file ConnectionStringSettings\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
