.TH "Csla.Test.MethodCaller.Caller3" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.MethodCaller.Caller3
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.Test\&.MethodCaller\&.Caller2\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 15 of file Caller3\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
