.TH "Csla.CommandBase< T >" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.CommandBase< T > \- This is the base class from which command objects will be derived\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.Core\&.ManagedObjectBase\fP, \fBCsla\&.Core\&.ICommandObject\fP, ICloneable, Csla\&.Server\&.IDataPortalTarget, Csla\&.Core\&.IManageProperties, and \fBCsla\&.ICommandBase\fP\&.
.PP
Inherited by \fBCsla\&.Test\&.DataPortal\&.PrivateMethodBase< T >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCommandBase\fP ()"
.br
.RI "Creates an instance of the object\&. "
.ti -1c
.RI "T \fBClone\fP ()"
.br
.RI "Creates a clone of the object\&. "
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBInitialize\fP ()"
.br
.RI "Override this method to set up event handlers so user code in a partial class can respond to events raised by generated code\&. "
.ti -1c
.RI "virtual void \fBDataPortal_OnDataPortalInvoke\fP (\fBDataPortalEventArgs\fP e)"
.br
.RI "Called by the server-side \fBDataPortal\fP prior to calling the requested DataPortal_xyz method\&. "
.ti -1c
.RI "virtual void \fBDataPortal_OnDataPortalInvokeComplete\fP (\fBDataPortalEventArgs\fP e)"
.br
.RI "Called by the server-side \fBDataPortal\fP after calling the requested DataPortal_xyz method\&. "
.ti -1c
.RI "virtual void \fBDataPortal_OnDataPortalException\fP (\fBDataPortalEventArgs\fP e, Exception ex)"
.br
.RI "Called by the server-side \fBDataPortal\fP if an exception occurs during server-side processing\&. "
.ti -1c
.RI "virtual object \fBGetClone\fP ()"
.br
.RI "Creates a clone of the object\&. "
.in -1c
.SS "Static Protected Member Functions"

.in +1c
.ti -1c
.RI "static \fBPropertyInfo\fP< P > \fBRegisterProperty< P >\fP (\fBPropertyInfo\fP< P > info)"
.br
.RI "Indicates that the specified property belongs to the business object type\&. "
.ti -1c
.RI "static \fBPropertyInfo\fP< P > \fBRegisterProperty< P >\fP (string propertyName)"
.br
.RI "Indicates that the specified property belongs to the business object type\&. "
.ti -1c
.RI "static \fBPropertyInfo\fP< P > \fBRegisterProperty< P >\fP (Expression< Func< T, object >> propertyLambdaExpression)"
.br
.RI "Indicates that the specified property belongs to the business object type\&. "
.ti -1c
.RI "static \fBPropertyInfo\fP< P > \fBRegisterProperty< P >\fP (Expression< Func< T, object >> propertyLambdaExpression, P defaultValue)"
.br
.RI "Indicates that the specified property belongs to the business object type\&. "
.ti -1c
.RI "static \fBPropertyInfo\fP< P > \fBRegisterProperty< P >\fP (string propertyName, \fBRelationshipTypes\fP relationship)"
.br
.RI "Indicates that the specified property belongs to the business object type\&. "
.ti -1c
.RI "static \fBPropertyInfo\fP< P > \fBRegisterProperty< P >\fP (Expression< Func< T, object >> propertyLambdaExpression, \fBRelationshipTypes\fP relationship)"
.br
.RI "Indicates that the specified property belongs to the business object type\&. "
.ti -1c
.RI "static \fBPropertyInfo\fP< P > \fBRegisterProperty< P >\fP (string propertyName, string friendlyName)"
.br
.RI "Indicates that the specified property belongs to the business object type\&. "
.ti -1c
.RI "static \fBPropertyInfo\fP< P > \fBRegisterProperty< P >\fP (Expression< Func< T, object >> propertyLambdaExpression, string friendlyName)"
.br
.RI "Indicates that the specified property belongs to the business object type\&. "
.ti -1c
.RI "static \fBPropertyInfo\fP< P > \fBRegisterProperty< P >\fP (Expression< Func< T, object >> propertyLambdaExpression, string friendlyName, \fBRelationshipTypes\fP relationship)"
.br
.RI "Indicates that the specified property belongs to the business object type\&. "
.ti -1c
.RI "static \fBPropertyInfo\fP< P > \fBRegisterProperty< P >\fP (string propertyName, string friendlyName, P defaultValue)"
.br
.RI "Indicates that the specified property belongs to the business object type\&. "
.ti -1c
.RI "static \fBPropertyInfo\fP< P > \fBRegisterProperty< P >\fP (Expression< Func< T, object >> propertyLambdaExpression, string friendlyName, P defaultValue)"
.br
.RI "Indicates that the specified property belongs to the business object type\&. "
.ti -1c
.RI "static \fBPropertyInfo\fP< P > \fBRegisterProperty< P >\fP (string propertyName, string friendlyName, P defaultValue, \fBRelationshipTypes\fP relationship)"
.br
.RI "Indicates that the specified property belongs to the business object type\&. "
.ti -1c
.RI "static \fBPropertyInfo\fP< P > \fBRegisterProperty< P >\fP (Expression< Func< T, object >> propertyLambdaExpression, string friendlyName, P defaultValue, \fBRelationshipTypes\fP relationship)"
.br
.RI "Indicates that the specified property belongs to the business object type\&. "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
This is the base class from which command objects will be derived\&. 

Command objects allow the execution of arbitrary server-side functionality\&. Most often, this involves the invocation of a stored procedure in the database, but can involve any other type of stateless, atomic call to the server instead\&. 
.PP
To implement a command object, inherit from \fBCommandBase\fP and override the DataPortal_Execute method\&. In this method you can implement any server-side code as required\&. 
.PP
To pass data to/from the server, use instance variables within the command object itself\&. The command object is instantiated on the client, and is passed by value to the server where the DataPortal_Execute method is invoked\&. The command object is then returned to the client by value\&. 
.PP
\fBType Constraints\fP
.TP
\fIT\fP : \fI\fBCommandBase\fP<T>\fP
.PP
Definition at line 46 of file CommandBase\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBCsla\&.CommandBase\fP< T >\&.\fBCommandBase\fP ()"

.PP
Creates an instance of the object\&. 
.PP
Definition at line 55 of file CommandBase\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "T \fBCsla\&.CommandBase\fP< T >\&.Clone ()"

.PP
Creates a clone of the object\&. 
.PP
\fBReturns\fP
.RS 4
A new object containing the exact data of the original object\&. 
.RE
.PP

.PP
Definition at line 219 of file CommandBase\&.cs\&.
.SS "virtual void \fBCsla\&.CommandBase\fP< T >\&.DataPortal_OnDataPortalException (\fBDataPortalEventArgs\fP e, Exception ex)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Called by the server-side \fBDataPortal\fP if an exception occurs during server-side processing\&. 
.PP
\fBParameters\fP
.RS 4
\fIe\fP The DataPortalContext object passed to the \fBDataPortal\fP\&.
.br
\fIex\fP The Exception thrown during processing\&.
.RE
.PP

.PP
Definition at line 147 of file CommandBase\&.cs\&.
.SS "virtual void \fBCsla\&.CommandBase\fP< T >\&.DataPortal_OnDataPortalInvoke (\fBDataPortalEventArgs\fP e)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Called by the server-side \fBDataPortal\fP prior to calling the requested DataPortal_xyz method\&. 
.PP
\fBParameters\fP
.RS 4
\fIe\fP The DataPortalContext object passed to the \fBDataPortal\fP\&.
.RE
.PP

.PP
Definition at line 122 of file CommandBase\&.cs\&.
.SS "virtual void \fBCsla\&.CommandBase\fP< T >\&.DataPortal_OnDataPortalInvokeComplete (\fBDataPortalEventArgs\fP e)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Called by the server-side \fBDataPortal\fP after calling the requested DataPortal_xyz method\&. 
.PP
\fBParameters\fP
.RS 4
\fIe\fP The DataPortalContext object passed to the \fBDataPortal\fP\&.
.RE
.PP

.PP
Definition at line 134 of file CommandBase\&.cs\&.
.SS "virtual object \fBCsla\&.CommandBase\fP< T >\&.GetClone ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Creates a clone of the object\&. 
.PP
\fBReturns\fP
.RS 4
A new object containing the exact data of the original object\&. 
.RE
.PP

.PP
Definition at line 208 of file CommandBase\&.cs\&.
.SS "virtual void \fBCsla\&.CommandBase\fP< T >\&.Initialize ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Override this method to set up event handlers so user code in a partial class can respond to events raised by generated code\&. 
.PP
Definition at line 67 of file CommandBase\&.cs\&.
.SS "static \fBPropertyInfo\fP<P> \fBCsla\&.CommandBase\fP< T >\&.RegisterProperty< P > (Expression< Func< T, object >> propertyLambdaExpression)\fC [static]\fP, \fC [protected]\fP"

.PP
Indicates that the specified property belongs to the business object type\&. 
.PP
\fBTemplate Parameters\fP
.RS 4
\fIP\fP Type of property
.RE
.PP
\fBParameters\fP
.RS 4
\fIpropertyLambdaExpression\fP Property Expression
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
Definition at line 265 of file CommandBase\&.cs\&.
.SS "static \fBPropertyInfo\fP<P> \fBCsla\&.CommandBase\fP< T >\&.RegisterProperty< P > (Expression< Func< T, object >> propertyLambdaExpression, P defaultValue)\fC [static]\fP, \fC [protected]\fP"

.PP
Indicates that the specified property belongs to the business object type\&. 
.PP
\fBTemplate Parameters\fP
.RS 4
\fIP\fP Type of property
.RE
.PP
\fBParameters\fP
.RS 4
\fIpropertyLambdaExpression\fP Property Expression
.br
\fIdefaultValue\fP Default Value for the property
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
Definition at line 280 of file CommandBase\&.cs\&.
.SS "static \fBPropertyInfo\fP<P> \fBCsla\&.CommandBase\fP< T >\&.RegisterProperty< P > (Expression< Func< T, object >> propertyLambdaExpression, \fBRelationshipTypes\fP relationship)\fC [static]\fP, \fC [protected]\fP"

.PP
Indicates that the specified property belongs to the business object type\&. 
.PP
\fBTemplate Parameters\fP
.RS 4
\fIP\fP Type of property
.RE
.PP
\fBParameters\fP
.RS 4
\fIpropertyLambdaExpression\fP Property Expression
.br
\fIrelationship\fP Relationship with property value\&.
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
Definition at line 308 of file CommandBase\&.cs\&.
.SS "static \fBPropertyInfo\fP<P> \fBCsla\&.CommandBase\fP< T >\&.RegisterProperty< P > (Expression< Func< T, object >> propertyLambdaExpression, string friendlyName)\fC [static]\fP, \fC [protected]\fP"

.PP
Indicates that the specified property belongs to the business object type\&. 
.PP
\fBTemplate Parameters\fP
.RS 4
\fIP\fP Type of property
.RE
.PP
\fBParameters\fP
.RS 4
\fIpropertyLambdaExpression\fP Property Expression
.br
\fIfriendlyName\fP Friendly description for a property to be used in databinding
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
Definition at line 335 of file CommandBase\&.cs\&.
.SS "static \fBPropertyInfo\fP<P> \fBCsla\&.CommandBase\fP< T >\&.RegisterProperty< P > (Expression< Func< T, object >> propertyLambdaExpression, string friendlyName, P defaultValue)\fC [static]\fP, \fC [protected]\fP"

.PP
Indicates that the specified property belongs to the business object type\&. 
.PP
\fBTemplate Parameters\fP
.RS 4
\fIP\fP Type of property
.RE
.PP
\fBParameters\fP
.RS 4
\fIpropertyLambdaExpression\fP Property Expression
.br
\fIfriendlyName\fP Friendly description for a property to be used in databinding
.br
\fIdefaultValue\fP Default Value for the property
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
Definition at line 381 of file CommandBase\&.cs\&.
.SS "static \fBPropertyInfo\fP<P> \fBCsla\&.CommandBase\fP< T >\&.RegisterProperty< P > (Expression< Func< T, object >> propertyLambdaExpression, string friendlyName, P defaultValue, \fBRelationshipTypes\fP relationship)\fC [static]\fP, \fC [protected]\fP"

.PP
Indicates that the specified property belongs to the business object type\&. 
.PP
\fBTemplate Parameters\fP
.RS 4
\fIP\fP Type of property
.RE
.PP
\fBParameters\fP
.RS 4
\fIpropertyLambdaExpression\fP Property Expression
.br
\fIfriendlyName\fP Friendly description for a property to be used in databinding
.br
\fIdefaultValue\fP Default Value for the property
.br
\fIrelationship\fP Relationship with property value\&.
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
Definition at line 412 of file CommandBase\&.cs\&.
.SS "static \fBPropertyInfo\fP<P> \fBCsla\&.CommandBase\fP< T >\&.RegisterProperty< P > (Expression< Func< T, object >> propertyLambdaExpression, string friendlyName, \fBRelationshipTypes\fP relationship)\fC [static]\fP, \fC [protected]\fP"

.PP
Indicates that the specified property belongs to the business object type\&. 
.PP
\fBTemplate Parameters\fP
.RS 4
\fIP\fP Type of property
.RE
.PP
\fBParameters\fP
.RS 4
\fIpropertyLambdaExpression\fP Property Expression
.br
\fIfriendlyName\fP Friendly description for a property to be used in databinding
.br
\fIrelationship\fP Relationship with property value\&.
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
Definition at line 351 of file CommandBase\&.cs\&.
.SS "static \fBPropertyInfo\fP<P> \fBCsla\&.CommandBase\fP< T >\&.RegisterProperty< P > (\fBPropertyInfo\fP< P > info)\fC [static]\fP, \fC [protected]\fP"

.PP
Indicates that the specified property belongs to the business object type\&. 
.PP
\fBTemplate Parameters\fP
.RS 4
\fIP\fP Type of property\&. 
.RE
.PP
\fBParameters\fP
.RS 4
\fIinfo\fP \fBPropertyInfo\fP object for the property\&. 
.RE
.PP
\fBReturns\fP
.RS 4
The provided IPropertyInfo object\&. 
.RE
.PP

.PP
Definition at line 241 of file CommandBase\&.cs\&.
.SS "static \fBPropertyInfo\fP<P> \fBCsla\&.CommandBase\fP< T >\&.RegisterProperty< P > (string propertyName)\fC [static]\fP, \fC [protected]\fP"

.PP
Indicates that the specified property belongs to the business object type\&. 
.PP
\fBTemplate Parameters\fP
.RS 4
\fIP\fP Type of property
.RE
.PP
\fBParameters\fP
.RS 4
\fIpropertyName\fP Property name from nameof()
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
Definition at line 253 of file CommandBase\&.cs\&.
.SS "static \fBPropertyInfo\fP<P> \fBCsla\&.CommandBase\fP< T >\&.RegisterProperty< P > (string propertyName, \fBRelationshipTypes\fP relationship)\fC [static]\fP, \fC [protected]\fP"

.PP
Indicates that the specified property belongs to the business object type\&. 
.PP
\fBTemplate Parameters\fP
.RS 4
\fIP\fP Type of property
.RE
.PP
\fBParameters\fP
.RS 4
\fIpropertyName\fP Property name from nameof()
.br
\fIrelationship\fP Relationship with property value\&.
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
Definition at line 295 of file CommandBase\&.cs\&.
.SS "static \fBPropertyInfo\fP<P> \fBCsla\&.CommandBase\fP< T >\&.RegisterProperty< P > (string propertyName, string friendlyName)\fC [static]\fP, \fC [protected]\fP"

.PP
Indicates that the specified property belongs to the business object type\&. 
.PP
\fBTemplate Parameters\fP
.RS 4
\fIP\fP Type of property
.RE
.PP
\fBParameters\fP
.RS 4
\fIpropertyName\fP Property name from nameof()
.br
\fIfriendlyName\fP Friendly description for a property to be used in databinding
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
Definition at line 322 of file CommandBase\&.cs\&.
.SS "static \fBPropertyInfo\fP<P> \fBCsla\&.CommandBase\fP< T >\&.RegisterProperty< P > (string propertyName, string friendlyName, P defaultValue)\fC [static]\fP, \fC [protected]\fP"

.PP
Indicates that the specified property belongs to the business object type\&. 
.PP
\fBTemplate Parameters\fP
.RS 4
\fIP\fP Type of property
.RE
.PP
\fBParameters\fP
.RS 4
\fIpropertyName\fP Property name from nameof()
.br
\fIfriendlyName\fP Friendly description for a property to be used in databinding
.br
\fIdefaultValue\fP Default Value for the property
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
Definition at line 367 of file CommandBase\&.cs\&.
.SS "static \fBPropertyInfo\fP<P> \fBCsla\&.CommandBase\fP< T >\&.RegisterProperty< P > (string propertyName, string friendlyName, P defaultValue, \fBRelationshipTypes\fP relationship)\fC [static]\fP, \fC [protected]\fP"

.PP
Indicates that the specified property belongs to the business object type\&. 
.PP
\fBTemplate Parameters\fP
.RS 4
\fIP\fP Type of property
.RE
.PP
\fBParameters\fP
.RS 4
\fIpropertyName\fP Property name from nameof()
.br
\fIfriendlyName\fP Friendly description for a property to be used in databinding
.br
\fIdefaultValue\fP Default Value for the property
.br
\fIrelationship\fP Relationship with property value\&.
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
Definition at line 397 of file CommandBase\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
