.TH "Csla.Test.Serialization.nonSerializableEventHandler" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.Serialization.nonSerializableEventHandler
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBReg\fP (\fBCsla\&.Core\&.BusinessBase\fP obj)"
.br
.ti -1c
.RI "void \fBobj_PropertyChanged\fP (object sender, System\&.ComponentModel\&.PropertyChangedEventArgs e)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 14 of file nonSerializableEventHandler\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Csla\&.Test\&.Serialization\&.nonSerializableEventHandler\&.obj_PropertyChanged (object sender, System\&.ComponentModel\&.PropertyChangedEventArgs e)"

.PP
Definition at line 23 of file nonSerializableEventHandler\&.cs\&.
.SS "void Csla\&.Test\&.Serialization\&.nonSerializableEventHandler\&.Reg (\fBCsla\&.Core\&.BusinessBase\fP obj)"

.PP
Definition at line 18 of file nonSerializableEventHandler\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
