.TH "Csla.Validation.CommonRules.MinValueRuleArgs< T >" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Validation.CommonRules.MinValueRuleArgs< T > \- Custom \fBRuleArgs\fP object required by the \fBMinValue\fP rule method\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.Validation\&.DecoratedRuleArgs\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMinValueRuleArgs\fP (string propertyName, T minValue)"
.br
.RI "Create a new object\&. "
.ti -1c
.RI "\fBMinValueRuleArgs\fP (\fBCore\&.IPropertyInfo\fP propertyInfo, T minValue)"
.br
.RI "Create a new object\&. "
.ti -1c
.RI "\fBMinValueRuleArgs\fP (string propertyName, string friendlyName, T minValue)"
.br
.RI "Create a new object\&. "
.ti -1c
.RI "\fBMinValueRuleArgs\fP (string propertyName, T minValue, string format)"
.br
.RI "Create a new object\&. "
.ti -1c
.RI "\fBMinValueRuleArgs\fP (\fBCore\&.IPropertyInfo\fP propertyInfo, T minValue, string format)"
.br
.RI "Create a new object\&. "
.ti -1c
.RI "\fBMinValueRuleArgs\fP (string propertyName, string friendlyName, T minValue, string format)"
.br
.RI "Create a new object\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "T \fBMinValue\fP\fC [get]\fP"
.br
.RI "Get the min value for the property\&. "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Custom \fBRuleArgs\fP object required by the \fBMinValue\fP rule method\&. 


.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP Type of the property to validate\&.
.RE
.PP

.PP
Definition at line 794 of file Csla\&.Validation\&.Shared/CommonRules\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBCsla\&.Validation\&.CommonRules\&.MinValueRuleArgs\fP< T >\&.\fBMinValueRuleArgs\fP (string propertyName, T minValue)"

.PP
Create a new object\&. 
.PP
\fBParameters\fP
.RS 4
\fIpropertyName\fP Name of the property\&.
.br
\fIminValue\fP Minimum allowed value for the property\&.
.RE
.PP

.PP
Definition at line 809 of file Csla\&.Validation\&.Shared/CommonRules\&.cs\&.
.SS "\fBCsla\&.Validation\&.CommonRules\&.MinValueRuleArgs\fP< T >\&.\fBMinValueRuleArgs\fP (\fBCore\&.IPropertyInfo\fP propertyInfo, T minValue)"

.PP
Create a new object\&. 
.PP
\fBParameters\fP
.RS 4
\fIpropertyInfo\fP Property to validate\&.
.br
\fIminValue\fP Minimum allowed value for the property\&.
.RE
.PP

.PP
Definition at line 822 of file Csla\&.Validation\&.Shared/CommonRules\&.cs\&.
.SS "\fBCsla\&.Validation\&.CommonRules\&.MinValueRuleArgs\fP< T >\&.\fBMinValueRuleArgs\fP (string propertyName, string friendlyName, T minValue)"

.PP
Create a new object\&. 
.PP
\fBParameters\fP
.RS 4
\fIpropertyName\fP Name of the property\&.
.br
\fIfriendlyName\fP A friendly name for the property, which will be used in place of the property name when creating the broken rule description string\&.
.br
\fIminValue\fP Minimum allowed value for the property\&.
.RE
.PP

.PP
Definition at line 838 of file Csla\&.Validation\&.Shared/CommonRules\&.cs\&.
.SS "\fBCsla\&.Validation\&.CommonRules\&.MinValueRuleArgs\fP< T >\&.\fBMinValueRuleArgs\fP (string propertyName, T minValue, string format)"

.PP
Create a new object\&. 
.PP
\fBParameters\fP
.RS 4
\fIpropertyName\fP Name of the property\&.
.br
\fIminValue\fP Minimum allowed value for the property\&.
.br
\fIformat\fP Format string for the min value value in the broken rule string\&.
.RE
.PP

.PP
Definition at line 854 of file Csla\&.Validation\&.Shared/CommonRules\&.cs\&.
.SS "\fBCsla\&.Validation\&.CommonRules\&.MinValueRuleArgs\fP< T >\&.\fBMinValueRuleArgs\fP (\fBCore\&.IPropertyInfo\fP propertyInfo, T minValue, string format)"

.PP
Create a new object\&. 
.PP
\fBParameters\fP
.RS 4
\fIpropertyInfo\fP Property to validate\&.
.br
\fIminValue\fP Minimum allowed value for the property\&.
.br
\fIformat\fP Format string for the min value value in the broken rule string\&.
.RE
.PP

.PP
Definition at line 869 of file Csla\&.Validation\&.Shared/CommonRules\&.cs\&.
.SS "\fBCsla\&.Validation\&.CommonRules\&.MinValueRuleArgs\fP< T >\&.\fBMinValueRuleArgs\fP (string propertyName, string friendlyName, T minValue, string format)"

.PP
Create a new object\&. 
.PP
\fBParameters\fP
.RS 4
\fIpropertyName\fP Name of the property\&.
.br
\fIfriendlyName\fP A friendly name for the property, which will be used in place of the property name when creating the broken rule description string\&.
.br
\fIminValue\fP Minimum allowed value for the property\&.
.br
\fIformat\fP Format string for the min value value in the broken rule string\&.
.RE
.PP

.PP
Definition at line 887 of file Csla\&.Validation\&.Shared/CommonRules\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "T \fBCsla\&.Validation\&.CommonRules\&.MinValueRuleArgs\fP< T >\&.MinValue\fC [get]\fP"

.PP
Get the min value for the property\&. 
.PP
Definition at line 799 of file Csla\&.Validation\&.Shared/CommonRules\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
