.TH "Csla.DataPortalClient.IWcfPortal" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.DataPortalClient.IWcfPortal
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBWcfResponse\fP \fBCreate\fP (\fBCreateRequest\fP request)"
.br
.ti -1c
.RI "System\&.Threading\&.Tasks\&.Task< \fBWcfResponse\fP > \fBCreateAsync\fP (\fBCreateRequest\fP request)"
.br
.ti -1c
.RI "\fBWcfResponse\fP \fBFetch\fP (\fBFetchRequest\fP request)"
.br
.ti -1c
.RI "System\&.Threading\&.Tasks\&.Task< \fBWcfResponse\fP > \fBFetchAsync\fP (\fBFetchRequest\fP request)"
.br
.ti -1c
.RI "\fBWcfResponse\fP \fBUpdate\fP (\fBUpdateRequest\fP request)"
.br
.ti -1c
.RI "System\&.Threading\&.Tasks\&.Task< \fBWcfResponse\fP > \fBUpdateAsync\fP (\fBUpdateRequest\fP request)"
.br
.ti -1c
.RI "\fBWcfResponse\fP \fBDelete\fP (\fBDeleteRequest\fP request)"
.br
.ti -1c
.RI "System\&.Threading\&.Tasks\&.Task< \fBWcfResponse\fP > \fBDeleteAsync\fP (\fBDeleteRequest\fP request)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 14 of file IWcfPortal\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBWcfResponse\fP Csla\&.DataPortalClient\&.IWcfPortal\&.Create (\fBCreateRequest\fP request)"

.SS "System\&.Threading\&.Tasks\&.Task<\fBWcfResponse\fP> Csla\&.DataPortalClient\&.IWcfPortal\&.CreateAsync (\fBCreateRequest\fP request)"

.SS "\fBWcfResponse\fP Csla\&.DataPortalClient\&.IWcfPortal\&.Delete (\fBDeleteRequest\fP request)"

.SS "System\&.Threading\&.Tasks\&.Task<\fBWcfResponse\fP> Csla\&.DataPortalClient\&.IWcfPortal\&.DeleteAsync (\fBDeleteRequest\fP request)"

.SS "\fBWcfResponse\fP Csla\&.DataPortalClient\&.IWcfPortal\&.Fetch (\fBFetchRequest\fP request)"

.SS "System\&.Threading\&.Tasks\&.Task<\fBWcfResponse\fP> Csla\&.DataPortalClient\&.IWcfPortal\&.FetchAsync (\fBFetchRequest\fP request)"

.SS "\fBWcfResponse\fP Csla\&.DataPortalClient\&.IWcfPortal\&.Update (\fBUpdateRequest\fP request)"

.SS "System\&.Threading\&.Tasks\&.Task<\fBWcfResponse\fP> Csla\&.DataPortalClient\&.IWcfPortal\&.UpdateAsync (\fBUpdateRequest\fP request)"


.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
