.TH "Csla.Xaml.IdentityConverter" 3 "Thu Jul 22 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Xaml.IdentityConverter \- Provides the functionality of a WPF value converter without affecting the value as it flows to and from the UI\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits IValueConverter\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "object \fBConvert\fP (object value, Type targetType, object parameter, System\&.Globalization\&.CultureInfo culture)"
.br
.RI "Returns the unchanged value\&. "
.ti -1c
.RI "object \fBConvertBack\fP (object value, Type targetType, object parameter, System\&.Globalization\&.CultureInfo culture)"
.br
.RI "Returns the unchanged value\&. "
.in -1c
.SH "Detailed Description"
.PP 
Provides the functionality of a WPF value converter without affecting the value as it flows to and from the UI\&. 


.PP
Definition at line 19 of file IdentityConverter\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "object Csla\&.Xaml\&.IdentityConverter\&.Convert (object value, Type targetType, object parameter, System\&.Globalization\&.CultureInfo culture)"

.PP
Returns the unchanged value\&. 
.PP
\fBParameters\fP
.RS 4
\fIvalue\fP Value to be converted\&.
.br
\fItargetType\fP Desired value type\&.
.br
\fIparameter\fP Conversion parameter\&.
.br
\fIculture\fP Conversion culture\&.
.RE
.PP

.PP
Definition at line 30 of file IdentityConverter\&.cs\&.
.SS "object Csla\&.Xaml\&.IdentityConverter\&.ConvertBack (object value, Type targetType, object parameter, System\&.Globalization\&.CultureInfo culture)"

.PP
Returns the unchanged value\&. 
.PP
\fBParameters\fP
.RS 4
\fIvalue\fP Value to be converted\&.
.br
\fItargetType\fP Desired value type\&.
.br
\fIparameter\fP Conversion parameter\&.
.br
\fIculture\fP Conversion culture\&.
.RE
.PP

.PP
Definition at line 44 of file IdentityConverter\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
