.TH "Csla.Test.GraphMerge.GraphMergerTests" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.GraphMerge.GraphMergerTests
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBMergeInsert\fP ()"
.br
.ti -1c
.RI "void \fBMergeUpdate\fP ()"
.br
.ti -1c
.RI "void \fBMergeRuleUnbroken\fP ()"
.br
.ti -1c
.RI "void \fBMergeDelete\fP ()"
.br
.ti -1c
.RI "void \fBMergeChildInsert\fP ()"
.br
.ti -1c
.RI "void \fBMergeChildUpdate\fP ()"
.br
.ti -1c
.RI "void \fBMergeNewChildUpdate\fP ()"
.br
.ti -1c
.RI "void \fBMergeChildDelete\fP ()"
.br
.ti -1c
.RI "void \fBMergeList\fP ()"
.br
.ti -1c
.RI "void \fBMergeListNewChild\fP ()"
.br
.ti -1c
.RI "void \fBMergeChildList\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 28 of file GraphMergerTests\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Csla\&.Test\&.GraphMerge\&.GraphMergerTests\&.MergeChildDelete ()"

.PP
Definition at line 198 of file GraphMergerTests\&.cs\&.
.SS "void Csla\&.Test\&.GraphMerge\&.GraphMergerTests\&.MergeChildInsert ()"

.PP
Definition at line 126 of file GraphMergerTests\&.cs\&.
.SS "void Csla\&.Test\&.GraphMerge\&.GraphMergerTests\&.MergeChildList ()"

.PP
Definition at line 295 of file GraphMergerTests\&.cs\&.
.SS "void Csla\&.Test\&.GraphMerge\&.GraphMergerTests\&.MergeChildUpdate ()"

.PP
Definition at line 153 of file GraphMergerTests\&.cs\&.
.SS "void Csla\&.Test\&.GraphMerge\&.GraphMergerTests\&.MergeDelete ()"

.PP
Definition at line 100 of file GraphMergerTests\&.cs\&.
.SS "void Csla\&.Test\&.GraphMerge\&.GraphMergerTests\&.MergeInsert ()"

.PP
Definition at line 31 of file GraphMergerTests\&.cs\&.
.SS "void Csla\&.Test\&.GraphMerge\&.GraphMergerTests\&.MergeList ()"

.PP
Definition at line 228 of file GraphMergerTests\&.cs\&.
.SS "void Csla\&.Test\&.GraphMerge\&.GraphMergerTests\&.MergeListNewChild ()"

.PP
Definition at line 261 of file GraphMergerTests\&.cs\&.
.SS "void Csla\&.Test\&.GraphMerge\&.GraphMergerTests\&.MergeNewChildUpdate ()"

.PP
Definition at line 181 of file GraphMergerTests\&.cs\&.
.SS "void Csla\&.Test\&.GraphMerge\&.GraphMergerTests\&.MergeRuleUnbroken ()"

.PP
Definition at line 77 of file GraphMergerTests\&.cs\&.
.SS "void Csla\&.Test\&.GraphMerge\&.GraphMergerTests\&.MergeUpdate ()"

.PP
Definition at line 54 of file GraphMergerTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
