.TH "Csla.Analyzers.Tests.CheckConstructorsAnalyzerPublicConstructorCodeFixTests" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Analyzers.Tests.CheckConstructorsAnalyzerPublicConstructorCodeFixTests
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBVerifyGetFixableDiagnosticIds\fP ()"
.br
.ti -1c
.RI "async Task \fBVerifyGetFixesWhenConstructorNoArgumentsDoesNotExist\fP ()"
.br
.ti -1c
.RI "async Task \fBVerifyGetFixesWhenPrivateConstructorNoArgumentsExists\fP ()"
.br
.ti -1c
.RI "async Task \fBVerifyGetFixesWhenPrivateConstructorNoArgumentsExistsAndLeadingTriviaExists\fP ()"
.br
.ti -1c
.RI "async Task \fBVerifyGetFixesWhenPrivateConstructorNoArgumentsExistsAndTrailingTriviaExists\fP ()"
.br
.ti -1c
.RI "async Task \fBVerifyGetFixesWhenPrivateConstructorNoArgumentsExistsWithNestedClasses\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 17 of file CheckConstructorsAnalyzerPublicConstructorCodeFixTests\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Csla\&.Analyzers\&.Tests\&.CheckConstructorsAnalyzerPublicConstructorCodeFixTests\&.VerifyGetFixableDiagnosticIds ()"

.PP
Definition at line 20 of file CheckConstructorsAnalyzerPublicConstructorCodeFixTests\&.cs\&.
.SS "async Task Csla\&.Analyzers\&.Tests\&.CheckConstructorsAnalyzerPublicConstructorCodeFixTests\&.VerifyGetFixesWhenConstructorNoArgumentsDoesNotExist ()"

.PP
Definition at line 31 of file CheckConstructorsAnalyzerPublicConstructorCodeFixTests\&.cs\&.
.SS "async Task Csla\&.Analyzers\&.Tests\&.CheckConstructorsAnalyzerPublicConstructorCodeFixTests\&.VerifyGetFixesWhenPrivateConstructorNoArgumentsExists ()"

.PP
Definition at line 69 of file CheckConstructorsAnalyzerPublicConstructorCodeFixTests\&.cs\&.
.SS "async Task Csla\&.Analyzers\&.Tests\&.CheckConstructorsAnalyzerPublicConstructorCodeFixTests\&.VerifyGetFixesWhenPrivateConstructorNoArgumentsExistsAndLeadingTriviaExists ()"

.PP
Definition at line 107 of file CheckConstructorsAnalyzerPublicConstructorCodeFixTests\&.cs\&.
.SS "async Task Csla\&.Analyzers\&.Tests\&.CheckConstructorsAnalyzerPublicConstructorCodeFixTests\&.VerifyGetFixesWhenPrivateConstructorNoArgumentsExistsAndTrailingTriviaExists ()"

.PP
Definition at line 148 of file CheckConstructorsAnalyzerPublicConstructorCodeFixTests\&.cs\&.
.SS "async Task Csla\&.Analyzers\&.Tests\&.CheckConstructorsAnalyzerPublicConstructorCodeFixTests\&.VerifyGetFixesWhenPrivateConstructorNoArgumentsExistsWithNestedClasses ()"

.PP
Definition at line 188 of file CheckConstructorsAnalyzerPublicConstructorCodeFixTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
