.TH "Csla.WcfPortal.CriteriaRequest" 3 "Thu Jul 22 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.WcfPortal.CriteriaRequest
.SH SYNOPSIS
.br
.PP
.PP
Inherits object, System\&.Runtime\&.Serialization\&.IExtensibleDataObject, and System\&.ComponentModel\&.INotifyPropertyChanged\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBRaisePropertyChanged\fP (string propertyName)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "System\&.Runtime\&.Serialization\&.ExtensionDataObject \fBExtensionData\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "byte[] \fBClientContext\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBClientCulture\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBClientUICulture\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "byte[] \fBCriteriaData\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "byte[] \fBGlobalContext\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "byte[] \fBPrincipal\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBTypeName\fP\fC [get, set]\fP"
.br
.in -1c
.SS "Events"

.in +1c
.ti -1c
.RI "System\&.ComponentModel\&.PropertyChangedEventHandler \fBPropertyChanged\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 21 of file Reference\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Csla\&.WcfPortal\&.CriteriaRequest\&.RaisePropertyChanged (string propertyName)\fC [protected]\fP"

.PP
Definition at line 150 of file Reference\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "byte [] Csla\&.WcfPortal\&.CriteriaRequest\&.ClientContext\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 58 of file Reference\&.cs\&.
.SS "string Csla\&.WcfPortal\&.CriteriaRequest\&.ClientCulture\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 71 of file Reference\&.cs\&.
.SS "string Csla\&.WcfPortal\&.CriteriaRequest\&.ClientUICulture\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 84 of file Reference\&.cs\&.
.SS "byte [] Csla\&.WcfPortal\&.CriteriaRequest\&.CriteriaData\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 97 of file Reference\&.cs\&.
.SS "System\&.Runtime\&.Serialization\&.ExtensionDataObject Csla\&.WcfPortal\&.CriteriaRequest\&.ExtensionData\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 48 of file Reference\&.cs\&.
.SS "byte [] Csla\&.WcfPortal\&.CriteriaRequest\&.GlobalContext\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 110 of file Reference\&.cs\&.
.SS "byte [] Csla\&.WcfPortal\&.CriteriaRequest\&.Principal\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 123 of file Reference\&.cs\&.
.SS "string Csla\&.WcfPortal\&.CriteriaRequest\&.TypeName\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 136 of file Reference\&.cs\&.
.SH "Event Documentation"
.PP 
.SS "System\&.ComponentModel\&.PropertyChangedEventHandler Csla\&.WcfPortal\&.CriteriaRequest\&.PropertyChanged"

.PP
Definition at line 148 of file Reference\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
