.TH "Csla.Testing.Business.ApplicationContext" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Testing.Business.ApplicationContext
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBContextBOVerifier\fP"
.br
.ti -1c
.RI "class \fBContextMessageValues\fP"
.br
.ti -1c
.RI "class \fBClientContextBOVerifier\fP"
.br
.ti -1c
.RI "class \fBGlobalContextBOVerifier\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum class \fBContexts\fP { \fBClient\fP, \fBGlobal\fP }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBCsla\&.Testing\&.Business\&.ApplicationContext\&.Contexts\fP\fC [strong]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIClient \fP\fP
.TP
\fB\fIGlobal \fP\fP
.PP
Definition at line 84 of file ContextBOVerifier\&.cs\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
