.TH "Csla.AspNetCore.RazorPages.PageModel< T >" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.AspNetCore.RazorPages.PageModel< T > \- Custom \fBPageModel\fP for CSLA \&.NET  

.SH SYNOPSIS
.br
.PP
.PP
Inherits PageModel\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "async Task< bool > \fBSaveAsync\fP (bool forceUpdate=false)"
.br
.RI "Save the Item "
.ti -1c
.RI "\fBPropertyInfo\fP \fBGetPropertyInfo\fP (string propertyName)"
.br
.RI "Get a \fBPropertyInfo\fP object for a property of the Model\&. \fBPropertyInfo\fP provides access to the metastate of the property\&. "
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBCanCreateItem\fP ()"
.br
.RI "Gets a value indicating whether the current user is authorized to create an instance of the business domain type "
.ti -1c
.RI "static bool \fBCanGetItem\fP ()"
.br
.RI "Gets a value indicating whether the current user is authorized to retrieve an instance of the business domain type "
.ti -1c
.RI "static bool \fBCanEditItem\fP ()"
.br
.RI "Gets a value indicating whether the current user is authorized to edit/save an instance of the business domain type "
.ti -1c
.RI "static bool \fBCanDeleteItem\fP ()"
.br
.RI "Gets a value indicating whether the current user is authorized to delete an instance of the business domain type "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "T \fBItem\fP\fC [get, set]\fP"
.br
.RI "Gets or sets the business domain model object\&. "
.in -1c
.SH "Detailed Description"
.PP 
Custom \fBPageModel\fP for CSLA \&.NET 


.PP
\fBType Constraints\fP
.TP
\fIT\fP : \fIISavable\fP
.PP
Definition at line 23 of file PageModel\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "static bool \fBCsla\&.AspNetCore\&.RazorPages\&.PageModel\fP< T >\&.CanCreateItem ()\fC [static]\fP"

.PP
Gets a value indicating whether the current user is authorized to create an instance of the business domain type 
.PP
\fBReturns\fP
.RS 4

.RE
.PP

.PP
Definition at line 117 of file PageModel\&.cs\&.
.SS "static bool \fBCsla\&.AspNetCore\&.RazorPages\&.PageModel\fP< T >\&.CanDeleteItem ()\fC [static]\fP"

.PP
Gets a value indicating whether the current user is authorized to delete an instance of the business domain type 
.PP
\fBReturns\fP
.RS 4

.RE
.PP

.PP
Definition at line 150 of file PageModel\&.cs\&.
.SS "static bool \fBCsla\&.AspNetCore\&.RazorPages\&.PageModel\fP< T >\&.CanEditItem ()\fC [static]\fP"

.PP
Gets a value indicating whether the current user is authorized to edit/save an instance of the business domain type 
.PP
\fBReturns\fP
.RS 4

.RE
.PP

.PP
Definition at line 139 of file PageModel\&.cs\&.
.SS "static bool \fBCsla\&.AspNetCore\&.RazorPages\&.PageModel\fP< T >\&.CanGetItem ()\fC [static]\fP"

.PP
Gets a value indicating whether the current user is authorized to retrieve an instance of the business domain type 
.PP
\fBReturns\fP
.RS 4

.RE
.PP

.PP
Definition at line 128 of file PageModel\&.cs\&.
.SS "\fBPropertyInfo\fP \fBCsla\&.AspNetCore\&.RazorPages\&.PageModel\fP< T >\&.GetPropertyInfo (string propertyName)"

.PP
Get a \fBPropertyInfo\fP object for a property of the Model\&. \fBPropertyInfo\fP provides access to the metastate of the property\&. 
.PP
\fBParameters\fP
.RS 4
\fIpropertyName\fP Property name
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
Definition at line 101 of file PageModel\&.cs\&.
.SS "async Task<bool> \fBCsla\&.AspNetCore\&.RazorPages\&.PageModel\fP< T >\&.SaveAsync (bool forceUpdate = \fCfalse\fP)"

.PP
Save the Item 
.PP
\fBParameters\fP
.RS 4
\fIforceUpdate\fP Indicates whether an update operation should be forced\&.
.RE
.PP
\fBReturns\fP
.RS 4
True if the save operation succeeds
.RE
.PP

.PP
Definition at line 37 of file PageModel\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "T \fBCsla\&.AspNetCore\&.RazorPages\&.PageModel\fP< T >\&.Item\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the business domain model object\&. 
.PP
Definition at line 30 of file PageModel\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
