.TH "IViewModel.cs" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IViewModel.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "interface \fBCsla\&.Web\&.Mvc\&.IViewModel\fP"
.br
.RI "Defines a CSLA \&.NET MVC viewmodel object\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBCsla\fP"
.br
.ti -1c
.RI "namespace \fBCsla\&.Web\fP"
.br
.ti -1c
.RI "namespace \fBCsla\&.Web\&.Mvc\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
