.TH "Csla.Serialization.Mobile.ReferenceComparer< T >" 3 "Thu Jul 22 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Serialization.Mobile.ReferenceComparer< T > \- Implements an equality comparer for \fBIMobileObject\fP that compares the objects only on the basis is the reference value\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits IEqualityComparer< T >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBEquals\fP (T x, T y)"
.br
.RI "Determines if the two objects are reference-equal\&. "
.ti -1c
.RI "int \fBGetHashCode\fP (T obj)"
.br
.RI "Gets the hash code value for the object\&. "
.in -1c
.SH "Detailed Description"
.PP 
Implements an equality comparer for \fBIMobileObject\fP that compares the objects only on the basis is the reference value\&. 


.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP Type of objects to compare\&.
.RE
.PP

.PP
Definition at line 20 of file ReferenceComparer\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "bool \fBCsla\&.Serialization\&.Mobile\&.ReferenceComparer\fP< T >\&.Equals (T x, T y)"

.PP
Determines if the two objects are reference-equal\&. 
.PP
\fBParameters\fP
.RS 4
\fIx\fP First object\&.
.br
\fIy\fP Second object\&.
.RE
.PP

.PP
Definition at line 29 of file ReferenceComparer\&.cs\&.
.SS "int \fBCsla\&.Serialization\&.Mobile\&.ReferenceComparer\fP< T >\&.GetHashCode (T obj)"

.PP
Gets the hash code value for the object\&. 
.PP
\fBParameters\fP
.RS 4
\fIobj\fP Object reference\&.
.RE
.PP

.PP
Definition at line 38 of file ReferenceComparer\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
