.TH "Csla.Serialization" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Serialization
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBMobile\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBinaryFormatterWrapper\fP"
.br
.RI "Wraps the BinaryFormatter in the \fBISerializationFormatter\fP interface so it can be used in a standardized manner\&. "
.ti -1c
.RI "interface \fBISerializationFormatter\fP"
.br
.RI "Defines an object that can serialize and deserialize object graphs\&. "
.ti -1c
.RI "class \fBNetDataContractSerializerWrapper\fP"
.br
.ti -1c
.RI "class \fBSerializationFormatterFactory\fP"
.br
.RI "Factory used to create the appropriate serialization formatter object based on the application configuration\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
