.TH "Csla.Serialization.Mobile.MobileFormatter" 3 "Thu Jul 22 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Serialization.Mobile.MobileFormatter \- Serializes and deserializes objects at the field level\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.Serialization\&.ISerializationFormatter\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSerialize\fP (Stream serializationStream, object graph)"
.br
.RI "Serialize an object graph into XML\&. "
.ti -1c
.RI "List< \fBSerializationInfo\fP > \fBSerializeAsDTO\fP (object graph)"
.br
.RI "Serialize an object graph into DTO\&. "
.ti -1c
.RI "\fBSerializationInfo\fP \fBSerializeObject\fP (object obj)"
.br
.RI "Serializes an object into a \fBSerializationInfo\fP object\&. "
.ti -1c
.RI "object \fBDeserialize\fP (Stream serializationStream)"
.br
.RI "Deserialize an object from XML\&. "
.ti -1c
.RI "object \fBDeserializeAsDTO\fP (List< \fBSerializationInfo\fP > deserialized)"
.br
.RI "Deserialize an object from DTO graph\&. "
.ti -1c
.RI "\fBIMobileObject\fP \fBGetObject\fP (int referenceId)"
.br
.RI "Gets a deserialized object based on the object's reference id within the serialization stream\&. "
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static byte[] \fBSerialize\fP (object obj)"
.br
.RI "Serializes the object into a byte array\&. "
.ti -1c
.RI "static List< \fBSerializationInfo\fP > \fBSerializeToDTO\fP (object obj)"
.br
.RI "Serializes the object into a DTO\&. "
.ti -1c
.RI "static object \fBDeserializeFromDTO\fP (List< \fBSerializationInfo\fP > serialized)"
.br
.RI "Serializes an object from a DTO graph "
.ti -1c
.RI "static object \fBDeserialize\fP (byte[] data)"
.br
.RI "Deserializes a byte stream into an object\&. "
.ti -1c
.RI "static object \fBDeserialize\fP (List< \fBSerializationInfo\fP > data)"
.br
.RI "Deserializes a byte stream into an object\&. "
.in -1c
.SH "Detailed Description"
.PP 
Serializes and deserializes objects at the field level\&. 


.PP
Definition at line 25 of file MobileFormatter\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "static object Csla\&.Serialization\&.Mobile\&.MobileFormatter\&.Deserialize (byte[] data)\fC [static]\fP"

.PP
Deserializes a byte stream into an object\&. 
.PP
\fBParameters\fP
.RS 4
\fIdata\fP Byte array containing the object's serialized data\&. 
.RE
.PP
\fBReturns\fP
.RS 4
An object containing the data from the byte stream\&. The object must implement \fBIMobileObject\fP to be deserialized\&. 
.RE
.PP

.PP
Implements \fBCsla\&.Serialization\&.ISerializationFormatter\fP\&.
.PP
Definition at line 395 of file MobileFormatter\&.cs\&.
.SS "static object Csla\&.Serialization\&.Mobile\&.MobileFormatter\&.Deserialize (List< \fBSerializationInfo\fP > data)\fC [static]\fP"

.PP
Deserializes a byte stream into an object\&. 
.PP
\fBParameters\fP
.RS 4
\fIdata\fP DTO containing the object's serialized data\&. 
.RE
.PP
\fBReturns\fP
.RS 4
An object containing the data from the byte stream\&. The object must implement \fBIMobileObject\fP to be deserialized\&. 
.RE
.PP

.PP
Definition at line 419 of file MobileFormatter\&.cs\&.
.SS "object Csla\&.Serialization\&.Mobile\&.MobileFormatter\&.Deserialize (Stream serializationStream)"

.PP
Deserialize an object from XML\&. 
.PP
\fBParameters\fP
.RS 4
\fIserializationStream\fP Stream containing the serialized XML data\&. 
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
Definition at line 212 of file MobileFormatter\&.cs\&.
.SS "object Csla\&.Serialization\&.Mobile\&.MobileFormatter\&.DeserializeAsDTO (List< \fBSerializationInfo\fP > deserialized)"

.PP
Deserialize an object from DTO graph\&. param name='deserialized'>DTO group to deserialize
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
Definition at line 245 of file MobileFormatter\&.cs\&.
.SS "static object Csla\&.Serialization\&.Mobile\&.MobileFormatter\&.DeserializeFromDTO (List< \fBSerializationInfo\fP > serialized)\fC [static]\fP"

.PP
Serializes an object from a DTO graph 
.PP
\fBParameters\fP
.RS 4
\fIserialized\fP DTO Graph to deserialize
.RE
.PP
\fBReturns\fP
.RS 4
Deserialized object
.RE
.PP

.PP
Definition at line 377 of file MobileFormatter\&.cs\&.
.SS "\fBIMobileObject\fP Csla\&.Serialization\&.Mobile\&.MobileFormatter\&.GetObject (int referenceId)"

.PP
Gets a deserialized object based on the object's reference id within the serialization stream\&. 
.PP
\fBParameters\fP
.RS 4
\fIreferenceId\fP Id of object in stream\&.
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
Definition at line 331 of file MobileFormatter\&.cs\&.
.SS "static byte [] Csla\&.Serialization\&.Mobile\&.MobileFormatter\&.Serialize (object obj)\fC [static]\fP"

.PP
Serializes the object into a byte array\&. 
.PP
\fBParameters\fP
.RS 4
\fIobj\fP The object to be serialized, which must implement \fBIMobileObject\fP\&. 
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
Implements \fBCsla\&.Serialization\&.ISerializationFormatter\fP\&.
.PP
Definition at line 348 of file MobileFormatter\&.cs\&.
.SS "void Csla\&.Serialization\&.Mobile\&.MobileFormatter\&.Serialize (Stream serializationStream, object graph)"

.PP
Serialize an object graph into XML\&. 
.PP
\fBParameters\fP
.RS 4
\fIserializationStream\fP Stream to which the serialized data will be written\&. 
.br
\fIgraph\fP Root object of the object graph to serialize\&. 
.RE
.PP

.PP
Definition at line 40 of file MobileFormatter\&.cs\&.
.SS "List<\fBSerializationInfo\fP> Csla\&.Serialization\&.Mobile\&.MobileFormatter\&.SerializeAsDTO (object graph)"

.PP
Serialize an object graph into DTO\&. 
.PP
\fBParameters\fP
.RS 4
\fIgraph\fP Root object of the object graph to serialize\&. 
.RE
.PP

.PP
Definition at line 65 of file MobileFormatter\&.cs\&.
.SS "\fBSerializationInfo\fP Csla\&.Serialization\&.Mobile\&.MobileFormatter\&.SerializeObject (object obj)"

.PP
Serializes an object into a \fBSerializationInfo\fP object\&. 
.PP
\fBParameters\fP
.RS 4
\fIobj\fP Object to be serialized\&.
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
Definition at line 117 of file MobileFormatter\&.cs\&.
.SS "static List<\fBSerializationInfo\fP> Csla\&.Serialization\&.Mobile\&.MobileFormatter\&.SerializeToDTO (object obj)\fC [static]\fP"

.PP
Serializes the object into a DTO\&. 
.PP
\fBParameters\fP
.RS 4
\fIobj\fP The object to be serialized, which must implement \fBIMobileObject\fP\&. 
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
Definition at line 366 of file MobileFormatter\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
