.TH "Csla.Analyzers.Tests.FindOperationsWithIncorrectReturnTypesAnalyzerTests" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Analyzers.Tests.FindOperationsWithIncorrectReturnTypesAnalyzerTests
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBVerifySupportedDiagnostics\fP ()"
.br
.ti -1c
.RI "async Task \fBAnalyzeWithNotMobileObject\fP ()"
.br
.ti -1c
.RI "async Task \fBAnalyzeWithMobileObjectAndMethodIsNotOperation\fP ()"
.br
.ti -1c
.RI "async Task \fBAnalyzeWithMobileObjectAndMethodIsOperationReturningVoid\fP ()"
.br
.ti -1c
.RI "async Task \fBAnalyzeWithMobileObjectAndMethodIsOperationReturningTask\fP ()"
.br
.ti -1c
.RI "async Task \fBAnalyzeWithMobileObjectAndMethodIsOperationReturningIncorrectType\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 9 of file FindOperationsWithIncorrectReturnTypesAnalyzerTests\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "async Task Csla\&.Analyzers\&.Tests\&.FindOperationsWithIncorrectReturnTypesAnalyzerTests\&.AnalyzeWithMobileObjectAndMethodIsNotOperation ()"

.PP
Definition at line 43 of file FindOperationsWithIncorrectReturnTypesAnalyzerTests\&.cs\&.
.SS "async Task Csla\&.Analyzers\&.Tests\&.FindOperationsWithIncorrectReturnTypesAnalyzerTests\&.AnalyzeWithMobileObjectAndMethodIsOperationReturningIncorrectType ()"

.PP
Definition at line 88 of file FindOperationsWithIncorrectReturnTypesAnalyzerTests\&.cs\&.
.SS "async Task Csla\&.Analyzers\&.Tests\&.FindOperationsWithIncorrectReturnTypesAnalyzerTests\&.AnalyzeWithMobileObjectAndMethodIsOperationReturningTask ()"

.PP
Definition at line 72 of file FindOperationsWithIncorrectReturnTypesAnalyzerTests\&.cs\&.
.SS "async Task Csla\&.Analyzers\&.Tests\&.FindOperationsWithIncorrectReturnTypesAnalyzerTests\&.AnalyzeWithMobileObjectAndMethodIsOperationReturningVoid ()"

.PP
Definition at line 57 of file FindOperationsWithIncorrectReturnTypesAnalyzerTests\&.cs\&.
.SS "async Task Csla\&.Analyzers\&.Tests\&.FindOperationsWithIncorrectReturnTypesAnalyzerTests\&.AnalyzeWithNotMobileObject ()"

.PP
Definition at line 35 of file FindOperationsWithIncorrectReturnTypesAnalyzerTests\&.cs\&.
.SS "void Csla\&.Analyzers\&.Tests\&.FindOperationsWithIncorrectReturnTypesAnalyzerTests\&.VerifySupportedDiagnostics ()"

.PP
Definition at line 12 of file FindOperationsWithIncorrectReturnTypesAnalyzerTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
