.TH "Csla.Server.Hosts.HttpPortal" 3 "Thu Jul 22 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Server.Hosts.HttpPortal \- Exposes server-side \fBDataPortal\fP functionality through HTTP request/response\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "async Task< \fBDataPortalResponse\fP > \fBCreate\fP (\fBCriteriaRequest\fP request)"
.br
.RI "Create and initialize an existing business object\&. "
.ti -1c
.RI "async Task< \fBDataPortalResponse\fP > \fBFetch\fP (\fBCriteriaRequest\fP request)"
.br
.RI "Get an existing business object\&. "
.ti -1c
.RI "async Task< \fBDataPortalResponse\fP > \fBUpdate\fP (\fBUpdateRequest\fP request)"
.br
.RI "Update a business object\&. "
.ti -1c
.RI "async Task< \fBDataPortalResponse\fP > \fBDelete\fP (\fBCriteriaRequest\fP request)"
.br
.RI "Delete a business object\&. "
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual \fBUpdateRequest\fP \fBConvertRequest\fP (\fBUpdateRequest\fP request)"
.br
.RI "Override to convert the request data before it is transferred over the network\&. "
.ti -1c
.RI "virtual \fBCriteriaRequest\fP \fBConvertRequest\fP (\fBCriteriaRequest\fP request)"
.br
.RI "Override to convert the request data before it is transferred over the network\&. "
.ti -1c
.RI "virtual \fBDataPortalResponse\fP \fBConvertResponse\fP (\fBDataPortalResponse\fP response)"
.br
.RI "Override to convert the response data after it comes back from the network\&. "
.in -1c
.SH "Detailed Description"
.PP 
Exposes server-side \fBDataPortal\fP functionality through HTTP request/response\&. 


.PP
Definition at line 27 of file HttpPortal\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual \fBCriteriaRequest\fP Csla\&.Server\&.Hosts\&.HttpPortal\&.ConvertRequest (\fBCriteriaRequest\fP request)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Override to convert the request data before it is transferred over the network\&. 
.PP
\fBParameters\fP
.RS 4
\fIrequest\fP Request object\&.
.RE
.PP

.PP
Definition at line 249 of file HttpPortal\&.cs\&.
.SS "virtual \fBUpdateRequest\fP Csla\&.Server\&.Hosts\&.HttpPortal\&.ConvertRequest (\fBUpdateRequest\fP request)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Override to convert the request data before it is transferred over the network\&. 
.PP
\fBParameters\fP
.RS 4
\fIrequest\fP Request object\&.
.RE
.PP

.PP
Definition at line 239 of file HttpPortal\&.cs\&.
.SS "virtual \fBDataPortalResponse\fP Csla\&.Server\&.Hosts\&.HttpPortal\&.ConvertResponse (\fBDataPortalResponse\fP response)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Override to convert the response data after it comes back from the network\&. 
.PP
\fBParameters\fP
.RS 4
\fIresponse\fP Response object\&.
.RE
.PP

.PP
Definition at line 259 of file HttpPortal\&.cs\&.
.SS "async Task<\fBDataPortalResponse\fP> Csla\&.Server\&.Hosts\&.HttpPortal\&.Create (\fBCriteriaRequest\fP request)"

.PP
Create and initialize an existing business object\&. 
.PP
\fBParameters\fP
.RS 4
\fIrequest\fP The request parameter object\&.
.RE
.PP

.PP
Definition at line 34 of file HttpPortal\&.cs\&.
.SS "async Task<\fBDataPortalResponse\fP> Csla\&.Server\&.Hosts\&.HttpPortal\&.Delete (\fBCriteriaRequest\fP request)"

.PP
Delete a business object\&. 
.PP
\fBParameters\fP
.RS 4
\fIrequest\fP The request parameter object\&.
.RE
.PP

.PP
Definition at line 176 of file HttpPortal\&.cs\&.
.SS "async Task<\fBDataPortalResponse\fP> Csla\&.Server\&.Hosts\&.HttpPortal\&.Fetch (\fBCriteriaRequest\fP request)"

.PP
Get an existing business object\&. 
.PP
\fBParameters\fP
.RS 4
\fIrequest\fP The request parameter object\&.
.RE
.PP

.PP
Definition at line 83 of file HttpPortal\&.cs\&.
.SS "async Task<\fBDataPortalResponse\fP> Csla\&.Server\&.Hosts\&.HttpPortal\&.Update (\fBUpdateRequest\fP request)"

.PP
Update a business object\&. 
.PP
\fBParameters\fP
.RS 4
\fIrequest\fP The request parameter object\&.
.RE
.PP

.PP
Definition at line 132 of file HttpPortal\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
