.TH "Csla.Server.Hosts.DataPortalChannel" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Server.Hosts.DataPortalChannel
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCriteriaRequest\fP"
.br
.RI "Message sent to the WCF data portal\&. "
.ti -1c
.RI "class \fBDataPortalErrorInfo\fP"
.br
.RI "Message containing details about any server-side exception\&. "
.ti -1c
.RI "class \fBDataPortalResponse\fP"
.br
.RI "Response message for returning the results of a data portal call\&. "
.ti -1c
.RI "class \fBUpdateRequest\fP"
.br
.RI "Request message for updating a business object\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
