.TH "Csla.Test.PropertyGetSet.PropertyGetSetTests" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.PropertyGetSet.PropertyGetSetTests
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBInitialize\fP ()"
.br
.ti -1c
.RI "void \fBCleanup\fP ()"
.br
.ti -1c
.RI "void \fBForceStaticInit\fP ()"
.br
.ti -1c
.RI "void \fBNullString\fP ()"
.br
.ti -1c
.RI "void \fBNonGenericLoadProperty\fP ()"
.br
.ti -1c
.RI "void \fBExplicitFieldProperties\fP ()"
.br
.ti -1c
.RI "void \fBSerializedExplicitFieldProperties\fP ()"
.br
.ti -1c
.RI "void \fBManagedFieldProperties\fP ()"
.br
.ti -1c
.RI "void \fBManagedFieldBaseProperties\fP ()"
.br
.ti -1c
.RI "void \fBSerializedManagedFieldProperties\fP ()"
.br
.ti -1c
.RI "void \fBMarkClean\fP ()"
.br
.ti -1c
.RI "void \fBSmartDateProperties\fP ()"
.br
.ti -1c
.RI "void \fBSimpleChildProperties\fP ()"
.br
.ti -1c
.RI "void \fBSerializedSimpleChildProperties\fP ()"
.br
.ti -1c
.RI "void \fBRootUndoCancel\fP ()"
.br
.ti -1c
.RI "void \fBRootUndoApply\fP ()"
.br
.ti -1c
.RI "void \fBRootChildUndoCancel\fP ()"
.br
.ti -1c
.RI "void \fBSerializedEditLevel\fP ()"
.br
.ti -1c
.RI "void \fBRootChildUndoCancelIsDirty\fP ()"
.br
.ti -1c
.RI "void \fBRootChildUndoApply\fP ()"
.br
.ti -1c
.RI "void \fBRootChildListUndoCancel\fP ()"
.br
.ti -1c
.RI "void \fBRootChildListUndoApply\fP ()"
.br
.ti -1c
.RI "void \fBLoadNullProperty\fP ()"
.br
.ti -1c
.RI "void \fBPropertyNotRegistered\fP ()"
.br
.ti -1c
.RI "void \fBPropertyRegisteredTwice\fP ()"
.br
.ti -1c
.RI "void \fBFieldDirty\fP ()"
.br
.ti -1c
.RI "void \fBIf_ManagedStringField_Property_Changes_ChildChanged_Event_Should_Not_Fire\fP ()"
.br
.ti -1c
.RI "void \fBIf_FieldBackedString_Property_Changes_On_ManagedChild_Then_ChildChanged_Should_Fire_On_Root_ButNot_On_ManagedChild\fP ()"
.br
.ti -1c
.RI "void \fBIf_FieldBackedString_Property_Changes_On_Item_In_ManagedChildList_Then_ChildChanged_Fires_On_Root_And_On_ManagedChildList\fP ()"
.br
.ti -1c
.RI "void \fBIf_FieldBackedString_Changes_On_GrandChild_Then_ChildChanged_Fires_On_GrandChild_Child_and_Root\fP ()"
.br
.ti -1c
.RI "void \fBIf_FieldBackedString_Property_Is_Changed_On_Child_After_CancelEdit_Then_ChildChanged_Fires_On_Root\fP ()"
.br
.ti -1c
.RI "void \fBIf_FieldBackedString_Is_Changed_On_GrandChild_List_Item_After_Root_Is_Deserialized_Then_Root_ChildChanged_Event_Fires\fP ()"
.br
.ti -1c
.RI "void \fBLazyLoadChild_GetBeforeSet\fP ()"
.br
.ti -1c
.RI "void \fBLazyLoadChild_GetAfterSet\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 31 of file PropertyGetSetTests\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Csla\&.Test\&.PropertyGetSet\&.PropertyGetSetTests\&.Cleanup ()"

.PP
Definition at line 43 of file PropertyGetSetTests\&.cs\&.
.SS "void Csla\&.Test\&.PropertyGetSet\&.PropertyGetSetTests\&.ExplicitFieldProperties ()"

.PP
Definition at line 94 of file PropertyGetSetTests\&.cs\&.
.SS "void Csla\&.Test\&.PropertyGetSet\&.PropertyGetSetTests\&.FieldDirty ()"

.PP
Definition at line 611 of file PropertyGetSetTests\&.cs\&.
.SS "void Csla\&.Test\&.PropertyGetSet\&.PropertyGetSetTests\&.ForceStaticInit ()"

.PP
Definition at line 49 of file PropertyGetSetTests\&.cs\&.
.SS "void Csla\&.Test\&.PropertyGetSet\&.PropertyGetSetTests\&.If_FieldBackedString_Changes_On_GrandChild_Then_ChildChanged_Fires_On_GrandChild_Child_and_Root ()"

.PP
Definition at line 659 of file PropertyGetSetTests\&.cs\&.
.SS "void Csla\&.Test\&.PropertyGetSet\&.PropertyGetSetTests\&.If_FieldBackedString_Is_Changed_On_GrandChild_List_Item_After_Root_Is_Deserialized_Then_Root_ChildChanged_Event_Fires ()"

.PP
Definition at line 712 of file PropertyGetSetTests\&.cs\&.
.SS "void Csla\&.Test\&.PropertyGetSet\&.PropertyGetSetTests\&.If_FieldBackedString_Property_Changes_On_Item_In_ManagedChildList_Then_ChildChanged_Fires_On_Root_And_On_ManagedChildList ()"

.PP
Definition at line 640 of file PropertyGetSetTests\&.cs\&.
.SS "void Csla\&.Test\&.PropertyGetSet\&.PropertyGetSetTests\&.If_FieldBackedString_Property_Changes_On_ManagedChild_Then_ChildChanged_Should_Fire_On_Root_ButNot_On_ManagedChild ()"

.PP
Definition at line 628 of file PropertyGetSetTests\&.cs\&.
.SS "void Csla\&.Test\&.PropertyGetSet\&.PropertyGetSetTests\&.If_FieldBackedString_Property_Is_Changed_On_Child_After_CancelEdit_Then_ChildChanged_Fires_On_Root ()"

.PP
Definition at line 693 of file PropertyGetSetTests\&.cs\&.
.SS "void Csla\&.Test\&.PropertyGetSet\&.PropertyGetSetTests\&.If_ManagedStringField_Property_Changes_ChildChanged_Event_Should_Not_Fire ()"

.PP
Definition at line 620 of file PropertyGetSetTests\&.cs\&.
.SS "void Csla\&.Test\&.PropertyGetSet\&.PropertyGetSetTests\&.Initialize ()"

.PP
Definition at line 36 of file PropertyGetSetTests\&.cs\&.
.SS "void Csla\&.Test\&.PropertyGetSet\&.PropertyGetSetTests\&.LazyLoadChild_GetAfterSet ()"

.PP
Definition at line 744 of file PropertyGetSetTests\&.cs\&.
.SS "void Csla\&.Test\&.PropertyGetSet\&.PropertyGetSetTests\&.LazyLoadChild_GetBeforeSet ()"

.PP
Definition at line 737 of file PropertyGetSetTests\&.cs\&.
.SS "void Csla\&.Test\&.PropertyGetSet\&.PropertyGetSetTests\&.LoadNullProperty ()"

.PP
Definition at line 551 of file PropertyGetSetTests\&.cs\&.
.SS "void Csla\&.Test\&.PropertyGetSet\&.PropertyGetSetTests\&.ManagedFieldBaseProperties ()"

.PP
Definition at line 178 of file PropertyGetSetTests\&.cs\&.
.SS "void Csla\&.Test\&.PropertyGetSet\&.PropertyGetSetTests\&.ManagedFieldProperties ()"

.PP
Definition at line 143 of file PropertyGetSetTests\&.cs\&.
.SS "void Csla\&.Test\&.PropertyGetSet\&.PropertyGetSetTests\&.MarkClean ()"

.PP
Definition at line 232 of file PropertyGetSetTests\&.cs\&.
.SS "void Csla\&.Test\&.PropertyGetSet\&.PropertyGetSetTests\&.NonGenericLoadProperty ()"

.PP
Definition at line 75 of file PropertyGetSetTests\&.cs\&.
.SS "void Csla\&.Test\&.PropertyGetSet\&.PropertyGetSetTests\&.NullString ()"

.PP
Definition at line 61 of file PropertyGetSetTests\&.cs\&.
.SS "void Csla\&.Test\&.PropertyGetSet\&.PropertyGetSetTests\&.PropertyNotRegistered ()"

.PP
Definition at line 563 of file PropertyGetSetTests\&.cs\&.
.SS "void Csla\&.Test\&.PropertyGetSet\&.PropertyGetSetTests\&.PropertyRegisteredTwice ()"

.PP
Definition at line 579 of file PropertyGetSetTests\&.cs\&.
.SS "void Csla\&.Test\&.PropertyGetSet\&.PropertyGetSetTests\&.RootChildListUndoApply ()"

.PP
Definition at line 519 of file PropertyGetSetTests\&.cs\&.
.SS "void Csla\&.Test\&.PropertyGetSet\&.PropertyGetSetTests\&.RootChildListUndoCancel ()"

.PP
Definition at line 491 of file PropertyGetSetTests\&.cs\&.
.SS "void Csla\&.Test\&.PropertyGetSet\&.PropertyGetSetTests\&.RootChildUndoApply ()"

.PP
Definition at line 465 of file PropertyGetSetTests\&.cs\&.
.SS "void Csla\&.Test\&.PropertyGetSet\&.PropertyGetSetTests\&.RootChildUndoCancel ()"

.PP
Definition at line 402 of file PropertyGetSetTests\&.cs\&.
.SS "void Csla\&.Test\&.PropertyGetSet\&.PropertyGetSetTests\&.RootChildUndoCancelIsDirty ()"

.PP
Definition at line 445 of file PropertyGetSetTests\&.cs\&.
.SS "void Csla\&.Test\&.PropertyGetSet\&.PropertyGetSetTests\&.RootUndoApply ()"

.PP
Definition at line 370 of file PropertyGetSetTests\&.cs\&.
.SS "void Csla\&.Test\&.PropertyGetSet\&.PropertyGetSetTests\&.RootUndoCancel ()"

.PP
Definition at line 342 of file PropertyGetSetTests\&.cs\&.
.SS "void Csla\&.Test\&.PropertyGetSet\&.PropertyGetSetTests\&.SerializedEditLevel ()"

.PP
Definition at line 424 of file PropertyGetSetTests\&.cs\&.
.SS "void Csla\&.Test\&.PropertyGetSet\&.PropertyGetSetTests\&.SerializedExplicitFieldProperties ()"

.PP
Definition at line 124 of file PropertyGetSetTests\&.cs\&.
.SS "void Csla\&.Test\&.PropertyGetSet\&.PropertyGetSetTests\&.SerializedManagedFieldProperties ()"

.PP
Definition at line 212 of file PropertyGetSetTests\&.cs\&.
.SS "void Csla\&.Test\&.PropertyGetSet\&.PropertyGetSetTests\&.SerializedSimpleChildProperties ()"

.PP
Definition at line 302 of file PropertyGetSetTests\&.cs\&.
.SS "void Csla\&.Test\&.PropertyGetSet\&.PropertyGetSetTests\&.SimpleChildProperties ()"

.PP
Definition at line 262 of file PropertyGetSetTests\&.cs\&.
.SS "void Csla\&.Test\&.PropertyGetSet\&.PropertyGetSetTests\&.SmartDateProperties ()"

.PP
Definition at line 246 of file PropertyGetSetTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
