.TH "Csla.Data.DataServiceContextManager< C >" 3 "Thu Jul 22 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Data.DataServiceContextManager< C > \- Provides an automated way to reuse an ADO\&.NET \fBData\fP Services context object within the context of a single data portal operation\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "List< T > \fBGetEntities< T >\fP ()"
.br
.RI "Gets a list of the entities of the specified type from the context\&. "
.ti -1c
.RI "T \fBGetEntity< T >\fP (string keyPropertyName, object keyPropertyValue)"
.br
.RI "Gets a list of the entities by key\&. "
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBDataServiceContextManager\fP< C > \fBGetManager\fP (Uri path)"
.br
.RI "Gets the DataServiceContext object for the specified URI\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "C \fBDataServiceContext\fP\fC [get]\fP"
.br
.RI "Gets the DataServiceContext object\&. "
.in -1c
.SH "Detailed Description"
.PP 
Provides an automated way to reuse an ADO\&.NET \fBData\fP Services context object within the context of a single data portal operation\&. 


.PP
\fBTemplate Parameters\fP
.RS 4
\fIC\fP Type of context object to use\&. 
.RE
.PP

.PP
\fBType Constraints\fP
.TP
\fIC\fP : \fISystem\&.Data\&.Services\&.Client\&.DataServiceContext\fP
.PP
Definition at line 22 of file DataServiceContextManager\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "List<T> \fBCsla\&.Data\&.DataServiceContextManager\fP< C >\&.GetEntities< T > ()"

.PP
Gets a list of the entities of the specified type from the context\&. 
.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP Type of entity\&. 
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
Definition at line 84 of file DataServiceContextManager\&.cs\&.
.SS "T \fBCsla\&.Data\&.DataServiceContextManager\fP< C >\&.GetEntity< T > (string keyPropertyName, object keyPropertyValue)"

.PP
Gets a list of the entities by key\&. 
.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP Type of entity\&. 
.RE
.PP
\fBParameters\fP
.RS 4
\fIkeyPropertyName\fP Name of the key property\&. 
.br
\fIkeyPropertyValue\fP Key value to match\&. 
.RE
.PP

.PP
Definition at line 109 of file DataServiceContextManager\&.cs\&.
.SS "static \fBDataServiceContextManager\fP<C> \fBCsla\&.Data\&.DataServiceContextManager\fP< C >\&.GetManager (Uri path)\fC [static]\fP"

.PP
Gets the DataServiceContext object for the specified URI\&. 
.PP
\fBParameters\fP
.RS 4
\fIpath\fP URI to the server-side services\&. 
.RE
.PP

.PP
Definition at line 35 of file DataServiceContextManager\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "C \fBCsla\&.Data\&.DataServiceContextManager\fP< C >\&.DataServiceContext\fC [get]\fP"

.PP
Gets the DataServiceContext object\&. 
.PP
Definition at line 63 of file DataServiceContextManager\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
