.TH "Csla.Test.DataPortal.PersonEditBase< T >" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.DataPortal.PersonEditBase< T >
.SH SYNOPSIS
.br
.PP
.PP
Inherits BusinessBase< PersonEditBase< T >>\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBDataPortal_Create\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 77 of file InheritedOperationTests\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void \fBCsla\&.Test\&.DataPortal\&.PersonEditBase\fP< T >\&.DataPortal_Create ()\fC [protected]\fP"

.PP
Definition at line 79 of file InheritedOperationTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
