.TH "Csla.Test.Silverlight.UnitContextTestBase" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.Silverlight.UnitContextTestBase
.SH SYNOPSIS
.br
.PP
.PP
Inherits TestBase\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetUp\fP ()"
.br
.ti -1c
.RI "void \fBTearDown\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "UnitTestContext \fB_context\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 22 of file UnitContextTestBase\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Csla\&.Test\&.Silverlight\&.UnitContextTestBase\&.SetUp ()"

.PP
Definition at line 27 of file UnitContextTestBase\&.cs\&.
.SS "void Csla\&.Test\&.Silverlight\&.UnitContextTestBase\&.TearDown ()"

.PP
Definition at line 32 of file UnitContextTestBase\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "UnitTestContext Csla\&.Test\&.Silverlight\&.UnitContextTestBase\&._context\fC [protected]\fP"

.PP
Definition at line 24 of file UnitContextTestBase\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
