.TH "cslalighttest.CslaDataProvider.CustomerWithError" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cslalighttest.CslaDataProvider.CustomerWithError
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.BusinessBase< CustomerWithError >\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFetchCriteria\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBAddBusinessRules\fP ()"
.br
.ti -1c
.RI "void \fBDataPortal_Fetch\fP (int criteria)"
.br
.ti -1c
.RI "void \fBDataPortal_Create\fP (int criteria)"
.br
.ti -1c
.RI "void \fBDataPortal_DeleteSelf\fP ()"
.br
.ti -1c
.RI "void \fBDataPortal_Delete\fP (int criteria)"
.br
.ti -1c
.RI "void \fBDataPortal_Insert\fP ()"
.br
.ti -1c
.RI "void \fBDataPortal_Update\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBId\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBName\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBMethod\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "bool \fBThrowException\fP\fC [get, set]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 20 of file CustomerWithError\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override void cslalighttest\&.CslaDataProvider\&.CustomerWithError\&.AddBusinessRules ()\fC [protected]\fP"

.PP
Definition at line 86 of file CustomerWithError\&.cs\&.
.SS "void cslalighttest\&.CslaDataProvider\&.CustomerWithError\&.DataPortal_Create (int criteria)\fC [protected]\fP"

.PP
Definition at line 142 of file CustomerWithError\&.cs\&.
.SS "void cslalighttest\&.CslaDataProvider\&.CustomerWithError\&.DataPortal_Delete (int criteria)\fC [protected]\fP"

.PP
Definition at line 155 of file CustomerWithError\&.cs\&.
.SS "void cslalighttest\&.CslaDataProvider\&.CustomerWithError\&.DataPortal_DeleteSelf ()\fC [protected]\fP"

.PP
Definition at line 149 of file CustomerWithError\&.cs\&.
.SS "void cslalighttest\&.CslaDataProvider\&.CustomerWithError\&.DataPortal_Fetch (int criteria)\fC [protected]\fP"

.PP
Definition at line 133 of file CustomerWithError\&.cs\&.
.SS "void cslalighttest\&.CslaDataProvider\&.CustomerWithError\&.DataPortal_Insert ()\fC [protected]\fP"

.PP
Definition at line 161 of file CustomerWithError\&.cs\&.
.SS "void cslalighttest\&.CslaDataProvider\&.CustomerWithError\&.DataPortal_Update ()\fC [protected]\fP"

.PP
Definition at line 167 of file CustomerWithError\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "int cslalighttest\&.CslaDataProvider\&.CustomerWithError\&.Id\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 34 of file CustomerWithError\&.cs\&.
.SS "string cslalighttest\&.CslaDataProvider\&.CustomerWithError\&.Method\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 60 of file CustomerWithError\&.cs\&.
.SS "string cslalighttest\&.CslaDataProvider\&.CustomerWithError\&.Name\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 47 of file CustomerWithError\&.cs\&.
.SS "bool cslalighttest\&.CslaDataProvider\&.CustomerWithError\&.ThrowException\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 74 of file CustomerWithError\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
