.TH "Csla.Core.UndoException" 3 "Thu Jul 22 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Core.UndoException \- Exception indicating a problem with the use of the n-level undo feature in CSLA \&.NET\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits System\&.Exception\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBUndoException\fP (string message, string typeName, string parentTypeName, int currentEditLevel, int expectedEditLevel)"
.br
.RI "Creates an instance of the object\&. "
.ti -1c
.RI "\fBUndoException\fP (string message, Exception ex)"
.br
.RI "Creates an instance of the object\&. "
.ti -1c
.RI "override void \fBGetObjectData\fP (System\&.Runtime\&.Serialization\&.SerializationInfo info, System\&.Runtime\&.Serialization\&.StreamingContext context)"
.br
.RI "Serializes the object\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBTypeName\fP"
.br
.RI "The type name of the object that caused this issue "
.ti -1c
.RI "string \fBParentTypeName\fP"
.br
.RI "The parent's type name of the object that caused this issue or null "
.ti -1c
.RI "int \fBCurrentEditLevel\fP"
.br
.RI "Object EditLevel "
.ti -1c
.RI "int \fBExpectedEditLevel\fP"
.br
.RI "Expected object EditLevel "
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBUndoException\fP (System\&.Runtime\&.Serialization\&.SerializationInfo info, System\&.Runtime\&.Serialization\&.StreamingContext context)"
.br
.RI "Creates an instance of the object for serialization\&. "
.in -1c
.SH "Detailed Description"
.PP 
Exception indicating a problem with the use of the n-level undo feature in CSLA \&.NET\&. 


.PP
Definition at line 19 of file UndoException\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Csla\&.Core\&.UndoException\&.UndoException (string message, string typeName, string parentTypeName, int currentEditLevel, int expectedEditLevel)"

.PP
Creates an instance of the object\&. 
.PP
\fBParameters\fP
.RS 4
\fImessage\fP Text describing the exception\&.
.br
\fItypeName\fP The type name of the object that caused this issue
.br
\fIparentTypeName\fP The parent's type name of the object that caused this issue or null
.br
\fIcurrentEditLevel\fP Object EditLevel
.br
\fIexpectedEditLevel\fP Expected object EditLevel
.RE
.PP

.PP
Definition at line 46 of file UndoException\&.cs\&.
.SS "Csla\&.Core\&.UndoException\&.UndoException (string message, Exception ex)"

.PP
Creates an instance of the object\&. 
.PP
\fBParameters\fP
.RS 4
\fImessage\fP Text describing the exception\&.
.br
\fIex\fP Inner exception\&.
.RE
.PP

.PP
Definition at line 60 of file UndoException\&.cs\&.
.SS "Csla\&.Core\&.UndoException\&.UndoException (System\&.Runtime\&.Serialization\&.SerializationInfo info, System\&.Runtime\&.Serialization\&.StreamingContext context)\fC [protected]\fP"

.PP
Creates an instance of the object for serialization\&. 
.PP
\fBParameters\fP
.RS 4
\fIinfo\fP Serialiation info object\&.
.br
\fIcontext\fP \fBSerialization\fP context object\&.
.RE
.PP

.PP
Definition at line 72 of file UndoException\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override void Csla\&.Core\&.UndoException\&.GetObjectData (System\&.Runtime\&.Serialization\&.SerializationInfo info, System\&.Runtime\&.Serialization\&.StreamingContext context)"

.PP
Serializes the object\&. 
.PP
\fBParameters\fP
.RS 4
\fIinfo\fP Serialiation info object\&.
.br
\fIcontext\fP \fBSerialization\fP context object\&.
.RE
.PP

.PP
Definition at line 83 of file UndoException\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "int Csla\&.Core\&.UndoException\&.CurrentEditLevel"

.PP
Object EditLevel 
.PP
Definition at line 32 of file UndoException\&.cs\&.
.SS "int Csla\&.Core\&.UndoException\&.ExpectedEditLevel"

.PP
Expected object EditLevel 
.PP
Definition at line 36 of file UndoException\&.cs\&.
.SS "string Csla\&.Core\&.UndoException\&.ParentTypeName"

.PP
The parent's type name of the object that caused this issue or null 
.PP
Definition at line 28 of file UndoException\&.cs\&.
.SS "string Csla\&.Core\&.UndoException\&.TypeName"

.PP
The type name of the object that caused this issue 
.PP
Definition at line 24 of file UndoException\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
