.TH "csla.netcore.test.DataPortal.DataPortalClientTests" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csla.netcore.test.DataPortal.DataPortalClientTests
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBCleanup\fP ()"
.br
.ti -1c
.RI "void \fBProxyFactoryGetTypeName\fP ()"
.br
.ti -1c
.RI "void \fBProxyFactoryGetTypeKeyNoResource\fP ()"
.br
.ti -1c
.RI "void \fBProxyFactoryGetTypeKeyResource\fP ()"
.br
.ti -1c
.RI "void \fBGetProxyDefault\fP ()"
.br
.ti -1c
.RI "void \fBGetProxyNoResource\fP ()"
.br
.ti -1c
.RI "void \fBGetProxyResource\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 25 of file DataPortalClientTests\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void csla\&.netcore\&.test\&.DataPortal\&.DataPortalClientTests\&.Cleanup ()"

.PP
Definition at line 28 of file DataPortalClientTests\&.cs\&.
.SS "void csla\&.netcore\&.test\&.DataPortal\&.DataPortalClientTests\&.GetProxyDefault ()"

.PP
Definition at line 57 of file DataPortalClientTests\&.cs\&.
.SS "void csla\&.netcore\&.test\&.DataPortal\&.DataPortalClientTests\&.GetProxyNoResource ()"

.PP
Definition at line 72 of file DataPortalClientTests\&.cs\&.
.SS "void csla\&.netcore\&.test\&.DataPortal\&.DataPortalClientTests\&.GetProxyResource ()"

.PP
Definition at line 92 of file DataPortalClientTests\&.cs\&.
.SS "void csla\&.netcore\&.test\&.DataPortal\&.DataPortalClientTests\&.ProxyFactoryGetTypeKeyNoResource ()"

.PP
Definition at line 43 of file DataPortalClientTests\&.cs\&.
.SS "void csla\&.netcore\&.test\&.DataPortal\&.DataPortalClientTests\&.ProxyFactoryGetTypeKeyResource ()"

.PP
Definition at line 50 of file DataPortalClientTests\&.cs\&.
.SS "void csla\&.netcore\&.test\&.DataPortal\&.DataPortalClientTests\&.ProxyFactoryGetTypeName ()"

.PP
Definition at line 36 of file DataPortalClientTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
