.TH "Csla.PropertyLoadException" 3 "Thu Jul 22 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.PropertyLoadException \- Exception indicating a failure to set a property's field\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits System\&.Exception\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPropertyLoadException\fP (string message)"
.br
.RI "Creates an instance of the object\&. "
.ti -1c
.RI "\fBPropertyLoadException\fP (string message, Exception ex)"
.br
.RI "Creates an instance of the object\&. "
.ti -1c
.RI "override void \fBGetObjectData\fP (System\&.Runtime\&.Serialization\&.SerializationInfo info, System\&.Runtime\&.Serialization\&.StreamingContext context)"
.br
.RI "Serializes the object\&. "
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBPropertyLoadException\fP (System\&.Runtime\&.Serialization\&.SerializationInfo info, System\&.Runtime\&.Serialization\&.StreamingContext context)"
.br
.RI "Creates an instance of the object for serialization\&. "
.in -1c
.SH "Detailed Description"
.PP 
Exception indicating a failure to set a property's field\&. 


.PP
Definition at line 18 of file PropertyLoadException\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Csla\&.PropertyLoadException\&.PropertyLoadException (string message)"

.PP
Creates an instance of the object\&. 
.PP
\fBParameters\fP
.RS 4
\fImessage\fP Text describing the exception\&.
.RE
.PP

.PP
Definition at line 24 of file PropertyLoadException\&.cs\&.
.SS "Csla\&.PropertyLoadException\&.PropertyLoadException (string message, Exception ex)"

.PP
Creates an instance of the object\&. 
.PP
\fBParameters\fP
.RS 4
\fImessage\fP Text describing the exception\&.
.br
\fIex\fP Inner exception\&.
.RE
.PP

.PP
Definition at line 33 of file PropertyLoadException\&.cs\&.
.SS "Csla\&.PropertyLoadException\&.PropertyLoadException (System\&.Runtime\&.Serialization\&.SerializationInfo info, System\&.Runtime\&.Serialization\&.StreamingContext context)\fC [protected]\fP"

.PP
Creates an instance of the object for serialization\&. 
.PP
\fBParameters\fP
.RS 4
\fIinfo\fP Serialiation info object\&.
.br
\fIcontext\fP \fBSerialization\fP context object\&.
.RE
.PP

.PP
Definition at line 43 of file PropertyLoadException\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override void Csla\&.PropertyLoadException\&.GetObjectData (System\&.Runtime\&.Serialization\&.SerializationInfo info, System\&.Runtime\&.Serialization\&.StreamingContext context)"

.PP
Serializes the object\&. 
.PP
\fBParameters\fP
.RS 4
\fIinfo\fP Serialiation info object\&.
.br
\fIcontext\fP \fBSerialization\fP context object\&.
.RE
.PP

.PP
Definition at line 52 of file PropertyLoadException\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
