.TH "Csla.InjectAttribute" 3 "Thu Jul 22 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.InjectAttribute \- Specifies a parameter that is provided via dependency injection\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Attribute\&.
.SH "Detailed Description"
.PP 
Specifies a parameter that is provided via dependency injection\&. 


.PP
Definition at line 17 of file DataPortalOperationAttributes\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
