.TH "Csla.Server.Dashboard.NullDashboard" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Server.Dashboard.NullDashboard \- \fBData\fP portal server dashboard that records no data and consumes no meaningful overhead\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.Server\&.Dashboard\&.IDashboard\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBDispose\fP ()"
.br
.RI "Dispose resources used by this object\&. "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
\fBData\fP portal server dashboard that records no data and consumes no meaningful overhead\&. 


.PP
Definition at line 17 of file NullDashboard\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Csla\&.Server\&.Dashboard\&.NullDashboard\&.Dispose ()"

.PP
Dispose resources used by this object\&. 
.PP
Definition at line 45 of file NullDashboard\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
