.TH "Csla.Rules.IBusinessRuleAsync" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Rules.IBusinessRuleAsync \- Interface defining a business/validation rule implementation\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.Rules\&.IBusinessRuleBase\fP\&.
.PP
Inherited by \fBCsla\&.Rules\&.BusinessRuleAsync\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "Task \fBExecuteAsync\fP (\fBIRuleContext\fP context)"
.br
.RI "Business or validation rule implementation\&. "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Interface defining a business/validation rule implementation\&. 


.PP
Definition at line 104 of file IBusinessRule\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "Task Csla\&.Rules\&.IBusinessRuleAsync\&.ExecuteAsync (\fBIRuleContext\fP context)"

.PP
Business or validation rule implementation\&. 
.PP
\fBParameters\fP
.RS 4
\fIcontext\fP Rule context object\&.
.RE
.PP

.PP
Implemented in \fBCsla\&.Rules\&.BusinessRuleAsync\fP, \fBCsla\&.Analyzers\&.IntegrationTests\&.CallingCompleteWithNameof\fP, \fBCsla\&.Analyzers\&.IntegrationTests\&.CallingComplete\fP, and \fBCsla\&.Analyzers\&.IntegrationTests\&.AsynchronousRuleNewSchool\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
