.TH "Csla.Test.GraphMerge.IdentityTests" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.GraphMerge.IdentityTests
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBIdentityInitializedBusinessBase\fP ()"
.br
.ti -1c
.RI "void \fBIdentityNewBaseChild\fP ()"
.br
.ti -1c
.RI "void \fBIdentityBaseClone\fP ()"
.br
.ti -1c
.RI "void \fBIdentityInitializedBusinessListBase\fP ()"
.br
.ti -1c
.RI "void \fBIdentityNewListChild\fP ()"
.br
.ti -1c
.RI "void \fBIdentityListClone\fP ()"
.br
.ti -1c
.RI "void \fBIdentityPostCloneIdentityManager\fP ()"
.br
.ti -1c
.RI "void \fBIdentityInitializedBusinessBindingListBase\fP ()"
.br
.ti -1c
.RI "void \fBIdentityInitializedDynamicListBase\fP ()"
.br
.ti -1c
.RI "void \fBIdentityInitializedDynamicBindingListBase\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 28 of file IdentityTests\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Csla\&.Test\&.GraphMerge\&.IdentityTests\&.IdentityBaseClone ()"

.PP
Definition at line 47 of file IdentityTests\&.cs\&.
.SS "void Csla\&.Test\&.GraphMerge\&.IdentityTests\&.IdentityInitializedBusinessBase ()"

.PP
Definition at line 31 of file IdentityTests\&.cs\&.
.SS "void Csla\&.Test\&.GraphMerge\&.IdentityTests\&.IdentityInitializedBusinessBindingListBase ()"

.PP
Definition at line 102 of file IdentityTests\&.cs\&.
.SS "void Csla\&.Test\&.GraphMerge\&.IdentityTests\&.IdentityInitializedBusinessListBase ()"

.PP
Definition at line 59 of file IdentityTests\&.cs\&.
.SS "void Csla\&.Test\&.GraphMerge\&.IdentityTests\&.IdentityInitializedDynamicBindingListBase ()"

.PP
Definition at line 118 of file IdentityTests\&.cs\&.
.SS "void Csla\&.Test\&.GraphMerge\&.IdentityTests\&.IdentityInitializedDynamicListBase ()"

.PP
Definition at line 110 of file IdentityTests\&.cs\&.
.SS "void Csla\&.Test\&.GraphMerge\&.IdentityTests\&.IdentityListClone ()"

.PP
Definition at line 76 of file IdentityTests\&.cs\&.
.SS "void Csla\&.Test\&.GraphMerge\&.IdentityTests\&.IdentityNewBaseChild ()"

.PP
Definition at line 38 of file IdentityTests\&.cs\&.
.SS "void Csla\&.Test\&.GraphMerge\&.IdentityTests\&.IdentityNewListChild ()"

.PP
Definition at line 66 of file IdentityTests\&.cs\&.
.SS "void Csla\&.Test\&.GraphMerge\&.IdentityTests\&.IdentityPostCloneIdentityManager ()"

.PP
Definition at line 87 of file IdentityTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
