.TH "Csla.WcfPortal.WcfErrorInfo" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.WcfPortal.WcfErrorInfo
.SH SYNOPSIS
.br
.PP
.PP
Inherits object, System\&.Runtime\&.Serialization\&.IExtensibleDataObject, and System\&.ComponentModel\&.INotifyPropertyChanged\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBRaisePropertyChanged\fP (string propertyName)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "System\&.Runtime\&.Serialization\&.ExtensionDataObject \fBExtensionData\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBExceptionTypeName\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBCsla\&.WcfPortal\&.WcfErrorInfo\fP \fBInnerError\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBMessage\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBSource\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBStackTrace\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBTargetSiteName\fP\fC [get, set]\fP"
.br
.in -1c
.SS "Events"

.in +1c
.ti -1c
.RI "System\&.ComponentModel\&.PropertyChangedEventHandler \fBPropertyChanged\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 239 of file Reference\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Csla\&.WcfPortal\&.WcfErrorInfo\&.RaisePropertyChanged (string propertyName)\fC [protected]\fP"

.PP
Definition at line 352 of file Reference\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "string Csla\&.WcfPortal\&.WcfErrorInfo\&.ExceptionTypeName\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 273 of file Reference\&.cs\&.
.SS "System\&.Runtime\&.Serialization\&.ExtensionDataObject Csla\&.WcfPortal\&.WcfErrorInfo\&.ExtensionData\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 263 of file Reference\&.cs\&.
.SS "\fBCsla\&.WcfPortal\&.WcfErrorInfo\fP Csla\&.WcfPortal\&.WcfErrorInfo\&.InnerError\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 286 of file Reference\&.cs\&.
.SS "string Csla\&.WcfPortal\&.WcfErrorInfo\&.Message\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 299 of file Reference\&.cs\&.
.SS "string Csla\&.WcfPortal\&.WcfErrorInfo\&.Source\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 312 of file Reference\&.cs\&.
.SS "string Csla\&.WcfPortal\&.WcfErrorInfo\&.StackTrace\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 325 of file Reference\&.cs\&.
.SS "string Csla\&.WcfPortal\&.WcfErrorInfo\&.TargetSiteName\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 338 of file Reference\&.cs\&.
.SH "Event Documentation"
.PP 
.SS "System\&.ComponentModel\&.PropertyChangedEventHandler Csla\&.WcfPortal\&.WcfErrorInfo\&.PropertyChanged"

.PP
Definition at line 350 of file Reference\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
