.TH "cslalighttest.CslaDataProvider.Customer.FetchCriteria" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cslalighttest.CslaDataProvider.Customer.FetchCriteria
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.CriteriaBase< FetchCriteria >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFetchCriteria\fP ()"
.br
.ti -1c
.RI "\fBFetchCriteria\fP (int customerID)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnGetState\fP (\fBCsla\&.Serialization\&.Mobile\&.SerializationInfo\fP info, \fBStateMode\fP mode)"
.br
.ti -1c
.RI "override void \fBOnSetState\fP (\fBCsla\&.Serialization\&.Mobile\&.SerializationInfo\fP info, \fBStateMode\fP mode)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBCustomerID\fP\fC [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 181 of file Silverlight/Server/CslaDataProvider/Customer\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "cslalighttest\&.CslaDataProvider\&.Customer\&.FetchCriteria\&.FetchCriteria ()"

.PP
Definition at line 183 of file Silverlight/Server/CslaDataProvider/Customer\&.cs\&.
.SS "cslalighttest\&.CslaDataProvider\&.Customer\&.FetchCriteria\&.FetchCriteria (int customerID)"

.PP
Definition at line 185 of file Silverlight/Server/CslaDataProvider/Customer\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override void cslalighttest\&.CslaDataProvider\&.Customer\&.FetchCriteria\&.OnGetState (\fBCsla\&.Serialization\&.Mobile\&.SerializationInfo\fP info, \fBStateMode\fP mode)\fC [protected]\fP"

.PP
Definition at line 201 of file Silverlight/Server/CslaDataProvider/Customer\&.cs\&.
.SS "override void cslalighttest\&.CslaDataProvider\&.Customer\&.FetchCriteria\&.OnSetState (\fBCsla\&.Serialization\&.Mobile\&.SerializationInfo\fP info, \fBStateMode\fP mode)\fC [protected]\fP"

.PP
Definition at line 206 of file Silverlight/Server/CslaDataProvider/Customer\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "int cslalighttest\&.CslaDataProvider\&.Customer\&.FetchCriteria\&.CustomerID\fC [get]\fP"

.PP
Definition at line 193 of file Silverlight/Server/CslaDataProvider/Customer\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
