.TH "Csla.Test.DataPortal.ObjectCriteriaCreate" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.DataPortal.ObjectCriteriaCreate
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.BusinessBase< ObjectCriteriaCreate >\fP\&.
.PP
Inherited by \fBCsla\&.Test\&.DataPortal\&.ObjectCriteriaCreateSubtype\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 412 of file ServiceProviderMethodCallerTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
