.TH "Csla.Test.DataPortal.ClassA" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.DataPortal.ClassA
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.BusinessBase< ClassA >\fP\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBClassA\fP \fBGetClassA\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBClassB\fP \fBChildB\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBDisposableClass\fP \fBDisposableClass\fP\fC [get, set]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 43 of file DisposeScopeTest\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "static \fBClassA\fP Csla\&.Test\&.DataPortal\&.ClassA\&.GetClassA ()\fC [static]\fP"

.PP
Definition at line 48 of file DisposeScopeTest\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "\fBClassB\fP Csla\&.Test\&.DataPortal\&.ClassA\&.ChildB\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 45 of file DisposeScopeTest\&.cs\&.
.SS "\fBDisposableClass\fP Csla\&.Test\&.DataPortal\&.ClassA\&.DisposableClass\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 46 of file DisposeScopeTest\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
