.TH "Csla.Test.Linq" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.Linq
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBLinqObservableCollectionTest\fP"
.br
.RI "This is a test class for \fBLinqObservableCollectionTest\fP and is intended to contain all \fBLinqObservableCollectionTest\fP Unit Tests /summary> "
.ti -1c
.RI "class \fBTestList\fP"
.br
.ti -1c
.RI "class \fBTestItem\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
