.TH "Csla.Core.ReadOnlyObservableBindingList< C >" 3 "Thu Jul 22 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Core.ReadOnlyObservableBindingList< C > \- A readonly version of \fBObservableBindingList\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.Core\&.ObservableBindingList< C >\fP, and Csla\&.Core\&.IReadOnlyBindingList\&.
.PP
Inherited by \fBCsla\&.ReadOnlyListBase< T, C >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBReadOnlyObservableBindingList\fP ()"
.br
.RI "Creates an instance of the object\&. "
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnCollectionChanged\fP (NotifyCollectionChangedEventArgs e)"
.br
.RI "Method invoked when collection is changed\&. "
.ti -1c
.RI "override void \fBSetLoadListMode\fP (bool enabled)"
.br
.RI "Sets the LoadListMode for the collection "
.ti -1c
.RI "override void \fBOnGetState\fP (\fBCsla\&.Serialization\&.Mobile\&.SerializationInfo\fP info)"
.br
.RI "Override this method to insert your field values into the MobileFormatter serialzation stream\&. "
.ti -1c
.RI "override void \fBOnSetState\fP (\fBCsla\&.Serialization\&.Mobile\&.SerializationInfo\fP info)"
.br
.RI "Override this method to retrieve your field values from the MobileFormatter serialzation stream\&. "
.ti -1c
.RI "override void \fBOnSetChildren\fP (\fBCsla\&.Serialization\&.Mobile\&.SerializationInfo\fP info, \fBCsla\&.Serialization\&.Mobile\&.MobileFormatter\fP formatter)"
.br
.RI "Override this method to retrieve your child object references from the MobileFormatter serialzation stream\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "bool \fBIsReadOnly\fP\fC [get, protected set]\fP"
.br
.RI "Gets or sets a value indicating whether the list is readonly\&. "
.in -1c
.SH "Detailed Description"
.PP 
A readonly version of \fBObservableBindingList\fP\&. 


.PP
\fBTemplate Parameters\fP
.RS 4
\fIC\fP Type of item contained in the list\&.
.RE
.PP
.PP
This is a subclass of \fBObservableBindingList\fP that implements a readonly list, preventing adding and removing of items from the list\&. Use the IsReadOnly property to unlock the list for loading/unloading data\&. 
.PP
Definition at line 28 of file ReadOnlyObservableBindingList\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBCsla\&.Core\&.ReadOnlyObservableBindingList\fP< C >\&.\fBReadOnlyObservableBindingList\fP ()"

.PP
Creates an instance of the object\&. 
.PP
Definition at line 35 of file ReadOnlyObservableBindingList\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override void \fBCsla\&.Core\&.ReadOnlyObservableBindingList\fP< C >\&.OnCollectionChanged (NotifyCollectionChangedEventArgs e)\fC [protected]\fP"

.PP
Method invoked when collection is changed\&. 
.PP
\fBParameters\fP
.RS 4
\fIe\fP Arguments
.RE
.PP

.PP
Definition at line 52 of file ReadOnlyObservableBindingList\&.cs\&.
.SS "override void \fBCsla\&.Core\&.ReadOnlyObservableBindingList\fP< C >\&.OnGetState (\fBCsla\&.Serialization\&.Mobile\&.SerializationInfo\fP info)\fC [protected]\fP"

.PP
Override this method to insert your field values into the MobileFormatter serialzation stream\&. 
.PP
\fBParameters\fP
.RS 4
\fIinfo\fP Object containing the data to serialize\&. 
.RE
.PP

.PP
Definition at line 104 of file ReadOnlyObservableBindingList\&.cs\&.
.SS "override void \fBCsla\&.Core\&.ReadOnlyObservableBindingList\fP< C >\&.OnSetChildren (\fBCsla\&.Serialization\&.Mobile\&.SerializationInfo\fP info, \fBCsla\&.Serialization\&.Mobile\&.MobileFormatter\fP formatter)\fC [protected]\fP"

.PP
Override this method to retrieve your child object references from the MobileFormatter serialzation stream\&. 
.PP
\fBParameters\fP
.RS 4
\fIinfo\fP Object containing the data to serialize\&. 
.br
\fIformatter\fP Reference to MobileFormatter instance\&. Use this to convert child references to/from reference id values\&. 
.RE
.PP

.PP
Definition at line 134 of file ReadOnlyObservableBindingList\&.cs\&.
.SS "override void \fBCsla\&.Core\&.ReadOnlyObservableBindingList\fP< C >\&.OnSetState (\fBCsla\&.Serialization\&.Mobile\&.SerializationInfo\fP info)\fC [protected]\fP"

.PP
Override this method to retrieve your field values from the MobileFormatter serialzation stream\&. 
.PP
\fBParameters\fP
.RS 4
\fIinfo\fP Object containing the data to serialize\&. 
.RE
.PP

.PP
Definition at line 117 of file ReadOnlyObservableBindingList\&.cs\&.
.SS "override void \fBCsla\&.Core\&.ReadOnlyObservableBindingList\fP< C >\&.SetLoadListMode (bool enabled)\fC [protected]\fP"

.PP
Sets the LoadListMode for the collection 
.PP
\fBParameters\fP
.RS 4
\fIenabled\fP Enable or disable mode
.RE
.PP

.PP
Definition at line 87 of file ReadOnlyObservableBindingList\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "bool \fBCsla\&.Core\&.ReadOnlyObservableBindingList\fP< C >\&.IsReadOnly\fC [get]\fP, \fC [protected set]\fP"

.PP
Gets or sets a value indicating whether the list is readonly\&. Subclasses can set this value to unlock the collection in order to alter the collection's data\&. 
.PP
True indicates that the list is readonly\&.
.PP
Definition at line 71 of file ReadOnlyObservableBindingList\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
