.TH "Csla.Xaml.ApplicationContextManager" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Xaml.ApplicationContextManager \- \fBApplicationContextManager\fP for WPF applications  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.Core\&.ApplicationContextManager\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override IPrincipal \fBGetUser\fP ()"
.br
.RI "Gets the current principal\&. "
.ti -1c
.RI "override void \fBSetUser\fP (IPrincipal principal)"
.br
.RI "Sets the current principal\&. "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
\fBApplicationContextManager\fP for WPF applications 


.PP
Definition at line 16 of file Csla\&.Xaml\&.Shared/ApplicationContextManager\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override IPrincipal Csla\&.Xaml\&.ApplicationContextManager\&.GetUser ()\fC [virtual]\fP"

.PP
Gets the current principal\&. 
.PP
\fBReturns\fP
.RS 4

.RE
.PP

.PP
Reimplemented from \fBCsla\&.Core\&.ApplicationContextManager\fP\&.
.PP
Definition at line 24 of file Csla\&.Xaml\&.Shared/ApplicationContextManager\&.cs\&.
.SS "override void Csla\&.Xaml\&.ApplicationContextManager\&.SetUser (IPrincipal principal)\fC [virtual]\fP"

.PP
Sets the current principal\&. 
.PP
\fBParameters\fP
.RS 4
\fIprincipal\fP Principal object\&.
.RE
.PP

.PP
Reimplemented from \fBCsla\&.Core\&.ApplicationContextManager\fP\&.
.PP
Definition at line 42 of file Csla\&.Xaml\&.Shared/ApplicationContextManager\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
