.TH "Csla.Test.Basic.TestCollection" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.Basic.TestCollection
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.BusinessBindingListBase< TestCollection, TestItem >\fP, and \fBCsla\&.BusinessBindingListBase< TestCollection, TestItem >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTestCollection\fP ()"
.br
.ti -1c
.RI "\fBTestCollection\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBTestCollection\fP \fBGetList\fP ()"
.br
.ti -1c
.RI "static \fBTestCollection\fP \fBGetList\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override object \fBAddNewCore\fP ()"
.br
.ti -1c
.RI "override object \fBAddNewCore\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 54 of file csla\&.netcore\&.test/Basic/CollectionTests\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Csla\&.Test\&.Basic\&.TestCollection\&.TestCollection ()"

.PP
Definition at line 56 of file csla\&.netcore\&.test/Basic/CollectionTests\&.cs\&.
.SS "Csla\&.Test\&.Basic\&.TestCollection\&.TestCollection ()"

.PP
Definition at line 56 of file Csla\&.test/Basic/CollectionTests\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override object Csla\&.Test\&.Basic\&.TestCollection\&.AddNewCore ()\fC [protected]\fP"

.PP
Definition at line 61 of file csla\&.netcore\&.test/Basic/CollectionTests\&.cs\&.
.SS "override object Csla\&.Test\&.Basic\&.TestCollection\&.AddNewCore ()\fC [protected]\fP"

.PP
Definition at line 61 of file Csla\&.test/Basic/CollectionTests\&.cs\&.
.SS "static \fBTestCollection\fP Csla\&.Test\&.Basic\&.TestCollection\&.GetList ()\fC [static]\fP"

.PP
Definition at line 68 of file csla\&.netcore\&.test/Basic/CollectionTests\&.cs\&.
.SS "static \fBTestCollection\fP Csla\&.Test\&.Basic\&.TestCollection\&.GetList ()\fC [static]\fP"

.PP
Definition at line 68 of file Csla\&.test/Basic/CollectionTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
