.TH "Csla.Test.BasicModern.BasicModernTests" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.BasicModern.BasicModernTests
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBCreateGraph\fP ()"
.br
.ti -1c
.RI "void \fBMakeOldMetastateEvents\fP ()"
.br
.ti -1c
.RI "void \fBMarkDeletedMetastateEvents\fP ()"
.br
.ti -1c
.RI "void \fBRootChangedMetastateEventsId\fP ()"
.br
.ti -1c
.RI "void \fBRootChangedMetastateEventsName\fP ()"
.br
.ti -1c
.RI "void \fBRootChangedMetastateEventsChild\fP ()"
.br
.ti -1c
.RI "void \fBEditLevelsWorkWithMobileFormatter\fP ()"
.br
.ti -1c
.RI "void \fBCloneWorkswithMobileFormatter\fP ()"
.br
.ti -1c
.RI "void \fBCreateGraph\fP ()"
.br
.ti -1c
.RI "void \fBMakeOldMetastateEvents\fP ()"
.br
.ti -1c
.RI "void \fBMarkDeletedMetastateEvents\fP ()"
.br
.ti -1c
.RI "void \fBRootChangedMetastateEventsId\fP ()"
.br
.ti -1c
.RI "void \fBRootChangedMetastateEventsName\fP ()"
.br
.ti -1c
.RI "void \fBRootChangedMetastateEventsChild\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 20 of file BasicModernTests\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Csla\&.Test\&.BasicModern\&.BasicModernTests\&.CloneWorkswithMobileFormatter ()"

.PP
Definition at line 53 of file BasicModernTests\&.cs\&.
.SS "void Csla\&.Test\&.BasicModern\&.BasicModernTests\&.CreateGraph ()"

.PP
Definition at line 23 of file BasicModernTests\&.cs\&.
.SS "void Csla\&.Test\&.BasicModern\&.BasicModernTests\&.CreateGraph ()"

.PP
Definition at line 89 of file BasicModernTests\&.cs\&.
.SS "void Csla\&.Test\&.BasicModern\&.BasicModernTests\&.EditLevelsWorkWithMobileFormatter ()"

.PP
Definition at line 23 of file BasicModernTests\&.cs\&.
.SS "void Csla\&.Test\&.BasicModern\&.BasicModernTests\&.MakeOldMetastateEvents ()"

.PP
Definition at line 32 of file BasicModernTests\&.cs\&.
.SS "void Csla\&.Test\&.BasicModern\&.BasicModernTests\&.MakeOldMetastateEvents ()"

.PP
Definition at line 98 of file BasicModernTests\&.cs\&.
.SS "void Csla\&.Test\&.BasicModern\&.BasicModernTests\&.MarkDeletedMetastateEvents ()"

.PP
Definition at line 53 of file BasicModernTests\&.cs\&.
.SS "void Csla\&.Test\&.BasicModern\&.BasicModernTests\&.MarkDeletedMetastateEvents ()"

.PP
Definition at line 119 of file BasicModernTests\&.cs\&.
.SS "void Csla\&.Test\&.BasicModern\&.BasicModernTests\&.RootChangedMetastateEventsChild ()"

.PP
Definition at line 144 of file BasicModernTests\&.cs\&.
.SS "void Csla\&.Test\&.BasicModern\&.BasicModernTests\&.RootChangedMetastateEventsChild ()"

.PP
Definition at line 210 of file BasicModernTests\&.cs\&.
.SS "void Csla\&.Test\&.BasicModern\&.BasicModernTests\&.RootChangedMetastateEventsId ()"

.PP
Definition at line 76 of file BasicModernTests\&.cs\&.
.SS "void Csla\&.Test\&.BasicModern\&.BasicModernTests\&.RootChangedMetastateEventsId ()"

.PP
Definition at line 142 of file BasicModernTests\&.cs\&.
.SS "void Csla\&.Test\&.BasicModern\&.BasicModernTests\&.RootChangedMetastateEventsName ()"

.PP
Definition at line 99 of file BasicModernTests\&.cs\&.
.SS "void Csla\&.Test\&.BasicModern\&.BasicModernTests\&.RootChangedMetastateEventsName ()"

.PP
Definition at line 165 of file BasicModernTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
