.TH "Csla.Server.DataPortal.NullAuthorizer" 3 "Thu Jul 22 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Server.DataPortal.NullAuthorizer \- Default implementation of the authorizer that allows all data portal calls to pass\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.Server\&.IAuthorizeDataPortal\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBAuthorize\fP (\fBAuthorizeRequest\fP clientRequest)"
.br
.RI "Creates an instance of the type\&. "
.in -1c
.SH "Detailed Description"
.PP 
Default implementation of the authorizer that allows all data portal calls to pass\&. 


.PP
Definition at line 700 of file Server/DataPortal\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Csla\&.Server\&.DataPortal\&.NullAuthorizer\&.Authorize (\fBAuthorizeRequest\fP clientRequest)"

.PP
Creates an instance of the type\&. 
.PP
\fBParameters\fP
.RS 4
\fIclientRequest\fP Client request information\&. 
.RE
.PP

.PP
Implements \fBCsla\&.Server\&.IAuthorizeDataPortal\fP\&.
.PP
Definition at line 708 of file Server/DataPortal\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
