.TH "Csla.Channels.Grpc.GrpcProxy" 3 "Thu Jul 22 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Channels.Grpc.GrpcProxy \- Implements a data portal proxy to relay data portal calls to a remote application server by using gRPC\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.DataPortalClient\&.DataPortalProxy\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGrpcProxy\fP (string dataPortalUrl)"
.br
.RI "Creates an instance of the object, initializing it to use the supplied URL\&. "
.ti -1c
.RI "\fBGrpcProxy\fP (GrpcChannel channel)"
.br
.RI "Creates an instance of the object, initializing it to use the supplied GrpcChannel object\&. "
.ti -1c
.RI "\fBGrpcProxy\fP (GrpcChannel channel, string dataPortalUrl)"
.br
.RI "Creates an instance of the object, initializing it to use the supplied GrpcChannel object and URL\&. "
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual GrpcChannel \fBGetChannel\fP ()"
.br
.RI "Gets the GrpcChannel used by the gRPC client\&. "
.ti -1c
.RI "virtual GrpcService\&.GrpcServiceClient \fBGetGrpcClient\fP ()"
.br
.RI "Get gRPC client object used by data portal\&. "
.ti -1c
.RI "override async Task< byte[]> \fBCallDataPortalServer\fP (byte[] serialized, string operation, string routingToken, bool isSync)"
.br
.RI "Create message and send to \fBGrpc\fP server\&. Return Response from server "
.in -1c
.SS "Static Protected Member Functions"

.in +1c
.ti -1c
.RI "static void \fBSetChannel\fP (GrpcChannel channel)"
.br
.RI "Sets the GrpcChannel used by gRPC clients\&. "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Implements a data portal proxy to relay data portal calls to a remote application server by using gRPC\&. 


.PP
Definition at line 27 of file GrpcProxy\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Csla\&.Channels\&.Grpc\&.GrpcProxy\&.GrpcProxy (string dataPortalUrl)"

.PP
Creates an instance of the object, initializing it to use the supplied URL\&. 
.PP
\fBParameters\fP
.RS 4
\fIdataPortalUrl\fP \fBServer\fP endpoint URL
.RE
.PP

.PP
Definition at line 34 of file GrpcProxy\&.cs\&.
.SS "Csla\&.Channels\&.Grpc\&.GrpcProxy\&.GrpcProxy (GrpcChannel channel)"

.PP
Creates an instance of the object, initializing it to use the supplied GrpcChannel object\&. 
.PP
\fBParameters\fP
.RS 4
\fIchannel\fP GrpcChannel instance
.RE
.PP

.PP
Definition at line 43 of file GrpcProxy\&.cs\&.
.SS "Csla\&.Channels\&.Grpc\&.GrpcProxy\&.GrpcProxy (GrpcChannel channel, string dataPortalUrl)"

.PP
Creates an instance of the object, initializing it to use the supplied GrpcChannel object and URL\&. 
.PP
\fBParameters\fP
.RS 4
\fIchannel\fP GrpcChannel instance
.br
\fIdataPortalUrl\fP \fBServer\fP endpoint URL
.RE
.PP

.PP
Definition at line 53 of file GrpcProxy\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override async Task<byte[]> Csla\&.Channels\&.Grpc\&.GrpcProxy\&.CallDataPortalServer (byte[] serialized, string operation, string routingToken, bool isSync)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Create message and send to \fBGrpc\fP server\&. Return Response from server 
.PP
\fBParameters\fP
.RS 4
\fIserialized\fP Serialised request
.br
\fIoperation\fP \fBDataPortal\fP operation
.br
\fIroutingToken\fP Routing Tag for server
.br
\fIisSync\fP True if the client-side proxy should synchronously invoke the server\&.
.RE
.PP
\fBReturns\fP
.RS 4
Serialised response from server
.RE
.PP

.PP
Implements \fBCsla\&.DataPortalClient\&.DataPortalProxy\fP\&.
.PP
Definition at line 105 of file GrpcProxy\&.cs\&.
.SS "virtual GrpcChannel Csla\&.Channels\&.Grpc\&.GrpcProxy\&.GetChannel ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Gets the GrpcChannel used by the gRPC client\&. 
.PP
\fBReturns\fP
.RS 4

.RE
.PP

.PP
Definition at line 66 of file GrpcProxy\&.cs\&.
.SS "virtual GrpcService\&.GrpcServiceClient Csla\&.Channels\&.Grpc\&.GrpcProxy\&.GetGrpcClient ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Get gRPC client object used by data portal\&. 
.PP
\fBReturns\fP
.RS 4

.RE
.PP

.PP
Definition at line 91 of file GrpcProxy\&.cs\&.
.SS "static void Csla\&.Channels\&.Grpc\&.GrpcProxy\&.SetChannel (GrpcChannel channel)\fC [static]\fP, \fC [protected]\fP"

.PP
Sets the GrpcChannel used by gRPC clients\&. 
.PP
\fBParameters\fP
.RS 4
\fIchannel\fP GrpcChannel instance
.RE
.PP

.PP
Definition at line 80 of file GrpcProxy\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
