.TH "Csla.Blazor.PropertyInfo" 3 "Thu Jul 22 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Blazor.PropertyInfo \- Exposes metastate for a property\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.Blazor\&.IPropertyInfo\fP, and INotifyPropertyChanged\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPropertyInfo\fP (object model, string propertyName)"
.br
.RI "Creates an instance of the type\&. "
.ti -1c
.RI "void \fBRefresh\fP ()"
.br
.RI "Indicate that all properties have changed to trigger a UI refresh of all values\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "object \fBModel\fP\fC [get]\fP"
.br
.RI "Gets the model "
.ti -1c
.RI "object \fBValue\fP\fC [get, set]\fP"
.br
.RI "Gets or sets the value of the property "
.ti -1c
.RI "string \fBFriendlyName\fP\fC [get]\fP"
.br
.RI "Gets the friendly name for the property\&. "
.ti -1c
.RI "string \fBPropertyName\fP\fC [get]\fP"
.br
.RI "Gets the property name for the property\&. "
.ti -1c
.RI "string \fBErrorText\fP\fC [get]\fP"
.br
.RI "Gets the validation error messages for a property on the Model "
.ti -1c
.RI "string \fBWarningText\fP\fC [get]\fP"
.br
.RI "Gets the validation warning messages for a property on the Model "
.ti -1c
.RI "string \fBInformationText\fP\fC [get]\fP"
.br
.RI "Gets the validation information messages for a property on the Model "
.ti -1c
.RI "bool \fBCanRead\fP\fC [get]\fP"
.br
.RI "Gets a value indicating whether the current user is authorized to read the property on the Model "
.ti -1c
.RI "bool \fBCanWrite\fP\fC [get]\fP"
.br
.RI "Gets a value indicating whether the current user is authorized to change the property on the Model "
.ti -1c
.RI "bool \fBIsBusy\fP\fC [get]\fP"
.br
.RI "Gets a value indicating whether the property on the Model is busy "
.in -1c
.SS "Events"

.in +1c
.ti -1c
.RI "PropertyChangedEventHandler \fBPropertyChanged\fP"
.br
.RI "Event raised when a property changes\&. "
.in -1c
.SH "Detailed Description"
.PP 
Exposes metastate for a property\&. 


.PP
Definition at line 16 of file Csla\&.Blazor/PropertyInfo\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Csla\&.Blazor\&.PropertyInfo\&.PropertyInfo (object model, string propertyName)"

.PP
Creates an instance of the type\&. 
.PP
\fBParameters\fP
.RS 4
\fImodel\fP Model object
.br
\fIpropertyName\fP Property name
.RE
.PP

.PP
Definition at line 30 of file Csla\&.Blazor/PropertyInfo\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Csla\&.Blazor\&.PropertyInfo\&.Refresh ()"

.PP
Indicate that all properties have changed to trigger a UI refresh of all values\&. 
.PP
Implements \fBCsla\&.Blazor\&.IPropertyInfo\fP\&.
.PP
Definition at line 50 of file Csla\&.Blazor/PropertyInfo\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "bool Csla\&.Blazor\&.PropertyInfo\&.CanRead\fC [get]\fP"

.PP
Gets a value indicating whether the current user is authorized to read the property on the Model 
.PP
\fBReturns\fP
.RS 4

.RE
.PP

.PP
Definition at line 142 of file Csla\&.Blazor/PropertyInfo\&.cs\&.
.SS "bool Csla\&.Blazor\&.PropertyInfo\&.CanWrite\fC [get]\fP"

.PP
Gets a value indicating whether the current user is authorized to change the property on the Model 
.PP
\fBReturns\fP
.RS 4

.RE
.PP

.PP
Definition at line 158 of file Csla\&.Blazor/PropertyInfo\&.cs\&.
.SS "string Csla\&.Blazor\&.PropertyInfo\&.ErrorText\fC [get]\fP"

.PP
Gets the validation error messages for a property on the Model 
.PP
\fBReturns\fP
.RS 4

.RE
.PP

.PP
Definition at line 94 of file Csla\&.Blazor/PropertyInfo\&.cs\&.
.SS "string Csla\&.Blazor\&.PropertyInfo\&.FriendlyName\fC [get]\fP"

.PP
Gets the friendly name for the property\&. 
.PP
Definition at line 75 of file Csla\&.Blazor/PropertyInfo\&.cs\&.
.SS "string Csla\&.Blazor\&.PropertyInfo\&.InformationText\fC [get]\fP"

.PP
Gets the validation information messages for a property on the Model 
.PP
\fBReturns\fP
.RS 4

.RE
.PP

.PP
Definition at line 126 of file Csla\&.Blazor/PropertyInfo\&.cs\&.
.SS "bool Csla\&.Blazor\&.PropertyInfo\&.IsBusy\fC [get]\fP"

.PP
Gets a value indicating whether the property on the Model is busy 
.PP
\fBReturns\fP
.RS 4

.RE
.PP

.PP
Definition at line 174 of file Csla\&.Blazor/PropertyInfo\&.cs\&.
.SS "object Csla\&.Blazor\&.PropertyInfo\&.Model\fC [get]\fP, \fC [protected]\fP"

.PP
Gets the model 
.PP
Definition at line 23 of file Csla\&.Blazor/PropertyInfo\&.cs\&.
.SS "string Csla\&.Blazor\&.PropertyInfo\&.PropertyName\fC [get]\fP"

.PP
Gets the property name for the property\&. 
.PP
Definition at line 87 of file Csla\&.Blazor/PropertyInfo\&.cs\&.
.SS "object Csla\&.Blazor\&.PropertyInfo\&.Value\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the value of the property 
.PP
Definition at line 59 of file Csla\&.Blazor/PropertyInfo\&.cs\&.
.SS "string Csla\&.Blazor\&.PropertyInfo\&.WarningText\fC [get]\fP"

.PP
Gets the validation warning messages for a property on the Model 
.PP
\fBReturns\fP
.RS 4

.RE
.PP

.PP
Definition at line 110 of file Csla\&.Blazor/PropertyInfo\&.cs\&.
.SH "Event Documentation"
.PP 
.SS "PropertyChangedEventHandler Csla\&.Blazor\&.PropertyInfo\&.PropertyChanged"

.PP
Event raised when a property changes\&. 
.PP
Definition at line 188 of file Csla\&.Blazor/PropertyInfo\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
