.TH "Csla.Testing.Business.EditableRootTests.RootWithNullableProperty" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Testing.Business.EditableRootTests.RootWithNullableProperty
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.BusinessBase< RootWithNullableProperty >\fP\&.
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static readonly \fBPropertyInfo\fP< \fBSmartDate\fP?> \fBTodayProperty\fP = RegisterProperty<\fBSmartDate\fP?>(c => c\&.Today)"
.br
.ti -1c
.RI "static readonly \fBPropertyInfo\fP< DateTime?> \fBOtherDateProperty\fP = RegisterProperty<DateTime?>(c => c\&.OtherDate)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBSmartDate\fP? \fBToday\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "DateTime? \fBOtherDate\fP\fC [get, set]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 7 of file RootWithNullableProperty\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "readonly \fBPropertyInfo\fP<DateTime?> Csla\&.Testing\&.Business\&.EditableRootTests\&.RootWithNullableProperty\&.OtherDateProperty = RegisterProperty<DateTime?>(c => c\&.OtherDate)\fC [static]\fP"

.PP
Definition at line 16 of file RootWithNullableProperty\&.cs\&.
.SS "readonly \fBPropertyInfo\fP<\fBSmartDate\fP?> Csla\&.Testing\&.Business\&.EditableRootTests\&.RootWithNullableProperty\&.TodayProperty = RegisterProperty<\fBSmartDate\fP?>(c => c\&.Today)\fC [static]\fP"

.PP
Definition at line 9 of file RootWithNullableProperty\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "DateTime? Csla\&.Testing\&.Business\&.EditableRootTests\&.RootWithNullableProperty\&.OtherDate\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 17 of file RootWithNullableProperty\&.cs\&.
.SS "\fBSmartDate\fP? Csla\&.Testing\&.Business\&.EditableRootTests\&.RootWithNullableProperty\&.Today\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 10 of file RootWithNullableProperty\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
