.TH "Csla.Web.Design.CslaDataSourceDesigner" 3 "Thu Jul 22 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Web.Design.CslaDataSourceDesigner \- Implements designer support for \fBCslaDataSource\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits DataSourceDesigner\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBInitialize\fP (IComponent component)"
.br
.RI "Initialize the designer component\&. "
.ti -1c
.RI "override DesignerDataSourceView \fBGetView\fP (string viewName)"
.br
.RI "Returns the default view for this designer\&. "
.ti -1c
.RI "override string[] \fBGetViewNames\fP ()"
.br
.RI "Return a list of available views\&. "
.ti -1c
.RI "override void \fBRefreshSchema\fP (bool preferSilent)"
.br
.RI "Refreshes the schema for the data\&. "
.ti -1c
.RI "override void \fBConfigure\fP ()"
.br
.RI "Invoke the design time configuration support provided by the control\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override bool \fBCanRefreshSchema\fP\fC [get]\fP"
.br
.RI "Get a value indicating whether the control can refresh its schema\&. "
.ti -1c
.RI "override bool \fBCanConfigure\fP\fC [get]\fP"
.br
.RI "Get a value indicating whether this control supports design time configuration\&. "
.ti -1c
.RI "override bool \fBAllowResize\fP\fC [get]\fP"
.br
.RI "Get a value indicating whether the control can be resized\&. "
.in -1c
.SH "Detailed Description"
.PP 
Implements designer support for \fBCslaDataSource\fP\&. 


.PP
Definition at line 20 of file CslaDataSourceDesigner\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override void Csla\&.Web\&.Design\&.CslaDataSourceDesigner\&.Configure ()"

.PP
Invoke the design time configuration support provided by the control\&. 
.PP
Definition at line 98 of file CslaDataSourceDesigner\&.cs\&.
.SS "override DesignerDataSourceView Csla\&.Web\&.Design\&.CslaDataSourceDesigner\&.GetView (string viewName)"

.PP
Returns the default view for this designer\&. 
.PP
\fBParameters\fP
.RS 4
\fIviewName\fP Ignored
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP
.PP
This designer supports only a 'Default' view\&. 
.PP
Definition at line 52 of file CslaDataSourceDesigner\&.cs\&.
.SS "override string [] Csla\&.Web\&.Design\&.CslaDataSourceDesigner\&.GetViewNames ()"

.PP
Return a list of available views\&. This designer supports only a 'Default' view\&. 
.PP
Definition at line 67 of file CslaDataSourceDesigner\&.cs\&.
.SS "override void Csla\&.Web\&.Design\&.CslaDataSourceDesigner\&.Initialize (IComponent component)"

.PP
Initialize the designer component\&. 
.PP
\fBParameters\fP
.RS 4
\fIcomponent\fP The \fBCslaDataSource\fP control to be designed\&.
.RE
.PP

.PP
Definition at line 31 of file CslaDataSourceDesigner\&.cs\&.
.SS "override void Csla\&.Web\&.Design\&.CslaDataSourceDesigner\&.RefreshSchema (bool preferSilent)"

.PP
Refreshes the schema for the data\&. 
.PP
\fBParameters\fP
.RS 4
\fIpreferSilent\fP 
.RE
.PP

.PP
Definition at line 77 of file CslaDataSourceDesigner\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "override bool Csla\&.Web\&.Design\&.CslaDataSourceDesigner\&.AllowResize\fC [get]\fP"

.PP
Get a value indicating whether the control can be resized\&. 
.PP
Definition at line 151 of file CslaDataSourceDesigner\&.cs\&.
.SS "override bool Csla\&.Web\&.Design\&.CslaDataSourceDesigner\&.CanConfigure\fC [get]\fP"

.PP
Get a value indicating whether this control supports design time configuration\&. 
.PP
Definition at line 139 of file CslaDataSourceDesigner\&.cs\&.
.SS "override bool Csla\&.Web\&.Design\&.CslaDataSourceDesigner\&.CanRefreshSchema\fC [get]\fP"

.PP
Get a value indicating whether the control can refresh its schema\&. 
.PP
Definition at line 86 of file CslaDataSourceDesigner\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
