.TH "Csla.Testing.Business.EditableChildTests.MockEditableChild" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Testing.Business.EditableChildTests.MockEditableChild
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.BusinessBase< MockEditableChild >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override string \fBToString\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBMockEditableChild\fP \fBLoad\fP (Guid \fBId\fP, string name)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBDataPortalMethod\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "Guid \fBId\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBName\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBGrandChildList\fP \fBGrandChildren\fP\fC [get, set]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 17 of file MockEditableChild\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "static \fBMockEditableChild\fP Csla\&.Testing\&.Business\&.EditableChildTests\&.MockEditableChild\&.Load (Guid Id, string name)\fC [static]\fP"

.PP
Definition at line 16 of file MockEditableChild\&.partial\&.cs\&.
.SS "override string Csla\&.Testing\&.Business\&.EditableChildTests\&.MockEditableChild\&.ToString ()"

.PP
Definition at line 63 of file MockEditableChild\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "string Csla\&.Testing\&.Business\&.EditableChildTests\&.MockEditableChild\&.DataPortalMethod\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 37 of file MockEditableChild\&.cs\&.
.SS "\fBGrandChildList\fP Csla\&.Testing\&.Business\&.EditableChildTests\&.MockEditableChild\&.GrandChildren\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 55 of file MockEditableChild\&.cs\&.
.SS "Guid Csla\&.Testing\&.Business\&.EditableChildTests\&.MockEditableChild\&.Id\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 43 of file MockEditableChild\&.cs\&.
.SS "string Csla\&.Testing\&.Business\&.EditableChildTests\&.MockEditableChild\&.Name\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 49 of file MockEditableChild\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
