.TH "Csla.Server.Hosts.WcfChannel.WcfResponse" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Server.Hosts.WcfChannel.WcfResponse \- Response message for returning the results of a data portal call\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBWcfResponse\fP (object result)"
.br
.RI "Create new instance of object\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "object \fBResult\fP\fC [get, set]\fP"
.br
.RI "Busines object or exception return as result of service call\&. "
.in -1c
.SH "Detailed Description"
.PP 
Response message for returning the results of a data portal call\&. 


.PP
Definition at line 18 of file WcfChannel/WcfResponse\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Csla\&.Server\&.Hosts\&.WcfChannel\&.WcfResponse\&.WcfResponse (object result)"

.PP
Create new instance of object\&. 
.PP
\fBParameters\fP
.RS 4
\fIresult\fP Result object to be returned\&.
.RE
.PP

.PP
Definition at line 27 of file WcfChannel/WcfResponse\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "object Csla\&.Server\&.Hosts\&.WcfChannel\&.WcfResponse\&.Result\fC [get]\fP, \fC [set]\fP"

.PP
Busines object or exception return as result of service call\&. 
.PP
Definition at line 35 of file WcfChannel/WcfResponse\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
