.TH "Csla.Analyzers.DoesChildOperationHaveRunLocalAnalyzer" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Analyzers.DoesChildOperationHaveRunLocalAnalyzer
.SH SYNOPSIS
.br
.PP
.PP
Inherits DiagnosticAnalyzer\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBInitialize\fP (AnalysisContext context)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override ImmutableArray< DiagnosticDescriptor > \fBSupportedDiagnostics\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 12 of file DoesChildOperationHaveRunLocalAnalyzer\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override void Csla\&.Analyzers\&.DoesChildOperationHaveRunLocalAnalyzer\&.Initialize (AnalysisContext context)"

.PP
Definition at line 25 of file DoesChildOperationHaveRunLocalAnalyzer\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "override ImmutableArray<DiagnosticDescriptor> Csla\&.Analyzers\&.DoesChildOperationHaveRunLocalAnalyzer\&.SupportedDiagnostics\fC [get]\fP"

.PP
Definition at line 23 of file DoesChildOperationHaveRunLocalAnalyzer\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
