.TH "Csla.Core.TypeConverters.SmartDateConverter" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Core.TypeConverters.SmartDateConverter \- Converts values to and from a \fBSmartDate\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits TypeConverter\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override bool \fBCanConvertFrom\fP (System\&.ComponentModel\&.ITypeDescriptorContext context, System\&.Type sourceType)"
.br
.RI "Determines if a value can be converted to a \fBSmartDate\fP\&. "
.ti -1c
.RI "override object \fBConvertFrom\fP (System\&.ComponentModel\&.ITypeDescriptorContext context, System\&.Globalization\&.CultureInfo culture, object value)"
.br
.RI "Converts values to a \fBSmartDate\fP\&. "
.ti -1c
.RI "override bool \fBCanConvertTo\fP (System\&.ComponentModel\&.ITypeDescriptorContext context, System\&.Type destinationType)"
.br
.RI "Determines if a \fBSmartDate\fP can be convert to a value\&. "
.ti -1c
.RI "override object \fBConvertTo\fP (System\&.ComponentModel\&.ITypeDescriptorContext context, System\&.Globalization\&.CultureInfo culture, object value, System\&.Type destinationType)"
.br
.RI "Converts a \fBSmartDate\fP to a value\&. "
.in -1c
.SH "Detailed Description"
.PP 
Converts values to and from a \fBSmartDate\fP\&. 


.PP
Definition at line 17 of file SmartDateConverter\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override bool Csla\&.Core\&.TypeConverters\&.SmartDateConverter\&.CanConvertFrom (System\&.ComponentModel\&.ITypeDescriptorContext context, System\&.Type sourceType)"

.PP
Determines if a value can be converted to a \fBSmartDate\fP\&. 
.PP
\fBParameters\fP
.RS 4
\fIcontext\fP 
.br
\fIsourceType\fP 
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
Definition at line 27 of file SmartDateConverter\&.cs\&.
.SS "override bool Csla\&.Core\&.TypeConverters\&.SmartDateConverter\&.CanConvertTo (System\&.ComponentModel\&.ITypeDescriptorContext context, System\&.Type destinationType)"

.PP
Determines if a \fBSmartDate\fP can be convert to a value\&. 
.PP
\fBParameters\fP
.RS 4
\fIcontext\fP 
.br
\fIdestinationType\fP 
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
Definition at line 71 of file SmartDateConverter\&.cs\&.
.SS "override object Csla\&.Core\&.TypeConverters\&.SmartDateConverter\&.ConvertFrom (System\&.ComponentModel\&.ITypeDescriptorContext context, System\&.Globalization\&.CultureInfo culture, object value)"

.PP
Converts values to a \fBSmartDate\fP\&. 
.PP
\fBParameters\fP
.RS 4
\fIcontext\fP 
.br
\fIculture\fP 
.br
\fIvalue\fP 
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
Definition at line 48 of file SmartDateConverter\&.cs\&.
.SS "override object Csla\&.Core\&.TypeConverters\&.SmartDateConverter\&.ConvertTo (System\&.ComponentModel\&.ITypeDescriptorContext context, System\&.Globalization\&.CultureInfo culture, object value, System\&.Type destinationType)"

.PP
Converts a \fBSmartDate\fP to a value\&. 
.PP
\fBParameters\fP
.RS 4
\fIcontext\fP 
.br
\fIculture\fP 
.br
\fIvalue\fP 
.br
\fIdestinationType\fP 
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
Definition at line 93 of file SmartDateConverter\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
