.TH "Csla.Test.CslaDataProvider.ProviderChild" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.CslaDataProvider.ProviderChild
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.BusinessBase< ProviderChild >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBProviderChild\fP ()"
.br
.ti -1c
.RI "\fBProviderChild\fP (bool makeOld)"
.br
.ti -1c
.RI "void \fBMarkItOld\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBPropertyInfo\fP< int > \fBDataProperty\fP = RegisterProperty<int>(c => c\&.Data)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBData\fP\fC [get, set]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 48 of file ProviderList\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Csla\&.Test\&.CslaDataProvider\&.ProviderChild\&.ProviderChild ()"

.PP
Definition at line 57 of file ProviderList\&.cs\&.
.SS "Csla\&.Test\&.CslaDataProvider\&.ProviderChild\&.ProviderChild (bool makeOld)"

.PP
Definition at line 62 of file ProviderList\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Csla\&.Test\&.CslaDataProvider\&.ProviderChild\&.MarkItOld ()"

.PP
Definition at line 69 of file ProviderList\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBPropertyInfo\fP<int> Csla\&.Test\&.CslaDataProvider\&.ProviderChild\&.DataProperty = RegisterProperty<int>(c => c\&.Data)\fC [static]\fP"

.PP
Definition at line 50 of file ProviderList\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "int Csla\&.Test\&.CslaDataProvider\&.ProviderChild\&.Data\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 51 of file ProviderList\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
