.TH "Csla.Test.Basic.TestItem" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.Basic.TestItem
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.BusinessBase< TestItem >\fP, and \fBCsla\&.BusinessBase< TestItem >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBHasParent\fP ()"
.br
.ti -1c
.RI "\fBTestItem\fP ()"
.br
.ti -1c
.RI "bool \fBHasParent\fP ()"
.br
.ti -1c
.RI "\fBTestItem\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBChild_Create\fP ()"
.br
.ti -1c
.RI "override void \fBChild_Create\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBId\fP\fC [get, set]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 85 of file csla\&.netcore\&.test/Basic/CollectionTests\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Csla\&.Test\&.Basic\&.TestItem\&.TestItem ()"

.PP
Definition at line 99 of file csla\&.netcore\&.test/Basic/CollectionTests\&.cs\&.
.SS "Csla\&.Test\&.Basic\&.TestItem\&.TestItem ()"

.PP
Definition at line 98 of file Csla\&.test/Basic/CollectionTests\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override void Csla\&.Test\&.Basic\&.TestItem\&.Child_Create ()\fC [protected]\fP"

.PP
Definition at line 105 of file csla\&.netcore\&.test/Basic/CollectionTests\&.cs\&.
.SS "override void Csla\&.Test\&.Basic\&.TestItem\&.Child_Create ()\fC [protected]\fP"

.PP
Definition at line 103 of file Csla\&.test/Basic/CollectionTests\&.cs\&.
.SS "bool Csla\&.Test\&.Basic\&.TestItem\&.HasParent ()"

.PP
Definition at line 94 of file csla\&.netcore\&.test/Basic/CollectionTests\&.cs\&.
.SS "bool Csla\&.Test\&.Basic\&.TestItem\&.HasParent ()"

.PP
Definition at line 93 of file Csla\&.test/Basic/CollectionTests\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "int Csla\&.Test\&.Basic\&.TestItem\&.Id\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 88 of file csla\&.netcore\&.test/Basic/CollectionTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
