.TH "Csla.Blazor.Test.Fakes.FakePerson" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Blazor.Test.Fakes.FakePerson
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.BusinessBase< FakePerson >\fP\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBFakePerson\fP \fBNewFakePerson\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBCsla\&.PropertyInfo\fP< string > \fBFirstNameProperty\fP = RegisterProperty<string>(nameof(\fBFirstName\fP))"
.br
.ti -1c
.RI "static \fBCsla\&.PropertyInfo\fP< string > \fBLastNameProperty\fP = RegisterProperty<string>(nameof(\fBLastName\fP))"
.br
.ti -1c
.RI "static \fBCsla\&.PropertyInfo\fP< string > \fBHomeTelephoneProperty\fP = RegisterProperty<string>(nameof(\fBHomeTelephone\fP))"
.br
.ti -1c
.RI "static \fBCsla\&.PropertyInfo\fP< string > \fBMobileTelephoneProperty\fP = RegisterProperty<string>(nameof(\fBMobileTelephone\fP))"
.br
.ti -1c
.RI "static \fBCsla\&.PropertyInfo\fP< \fBFakePersonEmailAddresses\fP > \fBEmailAddressesProperty\fP = RegisterProperty<\fBFakePersonEmailAddresses\fP>(nameof(\fBEmailAddresses\fP))"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBAddBusinessRules\fP ()"
.br
.ti -1c
.RI "override void \fBOnChildChanged\fP (\fBCsla\&.Core\&.ChildChangedEventArgs\fP e)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBFirstName\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBLastName\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBHomeTelephone\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBMobileTelephone\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBFakePersonEmailAddresses\fP \fBEmailAddresses\fP\fC [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 10 of file FakePerson\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override void Csla\&.Blazor\&.Test\&.Fakes\&.FakePerson\&.AddBusinessRules ()\fC [protected]\fP"

.PP
Definition at line 65 of file FakePerson\&.cs\&.
.SS "static \fBFakePerson\fP Csla\&.Blazor\&.Test\&.Fakes\&.FakePerson\&.NewFakePerson ()\fC [static]\fP"

.PP
Definition at line 56 of file FakePerson\&.cs\&.
.SS "override void Csla\&.Blazor\&.Test\&.Fakes\&.FakePerson\&.OnChildChanged (\fBCsla\&.Core\&.ChildChangedEventArgs\fP e)\fC [protected]\fP"

.PP
Definition at line 82 of file FakePerson\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBCsla\&.PropertyInfo\fP<\fBFakePersonEmailAddresses\fP> Csla\&.Blazor\&.Test\&.Fakes\&.FakePerson\&.EmailAddressesProperty = RegisterProperty<\fBFakePersonEmailAddresses\fP>(nameof(\fBEmailAddresses\fP))\fC [static]\fP"

.PP
Definition at line 16 of file FakePerson\&.cs\&.
.SS "\fBCsla\&.PropertyInfo\fP<string> Csla\&.Blazor\&.Test\&.Fakes\&.FakePerson\&.FirstNameProperty = RegisterProperty<string>(nameof(\fBFirstName\fP))\fC [static]\fP"

.PP
Definition at line 12 of file FakePerson\&.cs\&.
.SS "\fBCsla\&.PropertyInfo\fP<string> Csla\&.Blazor\&.Test\&.Fakes\&.FakePerson\&.HomeTelephoneProperty = RegisterProperty<string>(nameof(\fBHomeTelephone\fP))\fC [static]\fP"

.PP
Definition at line 14 of file FakePerson\&.cs\&.
.SS "\fBCsla\&.PropertyInfo\fP<string> Csla\&.Blazor\&.Test\&.Fakes\&.FakePerson\&.LastNameProperty = RegisterProperty<string>(nameof(\fBLastName\fP))\fC [static]\fP"

.PP
Definition at line 13 of file FakePerson\&.cs\&.
.SS "\fBCsla\&.PropertyInfo\fP<string> Csla\&.Blazor\&.Test\&.Fakes\&.FakePerson\&.MobileTelephoneProperty = RegisterProperty<string>(nameof(\fBMobileTelephone\fP))\fC [static]\fP"

.PP
Definition at line 15 of file FakePerson\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "\fBFakePersonEmailAddresses\fP Csla\&.Blazor\&.Test\&.Fakes\&.FakePerson\&.EmailAddresses\fC [get]\fP"

.PP
Definition at line 47 of file FakePerson\&.cs\&.
.SS "string Csla\&.Blazor\&.Test\&.Fakes\&.FakePerson\&.FirstName\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 21 of file FakePerson\&.cs\&.
.SS "string Csla\&.Blazor\&.Test\&.Fakes\&.FakePerson\&.HomeTelephone\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 35 of file FakePerson\&.cs\&.
.SS "string Csla\&.Blazor\&.Test\&.Fakes\&.FakePerson\&.LastName\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 29 of file FakePerson\&.cs\&.
.SS "string Csla\&.Blazor\&.Test\&.Fakes\&.FakePerson\&.MobileTelephone\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 41 of file FakePerson\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
