.TH "Csla.Test.PropertyGetSet.EditableGetSetTopNFIBase< T >" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.PropertyGetSet.EditableGetSetTopNFIBase< T >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.BusinessBase< T >\fP\&.
.PP
Inherited by \fBCsla\&.Test\&.PropertyGetSet\&.EditableGetSetNFIBase< T >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEditableGetSetTopNFIBase\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBPropertyInfo\fP< string > \fBTopBaseProperty\fP = RegisterProperty<string>(new \fBPropertyInfo\fP<string>('TopBase', '\fBTopBase\fP'))"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBTopBase\fP\fC [get, set]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
\fBType Constraints\fP
.TP
\fIT\fP : \fI\fBEditableGetSetTopNFIBase\fP<T>\fP
.PP
Definition at line 37 of file EditableGetSetTopBase\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBCsla\&.Test\&.PropertyGetSet\&.EditableGetSetTopNFIBase\fP< T >\&.\fBEditableGetSetTopNFIBase\fP ()"

.PP
Definition at line 40 of file EditableGetSetTopBase\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBPropertyInfo\fP<string> \fBCsla\&.Test\&.PropertyGetSet\&.EditableGetSetTopNFIBase\fP< T >\&.TopBaseProperty = RegisterProperty<string>(new \fBPropertyInfo\fP<string>('TopBase', '\fBTopBase\fP'))\fC [static]\fP"

.PP
Definition at line 44 of file EditableGetSetTopBase\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "string \fBCsla\&.Test\&.PropertyGetSet\&.EditableGetSetTopNFIBase\fP< T >\&.TopBase\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 45 of file EditableGetSetTopBase\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
