.TH "Csla.Blazor.Client.Authentication.CslaUserService.CurrentUserChangedEventArgs" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Blazor.Client.Authentication.CslaUserService.CurrentUserChangedEventArgs \- Event args for CurrentUserChanged event\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits EventArgs\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "ClaimsPrincipal \fBNewUser\fP\fC [get, set]\fP"
.br
.RI "Gets the new user value\&. "
.in -1c
.SH "Detailed Description"
.PP 
Event args for CurrentUserChanged event\&. 


.PP
Definition at line 46 of file CslaUserService\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "ClaimsPrincipal Csla\&.Blazor\&.Client\&.Authentication\&.CslaUserService\&.CurrentUserChangedEventArgs\&.NewUser\fC [get]\fP, \fC [set]\fP"

.PP
Gets the new user value\&. 
.PP
Definition at line 51 of file CslaUserService\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
