.TH "Csla.DataPortalClient.IDataPortalProxy" 3 "Thu Jul 22 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.DataPortalClient.IDataPortalProxy \- Interface implemented by client-side data portal proxy objects\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.Server\&.IDataPortalServer\fP\&.
.PP
Inherited by \fBCsla\&.DataPortalClient\&.BrokeredProxy\fP, \fBCsla\&.DataPortalClient\&.DataPortalProxy\fP, \fBCsla\&.DataPortalClient\&.LocalProxy\fP, and \fBCsla\&.DataPortalClient\&.WcfProxy\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "bool \fBIsServerRemote\fP\fC [get]\fP"
.br
.RI "Get a value indicating whether this proxy will invoke a remote data portal server, or run the 'server-side' data portal in the caller's process and AppDomain\&. "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Interface implemented by client-side data portal proxy objects\&. 


.PP
Definition at line 16 of file IDataPortalProxy\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "bool Csla\&.DataPortalClient\&.IDataPortalProxy\&.IsServerRemote\fC [get]\fP"

.PP
Get a value indicating whether this proxy will invoke a remote data portal server, or run the 'server-side' data portal in the caller's process and AppDomain\&. 
.PP
Definition at line 23 of file IDataPortalProxy\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
