.TH "Csla.Server.InterceptArgs" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Server.InterceptArgs \- Arguments parameter passed to the interceptor methods\&.  

.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "Type \fBObjectType\fP\fC [get, set]\fP"
.br
.RI "Gets or sets the business object type\&. "
.ti -1c
.RI "object \fBParameter\fP\fC [get, set]\fP"
.br
.RI "Gets or sets the criteria or business object paramter provided to the data portal from the client\&. "
.ti -1c
.RI "\fBDataPortalResult\fP \fBResult\fP\fC [get, set]\fP"
.br
.RI "Gets or sets the business object resulting from the data portal operation\&. "
.ti -1c
.RI "Exception \fBException\fP\fC [get, set]\fP"
.br
.RI "Gets or sets the exception that occurred during data portal processing\&. "
.ti -1c
.RI "\fBDataPortalOperations\fP \fBOperation\fP\fC [get, set]\fP"
.br
.RI "Gets or sets the data portal operation being performed\&. "
.ti -1c
.RI "bool \fBIsSync\fP\fC [get, set]\fP"
.br
.RI "Gets or sets a value indicating whether the data portal was invoked synchronously\&. "
.ti -1c
.RI "TimeSpan \fBRuntime\fP\fC [get, set]\fP"
.br
.RI "Gets or sets a value containing the elapsed runtime for this operation (only valid at end of operation)\&. "
.in -1c
.SH "Detailed Description"
.PP 
Arguments parameter passed to the interceptor methods\&. 


.PP
Definition at line 38 of file IInterceptDataPortal\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "Exception Csla\&.Server\&.InterceptArgs\&.Exception\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the exception that occurred during data portal processing\&. 
.PP
Definition at line 60 of file IInterceptDataPortal\&.cs\&.
.SS "bool Csla\&.Server\&.InterceptArgs\&.IsSync\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets a value indicating whether the data portal was invoked synchronously\&. 
.PP
Definition at line 70 of file IInterceptDataPortal\&.cs\&.
.SS "Type Csla\&.Server\&.InterceptArgs\&.ObjectType\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the business object type\&. 
.PP
Definition at line 43 of file IInterceptDataPortal\&.cs\&.
.SS "\fBDataPortalOperations\fP Csla\&.Server\&.InterceptArgs\&.Operation\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the data portal operation being performed\&. 
.PP
Definition at line 65 of file IInterceptDataPortal\&.cs\&.
.SS "object Csla\&.Server\&.InterceptArgs\&.Parameter\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the criteria or business object paramter provided to the data portal from the client\&. 
.PP
Definition at line 49 of file IInterceptDataPortal\&.cs\&.
.SS "\fBDataPortalResult\fP Csla\&.Server\&.InterceptArgs\&.Result\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the business object resulting from the data portal operation\&. 
.PP
Definition at line 55 of file IInterceptDataPortal\&.cs\&.
.SS "TimeSpan Csla\&.Server\&.InterceptArgs\&.Runtime\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets a value containing the elapsed runtime for this operation (only valid at end of operation)\&. 
.PP
Definition at line 77 of file IInterceptDataPortal\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
