.TH "Csla.Blazor.HasPermissionAttribute" 3 "Thu Jul 22 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Blazor.HasPermissionAttribute \- Authorizes user if they have permission\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits AuthorizeAttribute\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHasPermissionAttribute\fP (\fBRules\&.AuthorizationActions\fP action, Type objectType)"
.br
.RI "Creates instance of type "
.in -1c
.SH "Detailed Description"
.PP 
Authorizes user if they have permission\&. 


.PP
Definition at line 16 of file Csla\&.Blazor/HasPermissionAttribute\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Csla\&.Blazor\&.HasPermissionAttribute\&.HasPermissionAttribute (\fBRules\&.AuthorizationActions\fP action, Type objectType)"

.PP
Creates instance of type 
.PP
\fBParameters\fP
.RS 4
\fIaction\fP Authorization action
.br
\fIobjectType\fP Business domain type
.RE
.PP

.PP
Definition at line 23 of file Csla\&.Blazor/HasPermissionAttribute\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
