.TH "Csla.Validation.CommonRules.MaxValueRuleArgs< T >" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Validation.CommonRules.MaxValueRuleArgs< T > \- Custom \fBRuleArgs\fP object required by the \fBMaxValue\fP rule method\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.Validation\&.DecoratedRuleArgs\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMaxValueRuleArgs\fP (string propertyName, T maxValue)"
.br
.RI "Create a new object\&. "
.ti -1c
.RI "\fBMaxValueRuleArgs\fP (\fBCore\&.IPropertyInfo\fP propertyInfo, T maxValue)"
.br
.RI "Create a new object\&. "
.ti -1c
.RI "\fBMaxValueRuleArgs\fP (string propertyName, string friendlyName, T maxValue)"
.br
.RI "Create a new object\&. "
.ti -1c
.RI "\fBMaxValueRuleArgs\fP (string propertyName, T maxValue, string format)"
.br
.RI "Create a new object\&. "
.ti -1c
.RI "\fBMaxValueRuleArgs\fP (\fBCore\&.IPropertyInfo\fP propertyInfo, T maxValue, string format)"
.br
.RI "Create a new object\&. "
.ti -1c
.RI "\fBMaxValueRuleArgs\fP (string propertyName, string friendlyName, T maxValue, string format)"
.br
.RI "Create a new object\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "T \fBMaxValue\fP\fC [get]\fP"
.br
.RI "Get the max value for the property\&. "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Custom \fBRuleArgs\fP object required by the \fBMaxValue\fP rule method\&. 


.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP Type of the property to validate\&.
.RE
.PP

.PP
Definition at line 649 of file Csla\&.Validation\&.Shared/CommonRules\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBCsla\&.Validation\&.CommonRules\&.MaxValueRuleArgs\fP< T >\&.\fBMaxValueRuleArgs\fP (string propertyName, T maxValue)"

.PP
Create a new object\&. 
.PP
\fBParameters\fP
.RS 4
\fIpropertyName\fP Name of the property\&.
.br
\fImaxValue\fP Maximum allowed value for the property\&.
.RE
.PP

.PP
Definition at line 664 of file Csla\&.Validation\&.Shared/CommonRules\&.cs\&.
.SS "\fBCsla\&.Validation\&.CommonRules\&.MaxValueRuleArgs\fP< T >\&.\fBMaxValueRuleArgs\fP (\fBCore\&.IPropertyInfo\fP propertyInfo, T maxValue)"

.PP
Create a new object\&. 
.PP
\fBParameters\fP
.RS 4
\fIpropertyInfo\fP Property to validate\&.
.br
\fImaxValue\fP Maximum allowed value for the property\&.
.RE
.PP

.PP
Definition at line 677 of file Csla\&.Validation\&.Shared/CommonRules\&.cs\&.
.SS "\fBCsla\&.Validation\&.CommonRules\&.MaxValueRuleArgs\fP< T >\&.\fBMaxValueRuleArgs\fP (string propertyName, string friendlyName, T maxValue)"

.PP
Create a new object\&. 
.PP
\fBParameters\fP
.RS 4
\fIpropertyName\fP Name of the property\&.
.br
\fIfriendlyName\fP A friendly name for the property, which will be used in place of the property name when creating the broken rule description string\&.
.br
\fImaxValue\fP Maximum allowed value for the property\&.
.RE
.PP

.PP
Definition at line 693 of file Csla\&.Validation\&.Shared/CommonRules\&.cs\&.
.SS "\fBCsla\&.Validation\&.CommonRules\&.MaxValueRuleArgs\fP< T >\&.\fBMaxValueRuleArgs\fP (string propertyName, T maxValue, string format)"

.PP
Create a new object\&. 
.PP
\fBParameters\fP
.RS 4
\fIpropertyName\fP Name of the property\&.
.br
\fImaxValue\fP Maximum allowed value for the property\&.
.br
\fIformat\fP Format string for the max value value in the broken rule string\&.
.RE
.PP

.PP
Definition at line 709 of file Csla\&.Validation\&.Shared/CommonRules\&.cs\&.
.SS "\fBCsla\&.Validation\&.CommonRules\&.MaxValueRuleArgs\fP< T >\&.\fBMaxValueRuleArgs\fP (\fBCore\&.IPropertyInfo\fP propertyInfo, T maxValue, string format)"

.PP
Create a new object\&. 
.PP
\fBParameters\fP
.RS 4
\fIpropertyInfo\fP Property to validate\&.
.br
\fImaxValue\fP Maximum allowed value for the property\&.
.br
\fIformat\fP Format string for the max value value in the broken rule string\&.
.RE
.PP

.PP
Definition at line 724 of file Csla\&.Validation\&.Shared/CommonRules\&.cs\&.
.SS "\fBCsla\&.Validation\&.CommonRules\&.MaxValueRuleArgs\fP< T >\&.\fBMaxValueRuleArgs\fP (string propertyName, string friendlyName, T maxValue, string format)"

.PP
Create a new object\&. 
.PP
\fBParameters\fP
.RS 4
\fIpropertyName\fP Name of the property\&.
.br
\fIfriendlyName\fP A friendly name for the property, which will be used in place of the property name when creating the broken rule description string\&.
.br
\fImaxValue\fP Maximum allowed value for the property\&.
.br
\fIformat\fP Format string for the max value value in the broken rule string\&.
.RE
.PP

.PP
Definition at line 742 of file Csla\&.Validation\&.Shared/CommonRules\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "T \fBCsla\&.Validation\&.CommonRules\&.MaxValueRuleArgs\fP< T >\&.MaxValue\fC [get]\fP"

.PP
Get the max value for the property\&. 
.PP
Definition at line 654 of file Csla\&.Validation\&.Shared/CommonRules\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
