.TH "Csla.Test.DataPortalChild.Child" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.DataPortalChild.Child
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.BusinessBase< Child >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBChild\fP ()"
.br
.ti -1c
.RI "void \fBDeleteChild\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBChild\fP \fBNewChild\fP ()"
.br
.ti -1c
.RI "static \fBChild\fP \fBGetChild\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBChild_Create\fP ()"
.br
.ti -1c
.RI "void \fBChild_Fetch\fP ()"
.br
.ti -1c
.RI "void \fBChild_Insert\fP (\fBRoot\fP parent)"
.br
.ti -1c
.RI "void \fBChild_Update\fP (\fBRoot\fP parent)"
.br
.ti -1c
.RI "void \fBChild_DeleteSelf\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBData\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBRootData\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBStatus\fP\fC [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 16 of file Child\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Csla\&.Test\&.DataPortalChild\&.Child\&.Child ()"

.PP
Definition at line 28 of file Child\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override void Csla\&.Test\&.DataPortalChild\&.Child\&.Child_Create ()\fC [protected]\fP"

.PP
Definition at line 58 of file Child\&.cs\&.
.SS "void Csla\&.Test\&.DataPortalChild\&.Child\&.Child_DeleteSelf ()\fC [protected]\fP"

.PP
Definition at line 94 of file Child\&.cs\&.
.SS "void Csla\&.Test\&.DataPortalChild\&.Child\&.Child_Fetch ()\fC [protected]\fP"

.PP
Definition at line 63 of file Child\&.cs\&.
.SS "void Csla\&.Test\&.DataPortalChild\&.Child\&.Child_Insert (\fBRoot\fP parent)\fC [protected]\fP"

.PP
Definition at line 68 of file Child\&.cs\&.
.SS "void Csla\&.Test\&.DataPortalChild\&.Child\&.Child_Update (\fBRoot\fP parent)\fC [protected]\fP"

.PP
Definition at line 81 of file Child\&.cs\&.
.SS "void Csla\&.Test\&.DataPortalChild\&.Child\&.DeleteChild ()"

.PP
Definition at line 53 of file Child\&.cs\&.
.SS "static \fBChild\fP Csla\&.Test\&.DataPortalChild\&.Child\&.GetChild ()\fC [static]\fP"

.PP
Definition at line 23 of file Child\&.cs\&.
.SS "static \fBChild\fP Csla\&.Test\&.DataPortalChild\&.Child\&.NewChild ()\fC [static]\fP"

.PP
Definition at line 18 of file Child\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "string Csla\&.Test\&.DataPortalChild\&.Child\&.Data\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 34 of file Child\&.cs\&.
.SS "string Csla\&.Test\&.DataPortalChild\&.Child\&.RootData\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 41 of file Child\&.cs\&.
.SS "string Csla\&.Test\&.DataPortalChild\&.Child\&.Status\fC [get]\fP"

.PP
Definition at line 48 of file Child\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
