.TH "Csla.WcfPortal.WcfPortalClient" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.WcfPortal.WcfPortalClient
.SH SYNOPSIS
.br
.PP
.PP
Inherits System\&.ServiceModel\&.ClientBase< Csla\&.WcfPortal\&.IWcfPortal >, and \fBCsla\&.WcfPortal\&.IWcfPortal\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBWcfPortalClient\fP ()"
.br
.ti -1c
.RI "\fBWcfPortalClient\fP (string endpointConfigurationName)"
.br
.ti -1c
.RI "\fBWcfPortalClient\fP (string endpointConfigurationName, string remoteAddress)"
.br
.ti -1c
.RI "\fBWcfPortalClient\fP (string endpointConfigurationName, System\&.ServiceModel\&.EndpointAddress remoteAddress)"
.br
.ti -1c
.RI "\fBWcfPortalClient\fP (System\&.ServiceModel\&.Channels\&.Binding binding, System\&.ServiceModel\&.EndpointAddress remoteAddress)"
.br
.ti -1c
.RI "\fBCsla\&.WcfPortal\&.WcfResponse\fP \fBCreate\fP (\fBCsla\&.WcfPortal\&.CriteriaRequest\fP request)"
.br
.ti -1c
.RI "System\&.Threading\&.Tasks\&.Task< \fBCsla\&.WcfPortal\&.WcfResponse\fP > \fBCreateAsync\fP (\fBCsla\&.WcfPortal\&.CriteriaRequest\fP request)"
.br
.ti -1c
.RI "\fBCsla\&.WcfPortal\&.WcfResponse\fP \fBFetch\fP (\fBCsla\&.WcfPortal\&.CriteriaRequest\fP request)"
.br
.ti -1c
.RI "System\&.Threading\&.Tasks\&.Task< \fBCsla\&.WcfPortal\&.WcfResponse\fP > \fBFetchAsync\fP (\fBCsla\&.WcfPortal\&.CriteriaRequest\fP request)"
.br
.ti -1c
.RI "\fBCsla\&.WcfPortal\&.WcfResponse\fP \fBUpdate\fP (\fBCsla\&.WcfPortal\&.UpdateRequest\fP request)"
.br
.ti -1c
.RI "System\&.Threading\&.Tasks\&.Task< \fBCsla\&.WcfPortal\&.WcfResponse\fP > \fBUpdateAsync\fP (\fBCsla\&.WcfPortal\&.UpdateRequest\fP request)"
.br
.ti -1c
.RI "\fBCsla\&.WcfPortal\&.WcfResponse\fP \fBDelete\fP (\fBCsla\&.WcfPortal\&.CriteriaRequest\fP request)"
.br
.ti -1c
.RI "System\&.Threading\&.Tasks\&.Task< \fBCsla\&.WcfPortal\&.WcfResponse\fP > \fBDeleteAsync\fP (\fBCsla\&.WcfPortal\&.CriteriaRequest\fP request)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 520 of file Reference\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Csla\&.WcfPortal\&.WcfPortalClient\&.WcfPortalClient ()"

.PP
Definition at line 522 of file Reference\&.cs\&.
.SS "Csla\&.WcfPortal\&.WcfPortalClient\&.WcfPortalClient (string endpointConfigurationName)"

.PP
Definition at line 525 of file Reference\&.cs\&.
.SS "Csla\&.WcfPortal\&.WcfPortalClient\&.WcfPortalClient (string endpointConfigurationName, string remoteAddress)"

.PP
Definition at line 529 of file Reference\&.cs\&.
.SS "Csla\&.WcfPortal\&.WcfPortalClient\&.WcfPortalClient (string endpointConfigurationName, System\&.ServiceModel\&.EndpointAddress remoteAddress)"

.PP
Definition at line 533 of file Reference\&.cs\&.
.SS "Csla\&.WcfPortal\&.WcfPortalClient\&.WcfPortalClient (System\&.ServiceModel\&.Channels\&.Binding binding, System\&.ServiceModel\&.EndpointAddress remoteAddress)"

.PP
Definition at line 537 of file Reference\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBCsla\&.WcfPortal\&.WcfResponse\fP Csla\&.WcfPortal\&.WcfPortalClient\&.Create (\fBCsla\&.WcfPortal\&.CriteriaRequest\fP request)"

.PP
Implements \fBCsla\&.WcfPortal\&.IWcfPortal\fP\&.
.PP
Definition at line 541 of file Reference\&.cs\&.
.SS "System\&.Threading\&.Tasks\&.Task<\fBCsla\&.WcfPortal\&.WcfResponse\fP> Csla\&.WcfPortal\&.WcfPortalClient\&.CreateAsync (\fBCsla\&.WcfPortal\&.CriteriaRequest\fP request)"

.PP
Implements \fBCsla\&.WcfPortal\&.IWcfPortal\fP\&.
.PP
Definition at line 545 of file Reference\&.cs\&.
.SS "\fBCsla\&.WcfPortal\&.WcfResponse\fP Csla\&.WcfPortal\&.WcfPortalClient\&.Delete (\fBCsla\&.WcfPortal\&.CriteriaRequest\fP request)"

.PP
Implements \fBCsla\&.WcfPortal\&.IWcfPortal\fP\&.
.PP
Definition at line 565 of file Reference\&.cs\&.
.SS "System\&.Threading\&.Tasks\&.Task<\fBCsla\&.WcfPortal\&.WcfResponse\fP> Csla\&.WcfPortal\&.WcfPortalClient\&.DeleteAsync (\fBCsla\&.WcfPortal\&.CriteriaRequest\fP request)"

.PP
Implements \fBCsla\&.WcfPortal\&.IWcfPortal\fP\&.
.PP
Definition at line 569 of file Reference\&.cs\&.
.SS "\fBCsla\&.WcfPortal\&.WcfResponse\fP Csla\&.WcfPortal\&.WcfPortalClient\&.Fetch (\fBCsla\&.WcfPortal\&.CriteriaRequest\fP request)"

.PP
Implements \fBCsla\&.WcfPortal\&.IWcfPortal\fP\&.
.PP
Definition at line 549 of file Reference\&.cs\&.
.SS "System\&.Threading\&.Tasks\&.Task<\fBCsla\&.WcfPortal\&.WcfResponse\fP> Csla\&.WcfPortal\&.WcfPortalClient\&.FetchAsync (\fBCsla\&.WcfPortal\&.CriteriaRequest\fP request)"

.PP
Implements \fBCsla\&.WcfPortal\&.IWcfPortal\fP\&.
.PP
Definition at line 553 of file Reference\&.cs\&.
.SS "\fBCsla\&.WcfPortal\&.WcfResponse\fP Csla\&.WcfPortal\&.WcfPortalClient\&.Update (\fBCsla\&.WcfPortal\&.UpdateRequest\fP request)"

.PP
Implements \fBCsla\&.WcfPortal\&.IWcfPortal\fP\&.
.PP
Definition at line 557 of file Reference\&.cs\&.
.SS "System\&.Threading\&.Tasks\&.Task<\fBCsla\&.WcfPortal\&.WcfResponse\fP> Csla\&.WcfPortal\&.WcfPortalClient\&.UpdateAsync (\fBCsla\&.WcfPortal\&.UpdateRequest\fP request)"

.PP
Implements \fBCsla\&.WcfPortal\&.IWcfPortal\fP\&.
.PP
Definition at line 561 of file Reference\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
