.TH "Csla.Test.Linq.LinqObservableCollectionTest" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.Linq.LinqObservableCollectionTest \- This is a test class for \fBLinqObservableCollectionTest\fP and is intended to contain all \fBLinqObservableCollectionTest\fP Unit Tests /summary>  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBBlb2Loc_WhereOnly\fP ()"
.br
.ti -1c
.RI "void \fBBlb2Loc\fP ()"
.br
.ti -1c
.RI "void \fBBlb2Loc_Ordered\fP ()"
.br
.ti -1c
.RI "void \fBBlb2Loc_ResultToSync\fP ()"
.br
.ti -1c
.RI "void \fBBlb2Loc_Add\fP ()"
.br
.ti -1c
.RI "void \fBBlb2Loc_Remove\fP ()"
.br
.ti -1c
.RI "void \fBBlb2Loc_RemoveOriginal\fP ()"
.br
.ti -1c
.RI "void \fBCreate\fP ()"
.br
.ti -1c
.RI "void \fBAddItem\fP ()"
.br
.ti -1c
.RI "void \fBInsertItem\fP ()"
.br
.ti -1c
.RI "void \fBRemoveAt\fP ()"
.br
.ti -1c
.RI "void \fBRemoveItem\fP ()"
.br
.ti -1c
.RI "void \fBReplaceItem\fP ()"
.br
.ti -1c
.RI "void \fBMoveItem\fP ()"
.br
.ti -1c
.RI "void \fBClearSource\fP ()"
.br
.ti -1c
.RI "void \fBClearView\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
This is a test class for \fBLinqObservableCollectionTest\fP and is intended to contain all \fBLinqObservableCollectionTest\fP Unit Tests /summary> 
.PP
Definition at line 35 of file LinqObservableCollectionTest\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Csla\&.Test\&.Linq\&.LinqObservableCollectionTest\&.AddItem ()"

.PP
Definition at line 156 of file LinqObservableCollectionTest\&.cs\&.
.SS "void Csla\&.Test\&.Linq\&.LinqObservableCollectionTest\&.Blb2Loc ()"

.PP
Definition at line 48 of file LinqObservableCollectionTest\&.cs\&.
.SS "void Csla\&.Test\&.Linq\&.LinqObservableCollectionTest\&.Blb2Loc_Add ()"

.PP
Definition at line 79 of file LinqObservableCollectionTest\&.cs\&.
.SS "void Csla\&.Test\&.Linq\&.LinqObservableCollectionTest\&.Blb2Loc_Ordered ()"

.PP
Definition at line 58 of file LinqObservableCollectionTest\&.cs\&.
.SS "void Csla\&.Test\&.Linq\&.LinqObservableCollectionTest\&.Blb2Loc_Remove ()"

.PP
Definition at line 97 of file LinqObservableCollectionTest\&.cs\&.
.SS "void Csla\&.Test\&.Linq\&.LinqObservableCollectionTest\&.Blb2Loc_RemoveOriginal ()"

.PP
Definition at line 115 of file LinqObservableCollectionTest\&.cs\&.
.SS "void Csla\&.Test\&.Linq\&.LinqObservableCollectionTest\&.Blb2Loc_ResultToSync ()"

.PP
Definition at line 69 of file LinqObservableCollectionTest\&.cs\&.
.SS "void Csla\&.Test\&.Linq\&.LinqObservableCollectionTest\&.Blb2Loc_WhereOnly ()"

.PP
Definition at line 39 of file LinqObservableCollectionTest\&.cs\&.
.SS "void Csla\&.Test\&.Linq\&.LinqObservableCollectionTest\&.ClearSource ()"

.PP
Definition at line 380 of file LinqObservableCollectionTest\&.cs\&.
.SS "void Csla\&.Test\&.Linq\&.LinqObservableCollectionTest\&.ClearView ()"

.PP
Definition at line 406 of file LinqObservableCollectionTest\&.cs\&.
.SS "void Csla\&.Test\&.Linq\&.LinqObservableCollectionTest\&.Create ()"

.PP
Definition at line 143 of file LinqObservableCollectionTest\&.cs\&.
.SS "void Csla\&.Test\&.Linq\&.LinqObservableCollectionTest\&.InsertItem ()"

.PP
Definition at line 194 of file LinqObservableCollectionTest\&.cs\&.
.SS "void Csla\&.Test\&.Linq\&.LinqObservableCollectionTest\&.MoveItem ()"

.PP
Definition at line 351 of file LinqObservableCollectionTest\&.cs\&.
.SS "void Csla\&.Test\&.Linq\&.LinqObservableCollectionTest\&.RemoveAt ()"

.PP
Definition at line 232 of file LinqObservableCollectionTest\&.cs\&.
.SS "void Csla\&.Test\&.Linq\&.LinqObservableCollectionTest\&.RemoveItem ()"

.PP
Definition at line 270 of file LinqObservableCollectionTest\&.cs\&.
.SS "void Csla\&.Test\&.Linq\&.LinqObservableCollectionTest\&.ReplaceItem ()"

.PP
Definition at line 308 of file LinqObservableCollectionTest\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
