.TH "CommonRules.cs" 3 "Thu Jul 22 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CommonRules.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCsla\&.Rules\&.CommonRules\&.CommonBusinessRule\fP"
.br
.RI "Base class used to create common rules\&. "
.ti -1c
.RI "class \fBCsla\&.Rules\&.CommonRules\&.DataAnnotation\fP"
.br
.RI "Business rule that encapsulates a DataAnnotations ValidationAttribute rule\&. "
.ti -1c
.RI "class \fBCsla\&.Rules\&.CommonRules\&.Required\fP"
.br
.RI "Business rule for a required string\&. "
.ti -1c
.RI "class \fBCsla\&.Rules\&.CommonRules\&.MaxLength\fP"
.br
.RI "Business rule for a maximum length string\&. "
.ti -1c
.RI "class \fBCsla\&.Rules\&.CommonRules\&.MinLength\fP"
.br
.RI "Business rule for a minimum length string\&. "
.ti -1c
.RI "class \fBCsla\&.Rules\&.CommonRules\&.MinValue< T >\fP"
.br
.RI "Business rule for a minimum value\&. "
.ti -1c
.RI "class \fBCsla\&.Rules\&.CommonRules\&.MaxValue< T >\fP"
.br
.RI "Business rule for a maximum value\&. "
.ti -1c
.RI "class \fBCsla\&.Rules\&.CommonRules\&.RegExMatch\fP"
.br
.RI "Business rule that evaluates a regular expression\&. "
.ti -1c
.RI "class \fBCsla\&.Rules\&.CommonRules\&.InfoMessage\fP"
.br
.RI "Adds an information message to a property\&. "
.ti -1c
.RI "class \fBCsla\&.Rules\&.CommonRules\&.Lambda\fP"
.br
.RI "A business rule defined by a lambda expression\&. "
.ti -1c
.RI "class \fBCsla\&.Rules\&.CommonRules\&.Dependency\fP"
.br
.RI "A rule that establishes a dependency between two properties\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBCsla\fP"
.br
.ti -1c
.RI "namespace \fBCsla\&.Rules\fP"
.br
.ti -1c
.RI "namespace \fBCsla\&.Rules\&.CommonRules\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
