.TH "cslalighttest.Serialization.Person" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cslalighttest.Serialization.Person
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.BusinessBase< Person >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "DateTime \fBGetBDate\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static readonly \fBPropertyInfo\fP< string > \fBNameProperty\fP"
.br
.ti -1c
.RI "static readonly \fBPropertyInfo\fP< DateTime > \fBBirthdateProperty\fP"
.br
.ti -1c
.RI "static readonly \fBPropertyInfo\fP< \fBAddressList\fP > \fBAddressesProperty\fP"
.br
.ti -1c
.RI "static readonly \fBPropertyInfo\fP< \fBAddress\fP > \fBPrimaryAddressProperty\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBName\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "DateTime \fBBirthdate\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBAge\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBUnserialized\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBAddressList\fP \fBAddresses\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "DateTimeOffset \fBDtoDate\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBAddress\fP \fBPrimaryAddress\fP\fC [get, set]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 17 of file Person\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "DateTime cslalighttest\&.Serialization\&.Person\&.GetBDate ()"

.PP
Definition at line 69 of file Person\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "readonly \fBPropertyInfo\fP<\fBAddressList\fP> cslalighttest\&.Serialization\&.Person\&.AddressesProperty\fC [static]\fP"
\fBInitial value:\fP
.PP
.nf
= RegisterProperty<AddressList>(
      typeof(Person),
      new PropertyInfo<AddressList>("Addresses"))
.fi
.PP
Definition at line 29 of file Person\&.cs\&.
.SS "readonly \fBPropertyInfo\fP<DateTime> cslalighttest\&.Serialization\&.Person\&.BirthdateProperty\fC [static]\fP"
\fBInitial value:\fP
.PP
.nf
= RegisterProperty<DateTime>(
      typeof(Person),
      new PropertyInfo<DateTime>("Birthdate"))
.fi
.PP
Definition at line 25 of file Person\&.cs\&.
.SS "readonly \fBPropertyInfo\fP<string> cslalighttest\&.Serialization\&.Person\&.NameProperty\fC [static]\fP"
\fBInitial value:\fP
.PP
.nf
= RegisterProperty<string>(
      typeof(Person),
      new PropertyInfo<string>("Name"))
.fi
.PP
Definition at line 21 of file Person\&.cs\&.
.SS "readonly \fBPropertyInfo\fP<\fBAddress\fP> cslalighttest\&.Serialization\&.Person\&.PrimaryAddressProperty\fC [static]\fP"
\fBInitial value:\fP
.PP
.nf
= RegisterProperty<Address>(
      typeof(Person),
      new PropertyInfo<Address>("PrimaryAddress"))
.fi
.PP
Definition at line 33 of file Person\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "\fBAddressList\fP cslalighttest\&.Serialization\&.Person\&.Addresses\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 63 of file Person\&.cs\&.
.SS "int cslalighttest\&.Serialization\&.Person\&.Age\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 49 of file Person\&.cs\&.
.SS "DateTime cslalighttest\&.Serialization\&.Person\&.Birthdate\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 43 of file Person\&.cs\&.
.SS "DateTimeOffset cslalighttest\&.Serialization\&.Person\&.DtoDate\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 75 of file Person\&.cs\&.
.SS "string cslalighttest\&.Serialization\&.Person\&.Name\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 37 of file Person\&.cs\&.
.SS "\fBAddress\fP cslalighttest\&.Serialization\&.Person\&.PrimaryAddress\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 81 of file Person\&.cs\&.
.SS "string cslalighttest\&.Serialization\&.Person\&.Unserialized\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 57 of file Person\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
