.TH "Csla.Testing.Business.EditableChildTests.GrandChildList" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Testing.Business.EditableChildTests.GrandChildList
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.BusinessListBase< GrandChildList, GrandChild >\fP\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBGrandChildList\fP \fBLoad\fP (Guid parentId)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static int \fBGrandChildId1\fP = 1"
.br
.ti -1c
.RI "static int \fBGrandChildId2\fP = 2"
.br
.ti -1c
.RI "static int \fBGrandChildId3\fP = 3"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 14 of file GrandChildList\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "static \fBGrandChildList\fP Csla\&.Testing\&.Business\&.EditableChildTests\&.GrandChildList\&.Load (Guid parentId)\fC [static]\fP"

.PP
Definition at line 16 of file GrandChildList\&.partial\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "int Csla\&.Testing\&.Business\&.EditableChildTests\&.GrandChildList\&.GrandChildId1 = 1\fC [static]\fP"

.PP
Definition at line 18 of file GrandChildList\&.cs\&.
.SS "int Csla\&.Testing\&.Business\&.EditableChildTests\&.GrandChildList\&.GrandChildId2 = 2\fC [static]\fP"

.PP
Definition at line 19 of file GrandChildList\&.cs\&.
.SS "int Csla\&.Testing\&.Business\&.EditableChildTests\&.GrandChildList\&.GrandChildId3 = 3\fC [static]\fP"

.PP
Definition at line 20 of file GrandChildList\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
