.TH "Csla.Test.ValidationRules.CascadeRoot" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.ValidationRules.CascadeRoot
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.BusinessBase< CascadeRoot >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBCheckRules\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static readonly \fBPropertyInfo\fP< int > \fBNum1Property\fP = RegisterProperty<int>(c => c\&.Num1)"
.br
.ti -1c
.RI "static readonly \fBPropertyInfo\fP< int > \fBNum2Property\fP = RegisterProperty<int>(c => c\&.Num2)"
.br
.ti -1c
.RI "static readonly \fBPropertyInfo\fP< int > \fBNum3Property\fP = RegisterProperty<int>(c => c\&.Num3)"
.br
.ti -1c
.RI "static readonly \fBPropertyInfo\fP< int > \fBNum4Property\fP = RegisterProperty<int>(c => c\&.Num4)"
.br
.ti -1c
.RI "static readonly \fBPropertyInfo\fP< int > \fBNum5Property\fP = RegisterProperty<int>(c => c\&.Num5)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBAddBusinessRules\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBNum1\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBNum2\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBNum3\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBNum4\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBNum5\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBValueAa\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBValueAb\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBValueAc\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBValueAd\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBValueAe\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBValueAf\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBValueAg\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBValueBa\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBValueBb\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "decimal \fBValueCa\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "decimal \fBValueCb\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "decimal \fBValueCc\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "decimal \fBValueCd\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "decimal \fBValueCe\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "bool \fBCascadeOnDirtyProperties\fP\fC [get, set]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 12 of file CascadeRoot\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override void Csla\&.Test\&.ValidationRules\&.CascadeRoot\&.AddBusinessRules ()\fC [protected]\fP"

.PP
Definition at line 152 of file CascadeRoot\&.cs\&.
.SS "void Csla\&.Test\&.ValidationRules\&.CascadeRoot\&.CheckRules ()"

.PP
Definition at line 14 of file CascadeRoot\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "readonly \fBPropertyInfo\fP<int> Csla\&.Test\&.ValidationRules\&.CascadeRoot\&.Num1Property = RegisterProperty<int>(c => c\&.Num1)\fC [static]\fP"

.PP
Definition at line 19 of file CascadeRoot\&.cs\&.
.SS "readonly \fBPropertyInfo\fP<int> Csla\&.Test\&.ValidationRules\&.CascadeRoot\&.Num2Property = RegisterProperty<int>(c => c\&.Num2)\fC [static]\fP"

.PP
Definition at line 26 of file CascadeRoot\&.cs\&.
.SS "readonly \fBPropertyInfo\fP<int> Csla\&.Test\&.ValidationRules\&.CascadeRoot\&.Num3Property = RegisterProperty<int>(c => c\&.Num3)\fC [static]\fP"

.PP
Definition at line 33 of file CascadeRoot\&.cs\&.
.SS "readonly \fBPropertyInfo\fP<int> Csla\&.Test\&.ValidationRules\&.CascadeRoot\&.Num4Property = RegisterProperty<int>(c => c\&.Num4)\fC [static]\fP"

.PP
Definition at line 40 of file CascadeRoot\&.cs\&.
.SS "readonly \fBPropertyInfo\fP<int> Csla\&.Test\&.ValidationRules\&.CascadeRoot\&.Num5Property = RegisterProperty<int>(c => c\&.Num5)\fC [static]\fP"

.PP
Definition at line 47 of file CascadeRoot\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "bool Csla\&.Test\&.ValidationRules\&.CascadeRoot\&.CascadeOnDirtyProperties\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 181 of file CascadeRoot\&.cs\&.
.SS "int Csla\&.Test\&.ValidationRules\&.CascadeRoot\&.Num1\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 20 of file CascadeRoot\&.cs\&.
.SS "int Csla\&.Test\&.ValidationRules\&.CascadeRoot\&.Num2\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 27 of file CascadeRoot\&.cs\&.
.SS "int Csla\&.Test\&.ValidationRules\&.CascadeRoot\&.Num3\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 34 of file CascadeRoot\&.cs\&.
.SS "int Csla\&.Test\&.ValidationRules\&.CascadeRoot\&.Num4\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 41 of file CascadeRoot\&.cs\&.
.SS "int Csla\&.Test\&.ValidationRules\&.CascadeRoot\&.Num5\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 48 of file CascadeRoot\&.cs\&.
.SS "int Csla\&.Test\&.ValidationRules\&.CascadeRoot\&.ValueAa\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 55 of file CascadeRoot\&.cs\&.
.SS "int Csla\&.Test\&.ValidationRules\&.CascadeRoot\&.ValueAb\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 62 of file CascadeRoot\&.cs\&.
.SS "int Csla\&.Test\&.ValidationRules\&.CascadeRoot\&.ValueAc\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 69 of file CascadeRoot\&.cs\&.
.SS "int Csla\&.Test\&.ValidationRules\&.CascadeRoot\&.ValueAd\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 76 of file CascadeRoot\&.cs\&.
.SS "int Csla\&.Test\&.ValidationRules\&.CascadeRoot\&.ValueAe\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 83 of file CascadeRoot\&.cs\&.
.SS "int Csla\&.Test\&.ValidationRules\&.CascadeRoot\&.ValueAf\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 90 of file CascadeRoot\&.cs\&.
.SS "int Csla\&.Test\&.ValidationRules\&.CascadeRoot\&.ValueAg\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 97 of file CascadeRoot\&.cs\&.
.SS "int Csla\&.Test\&.ValidationRules\&.CascadeRoot\&.ValueBa\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 104 of file CascadeRoot\&.cs\&.
.SS "int Csla\&.Test\&.ValidationRules\&.CascadeRoot\&.ValueBb\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 111 of file CascadeRoot\&.cs\&.
.SS "decimal Csla\&.Test\&.ValidationRules\&.CascadeRoot\&.ValueCa\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 118 of file CascadeRoot\&.cs\&.
.SS "decimal Csla\&.Test\&.ValidationRules\&.CascadeRoot\&.ValueCb\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 125 of file CascadeRoot\&.cs\&.
.SS "decimal Csla\&.Test\&.ValidationRules\&.CascadeRoot\&.ValueCc\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 132 of file CascadeRoot\&.cs\&.
.SS "decimal Csla\&.Test\&.ValidationRules\&.CascadeRoot\&.ValueCd\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 139 of file CascadeRoot\&.cs\&.
.SS "decimal Csla\&.Test\&.ValidationRules\&.CascadeRoot\&.ValueCe\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 146 of file CascadeRoot\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
