.TH "Csla.Analyzers.IntegrationTests.InternalConstructorTest" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Analyzers.IntegrationTests.InternalConstructorTest
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.BusinessBase< PrivateConstructorTest >\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 42 of file ConstructorTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
