.TH "Csla.Test.LazyLoad.AParent" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.LazyLoad.AParent
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.BusinessBase< AParent >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAChildList\fP \fBGetChildList\fP ()"
.br
.ti -1c
.RI "\fBAParent\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBPropertyInfo\fP< Guid > \fBIdProperty\fP = RegisterProperty<Guid>(c => c\&.Id)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "Guid \fBId\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBAChildList\fP \fBChildList\fP\fC [get]\fP"
.br
.ti -1c
.RI "new int \fBEditLevel\fP\fC [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 15 of file AParent\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Csla\&.Test\&.LazyLoad\&.AParent\&.AParent ()"

.PP
Definition at line 50 of file AParent\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBAChildList\fP Csla\&.Test\&.LazyLoad\&.AParent\&.GetChildList ()"

.PP
Definition at line 36 of file AParent\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBPropertyInfo\fP<Guid> Csla\&.Test\&.LazyLoad\&.AParent\&.IdProperty = RegisterProperty<Guid>(c => c\&.Id)\fC [static]\fP"

.PP
Definition at line 17 of file AParent\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "\fBAChildList\fP Csla\&.Test\&.LazyLoad\&.AParent\&.ChildList\fC [get]\fP"

.PP
Definition at line 26 of file AParent\&.cs\&.
.SS "new int Csla\&.Test\&.LazyLoad\&.AParent\&.EditLevel\fC [get]\fP"

.PP
Definition at line 45 of file AParent\&.cs\&.
.SS "Guid Csla\&.Test\&.LazyLoad\&.AParent\&.Id\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 18 of file AParent\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
