.TH "Csla.Xaml.CslaDataProviderCommandManager" 3 "Thu Jul 22 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Xaml.CslaDataProviderCommandManager \- Implements support for RoutedCommands that can be executed by the \fBCslaDataProvider\fP control\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits System\&.Windows\&.UIElement\&.
.SH "Detailed Description"
.PP 
Implements support for RoutedCommands that can be executed by the \fBCslaDataProvider\fP control\&. 

Use this object as the CommandTarget for command source objects when you want the \fBCslaDataProvider\fP to execute the command\&. 
.PP
Definition at line 24 of file CslaDataProviderCommandManager\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
