.TH "Csla.Test.ValidationRules.CascadeTests" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.ValidationRules.CascadeTests
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBBusinessRules_MustCascade_WhenCascadeOnDirtyPropertiesIsTrue\fP ()"
.br
.ti -1c
.RI "void \fBBusinessRules_MustNotCascade_WhenCanRunAsAffectedIsFalse\fP ()"
.br
.ti -1c
.RI "void \fBBusinessRules_MustNotCascade_WhenCascadeOnDirtyPropertiesIsFalse\fP ()"
.br
.ti -1c
.RI "void \fBBusinessRules_MustCascadeAsSpreadsheet_WhenCascadeOnDirtyPropertiesIsTrue\fP ()"
.br
.ti -1c
.RI "void \fBBusinessRules_MustCheckBothSums_WhenCascadeOnDirtyPropertiesIsTrue\fP ()"
.br
.ti -1c
.RI "void \fBBusinessRules_MustRecalculateSumAfterCaclulateFraction_WhenCascadeOnDirtyPropertiesIsTrue\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 9 of file CascadeTests\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Csla\&.Test\&.ValidationRules\&.CascadeTests\&.BusinessRules_MustCascade_WhenCascadeOnDirtyPropertiesIsTrue ()"

.PP
Definition at line 12 of file CascadeTests\&.cs\&.
.SS "void Csla\&.Test\&.ValidationRules\&.CascadeTests\&.BusinessRules_MustCascadeAsSpreadsheet_WhenCascadeOnDirtyPropertiesIsTrue ()"

.PP
Definition at line 60 of file CascadeTests\&.cs\&.
.SS "void Csla\&.Test\&.ValidationRules\&.CascadeTests\&.BusinessRules_MustCheckBothSums_WhenCascadeOnDirtyPropertiesIsTrue ()"

.PP
Definition at line 94 of file CascadeTests\&.cs\&.
.SS "void Csla\&.Test\&.ValidationRules\&.CascadeTests\&.BusinessRules_MustNotCascade_WhenCanRunAsAffectedIsFalse ()"

.PP
Definition at line 27 of file CascadeTests\&.cs\&.
.SS "void Csla\&.Test\&.ValidationRules\&.CascadeTests\&.BusinessRules_MustNotCascade_WhenCascadeOnDirtyPropertiesIsFalse ()"

.PP
Definition at line 44 of file CascadeTests\&.cs\&.
.SS "void Csla\&.Test\&.ValidationRules\&.CascadeTests\&.BusinessRules_MustRecalculateSumAfterCaclulateFraction_WhenCascadeOnDirtyPropertiesIsTrue ()"

.PP
Definition at line 119 of file CascadeTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
