.TH "Csla.Server.Hosts.DataPortalChannel.UpdateRequest" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Server.Hosts.DataPortalChannel.UpdateRequest \- Request message for updating a business object\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.ReadOnlyBase< UpdateRequest >\fP\&.
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static readonly \fBPropertyInfo\fP< byte[]> \fBObjectDataProperty\fP = RegisterProperty<byte[]>(c => c\&.ObjectData)"
.br
.RI "Serialized object data\&. "
.ti -1c
.RI "static readonly \fBPropertyInfo\fP< byte[]> \fBPrincipalProperty\fP = RegisterProperty<byte[]>(c => c\&.Principal)"
.br
.RI "Serialized data for the principal object\&. "
.ti -1c
.RI "static readonly \fBPropertyInfo\fP< byte[]> \fBGlobalContextProperty\fP = RegisterProperty<byte[]>(c => c\&.GlobalContext)"
.br
.RI "Serialized data for the global context object\&. "
.ti -1c
.RI "static readonly \fBPropertyInfo\fP< byte[]> \fBClientContextProperty\fP = RegisterProperty<byte[]>(c => c\&.ClientContext)"
.br
.RI "Serialized data for the client context object\&. "
.ti -1c
.RI "static readonly \fBPropertyInfo\fP< string > \fBClientCultureProperty\fP = RegisterProperty<string>(c => c\&.ClientCulture)"
.br
.RI "Serialized client culture\&. "
.ti -1c
.RI "static readonly \fBPropertyInfo\fP< string > \fBClientUICultureProperty\fP = RegisterProperty<string>(c => c\&.ClientUICulture)"
.br
.RI "Serialized client UI culture\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "byte[] \fBObjectData\fP\fC [get, set]\fP"
.br
.RI "Serialized object data\&. "
.ti -1c
.RI "byte[] \fBPrincipal\fP\fC [get, set]\fP"
.br
.RI "Serialized data for the principal object\&. "
.ti -1c
.RI "byte[] \fBGlobalContext\fP\fC [get, set]\fP"
.br
.RI "Serialized data for the global context object\&. "
.ti -1c
.RI "byte[] \fBClientContext\fP\fC [get, set]\fP"
.br
.RI "Serialized data for the client context object\&. "
.ti -1c
.RI "string \fBClientCulture\fP\fC [get, set]\fP"
.br
.RI "Serialized client culture\&. "
.ti -1c
.RI "string \fBClientUICulture\fP\fC [get, set]\fP"
.br
.RI "Serialized client UI culture\&. "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Request message for updating a business object\&. 


.PP
Definition at line 18 of file UpdateRequest\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "readonly \fBPropertyInfo\fP<byte[]> Csla\&.Server\&.Hosts\&.DataPortalChannel\&.UpdateRequest\&.ClientContextProperty = RegisterProperty<byte[]>(c => c\&.ClientContext)\fC [static]\fP"

.PP
Serialized data for the client context object\&. 
.PP
Definition at line 65 of file UpdateRequest\&.cs\&.
.SS "readonly \fBPropertyInfo\fP<string> Csla\&.Server\&.Hosts\&.DataPortalChannel\&.UpdateRequest\&.ClientCultureProperty = RegisterProperty<string>(c => c\&.ClientCulture)\fC [static]\fP"

.PP
Serialized client culture\&. The client culture\&.
.PP
Definition at line 80 of file UpdateRequest\&.cs\&.
.SS "readonly \fBPropertyInfo\fP<string> Csla\&.Server\&.Hosts\&.DataPortalChannel\&.UpdateRequest\&.ClientUICultureProperty = RegisterProperty<string>(c => c\&.ClientUICulture)\fC [static]\fP"

.PP
Serialized client UI culture\&. The client UI culture\&.
.PP
Definition at line 96 of file UpdateRequest\&.cs\&.
.SS "readonly \fBPropertyInfo\fP<byte[]> Csla\&.Server\&.Hosts\&.DataPortalChannel\&.UpdateRequest\&.GlobalContextProperty = RegisterProperty<byte[]>(c => c\&.GlobalContext)\fC [static]\fP"

.PP
Serialized data for the global context object\&. 
.PP
Definition at line 51 of file UpdateRequest\&.cs\&.
.SS "readonly \fBPropertyInfo\fP<byte[]> Csla\&.Server\&.Hosts\&.DataPortalChannel\&.UpdateRequest\&.ObjectDataProperty = RegisterProperty<byte[]>(c => c\&.ObjectData)\fC [static]\fP"

.PP
Serialized object data\&. 
.PP
Definition at line 23 of file UpdateRequest\&.cs\&.
.SS "readonly \fBPropertyInfo\fP<byte[]> Csla\&.Server\&.Hosts\&.DataPortalChannel\&.UpdateRequest\&.PrincipalProperty = RegisterProperty<byte[]>(c => c\&.Principal)\fC [static]\fP"

.PP
Serialized data for the principal object\&. 
.PP
Definition at line 37 of file UpdateRequest\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "byte [] Csla\&.Server\&.Hosts\&.DataPortalChannel\&.UpdateRequest\&.ClientContext\fC [get]\fP, \fC [set]\fP"

.PP
Serialized data for the client context object\&. 
.PP
Definition at line 70 of file UpdateRequest\&.cs\&.
.SS "string Csla\&.Server\&.Hosts\&.DataPortalChannel\&.UpdateRequest\&.ClientCulture\fC [get]\fP, \fC [set]\fP"

.PP
Serialized client culture\&. The client culture\&.
.PP
Definition at line 86 of file UpdateRequest\&.cs\&.
.SS "string Csla\&.Server\&.Hosts\&.DataPortalChannel\&.UpdateRequest\&.ClientUICulture\fC [get]\fP, \fC [set]\fP"

.PP
Serialized client UI culture\&. The client UI culture\&.
.PP
Definition at line 102 of file UpdateRequest\&.cs\&.
.SS "byte [] Csla\&.Server\&.Hosts\&.DataPortalChannel\&.UpdateRequest\&.GlobalContext\fC [get]\fP, \fC [set]\fP"

.PP
Serialized data for the global context object\&. 
.PP
Definition at line 56 of file UpdateRequest\&.cs\&.
.SS "byte [] Csla\&.Server\&.Hosts\&.DataPortalChannel\&.UpdateRequest\&.ObjectData\fC [get]\fP, \fC [set]\fP"

.PP
Serialized object data\&. 
.PP
Definition at line 28 of file UpdateRequest\&.cs\&.
.SS "byte [] Csla\&.Server\&.Hosts\&.DataPortalChannel\&.UpdateRequest\&.Principal\fC [get]\fP, \fC [set]\fP"

.PP
Serialized data for the principal object\&. 
.PP
Definition at line 42 of file UpdateRequest\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
