.TH "C:/Users/korye/source/repos/csla/Source/Csla/Configuration/Fluent/CslaSecurityConfiguration.cs" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/korye/source/repos/csla/Source/Csla/Configuration/Fluent/CslaSecurityConfiguration.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCsla\&.Configuration\&.CslaSecurityConfigurationExtension\fP"
.br
.RI "Extension method for \fBCslaSecurityConfiguration\fP "
.ti -1c
.RI "class \fBCsla\&.Configuration\&.CslaSecurityConfiguration\fP"
.br
.RI "Use this type to configure the settings for security\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBCsla\fP"
.br
.ti -1c
.RI "namespace \fBCsla\&.Configuration\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
