.TH "Csla.Test.DataPortalTest.SingleCommand" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.DataPortalTest.SingleCommand
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.CommandBase< SingleCommand >\fP\&.
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static readonly \fBPropertyInfo\fP< int > \fBValueProperty\fP = RegisterProperty<int>(c => c\&.Value)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBDataPortal_Execute\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBValue\fP\fC [get, set]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 230 of file Single\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Csla\&.Test\&.DataPortalTest\&.SingleCommand\&.DataPortal_Execute ()\fC [protected]\fP"

.PP
Definition at line 240 of file Single\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "readonly \fBPropertyInfo\fP<int> Csla\&.Test\&.DataPortalTest\&.SingleCommand\&.ValueProperty = RegisterProperty<int>(c => c\&.Value)\fC [static]\fP"

.PP
Definition at line 232 of file Single\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "int Csla\&.Test\&.DataPortalTest\&.SingleCommand\&.Value\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 233 of file Single\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
