.TH "cslalighttest.Serialization.CustomerWithEnum" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cslalighttest.Serialization.CustomerWithEnum \- Implementation of a test business object with an enum\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.BusinessBase< CustomerWithEnum >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCustomerWithEnum\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBName\fP\fC [get, set]\fP"
.br
.RI "Gets or sets the name of the \fBCustomerWithEnum\fP\&. "
.ti -1c
.RI "\fBCustomerQuality\fP \fBQuality\fP\fC [get, set]\fP"
.br
.RI "Gets or sets the quality of the customer\&. "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Implementation of a test business object with an enum\&. 


.PP
Definition at line 28 of file CustomerWithEnum\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "cslalighttest\&.Serialization\&.CustomerWithEnum\&.CustomerWithEnum ()"

.PP
Definition at line 32 of file CustomerWithEnum\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "string cslalighttest\&.Serialization\&.CustomerWithEnum\&.Name\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the name of the \fBCustomerWithEnum\fP\&. 
.PP
Definition at line 46 of file CustomerWithEnum\&.cs\&.
.SS "\fBCustomerQuality\fP cslalighttest\&.Serialization\&.CustomerWithEnum\&.Quality\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the quality of the customer\&. 
.PP
Definition at line 57 of file CustomerWithEnum\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
