.TH "Csla.Testing.Business.BusyStatus.ItemWithAsynchRule" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Testing.Business.BusyStatus.ItemWithAsynchRule
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.BusinessBase< ItemWithAsynchRule >\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFiveSecondsLongRule\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBItemWithAsynchRule\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBAddBusinessRules\fP ()"
.br
.ti -1c
.RI "void \fBDataPortal_Create\fP ()"
.br
.ti -1c
.RI "void \fBDataPortal_Insert\fP ()"
.br
.ti -1c
.RI "void \fBDataPortal_Update\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBId\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBOperationResult\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBRuleField\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "bool \fBIsRunningRules\fP\fC [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 21 of file ItemWithAsynchRule\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Csla\&.Testing\&.Business\&.BusyStatus\&.ItemWithAsynchRule\&.ItemWithAsynchRule ()"

.PP
Definition at line 23 of file ItemWithAsynchRule\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override void Csla\&.Testing\&.Business\&.BusyStatus\&.ItemWithAsynchRule\&.AddBusinessRules ()\fC [protected]\fP"

.PP
Definition at line 81 of file ItemWithAsynchRule\&.cs\&.
.SS "void Csla\&.Testing\&.Business\&.BusyStatus\&.ItemWithAsynchRule\&.DataPortal_Create ()\fC [protected]\fP"

.PP
Definition at line 132 of file ItemWithAsynchRule\&.cs\&.
.SS "void Csla\&.Testing\&.Business\&.BusyStatus\&.ItemWithAsynchRule\&.DataPortal_Insert ()\fC [protected]\fP"

.PP
Definition at line 140 of file ItemWithAsynchRule\&.cs\&.
.SS "void Csla\&.Testing\&.Business\&.BusyStatus\&.ItemWithAsynchRule\&.DataPortal_Update ()\fC [protected]\fP"

.PP
Definition at line 148 of file ItemWithAsynchRule\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "string Csla\&.Testing\&.Business\&.BusyStatus\&.ItemWithAsynchRule\&.Id\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 27 of file ItemWithAsynchRule\&.cs\&.
.SS "bool Csla\&.Testing\&.Business\&.BusyStatus\&.ItemWithAsynchRule\&.IsRunningRules\fC [get]\fP"

.PP
Definition at line 76 of file ItemWithAsynchRule\&.cs\&.
.SS "string Csla\&.Testing\&.Business\&.BusyStatus\&.ItemWithAsynchRule\&.OperationResult\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 41 of file ItemWithAsynchRule\&.cs\&.
.SS "string Csla\&.Testing\&.Business\&.BusyStatus\&.ItemWithAsynchRule\&.RuleField\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 55 of file ItemWithAsynchRule\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
