.TH "Csla.Test.Windows.BindingRefreshTests" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.Windows.BindingRefreshTests
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBTestDoNotRefreshOnException\fP ()"
.br
.ti -1c
.RI "void \fBTestRefreshOnException\fP ()"
.br
.ti -1c
.RI "void \fBTestRefresh\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 32 of file BindingRefreshTests\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Csla\&.Test\&.Windows\&.BindingRefreshTests\&.TestDoNotRefreshOnException ()"

.PP
Definition at line 37 of file BindingRefreshTests\&.cs\&.
.SS "void Csla\&.Test\&.Windows\&.BindingRefreshTests\&.TestRefresh ()"

.PP
Definition at line 93 of file BindingRefreshTests\&.cs\&.
.SS "void Csla\&.Test\&.Windows\&.BindingRefreshTests\&.TestRefreshOnException ()"

.PP
Definition at line 66 of file BindingRefreshTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
