.TH "Csla.Test.ValidationRules.HasLambdaRules" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.ValidationRules.HasLambdaRules
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.BusinessBase< HasLambdaRules >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "string[] \fBGetRuleDescriptions\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBHasLambdaRules\fP \fBNew\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBPropertyInfo\fP< string > \fBSsnProperty\fP = RegisterProperty<string>(c => c\&.Ssn)"
.br
.ti -1c
.RI "static \fBPropertyInfo\fP< string > \fBSsn2Property\fP = RegisterProperty<string>(c => c\&.Ssn2)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBDataPortal_Create\fP ()"
.br
.ti -1c
.RI "override void \fBAddBusinessRules\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBSsn\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBSsn2\fP\fC [get, set]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 10 of file HasLambdaRules\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override void Csla\&.Test\&.ValidationRules\&.HasLambdaRules\&.AddBusinessRules ()\fC [protected]\fP"

.PP
Definition at line 46 of file HasLambdaRules\&.cs\&.
.SS "void Csla\&.Test\&.ValidationRules\&.HasLambdaRules\&.DataPortal_Create ()\fC [protected]\fP"

.PP
Definition at line 35 of file HasLambdaRules\&.cs\&.
.SS "string [] Csla\&.Test\&.ValidationRules\&.HasLambdaRules\&.GetRuleDescriptions ()"

.PP
Definition at line 42 of file HasLambdaRules\&.cs\&.
.SS "static \fBHasLambdaRules\fP Csla\&.Test\&.ValidationRules\&.HasLambdaRules\&.New ()\fC [static]\fP"

.PP
Definition at line 28 of file HasLambdaRules\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBPropertyInfo\fP<string> Csla\&.Test\&.ValidationRules\&.HasLambdaRules\&.Ssn2Property = RegisterProperty<string>(c => c\&.Ssn2)\fC [static]\fP"

.PP
Definition at line 20 of file HasLambdaRules\&.cs\&.
.SS "\fBPropertyInfo\fP<string> Csla\&.Test\&.ValidationRules\&.HasLambdaRules\&.SsnProperty = RegisterProperty<string>(c => c\&.Ssn)\fC [static]\fP"

.PP
Definition at line 12 of file HasLambdaRules\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "string Csla\&.Test\&.ValidationRules\&.HasLambdaRules\&.Ssn\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 14 of file HasLambdaRules\&.cs\&.
.SS "string Csla\&.Test\&.ValidationRules\&.HasLambdaRules\&.Ssn2\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 22 of file HasLambdaRules\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
