.TH "Csla.ObjectAuthorizationRulesAttribute" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.ObjectAuthorizationRulesAttribute \- Attribute identifying static method invoked to add object authorization rules for type\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Attribute\&.
.SH "Detailed Description"
.PP 
Attribute identifying static method invoked to add object authorization rules for type\&. 


.PP
Definition at line 17 of file ObjectAuthorizationRulesAttribute\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
