.TH "Csla.Serialization.Mobile.ICslaWriter" 3 "Thu Jul 22 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Serialization.Mobile.ICslaWriter \- Represents a class that can be used to write a list of \fBSerializationInfo\fP objects into a stream, typically MemoryStream  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBCsla\&.Serialization\&.Mobile\&.CslaBinaryWriter\fP, \fBCsla\&.Serialization\&.Mobile\&.CslaLegacyBinaryWriter\fP, \fBCsla\&.Serialization\&.Mobile\&.CslaXmlBinaryWriter\fP, and \fBCsla\&.Serialization\&.Mobile\&.CslaXmlWriter\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBWrite\fP (Stream serializationStream, List< \fBSerializationInfo\fP > objectData)"
.br
.RI "Write a list of \fBSerializationInfo\fP objects into a stream, typically MemoryStream "
.in -1c
.SH "Detailed Description"
.PP 
Represents a class that can be used to write a list of \fBSerializationInfo\fP objects into a stream, typically MemoryStream 


.PP
Definition at line 11 of file ICslaWriter\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Csla\&.Serialization\&.Mobile\&.ICslaWriter\&.Write (Stream serializationStream, List< \fBSerializationInfo\fP > objectData)"

.PP
Write a list of \fBSerializationInfo\fP objects into a stream, typically MemoryStream 
.PP
\fBParameters\fP
.RS 4
\fIserializationStream\fP Stream to write the data into
.br
\fIobjectData\fP List of \fBSerializationInfo\fP objects to write
.RE
.PP

.PP
Implemented in \fBCsla\&.Serialization\&.Mobile\&.CslaXmlWriter\fP, \fBCsla\&.Serialization\&.Mobile\&.CslaXmlBinaryWriter\fP, \fBCsla\&.Serialization\&.Mobile\&.CslaLegacyBinaryWriter\fP, and \fBCsla\&.Serialization\&.Mobile\&.CslaBinaryWriter\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
