.TH "Csla.Test.CslaDataProvider" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.CslaDataProvider
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCslaDataProviderTests\fP"
.br
.ti -1c
.RI "class \fBCustomer\fP"
.br
.ti -1c
.RI "class \fBProviderList\fP"
.br
.ti -1c
.RI "class \fBProviderChild\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
