.TH "Csla.Test.ObjectFactory.Root" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.ObjectFactory.Root
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.BusinessBase< Root >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBMarkAsNew\fP ()"
.br
.ti -1c
.RI "void \fBMarkAsOld\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBData\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "Csla\&.ApplicationContext\&.ExecutionLocations \fBLocation\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBTransactionalTypes\fP \fBTransactionalType\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBIsolationLevel\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBTransactionTimeout\fP\fC [get, set]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 18 of file Root\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Csla\&.Test\&.ObjectFactory\&.Root\&.MarkAsNew ()"

.PP
Definition at line 55 of file Root\&.cs\&.
.SS "void Csla\&.Test\&.ObjectFactory\&.Root\&.MarkAsOld ()"

.PP
Definition at line 60 of file Root\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "string Csla\&.Test\&.ObjectFactory\&.Root\&.Data\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 21 of file Root\&.cs\&.
.SS "string Csla\&.Test\&.ObjectFactory\&.Root\&.IsolationLevel\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 42 of file Root\&.cs\&.
.SS "Csla\&.ApplicationContext\&.ExecutionLocations Csla\&.Test\&.ObjectFactory\&.Root\&.Location\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 28 of file Root\&.cs\&.
.SS "\fBTransactionalTypes\fP Csla\&.Test\&.ObjectFactory\&.Root\&.TransactionalType\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 35 of file Root\&.cs\&.
.SS "int Csla\&.Test\&.ObjectFactory\&.Root\&.TransactionTimeout\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 49 of file Root\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
