.TH "Csla.Analyzers.Tests.FindOperationsWithIncorrectReturnTypeResolveCorrectTypeCodeFixTests" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Analyzers.Tests.FindOperationsWithIncorrectReturnTypeResolveCorrectTypeCodeFixTests
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBVerifyGetFixableDiagnosticIds\fP ()"
.br
.ti -1c
.RI "async Task \fBVerifyGetFixesWhenChangingToVoid\fP ()"
.br
.ti -1c
.RI "async Task \fBVerifyGetFixesWhenChangingToTask\fP ()"
.br
.ti -1c
.RI "async Task \fBVerifyGetFixesWhenChangingToTaskAndUsingDoesNotExist\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 16 of file FindOperationsWithIncorrectReturnTypeResolveCorrectTypeCodeFixTests\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Csla\&.Analyzers\&.Tests\&.FindOperationsWithIncorrectReturnTypeResolveCorrectTypeCodeFixTests\&.VerifyGetFixableDiagnosticIds ()"

.PP
Definition at line 19 of file FindOperationsWithIncorrectReturnTypeResolveCorrectTypeCodeFixTests\&.cs\&.
.SS "async Task Csla\&.Analyzers\&.Tests\&.FindOperationsWithIncorrectReturnTypeResolveCorrectTypeCodeFixTests\&.VerifyGetFixesWhenChangingToTask ()"

.PP
Definition at line 69 of file FindOperationsWithIncorrectReturnTypeResolveCorrectTypeCodeFixTests\&.cs\&.
.SS "async Task Csla\&.Analyzers\&.Tests\&.FindOperationsWithIncorrectReturnTypeResolveCorrectTypeCodeFixTests\&.VerifyGetFixesWhenChangingToTaskAndUsingDoesNotExist ()"

.PP
Definition at line 108 of file FindOperationsWithIncorrectReturnTypeResolveCorrectTypeCodeFixTests\&.cs\&.
.SS "async Task Csla\&.Analyzers\&.Tests\&.FindOperationsWithIncorrectReturnTypeResolveCorrectTypeCodeFixTests\&.VerifyGetFixesWhenChangingToVoid ()"

.PP
Definition at line 30 of file FindOperationsWithIncorrectReturnTypeResolveCorrectTypeCodeFixTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
