.TH "Csla.Test.DataPortal.ArrayDataPortalClass" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.DataPortal.ArrayDataPortalClass
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.BusinessBase< ArrayDataPortalClass >\fP\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBArrayDataPortalClass\fP \fBGet\fP (int[] values)"
.br
.ti -1c
.RI "static \fBArrayDataPortalClass\fP \fBGet\fP (string[] values)"
.br
.ti -1c
.RI "static \fBArrayDataPortalClass\fP \fBGetParams\fP (params int[] values)"
.br
.ti -1c
.RI "static \fBArrayDataPortalClass\fP \fBGetParams\fP (params string[] values)"
.br
.ti -1c
.RI "static \fBArrayDataPortalClass\fP \fBGetChild\fP (int[] values)"
.br
.ti -1c
.RI "static \fBArrayDataPortalClass\fP \fBGetChild\fP (string[] values)"
.br
.ti -1c
.RI "static \fBArrayDataPortalClass\fP \fBGetChildParams\fP (params int[] values)"
.br
.ti -1c
.RI "static \fBArrayDataPortalClass\fP \fBGetChildParams\fP (params string[] values)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 92 of file ArrayTests\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "static \fBArrayDataPortalClass\fP Csla\&.Test\&.DataPortal\&.ArrayDataPortalClass\&.Get (int[] values)\fC [static]\fP"

.PP
Definition at line 96 of file ArrayTests\&.cs\&.
.SS "static \fBArrayDataPortalClass\fP Csla\&.Test\&.DataPortal\&.ArrayDataPortalClass\&.Get (string[] values)\fC [static]\fP"

.PP
Definition at line 101 of file ArrayTests\&.cs\&.
.SS "static \fBArrayDataPortalClass\fP Csla\&.Test\&.DataPortal\&.ArrayDataPortalClass\&.GetChild (int[] values)\fC [static]\fP"

.PP
Definition at line 116 of file ArrayTests\&.cs\&.
.SS "static \fBArrayDataPortalClass\fP Csla\&.Test\&.DataPortal\&.ArrayDataPortalClass\&.GetChild (string[] values)\fC [static]\fP"

.PP
Definition at line 121 of file ArrayTests\&.cs\&.
.SS "static \fBArrayDataPortalClass\fP Csla\&.Test\&.DataPortal\&.ArrayDataPortalClass\&.GetChildParams (params int[] values)\fC [static]\fP"

.PP
Definition at line 126 of file ArrayTests\&.cs\&.
.SS "static \fBArrayDataPortalClass\fP Csla\&.Test\&.DataPortal\&.ArrayDataPortalClass\&.GetChildParams (params string[] values)\fC [static]\fP"

.PP
Definition at line 131 of file ArrayTests\&.cs\&.
.SS "static \fBArrayDataPortalClass\fP Csla\&.Test\&.DataPortal\&.ArrayDataPortalClass\&.GetParams (params int[] values)\fC [static]\fP"

.PP
Definition at line 106 of file ArrayTests\&.cs\&.
.SS "static \fBArrayDataPortalClass\fP Csla\&.Test\&.DataPortal\&.ArrayDataPortalClass\&.GetParams (params string[] values)\fC [static]\fP"

.PP
Definition at line 111 of file ArrayTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
