.TH "Csla.Analyzers.FindOperationsWithIncorrectReturnTypeResolveCorrectTypeCodeFix" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Analyzers.FindOperationsWithIncorrectReturnTypeResolveCorrectTypeCodeFix
.SH SYNOPSIS
.br
.PP
.PP
Inherits CodeFixProvider\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "sealed override FixAllProvider \fBGetFixAllProvider\fP ()"
.br
.ti -1c
.RI "override async Task \fBRegisterCodeFixesAsync\fP (CodeFixContext context)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override ImmutableArray< string > \fBFixableDiagnosticIds\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 16 of file FindOperationsWithIncorrectReturnTypeResolveCorrectTypeCodeFix\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "sealed override FixAllProvider Csla\&.Analyzers\&.FindOperationsWithIncorrectReturnTypeResolveCorrectTypeCodeFix\&.GetFixAllProvider ()"

.SS "override async Task Csla\&.Analyzers\&.FindOperationsWithIncorrectReturnTypeResolveCorrectTypeCodeFix\&.RegisterCodeFixesAsync (CodeFixContext context)"

.PP
Definition at line 23 of file FindOperationsWithIncorrectReturnTypeResolveCorrectTypeCodeFix\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "override ImmutableArray<string> Csla\&.Analyzers\&.FindOperationsWithIncorrectReturnTypeResolveCorrectTypeCodeFix\&.FixableDiagnosticIds\fC [get]\fP"

.PP
Definition at line 19 of file FindOperationsWithIncorrectReturnTypeResolveCorrectTypeCodeFix\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
