.TH "cslalighttest.CslaDataProvider.CustomerContactList" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cslalighttest.CslaDataProvider.CustomerContactList
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.BusinessListBase< CustomerContactList, CustomerContact >\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBCustomer\fP \fBMyParent\fP\fC [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 20 of file CustomerContactList\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "\fBCustomer\fP cslalighttest\&.CslaDataProvider\&.CustomerContactList\&.MyParent\fC [get]\fP"

.PP
Definition at line 23 of file CustomerContactList\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
