.TH "Csla.Server.Hosts.WcfChannel" 3 "Thu Jul 22 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Server.Hosts.WcfChannel
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCreateRequest\fP"
.br
.RI "Request message for creating a new business object\&. "
.ti -1c
.RI "class \fBDeleteRequest\fP"
.br
.RI "Request message for deleting a business object\&. "
.ti -1c
.RI "class \fBFetchRequest\fP"
.br
.RI "Request message for retrieving an existing business object\&. "
.ti -1c
.RI "class \fBNetDataContractOperationBehavior\fP"
.br
.RI "Override the DataContract serialization behavior to use the NetDataContractSerializer\&. "
.ti -1c
.RI "class \fBUpdateRequest\fP"
.br
.RI "Request message for updating a business object\&. "
.ti -1c
.RI "class \fBUseNetDataContractAttribute\fP"
.br
.RI "Specify that WCF should serialize objects in a \&.NET specific manner to as to preserve complex object references and to be able to deserialize the graph into the same type as the original objets\&. "
.ti -1c
.RI "class \fBWcfResponse\fP"
.br
.RI "Response message for returning the results of a data portal call\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
