.TH "Csla.DataPortalResult< T >" 3 "Thu Jul 22 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.DataPortalResult< T > \- \fBDataPortalResult\fP defines the results of \fBDataPortal\fP operation\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits EventArgs, and \fBCsla\&.IDataPortalResult\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDataPortalResult\fP (T obj, Exception ex, object userState)"
.br
.RI "Create new instance of data portal result "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "T \fBObject\fP\fC [get]\fP"
.br
.RI "Object that \fBDataPortal\fP received as a result of current operation "
.ti -1c
.RI "Exception \fBError\fP\fC [get]\fP"
.br
.RI "Error that occurred during the DataPotal call\&. "
.ti -1c
.RI "object \fBUserState\fP\fC [get]\fP"
.br
.RI "User defined information that was passed into data portal on initial request "
.in -1c
.SH "Detailed Description"
.PP 
\fBDataPortalResult\fP defines the results of \fBDataPortal\fP operation\&. 

It contains object that was received from the server, an error (if occurred) and userState - user defined information that was passed into data portal on initial request
.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP Type of object that \fBDataPortal\fP received
.RE
.PP

.PP
Definition at line 19 of file DataPortalResult\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBCsla\&.DataPortalResult\fP< T >\&.\fBDataPortalResult\fP (T obj, Exception ex, object userState)"

.PP
Create new instance of data portal result 
.PP
\fBParameters\fP
.RS 4
\fIobj\fP Object that \fBDataPortal\fP received as a result of current operation 
.br
\fIex\fP Error that occurred during the DataPotal call\&. This will be null if no errors occurred\&. 
.br
\fIuserState\fP User defined information that was passed into data portal on initial request 
.RE
.PP

.PP
Definition at line 51 of file DataPortalResult\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "Exception \fBCsla\&.DataPortalResult\fP< T >\&.Error\fC [get]\fP"

.PP
Error that occurred during the DataPotal call\&. This will be null if no errors occurred\&.
.PP
Definition at line 29 of file DataPortalResult\&.cs\&.
.SS "T \fBCsla\&.DataPortalResult\fP< T >\&.Object\fC [get]\fP"

.PP
Object that \fBDataPortal\fP received as a result of current operation 
.PP
Definition at line 24 of file DataPortalResult\&.cs\&.
.SS "object \fBCsla\&.DataPortalResult\fP< T >\&.UserState\fC [get]\fP"

.PP
User defined information that was passed into data portal on initial request 
.PP
Definition at line 35 of file DataPortalResult\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
