.TH "Csla.Test.Silverlight.DataPortal.AuthorizeDataPortalTests" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.Silverlight.DataPortal.AuthorizeDataPortalTests \- Set of integration tests for IAUthorizeDataPortal Notice 2 roundtrips to the server in each test, first being Execute Command, and second being a \fBData\fP Portal call being tested\&. (Create, Fatch, Delete, and Update)\&. The reason for the first roundtrip is to set the appSetting in App\&.Config to value needed by the test  

.SH SYNOPSIS
.br
.PP
.PP
Inherits TestBase\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "async Task \fBIAuthorizeDataPortal_Implementation_Allows_Creation\fP ()"
.br
.ti -1c
.RI "async Task \fBIAuthorizeDataPortal_Implementation_Allows_Fetch\fP ()"
.br
.ti -1c
.RI "async Task \fBIAuthorizeDataPortal_Implementation_Allows_Delete\fP ()"
.br
.ti -1c
.RI "async Task \fBIAuthorizeDataPortal_Implementation_Allows_Update\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Set of integration tests for IAUthorizeDataPortal Notice 2 roundtrips to the server in each test, first being Execute Command, and second being a \fBData\fP Portal call being tested\&. (Create, Fatch, Delete, and Update)\&. The reason for the first roundtrip is to set the appSetting in App\&.Config to value needed by the test 


.PP
Definition at line 35 of file AuthorizeDataPortalTests\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "async Task Csla\&.Test\&.Silverlight\&.DataPortal\&.AuthorizeDataPortalTests\&.IAuthorizeDataPortal_Implementation_Allows_Creation ()"

.PP
Definition at line 38 of file AuthorizeDataPortalTests\&.cs\&.
.SS "async Task Csla\&.Test\&.Silverlight\&.DataPortal\&.AuthorizeDataPortalTests\&.IAuthorizeDataPortal_Implementation_Allows_Delete ()"

.PP
Definition at line 72 of file AuthorizeDataPortalTests\&.cs\&.
.SS "async Task Csla\&.Test\&.Silverlight\&.DataPortal\&.AuthorizeDataPortalTests\&.IAuthorizeDataPortal_Implementation_Allows_Fetch ()"

.PP
Definition at line 55 of file AuthorizeDataPortalTests\&.cs\&.
.SS "async Task Csla\&.Test\&.Silverlight\&.DataPortal\&.AuthorizeDataPortalTests\&.IAuthorizeDataPortal_Implementation_Allows_Update ()"

.PP
Definition at line 86 of file AuthorizeDataPortalTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
