.TH "Csla.Xaml.PropertyInfo" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Xaml.PropertyInfo \- Expose metastate information about a property\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits FrameworkElement, and System\&.ComponentModel\&.INotifyPropertyChanged\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPropertyInfo\fP ()"
.br
.RI "Creates an instance of the object\&. "
.ti -1c
.RI "\fBPropertyInfo\fP (bool testing)"
.br
.RI "Creates an instance of the object for testing\&. "
.ti -1c
.RI "virtual void \fBUpdateState\fP ()"
.br
.RI "Updates the metastate values on control based on the current state of the business object and property\&. "
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static readonly DependencyProperty \fBBrokenRulesProperty\fP"
.br
.RI "Gets the broken rules collection from the business object\&. "
.ti -1c
.RI "static readonly DependencyProperty \fBMyDataContextProperty\fP"
.br
.RI "Used to monitor for changes in the binding path\&. "
.ti -1c
.RI "static readonly DependencyProperty \fBRelativeBindingProperty\fP"
.br
.RI "Used to monitor for changes in the binding path\&. "
.ti -1c
.RI "static readonly DependencyProperty \fBPropertyProperty\fP"
.br
.RI "Gets or sets the source business property to which this control is bound\&. "
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual BindingExpression \fBParseRelativeBinding\fP (BindingExpression sourceBinding)"
.br
.RI "Checks a binding expression to see if it is a relative source binding used in a control template\&. "
.ti -1c
.RI "virtual void \fBSetSource\fP (bool propertyValueChanged)"
.br
.RI "Sets the source binding and updates status\&. "
.ti -1c
.RI "virtual void \fBSetSource\fP (object dataItem)"
.br
.RI "Sets the source binding and updates status\&. "
.ti -1c
.RI "object \fBGetRealSource\fP (object source, string bindingPath)"
.br
.RI "Gets the real source helper method\&. "
.ti -1c
.RI "PropertyPath \fBGetRelativePath\fP (object source, string bindingPath)"
.br
.RI "Gets the part of the binding path relevant to the given source\&. "
.ti -1c
.RI "virtual void \fBOnPropertyChanged\fP (string propertyName)"
.br
.RI "Raises the PropertyChanged event\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "ObservableCollection< \fBBrokenRule\fP > \fBBrokenRules\fP\fC [get]\fP"
.br
.RI "Gets the broken rules collection from the business object\&. "
.ti -1c
.RI "object \fBSource\fP\fC [get, set]\fP"
.br
.RI "Gets or sets the Source\&. "
.ti -1c
.RI "string \fBBindingPath\fP\fC [get, set]\fP"
.br
.RI "Gets or sets the binding path\&. "
.ti -1c
.RI "object \fBProperty\fP\fC [get, set]\fP"
.br
.RI "Gets or sets the source business property to which this control is bound\&. "
.ti -1c
.RI "string \fBErrorText\fP\fC [get]\fP"
.br
.RI "Gets the validation error messages for a property on the Model "
.ti -1c
.RI "string \fBWarningText\fP\fC [get]\fP"
.br
.RI "Gets the validation warning messages for a property on the Model "
.ti -1c
.RI "string \fBInformationText\fP\fC [get]\fP"
.br
.RI "Gets the validation information messages for a property on the Model "
.ti -1c
.RI "object \fBValue\fP\fC [get, set]\fP"
.br
.RI "Gets and sets the value of the property on the business object\&. "
.ti -1c
.RI "bool \fBCanRead\fP\fC [get, protected set]\fP"
.br
.RI "Gets a value indicating whether the user is authorized to read the property\&. "
.ti -1c
.RI "bool \fBCanWrite\fP\fC [get, protected set]\fP"
.br
.RI "Gets a value indicating whether the user is authorized to write the property\&. "
.ti -1c
.RI "bool \fBIsBusy\fP\fC [get]\fP"
.br
.RI "Gets a value indicating whether the property is busy with an asynchronous operation\&. "
.ti -1c
.RI "bool \fBIsValid\fP\fC [get]\fP"
.br
.RI "Gets a value indicating whether the property is valid\&. "
.ti -1c
.RI "\fBRuleSeverity\fP \fBRuleSeverity\fP\fC [get]\fP"
.br
.RI "Gets a value indicating the worst severity of all broken rules for this property (if IsValid is false)\&. "
.ti -1c
.RI "string \fBRuleDescription\fP\fC [get]\fP"
.br
.RI "Gets the description of the most severe broken rule for this property\&. "
.ti -1c
.RI "object \fBCustomTag\fP\fC [get, set]\fP"
.br
.RI "Gets or sets an arbitrary value associated with this \fBPropertyInfo\fP instance\&. "
.in -1c
.SS "Events"

.in +1c
.ti -1c
.RI "PropertyChangedEventHandler \fBPropertyChanged\fP"
.br
.RI "Event raised when a property has changed\&. "
.in -1c
.SH "Detailed Description"
.PP 
Expose metastate information about a property\&. 


.PP
Definition at line 38 of file PropertyInfo\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Csla\&.Xaml\&.PropertyInfo\&.PropertyInfo ()"

.PP
Creates an instance of the object\&. 
.PP
Definition at line 47 of file PropertyInfo\&.cs\&.
.SS "Csla\&.Xaml\&.PropertyInfo\&.PropertyInfo (bool testing)"

.PP
Creates an instance of the object for testing\&. 
.PP
\fBParameters\fP
.RS 4
\fItesting\fP \fBTest\fP mode parameter\&.
.RE
.PP

.PP
Definition at line 70 of file PropertyInfo\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "object Csla\&.Xaml\&.PropertyInfo\&.GetRealSource (object source, string bindingPath)\fC [protected]\fP"

.PP
Gets the real source helper method\&. 
.PP
\fBParameters\fP
.RS 4
\fIsource\fP The source\&.
.br
\fIbindingPath\fP The binding path\&.
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
Definition at line 457 of file PropertyInfo\&.cs\&.
.SS "PropertyPath Csla\&.Xaml\&.PropertyInfo\&.GetRelativePath (object source, string bindingPath)\fC [protected]\fP"

.PP
Gets the part of the binding path relevant to the given source\&. 
.PP
\fBParameters\fP
.RS 4
\fIsource\fP The source\&.
.br
\fIbindingPath\fP The binding path\&.
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
Definition at line 483 of file PropertyInfo\&.cs\&.
.SS "virtual void Csla\&.Xaml\&.PropertyInfo\&.OnPropertyChanged (string propertyName)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Raises the PropertyChanged event\&. 
.PP
\fBParameters\fP
.RS 4
\fIpropertyName\fP Name of the changed property\&.
.RE
.PP

.PP
Definition at line 878 of file PropertyInfo\&.cs\&.
.SS "virtual BindingExpression Csla\&.Xaml\&.PropertyInfo\&.ParseRelativeBinding (BindingExpression sourceBinding)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Checks a binding expression to see if it is a relative source binding used in a control template\&. 
.PP
\fBParameters\fP
.RS 4
\fIsourceBinding\fP The binding expression to parse\&.
.RE
.PP
\fBReturns\fP
.RS 4
If the source binding is a relative source binding, this method finds the proper dependency property on the parent control and returns the binding expression for that property\&.
.RE
.PP

.PP
Definition at line 317 of file PropertyInfo\&.cs\&.
.SS "virtual void Csla\&.Xaml\&.PropertyInfo\&.SetSource (bool propertyValueChanged)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Sets the source binding and updates status\&. 
.PP
Definition at line 361 of file PropertyInfo\&.cs\&.
.SS "virtual void Csla\&.Xaml\&.PropertyInfo\&.SetSource (object dataItem)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Sets the source binding and updates status\&. 
.PP
Definition at line 373 of file PropertyInfo\&.cs\&.
.SS "virtual void Csla\&.Xaml\&.PropertyInfo\&.UpdateState ()\fC [virtual]\fP"

.PP
Updates the metastate values on control based on the current state of the business object and property\&. 
.PP
Definition at line 790 of file PropertyInfo\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "readonly DependencyProperty Csla\&.Xaml\&.PropertyInfo\&.BrokenRulesProperty\fC [static]\fP"
\fBInitial value:\fP
.PP
.nf
= DependencyProperty\&.Register(
      "BrokenRules",
      typeof(ObservableCollection<BrokenRule>),
      typeof(PropertyInfo),
      null)
.fi
.PP
Gets the broken rules collection from the business object\&. 
.PP
Definition at line 100 of file PropertyInfo\&.cs\&.
.SS "readonly DependencyProperty Csla\&.Xaml\&.PropertyInfo\&.MyDataContextProperty\fC [static]\fP"
\fBInitial value:\fP
.PP
.nf
=
    DependencyProperty\&.Register("MyDataContext",
                                typeof(Object),
                                typeof(PropertyInfo),



                                new PropertyMetadata(MyDataContextPropertyChanged))
.fi
.PP
Used to monitor for changes in the binding path\&. 
.PP
Definition at line 127 of file PropertyInfo\&.cs\&.
.SS "readonly DependencyProperty Csla\&.Xaml\&.PropertyInfo\&.PropertyProperty\fC [static]\fP"
\fBInitial value:\fP
.PP
.nf
= DependencyProperty\&.Register(
      "Property",
      typeof(object),
      typeof(PropertyInfo),
      new PropertyMetadata(new object(), (o, e) =>
      {
        bool changed = true;
        if (e\&.NewValue == null)
        {
          if (e\&.OldValue == null)
            changed = false;
        }
        else if (e\&.NewValue\&.Equals(e\&.OldValue))
        {
          changed = false;
        }
        ((PropertyInfo)o)\&.SetSource(changed);
      }))
.fi
.PP
Gets or sets the source business property to which this control is bound\&. 
.PP
Definition at line 273 of file PropertyInfo\&.cs\&.
.SS "readonly DependencyProperty Csla\&.Xaml\&.PropertyInfo\&.RelativeBindingProperty\fC [static]\fP"
\fBInitial value:\fP
.PP
.nf
=
    DependencyProperty\&.Register("RelativeBinding",
                                typeof(Object),
                                typeof(PropertyInfo),



                                new PropertyMetadata(RelativeBindingPropertyChanged))
.fi
.PP
Used to monitor for changes in the binding path\&. 
.PP
Definition at line 153 of file PropertyInfo\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "string Csla\&.Xaml\&.PropertyInfo\&.BindingPath\fC [get]\fP, \fC [set]\fP, \fC [protected]\fP"

.PP
Gets or sets the binding path\&. The binding path\&.
.PP
Definition at line 183 of file PropertyInfo\&.cs\&.
.SS "ObservableCollection<\fBBrokenRule\fP> Csla\&.Xaml\&.PropertyInfo\&.BrokenRules\fC [get]\fP"

.PP
Gets the broken rules collection from the business object\&. 
.PP
Definition at line 111 of file PropertyInfo\&.cs\&.
.SS "bool Csla\&.Xaml\&.PropertyInfo\&.CanRead\fC [get]\fP, \fC [protected set]\fP"

.PP
Gets a value indicating whether the user is authorized to read the property\&. 
.PP
Definition at line 649 of file PropertyInfo\&.cs\&.
.SS "bool Csla\&.Xaml\&.PropertyInfo\&.CanWrite\fC [get]\fP, \fC [protected set]\fP"

.PP
Gets a value indicating whether the user is authorized to write the property\&. 
.PP
Definition at line 668 of file PropertyInfo\&.cs\&.
.SS "object Csla\&.Xaml\&.PropertyInfo\&.CustomTag\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets an arbitrary value associated with this \fBPropertyInfo\fP instance\&. 
.PP
Definition at line 765 of file PropertyInfo\&.cs\&.
.SS "string Csla\&.Xaml\&.PropertyInfo\&.ErrorText\fC [get]\fP"

.PP
Gets the validation error messages for a property on the Model 
.PP
\fBReturns\fP
.RS 4

.RE
.PP

.PP
Definition at line 574 of file PropertyInfo\&.cs\&.
.SS "string Csla\&.Xaml\&.PropertyInfo\&.InformationText\fC [get]\fP"

.PP
Gets the validation information messages for a property on the Model 
.PP
\fBReturns\fP
.RS 4

.RE
.PP

.PP
Definition at line 606 of file PropertyInfo\&.cs\&.
.SS "bool Csla\&.Xaml\&.PropertyInfo\&.IsBusy\fC [get]\fP"

.PP
Gets a value indicating whether the property is busy with an asynchronous operation\&. 
.PP
Definition at line 687 of file PropertyInfo\&.cs\&.
.SS "bool Csla\&.Xaml\&.PropertyInfo\&.IsValid\fC [get]\fP"

.PP
Gets a value indicating whether the property is valid\&. 
.PP
Definition at line 706 of file PropertyInfo\&.cs\&.
.SS "object Csla\&.Xaml\&.PropertyInfo\&.Property\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the source business property to which this control is bound\&. 
.PP
Definition at line 297 of file PropertyInfo\&.cs\&.
.SS "string Csla\&.Xaml\&.PropertyInfo\&.RuleDescription\fC [get]\fP"

.PP
Gets the description of the most severe broken rule for this property\&. 
.PP
Definition at line 746 of file PropertyInfo\&.cs\&.
.SS "\fBRuleSeverity\fP Csla\&.Xaml\&.PropertyInfo\&.RuleSeverity\fC [get]\fP"

.PP
Gets a value indicating the worst severity of all broken rules for this property (if IsValid is false)\&. 
.PP
Definition at line 727 of file PropertyInfo\&.cs\&.
.SS "object Csla\&.Xaml\&.PropertyInfo\&.Source\fC [get]\fP, \fC [set]\fP, \fC [protected]\fP"

.PP
Gets or sets the Source\&. The source\&.
.PP
Definition at line 177 of file PropertyInfo\&.cs\&.
.SS "object Csla\&.Xaml\&.PropertyInfo\&.Value\fC [get]\fP, \fC [set]\fP"

.PP
Gets and sets the value of the property on the business object\&. 
.PP
Definition at line 626 of file PropertyInfo\&.cs\&.
.SS "string Csla\&.Xaml\&.PropertyInfo\&.WarningText\fC [get]\fP"

.PP
Gets the validation warning messages for a property on the Model 
.PP
\fBReturns\fP
.RS 4

.RE
.PP

.PP
Definition at line 590 of file PropertyInfo\&.cs\&.
.SH "Event Documentation"
.PP 
.SS "PropertyChangedEventHandler Csla\&.Xaml\&.PropertyInfo\&.PropertyChanged"

.PP
Event raised when a property has changed\&. 
.PP
Definition at line 872 of file PropertyInfo\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
