.TH "Csla.CriteriaBase< T >" 3 "Thu Jul 22 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.CriteriaBase< T > \- Base type from which Criteria classes can be derived in a business class\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.Core\&.ManagedObjectBase\fP\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBCriteriaBase\fP ()"
.br
.RI "Initializes empty \fBCriteriaBase\fP\&. The type of business object to be created by the \fBDataPortal\fP MUST be supplied by the subclass\&. "
.in -1c
.SS "Static Protected Member Functions"

.in +1c
.ti -1c
.RI "static \fBPropertyInfo\fP< P > \fBRegisterProperty< P >\fP (\fBPropertyInfo\fP< P > info)"
.br
.RI "Indicates that the specified property belongs to the business object type\&. "
.ti -1c
.RI "static \fBPropertyInfo\fP< P > \fBRegisterProperty< P >\fP (string propertyName)"
.br
.RI "Indicates that the specified property belongs to the business object type\&. "
.ti -1c
.RI "static \fBPropertyInfo\fP< P > \fBRegisterProperty< P >\fP (Expression< Func< T, object >> propertyLambdaExpression)"
.br
.RI "Indicates that the specified property belongs to the business object type\&. "
.ti -1c
.RI "static \fBPropertyInfo\fP< P > \fBRegisterProperty< P >\fP (Expression< Func< T, object >> propertyLambdaExpression, P defaultValue)"
.br
.RI "Indicates that the specified property belongs to the business object type\&. "
.ti -1c
.RI "static \fBPropertyInfo\fP< P > \fBRegisterProperty< P >\fP (string propertyName, \fBRelationshipTypes\fP relationship)"
.br
.RI "Indicates that the specified property belongs to the business object type\&. "
.ti -1c
.RI "static \fBPropertyInfo\fP< P > \fBRegisterProperty< P >\fP (Expression< Func< T, object >> propertyLambdaExpression, \fBRelationshipTypes\fP relationship)"
.br
.RI "Indicates that the specified property belongs to the business object type\&. "
.ti -1c
.RI "static \fBPropertyInfo\fP< P > \fBRegisterProperty< P >\fP (string propertyName, string friendlyName)"
.br
.RI "Indicates that the specified property belongs to the business object type\&. "
.ti -1c
.RI "static \fBPropertyInfo\fP< P > \fBRegisterProperty< P >\fP (Expression< Func< T, object >> propertyLambdaExpression, string friendlyName)"
.br
.RI "Indicates that the specified property belongs to the business object type\&. "
.ti -1c
.RI "static \fBPropertyInfo\fP< P > \fBRegisterProperty< P >\fP (Expression< Func< T, object >> propertyLambdaExpression, string friendlyName, \fBRelationshipTypes\fP relationship)"
.br
.RI "Indicates that the specified property belongs to the business object type\&. "
.ti -1c
.RI "static \fBPropertyInfo\fP< P > \fBRegisterProperty< P >\fP (string propertyName, string friendlyName, P defaultValue)"
.br
.RI "Indicates that the specified property belongs to the business object type\&. "
.ti -1c
.RI "static \fBPropertyInfo\fP< P > \fBRegisterProperty< P >\fP (Expression< Func< T, object >> propertyLambdaExpression, string friendlyName, P defaultValue)"
.br
.RI "Indicates that the specified property belongs to the business object type\&. "
.ti -1c
.RI "static \fBPropertyInfo\fP< P > \fBRegisterProperty< P >\fP (string propertyName, string friendlyName, P defaultValue, \fBRelationshipTypes\fP relationship)"
.br
.RI "Indicates that the specified property belongs to the business object type\&. "
.ti -1c
.RI "static \fBPropertyInfo\fP< P > \fBRegisterProperty< P >\fP (Expression< Func< T, object >> propertyLambdaExpression, string friendlyName, P defaultValue, \fBRelationshipTypes\fP relationship)"
.br
.RI "Indicates that the specified property belongs to the business object type\&. "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Base type from which Criteria classes can be derived in a business class\&. 


.PP
\fBType Constraints\fP
.TP
\fIT\fP : \fI\fBCriteriaBase\fP<T>\fP
.PP
Definition at line 23 of file CriteriaBase\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBCsla\&.CriteriaBase\fP< T >\&.\fBCriteriaBase\fP ()\fC [protected]\fP"

.PP
Initializes empty \fBCriteriaBase\fP\&. The type of business object to be created by the \fBDataPortal\fP MUST be supplied by the subclass\&. 
.PP
Definition at line 31 of file CriteriaBase\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "static \fBPropertyInfo\fP<P> \fBCsla\&.CriteriaBase\fP< T >\&.RegisterProperty< P > (Expression< Func< T, object >> propertyLambdaExpression)\fC [static]\fP, \fC [protected]\fP"

.PP
Indicates that the specified property belongs to the business object type\&. 
.PP
\fBTemplate Parameters\fP
.RS 4
\fIP\fP Type of property
.RE
.PP
\fBParameters\fP
.RS 4
\fIpropertyLambdaExpression\fP Property Expression
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
Definition at line 73 of file CriteriaBase\&.cs\&.
.SS "static \fBPropertyInfo\fP<P> \fBCsla\&.CriteriaBase\fP< T >\&.RegisterProperty< P > (Expression< Func< T, object >> propertyLambdaExpression, P defaultValue)\fC [static]\fP, \fC [protected]\fP"

.PP
Indicates that the specified property belongs to the business object type\&. 
.PP
\fBTemplate Parameters\fP
.RS 4
\fIP\fP Type of property
.RE
.PP
\fBParameters\fP
.RS 4
\fIpropertyLambdaExpression\fP Property Expression
.br
\fIdefaultValue\fP Default Value for the property
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
Definition at line 88 of file CriteriaBase\&.cs\&.
.SS "static \fBPropertyInfo\fP<P> \fBCsla\&.CriteriaBase\fP< T >\&.RegisterProperty< P > (Expression< Func< T, object >> propertyLambdaExpression, \fBRelationshipTypes\fP relationship)\fC [static]\fP, \fC [protected]\fP"

.PP
Indicates that the specified property belongs to the business object type\&. 
.PP
\fBTemplate Parameters\fP
.RS 4
\fIP\fP Type of property
.RE
.PP
\fBParameters\fP
.RS 4
\fIpropertyLambdaExpression\fP Property Expression
.br
\fIrelationship\fP Relationship with referenced object\&.
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
Definition at line 118 of file CriteriaBase\&.cs\&.
.SS "static \fBPropertyInfo\fP<P> \fBCsla\&.CriteriaBase\fP< T >\&.RegisterProperty< P > (Expression< Func< T, object >> propertyLambdaExpression, string friendlyName)\fC [static]\fP, \fC [protected]\fP"

.PP
Indicates that the specified property belongs to the business object type\&. 
.PP
\fBTemplate Parameters\fP
.RS 4
\fIP\fP Type of property
.RE
.PP
\fBParameters\fP
.RS 4
\fIpropertyLambdaExpression\fP Property Expression
.br
\fIfriendlyName\fP Friendly description for a property to be used in databinding
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
Definition at line 145 of file CriteriaBase\&.cs\&.
.SS "static \fBPropertyInfo\fP<P> \fBCsla\&.CriteriaBase\fP< T >\&.RegisterProperty< P > (Expression< Func< T, object >> propertyLambdaExpression, string friendlyName, P defaultValue)\fC [static]\fP, \fC [protected]\fP"

.PP
Indicates that the specified property belongs to the business object type\&. 
.PP
\fBTemplate Parameters\fP
.RS 4
\fIP\fP Type of property
.RE
.PP
\fBParameters\fP
.RS 4
\fIpropertyLambdaExpression\fP Property Expression
.br
\fIfriendlyName\fP Friendly description for a property to be used in databinding
.br
\fIdefaultValue\fP Default Value for the property
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
Definition at line 192 of file CriteriaBase\&.cs\&.
.SS "static \fBPropertyInfo\fP<P> \fBCsla\&.CriteriaBase\fP< T >\&.RegisterProperty< P > (Expression< Func< T, object >> propertyLambdaExpression, string friendlyName, P defaultValue, \fBRelationshipTypes\fP relationship)\fC [static]\fP, \fC [protected]\fP"

.PP
Indicates that the specified property belongs to the business object type\&. 
.PP
\fBTemplate Parameters\fP
.RS 4
\fIP\fP Type of property
.RE
.PP
\fBParameters\fP
.RS 4
\fIpropertyLambdaExpression\fP Property Expression
.br
\fIfriendlyName\fP Friendly description for a property to be used in databinding
.br
\fIdefaultValue\fP Default Value for the property
.br
\fIrelationship\fP Relationship with referenced object\&.
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
Definition at line 225 of file CriteriaBase\&.cs\&.
.SS "static \fBPropertyInfo\fP<P> \fBCsla\&.CriteriaBase\fP< T >\&.RegisterProperty< P > (Expression< Func< T, object >> propertyLambdaExpression, string friendlyName, \fBRelationshipTypes\fP relationship)\fC [static]\fP, \fC [protected]\fP"

.PP
Indicates that the specified property belongs to the business object type\&. 
.PP
\fBTemplate Parameters\fP
.RS 4
\fIP\fP Type of property
.RE
.PP
\fBParameters\fP
.RS 4
\fIpropertyLambdaExpression\fP Property Expression
.br
\fIfriendlyName\fP Friendly description for a property to be used in databinding
.br
\fIrelationship\fP Relationship with referenced object\&.
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
Definition at line 162 of file CriteriaBase\&.cs\&.
.SS "static \fBPropertyInfo\fP<P> \fBCsla\&.CriteriaBase\fP< T >\&.RegisterProperty< P > (\fBPropertyInfo\fP< P > info)\fC [static]\fP, \fC [protected]\fP"

.PP
Indicates that the specified property belongs to the business object type\&. 
.PP
\fBTemplate Parameters\fP
.RS 4
\fIP\fP Type of property\&. 
.RE
.PP
\fBParameters\fP
.RS 4
\fIinfo\fP \fBPropertyInfo\fP object for the property\&. 
.RE
.PP
\fBReturns\fP
.RS 4
The provided IPropertyInfo object\&. 
.RE
.PP

.PP
Definition at line 49 of file CriteriaBase\&.cs\&.
.SS "static \fBPropertyInfo\fP<P> \fBCsla\&.CriteriaBase\fP< T >\&.RegisterProperty< P > (string propertyName)\fC [static]\fP, \fC [protected]\fP"

.PP
Indicates that the specified property belongs to the business object type\&. 
.PP
\fBTemplate Parameters\fP
.RS 4
\fIP\fP Type of property
.RE
.PP
\fBParameters\fP
.RS 4
\fIpropertyName\fP Property name from nameof()
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
Definition at line 61 of file CriteriaBase\&.cs\&.
.SS "static \fBPropertyInfo\fP<P> \fBCsla\&.CriteriaBase\fP< T >\&.RegisterProperty< P > (string propertyName, \fBRelationshipTypes\fP relationship)\fC [static]\fP, \fC [protected]\fP"

.PP
Indicates that the specified property belongs to the business object type\&. 
.PP
\fBTemplate Parameters\fP
.RS 4
\fIP\fP Type of property
.RE
.PP
\fBParameters\fP
.RS 4
\fIpropertyName\fP Property name from nameof()
.br
\fIrelationship\fP Relationship with referenced object\&.
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
Definition at line 104 of file CriteriaBase\&.cs\&.
.SS "static \fBPropertyInfo\fP<P> \fBCsla\&.CriteriaBase\fP< T >\&.RegisterProperty< P > (string propertyName, string friendlyName)\fC [static]\fP, \fC [protected]\fP"

.PP
Indicates that the specified property belongs to the business object type\&. 
.PP
\fBTemplate Parameters\fP
.RS 4
\fIP\fP Type of property
.RE
.PP
\fBParameters\fP
.RS 4
\fIpropertyName\fP Property name from nameof()
.br
\fIfriendlyName\fP Friendly description for a property to be used in databinding
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
Definition at line 132 of file CriteriaBase\&.cs\&.
.SS "static \fBPropertyInfo\fP<P> \fBCsla\&.CriteriaBase\fP< T >\&.RegisterProperty< P > (string propertyName, string friendlyName, P defaultValue)\fC [static]\fP, \fC [protected]\fP"

.PP
Indicates that the specified property belongs to the business object type\&. 
.PP
\fBTemplate Parameters\fP
.RS 4
\fIP\fP Type of property
.RE
.PP
\fBParameters\fP
.RS 4
\fIpropertyName\fP Property name from nameof()
.br
\fIfriendlyName\fP Friendly description for a property to be used in databinding
.br
\fIdefaultValue\fP Default Value for the property
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
Definition at line 178 of file CriteriaBase\&.cs\&.
.SS "static \fBPropertyInfo\fP<P> \fBCsla\&.CriteriaBase\fP< T >\&.RegisterProperty< P > (string propertyName, string friendlyName, P defaultValue, \fBRelationshipTypes\fP relationship)\fC [static]\fP, \fC [protected]\fP"

.PP
Indicates that the specified property belongs to the business object type\&. 
.PP
\fBTemplate Parameters\fP
.RS 4
\fIP\fP Type of property
.RE
.PP
\fBParameters\fP
.RS 4
\fIpropertyName\fP Property name from nameof()
.br
\fIfriendlyName\fP Friendly description for a property to be used in databinding
.br
\fIdefaultValue\fP Default Value for the property
.br
\fIrelationship\fP Relationship with referenced object\&.
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
Definition at line 209 of file CriteriaBase\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
