.TH "Csla.Test.Authorization" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.Authorization
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAuthRuleExpectsCriteria\fP"
.br
.ti -1c
.RI "class \fBAuthTests\fP"
.br
.ti -1c
.RI "class \fBPerTypeAuthDPActivator\fP"
.br
.ti -1c
.RI "interface \fBIPerTypeAuthRoot\fP"
.br
.ti -1c
.RI "class \fBPerTypeAuthRoot\fP"
.br
.ti -1c
.RI "class \fBRootList\fP"
.br
.ti -1c
.RI "class \fBChildItem\fP"
.br
.ti -1c
.RI "class \fBPermissionRootWithCriteria\fP"
.br
.ti -1c
.RI "class \fBPerTypeAuthorization\fP"
.br
.ti -1c
.RI "class \fBPerTypeAuthorizationTests\fP"
.br
.ti -1c
.RI "class \fBReadonlyAuthorizationTests\fP"
.br
.ti -1c
.RI "class \fBReadOnlyPerson\fP"
.br
.ti -1c
.RI "class \fBRootException\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
