.TH "Csla.Test.ValidationRules.DirtyAfterOutValueChangesProperty" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.ValidationRules.DirtyAfterOutValueChangesProperty
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.BusinessBase< DirtyAfterOutValueChangesProperty >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDirtyAfterOutValueChangesProperty\fP ()"
.br
.ti -1c
.RI "\fBDirtyAfterOutValueChangesProperty\fP (string value)"
.br
.ti -1c
.RI "void \fBCheckRules\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBPropertyInfo\fP< string > \fBValue1Property\fP = RegisterProperty<string>(c => c\&.Value1)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBAddBusinessRules\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBValue1\fP\fC [get, set]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 729 of file ValidationTests\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Csla\&.Test\&.ValidationRules\&.DirtyAfterOutValueChangesProperty\&.DirtyAfterOutValueChangesProperty ()"

.PP
Definition at line 738 of file ValidationTests\&.cs\&.
.SS "Csla\&.Test\&.ValidationRules\&.DirtyAfterOutValueChangesProperty\&.DirtyAfterOutValueChangesProperty (string value)"

.PP
Definition at line 741 of file ValidationTests\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override void Csla\&.Test\&.ValidationRules\&.DirtyAfterOutValueChangesProperty\&.AddBusinessRules ()\fC [protected]\fP"

.PP
Definition at line 751 of file ValidationTests\&.cs\&.
.SS "void Csla\&.Test\&.ValidationRules\&.DirtyAfterOutValueChangesProperty\&.CheckRules ()"

.PP
Definition at line 773 of file ValidationTests\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBPropertyInfo\fP<string> Csla\&.Test\&.ValidationRules\&.DirtyAfterOutValueChangesProperty\&.Value1Property = RegisterProperty<string>(c => c\&.Value1)\fC [static]\fP"

.PP
Definition at line 731 of file ValidationTests\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "string Csla\&.Test\&.ValidationRules\&.DirtyAfterOutValueChangesProperty\&.Value1\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 732 of file ValidationTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
