.TH "cslalighttest.ReadOnly.MockReadOnlyList" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cslalighttest.ReadOnly.MockReadOnlyList
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.ReadOnlyBindingListBase< MockReadOnlyList, MockReadOnly >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMockReadOnlyList\fP ()"
.br
.ti -1c
.RI "\fBMockReadOnlyList\fP (\fBMockReadOnly\fP mock)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 26 of file ReadOnly/MockReadOnlyList\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "cslalighttest\&.ReadOnly\&.MockReadOnlyList\&.MockReadOnlyList ()"

.PP
Definition at line 28 of file ReadOnly/MockReadOnlyList\&.cs\&.
.SS "cslalighttest\&.ReadOnly\&.MockReadOnlyList\&.MockReadOnlyList (\fBMockReadOnly\fP mock)"

.PP
Definition at line 30 of file ReadOnly/MockReadOnlyList\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
