.TH "Csla.Test.MethodCaller.Caller1" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.MethodCaller.Caller1
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBCsla\&.Test\&.MethodCaller\&.Caller2\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual int \fBMethod1\fP ()"
.br
.ti -1c
.RI "virtual int \fBMethod2\fP (int something)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 15 of file Caller1\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual int Csla\&.Test\&.MethodCaller\&.Caller1\&.Method1 ()\fC [virtual]\fP"

.PP
Reimplemented in \fBCsla\&.Test\&.MethodCaller\&.Caller2\fP\&.
.PP
Definition at line 17 of file Caller1\&.cs\&.
.SS "virtual int Csla\&.Test\&.MethodCaller\&.Caller1\&.Method2 (int something)\fC [virtual]\fP"

.PP
Reimplemented in \fBCsla\&.Test\&.MethodCaller\&.Caller2\fP\&.
.PP
Definition at line 22 of file Caller1\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
