.TH "Csla.Test.ValidationRules.ChildList" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.ValidationRules.ChildList
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.BusinessBindingListBase< ChildList, Child >\fP\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBChildList\fP \fBNewList\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 19 of file ChildList\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "static \fBChildList\fP Csla\&.Test\&.ValidationRules\&.ChildList\&.NewList ()\fC [static]\fP"

.PP
Definition at line 21 of file ChildList\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
