.TH "Csla.Threading.BackgroundWorker" 3 "Thu Jul 22 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Threading.BackgroundWorker \- A \fBBackgroundWorker\fP that wraps a System\&.ComponentModel\&.BackgroundWorkertransfers ApplicationContext\&.User, ClientContext, GlobalContext, CurrentCulture and CurrentUICulture to the background thread\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits System\&.ComponentModel\&.Component\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBackgroundWorker\fP ()"
.br
.RI "Initializes a new instance of the \fBBackgroundWorker\fP class\&. "
.ti -1c
.RI "void \fBCancelAsync\fP ()"
.br
.RI "Request cancelation of async operation\&. "
.ti -1c
.RI "void \fBRunWorkerAsync\fP ()"
.br
.RI "Starts execution of a background operation\&. "
.ti -1c
.RI "void \fBRunWorkerAsync\fP (object argument)"
.br
.RI "Starts execution of a background operation\&. "
.ti -1c
.RI "void \fBReportProgress\fP (int percentProgress)"
.br
.RI "Calls report progress on the underlying background worker\&. "
.ti -1c
.RI "void \fBReportProgress\fP (int percentProgress, object userState)"
.br
.RI "Calls report progress on the background worker\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "DoWorkEventHandler \fBDoWork\fP"
.br
.RI "Occurs when M:System\&.ComponentModel\&.BackgroundWorker\&.RunWorkerAsync is called\&. "
.ti -1c
.RI "RunWorkerCompletedEventHandler \fBRunWorkerCompleted\fP"
.br
.RI "Occurs when the background operation has completed, has been canceled, or has raised an exception\&. "
.ti -1c
.RI "ProgressChangedEventHandler \fBProgressChanged\fP"
.br
.RI "Occurs when M:System\&.ComponentModel\&.BackgroundWorker\&.ReportProgress is called\&. "
.ti -1c
.RI "bool \fBIsBusy\fP\fC [get]\fP"
.br
.RI "Gets a value indicating whether the T:System\&.ComponentModel\&.BackgroundWorker is running an asynchronous operation\&. "
.ti -1c
.RI "bool \fBWorkerReportsProgress\fP\fC [get, set]\fP"
.br
.RI "Gets or sets a value indicating whether the T:System\&.ComponentModel\&.BackgroundWorker can report progress updates\&. "
.ti -1c
.RI "bool \fBWorkerSupportsCancellation\fP\fC [get, set]\fP"
.br
.RI "Gets or sets a value indicating whether the T:System\&.ComponentModel\&.BackgroundWorker supports asynchronous cancellation\&. "
.ti -1c
.RI "bool \fBCancellationPending\fP\fC [get]\fP"
.br
.RI "Gets a value indicating whether the application has requested cancellation of a background operation\&. "
.ti -1c
.RI "\fBCsla\&.Core\&.ContextDictionary\fP \fBGlobalContext\fP\fC [get]\fP"
.br
.RI "Gets a reference to the global context returned from the background thread and/or server\&. "
.in -1c
.SH "Detailed Description"
.PP 
A \fBBackgroundWorker\fP that wraps a System\&.ComponentModel\&.BackgroundWorkertransfers ApplicationContext\&.User, ClientContext, GlobalContext, CurrentCulture and CurrentUICulture to the background thread\&. 


.PP
Definition at line 19 of file BackgroundWorker\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Csla\&.Threading\&.BackgroundWorker\&.BackgroundWorker ()"

.PP
Initializes a new instance of the \fBBackgroundWorker\fP class\&. 
.PP
Definition at line 25 of file BackgroundWorker\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Csla\&.Threading\&.BackgroundWorker\&.CancelAsync ()"

.PP
Request cancelation of async operation\&. 
.PP
\fBExceptions\fP
.RS 4
\fIT:System\&.InvalidOperationException\fP P:System\&.ComponentModel\&.BackgroundWorker\&.WorkerSupportsCancellation is false\&. 
.RE
.PP
<PermissionSet> <IPermission class='System\&.Security\&.Permissions\&.SecurityPermission, mscorlib, Version=2\&.0\&.3600\&.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' version='1' Flags='UnmanagedCode, ControlEvidence'> </PermissionSet> 
.PP
Definition at line 145 of file BackgroundWorker\&.cs\&.
.SS "void Csla\&.Threading\&.BackgroundWorker\&.ReportProgress (int percentProgress)"

.PP
Calls report progress on the underlying background worker\&. 
.PP
\fBParameters\fP
.RS 4
\fIpercentProgress\fP The percentage, from 0 to 100, of the background operation that is complete\&.
.RE
.PP

.PP
Definition at line 329 of file BackgroundWorker\&.cs\&.
.SS "void Csla\&.Threading\&.BackgroundWorker\&.ReportProgress (int percentProgress, object userState)"

.PP
Calls report progress on the background worker\&. 
.PP
\fBParameters\fP
.RS 4
\fIpercentProgress\fP The percent progress\&.
.br
\fIuserState\fP User state object\&.
.RE
.PP

.PP
Definition at line 339 of file BackgroundWorker\&.cs\&.
.SS "void Csla\&.Threading\&.BackgroundWorker\&.RunWorkerAsync ()"

.PP
Starts execution of a background operation\&. 
.PP
\fBExceptions\fP
.RS 4
\fIT:System\&.InvalidOperationException\fP P:System\&.ComponentModel\&.BackgroundWorker\&.IsBusy is true\&. 
.RE
.PP
<PermissionSet> <IPermission class='System\&.Security\&.Permissions\&.SecurityPermission, mscorlib, Version=2\&.0\&.3600\&.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' version='1' Flags='UnmanagedCode, ControlEvidence'> </PermissionSet> 
.PP
Definition at line 215 of file BackgroundWorker\&.cs\&.
.SS "void Csla\&.Threading\&.BackgroundWorker\&.RunWorkerAsync (object argument)"

.PP
Starts execution of a background operation\&. 
.PP
\fBParameters\fP
.RS 4
\fIargument\fP A parameter for use by the background operation to be executed in the E:System\&.ComponentModel\&.BackgroundWorker\&.DoWork event handler\&.
.RE
.PP
\fBExceptions\fP
.RS 4
\fIT:System\&.InvalidOperationException\fP P:System\&.ComponentModel\&.BackgroundWorker\&.IsBusy is true\&. 
.RE
.PP

.PP
Definition at line 227 of file BackgroundWorker\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "bool Csla\&.Threading\&.BackgroundWorker\&.CancellationPending\fC [get]\fP"

.PP
Gets a value indicating whether the application has requested cancellation of a background operation\&. 
.PP
\fBReturns\fP
.RS 4
true if the application has requested cancellation of a background operation; otherwise, false\&. The default is false\&. 
.RE
.PP

.PP
Definition at line 156 of file BackgroundWorker\&.cs\&.
.SS "DoWorkEventHandler Csla\&.Threading\&.BackgroundWorker\&.DoWork\fC [add]\fP, \fC [remove]\fP"

.PP
Occurs when M:System\&.ComponentModel\&.BackgroundWorker\&.RunWorkerAsync is called\&. 
.PP
Definition at line 41 of file BackgroundWorker\&.cs\&.
.SS "\fBCsla\&.Core\&.ContextDictionary\fP Csla\&.Threading\&.BackgroundWorker\&.GlobalContext\fC [get]\fP"

.PP
Gets a reference to the global context returned from the background thread and/or server\&. 
.PP
Definition at line 200 of file BackgroundWorker\&.cs\&.
.SS "bool Csla\&.Threading\&.BackgroundWorker\&.IsBusy\fC [get]\fP"

.PP
Gets a value indicating whether the T:System\&.ComponentModel\&.BackgroundWorker is running an asynchronous operation\&. 
.PP
\fBReturns\fP
.RS 4
true, if the T:System\&.ComponentModel\&.BackgroundWorker is running an asynchronous operation; otherwise, false\&. 
.RE
.PP

.PP
Definition at line 92 of file BackgroundWorker\&.cs\&.
.SS "ProgressChangedEventHandler Csla\&.Threading\&.BackgroundWorker\&.ProgressChanged\fC [add]\fP, \fC [remove]\fP"

.PP
Occurs when M:System\&.ComponentModel\&.BackgroundWorker\&.ReportProgress is called\&. 
.PP
Definition at line 74 of file BackgroundWorker\&.cs\&.
.SS "RunWorkerCompletedEventHandler Csla\&.Threading\&.BackgroundWorker\&.RunWorkerCompleted\fC [add]\fP, \fC [remove]\fP"

.PP
Occurs when the background operation has completed, has been canceled, or has raised an exception\&. 
.PP
Definition at line 57 of file BackgroundWorker\&.cs\&.
.SS "bool Csla\&.Threading\&.BackgroundWorker\&.WorkerReportsProgress\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets a value indicating whether the T:System\&.ComponentModel\&.BackgroundWorker can report progress updates\&. 
.PP
\fBReturns\fP
.RS 4
true if the T:System\&.ComponentModel\&.BackgroundWorker supports progress updates; otherwise false\&. The default is false\&. 
.RE
.PP

.PP
Definition at line 106 of file BackgroundWorker\&.cs\&.
.SS "bool Csla\&.Threading\&.BackgroundWorker\&.WorkerSupportsCancellation\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets a value indicating whether the T:System\&.ComponentModel\&.BackgroundWorker supports asynchronous cancellation\&. 
.PP
\fBReturns\fP
.RS 4
true if the T:System\&.ComponentModel\&.BackgroundWorker supports cancellation; otherwise false\&. The default is false\&. 
.RE
.PP

.PP
Definition at line 124 of file BackgroundWorker\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
