.TH "Csla.Test.LazyLoad.AChildList" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.LazyLoad.AChildList
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.BusinessBindingListBase< AChildList, AChild >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAChildList\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "new int \fBEditLevel\fP\fC [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 15 of file AChildList\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Csla\&.Test\&.LazyLoad\&.AChildList\&.AChildList ()"

.PP
Definition at line 17 of file AChildList\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "new int Csla\&.Test\&.LazyLoad\&.AChildList\&.EditLevel\fC [get]\fP"

.PP
Definition at line 23 of file AChildList\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
