.TH "Csla.Test.ChildrenByInterface.IItem" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.ChildrenByInterface.IItem
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.Core\&.IEditableBusinessObject\fP\&.
.PP
Inherited by \fBCsla\&.Test\&.ChildrenByInterface\&.Item1\fP, and \fBCsla\&.Test\&.ChildrenByInterface\&.Item2\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 40 of file ChildInterfaceTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
