.TH "Csla.Test.DataMapper" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.DataMapper
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDataMapperTests\fP"
.br
.ti -1c
.RI "class \fBManagedTarget\fP"
.br
.ti -1c
.RI "class \fBDataMapTarget\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum class \fBDataMapEnum\fP { \fBFirst\fP, \fBSecond\fP, \fBThird\fP }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBCsla\&.Test\&.DataMapper\&.DataMapEnum\fP\fC [strong]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIFirst \fP\fP
.TP
\fB\fISecond \fP\fP
.TP
\fB\fIThird \fP\fP
.PP
Definition at line 231 of file DataMapperTests\&.cs\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
