.TH "Csla.Test.DataMapper.DataMapperTests" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.DataMapper.DataMapperTests
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBDictionaryMap\fP ()"
.br
.ti -1c
.RI "void \fBNumericTypes\fP ()"
.br
.ti -1c
.RI "void \fBBooleanTypes\fP ()"
.br
.ti -1c
.RI "void \fBGuidTypes\fP ()"
.br
.ti -1c
.RI "void \fBNullableTypes\fP ()"
.br
.ti -1c
.RI "void \fBEnumTypes\fP ()"
.br
.ti -1c
.RI "void \fBDateTimeTypes\fP ()"
.br
.ti -1c
.RI "void \fBSmartDateTypes\fP ()"
.br
.ti -1c
.RI "void \fBSetFields\fP ()"
.br
.ti -1c
.RI "void \fBBasicDataMap\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 26 of file DataMapperTests\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Csla\&.Test\&.DataMapper\&.DataMapperTests\&.BasicDataMap ()"

.PP
Definition at line 195 of file DataMapperTests\&.cs\&.
.SS "void Csla\&.Test\&.DataMapper\&.DataMapperTests\&.BooleanTypes ()"

.PP
Definition at line 62 of file DataMapperTests\&.cs\&.
.SS "void Csla\&.Test\&.DataMapper\&.DataMapperTests\&.DateTimeTypes ()"

.PP
Definition at line 130 of file DataMapperTests\&.cs\&.
.SS "void Csla\&.Test\&.DataMapper\&.DataMapperTests\&.DictionaryMap ()"

.PP
Definition at line 29 of file DataMapperTests\&.cs\&.
.SS "void Csla\&.Test\&.DataMapper\&.DataMapperTests\&.EnumTypes ()"

.PP
Definition at line 115 of file DataMapperTests\&.cs\&.
.SS "void Csla\&.Test\&.DataMapper\&.DataMapperTests\&.GuidTypes ()"

.PP
Definition at line 80 of file DataMapperTests\&.cs\&.
.SS "void Csla\&.Test\&.DataMapper\&.DataMapperTests\&.NullableTypes ()"

.PP
Definition at line 97 of file DataMapperTests\&.cs\&.
.SS "void Csla\&.Test\&.DataMapper\&.DataMapperTests\&.NumericTypes ()"

.PP
Definition at line 41 of file DataMapperTests\&.cs\&.
.SS "void Csla\&.Test\&.DataMapper\&.DataMapperTests\&.SetFields ()"

.PP
Definition at line 168 of file DataMapperTests\&.cs\&.
.SS "void Csla\&.Test\&.DataMapper\&.DataMapperTests\&.SmartDateTypes ()"

.PP
Definition at line 145 of file DataMapperTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
