.TH "Csla.Server.DataPortalResult" 3 "Thu Jul 22 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Server.DataPortalResult \- Returns data from the server-side \fBDataPortal\fP to the client-side \fBDataPortal\fP\&. Intended for internal CSLA \&.NET use only\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits EventArgs\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDataPortalResult\fP ()"
.br
.RI "Creates an instance of the object\&. "
.ti -1c
.RI "\fBDataPortalResult\fP (object returnObject)"
.br
.RI "Creates an instance of the object\&. "
.ti -1c
.RI "\fBDataPortalResult\fP (object returnObject, \fBContextDictionary\fP globalContext)"
.br
.RI "Creates an instance of the object\&. "
.ti -1c
.RI "\fBDataPortalResult\fP (object returnObject, Exception ex, \fBContextDictionary\fP globalContext)"
.br
.RI "Creates an instance of the object\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "object \fBReturnObject\fP\fC [get]\fP"
.br
.RI "The business object being returned from the server\&. "
.ti -1c
.RI "Exception \fBError\fP\fC [get]\fP"
.br
.RI "Error that occurred during the DataPotal call\&. This will be null if no errors occurred\&. "
.ti -1c
.RI "\fBContextDictionary\fP \fBGlobalContext\fP\fC [get]\fP"
.br
.RI "The global context being returned from the server\&. "
.in -1c
.SH "Detailed Description"
.PP 
Returns data from the server-side \fBDataPortal\fP to the client-side \fBDataPortal\fP\&. Intended for internal CSLA \&.NET use only\&. 


.PP
Definition at line 20 of file Server/DataPortalResult\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Csla\&.Server\&.DataPortalResult\&.DataPortalResult ()"

.PP
Creates an instance of the object\&. 
.PP
Definition at line 43 of file Server/DataPortalResult\&.cs\&.
.SS "Csla\&.Server\&.DataPortalResult\&.DataPortalResult (object returnObject)"

.PP
Creates an instance of the object\&. 
.PP
\fBParameters\fP
.RS 4
\fIreturnObject\fP Object to return as part of the result\&.
.RE
.PP

.PP
Definition at line 53 of file Server/DataPortalResult\&.cs\&.
.SS "Csla\&.Server\&.DataPortalResult\&.DataPortalResult (object returnObject, \fBContextDictionary\fP globalContext)"

.PP
Creates an instance of the object\&. 
.PP
\fBParameters\fP
.RS 4
\fIreturnObject\fP Object to return as part of the result\&.
.br
\fIglobalContext\fP Global context delivered via current reuest from the server 
.RE
.PP

.PP
Definition at line 66 of file Server/DataPortalResult\&.cs\&.
.SS "Csla\&.Server\&.DataPortalResult\&.DataPortalResult (object returnObject, Exception ex, \fBContextDictionary\fP globalContext)"

.PP
Creates an instance of the object\&. 
.PP
\fBParameters\fP
.RS 4
\fIreturnObject\fP Object to return as part of the result\&.
.br
\fIex\fP Error that occurred during the DataPotal call\&. This will be null if no errors occurred\&. 
.br
\fIglobalContext\fP Global context delivered via current reuest from the server 
.RE
.PP

.PP
Definition at line 83 of file Server/DataPortalResult\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "Exception Csla\&.Server\&.DataPortalResult\&.Error\fC [get]\fP"

.PP
Error that occurred during the DataPotal call\&. This will be null if no errors occurred\&. 
.PP
Definition at line 32 of file Server/DataPortalResult\&.cs\&.
.SS "\fBContextDictionary\fP Csla\&.Server\&.DataPortalResult\&.GlobalContext\fC [get]\fP"

.PP
The global context being returned from the server\&. 
.PP
Definition at line 38 of file Server/DataPortalResult\&.cs\&.
.SS "object Csla\&.Server\&.DataPortalResult\&.ReturnObject\fC [get]\fP"

.PP
The business object being returned from the server\&. 
.PP
Definition at line 26 of file Server/DataPortalResult\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
