.TH "Csla.Test.BypassPropertyChecks.TestObjectFactory" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.BypassPropertyChecks.TestObjectFactory
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.Server\&.ObjectFactory\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTestObjectFactory\fP ()"
.br
.ti -1c
.RI "\fBBypassBusinessBaseUsingFactory\fP \fBFetch\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 15 of file TestObjectFactory\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Csla\&.Test\&.BypassPropertyChecks\&.TestObjectFactory\&.TestObjectFactory ()"

.PP
Definition at line 17 of file TestObjectFactory\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBBypassBusinessBaseUsingFactory\fP Csla\&.Test\&.BypassPropertyChecks\&.TestObjectFactory\&.Fetch ()"

.PP
Definition at line 19 of file TestObjectFactory\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
