.TH "Csla.Test.Data" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.Data
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBContextTests\fP"
.br
.ti -1c
.RI "class \fBDataPortalTestDatabaseEntities\fP"
.br
.RI "No Metadata Documentation available\&. "
.ti -1c
.RI "class \fBTable2\fP"
.br
.RI "No Metadata Documentation available\&. "
.ti -1c
.RI "class \fBTestLinqToSqlContextDataContext\fP"
.br
.ti -1c
.RI "class \fBTable1\fP"
.br
.ti -1c
.RI "class \fBTransactionContextUser\fP"
.br
.ti -1c
.RI "class \fBTransactionContextUserList\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
