.TH "Csla.AspNetCore.Mvc.TagHelpers" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.AspNetCore.Mvc.TagHelpers
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCslaErrorsTagHelper\fP"
.br
.RI "Razor tag helper that displays CSLA \&.NET validation error text in a span\&. "
.ti -1c
.RI "class \fBCslaInformationTagHelper\fP"
.br
.RI "Razor tag helper that displays CSLA \&.NET information text in a span\&. "
.ti -1c
.RI "class \fBCslaWarningsTagHelper\fP"
.br
.RI "Razor tag helper that displays CSLA \&.NET validation warning text in a span\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
