.TH "cslalighttest.Serialization" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cslalighttest.Serialization
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAddress\fP"
.br
.ti -1c
.RI "class \fBAddressBase\fP"
.br
.ti -1c
.RI "class \fBAddressList\fP"
.br
.ti -1c
.RI "class \fBBindingListTests\fP"
.br
.ti -1c
.RI "class \fBCustomer\fP"
.br
.RI "Implementation of a test business object using CSLA managed properties backed by fields, and custom serialization logic (requirement of backing managed properties with fields)\&. "
.ti -1c
.RI "class \fBCustomerContact\fP"
.br
.RI "Implementation of a test business object using CSLA managed properties backed by fields, and custom serialization logic (requirement of backing managed properties with fields)\&. "
.ti -1c
.RI "class \fBCustomerWithEnum\fP"
.br
.RI "Implementation of a test business object with an enum\&. "
.ti -1c
.RI "class \fBCustomMobileList\fP"
.br
.ti -1c
.RI "class \fBMockMobileList\fP"
.br
.ti -1c
.RI "class \fBMockNonBusinessObject\fP"
.br
.ti -1c
.RI "class \fBMockNonBusinessObject2\fP"
.br
.ti -1c
.RI "class \fBMockReadOnly\fP"
.br
.ti -1c
.RI "class \fBMockReadOnlyList\fP"
.br
.ti -1c
.RI "class \fBPerson\fP"
.br
.ti -1c
.RI "class \fBPersonWIthSmartDateField\fP"
.br
.ti -1c
.RI "class \fBReadOnlyPerson\fP"
.br
.ti -1c
.RI "class \fBReadOnlyPersonList\fP"
.br
.ti -1c
.RI "class \fBSerializationTests\fP"
.br
.ti -1c
.RI "class \fBUndoTests\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum class \fBCustomerQuality\fP { \fBNone\fP = 0, \fBGood\fP = 1, \fBBad\fP = 2 }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBcslalighttest\&.Serialization\&.CustomerQuality\fP\fC [strong]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fINone \fP\fP
.TP
\fB\fIGood \fP\fP
.TP
\fB\fIBad \fP\fP
.PP
Definition at line 17 of file CustomerWithEnum\&.cs\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
