.TH "Csla.Test.IO.DPMethodOverloadTests" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.IO.DPMethodOverloadTests
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBCreateNoCriteria\fP ()"
.br
.ti -1c
.RI "void \fBCreateWithCriteria\fP ()"
.br
.ti -1c
.RI "void \fBCreateWithOtherCriteria\fP ()"
.br
.ti -1c
.RI "void \fBFetchNullCriteria\fP ()"
.br
.ti -1c
.RI "void \fBFetchNoCriteria\fP ()"
.br
.ti -1c
.RI "void \fBFetchWithCriteria\fP ()"
.br
.ti -1c
.RI "void \fBFetchWithOtherCriteria\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 26 of file DPMethodOverloadTests\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Csla\&.Test\&.IO\&.DPMethodOverloadTests\&.CreateNoCriteria ()"

.PP
Definition at line 30 of file DPMethodOverloadTests\&.cs\&.
.SS "void Csla\&.Test\&.IO\&.DPMethodOverloadTests\&.CreateWithCriteria ()"

.PP
Definition at line 43 of file DPMethodOverloadTests\&.cs\&.
.SS "void Csla\&.Test\&.IO\&.DPMethodOverloadTests\&.CreateWithOtherCriteria ()"

.PP
Definition at line 56 of file DPMethodOverloadTests\&.cs\&.
.SS "void Csla\&.Test\&.IO\&.DPMethodOverloadTests\&.FetchNoCriteria ()"

.PP
Definition at line 82 of file DPMethodOverloadTests\&.cs\&.
.SS "void Csla\&.Test\&.IO\&.DPMethodOverloadTests\&.FetchNullCriteria ()"

.PP
Definition at line 69 of file DPMethodOverloadTests\&.cs\&.
.SS "void Csla\&.Test\&.IO\&.DPMethodOverloadTests\&.FetchWithCriteria ()"

.PP
Definition at line 95 of file DPMethodOverloadTests\&.cs\&.
.SS "void Csla\&.Test\&.IO\&.DPMethodOverloadTests\&.FetchWithOtherCriteria ()"

.PP
Definition at line 108 of file DPMethodOverloadTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
