.TH "Csla.Channels.RabbitMq" 3 "Thu Jul 22 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Channels.RabbitMq
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBProxyListener\fP"
.br
.RI "Handles replies from data portal server\&. "
.ti -1c
.RI "class \fBRabbitMqPortal\fP"
.br
.RI "Exposes server-side \fBDataPortal\fP functionality through RabbitMQ "
.ti -1c
.RI "class \fBRabbitMqProxy\fP"
.br
.RI "Implements a data portal proxy to relay data portal calls to a remote application server by using RabbitMQ\&. "
.ti -1c
.RI "class \fBWip\fP"
.br
.ti -1c
.RI "class \fBWipItem\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
