.TH "Csla.Test.IO.IOTests" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.IO.IOTests
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSaveNewRoot\fP ()"
.br
.ti -1c
.RI "void \fBSaveOldRoot\fP ()"
.br
.ti -1c
.RI "void \fBLoadRoot\fP ()"
.br
.ti -1c
.RI "void \fBDeleteNewRoot\fP ()"
.br
.ti -1c
.RI "void \fBDeleteOldRoot\fP ()"
.br
.ti -1c
.RI "void \fBDeleteRootImmediate\fP ()"
.br
.ti -1c
.RI "void \fBClearContextsAfterEachTest\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 25 of file IOTests\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Csla\&.Test\&.IO\&.IOTests\&.ClearContextsAfterEachTest ()"

.PP
Definition at line 139 of file IOTests\&.cs\&.
.SS "void Csla\&.Test\&.IO\&.IOTests\&.DeleteNewRoot ()"

.PP
Definition at line 89 of file IOTests\&.cs\&.
.SS "void Csla\&.Test\&.IO\&.IOTests\&.DeleteOldRoot ()"

.PP
Definition at line 110 of file IOTests\&.cs\&.
.SS "void Csla\&.Test\&.IO\&.IOTests\&.DeleteRootImmediate ()"

.PP
Definition at line 131 of file IOTests\&.cs\&.
.SS "void Csla\&.Test\&.IO\&.IOTests\&.LoadRoot ()"

.PP
Definition at line 74 of file IOTests\&.cs\&.
.SS "void Csla\&.Test\&.IO\&.IOTests\&.SaveNewRoot ()"

.PP
Definition at line 29 of file IOTests\&.cs\&.
.SS "void Csla\&.Test\&.IO\&.IOTests\&.SaveOldRoot ()"

.PP
Definition at line 52 of file IOTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
