.TH "Csla.Test.Basic.GrandChildren" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.Basic.GrandChildren
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.BusinessListBase< GrandChildren, GrandChild >\fP, and \fBCsla\&.BusinessBindingListBase< GrandChildren, GrandChild >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBAdd\fP (string data)"
.br
.ti -1c
.RI "\fBGrandChildren\fP ()"
.br
.ti -1c
.RI "void \fBAdd\fP (string data)"
.br
.ti -1c
.RI "\fBGrandChildren\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 16 of file GrandChildren\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Csla\&.Test\&.Basic\&.GrandChildren\&.GrandChildren ()"

.PP
Definition at line 41 of file GrandChildren\&.cs\&.
.SS "Csla\&.Test\&.Basic\&.GrandChildren\&.GrandChildren ()"

.PP
Definition at line 41 of file GrandChildren\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Csla\&.Test\&.Basic\&.GrandChildren\&.Add (string data)"

.PP
Definition at line 18 of file GrandChildren\&.cs\&.
.SS "void Csla\&.Test\&.Basic\&.GrandChildren\&.Add (string data)"

.PP
Definition at line 18 of file GrandChildren\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
