.TH "Csla.Serialization.Mobile.ISerializationNotification" 3 "Thu Jul 22 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Serialization.Mobile.ISerializationNotification \- Interface defining callback methods used by the SerializationFormatterFactory\&.GetFormatter()\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBCsla\&.Core\&.BusinessBase\fP, \fBCsla\&.Core\&.ExtendedBindingList< T >\fP, \fBCsla\&.Core\&.ObservableBindingList< T >\fP, \fBCsla\&.DynamicListBase< T >\fP, \fBCsla\&.IBusinessBase\fP, \fBCsla\&.IBusinessListBase< C >\fP, \fBCsla\&.IReadOnlyBase\fP, \fBCsla\&.IReadOnlyListBase< C >\fP, \fBCsla\&.ReadOnlyBase< T >\fP, and \fBCsla\&.Rules\&.BusinessRules\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBDeserialized\fP ()"
.br
.RI "Method called on an object after deserialization is complete\&. "
.in -1c
.SH "Detailed Description"
.PP 
Interface defining callback methods used by the SerializationFormatterFactory\&.GetFormatter()\&. 


.PP
Definition at line 16 of file ISerializationNotification\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Csla\&.Serialization\&.Mobile\&.ISerializationNotification\&.Deserialized ()"

.PP
Method called on an object after deserialization is complete\&. This method is called on all objects in an object graph after all the objects have been deserialized\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
