.TH "Csla.Windows.BindingSourceRefresh" 3 "Thu Jul 22 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Windows.BindingSourceRefresh \- \fBBindingSourceRefresh\fP contains functionality for refreshing the data bound to controls on Host as well as a mechinism for catching data binding errors that occur in Host\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits System\&.ComponentModel\&.Component, IExtenderProvider, and ISupportInitialize\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBindingSourceRefresh\fP ()"
.br
.RI "Constructor creates a new \fBBindingSourceRefresh\fP component then initialises all the different sub components\&. "
.ti -1c
.RI "\fBBindingSourceRefresh\fP (IContainer container)"
.br
.RI "Constructor creates a new \fBBindingSourceRefresh\fP component, adds the component to the container supplied before initialising all the different sub components\&. "
.ti -1c
.RI "bool \fBCanExtend\fP (object extendee)"
.br
.RI "\fBCanExtend()\fP returns true if extendee is a binding source\&. "
.ti -1c
.RI "bool \fBGetReadValuesOnChange\fP (BindingSource source)"
.br
.RI "\fBGetReadValuesOnChange()\fP gets the value of the custom ReadValuesOnChange extender property added to extended controls\&. "
.ti -1c
.RI "void \fBSetReadValuesOnChange\fP (BindingSource source, bool value)"
.br
.RI "\fBSetReadValuesOnChange()\fP sets the value of the custom ReadValuesOnChange extender property added to extended controls\&. "
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBDispose\fP (bool disposing)"
.br
.RI "Clean up any resources being used\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "ContainerControl \fBHost\fP\fC [get, set]\fP"
.br
.RI "Not in use - kept for backward compatibility "
.ti -1c
.RI "bool \fBRefreshOnException\fP\fC [get, set]\fP"
.br
.RI "Forces the binding to re-read after an exception is thrown when changing the binding value "
.in -1c
.SS "Events"

.in +1c
.ti -1c
.RI "\fBBindingErrorEventHandler\fP \fBBindingError\fP = null"
.br
.RI "BindingError event is raised when a data binding error occurs due to a exception\&. "
.in -1c
.SH "Detailed Description"
.PP 
\fBBindingSourceRefresh\fP contains functionality for refreshing the data bound to controls on Host as well as a mechinism for catching data binding errors that occur in Host\&. 

\fBWindows\fP Forms extender control that resolves the data refresh issue with data bound detail controls as discussed in Chapter 5\&.
.PP
Definition at line 29 of file BindingSourceRefresh\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Csla\&.Windows\&.BindingSourceRefresh\&.BindingSourceRefresh ()"

.PP
Constructor creates a new \fBBindingSourceRefresh\fP component then initialises all the different sub components\&. 
.PP
Definition at line 44 of file BindingSourceRefresh\&.cs\&.
.SS "Csla\&.Windows\&.BindingSourceRefresh\&.BindingSourceRefresh (IContainer container)"

.PP
Constructor creates a new \fBBindingSourceRefresh\fP component, adds the component to the container supplied before initialising all the different sub components\&. 
.PP
\fBParameters\fP
.RS 4
\fIcontainer\fP The container the component is to be added to\&.
.RE
.PP

.PP
Definition at line 52 of file BindingSourceRefresh\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "bool Csla\&.Windows\&.BindingSourceRefresh\&.CanExtend (object extendee)"

.PP
\fBCanExtend()\fP returns true if extendee is a binding source\&. 
.PP
\fBParameters\fP
.RS 4
\fIextendee\fP The control to be extended\&.
.RE
.PP
\fBReturns\fP
.RS 4
True if the control is a binding source, else false\&.
.RE
.PP

.PP
Definition at line 94 of file BindingSourceRefresh\&.cs\&.
.SS "override void Csla\&.Windows\&.BindingSourceRefresh\&.Dispose (bool disposing)\fC [protected]\fP"

.PP
Clean up any resources being used\&. 
.PP
\fBParameters\fP
.RS 4
\fIdisposing\fP true if managed resources should be disposed; otherwise, false\&.
.RE
.PP

.PP
Definition at line 68 of file BindingSourceRefresh\&.cs\&.
.SS "bool Csla\&.Windows\&.BindingSourceRefresh\&.GetReadValuesOnChange (BindingSource source)"

.PP
\fBGetReadValuesOnChange()\fP gets the value of the custom ReadValuesOnChange extender property added to extended controls\&. property added to extended controls\&.
.PP
\fBParameters\fP
.RS 4
\fIsource\fP Control being extended\&.
.RE
.PP

.PP
Definition at line 104 of file BindingSourceRefresh\&.cs\&.
.SS "void Csla\&.Windows\&.BindingSourceRefresh\&.SetReadValuesOnChange (BindingSource source, bool value)"

.PP
\fBSetReadValuesOnChange()\fP sets the value of the custom ReadValuesOnChange extender property added to extended controls\&. 
.PP
\fBParameters\fP
.RS 4
\fIsource\fP Control being extended\&.
.br
\fIvalue\fP New value of property\&.
.RE
.PP

.PP
Definition at line 120 of file BindingSourceRefresh\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "ContainerControl Csla\&.Windows\&.BindingSourceRefresh\&.Host\fC [get]\fP, \fC [set]\fP"

.PP
Not in use - kept for backward compatibility 
.PP
Definition at line 141 of file BindingSourceRefresh\&.cs\&.
.SS "bool Csla\&.Windows\&.BindingSourceRefresh\&.RefreshOnException\fC [get]\fP, \fC [set]\fP"

.PP
Forces the binding to re-read after an exception is thrown when changing the binding value 
.PP
Definition at line 148 of file BindingSourceRefresh\&.cs\&.
.SH "Event Documentation"
.PP 
.SS "\fBBindingErrorEventHandler\fP Csla\&.Windows\&.BindingSourceRefresh\&.BindingError = null"

.PP
BindingError event is raised when a data binding error occurs due to a exception\&. 
.PP
Definition at line 38 of file BindingSourceRefresh\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
