.TH "Csla.Test.AppContext.AppContextThread" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.AppContext.AppContextThread
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAppContextThread\fP (string Name)"
.br
.ti -1c
.RI "void \fBStop\fP ()"
.br
.ti -1c
.RI "void \fBRun\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "bool \fBRemoved\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 16 of file AppContextThread\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Csla\&.Test\&.AppContext\&.AppContextThread\&.AppContextThread (string Name)"

.PP
Definition at line 39 of file AppContextThread\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Csla\&.Test\&.AppContext\&.AppContextThread\&.Run ()"

.PP
Definition at line 49 of file AppContextThread\&.cs\&.
.SS "void Csla\&.Test\&.AppContext\&.AppContextThread\&.Stop ()"

.PP
Definition at line 44 of file AppContextThread\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "bool Csla\&.Test\&.AppContext\&.AppContextThread\&.Removed\fC [get]\fP"

.PP
Definition at line 23 of file AppContextThread\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
