.TH "Csla.Rules.CommonRules.Required" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Rules.CommonRules.Required \- Business rule for a required string\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.Rules\&.CommonRules\&.CommonBusinessRule\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRequired\fP (\fBCsla\&.Core\&.IPropertyInfo\fP primaryProperty)"
.br
.RI "Creates an instance of the rule\&. "
.ti -1c
.RI "\fBRequired\fP (\fBCsla\&.Core\&.IPropertyInfo\fP primaryProperty, string message)"
.br
.RI "Creates an instance of the rule\&. "
.ti -1c
.RI "\fBRequired\fP (\fBCsla\&.Core\&.IPropertyInfo\fP primaryProperty, Func< string > messageDelegate)"
.br
.RI "Creates an instance of the rule\&. "
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override string \fBGetMessage\fP ()"
.br
.RI "Gets the error message\&. "
.ti -1c
.RI "override void \fBExecute\fP (\fBIRuleContext\fP context)"
.br
.RI "Rule implementation\&. "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Business rule for a required string\&. 


.PP
Definition at line 105 of file CommonRules\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Csla\&.Rules\&.CommonRules\&.Required\&.Required (\fBCsla\&.Core\&.IPropertyInfo\fP primaryProperty)"

.PP
Creates an instance of the rule\&. 
.PP
\fBParameters\fP
.RS 4
\fIprimaryProperty\fP Property to which the rule applies\&.
.RE
.PP

.PP
Definition at line 111 of file CommonRules\&.cs\&.
.SS "Csla\&.Rules\&.CommonRules\&.Required\&.Required (\fBCsla\&.Core\&.IPropertyInfo\fP primaryProperty, string message)"

.PP
Creates an instance of the rule\&. 
.PP
\fBParameters\fP
.RS 4
\fIprimaryProperty\fP Property to which the rule applies\&.
.br
\fImessage\fP The message\&.
.RE
.PP

.PP
Definition at line 123 of file CommonRules\&.cs\&.
.SS "Csla\&.Rules\&.CommonRules\&.Required\&.Required (\fBCsla\&.Core\&.IPropertyInfo\fP primaryProperty, Func< string > messageDelegate)"

.PP
Creates an instance of the rule\&. 
.PP
\fBParameters\fP
.RS 4
\fIprimaryProperty\fP Property to which the rule applies\&.
.br
\fImessageDelegate\fP The localizable message\&.
.RE
.PP

.PP
Definition at line 134 of file CommonRules\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override void Csla\&.Rules\&.CommonRules\&.Required\&.Execute (\fBIRuleContext\fP context)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Rule implementation\&. 
.PP
\fBParameters\fP
.RS 4
\fIcontext\fP Rule context\&.
.RE
.PP

.PP
Reimplemented from \fBCsla\&.Rules\&.BusinessRule\fP\&.
.PP
Definition at line 153 of file CommonRules\&.cs\&.
.SS "override string Csla\&.Rules\&.CommonRules\&.Required\&.GetMessage ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Gets the error message\&. 
.PP
Reimplemented from \fBCsla\&.Rules\&.PropertyRule\fP\&.
.PP
Definition at line 144 of file CommonRules\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
