.TH "Csla.Web.Mvc.Test.ModelBinderTest.RootWithValidation" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Web.Mvc.Test.ModelBinderTest.RootWithValidation
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.BusinessBase< RootWithValidation >\fP\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBRootWithValidation\fP \fBNewRootWithValidation\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static readonly \fBPropertyInfo\fP< string > \fBMax5CharsProperty\fP = RegisterProperty<string>(p => p\&.Max5Chars)"
.br
.ti -1c
.RI "static readonly \fBPropertyInfo\fP< int > \fBBetween2And10Property\fP = RegisterProperty<int>(p => p\&.Between2And10)"
.br
.ti -1c
.RI "static readonly \fBPropertyInfo\fP< string > \fBAlwaysInvalidProperty\fP = RegisterProperty<string>(p => p\&.AlwaysInvalid)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBAddBusinessRules\fP ()"
.br
.ti -1c
.RI "override void \fBDataPortal_Create\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBMax5Chars\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBBetween2And10\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBAlwaysInvalid\fP\fC [get, set]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 18 of file RootWithValidation\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override void Csla\&.Web\&.Mvc\&.Test\&.ModelBinderTest\&.RootWithValidation\&.AddBusinessRules ()\fC [protected]\fP"

.PP
Definition at line 43 of file RootWithValidation\&.cs\&.
.SS "override void Csla\&.Web\&.Mvc\&.Test\&.ModelBinderTest\&.RootWithValidation\&.DataPortal_Create ()\fC [protected]\fP"

.PP
Definition at line 54 of file RootWithValidation\&.cs\&.
.SS "static \fBRootWithValidation\fP Csla\&.Web\&.Mvc\&.Test\&.ModelBinderTest\&.RootWithValidation\&.NewRootWithValidation ()\fC [static]\fP"

.PP
Definition at line 50 of file RootWithValidation\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "readonly \fBPropertyInfo\fP<string> Csla\&.Web\&.Mvc\&.Test\&.ModelBinderTest\&.RootWithValidation\&.AlwaysInvalidProperty = RegisterProperty<string>(p => p\&.AlwaysInvalid)\fC [static]\fP"

.PP
Definition at line 35 of file RootWithValidation\&.cs\&.
.SS "readonly \fBPropertyInfo\fP<int> Csla\&.Web\&.Mvc\&.Test\&.ModelBinderTest\&.RootWithValidation\&.Between2And10Property = RegisterProperty<int>(p => p\&.Between2And10)\fC [static]\fP"

.PP
Definition at line 27 of file RootWithValidation\&.cs\&.
.SS "readonly \fBPropertyInfo\fP<string> Csla\&.Web\&.Mvc\&.Test\&.ModelBinderTest\&.RootWithValidation\&.Max5CharsProperty = RegisterProperty<string>(p => p\&.Max5Chars)\fC [static]\fP"

.PP
Definition at line 20 of file RootWithValidation\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "string Csla\&.Web\&.Mvc\&.Test\&.ModelBinderTest\&.RootWithValidation\&.AlwaysInvalid\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 37 of file RootWithValidation\&.cs\&.
.SS "int Csla\&.Web\&.Mvc\&.Test\&.ModelBinderTest\&.RootWithValidation\&.Between2And10\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 29 of file RootWithValidation\&.cs\&.
.SS "string Csla\&.Web\&.Mvc\&.Test\&.ModelBinderTest\&.RootWithValidation\&.Max5Chars\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 21 of file RootWithValidation\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
