.TH "Csla.Test.Utilities.UtilitiesTestHelper" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.Utilities.UtilitiesTestHelper
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override string \fBToString\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "const string \fBToStringValue\fP = 'UtilitiesTestHelper\&.ToString'"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBStringProperty\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBNullableStringProperty\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBIntProperty\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 12 of file UtilitiesTestHelper\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override string Csla\&.Test\&.Utilities\&.UtilitiesTestHelper\&.ToString ()"

.PP
Definition at line 22 of file UtilitiesTestHelper\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "const string Csla\&.Test\&.Utilities\&.UtilitiesTestHelper\&.ToStringValue = 'UtilitiesTestHelper\&.ToString'\fC [static]\fP"

.PP
Definition at line 14 of file UtilitiesTestHelper\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "int Csla\&.Test\&.Utilities\&.UtilitiesTestHelper\&.IntProperty\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 20 of file UtilitiesTestHelper\&.cs\&.
.SS "string Csla\&.Test\&.Utilities\&.UtilitiesTestHelper\&.NullableStringProperty\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 18 of file UtilitiesTestHelper\&.cs\&.
.SS "string Csla\&.Test\&.Utilities\&.UtilitiesTestHelper\&.StringProperty\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 16 of file UtilitiesTestHelper\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
