.TH "Csla.Test.Windows.ActionExtenderTests" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.Windows.ActionExtenderTests
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBTestActionExtenderDefaultButtonState\fP ()"
.br
.ti -1c
.RI "void \fBTestActionExtenderChangeState\fP ()"
.br
.ti -1c
.RI "void \fBTestActionExtenderToolStripDefaultButtonState\fP ()"
.br
.ti -1c
.RI "void \fBTestActionExtenderToolStripChangeState\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 32 of file ActionExtenderTests\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Csla\&.Test\&.Windows\&.ActionExtenderTests\&.TestActionExtenderChangeState ()"

.PP
Definition at line 72 of file ActionExtenderTests\&.cs\&.
.SS "void Csla\&.Test\&.Windows\&.ActionExtenderTests\&.TestActionExtenderDefaultButtonState ()"

.PP
Definition at line 37 of file ActionExtenderTests\&.cs\&.
.SS "void Csla\&.Test\&.Windows\&.ActionExtenderTests\&.TestActionExtenderToolStripChangeState ()"

.PP
Definition at line 141 of file ActionExtenderTests\&.cs\&.
.SS "void Csla\&.Test\&.Windows\&.ActionExtenderTests\&.TestActionExtenderToolStripDefaultButtonState ()"

.PP
Definition at line 106 of file ActionExtenderTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
