.TH "Csla.Test.ValidationRules.HasBadSharedRule" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.ValidationRules.HasBadSharedRule
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.BusinessBase< HasBadSharedRule >\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBadRule\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBPropertyInfo\fP< string > \fBDataProperty\fP = RegisterProperty<string>(c => c\&.Data)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBAddBusinessRules\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBData\fP\fC [get, set]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 20 of file HasBadSharedRule\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override void Csla\&.Test\&.ValidationRules\&.HasBadSharedRule\&.AddBusinessRules ()\fC [protected]\fP"

.PP
Definition at line 29 of file HasBadSharedRule\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBPropertyInfo\fP<string> Csla\&.Test\&.ValidationRules\&.HasBadSharedRule\&.DataProperty = RegisterProperty<string>(c => c\&.Data)\fC [static]\fP"

.PP
Definition at line 22 of file HasBadSharedRule\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "string Csla\&.Test\&.ValidationRules\&.HasBadSharedRule\&.Data\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 23 of file HasBadSharedRule\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
