.TH "Csla.Test.DataPortal.ICriteria" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.DataPortal.ICriteria
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.IReadOnlyBase\fP\&.
.PP
Inherited by \fBCsla\&.Test\&.DataPortal\&.MyCriteria\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBId\fP\fC [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 377 of file ServiceProviderMethodCallerTests\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "int Csla\&.Test\&.DataPortal\&.ICriteria\&.Id\fC [get]\fP"

.PP
Definition at line 379 of file ServiceProviderMethodCallerTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
