.TH "Csla.Server.Hosts.Mobile.WcfErrorInfo" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Server.Hosts.Mobile.WcfErrorInfo \- Message containing details about any server-side exception\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBWcfErrorInfo\fP (Exception ex)"
.br
.RI "Creates an instance of the object\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBExceptionTypeName\fP\fC [get, set]\fP"
.br
.RI "Type name of the exception object\&. "
.ti -1c
.RI "string \fBMessage\fP\fC [get, set]\fP"
.br
.RI "Message from the exception object\&. "
.ti -1c
.RI "string \fBStackTrace\fP\fC [get, set]\fP"
.br
.RI "Stack trace from the exception object\&. "
.ti -1c
.RI "string \fBSource\fP\fC [get, set]\fP"
.br
.RI "Source of the exception object\&. "
.ti -1c
.RI "string \fBTargetSiteName\fP\fC [get, set]\fP"
.br
.RI "Target site name from the exception object\&. "
.ti -1c
.RI "\fBWcfErrorInfo\fP \fBInnerError\fP\fC [get]\fP"
.br
.RI "\fBWcfErrorInfo\fP object containing information about any inner exception of the original exception\&. "
.in -1c
.SH "Detailed Description"
.PP 
Message containing details about any server-side exception\&. 


.PP
Definition at line 19 of file WcfErrorInfo\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Csla\&.Server\&.Hosts\&.Mobile\&.WcfErrorInfo\&.WcfErrorInfo (Exception ex)"

.PP
Creates an instance of the object\&. 
.PP
\fBParameters\fP
.RS 4
\fIex\fP The Exception to encapusulate\&. 
.RE
.PP

.PP
Definition at line 60 of file WcfErrorInfo\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "string Csla\&.Server\&.Hosts\&.Mobile\&.WcfErrorInfo\&.ExceptionTypeName\fC [get]\fP, \fC [set]\fP"

.PP
Type name of the exception object\&. 
.PP
Definition at line 25 of file WcfErrorInfo\&.cs\&.
.SS "\fBWcfErrorInfo\fP Csla\&.Server\&.Hosts\&.Mobile\&.WcfErrorInfo\&.InnerError\fC [get]\fP"

.PP
\fBWcfErrorInfo\fP object containing information about any inner exception of the original exception\&. 
.PP
Definition at line 52 of file WcfErrorInfo\&.cs\&.
.SS "string Csla\&.Server\&.Hosts\&.Mobile\&.WcfErrorInfo\&.Message\fC [get]\fP, \fC [set]\fP"

.PP
Message from the exception object\&. 
.PP
Definition at line 30 of file WcfErrorInfo\&.cs\&.
.SS "string Csla\&.Server\&.Hosts\&.Mobile\&.WcfErrorInfo\&.Source\fC [get]\fP, \fC [set]\fP"

.PP
Source of the exception object\&. 
.PP
Definition at line 40 of file WcfErrorInfo\&.cs\&.
.SS "string Csla\&.Server\&.Hosts\&.Mobile\&.WcfErrorInfo\&.StackTrace\fC [get]\fP, \fC [set]\fP"

.PP
Stack trace from the exception object\&. 
.PP
Definition at line 35 of file WcfErrorInfo\&.cs\&.
.SS "string Csla\&.Server\&.Hosts\&.Mobile\&.WcfErrorInfo\&.TargetSiteName\fC [get]\fP, \fC [set]\fP"

.PP
Target site name from the exception object\&. 
.PP
Definition at line 45 of file WcfErrorInfo\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
