.TH "Csla.Test.Nullable.NullableObject" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.Nullable.NullableObject
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.BusinessBase< NullableObject >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNullableObject\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBNullableObject\fP \fBNewNullableObject\fP ()"
.br
.ti -1c
.RI "static \fBNullableObject\fP \fBGetNullableObject\fP (string name)"
.br
.ti -1c
.RI "static void \fBDeleteNullableObject\fP (string name)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Nullable< int > \fB_nullableIntMember\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override object \fBGetIdValue\fP ()"
.br
.RI "Override this method to return a unique identifying value for this object\&. "
.ti -1c
.RI "void \fBDataPortal_Fetch\fP (object criteria)"
.br
.ti -1c
.RI "void \fBDataPortal_Update\fP ()"
.br
.ti -1c
.RI "void \fBDataPortal_Delete\fP (object criteria)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBName\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "Nullable< int > \fBNullableInteger\fP\fC [get, set]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 15 of file NullableObject\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Csla\&.Test\&.Nullable\&.NullableObject\&.NullableObject ()"

.PP
Definition at line 79 of file NullableObject\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Csla\&.Test\&.Nullable\&.NullableObject\&.DataPortal_Delete (object criteria)\fC [protected]\fP"

.PP
Definition at line 126 of file NullableObject\&.cs\&.
.SS "void Csla\&.Test\&.Nullable\&.NullableObject\&.DataPortal_Fetch (object criteria)\fC [protected]\fP"

.PP
Definition at line 92 of file NullableObject\&.cs\&.
.SS "void Csla\&.Test\&.Nullable\&.NullableObject\&.DataPortal_Update ()\fC [protected]\fP"

.PP
Definition at line 101 of file NullableObject\&.cs\&.
.SS "static void Csla\&.Test\&.Nullable\&.NullableObject\&.DeleteNullableObject (string name)\fC [static]\fP"

.PP
Definition at line 74 of file NullableObject\&.cs\&.
.SS "override object Csla\&.Test\&.Nullable\&.NullableObject\&.GetIdValue ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Override this method to return a unique identifying value for this object\&. 
.PP
Reimplemented from \fBCsla\&.BusinessBase< NullableObject >\fP\&.
.PP
Definition at line 21 of file NullableObject\&.cs\&.
.SS "static \fBNullableObject\fP Csla\&.Test\&.Nullable\&.NullableObject\&.GetNullableObject (string name)\fC [static]\fP"

.PP
Definition at line 69 of file NullableObject\&.cs\&.
.SS "static \fBNullableObject\fP Csla\&.Test\&.Nullable\&.NullableObject\&.NewNullableObject ()\fC [static]\fP"

.PP
Definition at line 64 of file NullableObject\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "Nullable<int> Csla\&.Test\&.Nullable\&.NullableObject\&._nullableIntMember"

.PP
Definition at line 19 of file NullableObject\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "string Csla\&.Test\&.Nullable\&.NullableObject\&.Name\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 26 of file NullableObject\&.cs\&.
.SS "Nullable<int> Csla\&.Test\&.Nullable\&.NullableObject\&.NullableInteger\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 35 of file NullableObject\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
