.TH "Csla.Rules.IHostRules" 3 "Thu Jul 22 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Rules.IHostRules \- Defines the interaction between the rules engine and a business object that hosts the rules\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBCsla\&.Core\&.BusinessBase\fP, \fBCsla\&.IBusinessBase\fP, \fBCsla\&.IReadOnlyBase\fP, and \fBCsla\&.ReadOnlyBase< T >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBRuleStart\fP (\fBCsla\&.Core\&.IPropertyInfo\fP property)"
.br
.RI "Indicates that a rule has started processing\&. "
.ti -1c
.RI "void \fBRuleComplete\fP (\fBCsla\&.Core\&.IPropertyInfo\fP property)"
.br
.RI "Indicates that a rule has finished processing\&. "
.ti -1c
.RI "void \fBRuleComplete\fP (string property)"
.br
.RI "Indicates that a rule has finished processing\&. "
.ti -1c
.RI "void \fBAllRulesComplete\fP ()"
.br
.RI "Indicates that all rules have finished processing\&. "
.in -1c
.SH "Detailed Description"
.PP 
Defines the interaction between the rules engine and a business object that hosts the rules\&. 


.PP
Definition at line 19 of file IHostRules\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Csla\&.Rules\&.IHostRules\&.AllRulesComplete ()"

.PP
Indicates that all rules have finished processing\&. 
.SS "void Csla\&.Rules\&.IHostRules\&.RuleComplete (\fBCsla\&.Core\&.IPropertyInfo\fP property)"

.PP
Indicates that a rule has finished processing\&. 
.PP
\fBParameters\fP
.RS 4
\fIproperty\fP Property for rule\&.
.RE
.PP

.SS "void Csla\&.Rules\&.IHostRules\&.RuleComplete (string property)"

.PP
Indicates that a rule has finished processing\&. 
.PP
\fBParameters\fP
.RS 4
\fIproperty\fP Property for rule\&.
.RE
.PP

.SS "void Csla\&.Rules\&.IHostRules\&.RuleStart (\fBCsla\&.Core\&.IPropertyInfo\fP property)"

.PP
Indicates that a rule has started processing\&. 
.PP
\fBParameters\fP
.RS 4
\fIproperty\fP Property for rule\&.
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
