.TH "Csla.Test.DataBinding" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.DataBinding
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBChildEntity\fP"
.br
.ti -1c
.RI "class \fBChildEntityList\fP"
.br
.ti -1c
.RI "class \fBParentEntity\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
