.TH "Csla.Serialization.Mobile.CslaLegacyBinaryWriter" 3 "Thu Jul 22 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Serialization.Mobile.CslaLegacyBinaryWriter \- This is a legacy version of \fBCslaBinaryWriter\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.Serialization\&.Mobile\&.ICslaWriter\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCslaLegacyBinaryWriter\fP ()"
.br
.RI "Creates new instance of \fBCslaLegacyBinaryWriter\fP "
.ti -1c
.RI "void \fBWrite\fP (Stream serializationStream, List< \fBSerializationInfo\fP > objectData)"
.br
.RI "Write a list of \fBSerializationInfo\fP objects into stream, typically MemoryStream "
.in -1c
.SH "Detailed Description"
.PP 
This is a legacy version of \fBCslaBinaryWriter\fP\&. 

You should not use this type unless you have issues with the \fBCslaBinaryWriter\fP\&.
.PP
Definition at line 13 of file CslaLegacyBinaryWriter\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Csla\&.Serialization\&.Mobile\&.CslaLegacyBinaryWriter\&.CslaLegacyBinaryWriter ()"

.PP
Creates new instance of \fBCslaLegacyBinaryWriter\fP 
.PP
Definition at line 20 of file CslaLegacyBinaryWriter\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Csla\&.Serialization\&.Mobile\&.CslaLegacyBinaryWriter\&.Write (Stream serializationStream, List< \fBSerializationInfo\fP > objectData)"

.PP
Write a list of \fBSerializationInfo\fP objects into stream, typically MemoryStream 
.PP
\fBParameters\fP
.RS 4
\fIserializationStream\fP Stream to write the data into
.br
\fIobjectData\fP List of \fBSerializationInfo\fP objects to write to stream
.RE
.PP

.PP
Implements \fBCsla\&.Serialization\&.Mobile\&.ICslaWriter\fP\&.
.PP
Definition at line 32 of file CslaLegacyBinaryWriter\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
