.TH "Csla.Test.Authorization.PerTypeAuthorizationTests" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.Authorization.PerTypeAuthorizationTests
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBDenyWritePerType\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 32 of file PerTypeAuthorization\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Csla\&.Test\&.Authorization\&.PerTypeAuthorizationTests\&.DenyWritePerType ()"

.PP
Definition at line 36 of file PerTypeAuthorization\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
