.TH "Csla.Server.DataPortalBroker" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Server.DataPortalBroker \- Allows the \fBData\fP Portal call to be intercepted by a custom \fBIDataPortalServer\fP implementation\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.Server\&.IDataPortalServer\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "Task< \fBDataPortalResult\fP > \fBCreate\fP (Type objectType, object criteria, \fBDataPortalContext\fP context, bool isSync)"
.br
.RI "Create a new business object\&. "
.ti -1c
.RI "Task< \fBDataPortalResult\fP > \fBFetch\fP (Type objectType, object criteria, \fBDataPortalContext\fP context, bool isSync)"
.br
.RI "Get an existing business object\&. "
.ti -1c
.RI "Task< \fBDataPortalResult\fP > \fBUpdate\fP (object obj, \fBDataPortalContext\fP context, bool isSync)"
.br
.RI "Update a business object\&. "
.ti -1c
.RI "Task< \fBDataPortalResult\fP > \fBDelete\fP (Type objectType, object criteria, \fBDataPortalContext\fP context, bool isSync)"
.br
.RI "Delete a business object\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "static \fBIDataPortalServer\fP \fBDataPortalServer\fP\fC [get, set]\fP"
.br
.RI "Gets or sets a reference to a implementation of \fBIDataPortalServer\fP to be used\&. "
.in -1c
.SH "Detailed Description"
.PP 
Allows the \fBData\fP Portal call to be intercepted by a custom \fBIDataPortalServer\fP implementation\&. 


.PP
Definition at line 17 of file DataPortalBroker\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "Task<\fBDataPortalResult\fP> Csla\&.Server\&.DataPortalBroker\&.Create (Type objectType, object criteria, \fBDataPortalContext\fP context, bool isSync)"

.PP
Create a new business object\&. 
.PP
\fBParameters\fP
.RS 4
\fIobjectType\fP Type of business object to create\&.
.br
\fIcriteria\fP Criteria object describing business object\&.
.br
\fIcontext\fP \fBServer\&.DataPortalContext\fP object passed to the server\&. 
.br
\fIisSync\fP True if the client-side proxy should synchronously invoke the server\&.
.RE
.PP

.PP
Implements \fBCsla\&.Server\&.IDataPortalServer\fP\&.
.PP
Definition at line 34 of file DataPortalBroker\&.cs\&.
.SS "Task<\fBDataPortalResult\fP> Csla\&.Server\&.DataPortalBroker\&.Delete (Type objectType, object criteria, \fBDataPortalContext\fP context, bool isSync)"

.PP
Delete a business object\&. 
.PP
\fBParameters\fP
.RS 4
\fIobjectType\fP Type of business object to create\&.
.br
\fIcriteria\fP Criteria object describing business object\&.
.br
\fIcontext\fP \fBServer\&.DataPortalContext\fP object passed to the server\&. 
.br
\fIisSync\fP True if the client-side proxy should synchronously invoke the server\&.
.RE
.PP

.PP
Implements \fBCsla\&.Server\&.IDataPortalServer\fP\&.
.PP
Definition at line 99 of file DataPortalBroker\&.cs\&.
.SS "Task<\fBDataPortalResult\fP> Csla\&.Server\&.DataPortalBroker\&.Fetch (Type objectType, object criteria, \fBDataPortalContext\fP context, bool isSync)"

.PP
Get an existing business object\&. 
.PP
\fBParameters\fP
.RS 4
\fIobjectType\fP Type of business object to retrieve\&.
.br
\fIcriteria\fP Criteria object describing business object\&.
.br
\fIcontext\fP \fBServer\&.DataPortalContext\fP object passed to the server\&. 
.br
\fIisSync\fP True if the client-side proxy should synchronously invoke the server\&.
.RE
.PP

.PP
Implements \fBCsla\&.Server\&.IDataPortalServer\fP\&.
.PP
Definition at line 56 of file DataPortalBroker\&.cs\&.
.SS "Task<\fBDataPortalResult\fP> Csla\&.Server\&.DataPortalBroker\&.Update (object obj, \fBDataPortalContext\fP context, bool isSync)"

.PP
Update a business object\&. 
.PP
\fBParameters\fP
.RS 4
\fIobj\fP Business object to update\&.
.br
\fIcontext\fP \fBServer\&.DataPortalContext\fP object passed to the server\&. 
.br
\fIisSync\fP True if the client-side proxy should synchronously invoke the server\&.
.RE
.PP

.PP
Implements \fBCsla\&.Server\&.IDataPortalServer\fP\&.
.PP
Definition at line 77 of file DataPortalBroker\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "\fBIDataPortalServer\fP Csla\&.Server\&.DataPortalBroker\&.DataPortalServer\fC [static]\fP, \fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets a reference to a implementation of \fBIDataPortalServer\fP to be used\&. 
.PP
Definition at line 23 of file DataPortalBroker\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
