.TH "Csla.Test.DataAnnotations.MultipleMetaDataClass" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.DataAnnotations.MultipleMetaDataClass
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "System\&.Decimal \fBAmount\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "System\&.Int32 \fBQuantity\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 215 of file DataAnnotationsTests\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "System\&.Decimal Csla\&.Test\&.DataAnnotations\&.MultipleMetaDataClass\&.Amount\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 219 of file DataAnnotationsTests\&.cs\&.
.SS "System\&.Int32 Csla\&.Test\&.DataAnnotations\&.MultipleMetaDataClass\&.Quantity\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 223 of file DataAnnotationsTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
