.TH "Csla.Windows.BindingErrorEventArgs" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Windows.BindingErrorEventArgs \- \fBBindingErrorEventArgs\fP defines the event arguments for reporting a data binding error due to a exception\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits EventArgs\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBindingErrorEventArgs\fP (\fBBinding\fP binding, \fBException\fP exception)"
.br
.RI "Constructor creates a new \fBBindingErrorEventArgs\fP object instance using the information specified\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "Exception \fBException\fP\fC [get]\fP"
.br
.RI "Exception gets the exception that caused the binding error\&. "
.ti -1c
.RI "Binding \fBBinding\fP\fC [get]\fP"
.br
.RI "Binding gets the binding that caused the exception\&. "
.in -1c
.SH "Detailed Description"
.PP 
\fBBindingErrorEventArgs\fP defines the event arguments for reporting a data binding error due to a exception\&. 


.PP
Definition at line 338 of file BindingSourceRefresh\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Csla\&.Windows\&.BindingErrorEventArgs\&.BindingErrorEventArgs (\fBBinding\fP binding, \fBException\fP exception)"

.PP
Constructor creates a new \fBBindingErrorEventArgs\fP object instance using the information specified\&. 
.PP
\fBParameters\fP
.RS 4
\fIbinding\fP The binding that caused th exception\&.
.br
\fIexception\fP The exception that caused the error\&.
.RE
.PP

.PP
Definition at line 375 of file BindingSourceRefresh\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "Binding Csla\&.Windows\&.BindingErrorEventArgs\&.Binding\fC [get]\fP"

.PP
Binding gets the binding that caused the exception\&. 
.PP
Definition at line 361 of file BindingSourceRefresh\&.cs\&.
.SS "Exception Csla\&.Windows\&.BindingErrorEventArgs\&.Exception\fC [get]\fP"

.PP
Exception gets the exception that caused the binding error\&. 
.PP
Definition at line 353 of file BindingSourceRefresh\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
