.TH "Csla.Analyzers.Tests.EvaluateOperationAttributeUsageAnalyzerTests" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Analyzers.Tests.EvaluateOperationAttributeUsageAnalyzerTests
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBVerifySupportedDiagnostics\fP ()"
.br
.ti -1c
.RI "async Task \fBAnalyzeWhenTypeIsNotStereotype\fP ()"
.br
.ti -1c
.RI "async Task \fBAnalyzeWhenTypeIsStereotypeAndOperationIsStatic\fP ()"
.br
.ti -1c
.RI "async Task \fBAnalyzeWhenTypeIsStereotypeAndOperationIsInstance\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 10 of file EvaluateOperationAttributeUsageAnalyzerTests\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "async Task Csla\&.Analyzers\&.Tests\&.EvaluateOperationAttributeUsageAnalyzerTests\&.AnalyzeWhenTypeIsNotStereotype ()"

.PP
Definition at line 34 of file EvaluateOperationAttributeUsageAnalyzerTests\&.cs\&.
.SS "async Task Csla\&.Analyzers\&.Tests\&.EvaluateOperationAttributeUsageAnalyzerTests\&.AnalyzeWhenTypeIsStereotypeAndOperationIsInstance ()"

.PP
Definition at line 67 of file EvaluateOperationAttributeUsageAnalyzerTests\&.cs\&.
.SS "async Task Csla\&.Analyzers\&.Tests\&.EvaluateOperationAttributeUsageAnalyzerTests\&.AnalyzeWhenTypeIsStereotypeAndOperationIsStatic ()"

.PP
Definition at line 49 of file EvaluateOperationAttributeUsageAnalyzerTests\&.cs\&.
.SS "void Csla\&.Analyzers\&.Tests\&.EvaluateOperationAttributeUsageAnalyzerTests\&.VerifySupportedDiagnostics ()"

.PP
Definition at line 13 of file EvaluateOperationAttributeUsageAnalyzerTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
