.TH "Csla.Analyzers.IntegrationTests.BusyProperties" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Analyzers.IntegrationTests.BusyProperties
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.BusinessBase< BusyProperties >\fP\&.
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static readonly \fBPropertyInfo\fP< int > \fBIdProperty\fP = RegisterProperty<int>(c => c\&.Id)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBId\fP\fC [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 6 of file BusyProperties\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "readonly \fBPropertyInfo\fP<int> Csla\&.Analyzers\&.IntegrationTests\&.BusyProperties\&.IdProperty = RegisterProperty<int>(c => c\&.Id)\fC [static]\fP"

.PP
Definition at line 9 of file BusyProperties\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "int Csla\&.Analyzers\&.IntegrationTests\&.BusyProperties\&.Id\fC [get]\fP"

.PP
Definition at line 10 of file BusyProperties\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
