.TH "Csla.WcfPortal" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.WcfPortal
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCriteriaRequest\fP"
.br
.ti -1c
.RI "class \fBWcfResponse\fP"
.br
.ti -1c
.RI "class \fBWcfErrorInfo\fP"
.br
.ti -1c
.RI "class \fBUpdateRequest\fP"
.br
.ti -1c
.RI "interface \fBIWcfPortal\fP"
.br
.ti -1c
.RI "interface \fBIWcfPortalChannel\fP"
.br
.ti -1c
.RI "class \fBWcfPortalClient\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
