.TH "Csla.Rules.CommonRules.RegExMatch" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Rules.CommonRules.RegExMatch \- Business rule that evaluates a regular expression\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.Rules\&.CommonRules\&.CommonBusinessRule\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum class \fBNullResultOptions\fP { \fBReturnFalse\fP, \fBReturnTrue\fP, \fBConvertToEmptyString\fP }"
.br
.RI "List of options for the NullResult property\&. "
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRegExMatch\fP (\fBCsla\&.Core\&.IPropertyInfo\fP primaryProperty, string expression)"
.br
.RI "Creates an instance of the rule\&. "
.ti -1c
.RI "\fBRegExMatch\fP (\fBCsla\&.Core\&.IPropertyInfo\fP primaryProperty, string expression, string message)"
.br
.RI "Creates an instance of the rule\&. "
.ti -1c
.RI "\fBRegExMatch\fP (\fBCsla\&.Core\&.IPropertyInfo\fP primaryProperty, string expression, Func< string > messageDelegate)"
.br
.RI "Creates an instance of the rule\&. "
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override string \fBGetMessage\fP ()"
.br
.RI "Gets the error message\&. "
.ti -1c
.RI "override void \fBExecute\fP (\fBIRuleContext\fP context)"
.br
.RI "Rule implementation\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBExpression\fP\fC [get]\fP"
.br
.RI "Gets the regular expression to be evaluated\&. "
.ti -1c
.RI "\fBNullResultOptions\fP \fBNullOption\fP\fC [get, set]\fP"
.br
.RI "Gets or sets a value that controls how null input values are handled\&. "
.in -1c
.SH "Detailed Description"
.PP 
Business rule that evaluates a regular expression\&. 


.PP
Definition at line 485 of file CommonRules\&.cs\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBCsla\&.Rules\&.CommonRules\&.RegExMatch\&.NullResultOptions\fP\fC [strong]\fP"

.PP
List of options for the NullResult property\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIReturnFalse \fP\fP
Indicates that a null value should always result in the rule returning false\&. 
.TP
\fB\fIReturnTrue \fP\fP
Indicates that a null value should always result in the rule returning true\&. 
.TP
\fB\fIConvertToEmptyString \fP\fP
Indicates that a null value should be converted to an empty string before the regular expression is evaluated\&. 
.PP
Definition at line 493 of file CommonRules\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Csla\&.Rules\&.CommonRules\&.RegExMatch\&.RegExMatch (\fBCsla\&.Core\&.IPropertyInfo\fP primaryProperty, string expression)"

.PP
Creates an instance of the rule\&. 
.PP
\fBParameters\fP
.RS 4
\fIprimaryProperty\fP Primary property\&.
.br
\fIexpression\fP Regular expression\&.
.RE
.PP

.PP
Definition at line 536 of file CommonRules\&.cs\&.
.SS "Csla\&.Rules\&.CommonRules\&.RegExMatch\&.RegExMatch (\fBCsla\&.Core\&.IPropertyInfo\fP primaryProperty, string expression, string message)"

.PP
Creates an instance of the rule\&. 
.PP
\fBParameters\fP
.RS 4
\fIprimaryProperty\fP Property to which the rule applies\&.
.br
\fIexpression\fP Regular expression\&.
.br
\fImessage\fP The message\&.
.RE
.PP

.PP
Definition at line 550 of file CommonRules\&.cs\&.
.SS "Csla\&.Rules\&.CommonRules\&.RegExMatch\&.RegExMatch (\fBCsla\&.Core\&.IPropertyInfo\fP primaryProperty, string expression, Func< string > messageDelegate)"

.PP
Creates an instance of the rule\&. 
.PP
\fBParameters\fP
.RS 4
\fIprimaryProperty\fP Property to which the rule applies\&.
.br
\fIexpression\fP Regular expression\&.
.br
\fImessageDelegate\fP The localizable message\&.
.RE
.PP

.PP
Definition at line 563 of file CommonRules\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override void Csla\&.Rules\&.CommonRules\&.RegExMatch\&.Execute (\fBIRuleContext\fP context)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Rule implementation\&. 
.PP
\fBParameters\fP
.RS 4
\fIcontext\fP Rule context\&.
.RE
.PP

.PP
Reimplemented from \fBCsla\&.Rules\&.BusinessRule\fP\&.
.PP
Definition at line 582 of file CommonRules\&.cs\&.
.SS "override string Csla\&.Rules\&.CommonRules\&.RegExMatch\&.GetMessage ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Gets the error message\&. 
.PP
Reimplemented from \fBCsla\&.Rules\&.PropertyRule\fP\&.
.PP
Definition at line 573 of file CommonRules\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "string Csla\&.Rules\&.CommonRules\&.RegExMatch\&.Expression\fC [get]\fP"

.PP
Gets the regular expression to be evaluated\&. 
.PP
Definition at line 523 of file CommonRules\&.cs\&.
.SS "\fBNullResultOptions\fP Csla\&.Rules\&.CommonRules\&.RegExMatch\&.NullOption\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets a value that controls how null input values are handled\&. 
.PP
Definition at line 529 of file CommonRules\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
