.TH "Csla.Test.Serialization.SerializationTests" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.Serialization.SerializationTests
.SH SYNOPSIS
.br
.PP
.PP
Inherits TestBase\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBCorrectDefaultSerializer\fP ()"
.br
.ti -1c
.RI "void \fBUseMobileFormatter\fP ()"
.br
.ti -1c
.RI "void \fBUseBinaryFormatter\fP ()"
.br
.ti -1c
.RI "void \fBUseCustomFormatter\fP ()"
.br
.ti -1c
.RI "void \fBSerializeDataPortalException\fP ()"
.br
.ti -1c
.RI "void \fBCorrectDefaultSerializer\fP ()"
.br
.ti -1c
.RI "void \fBTestWithoutSerializableHandler\fP ()"
.br
.ti -1c
.RI "void \fBClone\fP ()"
.br
.ti -1c
.RI "void \fBSerializableEvents\fP ()"
.br
.ti -1c
.RI "void \fBTestSerializableEventsActionFails\fP ()"
.br
.ti -1c
.RI "void \fBTestSerializableEventsActionSucceeds\fP ()"
.br
.ti -1c
.RI "async Task \fBTestValidationRulesAfterSerialization\fP ()"
.br
.ti -1c
.RI "void \fBTestSerializationCslaBinaryReaderWriterList\fP ()"
.br
.ti -1c
.RI "void \fBTestSerializationCslaBinaryReaderWriter\fP ()"
.br
.ti -1c
.RI "void \fBTestAuthorizationRulesAfterSerialization\fP ()"
.br
.ti -1c
.RI "void \fBDCClone\fP ()"
.br
.ti -1c
.RI "void \fBDCEditLevels\fP ()"
.br
.ti -1c
.RI "void \fBAsyncLoadManagerSerializationTest\fP ()"
.br
.ti -1c
.RI "void \fBSerializeCommand\fP ()"
.br
.ti -1c
.RI "void \fBCommandOverDataPortal\fP ()"
.br
.ti -1c
.RI "void \fBUseCustomSerializationFormatter\fP ()"
.br
.ti -1c
.RI "void \fBUseNetDataContractSerializer\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBPublicStaticOnIsDirtyChanged\fP (object sender, PropertyChangedEventArgs e)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 26 of file SerializationTests\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Csla\&.Test\&.Serialization\&.SerializationTests\&.AsyncLoadManagerSerializationTest ()"

.PP
Definition at line 503 of file SerializationTests\&.cs\&.
.SS "void Csla\&.Test\&.Serialization\&.SerializationTests\&.Clone ()"

.PP
Definition at line 107 of file SerializationTests\&.cs\&.
.SS "void Csla\&.Test\&.Serialization\&.SerializationTests\&.CommandOverDataPortal ()"

.PP
Definition at line 544 of file SerializationTests\&.cs\&.
.SS "void Csla\&.Test\&.Serialization\&.SerializationTests\&.CorrectDefaultSerializer ()"

.PP
Definition at line 29 of file SerializationTests\&.cs\&.
.SS "void Csla\&.Test\&.Serialization\&.SerializationTests\&.CorrectDefaultSerializer ()"

.PP
Definition at line 75 of file SerializationTests\&.cs\&.
.SS "void Csla\&.Test\&.Serialization\&.SerializationTests\&.DCClone ()"

.PP
Definition at line 463 of file SerializationTests\&.cs\&.
.SS "void Csla\&.Test\&.Serialization\&.SerializationTests\&.DCEditLevels ()"

.PP
Definition at line 484 of file SerializationTests\&.cs\&.
.SS "static void Csla\&.Test\&.Serialization\&.SerializationTests\&.PublicStaticOnIsDirtyChanged (object sender, PropertyChangedEventArgs e)\fC [static]\fP"

.PP
Definition at line 455 of file SerializationTests\&.cs\&.
.SS "void Csla\&.Test\&.Serialization\&.SerializationTests\&.SerializableEvents ()"

.PP
Definition at line 123 of file SerializationTests\&.cs\&.
.SS "void Csla\&.Test\&.Serialization\&.SerializationTests\&.SerializeCommand ()"

.PP
Definition at line 519 of file SerializationTests\&.cs\&.
.SS "void Csla\&.Test\&.Serialization\&.SerializationTests\&.SerializeDataPortalException ()"

.PP
Definition at line 66 of file SerializationTests\&.cs\&.
.SS "void Csla\&.Test\&.Serialization\&.SerializationTests\&.TestAuthorizationRulesAfterSerialization ()"

.PP
Definition at line 390 of file SerializationTests\&.cs\&.
.SS "void Csla\&.Test\&.Serialization\&.SerializationTests\&.TestSerializableEventsActionFails ()"

.PP
Definition at line 205 of file SerializationTests\&.cs\&.
.SS "void Csla\&.Test\&.Serialization\&.SerializationTests\&.TestSerializableEventsActionSucceeds ()"

.PP
Definition at line 226 of file SerializationTests\&.cs\&.
.SS "void Csla\&.Test\&.Serialization\&.SerializationTests\&.TestSerializationCslaBinaryReaderWriter ()"

.PP
Definition at line 324 of file SerializationTests\&.cs\&.
.SS "void Csla\&.Test\&.Serialization\&.SerializationTests\&.TestSerializationCslaBinaryReaderWriterList ()"

.PP
Definition at line 266 of file SerializationTests\&.cs\&.
.SS "async Task Csla\&.Test\&.Serialization\&.SerializationTests\&.TestValidationRulesAfterSerialization ()"

.PP
Definition at line 247 of file SerializationTests\&.cs\&.
.SS "void Csla\&.Test\&.Serialization\&.SerializationTests\&.TestWithoutSerializableHandler ()"

.PP
Definition at line 82 of file SerializationTests\&.cs\&.
.SS "void Csla\&.Test\&.Serialization\&.SerializationTests\&.UseBinaryFormatter ()"

.PP
Definition at line 53 of file SerializationTests\&.cs\&.
.SS "void Csla\&.Test\&.Serialization\&.SerializationTests\&.UseCustomFormatter ()"

.PP
Definition at line 70 of file SerializationTests\&.cs\&.
.SS "void Csla\&.Test\&.Serialization\&.SerializationTests\&.UseCustomSerializationFormatter ()"

.PP
Definition at line 565 of file SerializationTests\&.cs\&.
.SS "void Csla\&.Test\&.Serialization\&.SerializationTests\&.UseMobileFormatter ()"

.PP
Definition at line 36 of file SerializationTests\&.cs\&.
.SS "void Csla\&.Test\&.Serialization\&.SerializationTests\&.UseNetDataContractSerializer ()"

.PP
Definition at line 582 of file SerializationTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
