.TH "cslalighttest.Stereotypes" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cslalighttest.Stereotypes
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBEditableChildTestsLocal\fP"
.br
.ti -1c
.RI "class \fBEditableChildTestsRemote\fP"
.br
.ti -1c
.RI "class \fBEditableRootTests\fP"
.br
.ti -1c
.RI "class \fBReadOnlyListTestsLocalAndRemote\fP"
.br
.ti -1c
.RI "class \fBTestCriteria\fP"
.br
.ti -1c
.RI "class \fBCustomCriteria\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
