.TH "Csla.Blazor.ViewModel< T >" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Blazor.ViewModel< T > \- Base type for creating your own viewmodel\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBViewModel\fP (\fBIDataPortal\fP< T > dataPortal)"
.br
.RI "Creates an instance of the type "
.ti -1c
.RI "async Task< T > \fBRefreshAsync\fP (Func< Task< T >> factory)"
.br
.RI "Refresh the Model "
.ti -1c
.RI "async Task \fBSaveAsync\fP ()"
.br
.RI "Saves the Model "
.ti -1c
.RI "\fBIPropertyInfo\fP \fBGetPropertyInfo< P >\fP (Expression< Func< P >> property)"
.br
.RI "Get a \fBPropertyInfo\fP object for a property\&. \fBPropertyInfo\fP provides access to the metastate of the property\&. "
.ti -1c
.RI "\fBIPropertyInfo\fP \fBGetPropertyInfo< P >\fP (Expression< Func< P >> property, string id)"
.br
.RI "Get a \fBPropertyInfo\fP object for a property\&. \fBPropertyInfo\fP provides access to the metastate of the property\&. "
.ti -1c
.RI "\fBIPropertyInfo\fP \fBGetPropertyInfo\fP (string propertyName)"
.br
.RI "Get a \fBPropertyInfo\fP object for a property of the Model\&. \fBPropertyInfo\fP provides access to the metastate of the property\&. "
.ti -1c
.RI "\fBIPropertyInfo\fP \fBGetPropertyInfo\fP (string propertyName, string id)"
.br
.RI "Get a \fBPropertyInfo\fP object for a property of the Model\&. \fBPropertyInfo\fP provides access to the metastate of the property\&. "
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBCanCreateObject\fP ()"
.br
.RI "Gets a value indicating whether the current user is authorized to create an instance of the business domain type "
.ti -1c
.RI "static bool \fBCanGetObject\fP ()"
.br
.RI "Gets a value indicating whether the current user is authorized to retrieve an instance of the business domain type "
.ti -1c
.RI "static bool \fBCanEditObject\fP ()"
.br
.RI "Gets a value indicating whether the current user is authorized to edit/save an instance of the business domain type "
.ti -1c
.RI "static bool \fBCanDeleteObject\fP ()"
.br
.RI "Gets a value indicating whether the current user is authorized to delete an instance of the business domain type "
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBOnModelChanging\fP (T oldValue, T newValue)"
.br
.RI "Raises the ModelChanging event "
.ti -1c
.RI "virtual void \fBOnModelChanged\fP ()"
.br
.RI "Raises the ModelChanged event "
.ti -1c
.RI "virtual void \fBOnModelPropertyChanged\fP (string propertyName)"
.br
.RI "Raises the ModelPropertyChanged event "
.ti -1c
.RI "virtual async Task< T > \fBDoSaveAsync\fP ()"
.br
.RI "Override to provide custom Model save behavior "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "T \fBModel\fP\fC [get, set]\fP"
.br
.RI "Gets or sets the Model object\&. "
.ti -1c
.RI "string \fBViewModelErrorText\fP\fC [get, protected set]\fP"
.br
.RI "Gets any error text generated by refresh or save operations "
.ti -1c
.RI "virtual string \fBModelErrorText\fP\fC [get]\fP"
.br
.RI "Gets the first validation error message from the Model "
.ti -1c
.RI "Exception \fBException\fP\fC [get]\fP"
.br
.RI "Gets the last exception caught by the viewmodel during refresh or save operations\&. "
.in -1c
.SS "Events"

.in +1c
.ti -1c
.RI "Action \fBSaved\fP"
.br
.RI "Event raised after Model has been saved "
.ti -1c
.RI "Action< T, T > \fBModelChanging\fP"
.br
.RI "Event raised when Model is changing "
.ti -1c
.RI "Action \fBModelChanged\fP"
.br
.RI "Event raised when Model has changed "
.ti -1c
.RI "PropertyChangedEventHandler \fBModelPropertyChanged\fP"
.br
.RI "Event raised when the Model object raises its PropertyChanged event "
.in -1c
.SH "Detailed Description"
.PP 
Base type for creating your own viewmodel\&. 


.PP
Definition at line 22 of file Csla\&.Blazor/ViewModel\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBCsla\&.Blazor\&.ViewModel\fP< T >\&.\fBViewModel\fP (\fBIDataPortal\fP< T > dataPortal)"

.PP
Creates an instance of the type 
.PP
Definition at line 79 of file Csla\&.Blazor/ViewModel\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "static bool \fBCsla\&.Blazor\&.ViewModel\fP< T >\&.CanCreateObject ()\fC [static]\fP"

.PP
Gets a value indicating whether the current user is authorized to create an instance of the business domain type 
.PP
\fBReturns\fP
.RS 4

.RE
.PP

.PP
Definition at line 283 of file Csla\&.Blazor/ViewModel\&.cs\&.
.SS "static bool \fBCsla\&.Blazor\&.ViewModel\fP< T >\&.CanDeleteObject ()\fC [static]\fP"

.PP
Gets a value indicating whether the current user is authorized to delete an instance of the business domain type 
.PP
\fBReturns\fP
.RS 4

.RE
.PP

.PP
Definition at line 316 of file Csla\&.Blazor/ViewModel\&.cs\&.
.SS "static bool \fBCsla\&.Blazor\&.ViewModel\fP< T >\&.CanEditObject ()\fC [static]\fP"

.PP
Gets a value indicating whether the current user is authorized to edit/save an instance of the business domain type 
.PP
\fBReturns\fP
.RS 4

.RE
.PP

.PP
Definition at line 305 of file Csla\&.Blazor/ViewModel\&.cs\&.
.SS "static bool \fBCsla\&.Blazor\&.ViewModel\fP< T >\&.CanGetObject ()\fC [static]\fP"

.PP
Gets a value indicating whether the current user is authorized to retrieve an instance of the business domain type 
.PP
\fBReturns\fP
.RS 4

.RE
.PP

.PP
Definition at line 294 of file Csla\&.Blazor/ViewModel\&.cs\&.
.SS "virtual async Task<T> \fBCsla\&.Blazor\&.ViewModel\fP< T >\&.DoSaveAsync ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Override to provide custom Model save behavior 
.PP
\fBReturns\fP
.RS 4

.RE
.PP

.PP
Definition at line 140 of file Csla\&.Blazor/ViewModel\&.cs\&.
.SS "\fBIPropertyInfo\fP \fBCsla\&.Blazor\&.ViewModel\fP< T >\&.GetPropertyInfo (string propertyName)"

.PP
Get a \fBPropertyInfo\fP object for a property of the Model\&. \fBPropertyInfo\fP provides access to the metastate of the property\&. 
.PP
\fBParameters\fP
.RS 4
\fIpropertyName\fP Property name
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
Definition at line 214 of file Csla\&.Blazor/ViewModel\&.cs\&.
.SS "\fBIPropertyInfo\fP \fBCsla\&.Blazor\&.ViewModel\fP< T >\&.GetPropertyInfo (string propertyName, string id)"

.PP
Get a \fBPropertyInfo\fP object for a property of the Model\&. \fBPropertyInfo\fP provides access to the metastate of the property\&. 
.PP
\fBParameters\fP
.RS 4
\fIpropertyName\fP Property name
.br
\fIid\fP Unique identifier for property in list or array
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
Definition at line 228 of file Csla\&.Blazor/ViewModel\&.cs\&.
.SS "\fBIPropertyInfo\fP \fBCsla\&.Blazor\&.ViewModel\fP< T >\&.\fBGetPropertyInfo\fP< P > (Expression< Func< P >> property)"

.PP
Get a \fBPropertyInfo\fP object for a property\&. \fBPropertyInfo\fP provides access to the metastate of the property\&. 
.PP
\fBParameters\fP
.RS 4
\fIproperty\fP Property expression
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
Definition at line 179 of file Csla\&.Blazor/ViewModel\&.cs\&.
.SS "\fBIPropertyInfo\fP \fBCsla\&.Blazor\&.ViewModel\fP< T >\&.\fBGetPropertyInfo\fP< P > (Expression< Func< P >> property, string id)"

.PP
Get a \fBPropertyInfo\fP object for a property\&. \fBPropertyInfo\fP provides access to the metastate of the property\&. 
.PP
\fBParameters\fP
.RS 4
\fIproperty\fP Property expression
.br
\fIid\fP Unique identifier for property in list or array
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
Definition at line 197 of file Csla\&.Blazor/ViewModel\&.cs\&.
.SS "virtual void \fBCsla\&.Blazor\&.ViewModel\fP< T >\&.OnModelChanged ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Raises the ModelChanged event 
.PP
Definition at line 62 of file Csla\&.Blazor/ViewModel\&.cs\&.
.SS "virtual void \fBCsla\&.Blazor\&.ViewModel\fP< T >\&.OnModelChanging (T oldValue, T newValue)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Raises the ModelChanging event 
.PP
\fBParameters\fP
.RS 4
\fIoldValue\fP Old Model value
.br
\fInewValue\fP New Model value
.RE
.PP

.PP
Definition at line 49 of file Csla\&.Blazor/ViewModel\&.cs\&.
.SS "virtual void \fBCsla\&.Blazor\&.ViewModel\fP< T >\&.OnModelPropertyChanged (string propertyName)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Raises the ModelPropertyChanged event 
.PP
\fBParameters\fP
.RS 4
\fIpropertyName\fP 
.RE
.PP

.PP
Definition at line 71 of file Csla\&.Blazor/ViewModel\&.cs\&.
.SS "async Task<T> \fBCsla\&.Blazor\&.ViewModel\fP< T >\&.RefreshAsync (Func< Task< T >> factory)"

.PP
Refresh the Model 
.PP
\fBParameters\fP
.RS 4
\fIfactory\fP Async data portal or factory method
.RE
.PP

.PP
Definition at line 88 of file Csla\&.Blazor/ViewModel\&.cs\&.
.SS "async Task \fBCsla\&.Blazor\&.ViewModel\fP< T >\&.SaveAsync ()"

.PP
Saves the Model 
.PP
\fBReturns\fP
.RS 4

.RE
.PP

.PP
Definition at line 115 of file Csla\&.Blazor/ViewModel\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "Exception \fBCsla\&.Blazor\&.ViewModel\fP< T >\&.Exception\fC [get]\fP"

.PP
Gets the last exception caught by the viewmodel during refresh or save operations\&. 
.PP
Definition at line 275 of file Csla\&.Blazor/ViewModel\&.cs\&.
.SS "T \fBCsla\&.Blazor\&.ViewModel\fP< T >\&.Model\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the Model object\&. 
.PP
Definition at line 157 of file Csla\&.Blazor/ViewModel\&.cs\&.
.SS "virtual string \fBCsla\&.Blazor\&.ViewModel\fP< T >\&.ModelErrorText\fC [get]\fP, \fC [protected]\fP"

.PP
Gets the first validation error message from the Model 
.PP
Definition at line 258 of file Csla\&.Blazor/ViewModel\&.cs\&.
.SS "string \fBCsla\&.Blazor\&.ViewModel\fP< T >\&.ViewModelErrorText\fC [get]\fP, \fC [protected set]\fP"

.PP
Gets any error text generated by refresh or save operations 
.PP
Definition at line 252 of file Csla\&.Blazor/ViewModel\&.cs\&.
.SH "Event Documentation"
.PP 
.SS "Action \fBCsla\&.Blazor\&.ViewModel\fP< T >\&.ModelChanged"

.PP
Event raised when Model has changed 
.PP
Definition at line 37 of file Csla\&.Blazor/ViewModel\&.cs\&.
.SS "Action<T, T> \fBCsla\&.Blazor\&.ViewModel\fP< T >\&.ModelChanging"

.PP
Event raised when Model is changing 
.PP
Definition at line 33 of file Csla\&.Blazor/ViewModel\&.cs\&.
.SS "PropertyChangedEventHandler \fBCsla\&.Blazor\&.ViewModel\fP< T >\&.ModelPropertyChanged"

.PP
Event raised when the Model object raises its PropertyChanged event 
.PP
Definition at line 42 of file Csla\&.Blazor/ViewModel\&.cs\&.
.SS "Action \fBCsla\&.Blazor\&.ViewModel\fP< T >\&.Saved"

.PP
Event raised after Model has been saved 
.PP
Definition at line 29 of file Csla\&.Blazor/ViewModel\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
