.TH "Csla.Rules.BrokenRulesTree" 3 "Thu Jul 22 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Rules.BrokenRulesTree \- Holds a list of broken rules tree list  

.SH SYNOPSIS
.br
.PP
.PP
Inherits List< BrokenRulesNode >\&.
.SH "Detailed Description"
.PP 
Holds a list of broken rules tree list 


.PP
Definition at line 18 of file BrokenRulesTree\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
