.TH "Csla.Test.SortedBindingList.MyChild" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.SortedBindingList.MyChild
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.BusinessBase< MyChild >\fP\&.
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static readonly \fBPropertyInfo\fP< string > \fBNameProperty\fP = RegisterProperty<string>(p => p\&.Name)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBName\fP\fC [get, set]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 231 of file SortedBindingListTests\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "readonly \fBPropertyInfo\fP<string> Csla\&.Test\&.SortedBindingList\&.MyChild\&.NameProperty = RegisterProperty<string>(p => p\&.Name)\fC [static]\fP"

.PP
Definition at line 234 of file SortedBindingListTests\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "string Csla\&.Test\&.SortedBindingList\&.MyChild\&.Name\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 235 of file SortedBindingListTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
