.TH "Csla.Test.ValidationRules.AsyncRuleRoot" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.ValidationRules.AsyncRuleRoot
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.BusinessBase< AsyncRuleRoot >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAsyncRuleRoot\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBAsyncRuleRoot\fP \fBNewRoot\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static readonly \fBPropertyInfo\fP< string > \fBCustomerNumberProperty\fP = RegisterProperty<string>(c => c\&.CustomerNumber)"
.br
.ti -1c
.RI "static readonly \fBPropertyInfo\fP< string > \fBCustomerNameProperty\fP = RegisterProperty<string>(c => c\&.CustomerName)"
.br
.ti -1c
.RI "static readonly \fBPropertyInfo\fP< string > \fBAsyncAwaitProperty\fP = RegisterProperty<string>(c => c\&.AsyncAwait)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBAddBusinessRules\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBCustomerNumber\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBCustomerName\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBAsyncAwait\fP\fC [get, set]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 13 of file AsyncRuleRoot\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Csla\&.Test\&.ValidationRules\&.AsyncRuleRoot\&.AsyncRuleRoot ()"

.PP
Definition at line 45 of file AsyncRuleRoot\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override void Csla\&.Test\&.ValidationRules\&.AsyncRuleRoot\&.AddBusinessRules ()\fC [protected]\fP"

.PP
Definition at line 50 of file AsyncRuleRoot\&.cs\&.
.SS "static \fBAsyncRuleRoot\fP Csla\&.Test\&.ValidationRules\&.AsyncRuleRoot\&.NewRoot ()\fC [static]\fP"

.PP
Definition at line 40 of file AsyncRuleRoot\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "readonly \fBPropertyInfo\fP<string> Csla\&.Test\&.ValidationRules\&.AsyncRuleRoot\&.AsyncAwaitProperty = RegisterProperty<string>(c => c\&.AsyncAwait)\fC [static]\fP"

.PP
Definition at line 33 of file AsyncRuleRoot\&.cs\&.
.SS "readonly \fBPropertyInfo\fP<string> Csla\&.Test\&.ValidationRules\&.AsyncRuleRoot\&.CustomerNameProperty = RegisterProperty<string>(c => c\&.CustomerName)\fC [static]\fP"

.PP
Definition at line 24 of file AsyncRuleRoot\&.cs\&.
.SS "readonly \fBPropertyInfo\fP<string> Csla\&.Test\&.ValidationRules\&.AsyncRuleRoot\&.CustomerNumberProperty = RegisterProperty<string>(c => c\&.CustomerNumber)\fC [static]\fP"

.PP
Definition at line 15 of file AsyncRuleRoot\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "string Csla\&.Test\&.ValidationRules\&.AsyncRuleRoot\&.AsyncAwait\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 34 of file AsyncRuleRoot\&.cs\&.
.SS "string Csla\&.Test\&.ValidationRules\&.AsyncRuleRoot\&.CustomerName\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 26 of file AsyncRuleRoot\&.cs\&.
.SS "string Csla\&.Test\&.ValidationRules\&.AsyncRuleRoot\&.CustomerNumber\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 17 of file AsyncRuleRoot\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
