.TH "Csla.Analyzers.Tests.FindBusinessObjectCreationAnalyzerTests" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Analyzers.Tests.FindBusinessObjectCreationAnalyzerTests
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBVerifySupportedDiagnostics\fP ()"
.br
.ti -1c
.RI "async Task \fBAnalyzeWhenConstructorIsNotOnBusinessObject\fP ()"
.br
.ti -1c
.RI "async Task \fBAnalyzeWhenConstructorIsOnBusinessObjectWithinObjectFactory\fP ()"
.br
.ti -1c
.RI "async Task \fBAnalyzeWhenConstructorIsOnBusinessObjectOutsideOfObjectFactory\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 10 of file FindBusinessObjectCreationAnalyzerTests\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "async Task Csla\&.Analyzers\&.Tests\&.FindBusinessObjectCreationAnalyzerTests\&.AnalyzeWhenConstructorIsNotOnBusinessObject ()"

.PP
Definition at line 36 of file FindBusinessObjectCreationAnalyzerTests\&.cs\&.
.SS "async Task Csla\&.Analyzers\&.Tests\&.FindBusinessObjectCreationAnalyzerTests\&.AnalyzeWhenConstructorIsOnBusinessObjectOutsideOfObjectFactory ()"

.PP
Definition at line 73 of file FindBusinessObjectCreationAnalyzerTests\&.cs\&.
.SS "async Task Csla\&.Analyzers\&.Tests\&.FindBusinessObjectCreationAnalyzerTests\&.AnalyzeWhenConstructorIsOnBusinessObjectWithinObjectFactory ()"

.PP
Definition at line 53 of file FindBusinessObjectCreationAnalyzerTests\&.cs\&.
.SS "void Csla\&.Analyzers\&.Tests\&.FindBusinessObjectCreationAnalyzerTests\&.VerifySupportedDiagnostics ()"

.PP
Definition at line 13 of file FindBusinessObjectCreationAnalyzerTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
