.TH "Csla.Analyzers.IntegrationTests.CallingMethods" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Analyzers.IntegrationTests.CallingMethods
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCallingMethods\fP \fBSave\fP ()"
.br
.ti -1c
.RI "async Task< \fBCallingMethods\fP > \fBSaveAsync\fP ()"
.br
.ti -1c
.RI "async Task \fBUsedByCallingMethodsSaveAsync\fP ()"
.br
.ti -1c
.RI "void \fBUsedByCallingMethodsSave\fP ()"
.br
.ti -1c
.RI "\fBUsedByCallingMethods\fP \fBReturnsUser\fP ()"
.br
.ti -1c
.RI "async Task< \fBUsedByCallingMethods\fP > \fBReturnsUserAsync\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 11 of file IgnoringReturnValuesTests\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBUsedByCallingMethods\fP Csla\&.Analyzers\&.IntegrationTests\&.CallingMethods\&.ReturnsUser ()"

.PP
Definition at line 83 of file IgnoringReturnValuesTests\&.cs\&.
.SS "async Task<\fBUsedByCallingMethods\fP> Csla\&.Analyzers\&.IntegrationTests\&.CallingMethods\&.ReturnsUserAsync ()"

.PP
Definition at line 89 of file IgnoringReturnValuesTests\&.cs\&.
.SS "\fBCallingMethods\fP Csla\&.Analyzers\&.IntegrationTests\&.CallingMethods\&.Save ()"

.PP
Definition at line 15 of file IgnoringReturnValuesTests\&.cs\&.
.SS "async Task<\fBCallingMethods\fP> Csla\&.Analyzers\&.IntegrationTests\&.CallingMethods\&.SaveAsync ()"

.PP
Definition at line 17 of file IgnoringReturnValuesTests\&.cs\&.
.SS "void Csla\&.Analyzers\&.IntegrationTests\&.CallingMethods\&.UsedByCallingMethodsSave ()"

.PP
Definition at line 40 of file IgnoringReturnValuesTests\&.cs\&.
.SS "async Task Csla\&.Analyzers\&.IntegrationTests\&.CallingMethods\&.UsedByCallingMethodsSaveAsync ()"

.PP
Definition at line 19 of file IgnoringReturnValuesTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
