.TH "Csla.Test.Serialization.TestEventSink" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.Serialization.TestEventSink
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBReg\fP (\fBCore\&.BusinessBase\fP obj)"
.br
.ti -1c
.RI "void \fBOnIsDirtyChanged\fP (object sender, System\&.ComponentModel\&.PropertyChangedEventArgs e)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 15 of file TestEventSink\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Csla\&.Test\&.Serialization\&.TestEventSink\&.OnIsDirtyChanged (object sender, System\&.ComponentModel\&.PropertyChangedEventArgs e)"

.PP
Definition at line 32 of file TestEventSink\&.cs\&.
.SS "void Csla\&.Test\&.Serialization\&.TestEventSink\&.Reg (\fBCore\&.BusinessBase\fP obj)"

.PP
Definition at line 17 of file TestEventSink\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
