.TH "Csla.Test.ValidationRules.TwoPropertyRules" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.ValidationRules.TwoPropertyRules
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.BusinessBase< TwoPropertyRules >\fP\&.
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBPropertyInfo\fP< string > \fBValue1Property\fP = RegisterProperty<string>(c => c\&.Value1)"
.br
.ti -1c
.RI "static \fBPropertyInfo\fP< string > \fBValue2Property\fP = RegisterProperty<string>(c => c\&.Value2)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBAddBusinessRules\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBValue1\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBValue2\fP\fC [get, set]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 656 of file ValidationTests\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override void Csla\&.Test\&.ValidationRules\&.TwoPropertyRules\&.AddBusinessRules ()\fC [protected]\fP"

.PP
Definition at line 672 of file ValidationTests\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBPropertyInfo\fP<string> Csla\&.Test\&.ValidationRules\&.TwoPropertyRules\&.Value1Property = RegisterProperty<string>(c => c\&.Value1)\fC [static]\fP"

.PP
Definition at line 658 of file ValidationTests\&.cs\&.
.SS "\fBPropertyInfo\fP<string> Csla\&.Test\&.ValidationRules\&.TwoPropertyRules\&.Value2Property = RegisterProperty<string>(c => c\&.Value2)\fC [static]\fP"

.PP
Definition at line 665 of file ValidationTests\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "string Csla\&.Test\&.ValidationRules\&.TwoPropertyRules\&.Value1\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 659 of file ValidationTests\&.cs\&.
.SS "string Csla\&.Test\&.ValidationRules\&.TwoPropertyRules\&.Value2\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 666 of file ValidationTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
