.TH "Csla.Test.Silverlight.PropertyGetSet.AbstractGetSet< T >" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.Silverlight.PropertyGetSet.AbstractGetSet< T >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.BusinessBase< T >\fP\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBAbstractGetSet\fP ()"
.br
.ti -1c
.RI "override void \fBOnDeserialized\fP (System\&.Runtime\&.Serialization\&.StreamingContext context)"
.br
.RI "This method is called on a newly deserialized object after deserialization is complete\&. "
.in -1c
.SS "Static Protected Attributes"

.in +1c
.ti -1c
.RI "static \fBPropertyInfo\fP< int > \fBIdProperty\fP = RegisterProperty<int>(c => c\&.Id, 'Id')"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBId\fP\fC [get, set]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
\fBType Constraints\fP
.TP
\fIT\fP : \fI\fBAbstractGetSet\fP<T>\fP
.PP
Definition at line 16 of file AbstractGetSet\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBCsla\&.Test\&.Silverlight\&.PropertyGetSet\&.AbstractGetSet\fP< T >\&.\fBAbstractGetSet\fP ()\fC [protected]\fP"

.PP
Definition at line 29 of file AbstractGetSet\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override void \fBCsla\&.Test\&.Silverlight\&.PropertyGetSet\&.AbstractGetSet\fP< T >\&.OnDeserialized (System\&.Runtime\&.Serialization\&.StreamingContext context)\fC [protected]\fP, \fC [virtual]\fP"

.PP
This method is called on a newly deserialized object after deserialization is complete\&. 
.PP
\fBParameters\fP
.RS 4
\fIcontext\fP \fBSerialization\fP context object\&.
.RE
.PP

.PP
Reimplemented from \fBCsla\&.Core\&.BusinessBase\fP\&.
.PP
Definition at line 34 of file AbstractGetSet\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBPropertyInfo\fP<int> \fBCsla\&.Test\&.Silverlight\&.PropertyGetSet\&.AbstractGetSet\fP< T >\&.IdProperty = RegisterProperty<int>(c => c\&.Id, 'Id')\fC [static]\fP, \fC [protected]\fP"

.PP
Definition at line 18 of file AbstractGetSet\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "int \fBCsla\&.Test\&.Silverlight\&.PropertyGetSet\&.AbstractGetSet\fP< T >\&.Id\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 19 of file AbstractGetSet\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
