.TH "Csla.Test.DataPortal.ServiceProviderInvocationTests" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.DataPortal.ServiceProviderInvocationTests
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBInitialize\fP ()"
.br
.ti -1c
.RI "async Task \fBNoServiceProvider\fP ()"
.br
.ti -1c
.RI "async Task \fBWithServiceProvider\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 29 of file ServiceProviderInvocationTests\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Csla\&.Test\&.DataPortal\&.ServiceProviderInvocationTests\&.Initialize ()"

.PP
Definition at line 32 of file ServiceProviderInvocationTests\&.cs\&.
.SS "async Task Csla\&.Test\&.DataPortal\&.ServiceProviderInvocationTests\&.NoServiceProvider ()"

.PP
Definition at line 39 of file ServiceProviderInvocationTests\&.cs\&.
.SS "async Task Csla\&.Test\&.DataPortal\&.ServiceProviderInvocationTests\&.WithServiceProvider ()"

.PP
Definition at line 48 of file ServiceProviderInvocationTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
