.TH "Csla.Configuration.ConnectionStringSettingsCollection" 3 "Thu Jul 22 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Configuration.ConnectionStringSettingsCollection \- Collection of connection strings\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Dictionary< string, ConnectionStringSettings >\&.
.SH "Detailed Description"
.PP 
Collection of connection strings\&. 


.PP
Definition at line 15 of file ConnectionStringSettingsCollection\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
