.TH "Csla.Testing.Business.EditableRootListTests.RootSingleItemsList.FetchCriteria" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Testing.Business.EditableRootListTests.RootSingleItemsList.FetchCriteria
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.CriteriaBase< FetchCriteria >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFetchCriteria\fP ()"
.br
.ti -1c
.RI "\fBFetchCriteria\fP (int startId, int endId)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBPropertyInfo\fP< int > \fBStartIDProperty\fP = RegisterProperty<int>(c => c\&.StartID)"
.br
.ti -1c
.RI "static \fBPropertyInfo\fP< int > \fBEndIDProperty\fP = RegisterProperty<int>(c => c\&.EndID)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBStartID\fP\fC [get]\fP"
.br
.ti -1c
.RI "int \fBEndID\fP\fC [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 26 of file RootSingleItemsList\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Csla\&.Testing\&.Business\&.EditableRootListTests\&.RootSingleItemsList\&.FetchCriteria\&.FetchCriteria ()"

.PP
Definition at line 28 of file RootSingleItemsList\&.cs\&.
.SS "Csla\&.Testing\&.Business\&.EditableRootListTests\&.RootSingleItemsList\&.FetchCriteria\&.FetchCriteria (int startId, int endId)"

.PP
Definition at line 30 of file RootSingleItemsList\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBPropertyInfo\fP<int> Csla\&.Testing\&.Business\&.EditableRootListTests\&.RootSingleItemsList\&.FetchCriteria\&.EndIDProperty = RegisterProperty<int>(c => c\&.EndID)\fC [static]\fP"

.PP
Definition at line 43 of file RootSingleItemsList\&.cs\&.
.SS "\fBPropertyInfo\fP<int> Csla\&.Testing\&.Business\&.EditableRootListTests\&.RootSingleItemsList\&.FetchCriteria\&.StartIDProperty = RegisterProperty<int>(c => c\&.StartID)\fC [static]\fP"

.PP
Definition at line 36 of file RootSingleItemsList\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "int Csla\&.Testing\&.Business\&.EditableRootListTests\&.RootSingleItemsList\&.FetchCriteria\&.EndID\fC [get]\fP"

.PP
Definition at line 44 of file RootSingleItemsList\&.cs\&.
.SS "int Csla\&.Testing\&.Business\&.EditableRootListTests\&.RootSingleItemsList\&.FetchCriteria\&.StartID\fC [get]\fP"

.PP
Definition at line 37 of file RootSingleItemsList\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
