.TH "Csla.Server.Hosts.Mobile.UpdateRequest" 3 "Thu Jul 22 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Server.Hosts.Mobile.UpdateRequest \- Message sent to the WCF data portal\&.  

.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "byte[] \fBObjectData\fP\fC [get, set]\fP"
.br
.RI "Serialized object data\&. "
.ti -1c
.RI "byte[] \fBPrincipal\fP\fC [get, set]\fP"
.br
.RI "Serialized principal object\&. "
.ti -1c
.RI "byte[] \fBGlobalContext\fP\fC [get, set]\fP"
.br
.RI "Serialized global context object\&. "
.ti -1c
.RI "byte[] \fBClientContext\fP\fC [get, set]\fP"
.br
.RI "Serialized client context object\&. "
.ti -1c
.RI "string \fBClientCulture\fP\fC [get, set]\fP"
.br
.RI "Serialized client culture\&. "
.ti -1c
.RI "string \fBClientUICulture\fP\fC [get, set]\fP"
.br
.RI "Serialized client UI culture\&. "
.in -1c
.SH "Detailed Description"
.PP 
Message sent to the WCF data portal\&. 


.PP
Definition at line 18 of file Mobile/UpdateRequest\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "byte [] Csla\&.Server\&.Hosts\&.Mobile\&.UpdateRequest\&.ClientContext\fC [get]\fP, \fC [set]\fP"

.PP
Serialized client context object\&. 
.PP
Definition at line 42 of file Mobile/UpdateRequest\&.cs\&.
.SS "string Csla\&.Server\&.Hosts\&.Mobile\&.UpdateRequest\&.ClientCulture\fC [get]\fP, \fC [set]\fP"

.PP
Serialized client culture\&. The client culture\&.
.PP
Definition at line 49 of file Mobile/UpdateRequest\&.cs\&.
.SS "string Csla\&.Server\&.Hosts\&.Mobile\&.UpdateRequest\&.ClientUICulture\fC [get]\fP, \fC [set]\fP"

.PP
Serialized client UI culture\&. The client UI culture\&.
.PP
Definition at line 56 of file Mobile/UpdateRequest\&.cs\&.
.SS "byte [] Csla\&.Server\&.Hosts\&.Mobile\&.UpdateRequest\&.GlobalContext\fC [get]\fP, \fC [set]\fP"

.PP
Serialized global context object\&. 
.PP
Definition at line 36 of file Mobile/UpdateRequest\&.cs\&.
.SS "byte [] Csla\&.Server\&.Hosts\&.Mobile\&.UpdateRequest\&.ObjectData\fC [get]\fP, \fC [set]\fP"

.PP
Serialized object data\&. 
.PP
Definition at line 24 of file Mobile/UpdateRequest\&.cs\&.
.SS "byte [] Csla\&.Server\&.Hosts\&.Mobile\&.UpdateRequest\&.Principal\fC [get]\fP, \fC [set]\fP"

.PP
Serialized principal object\&. 
.PP
Definition at line 30 of file Mobile/UpdateRequest\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
