.TH "Csla.Test.PropertyGetSet.EditableGetSet" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.PropertyGetSet.EditableGetSet
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.Test\&.PropertyGetSet\&.EditableGetSetBase< EditableGetSet >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBLoadM02\fP (int value)"
.br
.ti -1c
.RI "void \fBLoadInternalAndPrivate\fP (string value)"
.br
.ti -1c
.RI "new void \fBMarkClean\fP ()"
.br
.ti -1c
.RI "\fBEditableGetSet\fP ()"
.br
.ti -1c
.RI "\fBEditableGetSet\fP (bool isChild)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBEditableGetSet\fP \fBGetObject\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static readonly \fBPropertyInfo\fP< string > \fBManagedStringFieldProperty\fP = RegisterProperty<string>(nameof(\fBManagedStringField\fP))"
.br
.ti -1c
.RI "static readonly \fBPropertyInfo\fP< string > \fB_m08Property\fP = RegisterProperty<string>(c => c\&.M08)"
.br
.ti -1c
.RI "static readonly \fBPropertyInfo\fP< string > \fB_m09Property\fP = RegisterProperty<string>(c => c\&.M09)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBDataPortal_Insert\fP ()"
.br
.ti -1c
.RI "void \fBDataPortal_Update\fP ()"
.br
.ti -1c
.RI "override void \fBOnGetState\fP (\fBSerializationInfo\fP info, \fBCsla\&.Core\&.StateMode\fP mode)"
.br
.ti -1c
.RI "override void \fBOnSetState\fP (\fBSerializationInfo\fP info, \fBCsla\&.Core\&.StateMode\fP mode)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBFieldBackedString\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBF02\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBF03\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBF04\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "bool \fBF05\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBF06\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBManagedStringField\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "bool \fBManagedStringFieldDirty\fP\fC [get]\fP"
.br
.ti -1c
.RI "int \fBM02\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBM03\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBM04\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "bool \fBM05\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "Guid \fBM06\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBM07\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBEditableGetSet\fP \fBManagedChild\fP\fC [get]\fP"
.br
.ti -1c
.RI "\fBChildList\fP \fBManagedChildList\fP\fC [get]\fP"
.br
.ti -1c
.RI "\fBChildList\fP \fBLazyChild\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "new int \fBEditLevel\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 22 of file EditableGetSet\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Csla\&.Test\&.PropertyGetSet\&.EditableGetSet\&.EditableGetSet ()"

.PP
Definition at line 195 of file EditableGetSet\&.cs\&.
.SS "Csla\&.Test\&.PropertyGetSet\&.EditableGetSet\&.EditableGetSet (bool isChild)"

.PP
Definition at line 201 of file EditableGetSet\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Csla\&.Test\&.PropertyGetSet\&.EditableGetSet\&.DataPortal_Insert ()\fC [protected]\fP"

.PP
Definition at line 226 of file EditableGetSet\&.cs\&.
.SS "void Csla\&.Test\&.PropertyGetSet\&.EditableGetSet\&.DataPortal_Update ()\fC [protected]\fP"

.PP
Definition at line 236 of file EditableGetSet\&.cs\&.
.SS "static \fBEditableGetSet\fP Csla\&.Test\&.PropertyGetSet\&.EditableGetSet\&.GetObject ()\fC [static]\fP"

.PP
Definition at line 212 of file EditableGetSet\&.cs\&.
.SS "void Csla\&.Test\&.PropertyGetSet\&.EditableGetSet\&.LoadInternalAndPrivate (string value)"

.PP
Definition at line 146 of file EditableGetSet\&.cs\&.
.SS "void Csla\&.Test\&.PropertyGetSet\&.EditableGetSet\&.LoadM02 (int value)"

.PP
Definition at line 91 of file EditableGetSet\&.cs\&.
.SS "new void Csla\&.Test\&.PropertyGetSet\&.EditableGetSet\&.MarkClean ()"

.PP
Definition at line 190 of file EditableGetSet\&.cs\&.
.SS "override void Csla\&.Test\&.PropertyGetSet\&.EditableGetSet\&.OnGetState (\fBSerializationInfo\fP info, \fBCsla\&.Core\&.StateMode\fP mode)\fC [protected]\fP"

.PP
Definition at line 255 of file EditableGetSet\&.cs\&.
.SS "override void Csla\&.Test\&.PropertyGetSet\&.EditableGetSet\&.OnSetState (\fBSerializationInfo\fP info, \fBCsla\&.Core\&.StateMode\fP mode)\fC [protected]\fP"

.PP
Definition at line 271 of file EditableGetSet\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "readonly \fBPropertyInfo\fP<string> Csla\&.Test\&.PropertyGetSet\&.EditableGetSet\&._m08Property = RegisterProperty<string>(c => c\&.M08)\fC [static]\fP"

.PP
Definition at line 132 of file EditableGetSet\&.cs\&.
.SS "readonly \fBPropertyInfo\fP<string> Csla\&.Test\&.PropertyGetSet\&.EditableGetSet\&._m09Property = RegisterProperty<string>(c => c\&.M09)\fC [static]\fP"

.PP
Definition at line 139 of file EditableGetSet\&.cs\&.
.SS "readonly \fBPropertyInfo\fP<string> Csla\&.Test\&.PropertyGetSet\&.EditableGetSet\&.ManagedStringFieldProperty = RegisterProperty<string>(nameof(\fBManagedStringField\fP))\fC [static]\fP"

.PP
Definition at line 72 of file EditableGetSet\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "new int Csla\&.Test\&.PropertyGetSet\&.EditableGetSet\&.EditLevel\fC [get]\fP"

.PP
Definition at line 185 of file EditableGetSet\&.cs\&.
.SS "int Csla\&.Test\&.PropertyGetSet\&.EditableGetSet\&.F02\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 34 of file EditableGetSet\&.cs\&.
.SS "string Csla\&.Test\&.PropertyGetSet\&.EditableGetSet\&.F03\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 42 of file EditableGetSet\&.cs\&.
.SS "string Csla\&.Test\&.PropertyGetSet\&.EditableGetSet\&.F04\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 50 of file EditableGetSet\&.cs\&.
.SS "bool Csla\&.Test\&.PropertyGetSet\&.EditableGetSet\&.F05\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 58 of file EditableGetSet\&.cs\&.
.SS "string Csla\&.Test\&.PropertyGetSet\&.EditableGetSet\&.F06\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 66 of file EditableGetSet\&.cs\&.
.SS "string Csla\&.Test\&.PropertyGetSet\&.EditableGetSet\&.FieldBackedString\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 26 of file EditableGetSet\&.cs\&.
.SS "\fBChildList\fP Csla\&.Test\&.PropertyGetSet\&.EditableGetSet\&.LazyChild\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 179 of file EditableGetSet\&.cs\&.
.SS "int Csla\&.Test\&.PropertyGetSet\&.EditableGetSet\&.M02\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 85 of file EditableGetSet\&.cs\&.
.SS "string Csla\&.Test\&.PropertyGetSet\&.EditableGetSet\&.M03\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 98 of file EditableGetSet\&.cs\&.
.SS "string Csla\&.Test\&.PropertyGetSet\&.EditableGetSet\&.M04\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 105 of file EditableGetSet\&.cs\&.
.SS "bool Csla\&.Test\&.PropertyGetSet\&.EditableGetSet\&.M05\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 112 of file EditableGetSet\&.cs\&.
.SS "Guid Csla\&.Test\&.PropertyGetSet\&.EditableGetSet\&.M06\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 119 of file EditableGetSet\&.cs\&.
.SS "string Csla\&.Test\&.PropertyGetSet\&.EditableGetSet\&.M07\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 126 of file EditableGetSet\&.cs\&.
.SS "\fBEditableGetSet\fP Csla\&.Test\&.PropertyGetSet\&.EditableGetSet\&.ManagedChild\fC [get]\fP"

.PP
Definition at line 156 of file EditableGetSet\&.cs\&.
.SS "\fBChildList\fP Csla\&.Test\&.PropertyGetSet\&.EditableGetSet\&.ManagedChildList\fC [get]\fP"

.PP
Definition at line 167 of file EditableGetSet\&.cs\&.
.SS "string Csla\&.Test\&.PropertyGetSet\&.EditableGetSet\&.ManagedStringField\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 73 of file EditableGetSet\&.cs\&.
.SS "bool Csla\&.Test\&.PropertyGetSet\&.EditableGetSet\&.ManagedStringFieldDirty\fC [get]\fP"

.PP
Definition at line 79 of file EditableGetSet\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
