.TH "Csla.Test.PropertyInfo.PropertyInfoTests" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.PropertyInfo.PropertyInfoTests
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBTestName\fP ()"
.br
.ti -1c
.RI "void \fBTestNameDataAnnotations\fP ()"
.br
.ti -1c
.RI "void \fBTestNameComponentModel\fP ()"
.br
.ti -1c
.RI "void \fBTestNameFriendlyName\fP ()"
.br
.ti -1c
.RI "void \fBTestDefaultValue\fP ()"
.br
.ti -1c
.RI "void \fBTestStringNullDefaultValue\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 23 of file PropertyInfoTests\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Csla\&.Test\&.PropertyInfo\&.PropertyInfoTests\&.TestDefaultValue ()"

.PP
Definition at line 50 of file PropertyInfoTests\&.cs\&.
.SS "void Csla\&.Test\&.PropertyInfo\&.PropertyInfoTests\&.TestName ()"

.PP
Definition at line 26 of file PropertyInfoTests\&.cs\&.
.SS "void Csla\&.Test\&.PropertyInfo\&.PropertyInfoTests\&.TestNameComponentModel ()"

.PP
Definition at line 38 of file PropertyInfoTests\&.cs\&.
.SS "void Csla\&.Test\&.PropertyInfo\&.PropertyInfoTests\&.TestNameDataAnnotations ()"

.PP
Definition at line 32 of file PropertyInfoTests\&.cs\&.
.SS "void Csla\&.Test\&.PropertyInfo\&.PropertyInfoTests\&.TestNameFriendlyName ()"

.PP
Definition at line 44 of file PropertyInfoTests\&.cs\&.
.SS "void Csla\&.Test\&.PropertyInfo\&.PropertyInfoTests\&.TestStringNullDefaultValue ()"

.PP
Definition at line 57 of file PropertyInfoTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
