.TH "Csla.Data.SqlClient" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Data.SqlClient
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBConnectionManager\fP"
.br
.RI "Provides an automated way to reuse open database connections within the context of a single data portal operation\&. "
.ti -1c
.RI "class \fBSafeSqlDataReader\fP"
.br
.RI "This is a SqlDataReader that 'fixes' any null values before they are returned to our business code\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
