.TH "Csla.Test.AppDomainTests.AppDomainTestClass" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.AppDomainTests.AppDomainTestClass
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBAppDomainTestIsCalled\fP ()"
.br
.ti -1c
.RI "void \fBClearContextsAfterEachTest\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 25 of file AppDomainTests\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Csla\&.Test\&.AppDomainTests\&.AppDomainTestClass\&.AppDomainTestIsCalled ()"

.PP
Definition at line 28 of file AppDomainTests\&.cs\&.
.SS "void Csla\&.Test\&.AppDomainTests\&.AppDomainTestClass\&.ClearContextsAfterEachTest ()"

.PP
Definition at line 43 of file AppDomainTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
