.TH "Csla.Test.Basic.Child" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.Basic.Child
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.BusinessBase< Child >\fP, and \fBCsla\&.BusinessBase< Child >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBChild\fP ()"
.br
.ti -1c
.RI "override bool \fBEquals\fP (object obj)"
.br
.ti -1c
.RI "override int \fBGetHashCode\fP ()"
.br
.ti -1c
.RI "\fBChild\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static readonly \fBPropertyInfo\fP< string > \fBDataProperty\fP = RegisterProperty<string>(c => c\&.Data)"
.br
.ti -1c
.RI "static readonly \fBPropertyInfo\fP< \fBGrandChildren\fP > \fBGrandChildrenProperty\fP = RegisterProperty<\fBGrandChildren\fP>(c => c\&.GrandChildren)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override object \fBGetIdValue\fP ()"
.br
.RI "Override this method to return a unique identifying value for this object\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBData\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "Guid \fBGuid\fP\fC [get]\fP"
.br
.ti -1c
.RI "\fBGrandChildren\fP \fBGrandChildren\fP\fC [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 16 of file Child\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Csla\&.Test\&.Basic\&.Child\&.Child ()"

.PP
Definition at line 53 of file Child\&.cs\&.
.SS "Csla\&.Test\&.Basic\&.Child\&.Child ()"

.PP
Definition at line 80 of file Child\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override bool Csla\&.Test\&.Basic\&.Child\&.Equals (object obj)"

.PP
Definition at line 41 of file Child\&.cs\&.
.SS "override int Csla\&.Test\&.Basic\&.Child\&.GetHashCode ()"

.PP
Definition at line 51 of file Child\&.cs\&.
.SS "override object Csla\&.Test\&.Basic\&.Child\&.GetIdValue ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Override this method to return a unique identifying value for this object\&. 
.PP
Reimplemented from \fBCsla\&.BusinessBase< Child >\fP\&.
.PP
Definition at line 23 of file Child\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "readonly \fBPropertyInfo\fP<string> Csla\&.Test\&.Basic\&.Child\&.DataProperty = RegisterProperty<string>(c => c\&.Data)\fC [static]\fP"

.PP
Definition at line 20 of file Child\&.cs\&.
.SS "readonly \fBPropertyInfo\fP<\fBGrandChildren\fP> Csla\&.Test\&.Basic\&.Child\&.GrandChildrenProperty = RegisterProperty<\fBGrandChildren\fP>(c => c\&.GrandChildren)\fC [static]\fP"

.PP
Definition at line 32 of file Child\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "string Csla\&.Test\&.Basic\&.Child\&.Data\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 21 of file Child\&.cs\&.
.SS "\fBGrandChildren\fP Csla\&.Test\&.Basic\&.Child\&.GrandChildren\fC [get]\fP"

.PP
Definition at line 33 of file Child\&.cs\&.
.SS "Guid Csla\&.Test\&.Basic\&.Child\&.Guid\fC [get]\fP"

.PP
Definition at line 27 of file Child\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
