.TH "Csla.Serialization.ISerializationFormatter" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Serialization.ISerializationFormatter \- Defines an object that can serialize and deserialize object graphs\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBCsla\&.Serialization\&.BinaryFormatterWrapper\fP, \fBCsla\&.Serialization\&.Mobile\&.MobileFormatter\fP, and \fBCsla\&.Serialization\&.NetDataContractSerializerWrapper\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "object \fBDeserialize\fP (System\&.IO\&.Stream serializationStream)"
.br
.RI "Converts a serialization stream into an object graph\&. "
.ti -1c
.RI "object \fBDeserialize\fP (byte[] serializationStream)"
.br
.RI "Converts a serialization stream into an object graph\&. "
.ti -1c
.RI "void \fBSerialize\fP (System\&.IO\&.Stream serializationStream, object graph)"
.br
.RI "Converts an object graph into a byte stream\&. "
.ti -1c
.RI "byte[] \fBSerialize\fP (object graph)"
.br
.RI "Converts an object graph into a byte stream\&. "
.in -1c
.SH "Detailed Description"
.PP 
Defines an object that can serialize and deserialize object graphs\&. 


.PP
Definition at line 16 of file ISerializationFormatter\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "object Csla\&.Serialization\&.ISerializationFormatter\&.Deserialize (byte[] serializationStream)"

.PP
Converts a serialization stream into an object graph\&. 
.PP
\fBParameters\fP
.RS 4
\fIserializationStream\fP Byte stream containing the serialized data\&.
.RE
.PP
\fBReturns\fP
.RS 4
A deserialized object graph\&.
.RE
.PP

.PP
Implemented in \fBCsla\&.Serialization\&.Mobile\&.MobileFormatter\fP, \fBCsla\&.Serialization\&.NetDataContractSerializerWrapper\fP, and \fBCsla\&.Serialization\&.BinaryFormatterWrapper\fP\&.
.SS "object Csla\&.Serialization\&.ISerializationFormatter\&.Deserialize (System\&.IO\&.Stream serializationStream)"

.PP
Converts a serialization stream into an object graph\&. 
.PP
\fBParameters\fP
.RS 4
\fIserializationStream\fP Byte stream containing the serialized data\&.
.RE
.PP
\fBReturns\fP
.RS 4
A deserialized object graph\&.
.RE
.PP

.PP
Implemented in \fBCsla\&.Serialization\&.NetDataContractSerializerWrapper\fP, and \fBCsla\&.Serialization\&.BinaryFormatterWrapper\fP\&.
.SS "byte [] Csla\&.Serialization\&.ISerializationFormatter\&.Serialize (object graph)"

.PP
Converts an object graph into a byte stream\&. 
.PP
\fBParameters\fP
.RS 4
\fIgraph\fP Object graph to be serialized\&.
.RE
.PP

.PP
Implemented in \fBCsla\&.Serialization\&.Mobile\&.MobileFormatter\fP, \fBCsla\&.Serialization\&.NetDataContractSerializerWrapper\fP, and \fBCsla\&.Serialization\&.BinaryFormatterWrapper\fP\&.
.SS "void Csla\&.Serialization\&.ISerializationFormatter\&.Serialize (System\&.IO\&.Stream serializationStream, object graph)"

.PP
Converts an object graph into a byte stream\&. 
.PP
\fBParameters\fP
.RS 4
\fIserializationStream\fP Stream that will contain the the serialized data\&.
.br
\fIgraph\fP Object graph to be serialized\&.
.RE
.PP

.PP
Implemented in \fBCsla\&.Serialization\&.NetDataContractSerializerWrapper\fP, and \fBCsla\&.Serialization\&.BinaryFormatterWrapper\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
