.TH "Csla.Test.Serialization.SerializationRoot" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.Serialization.SerializationRoot
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.BusinessBase< SerializationRoot >\fP\&.
.PP
Inherited by \fBCsla\&.Test\&.Serialization\&.OverrideSerializationRoot\fP\&.
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBPropertyInfo\fP< string > \fBDataProperty\fP = RegisterProperty<string>(c => c\&.Data, \fBRelationshipTypes\&.PrivateField\fP)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnDeserialized\fP (System\&.Runtime\&.Serialization\&.StreamingContext context)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBData\fP\fC [get, set]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 15 of file SerializationRoot\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override void Csla\&.Test\&.Serialization\&.SerializationRoot\&.OnDeserialized (System\&.Runtime\&.Serialization\&.StreamingContext context)\fC [protected]\fP"

.PP
Definition at line 25 of file SerializationRoot\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBPropertyInfo\fP<string> Csla\&.Test\&.Serialization\&.SerializationRoot\&.DataProperty = RegisterProperty<string>(c => c\&.Data, \fBRelationshipTypes\&.PrivateField\fP)\fC [static]\fP"

.PP
Definition at line 17 of file SerializationRoot\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "string Csla\&.Test\&.Serialization\&.SerializationRoot\&.Data\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 19 of file SerializationRoot\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
