.TH "Csla.Core.INotifyBusy" 3 "Thu Jul 22 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Core.INotifyBusy \- Interface defining an object that notifies when it is busy executing an asynchronous operation\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.Core\&.INotifyUnhandledAsyncException\fP\&.
.PP
Inherited by \fBCsla\&.BusinessBindingListBase< T, C >\fP, \fBCsla\&.BusinessListBase< T, C >\fP, \fBCsla\&.Core\&.BusinessBase\fP, \fBCsla\&.Core\&.ExtendedBindingList< T >\fP, \fBCsla\&.Core\&.ITrackStatus\fP, Csla\&.Core\&.LoadManager\&.AsyncLoadManager, \fBCsla\&.Core\&.ObservableBindingList< T >\fP, \fBCsla\&.IBusinessBase\fP, \fBCsla\&.IBusinessListBase< C >\fP, \fBCsla\&.IReadOnlyBase\fP, \fBCsla\&.IReadOnlyListBase< C >\fP, and \fBCsla\&.ReadOnlyBase< T >\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "bool \fBIsBusy\fP\fC [get]\fP"
.br
.RI "Gets a value indicating whether the object, or any of the object's child objects, are busy running an asynchronous operation\&. "
.ti -1c
.RI "bool \fBIsSelfBusy\fP\fC [get]\fP"
.br
.RI "Gets a value indicating whether the object is busy running an asynchronous operation\&. "
.in -1c
.SS "Events"

.in +1c
.ti -1c
.RI "\fBBusyChangedEventHandler\fP \fBBusyChanged\fP"
.br
.RI "Event raised when the object's busy status changes\&. "
.in -1c
.SH "Detailed Description"
.PP 
Interface defining an object that notifies when it is busy executing an asynchronous operation\&. 


.PP
Definition at line 16 of file INotifyBusy\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "bool Csla\&.Core\&.INotifyBusy\&.IsBusy\fC [get]\fP"

.PP
Gets a value indicating whether the object, or any of the object's child objects, are busy running an asynchronous operation\&. 
.PP
Definition at line 29 of file INotifyBusy\&.cs\&.
.SS "bool Csla\&.Core\&.INotifyBusy\&.IsSelfBusy\fC [get]\fP"

.PP
Gets a value indicating whether the object is busy running an asynchronous operation\&. 
.PP
Definition at line 34 of file INotifyBusy\&.cs\&.
.SH "Event Documentation"
.PP 
.SS "\fBBusyChangedEventHandler\fP Csla\&.Core\&.INotifyBusy\&.BusyChanged"

.PP
Event raised when the object's busy status changes\&. 
.PP
Definition at line 22 of file INotifyBusy\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
