.TH "Csla.Validation.CommonRules.IntegerMinValueRuleArgs" 3 "Thu Jul 22 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Validation.CommonRules.IntegerMinValueRuleArgs \- Custom \fBRuleArgs\fP object required by the IntegerMinValue rule method\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.Validation\&.DecoratedRuleArgs\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBIntegerMinValueRuleArgs\fP (string propertyName, int minValue)"
.br
.RI "Create a new object\&. "
.ti -1c
.RI "\fBIntegerMinValueRuleArgs\fP (\fBCore\&.IPropertyInfo\fP propertyInfo, int minValue)"
.br
.RI "Create a new object\&. "
.ti -1c
.RI "\fBIntegerMinValueRuleArgs\fP (string propertyName, string friendlyName, int minValue)"
.br
.RI "Create a new object\&. "
.ti -1c
.RI "\fBIntegerMinValueRuleArgs\fP (string propertyName, int minValue, string format)"
.br
.RI "Create a new object\&. "
.ti -1c
.RI "\fBIntegerMinValueRuleArgs\fP (\fBCore\&.IPropertyInfo\fP propertyInfo, int minValue, string format)"
.br
.RI "Create a new object\&. "
.ti -1c
.RI "\fBIntegerMinValueRuleArgs\fP (string propertyName, string friendlyName, int minValue, string format)"
.br
.RI "Create a new object\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBMinValue\fP\fC [get]\fP"
.br
.RI "Get the min value for the property\&. "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Custom \fBRuleArgs\fP object required by the IntegerMinValue rule method\&. 


.PP
Definition at line 510 of file Csla\&.Validation\&.Shared/CommonRules\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Csla\&.Validation\&.CommonRules\&.IntegerMinValueRuleArgs\&.IntegerMinValueRuleArgs (string propertyName, int minValue)"

.PP
Create a new object\&. 
.PP
\fBParameters\fP
.RS 4
\fIpropertyName\fP Name of the property\&.
.br
\fIminValue\fP Minimum allowed value for the property\&.
.RE
.PP

.PP
Definition at line 525 of file Csla\&.Validation\&.Shared/CommonRules\&.cs\&.
.SS "Csla\&.Validation\&.CommonRules\&.IntegerMinValueRuleArgs\&.IntegerMinValueRuleArgs (\fBCore\&.IPropertyInfo\fP propertyInfo, int minValue)"

.PP
Create a new object\&. 
.PP
\fBParameters\fP
.RS 4
\fIpropertyInfo\fP Property to validate\&.
.br
\fIminValue\fP Minimum allowed value for the property\&.
.RE
.PP

.PP
Definition at line 537 of file Csla\&.Validation\&.Shared/CommonRules\&.cs\&.
.SS "Csla\&.Validation\&.CommonRules\&.IntegerMinValueRuleArgs\&.IntegerMinValueRuleArgs (string propertyName, string friendlyName, int minValue)"

.PP
Create a new object\&. 
.PP
\fBParameters\fP
.RS 4
\fIpropertyName\fP Name of the property\&.
.br
\fIfriendlyName\fP A friendly name for the property, which will be used in place of the property name when creating the broken rule description string\&.
.br
\fIminValue\fP Minimum allowed value for the property\&.
.RE
.PP

.PP
Definition at line 552 of file Csla\&.Validation\&.Shared/CommonRules\&.cs\&.
.SS "Csla\&.Validation\&.CommonRules\&.IntegerMinValueRuleArgs\&.IntegerMinValueRuleArgs (string propertyName, int minValue, string format)"

.PP
Create a new object\&. 
.PP
\fBParameters\fP
.RS 4
\fIpropertyName\fP Name of the property\&.
.br
\fIminValue\fP Minimum allowed value for the property\&.
.br
\fIformat\fP Format string for the min value value in the broken rule string\&.
.RE
.PP

.PP
Definition at line 567 of file Csla\&.Validation\&.Shared/CommonRules\&.cs\&.
.SS "Csla\&.Validation\&.CommonRules\&.IntegerMinValueRuleArgs\&.IntegerMinValueRuleArgs (\fBCore\&.IPropertyInfo\fP propertyInfo, int minValue, string format)"

.PP
Create a new object\&. 
.PP
\fBParameters\fP
.RS 4
\fIpropertyInfo\fP Property to validate\&.
.br
\fIminValue\fP Minimum allowed value for the property\&.
.br
\fIformat\fP Format string for the min value value in the broken rule string\&.
.RE
.PP

.PP
Definition at line 581 of file Csla\&.Validation\&.Shared/CommonRules\&.cs\&.
.SS "Csla\&.Validation\&.CommonRules\&.IntegerMinValueRuleArgs\&.IntegerMinValueRuleArgs (string propertyName, string friendlyName, int minValue, string format)"

.PP
Create a new object\&. 
.PP
\fBParameters\fP
.RS 4
\fIpropertyName\fP Name of the property\&.
.br
\fIfriendlyName\fP A friendly name for the property, which will be used in place of the property name when creating the broken rule description string\&.
.br
\fIminValue\fP Minimum allowed value for the property\&.
.br
\fIformat\fP Format string for the min value value in the broken rule string\&.
.RE
.PP

.PP
Definition at line 598 of file Csla\&.Validation\&.Shared/CommonRules\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "int Csla\&.Validation\&.CommonRules\&.IntegerMinValueRuleArgs\&.MinValue\fC [get]\fP"

.PP
Get the min value for the property\&. 
.PP
Definition at line 515 of file Csla\&.Validation\&.Shared/CommonRules\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
