.TH "Csla.Validation.Resource.String" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Validation.Resource.String
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static int \fBApplicationName\fP = 2130771968"
.br
.ti -1c
.RI "static int \fBHello\fP = 2130771969"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 39 of file Resource\&.Designer\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "int Csla\&.Validation\&.Resource\&.String\&.ApplicationName = 2130771968\fC [static]\fP"

.PP
Definition at line 43 of file Resource\&.Designer\&.cs\&.
.SS "int Csla\&.Validation\&.Resource\&.String\&.Hello = 2130771969\fC [static]\fP"

.PP
Definition at line 46 of file Resource\&.Designer\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
