.TH "Csla.Iosui.Binding.BindingManager" 3 "Thu Jul 22 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Iosui.Binding.BindingManager \- Provides the ability to bing properties on iOS UI controls to properties on CSLA objects\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBindingManager\fP (UIView view)"
.br
.RI "Creates a new instance of the binding manager\&. "
.ti -1c
.RI "void \fBAdd\fP (UIView control, string targetProperty, object source, string sourceProperty, BindingDirection bindingDirection)"
.br
.RI "Adds a new binding to be managed\&. "
.ti -1c
.RI "void \fBAdd\fP (\fBBinding\fP binding)"
.br
.RI "Adds a new binding to be managed\&. "
.ti -1c
.RI "void \fBRemove\fP (UIView target, string targetProperty, object source, string sourceProperty)"
.br
.RI "Removes the binding matching the supplied parameters from the binding manager\&. "
.ti -1c
.RI "void \fBRemove\fP (\fBBinding\fP binding)"
.br
.RI "Removes the supplied binding from the binding manager\&. "
.ti -1c
.RI "void \fBRemoveAll\fP ()"
.br
.RI "Removes all bindings from the binding manager\&. "
.ti -1c
.RI "IEnumerable< \fBBinding\fP > \fBGetBindingsForView\fP (UIView view)"
.br
.RI "Returns all bindings for the supplied view\&. "
.ti -1c
.RI "void \fBUpdateSourceForView\fP (UIView control)"
.br
.RI "Updates bindings with the current values in the supplied control\&. "
.ti -1c
.RI "void \fBUpdateSourceForLastView\fP ()"
.br
.RI "Updates bindings on the view that is in current focus on the activity supplied to the \fBBindingManager\fP\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "List< \fBBinding\fP > \fBBindings\fP\fC [get]\fP"
.br
.RI "A list of bindings that have been added to the manager\&. "
.in -1c
.SH "Detailed Description"
.PP 
Provides the ability to bing properties on iOS UI controls to properties on CSLA objects\&. 

Bindings update normally when the control looses focus\&.
.PP
Definition at line 24 of file Csla\&.Iosui\&.Ios/Binding/BindingManager\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Csla\&.Iosui\&.Binding\&.BindingManager\&.BindingManager (UIView view)"

.PP
Creates a new instance of the binding manager\&. 
.PP
\fBParameters\fP
.RS 4
\fIview\fP The Android activity that is using the view with the controls to bind to\&.
.RE
.PP

.PP
Definition at line 35 of file Csla\&.Iosui\&.Ios/Binding/BindingManager\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Csla\&.Iosui\&.Binding\&.BindingManager\&.Add (\fBBinding\fP binding)"

.PP
Adds a new binding to be managed\&. 
.PP
\fBParameters\fP
.RS 4
\fIbinding\fP The new binding to add\&.
.RE
.PP

.PP
Definition at line 63 of file Csla\&.Iosui\&.Ios/Binding/BindingManager\&.cs\&.
.SS "void Csla\&.Iosui\&.Binding\&.BindingManager\&.Add (UIView control, string targetProperty, object source, string sourceProperty, BindingDirection bindingDirection)"

.PP
Adds a new binding to be managed\&. 
.PP
\fBParameters\fP
.RS 4
\fIcontrol\fP A reference to the control to bind to\&.
.br
\fItargetProperty\fP The name of the property on the view to bind to\&.
.br
\fIsource\fP A reference to the object that will be bound to the control\&.
.br
\fIsourceProperty\fP The name of the property on the object that will be bound to the target property\&.
.br
\fIbindingDirection\fP Indicates if the binding is one way or two way\&.
.RE
.PP

.PP
Definition at line 54 of file Csla\&.Iosui\&.Ios/Binding/BindingManager\&.cs\&.
.SS "IEnumerable<\fBBinding\fP> Csla\&.Iosui\&.Binding\&.BindingManager\&.GetBindingsForView (UIView view)"

.PP
Returns all bindings for the supplied view\&. 
.PP
\fBParameters\fP
.RS 4
\fIview\fP A reference to the view to return bindings for\&.
.RE
.PP
\fBReturns\fP
.RS 4
A enumerable containing the bindings for the supplied view\&.
.RE
.PP

.PP
Definition at line 112 of file Csla\&.Iosui\&.Ios/Binding/BindingManager\&.cs\&.
.SS "void Csla\&.Iosui\&.Binding\&.BindingManager\&.Remove (\fBBinding\fP binding)"

.PP
Removes the supplied binding from the binding manager\&. 
.PP
\fBParameters\fP
.RS 4
\fIbinding\fP The binding to remove\&.
.RE
.PP

.PP
Definition at line 90 of file Csla\&.Iosui\&.Ios/Binding/BindingManager\&.cs\&.
.SS "void Csla\&.Iosui\&.Binding\&.BindingManager\&.Remove (UIView target, string targetProperty, object source, string sourceProperty)"

.PP
Removes the binding matching the supplied parameters from the binding manager\&. If no bindings matched the method does nothing\&.
.PP
\fBParameters\fP
.RS 4
\fItarget\fP A reference to the bound control\&.
.br
\fItargetProperty\fP The name of the property on the view that is bound to\&.
.br
\fIsource\fP A reference to the object that is bound to\&.
.br
\fIsourceProperty\fP The name of the property on the object that that is bound to the target property\&.
.RE
.PP

.PP
Definition at line 76 of file Csla\&.Iosui\&.Ios/Binding/BindingManager\&.cs\&.
.SS "void Csla\&.Iosui\&.Binding\&.BindingManager\&.RemoveAll ()"

.PP
Removes all bindings from the binding manager\&. 
.PP
Definition at line 99 of file Csla\&.Iosui\&.Ios/Binding/BindingManager\&.cs\&.
.SS "void Csla\&.Iosui\&.Binding\&.BindingManager\&.UpdateSourceForLastView ()"

.PP
Updates bindings on the view that is in current focus on the activity supplied to the \fBBindingManager\fP\&. 
.PP
Definition at line 130 of file Csla\&.Iosui\&.Ios/Binding/BindingManager\&.cs\&.
.SS "void Csla\&.Iosui\&.Binding\&.BindingManager\&.UpdateSourceForView (UIView control)"

.PP
Updates bindings with the current values in the supplied control\&. 
.PP
\fBParameters\fP
.RS 4
\fIcontrol\fP The control to update bindings for\&.
.RE
.PP

.PP
Definition at line 121 of file Csla\&.Iosui\&.Ios/Binding/BindingManager\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "List<\fBBinding\fP> Csla\&.Iosui\&.Binding\&.BindingManager\&.Bindings\fC [get]\fP"

.PP
A list of bindings that have been added to the manager\&. 
.PP
Definition at line 44 of file Csla\&.Iosui\&.Ios/Binding/BindingManager\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
