.TH "Csla.Core.ContextDictionary" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Core.ContextDictionary \- Dictionary type that is serializable with the SerializationFormatterFactory\&.GetFormatter()\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits HybridDictionary, and \fBCsla\&.Serialization\&.Mobile\&.IMobileObject\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "object \fBGetValueOrNull\fP (string key)"
.br
.RI "Get a value from the dictionary, or return null if the key is not found in the dictionary\&. "
.in -1c
.SH "Detailed Description"
.PP 
Dictionary type that is serializable with the SerializationFormatterFactory\&.GetFormatter()\&. 


.PP
Definition at line 19 of file ContextDictionary\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "object Csla\&.Core\&.ContextDictionary\&.GetValueOrNull (string key)"

.PP
Get a value from the dictionary, or return null if the key is not found in the dictionary\&. 
.PP
\fBParameters\fP
.RS 4
\fIkey\fP Key of value to get from dictionary\&.
.RE
.PP

.PP
Definition at line 26 of file ContextDictionary\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
