.TH "csla.netcore.test.DataPortal.RoutingTagTests" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csla.netcore.test.DataPortal.RoutingTagTests
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBCleanup\fP ()"
.br
.ti -1c
.RI "void \fBGetRoutingTag\fP ()"
.br
.ti -1c
.RI "void \fBCreateTagNoVersionNoRoute\fP ()"
.br
.ti -1c
.RI "void \fBCreateTagNoVersion\fP ()"
.br
.ti -1c
.RI "void \fBCreateTagNoRoute\fP ()"
.br
.ti -1c
.RI "void \fBCreateTag\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 29 of file RoutingTagTests\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void csla\&.netcore\&.test\&.DataPortal\&.RoutingTagTests\&.Cleanup ()"

.PP
Definition at line 32 of file RoutingTagTests\&.cs\&.
.SS "void csla\&.netcore\&.test\&.DataPortal\&.RoutingTagTests\&.CreateTag ()"

.PP
Definition at line 85 of file RoutingTagTests\&.cs\&.
.SS "void csla\&.netcore\&.test\&.DataPortal\&.RoutingTagTests\&.CreateTagNoRoute ()"

.PP
Definition at line 74 of file RoutingTagTests\&.cs\&.
.SS "void csla\&.netcore\&.test\&.DataPortal\&.RoutingTagTests\&.CreateTagNoVersion ()"

.PP
Definition at line 63 of file RoutingTagTests\&.cs\&.
.SS "void csla\&.netcore\&.test\&.DataPortal\&.RoutingTagTests\&.CreateTagNoVersionNoRoute ()"

.PP
Definition at line 52 of file RoutingTagTests\&.cs\&.
.SS "void csla\&.netcore\&.test\&.DataPortal\&.RoutingTagTests\&.GetRoutingTag ()"

.PP
Definition at line 40 of file RoutingTagTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
