.TH "Csla.Test.Serialization.NonSerializedClass" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.Serialization.NonSerializedClass
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBDo\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5 of file NonSerializedClass\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Csla\&.Test\&.Serialization\&.NonSerializedClass\&.Do ()"

.PP
Definition at line 7 of file NonSerializedClass\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
