.TH "Csla.Testing.Business" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Testing.Business
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBApplicationContext\fP"
.br
.ti -1c
.RI "namespace \fBBusyStatus\fP"
.br
.ti -1c
.RI "namespace \fBCommandBase\fP"
.br
.ti -1c
.RI "namespace \fBDataPortal\fP"
.br
.ti -1c
.RI "namespace \fBEditableChildTests\fP"
.br
.ti -1c
.RI "namespace \fBEditableRootListTests\fP"
.br
.ti -1c
.RI "namespace \fBEditableRootTests\fP"
.br
.ti -1c
.RI "namespace \fBObjectFactory\fP"
.br
.ti -1c
.RI "namespace \fBReadOnlyTest\fP"
.br
.ti -1c
.RI "namespace \fBTestProxies\fP"
.br
.ti -1c
.RI "namespace \fBValidation\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
