.TH "Csla.Analyzers.IntegrationTests.SerializedObject" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Analyzers.IntegrationTests.SerializedObject
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Definition at line 39 of file SerializableArgumentTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
