.TH "Csla.Test.DataPortalChild.DataPortalChildTests" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.DataPortalChild.DataPortalChildTests
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBCreateAndSaveChild\fP ()"
.br
.ti -1c
.RI "void \fBCreateAndDeleteChild\fP ()"
.br
.ti -1c
.RI "void \fBFetchAndSaveChild\fP ()"
.br
.ti -1c
.RI "void \fBFetchAndDeleteChild\fP ()"
.br
.ti -1c
.RI "void \fBFetchAndSaveChildList\fP ()"
.br
.ti -1c
.RI "void \fBFetchAndSaveChildListVerifyParent\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 26 of file DataPortalChildTests\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Csla\&.Test\&.DataPortalChild\&.DataPortalChildTests\&.CreateAndDeleteChild ()"

.PP
Definition at line 50 of file DataPortalChildTests\&.cs\&.
.SS "void Csla\&.Test\&.DataPortalChild\&.DataPortalChildTests\&.CreateAndSaveChild ()"

.PP
Definition at line 29 of file DataPortalChildTests\&.cs\&.
.SS "void Csla\&.Test\&.DataPortalChild\&.DataPortalChildTests\&.FetchAndDeleteChild ()"

.PP
Definition at line 91 of file DataPortalChildTests\&.cs\&.
.SS "void Csla\&.Test\&.DataPortalChild\&.DataPortalChildTests\&.FetchAndSaveChild ()"

.PP
Definition at line 68 of file DataPortalChildTests\&.cs\&.
.SS "void Csla\&.Test\&.DataPortalChild\&.DataPortalChildTests\&.FetchAndSaveChildList ()"

.PP
Definition at line 114 of file DataPortalChildTests\&.cs\&.
.SS "void Csla\&.Test\&.DataPortalChild\&.DataPortalChildTests\&.FetchAndSaveChildListVerifyParent ()"

.PP
Definition at line 139 of file DataPortalChildTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
