.TH "Csla.Validation.DecoratedRuleArgs" 3 "Thu Jul 22 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Validation.DecoratedRuleArgs \- Object providing extra information to methods that implement business rules\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.Validation\&.RuleArgs\fP\&.
.PP
Inherited by \fBCsla\&.Validation\&.CommonRules\&.IntegerMaxValueRuleArgs\fP, \fBCsla\&.Validation\&.CommonRules\&.IntegerMinValueRuleArgs\fP, \fBCsla\&.Validation\&.CommonRules\&.MaxLengthRuleArgs\fP, \fBCsla\&.Validation\&.CommonRules\&.MaxValueRuleArgs< T >\fP, \fBCsla\&.Validation\&.CommonRules\&.MinLengthRuleArgs\fP, \fBCsla\&.Validation\&.CommonRules\&.MinValueRuleArgs< T >\fP, and \fBCsla\&.Validation\&.CommonRules\&.RegExRuleArgs\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDecoratedRuleArgs\fP (string propertyName)"
.br
.RI "Creates an instance of \fBRuleArgs\fP\&. "
.ti -1c
.RI "\fBDecoratedRuleArgs\fP (\fBCore\&.IPropertyInfo\fP propertyInfo)"
.br
.RI "Creates an instance of \fBRuleArgs\fP\&. "
.ti -1c
.RI "\fBDecoratedRuleArgs\fP (string propertyName, string friendlyName)"
.br
.RI "Creates an instance of \fBRuleArgs\fP\&. "
.ti -1c
.RI "\fBDecoratedRuleArgs\fP (string propertyName, \fBRuleSeverity\fP severity)"
.br
.RI "Creates an instance of \fBRuleArgs\fP\&. "
.ti -1c
.RI "\fBDecoratedRuleArgs\fP (\fBCore\&.IPropertyInfo\fP propertyInfo, \fBRuleSeverity\fP severity)"
.br
.RI "Creates an instance of \fBRuleArgs\fP\&. "
.ti -1c
.RI "\fBDecoratedRuleArgs\fP (string propertyName, string friendlyName, \fBRuleSeverity\fP severity)"
.br
.RI "Creates an instance of \fBRuleArgs\fP\&. "
.ti -1c
.RI "\fBDecoratedRuleArgs\fP (string propertyName, \fBRuleSeverity\fP severity, bool stopProcessing)"
.br
.RI "Creates an instance of \fBRuleArgs\fP\&. "
.ti -1c
.RI "\fBDecoratedRuleArgs\fP (\fBCore\&.IPropertyInfo\fP propertyInfo, \fBRuleSeverity\fP severity, bool stopProcessing)"
.br
.RI "Creates an instance of \fBRuleArgs\fP\&. "
.ti -1c
.RI "\fBDecoratedRuleArgs\fP (string propertyName, string friendlyName, \fBRuleSeverity\fP severity, bool stopProcessing)"
.br
.RI "Creates an instance of \fBRuleArgs\fP\&. "
.ti -1c
.RI "\fBDecoratedRuleArgs\fP (string propertyName, Dictionary< string, object > args)"
.br
.RI "Creates an instance of \fBRuleArgs\fP\&. "
.ti -1c
.RI "\fBDecoratedRuleArgs\fP (\fBCore\&.IPropertyInfo\fP propertyInfo, Dictionary< string, object > args)"
.br
.RI "Creates an instance of \fBRuleArgs\fP\&. "
.ti -1c
.RI "\fBDecoratedRuleArgs\fP (string propertyName, string friendlyName, Dictionary< string, object > args)"
.br
.RI "Creates an instance of \fBRuleArgs\fP\&. "
.ti -1c
.RI "\fBDecoratedRuleArgs\fP (string propertyName, \fBRuleSeverity\fP severity, Dictionary< string, object > args)"
.br
.RI "Creates an instance of \fBRuleArgs\fP\&. "
.ti -1c
.RI "\fBDecoratedRuleArgs\fP (\fBCore\&.IPropertyInfo\fP propertyInfo, \fBRuleSeverity\fP severity, Dictionary< string, object > args)"
.br
.RI "Creates an instance of \fBRuleArgs\fP\&. "
.ti -1c
.RI "\fBDecoratedRuleArgs\fP (string propertyName, string friendlyName, \fBRuleSeverity\fP severity, Dictionary< string, object > args)"
.br
.RI "Creates an instance of \fBRuleArgs\fP\&. "
.ti -1c
.RI "\fBDecoratedRuleArgs\fP (string propertyName, \fBRuleSeverity\fP severity, bool stopProcessing, Dictionary< string, object > args)"
.br
.RI "Creates an instance of \fBRuleArgs\fP\&. "
.ti -1c
.RI "\fBDecoratedRuleArgs\fP (\fBCore\&.IPropertyInfo\fP propertyInfo, \fBRuleSeverity\fP severity, bool stopProcessing, Dictionary< string, object > args)"
.br
.RI "Creates an instance of \fBRuleArgs\fP\&. "
.ti -1c
.RI "\fBDecoratedRuleArgs\fP (string propertyName, string friendlyName, \fBRuleSeverity\fP severity, bool stopProcessing, Dictionary< string, object > args)"
.br
.RI "Creates an instance of \fBRuleArgs\fP\&. "
.ti -1c
.RI "override string \fBToString\fP ()"
.br
.RI "Return a string representation of the object using the rule:// URI format\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "object \fBthis[string key]\fP\fC [get, set]\fP"
.br
.RI "Gets or sets an argument value for use by the rule method\&. "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Object providing extra information to methods that implement business rules\&. 


.PP
Definition at line 23 of file DecoratedRuleArgs\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Csla\&.Validation\&.DecoratedRuleArgs\&.DecoratedRuleArgs (string propertyName)"

.PP
Creates an instance of \fBRuleArgs\fP\&. 
.PP
\fBParameters\fP
.RS 4
\fIpropertyName\fP The name of the property to be validated\&.
.RE
.PP

.PP
Definition at line 33 of file DecoratedRuleArgs\&.cs\&.
.SS "Csla\&.Validation\&.DecoratedRuleArgs\&.DecoratedRuleArgs (\fBCore\&.IPropertyInfo\fP propertyInfo)"

.PP
Creates an instance of \fBRuleArgs\fP\&. 
.PP
\fBParameters\fP
.RS 4
\fIpropertyInfo\fP The \fBPropertyInfo\fP for the property to be validated\&.
.RE
.PP

.PP
Definition at line 43 of file DecoratedRuleArgs\&.cs\&.
.SS "Csla\&.Validation\&.DecoratedRuleArgs\&.DecoratedRuleArgs (string propertyName, string friendlyName)"

.PP
Creates an instance of \fBRuleArgs\fP\&. 
.PP
\fBParameters\fP
.RS 4
\fIpropertyName\fP The name of the property to be validated\&.
.br
\fIfriendlyName\fP A friendly name for the property, which will be used in place of the property name when creating the broken rule description string\&.
.RE
.PP

.PP
Definition at line 56 of file DecoratedRuleArgs\&.cs\&.
.SS "Csla\&.Validation\&.DecoratedRuleArgs\&.DecoratedRuleArgs (string propertyName, \fBRuleSeverity\fP severity)"

.PP
Creates an instance of \fBRuleArgs\fP\&. 
.PP
\fBParameters\fP
.RS 4
\fIpropertyName\fP The name of the property to be validated\&.
.br
\fIseverity\fP Initial default severity for the rule\&.
.RE
.PP
.PP
The \fBseverity\fP parameter defines only the initial default severity value\&. If the rule changes this value by setting e\&.Severity, then that new value will become the default for all subsequent rule invocations\&. 
.PP
To avoid confusion, it is recommended that the \fBseverity\fP constructor parameter only be used for rule methods that do not explicitly set e\&.Severity\&. 
.PP
Definition at line 80 of file DecoratedRuleArgs\&.cs\&.
.SS "Csla\&.Validation\&.DecoratedRuleArgs\&.DecoratedRuleArgs (\fBCore\&.IPropertyInfo\fP propertyInfo, \fBRuleSeverity\fP severity)"

.PP
Creates an instance of \fBRuleArgs\fP\&. 
.PP
\fBParameters\fP
.RS 4
\fIpropertyInfo\fP The \fBPropertyInfo\fP for the property to be validated\&.
.br
\fIseverity\fP Initial default severity for the rule\&.
.RE
.PP
.PP
The \fBseverity\fP parameter defines only the initial default severity value\&. If the rule changes this value by setting e\&.Severity, then that new value will become the default for all subsequent rule invocations\&. 
.PP
To avoid confusion, it is recommended that the \fBseverity\fP constructor parameter only be used for rule methods that do not explicitly set e\&.Severity\&. 
.PP
Definition at line 104 of file DecoratedRuleArgs\&.cs\&.
.SS "Csla\&.Validation\&.DecoratedRuleArgs\&.DecoratedRuleArgs (string propertyName, string friendlyName, \fBRuleSeverity\fP severity)"

.PP
Creates an instance of \fBRuleArgs\fP\&. 
.PP
\fBParameters\fP
.RS 4
\fIpropertyName\fP The name of the property to be validated\&.
.br
\fIfriendlyName\fP A friendly name for the property, which will be used in place of the property name when creating the broken rule description string\&.
.br
\fIseverity\fP Initial default severity for the rule\&.
.RE
.PP
.PP
The \fBseverity\fP parameter defines only the initial default severity value\&. If the rule changes this value by setting e\&.Severity, then that new value will become the default for all subsequent rule invocations\&. 
.PP
To avoid confusion, it is recommended that the \fBseverity\fP constructor parameter only be used for rule methods that do not explicitly set e\&.Severity\&. 
.PP
Definition at line 131 of file DecoratedRuleArgs\&.cs\&.
.SS "Csla\&.Validation\&.DecoratedRuleArgs\&.DecoratedRuleArgs (string propertyName, \fBRuleSeverity\fP severity, bool stopProcessing)"

.PP
Creates an instance of \fBRuleArgs\fP\&. 
.PP
\fBParameters\fP
.RS 4
\fIpropertyName\fP The name of the property to be validated\&.
.br
\fIseverity\fP The default severity for the rule\&.
.br
\fIstopProcessing\fP Initial default value for the StopProcessing property\&. 
.RE
.PP
.PP
The \fBseverity\fP and \fBstopProcessing\fP parameters define only the initial default values\&. If the rule changes these values by setting e\&.Severity or e\&.StopProcessing, then the new values will become the default for all subsequent rule invocations\&. 
.PP
To avoid confusion, It is recommended that the \fBseverity\fP and \fBstopProcessing\fP constructor parameters only be used for rule methods that do not explicitly set e\&.Severity or e\&.StopProcessing\&. 
.PP
Definition at line 159 of file DecoratedRuleArgs\&.cs\&.
.SS "Csla\&.Validation\&.DecoratedRuleArgs\&.DecoratedRuleArgs (\fBCore\&.IPropertyInfo\fP propertyInfo, \fBRuleSeverity\fP severity, bool stopProcessing)"

.PP
Creates an instance of \fBRuleArgs\fP\&. 
.PP
\fBParameters\fP
.RS 4
\fIpropertyInfo\fP The \fBPropertyInfo\fP for the property to be validated\&.
.br
\fIseverity\fP The default severity for the rule\&.
.br
\fIstopProcessing\fP Initial default value for the StopProcessing property\&. 
.RE
.PP
.PP
The \fBseverity\fP and \fBstopProcessing\fP parameters define only the initial default values\&. If the rule changes these values by setting e\&.Severity or e\&.StopProcessing, then the new values will become the default for all subsequent rule invocations\&. 
.PP
To avoid confusion, It is recommended that the \fBseverity\fP and \fBstopProcessing\fP constructor parameters only be used for rule methods that do not explicitly set e\&.Severity or e\&.StopProcessing\&. 
.PP
Definition at line 187 of file DecoratedRuleArgs\&.cs\&.
.SS "Csla\&.Validation\&.DecoratedRuleArgs\&.DecoratedRuleArgs (string propertyName, string friendlyName, \fBRuleSeverity\fP severity, bool stopProcessing)"

.PP
Creates an instance of \fBRuleArgs\fP\&. 
.PP
\fBParameters\fP
.RS 4
\fIpropertyName\fP The name of the property to be validated\&.
.br
\fIfriendlyName\fP A friendly name for the property, which will be used in place of the property name when creating the broken rule description string\&.
.br
\fIseverity\fP The default severity for the rule\&.
.br
\fIstopProcessing\fP Initial default value for the StopProcessing property\&. 
.RE
.PP
.PP
The \fBseverity\fP and \fBstopProcessing\fP parameters define only the initial default values\&. If the rule changes these values by setting e\&.Severity or e\&.StopProcessing, then the new values will become the default for all subsequent rule invocations\&. 
.PP
To avoid confusion, It is recommended that the \fBseverity\fP and \fBstopProcessing\fP constructor parameters only be used for rule methods that do not explicitly set e\&.Severity or e\&.StopProcessing\&. 
.PP
Definition at line 218 of file DecoratedRuleArgs\&.cs\&.
.SS "Csla\&.Validation\&.DecoratedRuleArgs\&.DecoratedRuleArgs (string propertyName, Dictionary< string, object > args)"

.PP
Creates an instance of \fBRuleArgs\fP\&. 
.PP
\fBParameters\fP
.RS 4
\fIpropertyName\fP The name of the property to be validated\&.
.br
\fIargs\fP Reference to a Dictionary containing name/value arguments for use by the rule method\&.
.RE
.PP

.PP
Definition at line 232 of file DecoratedRuleArgs\&.cs\&.
.SS "Csla\&.Validation\&.DecoratedRuleArgs\&.DecoratedRuleArgs (\fBCore\&.IPropertyInfo\fP propertyInfo, Dictionary< string, object > args)"

.PP
Creates an instance of \fBRuleArgs\fP\&. 
.PP
\fBParameters\fP
.RS 4
\fIpropertyInfo\fP The \fBPropertyInfo\fP for the property to be validated\&.
.br
\fIargs\fP Reference to a Dictionary containing name/value arguments for use by the rule method\&.
.RE
.PP

.PP
Definition at line 244 of file DecoratedRuleArgs\&.cs\&.
.SS "Csla\&.Validation\&.DecoratedRuleArgs\&.DecoratedRuleArgs (string propertyName, string friendlyName, Dictionary< string, object > args)"

.PP
Creates an instance of \fBRuleArgs\fP\&. 
.PP
\fBParameters\fP
.RS 4
\fIpropertyName\fP The name of the property to be validated\&.
.br
\fIfriendlyName\fP A friendly name for the property, which will be used in place of the property name when creating the broken rule description string\&.
.br
\fIargs\fP Reference to a Dictionary containing name/value arguments for use by the rule method\&.
.RE
.PP

.PP
Definition at line 259 of file DecoratedRuleArgs\&.cs\&.
.SS "Csla\&.Validation\&.DecoratedRuleArgs\&.DecoratedRuleArgs (string propertyName, \fBRuleSeverity\fP severity, Dictionary< string, object > args)"

.PP
Creates an instance of \fBRuleArgs\fP\&. 
.PP
\fBParameters\fP
.RS 4
\fIpropertyName\fP The name of the property to be validated\&.
.br
\fIseverity\fP Initial default severity for the rule\&.
.br
\fIargs\fP Reference to a Dictionary containing name/value arguments for use by the rule method\&.
.RE
.PP
.PP
The \fBseverity\fP parameter defines only the initial default severity value\&. If the rule changes this value by setting e\&.Severity, then that new value will become the default for all subsequent rule invocations\&. 
.PP
To avoid confusion, it is recommended that the \fBseverity\fP constructor parameter only be used for rule methods that do not explicitly set e\&.Severity\&. 
.PP
Definition at line 285 of file DecoratedRuleArgs\&.cs\&.
.SS "Csla\&.Validation\&.DecoratedRuleArgs\&.DecoratedRuleArgs (\fBCore\&.IPropertyInfo\fP propertyInfo, \fBRuleSeverity\fP severity, Dictionary< string, object > args)"

.PP
Creates an instance of \fBRuleArgs\fP\&. 
.PP
\fBParameters\fP
.RS 4
\fIpropertyInfo\fP The \fBPropertyInfo\fP for the property to be validated\&.
.br
\fIseverity\fP Initial default severity for the rule\&.
.br
\fIargs\fP Reference to a Dictionary containing name/value arguments for use by the rule method\&.
.RE
.PP
.PP
The \fBseverity\fP parameter defines only the initial default severity value\&. If the rule changes this value by setting e\&.Severity, then that new value will become the default for all subsequent rule invocations\&. 
.PP
To avoid confusion, it is recommended that the \fBseverity\fP constructor parameter only be used for rule methods that do not explicitly set e\&.Severity\&. 
.PP
Definition at line 311 of file DecoratedRuleArgs\&.cs\&.
.SS "Csla\&.Validation\&.DecoratedRuleArgs\&.DecoratedRuleArgs (string propertyName, string friendlyName, \fBRuleSeverity\fP severity, Dictionary< string, object > args)"

.PP
Creates an instance of \fBRuleArgs\fP\&. 
.PP
\fBParameters\fP
.RS 4
\fIpropertyName\fP The name of the property to be validated\&.
.br
\fIfriendlyName\fP A friendly name for the property, which will be used in place of the property name when creating the broken rule description string\&.
.br
\fIseverity\fP Initial default severity for the rule\&.
.br
\fIargs\fP Reference to a Dictionary containing name/value arguments for use by the rule method\&.
.RE
.PP
.PP
The \fBseverity\fP parameter defines only the initial default severity value\&. If the rule changes this value by setting e\&.Severity, then that new value will become the default for all subsequent rule invocations\&. 
.PP
To avoid confusion, it is recommended that the \fBseverity\fP constructor parameter only be used for rule methods that do not explicitly set e\&.Severity\&. 
.PP
Definition at line 340 of file DecoratedRuleArgs\&.cs\&.
.SS "Csla\&.Validation\&.DecoratedRuleArgs\&.DecoratedRuleArgs (string propertyName, \fBRuleSeverity\fP severity, bool stopProcessing, Dictionary< string, object > args)"

.PP
Creates an instance of \fBRuleArgs\fP\&. 
.PP
\fBParameters\fP
.RS 4
\fIpropertyName\fP The name of the property to be validated\&.
.br
\fIseverity\fP The default severity for the rule\&.
.br
\fIstopProcessing\fP Initial default value for the StopProcessing property\&. 
.br
\fIargs\fP Reference to a Dictionary containing name/value arguments for use by the rule method\&.
.RE
.PP
.PP
The \fBseverity\fP and \fBstopProcessing\fP parameters define only the initial default values\&. If the rule changes these values by setting e\&.Severity or e\&.StopProcessing, then the new values will become the default for all subsequent rule invocations\&. 
.PP
To avoid confusion, It is recommended that the \fBseverity\fP and \fBstopProcessing\fP constructor parameters only be used for rule methods that do not explicitly set e\&.Severity or e\&.StopProcessing\&. 
.PP
Definition at line 370 of file DecoratedRuleArgs\&.cs\&.
.SS "Csla\&.Validation\&.DecoratedRuleArgs\&.DecoratedRuleArgs (\fBCore\&.IPropertyInfo\fP propertyInfo, \fBRuleSeverity\fP severity, bool stopProcessing, Dictionary< string, object > args)"

.PP
Creates an instance of \fBRuleArgs\fP\&. 
.PP
\fBParameters\fP
.RS 4
\fIpropertyInfo\fP The \fBPropertyInfo\fP for the property to be validated\&.
.br
\fIseverity\fP The default severity for the rule\&.
.br
\fIstopProcessing\fP Initial default value for the StopProcessing property\&. 
.br
\fIargs\fP Reference to a Dictionary containing name/value arguments for use by the rule method\&.
.RE
.PP
.PP
The \fBseverity\fP and \fBstopProcessing\fP parameters define only the initial default values\&. If the rule changes these values by setting e\&.Severity or e\&.StopProcessing, then the new values will become the default for all subsequent rule invocations\&. 
.PP
To avoid confusion, It is recommended that the \fBseverity\fP and \fBstopProcessing\fP constructor parameters only be used for rule methods that do not explicitly set e\&.Severity or e\&.StopProcessing\&. 
.PP
Definition at line 400 of file DecoratedRuleArgs\&.cs\&.
.SS "Csla\&.Validation\&.DecoratedRuleArgs\&.DecoratedRuleArgs (string propertyName, string friendlyName, \fBRuleSeverity\fP severity, bool stopProcessing, Dictionary< string, object > args)"

.PP
Creates an instance of \fBRuleArgs\fP\&. 
.PP
\fBParameters\fP
.RS 4
\fIpropertyName\fP The name of the property to be validated\&.
.br
\fIfriendlyName\fP A friendly name for the property, which will be used in place of the property name when creating the broken rule description string\&.
.br
\fIseverity\fP The default severity for the rule\&.
.br
\fIstopProcessing\fP Initial default value for the StopProcessing property\&. 
.br
\fIargs\fP Reference to a Dictionary containing name/value arguments for use by the rule method\&.
.RE
.PP
.PP
The \fBseverity\fP and \fBstopProcessing\fP parameters define only the initial default values\&. If the rule changes these values by setting e\&.Severity or e\&.StopProcessing, then the new values will become the default for all subsequent rule invocations\&. 
.PP
To avoid confusion, It is recommended that the \fBseverity\fP and \fBstopProcessing\fP constructor parameters only be used for rule methods that do not explicitly set e\&.Severity or e\&.StopProcessing\&. 
.PP
Definition at line 433 of file DecoratedRuleArgs\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override string Csla\&.Validation\&.DecoratedRuleArgs\&.ToString ()"

.PP
Return a string representation of the object using the rule:// URI format\&. 
.PP
Definition at line 466 of file DecoratedRuleArgs\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "object Csla\&.Validation\&.DecoratedRuleArgs\&.this[string key]\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets an argument value for use by the rule method\&. 
.PP
\fBParameters\fP
.RS 4
\fIkey\fP The name under which the value is stored\&.
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
Definition at line 445 of file DecoratedRuleArgs\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
