.TH "cslalighttest.CslaDataProvider.CustomerContact" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cslalighttest.CslaDataProvider.CustomerContact
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.BusinessBase< CustomerContact >\fP\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBAddBusinessRules\fP ()"
.br
.ti -1c
.RI "void \fBChild_DeleteSelf\fP ()"
.br
.ti -1c
.RI "void \fBChild_Insert\fP ()"
.br
.ti -1c
.RI "void \fBChild_Update\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBId\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBCustomerId\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBFirstName\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBLastName\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBBirthday\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBParentName\fP\fC [get, set]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 20 of file Server/CslaDataProvider/CustomerContact\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override void cslalighttest\&.CslaDataProvider\&.CustomerContact\&.AddBusinessRules ()\fC [protected]\fP"

.PP
Definition at line 106 of file Server/CslaDataProvider/CustomerContact\&.cs\&.
.SS "void cslalighttest\&.CslaDataProvider\&.CustomerContact\&.Child_DeleteSelf ()\fC [protected]\fP"

.PP
Definition at line 120 of file Server/CslaDataProvider/CustomerContact\&.cs\&.
.SS "void cslalighttest\&.CslaDataProvider\&.CustomerContact\&.Child_Insert ()\fC [protected]\fP"

.PP
Definition at line 127 of file Server/CslaDataProvider/CustomerContact\&.cs\&.
.SS "void cslalighttest\&.CslaDataProvider\&.CustomerContact\&.Child_Update ()\fC [protected]\fP"

.PP
Definition at line 136 of file Server/CslaDataProvider/CustomerContact\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "string cslalighttest\&.CslaDataProvider\&.CustomerContact\&.Birthday\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 77 of file Server/CslaDataProvider/CustomerContact\&.cs\&.
.SS "int cslalighttest\&.CslaDataProvider\&.CustomerContact\&.CustomerId\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 38 of file Server/CslaDataProvider/CustomerContact\&.cs\&.
.SS "string cslalighttest\&.CslaDataProvider\&.CustomerContact\&.FirstName\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 51 of file Server/CslaDataProvider/CustomerContact\&.cs\&.
.SS "int cslalighttest\&.CslaDataProvider\&.CustomerContact\&.Id\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 25 of file Server/CslaDataProvider/CustomerContact\&.cs\&.
.SS "string cslalighttest\&.CslaDataProvider\&.CustomerContact\&.LastName\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 64 of file Server/CslaDataProvider/CustomerContact\&.cs\&.
.SS "string cslalighttest\&.CslaDataProvider\&.CustomerContact\&.ParentName\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 94 of file Server/CslaDataProvider/CustomerContact\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
