.TH "Csla.Test.DataAnnotations.Multiple" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.DataAnnotations.Multiple
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.BusinessBase< Multiple >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "string[] \fBGetRules\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBName\fP\fC [get, set]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 132 of file DataAnnotationsTests\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "string [] Csla\&.Test\&.DataAnnotations\&.Multiple\&.GetRules ()"

.PP
Definition at line 150 of file DataAnnotationsTests\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "string Csla\&.Test\&.DataAnnotations\&.Multiple\&.Name\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 138 of file DataAnnotationsTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
