.TH "Csla.Web.Design" 3 "Thu Jul 22 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Web.Design
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCslaDataSourceConfiguration\fP"
.br
.RI "\fBCslaDataSource\fP configuration form\&. "
.ti -1c
.RI "class \fBCslaDataSourceDesigner\fP"
.br
.RI "Implements designer support for \fBCslaDataSource\fP\&. "
.ti -1c
.RI "class \fBCslaDesignerDataSourceView\fP"
.br
.RI "Object responsible for providing details about data binding to a specific CSLA \&.NET object\&. "
.ti -1c
.RI "class \fBObjectFieldInfo\fP"
.br
.RI "Contains schema information for a single object property\&. "
.ti -1c
.RI "class \fBObjectSchema\fP"
.br
.RI "Object providing access to schema information for a business object\&. "
.ti -1c
.RI "class \fBObjectViewSchema\fP"
.br
.RI "Object providing schema information for a business object\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
