.TH "Csla.Test.DataBinding.ChildEntity" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.DataBinding.ChildEntity
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.BusinessBase< ChildEntity >\fP, and \fBCsla\&.BusinessBase< ChildEntity >\fP\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override object \fBGetIdValue\fP ()"
.br
.RI "Override this method to return a unique identifying value for this object\&. "
.ti -1c
.RI "override object \fBGetIdValue\fP ()"
.br
.RI "Override this method to return a unique identifying value for this object\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBID\fP\fC [get]\fP"
.br
.ti -1c
.RI "string \fBFirstName\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBLastName\fP\fC [get, set]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 15 of file csla\&.netcore\&.test/DataBinding/ChildEntity\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override object Csla\&.Test\&.DataBinding\&.ChildEntity\&.GetIdValue ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Override this method to return a unique identifying value for this object\&. 
.PP
Reimplemented from \fBCsla\&.BusinessBase< ChildEntity >\fP\&.
.PP
Definition at line 48 of file csla\&.netcore\&.test/DataBinding/ChildEntity\&.cs\&.
.SS "override object Csla\&.Test\&.DataBinding\&.ChildEntity\&.GetIdValue ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Override this method to return a unique identifying value for this object\&. 
.PP
Reimplemented from \fBCsla\&.BusinessBase< ChildEntity >\fP\&.
.PP
Definition at line 48 of file Csla\&.test/DataPortal/ChildEntity\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "string Csla\&.Test\&.DataBinding\&.ChildEntity\&.FirstName\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 26 of file csla\&.netcore\&.test/DataBinding/ChildEntity\&.cs\&.
.SS "int Csla\&.Test\&.DataBinding\&.ChildEntity\&.ID\fC [get]\fP"

.PP
Definition at line 21 of file csla\&.netcore\&.test/DataBinding/ChildEntity\&.cs\&.
.SS "string Csla\&.Test\&.DataBinding\&.ChildEntity\&.LastName\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 36 of file csla\&.netcore\&.test/DataBinding/ChildEntity\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
