.TH "Csla.Test.ChildChanged.SingleList" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.ChildChanged.SingleList
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.BusinessBindingListBase< SingleList, SingleRoot >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSingleList\fP ()"
.br
.ti -1c
.RI "\fBSingleList\fP (bool child)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 18 of file SingleList\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Csla\&.Test\&.ChildChanged\&.SingleList\&.SingleList ()"

.PP
Definition at line 20 of file SingleList\&.cs\&.
.SS "Csla\&.Test\&.ChildChanged\&.SingleList\&.SingleList (bool child)"

.PP
Definition at line 24 of file SingleList\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
