.TH "Csla.DataPortal< T >" 3 "Thu Jul 22 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.DataPortal< T > \- This is the client-side \fBDataPortal\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.IDataPortal< T >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "T \fBCreate\fP (params object[] criteria)"
.br
.RI "Called by a factory method in a business class to create a new object, which is loaded with default values from the database\&. "
.ti -1c
.RI "async Task< T > \fBCreateAsync\fP (params object[] criteria)"
.br
.RI "Called by a factory method in a business class or by the UI to create a new object, which is loaded with default values from the database\&. "
.ti -1c
.RI "void \fBBeginCreate\fP ()"
.br
.RI "Called by a factory method in a business class or by the UI to create a new object, which is loaded with default values from the database\&. "
.ti -1c
.RI "void \fBBeginCreate\fP (object criteria)"
.br
.RI "Called by a factory method in a business class or by the UI to create a new object, which is loaded with default values from the database\&. "
.ti -1c
.RI "async void \fBBeginCreate\fP (object criteria, object userState)"
.br
.RI "Called by a factory method in a business class or by the UI to create a new object, which is loaded with default values from the database\&. "
.ti -1c
.RI "T \fBFetch\fP (params object[] criteria)"
.br
.RI "Called by a factory method in a business class to Fetch a new object, which is loaded with default values from the database\&. "
.ti -1c
.RI "async Task< T > \fBFetchAsync\fP (params object[] criteria)"
.br
.RI "Called by a factory method in a business class or by the UI to Fetch a new object, which is loaded with default values from the database\&. "
.ti -1c
.RI "void \fBBeginFetch\fP ()"
.br
.RI "Called by a factory method in a business class or by the UI to Fetch a new object, which is loaded with default values from the database\&. "
.ti -1c
.RI "void \fBBeginFetch\fP (object criteria)"
.br
.RI "Called by a factory method in a business class or by the UI to Fetch a new object, which is loaded with default values from the database\&. "
.ti -1c
.RI "async void \fBBeginFetch\fP (object criteria, object userState)"
.br
.RI "Called by a factory method in a business class or by the UI to Fetch a new object, which is loaded with default values from the database\&. "
.ti -1c
.RI "T \fBUpdate\fP (T obj)"
.br
.RI "Called by a factory method in a business class or by the UI to update an object\&. "
.ti -1c
.RI "void \fBBeginUpdate\fP (T obj)"
.br
.RI "Called by a factory method in a business class or by the UI to update an object\&. "
.ti -1c
.RI "async void \fBBeginUpdate\fP (T obj, object userState)"
.br
.RI "Called by a factory method in a business class or by the UI to update an object\&. "
.ti -1c
.RI "async Task< T > \fBUpdateAsync\fP (T obj)"
.br
.RI "Called by a factory method in a business class or by the UI to update an object\&. "
.ti -1c
.RI "void \fBDelete\fP (params object[] criteria)"
.br
.RI "Called by a factory method in a business class or by the UI to delete an object\&. "
.ti -1c
.RI "void \fBBeginDelete\fP (object criteria)"
.br
.RI "Called by a factory method in a business class or by the UI to delete an object\&. "
.ti -1c
.RI "async void \fBBeginDelete\fP (object criteria, object userState)"
.br
.RI "Called by a factory method in a business class or by the UI to delete an object\&. "
.ti -1c
.RI "async Task \fBDeleteAsync\fP (params object[] criteria)"
.br
.RI "Called by a factory method in a business class or by the UI to delete an object\&. "
.ti -1c
.RI "T \fBExecute\fP (T command)"
.br
.RI "Called by a factory method in a business class or by the UI to execute a command object\&. "
.ti -1c
.RI "void \fBBeginExecute\fP (T command)"
.br
.RI "Called by a factory method in a business class or by the UI to execute a command object\&. "
.ti -1c
.RI "async void \fBBeginExecute\fP (T command, object userState)"
.br
.RI "Called by a factory method in a business class or by the UI to execute a command object\&. "
.ti -1c
.RI "async Task< T > \fBExecuteAsync\fP (T command)"
.br
.RI "Called by a factory method in a business class or by the UI to execute a command object\&. "
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static T \fBCreate< T >\fP (params object[] criteria)"
.br
.RI "Called by a factory method in a business class to create a new object, which is loaded with default values from the database\&. "
.ti -1c
.RI "static T \fBCreate< T >\fP ()"
.br
.RI "Called by a factory method in a business class to create a new object, which is loaded with default values from the database\&. "
.ti -1c
.RI "static object \fBCreate\fP (Type objectType, object criteria)"
.br
.RI "Called by a factory method in a business class to create a new object, which is loaded with default values from the database\&. "
.ti -1c
.RI "static void \fBBeginCreate< T >\fP (EventHandler< \fBDataPortalResult\fP< T >> callback)"
.br
.RI "Starts an asynchronous data portal operation to create a business object\&. "
.ti -1c
.RI "static void \fBBeginCreate< T >\fP (EventHandler< \fBDataPortalResult\fP< T >> callback, object userState)"
.br
.RI "Starts an asynchronous data portal operation to create a business object\&. "
.ti -1c
.RI "static void \fBBeginCreate< T >\fP (object criteria, EventHandler< \fBDataPortalResult\fP< T >> callback)"
.br
.RI "Starts an asynchronous data portal operation to create a business object\&. "
.ti -1c
.RI "static void \fBBeginCreate< T >\fP (object criteria, EventHandler< \fBDataPortalResult\fP< T >> callback, object userState)"
.br
.RI "Starts an asynchronous data portal operation to create a business object\&. "
.ti -1c
.RI "static async Task< T > \fBCreateAsync< T >\fP ()"
.br
.RI "Starts an asynchronous data portal operation to create a business object\&. "
.ti -1c
.RI "static async Task< T > \fBCreateAsync< T >\fP (params object[] criteria)"
.br
.RI "Starts an asynchronous data portal operation to create a business object\&. "
.ti -1c
.RI "static T \fBFetch< T >\fP (params object[] criteria)"
.br
.RI "Called by a factory method in a business class to retrieve an object, which is loaded with values from the database\&. "
.ti -1c
.RI "static T \fBFetch< T >\fP ()"
.br
.RI "Called by a factory method in a business class to retrieve an object, which is loaded with values from the database\&. "
.ti -1c
.RI "static void \fBBeginFetch< T >\fP (EventHandler< \fBDataPortalResult\fP< T >> callback)"
.br
.RI "Starts an asynchronous data portal operation to fetch a business object\&. "
.ti -1c
.RI "static void \fBBeginFetch< T >\fP (EventHandler< \fBDataPortalResult\fP< T >> callback, object userState)"
.br
.RI "Starts an asynchronous data portal operation to fetch a business object\&. "
.ti -1c
.RI "static void \fBBeginFetch< T >\fP (object criteria, EventHandler< \fBDataPortalResult\fP< T >> callback)"
.br
.RI "Starts an asynchronous data portal operation to fetch a business object\&. "
.ti -1c
.RI "static void \fBBeginFetch< T >\fP (object criteria, EventHandler< \fBDataPortalResult\fP< T >> callback, object userState)"
.br
.RI "Starts an asynchronous data portal operation to fetch a business object\&. "
.ti -1c
.RI "static async Task< T > \fBFetchAsync< T >\fP ()"
.br
.RI "Starts an asynchronous data portal operation to fetch a business object\&. "
.ti -1c
.RI "static async Task< T > \fBFetchAsync< T >\fP (params object[] criteria)"
.br
.RI "Starts an asynchronous data portal operation to fetch a business object\&. "
.ti -1c
.RI "static T \fBUpdate< T >\fP (T obj)"
.br
.RI "Called by the business object's Save() method to insert, update or delete an object in the database\&. "
.ti -1c
.RI "static void \fBBeginUpdate< T >\fP (T obj, EventHandler< \fBDataPortalResult\fP< T >> callback)"
.br
.RI "Starts an asynchronous data portal operation to update a business object\&. "
.ti -1c
.RI "static void \fBBeginUpdate< T >\fP (T obj, EventHandler< \fBDataPortalResult\fP< T >> callback, object userState)"
.br
.RI "Starts an asynchronous data portal operation to update a business object\&. "
.ti -1c
.RI "static async Task< T > \fBUpdateAsync< T >\fP (T obj)"
.br
.RI "Starts an asynchronous data portal operation to update a business object\&. "
.ti -1c
.RI "static void \fBDelete< T >\fP (params object[] criteria)"
.br
.RI "Called by a Shared (static in C#) method in the business class to cause immediate deletion of a specific object from the database\&. "
.ti -1c
.RI "static void \fBBeginDelete< T >\fP (object criteria, EventHandler< \fBDataPortalResult\fP< T >> callback)"
.br
.RI "Starts an asynchronous data portal operation to delete a business object\&. "
.ti -1c
.RI "static void \fBBeginDelete< T >\fP (object criteria, EventHandler< \fBDataPortalResult\fP< T >> callback, object userState)"
.br
.RI "Starts an asynchronous data portal operation to delete a business object\&. "
.ti -1c
.RI "static async Task \fBDeleteAsync< T >\fP (params object[] criteria)"
.br
.RI "Starts an asynchronous data portal operation to delete a business object\&. "
.ti -1c
.RI "static T \fBExecute< T >\fP (T obj)"
.br
.RI "Called to execute a Command object on the server\&. "
.ti -1c
.RI "static void \fBBeginExecute< T >\fP (T obj, EventHandler< \fBDataPortalResult\fP< T >> callback)"
.br
.RI "Starts an asynchronous data portal operation to execute a command object\&. "
.ti -1c
.RI "static void \fBBeginExecute< T >\fP (T obj, EventHandler< \fBDataPortalResult\fP< T >> callback, object userState)"
.br
.RI "Starts an asynchronous data portal operation to execute a command object\&. "
.ti -1c
.RI "static async Task< T > \fBExecuteAsync< T >\fP (T command)"
.br
.RI "Starts an asynchronous data portal operation to execute a command object\&. "
.ti -1c
.RI "static T \fBCreateChild< T >\fP ()"
.br
.RI "Creates and initializes a new child business object\&. "
.ti -1c
.RI "static T \fBCreateChild< T >\fP (params object[] parameters)"
.br
.RI "Creates and initializes a new child business object\&. "
.ti -1c
.RI "static async Task< T > \fBCreateChildAsync< T >\fP ()"
.br
.RI "Creates and initializes a new child business object\&. "
.ti -1c
.RI "static async Task< T > \fBCreateChildAsync< T >\fP (params object[] parameters)"
.br
.RI "Creates and initializes a new child business object\&. "
.ti -1c
.RI "static T \fBFetchChild< T >\fP ()"
.br
.RI "Creates and loads an existing child business object\&. "
.ti -1c
.RI "static T \fBFetchChild< T >\fP (params object[] parameters)"
.br
.RI "Creates and loads an existing child business object\&. "
.ti -1c
.RI "static async Task< T > \fBFetchChildAsync< T >\fP ()"
.br
.RI "Fetchs and initializes a new child business object\&. "
.ti -1c
.RI "static async Task< T > \fBFetchChildAsync< T >\fP (params object[] parameters)"
.br
.RI "Fetchs and initializes a new child business object\&. "
.ti -1c
.RI "static void \fBUpdateChild\fP (object child)"
.br
.RI "Inserts, updates or deletes an existing child business object\&. "
.ti -1c
.RI "static void \fBUpdateChild\fP (object child, params object[] parameters)"
.br
.RI "Inserts, updates or deletes an existing child business object\&. "
.ti -1c
.RI "static async Task \fBUpdateChildAsync\fP (object child)"
.br
.RI "Inserts, updates or deletes an existing child business object\&. "
.ti -1c
.RI "static async Task \fBUpdateChildAsync\fP (object child, params object[] parameters)"
.br
.RI "Inserts, updates or deletes an existing child business object\&. "
.ti -1c
.RI "static void \fBResetProxyFactory\fP ()"
.br
.RI "Resets the data portal proxy type, so the next data portal call will reload the proxy type based on current configuration values\&. "
.ti -1c
.RI "static void \fBResetProxyType\fP ()"
.br
.RI "Resets the data portal proxy type, so the next data portal call will reload the proxy type based on current configuration values\&. "
.ti -1c
.RI "static void \fBReleaseProxy\fP ()"
.br
.RI "Releases any remote data portal proxy object, so the next data portal call will create a new proxy instance\&. "
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBOnCreateCompleted\fP (\fBDataPortalResult\fP< T > e)"
.br
.RI "Raises the event\&. "
.ti -1c
.RI "virtual void \fBOnFetchCompleted\fP (\fBDataPortalResult\fP< T > e)"
.br
.RI "Raises the event\&. "
.ti -1c
.RI "virtual void \fBOnUpdateCompleted\fP (\fBDataPortalResult\fP< T > e)"
.br
.RI "Raises the event\&. "
.ti -1c
.RI "virtual void \fBOnDeleteCompleted\fP (\fBDataPortalResult\fP< T > e)"
.br
.RI "Raises the event\&. "
.ti -1c
.RI "virtual void \fBOnExecuteCompleted\fP (\fBDataPortalResult\fP< T > e)"
.br
.RI "Raises the ExecuteCompleted event\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "static \fBDataPortalClient\&.IDataPortalProxyFactory\fP \fBProxyFactory\fP\fC [get, set]\fP"
.br
.RI "Gets or sets a reference to a ProxyFactory object that is used to create an instance of the data portal proxy object\&. "
.ti -1c
.RI "static string \fBProxyTypeName\fP\fC [get, set]\fP"
.br
.RI "Gets or sets the assembly qualified type name of the proxy object to be loaded by the data portal\&. "
.ti -1c
.RI "\fBCsla\&.Core\&.ContextDictionary\fP \fBGlobalContext\fP\fC [get, set]\fP"
.br
.RI "Gets a reference to the global context returned from the background thread and/or server\&. "
.in -1c
.SS "Events"

.in +1c
.ti -1c
.RI "static Action< System\&.Object > \fBDataPortalInitInvoke\fP"
.br
.RI "Raised by \fBDataPortal\fP before it starts setting up to call a server-side \fBDataPortal\fP method\&. "
.ti -1c
.RI "static Action< \fBDataPortalEventArgs\fP > \fBDataPortalInvoke\fP"
.br
.RI "Raised by \fBDataPortal\fP prior to calling the requested server-side \fBDataPortal\fP method\&. "
.ti -1c
.RI "static Action< \fBDataPortalEventArgs\fP > \fBDataPortalInvokeComplete\fP"
.br
.RI "Raised by \fBDataPortal\fP after the requested server-side \fBDataPortal\fP method call is complete\&. "
.ti -1c
.RI "EventHandler< \fBDataPortalResult\fP< T > > \fBCreateCompleted\fP"
.br
.RI "Event raised when the operation has completed\&. "
.ti -1c
.RI "EventHandler< \fBDataPortalResult\fP< T > > \fBFetchCompleted\fP"
.br
.RI "Event raised when the operation has completed\&. "
.ti -1c
.RI "EventHandler< \fBDataPortalResult\fP< T > > \fBUpdateCompleted\fP"
.br
.RI "Event raised when the operation has completed\&. "
.ti -1c
.RI "EventHandler< \fBDataPortalResult\fP< T > > \fBDeleteCompleted\fP"
.br
.RI "Event raised when the operation has completed\&. "
.ti -1c
.RI "EventHandler< \fBDataPortalResult\fP< T > > \fBExecuteCompleted\fP"
.br
.RI "Event indicating an execute operation is complete\&. "
.in -1c
.SH "Detailed Description"
.PP 
This is the client-side \fBDataPortal\fP\&. 

Client side data portal used for making asynchronous data portal calls in \&.NET\&.
.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP Type of business object\&. 
.RE
.PP

.PP
Definition at line 23 of file DataPortalT\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void \fBCsla\&.DataPortal\fP< T >\&.BeginCreate ()"

.PP
Called by a factory method in a business class or by the UI to create a new object, which is loaded with default values from the database\&. 
.PP
Implements \fBCsla\&.IDataPortal< T >\fP\&.
.PP
Definition at line 227 of file DataPortalT\&.cs\&.
.SS "void \fBCsla\&.DataPortal\fP< T >\&.BeginCreate (object criteria)"

.PP
Called by a factory method in a business class or by the UI to create a new object, which is loaded with default values from the database\&. 
.PP
\fBParameters\fP
.RS 4
\fIcriteria\fP Object-specific criteria\&.
.RE
.PP

.PP
Implements \fBCsla\&.IDataPortal< T >\fP\&.
.PP
Definition at line 239 of file DataPortalT\&.cs\&.
.SS "async void \fBCsla\&.DataPortal\fP< T >\&.BeginCreate (object criteria, object userState)"

.PP
Called by a factory method in a business class or by the UI to create a new object, which is loaded with default values from the database\&. 
.PP
\fBParameters\fP
.RS 4
\fIcriteria\fP Object-specific criteria\&.
.br
\fIuserState\fP User state data\&.
.RE
.PP

.PP
Implements \fBCsla\&.IDataPortal< T >\fP\&.
.PP
Definition at line 252 of file DataPortalT\&.cs\&.
.SS "static void \fBCsla\&.DataPortal\fP< T >\&.\fBBeginCreate\fP< T > (EventHandler< \fBDataPortalResult\fP< T >> callback)\fC [static]\fP"

.PP
Starts an asynchronous data portal operation to create a business object\&. 
.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP Type of business object to create\&. 
.RE
.PP
\fBParameters\fP
.RS 4
\fIcallback\fP Reference to method that will handle the asynchronous callback when the operation is complete\&. 
.RE
.PP

.PP
\fBType Constraints\fP
.TP
\fIT\fP : \fIIMobileObject\fP
.PP
Definition at line 109 of file DataPortal\&.cs\&.
.SS "static void \fBCsla\&.DataPortal\fP< T >\&.\fBBeginCreate\fP< T > (EventHandler< \fBDataPortalResult\fP< T >> callback, object userState)\fC [static]\fP"

.PP
Starts an asynchronous data portal operation to create a business object\&. 
.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP Type of business object to create\&. 
.RE
.PP
\fBParameters\fP
.RS 4
\fIcallback\fP Reference to method that will handle the asynchronous callback when the operation is complete\&. 
.br
\fIuserState\fP User state object\&.
.RE
.PP

.PP
\fBType Constraints\fP
.TP
\fIT\fP : \fIIMobileObject\fP
.PP
Definition at line 129 of file DataPortal\&.cs\&.
.SS "static void \fBCsla\&.DataPortal\fP< T >\&.\fBBeginCreate\fP< T > (object criteria, EventHandler< \fBDataPortalResult\fP< T >> callback)\fC [static]\fP"

.PP
Starts an asynchronous data portal operation to create a business object\&. 
.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP Type of business object to create\&. 
.RE
.PP
\fBParameters\fP
.RS 4
\fIcriteria\fP Criteria describing the object to create\&. 
.br
\fIcallback\fP Reference to method that will handle the asynchronous callback when the operation is complete\&. 
.RE
.PP

.PP
\fBType Constraints\fP
.TP
\fIT\fP : \fIIMobileObject\fP
.PP
Definition at line 151 of file DataPortal\&.cs\&.
.SS "static void \fBCsla\&.DataPortal\fP< T >\&.\fBBeginCreate\fP< T > (object criteria, EventHandler< \fBDataPortalResult\fP< T >> callback, object userState)\fC [static]\fP"

.PP
Starts an asynchronous data portal operation to create a business object\&. 
.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP Type of business object to create\&. 
.RE
.PP
\fBParameters\fP
.RS 4
\fIcriteria\fP Criteria describing the object to create\&. 
.br
\fIcallback\fP Reference to method that will handle the asynchronous callback when the operation is complete\&. 
.br
\fIuserState\fP User state object\&.
.RE
.PP

.PP
\fBType Constraints\fP
.TP
\fIT\fP : \fIIMobileObject\fP
.PP
Definition at line 174 of file DataPortal\&.cs\&.
.SS "void \fBCsla\&.DataPortal\fP< T >\&.BeginDelete (object criteria)"

.PP
Called by a factory method in a business class or by the UI to delete an object\&. 
.PP
\fBParameters\fP
.RS 4
\fIcriteria\fP Object-specific criteria\&.
.RE
.PP

.PP
Implements \fBCsla\&.IDataPortal< T >\fP\&.
.PP
Definition at line 921 of file DataPortalT\&.cs\&.
.SS "async void \fBCsla\&.DataPortal\fP< T >\&.BeginDelete (object criteria, object userState)"

.PP
Called by a factory method in a business class or by the UI to delete an object\&. 
.PP
\fBParameters\fP
.RS 4
\fIcriteria\fP Object-specific criteria\&.
.br
\fIuserState\fP User state data\&.
.RE
.PP

.PP
Implements \fBCsla\&.IDataPortal< T >\fP\&.
.PP
Definition at line 933 of file DataPortalT\&.cs\&.
.SS "static void \fBCsla\&.DataPortal\fP< T >\&.\fBBeginDelete\fP< T > (object criteria, EventHandler< \fBDataPortalResult\fP< T >> callback)\fC [static]\fP"

.PP
Starts an asynchronous data portal operation to delete a business object\&. 
.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP Type of business object to delete\&. 
.RE
.PP
\fBParameters\fP
.RS 4
\fIcriteria\fP Criteria describing the object to delete\&. 
.br
\fIcallback\fP Reference to method that will handle the asynchronous callback when the operation is complete\&. 
.RE
.PP

.PP
\fBType Constraints\fP
.TP
\fIT\fP : \fIIMobileObject\fP
.PP
Definition at line 472 of file DataPortal\&.cs\&.
.SS "static void \fBCsla\&.DataPortal\fP< T >\&.\fBBeginDelete\fP< T > (object criteria, EventHandler< \fBDataPortalResult\fP< T >> callback, object userState)\fC [static]\fP"

.PP
Starts an asynchronous data portal operation to delete a business object\&. 
.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP Type of business object to delete\&. 
.RE
.PP
\fBParameters\fP
.RS 4
\fIcriteria\fP Criteria describing the object to delete\&. 
.br
\fIcallback\fP Reference to method that will handle the asynchronous callback when the operation is complete\&. 
.br
\fIuserState\fP User state object\&.
.RE
.PP

.PP
\fBType Constraints\fP
.TP
\fIT\fP : \fIIMobileObject\fP
.PP
Definition at line 495 of file DataPortal\&.cs\&.
.SS "void \fBCsla\&.DataPortal\fP< T >\&.BeginExecute (T command)"

.PP
Called by a factory method in a business class or by the UI to execute a command object\&. 
.PP
\fBParameters\fP
.RS 4
\fIcommand\fP Command object to execute\&.
.RE
.PP

.PP
Implements \fBCsla\&.IDataPortal< T >\fP\&.
.PP
Definition at line 995 of file DataPortalT\&.cs\&.
.SS "async void \fBCsla\&.DataPortal\fP< T >\&.BeginExecute (T command, object userState)"

.PP
Called by a factory method in a business class or by the UI to execute a command object\&. 
.PP
\fBParameters\fP
.RS 4
\fIcommand\fP Command object to execute\&.
.br
\fIuserState\fP User state data\&.
.RE
.PP

.PP
Implements \fBCsla\&.IDataPortal< T >\fP\&.
.PP
Definition at line 1007 of file DataPortalT\&.cs\&.
.SS "static void \fBCsla\&.DataPortal\fP< T >\&.\fBBeginExecute\fP< T > (T obj, EventHandler< \fBDataPortalResult\fP< T >> callback)\fC [static]\fP"

.PP
Starts an asynchronous data portal operation to execute a command object\&. 
.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP Type of object to execute\&. 
.RE
.PP
\fBParameters\fP
.RS 4
\fIobj\fP Reference to the object to execute\&. 
.br
\fIcallback\fP Reference to method that will handle the asynchronous callback when the operation is complete\&. 
.RE
.PP

.PP
\fBType Constraints\fP
.TP
\fIT\fP : \fIIMobileObject\fP
.PP
Definition at line 562 of file DataPortal\&.cs\&.
.SS "static void \fBCsla\&.DataPortal\fP< T >\&.\fBBeginExecute\fP< T > (T obj, EventHandler< \fBDataPortalResult\fP< T >> callback, object userState)\fC [static]\fP"

.PP
Starts an asynchronous data portal operation to execute a command object\&. 
.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP Type of object to execute\&. 
.RE
.PP
\fBParameters\fP
.RS 4
\fIobj\fP Reference to the object to execute\&. 
.br
\fIcallback\fP Reference to method that will handle the asynchronous callback when the operation is complete\&. 
.br
\fIuserState\fP User state object\&.
.RE
.PP

.PP
\fBType Constraints\fP
.TP
\fIT\fP : \fIIMobileObject\fP
.PP
Definition at line 585 of file DataPortal\&.cs\&.
.SS "void \fBCsla\&.DataPortal\fP< T >\&.BeginFetch ()"

.PP
Called by a factory method in a business class or by the UI to Fetch a new object, which is loaded with default values from the database\&. 
.PP
Implements \fBCsla\&.IDataPortal< T >\fP\&.
.PP
Definition at line 425 of file DataPortalT\&.cs\&.
.SS "void \fBCsla\&.DataPortal\fP< T >\&.BeginFetch (object criteria)"

.PP
Called by a factory method in a business class or by the UI to Fetch a new object, which is loaded with default values from the database\&. 
.PP
\fBParameters\fP
.RS 4
\fIcriteria\fP Object-specific criteria\&.
.RE
.PP

.PP
Implements \fBCsla\&.IDataPortal< T >\fP\&.
.PP
Definition at line 437 of file DataPortalT\&.cs\&.
.SS "async void \fBCsla\&.DataPortal\fP< T >\&.BeginFetch (object criteria, object userState)"

.PP
Called by a factory method in a business class or by the UI to Fetch a new object, which is loaded with default values from the database\&. 
.PP
\fBParameters\fP
.RS 4
\fIcriteria\fP Object-specific criteria\&.
.br
\fIuserState\fP User state data\&.
.RE
.PP

.PP
Implements \fBCsla\&.IDataPortal< T >\fP\&.
.PP
Definition at line 450 of file DataPortalT\&.cs\&.
.SS "static void \fBCsla\&.DataPortal\fP< T >\&.\fBBeginFetch\fP< T > (EventHandler< \fBDataPortalResult\fP< T >> callback)\fC [static]\fP"

.PP
Starts an asynchronous data portal operation to fetch a business object\&. 
.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP Type of business object to fetch\&. 
.RE
.PP
\fBParameters\fP
.RS 4
\fIcallback\fP Reference to method that will handle the asynchronous callback when the operation is complete\&. 
.RE
.PP

.PP
\fBType Constraints\fP
.TP
\fIT\fP : \fIIMobileObject\fP
.PP
Definition at line 253 of file DataPortal\&.cs\&.
.SS "static void \fBCsla\&.DataPortal\fP< T >\&.\fBBeginFetch\fP< T > (EventHandler< \fBDataPortalResult\fP< T >> callback, object userState)\fC [static]\fP"

.PP
Starts an asynchronous data portal operation to fetch a business object\&. 
.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP Type of business object to fetch\&. 
.RE
.PP
\fBParameters\fP
.RS 4
\fIcallback\fP Reference to method that will handle the asynchronous callback when the operation is complete\&. 
.br
\fIuserState\fP User state object\&.
.RE
.PP

.PP
\fBType Constraints\fP
.TP
\fIT\fP : \fIIMobileObject\fP
.PP
Definition at line 273 of file DataPortal\&.cs\&.
.SS "static void \fBCsla\&.DataPortal\fP< T >\&.\fBBeginFetch\fP< T > (object criteria, EventHandler< \fBDataPortalResult\fP< T >> callback)\fC [static]\fP"

.PP
Starts an asynchronous data portal operation to fetch a business object\&. 
.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP Type of business object to fetch\&. 
.RE
.PP
\fBParameters\fP
.RS 4
\fIcriteria\fP Criteria describing the object to fetch\&. 
.br
\fIcallback\fP Reference to method that will handle the asynchronous callback when the operation is complete\&. 
.RE
.PP

.PP
\fBType Constraints\fP
.TP
\fIT\fP : \fIIMobileObject\fP
.PP
Definition at line 295 of file DataPortal\&.cs\&.
.SS "static void \fBCsla\&.DataPortal\fP< T >\&.\fBBeginFetch\fP< T > (object criteria, EventHandler< \fBDataPortalResult\fP< T >> callback, object userState)\fC [static]\fP"

.PP
Starts an asynchronous data portal operation to fetch a business object\&. 
.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP Type of business object to fetch\&. 
.RE
.PP
\fBParameters\fP
.RS 4
\fIcriteria\fP Criteria describing the object to fetch\&. 
.br
\fIcallback\fP Reference to method that will handle the asynchronous callback when the operation is complete\&. 
.br
\fIuserState\fP User state object\&.
.RE
.PP

.PP
\fBType Constraints\fP
.TP
\fIT\fP : \fIIMobileObject\fP
.PP
Definition at line 318 of file DataPortal\&.cs\&.
.SS "void \fBCsla\&.DataPortal\fP< T >\&.BeginUpdate (T obj)"

.PP
Called by a factory method in a business class or by the UI to update an object\&. 
.PP
\fBParameters\fP
.RS 4
\fIobj\fP Object to update\&.
.RE
.PP

.PP
Implements \fBCsla\&.IDataPortal< T >\fP\&.
.PP
Definition at line 736 of file DataPortalT\&.cs\&.
.SS "async void \fBCsla\&.DataPortal\fP< T >\&.BeginUpdate (T obj, object userState)"

.PP
Called by a factory method in a business class or by the UI to update an object\&. 
.PP
\fBParameters\fP
.RS 4
\fIobj\fP Object to update\&.
.br
\fIuserState\fP User state data\&.
.RE
.PP

.PP
Implements \fBCsla\&.IDataPortal< T >\fP\&.
.PP
Definition at line 748 of file DataPortalT\&.cs\&.
.SS "static void \fBCsla\&.DataPortal\fP< T >\&.\fBBeginUpdate\fP< T > (T obj, EventHandler< \fBDataPortalResult\fP< T >> callback)\fC [static]\fP"

.PP
Starts an asynchronous data portal operation to update a business object\&. 
.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP Type of business object to update\&. 
.RE
.PP
\fBParameters\fP
.RS 4
\fIobj\fP Business object to update\&. 
.br
\fIcallback\fP Reference to method that will handle the asynchronous callback when the operation is complete\&. 
.RE
.PP

.PP
\fBType Constraints\fP
.TP
\fIT\fP : \fIIMobileObject\fP
.PP
Definition at line 392 of file DataPortal\&.cs\&.
.SS "static void \fBCsla\&.DataPortal\fP< T >\&.\fBBeginUpdate\fP< T > (T obj, EventHandler< \fBDataPortalResult\fP< T >> callback, object userState)\fC [static]\fP"

.PP
Starts an asynchronous data portal operation to update a business object\&. 
.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP Type of business object to update\&. 
.RE
.PP
\fBParameters\fP
.RS 4
\fIobj\fP Business object to update\&. 
.br
\fIcallback\fP Reference to method that will handle the asynchronous callback when the operation is complete\&. 
.br
\fIuserState\fP User state object\&.
.RE
.PP

.PP
\fBType Constraints\fP
.TP
\fIT\fP : \fIIMobileObject\fP
.PP
Definition at line 415 of file DataPortal\&.cs\&.
.SS "T \fBCsla\&.DataPortal\fP< T >\&.Create (params object[] criteria)"

.PP
Called by a factory method in a business class to create a new object, which is loaded with default values from the database\&. 
.PP
\fBParameters\fP
.RS 4
\fIcriteria\fP Object-specific criteria\&.
.RE
.PP
\fBReturns\fP
.RS 4
A new object, populated with default values\&.
.RE
.PP

.PP
Implements \fBCsla\&.IDataPortal< T >\fP\&.
.PP
Definition at line 141 of file DataPortalT\&.cs\&.
.SS "static object \fBCsla\&.DataPortal\fP< T >\&.Create (Type objectType, object criteria)\fC [static]\fP"

.PP
Called by a factory method in a business class to create a new object, which is loaded with default values from the database\&. 
.PP
\fBParameters\fP
.RS 4
\fIobjectType\fP Type of business object to create\&.
.br
\fIcriteria\fP Object-specific criteria\&.
.RE
.PP
\fBReturns\fP
.RS 4
A new object, populated with default values\&.
.RE
.PP

.PP
Definition at line 91 of file DataPortal\&.cs\&.
.SS "static T \fBCsla\&.DataPortal\fP< T >\&.\fBCreate\fP< T > ()\fC [static]\fP"

.PP
Called by a factory method in a business class to create a new object, which is loaded with default values from the database\&. 
.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP Specific type of the business object\&.
.RE
.PP
\fBReturns\fP
.RS 4
A new object, populated with default values\&.
.RE
.PP

.PP
Definition at line 78 of file DataPortal\&.cs\&.
.SS "static T \fBCsla\&.DataPortal\fP< T >\&.\fBCreate\fP< T > (params object[] criteria)\fC [static]\fP"

.PP
Called by a factory method in a business class to create a new object, which is loaded with default values from the database\&. 
.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP Specific type of the business object\&.
.RE
.PP
\fBParameters\fP
.RS 4
\fIcriteria\fP Object-specific criteria\&.
.RE
.PP
\fBReturns\fP
.RS 4
A new object, populated with default values\&.
.RE
.PP

.PP
Definition at line 65 of file DataPortal\&.cs\&.
.SS "async Task<T> \fBCsla\&.DataPortal\fP< T >\&.CreateAsync (params object[] criteria)"

.PP
Called by a factory method in a business class or by the UI to create a new object, which is loaded with default values from the database\&. 
.PP
\fBParameters\fP
.RS 4
\fIcriteria\fP Object-specific criteria\&.
.RE
.PP

.PP
Implements \fBCsla\&.IDataPortal< T >\fP\&.
.PP
Definition at line 168 of file DataPortalT\&.cs\&.
.SS "static async Task<T> \fBCsla\&.DataPortal\fP< T >\&.\fBCreateAsync\fP< T > ()\fC [static]\fP"

.PP
Starts an asynchronous data portal operation to create a business object\&. 
.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP Type of business object to create\&. 
.RE
.PP

.PP
Definition at line 189 of file DataPortal\&.cs\&.
.SS "static async Task<T> \fBCsla\&.DataPortal\fP< T >\&.\fBCreateAsync\fP< T > (params object[] criteria)\fC [static]\fP"

.PP
Starts an asynchronous data portal operation to create a business object\&. 
.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP Type of business object to create\&. 
.RE
.PP
\fBParameters\fP
.RS 4
\fIcriteria\fP Criteria describing the object to create\&. 
.RE
.PP

.PP
Definition at line 205 of file DataPortal\&.cs\&.
.SS "static T \fBCsla\&.DataPortal\fP< T >\&.CreateChild< T > ()\fC [static]\fP"

.PP
Creates and initializes a new child business object\&. 
.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP Type of business object to create\&. 
.RE
.PP

.PP
Definition at line 617 of file DataPortal\&.cs\&.
.SS "static T \fBCsla\&.DataPortal\fP< T >\&.CreateChild< T > (params object[] parameters)\fC [static]\fP"

.PP
Creates and initializes a new child business object\&. 
.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP Type of business object to create\&. 
.RE
.PP
\fBParameters\fP
.RS 4
\fIparameters\fP Parameters passed to child create method\&. 
.RE
.PP

.PP
Definition at line 633 of file DataPortal\&.cs\&.
.SS "static async Task<T> \fBCsla\&.DataPortal\fP< T >\&.CreateChildAsync< T > ()\fC [static]\fP"

.PP
Creates and initializes a new child business object\&. 
.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP Type of business object to create\&. 
.RE
.PP

.PP
Definition at line 646 of file DataPortal\&.cs\&.
.SS "static async Task<T> \fBCsla\&.DataPortal\fP< T >\&.CreateChildAsync< T > (params object[] parameters)\fC [static]\fP"

.PP
Creates and initializes a new child business object\&. 
.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP Type of business object to create\&. 
.RE
.PP
\fBParameters\fP
.RS 4
\fIparameters\fP Parameters passed to child create method\&. 
.RE
.PP

.PP
Definition at line 662 of file DataPortal\&.cs\&.
.SS "void \fBCsla\&.DataPortal\fP< T >\&.Delete (params object[] criteria)"

.PP
Called by a factory method in a business class or by the UI to delete an object\&. 
.PP
\fBParameters\fP
.RS 4
\fIcriteria\fP Object-specific criteria\&.
.RE
.PP

.PP
Implements \fBCsla\&.IDataPortal< T >\fP\&.
.PP
Definition at line 890 of file DataPortalT\&.cs\&.
.SS "static void \fBCsla\&.DataPortal\fP< T >\&.Delete< T > (params object[] criteria)\fC [static]\fP"

.PP
Called by a Shared (static in C#) method in the business class to cause immediate deletion of a specific object from the database\&. 
.PP
\fBParameters\fP
.RS 4
\fIcriteria\fP Object-specific criteria\&.
.RE
.PP

.PP
Definition at line 445 of file DataPortal\&.cs\&.
.SS "async Task \fBCsla\&.DataPortal\fP< T >\&.DeleteAsync (params object[] criteria)"

.PP
Called by a factory method in a business class or by the UI to delete an object\&. 
.PP
\fBParameters\fP
.RS 4
\fIcriteria\fP Object-specific criteria\&.
.RE
.PP

.PP
Implements \fBCsla\&.IDataPortal< T >\fP\&.
.PP
Definition at line 958 of file DataPortalT\&.cs\&.
.SS "static async Task \fBCsla\&.DataPortal\fP< T >\&.\fBDeleteAsync\fP< T > (params object[] criteria)\fC [static]\fP"

.PP
Starts an asynchronous data portal operation to delete a business object\&. 
.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP Type of business object to delete\&. 
.RE
.PP
\fBParameters\fP
.RS 4
\fIcriteria\fP Criteria describing the object to delete\&. 
.RE
.PP

.PP
\fBType Constraints\fP
.TP
\fIT\fP : \fIIMobileObject\fP
.PP
Definition at line 513 of file DataPortal\&.cs\&.
.SS "T \fBCsla\&.DataPortal\fP< T >\&.Execute (T command)"

.PP
Called by a factory method in a business class or by the UI to execute a command object\&. 
.PP
\fBParameters\fP
.RS 4
\fIcommand\fP Command object to execute\&.
.RE
.PP

.PP
Implements \fBCsla\&.IDataPortal< T >\fP\&.
.PP
Definition at line 984 of file DataPortalT\&.cs\&.
.SS "static T \fBCsla\&.DataPortal\fP< T >\&.\fBExecute\fP< T > (T obj)\fC [static]\fP"

.PP
Called to execute a Command object on the server\&. To be a Command object, the object must inherit from \fBCommandBase\fP\&. 
.PP
Note that this method returns a reference to the updated business object\&. If the server-side \fBDataPortal\fP is running remotely, this will be a new and different object from the original, and all object references MUST be updated to use this new object\&. 
.PP
On the server, the Command object's DataPortal_Execute() method will be invoked and on an ObjectFactory the Execute method will be invoked\&. Write any server-side code in that method\&. 
.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP Specific type of the Command object\&.
.RE
.PP
\fBParameters\fP
.RS 4
\fIobj\fP A reference to the Command object to be executed\&.
.RE
.PP
\fBReturns\fP
.RS 4
A reference to the updated Command object\&.
.RE
.PP

.PP
Definition at line 541 of file DataPortal\&.cs\&.
.SS "async Task<T> \fBCsla\&.DataPortal\fP< T >\&.ExecuteAsync (T command)"

.PP
Called by a factory method in a business class or by the UI to execute a command object\&. 
.PP
\fBParameters\fP
.RS 4
\fIcommand\fP Command object to execute\&.
.RE
.PP

.PP
Implements \fBCsla\&.IDataPortal< T >\fP\&.
.PP
Definition at line 1032 of file DataPortalT\&.cs\&.
.SS "static async Task<T> \fBCsla\&.DataPortal\fP< T >\&.\fBExecuteAsync\fP< T > (T command)\fC [static]\fP"

.PP
Starts an asynchronous data portal operation to execute a command object\&. 
.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP Type of object to execute\&. 
.RE
.PP
\fBParameters\fP
.RS 4
\fIcommand\fP Reference to the object to execute\&. 
.RE
.PP

.PP
\fBType Constraints\fP
.TP
\fIT\fP : \fIIMobileObject\fP
.PP
Definition at line 603 of file DataPortal\&.cs\&.
.SS "T \fBCsla\&.DataPortal\fP< T >\&.Fetch (params object[] criteria)"

.PP
Called by a factory method in a business class to Fetch a new object, which is loaded with default values from the database\&. 
.PP
\fBParameters\fP
.RS 4
\fIcriteria\fP Object-specific criteria\&.
.RE
.PP
\fBReturns\fP
.RS 4
A new object, populated with default values\&.
.RE
.PP

.PP
Implements \fBCsla\&.IDataPortal< T >\fP\&.
.PP
Definition at line 387 of file DataPortalT\&.cs\&.
.SS "static T \fBCsla\&.DataPortal\fP< T >\&.Fetch< T > ()\fC [static]\fP"

.PP
Called by a factory method in a business class to retrieve an object, which is loaded with values from the database\&. 
.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP Specific type of the business object\&.
.RE
.PP
\fBReturns\fP
.RS 4
An object populated with values from the database\&.
.RE
.PP

.PP
Definition at line 230 of file DataPortal\&.cs\&.
.SS "static T \fBCsla\&.DataPortal\fP< T >\&.Fetch< T > (params object[] criteria)\fC [static]\fP"

.PP
Called by a factory method in a business class to retrieve an object, which is loaded with values from the database\&. 
.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP Specific type of the business object\&.
.RE
.PP
\fBParameters\fP
.RS 4
\fIcriteria\fP Object-specific criteria\&.
.RE
.PP
\fBReturns\fP
.RS 4
An object populated with values from the database\&.
.RE
.PP

.PP
Definition at line 218 of file DataPortal\&.cs\&.
.SS "async Task<T> \fBCsla\&.DataPortal\fP< T >\&.FetchAsync (params object[] criteria)"

.PP
Called by a factory method in a business class or by the UI to Fetch a new object, which is loaded with default values from the database\&. 
.PP
\fBParameters\fP
.RS 4
\fIcriteria\fP Object-specific criteria\&.
.RE
.PP

.PP
Implements \fBCsla\&.IDataPortal< T >\fP\&.
.PP
Definition at line 414 of file DataPortalT\&.cs\&.
.SS "static async Task<T> \fBCsla\&.DataPortal\fP< T >\&.\fBFetchAsync\fP< T > ()\fC [static]\fP"

.PP
Starts an asynchronous data portal operation to fetch a business object\&. 
.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP Type of business object to fetch\&. 
.RE
.PP

.PP
\fBType Constraints\fP
.TP
\fIT\fP : \fIIMobileObject\fP
.PP
Definition at line 333 of file DataPortal\&.cs\&.
.SS "static async Task<T> \fBCsla\&.DataPortal\fP< T >\&.\fBFetchAsync\fP< T > (params object[] criteria)\fC [static]\fP"

.PP
Starts an asynchronous data portal operation to fetch a business object\&. 
.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP Type of business object to fetch\&. 
.RE
.PP
\fBParameters\fP
.RS 4
\fIcriteria\fP Criteria describing the object to fetch\&. 
.RE
.PP

.PP
\fBType Constraints\fP
.TP
\fIT\fP : \fIIMobileObject\fP
.PP
Definition at line 350 of file DataPortal\&.cs\&.
.SS "static T \fBCsla\&.DataPortal\fP< T >\&.FetchChild< T > ()\fC [static]\fP"

.PP
Creates and loads an existing child business object\&. 
.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP Type of business object to retrieve\&. 
.RE
.PP

.PP
Definition at line 675 of file DataPortal\&.cs\&.
.SS "static T \fBCsla\&.DataPortal\fP< T >\&.FetchChild< T > (params object[] parameters)\fC [static]\fP"

.PP
Creates and loads an existing child business object\&. 
.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP Type of business object to retrieve\&. 
.RE
.PP
\fBParameters\fP
.RS 4
\fIparameters\fP Parameters passed to child fetch method\&. 
.RE
.PP

.PP
Definition at line 691 of file DataPortal\&.cs\&.
.SS "static async Task<T> \fBCsla\&.DataPortal\fP< T >\&.FetchChildAsync< T > ()\fC [static]\fP"

.PP
Fetchs and initializes a new child business object\&. 
.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP Type of business object to Fetch\&. 
.RE
.PP

.PP
Definition at line 704 of file DataPortal\&.cs\&.
.SS "static async Task<T> \fBCsla\&.DataPortal\fP< T >\&.FetchChildAsync< T > (params object[] parameters)\fC [static]\fP"

.PP
Fetchs and initializes a new child business object\&. 
.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP Type of business object to Fetch\&. 
.RE
.PP
\fBParameters\fP
.RS 4
\fIparameters\fP Parameters passed to child Fetch method\&. 
.RE
.PP

.PP
Definition at line 720 of file DataPortal\&.cs\&.
.SS "virtual void \fBCsla\&.DataPortal\fP< T >\&.OnCreateCompleted (\fBDataPortalResult\fP< T > e)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Raises the event\&. 
.PP
\fBParameters\fP
.RS 4
\fIe\fP The parameter provided to the event handler\&. 
.RE
.PP
.PP
If your application is running in WPF, this event will be raised on the UI thread automatically\&. 
.PP
If your application is running in \fBWindows\fP Forms, this event will be raised on a background thread\&. If you also set DataPortal\&.SynchronizationObject to a \fBWindows\fP Forms form or control, then the event will be raised on the UI thread automatically\&. 
.PP
In any other environment (such as ASP\&.NET), this event will be raised on a background thread\&. 
.PP
Definition at line 216 of file DataPortalT\&.cs\&.
.SS "virtual void \fBCsla\&.DataPortal\fP< T >\&.OnDeleteCompleted (\fBDataPortalResult\fP< T > e)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Raises the event\&. 
.PP
\fBParameters\fP
.RS 4
\fIe\fP The parameter provided to the event handler\&. 
.RE
.PP
.PP
If your application is running in WPF, this event will be raised on the UI thread automatically\&. 
.PP
If your application is running in \fBWindows\fP Forms, this event will be raised on a background thread\&. If you also set DataPortal\&.SynchronizationObject to a \fBWindows\fP Forms form or control, then the event will be raised on the UI thread automatically\&. 
.PP
In any other environment (such as ASP\&.NET), this event will be raised on a background thread\&. 
.PP
Definition at line 880 of file DataPortalT\&.cs\&.
.SS "virtual void \fBCsla\&.DataPortal\fP< T >\&.OnExecuteCompleted (\fBDataPortalResult\fP< T > e)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Raises the ExecuteCompleted event\&. 
.PP
\fBParameters\fP
.RS 4
\fIe\fP Event arguments\&.
.RE
.PP

.PP
Definition at line 974 of file DataPortalT\&.cs\&.
.SS "virtual void \fBCsla\&.DataPortal\fP< T >\&.OnFetchCompleted (\fBDataPortalResult\fP< T > e)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Raises the event\&. 
.PP
\fBParameters\fP
.RS 4
\fIe\fP The parameter provided to the event handler\&. 
.RE
.PP
.PP
If your application is running in WPF, this event will be raised on the UI thread automatically\&. 
.PP
If your application is running in \fBWindows\fP Forms, this event will be raised on a background thread\&. If you also set DataPortal\&.SynchronizationObject to a \fBWindows\fP Forms form or control, then the event will be raised on the UI thread automatically\&. 
.PP
In any other environment (such as ASP\&.NET), this event will be raised on a background thread\&. 
.PP
Definition at line 375 of file DataPortalT\&.cs\&.
.SS "virtual void \fBCsla\&.DataPortal\fP< T >\&.OnUpdateCompleted (\fBDataPortalResult\fP< T > e)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Raises the event\&. 
.PP
\fBParameters\fP
.RS 4
\fIe\fP The parameter provided to the event handler\&. 
.RE
.PP
.PP
If your application is running in WPF, this event will be raised on the UI thread automatically\&. 
.PP
If your application is running in \fBWindows\fP Forms, this event will be raised on a background thread\&. If you also set DataPortal\&.SynchronizationObject to a \fBWindows\fP Forms form or control, then the event will be raised on the UI thread automatically\&. 
.PP
In any other environment (such as ASP\&.NET), this event will be raised on a background thread\&. 
.PP
Definition at line 705 of file DataPortalT\&.cs\&.
.SS "static void \fBCsla\&.DataPortal\fP< T >\&.ReleaseProxy ()\fC [static]\fP"

.PP
Releases any remote data portal proxy object, so the next data portal call will create a new proxy instance\&. 
.PP
Definition at line 874 of file DataPortal\&.cs\&.
.SS "static void \fBCsla\&.DataPortal\fP< T >\&.ResetProxyFactory ()\fC [static]\fP"

.PP
Resets the data portal proxy type, so the next data portal call will reload the proxy type based on current configuration values\&. 
.PP
Definition at line 849 of file DataPortal\&.cs\&.
.SS "static void \fBCsla\&.DataPortal\fP< T >\&.ResetProxyType ()\fC [static]\fP"

.PP
Resets the data portal proxy type, so the next data portal call will reload the proxy type based on current configuration values\&. 
.PP
Definition at line 859 of file DataPortal\&.cs\&.
.SS "T \fBCsla\&.DataPortal\fP< T >\&.Update (T obj)"

.PP
Called by a factory method in a business class or by the UI to update an object\&. 
.PP
\fBParameters\fP
.RS 4
\fIobj\fP Object to update\&.
.RE
.PP

.PP
Implements \fBCsla\&.IDataPortal< T >\fP\&.
.PP
Definition at line 715 of file DataPortalT\&.cs\&.
.SS "static T \fBCsla\&.DataPortal\fP< T >\&.\fBUpdate\fP< T > (T obj)\fC [static]\fP"

.PP
Called by the business object's Save() method to insert, update or delete an object in the database\&. Note that this method returns a reference to the updated business object\&. If the server-side \fBDataPortal\fP is running remotely, this will be a new and different object from the original, and all object references MUST be updated to use this new object\&. 
.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP Specific type of the business object\&.
.RE
.PP
\fBParameters\fP
.RS 4
\fIobj\fP A reference to the business object to be updated\&.
.RE
.PP
\fBReturns\fP
.RS 4
A reference to the updated business object\&.
.RE
.PP

.PP
Definition at line 370 of file DataPortal\&.cs\&.
.SS "async Task<T> \fBCsla\&.DataPortal\fP< T >\&.UpdateAsync (T obj)"

.PP
Called by a factory method in a business class or by the UI to update an object\&. 
.PP
\fBParameters\fP
.RS 4
\fIobj\fP Object to update\&.
.RE
.PP

.PP
Implements \fBCsla\&.IDataPortal< T >\fP\&.
.PP
Definition at line 773 of file DataPortalT\&.cs\&.
.SS "static async Task<T> \fBCsla\&.DataPortal\fP< T >\&.\fBUpdateAsync\fP< T > (T obj)\fC [static]\fP"

.PP
Starts an asynchronous data portal operation to update a business object\&. 
.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP Type of business object to update\&. 
.RE
.PP
\fBParameters\fP
.RS 4
\fIobj\fP Business object to update\&. 
.RE
.PP

.PP
\fBType Constraints\fP
.TP
\fIT\fP : \fIIMobileObject\fP
.PP
Definition at line 433 of file DataPortal\&.cs\&.
.SS "static void \fBCsla\&.DataPortal\fP< T >\&.UpdateChild (object child)\fC [static]\fP"

.PP
Inserts, updates or deletes an existing child business object\&. 
.PP
\fBParameters\fP
.RS 4
\fIchild\fP Business object to update\&. 
.RE
.PP

.PP
Definition at line 733 of file DataPortal\&.cs\&.
.SS "static void \fBCsla\&.DataPortal\fP< T >\&.UpdateChild (object child, params object[] parameters)\fC [static]\fP"

.PP
Inserts, updates or deletes an existing child business object\&. 
.PP
\fBParameters\fP
.RS 4
\fIchild\fP Business object to update\&. 
.br
\fIparameters\fP Parameters passed to child update method\&. 
.RE
.PP

.PP
Definition at line 749 of file DataPortal\&.cs\&.
.SS "static async Task \fBCsla\&.DataPortal\fP< T >\&.UpdateChildAsync (object child)\fC [static]\fP"

.PP
Inserts, updates or deletes an existing child business object\&. 
.PP
\fBParameters\fP
.RS 4
\fIchild\fP Business object to update\&. 
.RE
.PP

.PP
Definition at line 762 of file DataPortal\&.cs\&.
.SS "static async Task \fBCsla\&.DataPortal\fP< T >\&.UpdateChildAsync (object child, params object[] parameters)\fC [static]\fP"

.PP
Inserts, updates or deletes an existing child business object\&. 
.PP
\fBParameters\fP
.RS 4
\fIchild\fP Business object to update\&. 
.br
\fIparameters\fP Parameters passed to child update method\&. 
.RE
.PP

.PP
Definition at line 778 of file DataPortal\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "\fBCsla\&.Core\&.ContextDictionary\fP \fBCsla\&.DataPortal\fP< T >\&.GlobalContext\fC [get]\fP, \fC [set]\fP"

.PP
Gets a reference to the global context returned from the background thread and/or server\&. 
.PP
Definition at line 29 of file DataPortalT\&.cs\&.
.SS "\fBDataPortalClient\&.IDataPortalProxyFactory\fP \fBCsla\&.DataPortal\fP< T >\&.ProxyFactory\fC [static]\fP, \fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets a reference to a ProxyFactory object that is used to create an instance of the data portal proxy object\&. 
.PP
Definition at line 814 of file DataPortal\&.cs\&.
.SS "string \fBCsla\&.DataPortal\fP< T >\&.ProxyTypeName\fC [static]\fP, \fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the assembly qualified type name of the proxy object to be loaded by the data portal\&. 'Local' is a special value used to indicate that the data portal should run in local mode\&.
.PP
Deprecated: use ApplicationContext\&.DataPortalProxy 
.PP
Definition at line 838 of file DataPortal\&.cs\&.
.SH "Event Documentation"
.PP 
.SS "EventHandler<\fBDataPortalResult\fP<T> > \fBCsla\&.DataPortal\fP< T >\&.CreateCompleted"

.PP
Event raised when the operation has completed\&. If your application is running in WPF, this event will be raised on the UI thread automatically\&. 
.PP
If your application is running in \fBWindows\fP Forms, this event will be raised on a background thread\&. If you also set DataPortal\&.SynchronizationObject to a \fBWindows\fP Forms form or control, then the event will be raised on the UI thread automatically\&. 
.PP
In any other environment (such as ASP\&.NET), this event will be raised on a background thread\&. 
.PP
Definition at line 192 of file DataPortalT\&.cs\&.
.SS "Action<System\&.Object> \fBCsla\&.DataPortal\fP< T >\&.DataPortalInitInvoke\fC [static]\fP"

.PP
Raised by \fBDataPortal\fP before it starts setting up to call a server-side \fBDataPortal\fP method\&. 
.PP
Definition at line 28 of file DataPortal\&.cs\&.
.SS "Action<\fBDataPortalEventArgs\fP> \fBCsla\&.DataPortal\fP< T >\&.DataPortalInvoke\fC [static]\fP"

.PP
Raised by \fBDataPortal\fP prior to calling the requested server-side \fBDataPortal\fP method\&. 
.PP
Definition at line 34 of file DataPortal\&.cs\&.
.SS "Action<\fBDataPortalEventArgs\fP> \fBCsla\&.DataPortal\fP< T >\&.DataPortalInvokeComplete\fC [static]\fP"

.PP
Raised by \fBDataPortal\fP after the requested server-side \fBDataPortal\fP method call is complete\&. 
.PP
Definition at line 40 of file DataPortal\&.cs\&.
.SS "EventHandler<\fBDataPortalResult\fP<T> > \fBCsla\&.DataPortal\fP< T >\&.DeleteCompleted"

.PP
Event raised when the operation has completed\&. If your application is running in WPF, this event will be raised on the UI thread automatically\&. 
.PP
If your application is running in \fBWindows\fP Forms, this event will be raised on a background thread\&. If you also set DataPortal\&.SynchronizationObject to a \fBWindows\fP Forms form or control, then the event will be raised on the UI thread automatically\&. 
.PP
In any other environment (such as ASP\&.NET), this event will be raised on a background thread\&. 
.PP
Definition at line 856 of file DataPortalT\&.cs\&.
.SS "EventHandler<\fBDataPortalResult\fP<T> > \fBCsla\&.DataPortal\fP< T >\&.ExecuteCompleted"

.PP
Event indicating an execute operation is complete\&. 
.PP
Definition at line 967 of file DataPortalT\&.cs\&.
.SS "EventHandler<\fBDataPortalResult\fP<T> > \fBCsla\&.DataPortal\fP< T >\&.FetchCompleted"

.PP
Event raised when the operation has completed\&. If your application is running in WPF, this event will be raised on the UI thread automatically\&. 
.PP
If your application is running in \fBWindows\fP Forms, this event will be raised on a background thread\&. If you also set DataPortal\&.SynchronizationObject to a \fBWindows\fP Forms form or control, then the event will be raised on the UI thread automatically\&. 
.PP
In any other environment (such as ASP\&.NET), this event will be raised on a background thread\&. 
.PP
Definition at line 351 of file DataPortalT\&.cs\&.
.SS "EventHandler<\fBDataPortalResult\fP<T> > \fBCsla\&.DataPortal\fP< T >\&.UpdateCompleted"

.PP
Event raised when the operation has completed\&. If your application is running in WPF, this event will be raised on the UI thread automatically\&. 
.PP
If your application is running in \fBWindows\fP Forms, this event will be raised on a background thread\&. If you also set DataPortal\&.SynchronizationObject to a \fBWindows\fP Forms form or control, then the event will be raised on the UI thread automatically\&. 
.PP
In any other environment (such as ASP\&.NET), this event will be raised on a background thread\&. 
.PP
Definition at line 681 of file DataPortalT\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
