.TH "Csla.Windows.ObjectSaveException" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Windows.ObjectSaveException \- Exception indicating a failure during an object save operation\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits System\&.Exception\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBObjectSaveException\fP ()"
.br
.RI "Creates an instance of the object\&. "
.ti -1c
.RI "\fBObjectSaveException\fP (string message)"
.br
.RI "Creates an instance of the object\&. "
.ti -1c
.RI "\fBObjectSaveException\fP (string message, Exception innerException)"
.br
.RI "Creates an instance of the object\&. "
.ti -1c
.RI "\fBObjectSaveException\fP (Exception innerException)"
.br
.RI "Creates an instance of the object\&. "
.in -1c
.SH "Detailed Description"
.PP 
Exception indicating a failure during an object save operation\&. 


.PP
Definition at line 20 of file ObjectSaveException\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Csla\&.Windows\&.ObjectSaveException\&.ObjectSaveException ()"

.PP
Creates an instance of the object\&. 
.PP
Definition at line 25 of file ObjectSaveException\&.cs\&.
.SS "Csla\&.Windows\&.ObjectSaveException\&.ObjectSaveException (string message)"

.PP
Creates an instance of the object\&. 
.PP
\fBParameters\fP
.RS 4
\fImessage\fP Exception message text\&. 
.RE
.PP

.PP
Definition at line 33 of file ObjectSaveException\&.cs\&.
.SS "Csla\&.Windows\&.ObjectSaveException\&.ObjectSaveException (string message, Exception innerException)"

.PP
Creates an instance of the object\&. 
.PP
\fBParameters\fP
.RS 4
\fImessage\fP Exception message text\&. 
.br
\fIinnerException\fP Reference to an inner exception\&. 
.RE
.PP

.PP
Definition at line 44 of file ObjectSaveException\&.cs\&.
.SS "Csla\&.Windows\&.ObjectSaveException\&.ObjectSaveException (Exception innerException)"

.PP
Creates an instance of the object\&. 
.PP
\fBParameters\fP
.RS 4
\fIinnerException\fP Reference to an inner exception\&. 
.RE
.PP

.PP
Definition at line 52 of file ObjectSaveException\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
