.TH "cslalighttest.CslaDataProvider.CustomerWithErrorList" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cslalighttest.CslaDataProvider.CustomerWithErrorList
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.BusinessListBase< CustomerWithErrorList, CustomerWithError >\fP\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBDataPortal_Fetch\fP ()"
.br
.ti -1c
.RI "void \fBDataPortal_Create\fP ()"
.br
.ti -1c
.RI "void \fBDataPortal_Update\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 20 of file CustomerWithErrorList\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void cslalighttest\&.CslaDataProvider\&.CustomerWithErrorList\&.DataPortal_Create ()\fC [protected]\fP"

.PP
Definition at line 34 of file CustomerWithErrorList\&.cs\&.
.SS "void cslalighttest\&.CslaDataProvider\&.CustomerWithErrorList\&.DataPortal_Fetch ()\fC [protected]\fP"

.PP
Definition at line 24 of file CustomerWithErrorList\&.cs\&.
.SS "void cslalighttest\&.CslaDataProvider\&.CustomerWithErrorList\&.DataPortal_Update ()\fC [protected]\fP"

.PP
Definition at line 40 of file CustomerWithErrorList\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
