.TH "Csla.Test.ChildChanged.Grandchild" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.ChildChanged.Grandchild
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.BusinessBase< Grandchild >\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBName\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBSingleChild\fP \fBChild\fP\fC [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 18 of file Csla\&.test/ChildChanged/GrandChild\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "\fBSingleChild\fP Csla\&.Test\&.ChildChanged\&.Grandchild\&.Child\fC [get]\fP"

.PP
Definition at line 28 of file Csla\&.test/ChildChanged/GrandChild\&.cs\&.
.SS "string Csla\&.Test\&.ChildChanged\&.Grandchild\&.Name\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 21 of file Csla\&.test/ChildChanged/GrandChild\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
