.TH "Csla.WcfPortal.WcfResponse" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.WcfPortal.WcfResponse
.SH SYNOPSIS
.br
.PP
.PP
Inherits object, System\&.Runtime\&.Serialization\&.IExtensibleDataObject, and System\&.ComponentModel\&.INotifyPropertyChanged\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBRaisePropertyChanged\fP (string propertyName)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "System\&.Runtime\&.Serialization\&.ExtensionDataObject \fBExtensionData\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBCsla\&.WcfPortal\&.WcfErrorInfo\fP \fBErrorData\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "byte[] \fBGlobalContext\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "byte[] \fBObjectData\fP\fC [get, set]\fP"
.br
.in -1c
.SS "Events"

.in +1c
.ti -1c
.RI "System\&.ComponentModel\&.PropertyChangedEventHandler \fBPropertyChanged\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 162 of file Reference\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Csla\&.WcfPortal\&.WcfResponse\&.RaisePropertyChanged (string propertyName)\fC [protected]\fP"

.PP
Definition at line 227 of file Reference\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "\fBCsla\&.WcfPortal\&.WcfErrorInfo\fP Csla\&.WcfPortal\&.WcfResponse\&.ErrorData\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 187 of file Reference\&.cs\&.
.SS "System\&.Runtime\&.Serialization\&.ExtensionDataObject Csla\&.WcfPortal\&.WcfResponse\&.ExtensionData\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 177 of file Reference\&.cs\&.
.SS "byte [] Csla\&.WcfPortal\&.WcfResponse\&.GlobalContext\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 200 of file Reference\&.cs\&.
.SS "byte [] Csla\&.WcfPortal\&.WcfResponse\&.ObjectData\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 213 of file Reference\&.cs\&.
.SH "Event Documentation"
.PP 
.SS "System\&.ComponentModel\&.PropertyChangedEventHandler Csla\&.WcfPortal\&.WcfResponse\&.PropertyChanged"

.PP
Definition at line 225 of file Reference\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
