.TH "Csla.Web.Mvc.Test.ModelBinderTest.Child" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Web.Mvc.Test.ModelBinderTest.Child
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.BusinessBase< Child >\fP\&.
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static readonly \fBPropertyInfo\fP< string > \fBAnyStringProperty\fP = RegisterProperty<string>(p => p\&.AnyString)"
.br
.ti -1c
.RI "static readonly \fBPropertyInfo\fP< string > \fBMax5CharsProperty\fP = RegisterProperty<string>(p => p\&.Max5Chars)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBAnyString\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBMax5Chars\fP\fC [get, set]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 17 of file Child\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "readonly \fBPropertyInfo\fP<string> Csla\&.Web\&.Mvc\&.Test\&.ModelBinderTest\&.Child\&.AnyStringProperty = RegisterProperty<string>(p => p\&.AnyString)\fC [static]\fP"

.PP
Definition at line 19 of file Child\&.cs\&.
.SS "readonly \fBPropertyInfo\fP<string> Csla\&.Web\&.Mvc\&.Test\&.ModelBinderTest\&.Child\&.Max5CharsProperty = RegisterProperty<string>(p => p\&.Max5Chars)\fC [static]\fP"

.PP
Definition at line 25 of file Child\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "string Csla\&.Web\&.Mvc\&.Test\&.ModelBinderTest\&.Child\&.AnyString\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 20 of file Child\&.cs\&.
.SS "string Csla\&.Web\&.Mvc\&.Test\&.ModelBinderTest\&.Child\&.Max5Chars\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 27 of file Child\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
