.TH "Csla.Test.Authorization.ChildItem" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.Authorization.ChildItem
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.BusinessBase< ChildItem >\fP\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBAddBusinessRules\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 590 of file AuthTests\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override void Csla\&.Test\&.Authorization\&.ChildItem\&.AddBusinessRules ()\fC [protected]\fP"

.PP
Definition at line 592 of file AuthTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
