.TH "Csla.Configuration.CslaDataPortalConfiguration" 3 "Thu Jul 22 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Configuration.CslaDataPortalConfiguration \- Use this type to configure the settings for the CSLA \&.NET data portal\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCslaDataPortalConfiguration\fP \fBDefaultProxy\fP (Type type, string defaultUrl)"
.br
.RI "Configure the default data portal proxy type and URL\&. "
.ti -1c
.RI "\fBCslaDataPortalConfiguration\fP \fBDefaultProxy\fP (string typeName, string defaultUrl)"
.br
.RI "Configure the default data portal proxy type and URL\&. "
.ti -1c
.RI "\fBCslaDataPortalConfiguration\fP \fBProxyDescriptors\fP (List< Tuple< string, string, string >> descriptors)"
.br
.RI "Adds resource/type to data portal proxy mappings for use by the data portal\&. "
.ti -1c
.RI "\fBCslaDataPortalConfiguration\fP \fBProxyFactoryType\fP (Type type)"
.br
.RI "summary> Sets the full type name (or 'Default') of the data portal proxy factory object to be used to get the DataPortalProxy instance to use when communicating with the data portal server\&. "
.ti -1c
.RI "\fBCslaDataPortalConfiguration\fP \fBProxyFactoryType\fP (string typeName)"
.br
.ti -1c
.RI "\fBCslaDataPortalConfiguration\fP \fBActivatorType\fP (Type type)"
.br
.RI "Sets the type of the IDataPortalActivator provider\&. "
.ti -1c
.RI "\fBCslaDataPortalConfiguration\fP \fBActivatorType\fP (string typeName)"
.br
.RI "Sets the type of the IDataPortalActivator provider\&. "
.ti -1c
.RI "\fBCslaDataPortalConfiguration\fP \fBActivator\fP (\fBServer\&.IDataPortalActivator\fP activator)"
.br
.RI "Sets an instance of the IDataPortalActivator provider\&. "
.ti -1c
.RI "\fBCslaDataPortalConfiguration\fP \fBAuthenticationType\fP (string typeName)"
.br
.RI "Sets the authentication type being used by the CSLA \&.NET framework\&. "
.ti -1c
.RI "\fBCslaDataPortalConfiguration\fP \fBServerAuthorizationProviderType\fP (Type type)"
.br
.RI "Sets the type name to be used for server-side data portal authorization\&. "
.ti -1c
.RI "\fBCslaDataPortalConfiguration\fP \fBServerAuthorizationProviderType\fP (string typeName)"
.br
.RI "Sets the type name to be used for server-side data portal authorization\&. "
.ti -1c
.RI "\fBCslaDataPortalConfiguration\fP \fBInterceptorType\fP (string typeName)"
.br
.RI "Sets the type of interceptor invoked by the data portal for pre- and post-processing of each data portal invocation\&. "
.ti -1c
.RI "\fBCslaDataPortalConfiguration\fP \fBInterceptorType\fP (Type type)"
.br
.RI "Sets the type of interceptor invoked by the data portal for pre- and post-processing of each data portal invocation\&. "
.ti -1c
.RI "\fBCslaDataPortalConfiguration\fP \fBExceptionInspectorType\fP (Type type)"
.br
.RI "Sets the type of the ExceptionInspector class\&. "
.ti -1c
.RI "\fBCslaDataPortalConfiguration\fP \fBExceptionInspectorType\fP (string typeName)"
.br
.RI "Sets the type name of the ExceptionInspector class\&. "
.ti -1c
.RI "\fBCslaDataPortalConfiguration\fP \fBFactoryLoaderType\fP (Type type)"
.br
.RI "Sets the type of the factor loader used to create server-side instances of business object factories when using the FactoryDataPortal model\&. "
.ti -1c
.RI "\fBCslaDataPortalConfiguration\fP \fBFactoryLoaderType\fP (string typeName)"
.br
.RI "Sets the type name of the factor loader used to create server-side instances of business object factories when using the FactoryDataPortal model\&. "
.ti -1c
.RI "\fBCslaDataPortalConfiguration\fP \fBAutoCloneOnUpdate\fP (bool value)"
.br
.RI "Sets a value indicating whether objects should be automatically cloned by the data portal Update() method when using a local data portal configuration\&. "
.ti -1c
.RI "\fBCslaDataPortalConfiguration\fP \fBDataPortalReturnObjectOnException\fP (bool value)"
.br
.RI "Gets or sets a value indicating whether the server-side business object should be returned to the client as part of the \fBDataPortalException\fP\&. "
.ti -1c
.RI "\fBCslaDataPortalConfiguration\fP \fBDashboardType\fP (Type type)"
.br
.RI "Sets the assembly qualified type name of the dashboard, or 'Dashboard' for default, or 'NullDashboard' for the null dashboard\&. "
.ti -1c
.RI "\fBCslaDataPortalConfiguration\fP \fBDashboardType\fP (string typeName)"
.br
.RI "Sets the assembly qualified type name of the dashboard, or 'Dashboard' for default, or 'NullDashboard' for the null dashboard\&. "
.ti -1c
.RI "\fBCslaDataPortalConfiguration\fP \fBFlowSynchronizationContext\fP (bool flow)"
.br
.RI "Sets a value indicating whether any synchronization context should be flowed to child tasks by LocalProxy\&. "
.in -1c
.SH "Detailed Description"
.PP 
Use this type to configure the settings for the CSLA \&.NET data portal\&. 


.PP
Definition at line 31 of file CslaDataPortalConfiguration\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBCslaDataPortalConfiguration\fP Csla\&.Configuration\&.CslaDataPortalConfiguration\&.Activator (\fBServer\&.IDataPortalActivator\fP activator)"

.PP
Sets an instance of the IDataPortalActivator provider\&. 
.PP
\fBParameters\fP
.RS 4
\fIactivator\fP Activator instance
.RE
.PP

.PP
Definition at line 144 of file CslaDataPortalConfiguration\&.cs\&.
.SS "\fBCslaDataPortalConfiguration\fP Csla\&.Configuration\&.CslaDataPortalConfiguration\&.ActivatorType (string typeName)"

.PP
Sets the type of the IDataPortalActivator provider\&. 
.PP
\fBParameters\fP
.RS 4
\fItypeName\fP Assembly qualified type name
.RE
.PP

.PP
Definition at line 134 of file CslaDataPortalConfiguration\&.cs\&.
.SS "\fBCslaDataPortalConfiguration\fP Csla\&.Configuration\&.CslaDataPortalConfiguration\&.ActivatorType (Type type)"

.PP
Sets the type of the IDataPortalActivator provider\&. 
.PP
\fBParameters\fP
.RS 4
\fItype\fP Activator type
.RE
.PP

.PP
Definition at line 124 of file CslaDataPortalConfiguration\&.cs\&.
.SS "\fBCslaDataPortalConfiguration\fP Csla\&.Configuration\&.CslaDataPortalConfiguration\&.AuthenticationType (string typeName)"

.PP
Sets the authentication type being used by the CSLA \&.NET framework\&. 
.PP
\fBParameters\fP
.RS 4
\fItypeName\fP Authentication type value (defaults to '\fBCsla\fP')
.RE
.PP

.PP
Definition at line 155 of file CslaDataPortalConfiguration\&.cs\&.
.SS "\fBCslaDataPortalConfiguration\fP Csla\&.Configuration\&.CslaDataPortalConfiguration\&.AutoCloneOnUpdate (bool value)"

.PP
Sets a value indicating whether objects should be automatically cloned by the data portal Update() method when using a local data portal configuration\&. 
.PP
\fBParameters\fP
.RS 4
\fIvalue\fP Value (defaults to true)
.RE
.PP

.PP
Definition at line 263 of file CslaDataPortalConfiguration\&.cs\&.
.SS "\fBCslaDataPortalConfiguration\fP Csla\&.Configuration\&.CslaDataPortalConfiguration\&.DashboardType (string typeName)"

.PP
Sets the assembly qualified type name of the dashboard, or 'Dashboard' for default, or 'NullDashboard' for the null dashboard\&. 
.PP
\fBParameters\fP
.RS 4
\fItypeName\fP Assembly qualified type name
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
Definition at line 299 of file CslaDataPortalConfiguration\&.cs\&.
.SS "\fBCslaDataPortalConfiguration\fP Csla\&.Configuration\&.CslaDataPortalConfiguration\&.DashboardType (Type type)"

.PP
Sets the assembly qualified type name of the dashboard, or 'Dashboard' for default, or 'NullDashboard' for the null dashboard\&. 
.PP
\fBParameters\fP
.RS 4
\fItype\fP Dashboard type
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
Definition at line 287 of file CslaDataPortalConfiguration\&.cs\&.
.SS "\fBCslaDataPortalConfiguration\fP Csla\&.Configuration\&.CslaDataPortalConfiguration\&.DataPortalReturnObjectOnException (bool value)"

.PP
Gets or sets a value indicating whether the server-side business object should be returned to the client as part of the \fBDataPortalException\fP\&. 
.PP
\fBParameters\fP
.RS 4
\fIvalue\fP Value (default is false)
.RE
.PP

.PP
Definition at line 275 of file CslaDataPortalConfiguration\&.cs\&.
.SS "\fBCslaDataPortalConfiguration\fP Csla\&.Configuration\&.CslaDataPortalConfiguration\&.DefaultProxy (string typeName, string defaultUrl)"

.PP
Configure the default data portal proxy type and URL\&. 
.PP
\fBParameters\fP
.RS 4
\fItypeName\fP Assembly qualified type name
.br
\fIdefaultUrl\fP Default server URL
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
Definition at line 51 of file CslaDataPortalConfiguration\&.cs\&.
.SS "\fBCslaDataPortalConfiguration\fP Csla\&.Configuration\&.CslaDataPortalConfiguration\&.DefaultProxy (Type type, string defaultUrl)"

.PP
Configure the default data portal proxy type and URL\&. 
.PP
\fBParameters\fP
.RS 4
\fItype\fP Type of data portal proxy
.br
\fIdefaultUrl\fP Default server URL
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
Definition at line 39 of file CslaDataPortalConfiguration\&.cs\&.
.SS "\fBCslaDataPortalConfiguration\fP Csla\&.Configuration\&.CslaDataPortalConfiguration\&.ExceptionInspectorType (string typeName)"

.PP
Sets the type name of the ExceptionInspector class\&. Type must implement IDataPortalExceptionInspector\&.
.PP
\fBParameters\fP
.RS 4
\fItypeName\fP Assembly qualified type name
.RE
.PP

.PP
Definition at line 225 of file CslaDataPortalConfiguration\&.cs\&.
.SS "\fBCslaDataPortalConfiguration\fP Csla\&.Configuration\&.CslaDataPortalConfiguration\&.ExceptionInspectorType (Type type)"

.PP
Sets the type of the ExceptionInspector class\&. Type must implement IDataPortalExceptionInspector\&.
.PP
\fBParameters\fP
.RS 4
\fItype\fP Inspector type
.RE
.PP

.PP
Definition at line 214 of file CslaDataPortalConfiguration\&.cs\&.
.SS "\fBCslaDataPortalConfiguration\fP Csla\&.Configuration\&.CslaDataPortalConfiguration\&.FactoryLoaderType (string typeName)"

.PP
Sets the type name of the factor loader used to create server-side instances of business object factories when using the FactoryDataPortal model\&. Type must implement IObjectFactoryLoader\&.
.PP
\fBParameters\fP
.RS 4
\fItypeName\fP Assembly qualified type name
.RE
.PP

.PP
Definition at line 251 of file CslaDataPortalConfiguration\&.cs\&.
.SS "\fBCslaDataPortalConfiguration\fP Csla\&.Configuration\&.CslaDataPortalConfiguration\&.FactoryLoaderType (Type type)"

.PP
Sets the type of the factor loader used to create server-side instances of business object factories when using the FactoryDataPortal model\&. Type must implement IObjectFactoryLoader\&.
.PP
\fBParameters\fP
.RS 4
\fItype\fP Factory loader type
.RE
.PP

.PP
Definition at line 238 of file CslaDataPortalConfiguration\&.cs\&.
.SS "\fBCslaDataPortalConfiguration\fP Csla\&.Configuration\&.CslaDataPortalConfiguration\&.FlowSynchronizationContext (bool flow)"

.PP
Sets a value indicating whether any synchronization context should be flowed to child tasks by LocalProxy\&. Setting this to true may restrict or eliminate the use of background threads by LocalProxy\&.
.PP
\fBParameters\fP
.RS 4
\fIflow\fP True to flow context
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
Definition at line 315 of file CslaDataPortalConfiguration\&.cs\&.
.SS "\fBCslaDataPortalConfiguration\fP Csla\&.Configuration\&.CslaDataPortalConfiguration\&.InterceptorType (string typeName)"

.PP
Sets the type of interceptor invoked by the data portal for pre- and post-processing of each data portal invocation\&. Type must implement IInterceptDataPortal\&.
.PP
\fBParameters\fP
.RS 4
\fItypeName\fP Assembly qualified type name
.RE
.PP

.PP
Definition at line 190 of file CslaDataPortalConfiguration\&.cs\&.
.SS "\fBCslaDataPortalConfiguration\fP Csla\&.Configuration\&.CslaDataPortalConfiguration\&.InterceptorType (Type type)"

.PP
Sets the type of interceptor invoked by the data portal for pre- and post-processing of each data portal invocation\&. Type must implement IInterceptDataPortal\&.
.PP
\fBParameters\fP
.RS 4
\fItype\fP Interceptor type
.RE
.PP

.PP
Definition at line 203 of file CslaDataPortalConfiguration\&.cs\&.
.SS "\fBCslaDataPortalConfiguration\fP Csla\&.Configuration\&.CslaDataPortalConfiguration\&.ProxyDescriptors (List< Tuple< string, string, string >> descriptors)"

.PP
Adds resource/type to data portal proxy mappings for use by the data portal\&. 
.PP
\fBParameters\fP
.RS 4
\fIdescriptors\fP \fBData\fP portal type/resource to proxy mapping
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP
summary> Sets the type for the data portal proxy factory object to be used to get the DataPortalProxy instance to use when communicating with the data portal server\&.
.PP
\fBParameters\fP
.RS 4
\fItype\fP Proxy factory type
.RE
.PP

.PP
Definition at line 64 of file CslaDataPortalConfiguration\&.cs\&.
.SS "\fBCslaDataPortalConfiguration\fP Csla\&.Configuration\&.CslaDataPortalConfiguration\&.ProxyFactoryType (string typeName)"

.PP
Definition at line 114 of file CslaDataPortalConfiguration\&.cs\&.
.SS "\fBCslaDataPortalConfiguration\fP Csla\&.Configuration\&.CslaDataPortalConfiguration\&.ProxyFactoryType (Type type)"

.PP
summary> Sets the full type name (or 'Default') of the data portal proxy factory object to be used to get the DataPortalProxy instance to use when communicating with the data portal server\&. 
.PP
\fBParameters\fP
.RS 4
\fItypeName\fP Assembly qualified type name
.RE
.PP

.PP
Definition at line 101 of file CslaDataPortalConfiguration\&.cs\&.
.SS "\fBCslaDataPortalConfiguration\fP Csla\&.Configuration\&.CslaDataPortalConfiguration\&.ServerAuthorizationProviderType (string typeName)"

.PP
Sets the type name to be used for server-side data portal authorization\&. Type must implement IAuthorizeDataPortal\&.
.PP
\fBParameters\fP
.RS 4
\fItypeName\fP Assembly qualified type name
.RE
.PP

.PP
Definition at line 177 of file CslaDataPortalConfiguration\&.cs\&.
.SS "\fBCslaDataPortalConfiguration\fP Csla\&.Configuration\&.CslaDataPortalConfiguration\&.ServerAuthorizationProviderType (Type type)"

.PP
Sets the type name to be used for server-side data portal authorization\&. Type must implement IAuthorizeDataPortal\&.
.PP
\fBParameters\fP
.RS 4
\fItype\fP Authorization provider type
.RE
.PP

.PP
Definition at line 166 of file CslaDataPortalConfiguration\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
