.TH "Csla.Test.BasicModern.Child" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.BasicModern.Child
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.BusinessBase< Child >\fP, and \fBCsla\&.BusinessBase< Child >\fP\&.
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static readonly \fBPropertyInfo\fP< int > \fBIdProperty\fP = RegisterProperty<int>(nameof(\fBId\fP))"
.br
.ti -1c
.RI "static readonly \fBPropertyInfo\fP< string > \fBNameProperty\fP = RegisterProperty<string>(nameof(\fBName\fP))"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBId\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBName\fP\fC [get, set]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 13 of file Child\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "static readonly \fBPropertyInfo\fP< int > Csla\&.Test\&.BasicModern\&.Child\&.IdProperty = RegisterProperty<int>(nameof(\fBId\fP))\fC [static]\fP"

.PP
Definition at line 15 of file Child\&.cs\&.
.SS "static readonly \fBPropertyInfo\fP< string > Csla\&.Test\&.BasicModern\&.Child\&.NameProperty = RegisterProperty<string>(nameof(\fBName\fP))\fC [static]\fP"

.PP
Definition at line 22 of file Child\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "int Csla\&.Test\&.BasicModern\&.Child\&.Id\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 16 of file Child\&.cs\&.
.SS "string Csla\&.Test\&.BasicModern\&.Child\&.Name\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 24 of file Child\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
