.TH "Csla.Xaml.TriggerAction" 3 "Thu Jul 22 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Xaml.TriggerAction \- Control used to invoke a method on the DataContext based on an event being raised by a UI control\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits FrameworkElement\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTriggerAction\fP ()"
.br
.RI "Creates an instance of the object\&. "
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static readonly DependencyProperty \fBTargetControlProperty\fP"
.br
.RI "Gets or sets the target UI control\&. "
.ti -1c
.RI "static readonly DependencyProperty \fBTriggerEventProperty\fP"
.br
.RI "Gets or sets the name of the event that will trigger the action\&. "
.ti -1c
.RI "static readonly DependencyProperty \fBMethodNameProperty\fP"
.br
.RI "Gets or sets the name of the method to be invoked\&. "
.ti -1c
.RI "static readonly DependencyProperty \fBMethodParameterProperty\fP"
.br
.RI "Gets or sets the value of a parameter to be passed to the invoked method\&. "
.ti -1c
.RI "static readonly DependencyProperty \fBRebindParameterDynamicallyProperty\fP"
.br
.RI "Gets or sets a value indicating whether the MethodParameter value should be dynamically rebound before invoking the target method\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "FrameworkElement \fBTargetControl\fP\fC [get, set]\fP"
.br
.RI "Gets or sets the target UI control\&. "
.ti -1c
.RI "string \fBTriggerEvent\fP\fC [get, set]\fP"
.br
.RI "Gets or sets the name of the event that will trigger the action\&. "
.ti -1c
.RI "string \fBMethodName\fP\fC [get, set]\fP"
.br
.RI "Gets or sets the name of the method to be invoked\&. "
.ti -1c
.RI "object \fBMethodParameter\fP\fC [get, set]\fP"
.br
.RI "Gets or sets the value of a parameter to be passed to the invoked method\&. "
.ti -1c
.RI "bool \fBRebindParameterDynamically\fP\fC [get, set]\fP"
.br
.RI "Gets or sets a value indicating whether the MethodParameter value should be dynamically rebound before invoking the target method\&. "
.in -1c
.SH "Detailed Description"
.PP 
Control used to invoke a method on the DataContext based on an event being raised by a UI control\&. 


.PP
Definition at line 25 of file TriggerAction\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Csla\&.Xaml\&.TriggerAction\&.TriggerAction ()"

.PP
Creates an instance of the object\&. 
.PP
Definition at line 30 of file TriggerAction\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "readonly DependencyProperty Csla\&.Xaml\&.TriggerAction\&.MethodNameProperty\fC [static]\fP"
\fBInitial value:\fP
.PP
.nf
=
      DependencyProperty\&.Register("MethodName", typeof(string),
      typeof(TriggerAction), new PropertyMetadata(null))
.fi
.PP
Gets or sets the name of the method to be invoked\&. 
.PP
Definition at line 199 of file TriggerAction\&.cs\&.
.SS "readonly DependencyProperty Csla\&.Xaml\&.TriggerAction\&.MethodParameterProperty\fC [static]\fP"
\fBInitial value:\fP
.PP
.nf
=
      DependencyProperty\&.Register("MethodParameter", typeof(object),
      typeof(TriggerAction), new PropertyMetadata(null))
.fi
.PP
Gets or sets the value of a parameter to be passed to the invoked method\&. 
.PP
Definition at line 217 of file TriggerAction\&.cs\&.
.SS "readonly DependencyProperty Csla\&.Xaml\&.TriggerAction\&.RebindParameterDynamicallyProperty\fC [static]\fP"
\fBInitial value:\fP
.PP
.nf
=
      DependencyProperty\&.Register("RebindParameterDynamically", typeof(bool),
      typeof(TriggerAction), new PropertyMetadata(null))
.fi
.PP
Gets or sets a value indicating whether the MethodParameter value should be dynamically rebound before invoking the target method\&. 
.PP
Definition at line 236 of file TriggerAction\&.cs\&.
.SS "readonly DependencyProperty Csla\&.Xaml\&.TriggerAction\&.TargetControlProperty\fC [static]\fP"
\fBInitial value:\fP
.PP
.nf
=
      DependencyProperty\&.Register("TargetControl", typeof(FrameworkElement),
      typeof(TriggerAction), new PropertyMetadata((o, e) =>
        {
          var ta = (TriggerAction)o;
          ta\&.HookEvent(
            (FrameworkElement)e\&.OldValue, ta\&.TriggerEvent, (FrameworkElement)e\&.NewValue, ta\&.TriggerEvent);
        }))
.fi
.PP
Gets or sets the target UI control\&. 
.PP
Definition at line 155 of file TriggerAction\&.cs\&.
.SS "readonly DependencyProperty Csla\&.Xaml\&.TriggerAction\&.TriggerEventProperty\fC [static]\fP"
\fBInitial value:\fP
.PP
.nf
=
      DependencyProperty\&.Register("TriggerEvent", typeof(string),
      typeof(TriggerAction), new PropertyMetadata("Click", (o, e) =>
      {
        var ta = (TriggerAction)o;
        ta\&.HookEvent(ta\&.TargetControl, (string)e\&.OldValue, ta\&.TargetControl, (string)e\&.NewValue);
      }))
.fi
.PP
Gets or sets the name of the event that will trigger the action\&. 
.PP
Definition at line 177 of file TriggerAction\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "string Csla\&.Xaml\&.TriggerAction\&.MethodName\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the name of the method to be invoked\&. 
.PP
Definition at line 207 of file TriggerAction\&.cs\&.
.SS "object Csla\&.Xaml\&.TriggerAction\&.MethodParameter\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the value of a parameter to be passed to the invoked method\&. 
.PP
Definition at line 225 of file TriggerAction\&.cs\&.
.SS "bool Csla\&.Xaml\&.TriggerAction\&.RebindParameterDynamically\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets a value indicating whether the MethodParameter value should be dynamically rebound before invoking the target method\&. 
.PP
Definition at line 245 of file TriggerAction\&.cs\&.
.SS "FrameworkElement Csla\&.Xaml\&.TriggerAction\&.TargetControl\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the target UI control\&. 
.PP
Definition at line 167 of file TriggerAction\&.cs\&.
.SS "string Csla\&.Xaml\&.TriggerAction\&.TriggerEvent\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the name of the event that will trigger the action\&. 
.PP
Definition at line 189 of file TriggerAction\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
