.TH "Csla.Xaml.CslaDataProvider" 3 "Thu Jul 22 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Xaml.CslaDataProvider \- Wraps and creates a CSLA \&.NET-style object that you can use as a binding source\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits DataSourceProvider\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCslaDataProvider\fP ()"
.br
.RI "Creates an instance of the object\&. "
.ti -1c
.RI "void \fBRebind\fP ()"
.br
.RI "Triggers WPF data binding to rebind to the data object\&. "
.ti -1c
.RI "void \fBCancel\fP ()"
.br
.RI "Cancels changes to the business object, returning it to its previous state\&. "
.ti -1c
.RI "void \fBSave\fP ()"
.br
.RI "Accepts changes to the business object, and commits them by calling the object's \fBSave()\fP method\&. "
.ti -1c
.RI "object \fBAddNew\fP ()"
.br
.RI "Adds a new item to the object if the object implements IBindingList and AllowNew is true\&. "
.ti -1c
.RI "void \fBRemoveItem\fP (object sender, \fBExecuteEventArgs\fP e)"
.br
.RI "Removes an item from the list if the object implements IBindingList and AllowRemove is true\&. "
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBOnSaved\fP (object newObject, Exception error, object userState)"
.br
.RI "Raise the Saved event when the object has been saved\&. "
.ti -1c
.RI "override void \fBBeginInit\fP ()"
.br
.RI "Indicates that the control is about to initialize\&. "
.ti -1c
.RI "override void \fBEndInit\fP ()"
.br
.RI "Indicates that the control has initialized\&. "
.ti -1c
.RI "override void \fBBeginQuery\fP ()"
.br
.RI "Overridden\&. Starts to create the requested object, either immediately or on a background thread, based on the value of the IsAsynchronous property\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBCslaDataProviderCommandManager\fP \fBCommandManager\fP\fC [get]\fP"
.br
.RI "Gets an object that can be used to execute Save and Undo commands on this \fBCslaDataProvider\fP through XAML command bindings\&. "
.ti -1c
.RI "Type \fBObjectType\fP\fC [get, set]\fP"
.br
.RI "Gets or sets the type of object to create an instance of\&. "
.ti -1c
.RI "bool \fBManageObjectLifetime\fP\fC [get, set]\fP"
.br
.RI "Gets or sets a value indicating whether the data control should manage the lifetime of the business object, including using n-level undo\&. "
.ti -1c
.RI "object \fBDataChangedHandler\fP\fC [get, set]\fP"
.br
.RI "Gets or sets a reference to an object that will handle the DataChanged event raised by this data provider\&. "
.ti -1c
.RI "string \fBFactoryMethod\fP\fC [get, set]\fP"
.br
.RI "Gets or sets the name of the static (Shared in Visual Basic) factory method that should be called to create the object instance\&. "
.ti -1c
.RI "IList \fBFactoryParameters\fP\fC [get]\fP"
.br
.RI "Get the list of parameters to pass to the factory method\&. "
.ti -1c
.RI "bool \fBIsAsynchronous\fP\fC [get, set]\fP"
.br
.RI "Gets or sets a value that indicates whether to perform object creation in a worker thread or in the active context\&. "
.ti -1c
.RI "object \fBObjectInstance\fP\fC [get, set]\fP"
.br
.RI "Gets or sets a reference to the data object\&. "
.ti -1c
.RI "bool \fBIsBusy\fP\fC [get, protected set]\fP"
.br
.RI "Gets a value indicating if this object is busy\&. "
.in -1c
.SS "Events"

.in +1c
.ti -1c
.RI "EventHandler< \fBCsla\&.Core\&.SavedEventArgs\fP > \fBSaved\fP"
.br
.RI "Event raised when the object has been saved\&. "
.in -1c
.SH "Detailed Description"
.PP 
Wraps and creates a CSLA \&.NET-style object that you can use as a binding source\&. 


.PP
Definition at line 25 of file CslaDataProvider\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Csla\&.Xaml\&.CslaDataProvider\&.CslaDataProvider ()"

.PP
Creates an instance of the object\&. 
.PP
Definition at line 31 of file CslaDataProvider\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "object Csla\&.Xaml\&.CslaDataProvider\&.AddNew ()"

.PP
Adds a new item to the object if the object implements IBindingList and AllowNew is true\&. 
.PP
Definition at line 532 of file CslaDataProvider\&.cs\&.
.SS "override void Csla\&.Xaml\&.CslaDataProvider\&.BeginInit ()\fC [protected]\fP"

.PP
Indicates that the control is about to initialize\&. 
.PP
Definition at line 241 of file CslaDataProvider\&.cs\&.
.SS "override void Csla\&.Xaml\&.CslaDataProvider\&.BeginQuery ()\fC [protected]\fP"

.PP
Overridden\&. Starts to create the requested object, either immediately or on a background thread, based on the value of the IsAsynchronous property\&. 
.PP
Definition at line 262 of file CslaDataProvider\&.cs\&.
.SS "void Csla\&.Xaml\&.CslaDataProvider\&.Cancel ()"

.PP
Cancels changes to the business object, returning it to its previous state\&. This metod does nothing unless ManageLifetime is set to true and the object supports n-level undo\&. 
.PP
Definition at line 442 of file CslaDataProvider\&.cs\&.
.SS "override void Csla\&.Xaml\&.CslaDataProvider\&.EndInit ()\fC [protected]\fP"

.PP
Indicates that the control has initialized\&. 
.PP
Definition at line 250 of file CslaDataProvider\&.cs\&.
.SS "virtual void Csla\&.Xaml\&.CslaDataProvider\&.OnSaved (object newObject, Exception error, object userState)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Raise the Saved event when the object has been saved\&. 
.PP
\fBParameters\fP
.RS 4
\fInewObject\fP New object reference as a result of the save operation\&.
.br
\fIerror\fP Reference to an exception object if an error occurred\&.
.br
\fIuserState\fP Reference to a userstate object\&.
.RE
.PP

.PP
Definition at line 51 of file CslaDataProvider\&.cs\&.
.SS "void Csla\&.Xaml\&.CslaDataProvider\&.Rebind ()"

.PP
Triggers WPF data binding to rebind to the data object\&. 
.PP
Definition at line 222 of file CslaDataProvider\&.cs\&.
.SS "void Csla\&.Xaml\&.CslaDataProvider\&.RemoveItem (object sender, \fBExecuteEventArgs\fP e)"

.PP
Removes an item from the list if the object implements IBindingList and AllowRemove is true\&. 
.PP
\fBParameters\fP
.RS 4
\fIsender\fP Object invoking this method\&.
.br
\fIe\fP \fBExecuteEventArgs\fP, where MethodParameter contains the item to be removed from the list\&. 
.RE
.PP

.PP
Definition at line 553 of file CslaDataProvider\&.cs\&.
.SS "void Csla\&.Xaml\&.CslaDataProvider\&.Save ()"

.PP
Accepts changes to the business object, and commits them by calling the object's \fBSave()\fP method\&. This method does nothing unless the object implements \fBCsla\&.Core\&.ISavable\fP\&. 
.PP
If the object implements IClonable, it will be cloned, and the clone will be saved\&. 
.PP
If the object supports n-level undo and ManageLifetime is true, then this method will automatically call ApplyEdit() and BeginEdit() appropriately\&. 
.PP
Definition at line 474 of file CslaDataProvider\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "\fBCslaDataProviderCommandManager\fP Csla\&.Xaml\&.CslaDataProvider\&.CommandManager\fC [get]\fP"

.PP
Gets an object that can be used to execute Save and Undo commands on this \fBCslaDataProvider\fP through XAML command bindings\&. 
.PP
Definition at line 78 of file CslaDataProvider\&.cs\&.
.SS "object Csla\&.Xaml\&.CslaDataProvider\&.DataChangedHandler\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets a reference to an object that will handle the DataChanged event raised by this data provider\&. This property is designed to reference an \fBIErrorDialog\fP control\&. 
.PP
Definition at line 133 of file CslaDataProvider\&.cs\&.
.SS "string Csla\&.Xaml\&.CslaDataProvider\&.FactoryMethod\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the name of the static (Shared in Visual Basic) factory method that should be called to create the object instance\&. 
.PP
Definition at line 155 of file CslaDataProvider\&.cs\&.
.SS "IList Csla\&.Xaml\&.CslaDataProvider\&.FactoryParameters\fC [get]\fP"

.PP
Get the list of parameters to pass to the factory method\&. 
.PP
Definition at line 172 of file CslaDataProvider\&.cs\&.
.SS "bool Csla\&.Xaml\&.CslaDataProvider\&.IsAsynchronous\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets a value that indicates whether to perform object creation in a worker thread or in the active context\&. 
.PP
Definition at line 185 of file CslaDataProvider\&.cs\&.
.SS "bool Csla\&.Xaml\&.CslaDataProvider\&.IsBusy\fC [get]\fP, \fC [protected set]\fP"

.PP
Gets a value indicating if this object is busy\&. 
.PP
Definition at line 208 of file CslaDataProvider\&.cs\&.
.SS "bool Csla\&.Xaml\&.CslaDataProvider\&.ManageObjectLifetime\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets a value indicating whether the data control should manage the lifetime of the business object, including using n-level undo\&. 
.PP
Definition at line 109 of file CslaDataProvider\&.cs\&.
.SS "object Csla\&.Xaml\&.CslaDataProvider\&.ObjectInstance\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets a reference to the data object\&. 
.PP
Definition at line 195 of file CslaDataProvider\&.cs\&.
.SS "Type Csla\&.Xaml\&.CslaDataProvider\&.ObjectType\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the type of object to create an instance of\&. 
.PP
Definition at line 90 of file CslaDataProvider\&.cs\&.
.SH "Event Documentation"
.PP 
.SS "EventHandler<\fBCsla\&.Core\&.SavedEventArgs\fP> Csla\&.Xaml\&.CslaDataProvider\&.Saved"

.PP
Event raised when the object has been saved\&. 
.PP
Definition at line 42 of file CslaDataProvider\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
