.TH "Csla.Test.MethodCaller.CreateConstructorTests.NonPublic1" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.MethodCaller.CreateConstructorTests.NonPublic1
.SH SYNOPSIS
.br
.PP
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBNonPublic1\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 52 of file CreateConstructorTests\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Csla\&.Test\&.MethodCaller\&.CreateConstructorTests\&.NonPublic1\&.NonPublic1 ()\fC [protected]\fP"

.PP
Definition at line 54 of file CreateConstructorTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
