.TH "Csla.Blazor.Test.Fakes.FakePersonEmailAddress" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Blazor.Test.Fakes.FakePersonEmailAddress
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.BusinessBase< FakePersonEmailAddress >\fP\&.
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBCsla\&.PropertyInfo\fP< string > \fBEmailAddressProperty\fP = RegisterProperty<string>(nameof(\fBEmailAddress\fP))"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBEmailAddress\fP\fC [get, set]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 8 of file FakePersonEmailAddress\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBCsla\&.PropertyInfo\fP<string> Csla\&.Blazor\&.Test\&.Fakes\&.FakePersonEmailAddress\&.EmailAddressProperty = RegisterProperty<string>(nameof(\fBEmailAddress\fP))\fC [static]\fP"

.PP
Definition at line 10 of file FakePersonEmailAddress\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "string Csla\&.Blazor\&.Test\&.Fakes\&.FakePersonEmailAddress\&.EmailAddress\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 16 of file FakePersonEmailAddress\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
