.TH "cslalighttest.Serialization.Address" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cslalighttest.Serialization.Address
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBcslalighttest\&.Serialization\&.AddressBase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAddress\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static readonly \fBPropertyInfo\fP< string > \fBZipCodeProperty\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBZipCode\fP\fC [get, set]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 15 of file Address\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "cslalighttest\&.Serialization\&.Address\&.Address ()"

.PP
Definition at line 17 of file Address\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "readonly \fBPropertyInfo\fP<string> cslalighttest\&.Serialization\&.Address\&.ZipCodeProperty\fC [static]\fP"
\fBInitial value:\fP
.PP
.nf
= RegisterProperty(
      typeof(Address),
      new PropertyInfo<string>("ZipCode"))
.fi
.PP
Definition at line 21 of file Address\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "string cslalighttest\&.Serialization\&.Address\&.ZipCode\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 25 of file Address\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
