.TH "Csla.Test.DataPortal.TestMethods" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.DataPortal.TestMethods
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBMethod1\fP (int id, [Inject] \fBISpeak\fP speaker)"
.br
.ti -1c
.RI "string \fBGetSpeech\fP (int id, [Inject] \fBISpeak\fP speaker)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 75 of file ServiceProviderInvocationTests\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "string Csla\&.Test\&.DataPortal\&.TestMethods\&.GetSpeech (int id, [Inject] \fBISpeak\fP speaker)"

.PP
Definition at line 82 of file ServiceProviderInvocationTests\&.cs\&.
.SS "bool Csla\&.Test\&.DataPortal\&.TestMethods\&.Method1 (int id, [Inject] \fBISpeak\fP speaker)"

.PP
Definition at line 77 of file ServiceProviderInvocationTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
