.TH "Csla.Testing.Business.Validation.ИзилдрRule" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Testing.Business.Validation.ИзилдрRule
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.Rules\&.BusinessRule\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBИзилдрRule\fP (\fBIPropertyInfo\fP property)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 10 of file RuleWithCyrillic\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Csla\&.Testing\&.Business\&.Validation\&.ИзилдрRule\&.ИзилдрRule (\fBIPropertyInfo\fP property)"

.PP
Definition at line 12 of file RuleWithCyrillic\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
