.TH "Csla.Core.IMemberInfo" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Core.IMemberInfo \- Maintains metadata about a method or property\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBCsla\&.Core\&.IPropertyInfo\fP, and \fBCsla\&.MethodInfo\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBName\fP\fC [get]\fP"
.br
.RI "Gets the member name value\&. "
.in -1c
.SH "Detailed Description"
.PP 
Maintains metadata about a method or property\&. 


.PP
Definition at line 18 of file IMemberInfo\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "string Csla\&.Core\&.IMemberInfo\&.Name\fC [get]\fP"

.PP
Gets the member name value\&. 
.PP
Definition at line 23 of file IMemberInfo\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
