.TH "Csla.Xaml.PropertyStatus" 3 "Thu Jul 22 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Xaml.PropertyStatus \- Displays validation information for a business object property, and manipulates an associated UI control based on the business object's authorization rules\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits ContentControl, and System\&.ComponentModel\&.INotifyPropertyChanged\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPropertyStatus\fP ()"
.br
.RI "Creates an instance of the object\&. "
.ti -1c
.RI "override void \fBOnApplyTemplate\fP ()"
.br
.RI "Applies the visual template\&. "
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static readonly DependencyProperty \fBPropertyProperty\fP"
.br
.RI "Gets or sets the source business property to which this control is bound\&. "
.ti -1c
.RI "static readonly DependencyProperty \fBBrokenRulesProperty\fP"
.br
.RI "Gets the broken rules collection from the business object\&. "
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBSetSource\fP (bool propertyValueChanged)"
.br
.RI "Sets the source binding and updates status\&. "
.ti -1c
.RI "virtual void \fBSetSource\fP (object dataItem)"
.br
.RI "Sets the source binding and updates status\&. "
.ti -1c
.RI "object \fBGetRealSource\fP (object source, string bindingPath)"
.br
.RI "Gets the real source helper method\&. "
.ti -1c
.RI "virtual void \fBUpdateState\fP ()"
.br
.RI "Updates the state on control Property\&. "
.ti -1c
.RI "virtual void \fBClearState\fP ()"
.br
.RI "Clears the state\&. Must be called whenever the DataContext is updated (and new object is selected)\&. "
.ti -1c
.RI "virtual void \fBGoToState\fP (bool useTransitions)"
.br
.RI "Updates the status of the Property in UI "
.ti -1c
.RI "DependencyObject \fBFindChild\fP (DependencyObject parent, string name)"
.br
.RI "Find child dependency property\&. "
.ti -1c
.RI "virtual void \fBOnPropertyChanged\fP (string propertyName)"
.br
.RI "Raises the PropertyChanged event\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "bool \fBIsReadOnly\fP\fC [get, set]\fP"
.br
.RI "Gets or sets a value indicating whether this DependencyProperty field is read only\&. "
.ti -1c
.RI "object \fBProperty\fP\fC [get, set]\fP"
.br
.RI "Gets or sets the source business property to which this control is bound\&. "
.ti -1c
.RI "object \fBSource\fP\fC [get, set]\fP"
.br
.RI "Gets or sets the Source\&. "
.ti -1c
.RI "string \fBBindingPath\fP\fC [get, set]\fP"
.br
.RI "Gets or sets the binding path\&. "
.ti -1c
.RI "string \fBPropertyName\fP\fC [get, set]\fP"
.br
.RI "Gets or sets the name of the property\&. "
.ti -1c
.RI "ObservableCollection< \fBBrokenRule\fP > \fBBrokenRules\fP\fC [get]\fP"
.br
.RI "Gets the broken rules collection from the business object\&. "
.ti -1c
.RI "bool \fBCanRead\fP\fC [get, protected set]\fP"
.br
.RI "Gets a value indicating whether the user is authorized to read the property\&. "
.ti -1c
.RI "bool \fBCanWrite\fP\fC [get, protected set]\fP"
.br
.RI "Gets a value indicating whether the user is authorized to write the property\&. "
.ti -1c
.RI "bool \fBIsBusy\fP\fC [get]\fP"
.br
.RI "Gets a value indicating whether the property is busy with an asynchronous operation\&. "
.ti -1c
.RI "bool \fBIsValid\fP\fC [get]\fP"
.br
.RI "Gets a value indicating whether the property is valid\&. "
.ti -1c
.RI "\fBRuleSeverity\fP \fBRuleSeverity\fP\fC [get]\fP"
.br
.RI "Gets a valud indicating the worst severity of all broken rules for this property (if IsValid is false)\&. "
.ti -1c
.RI "string \fBRuleDescription\fP\fC [get]\fP"
.br
.RI "Gets the description of the most severe broken rule for this property\&. "
.in -1c
.SS "Events"

.in +1c
.ti -1c
.RI "PropertyChangedEventHandler \fBPropertyChanged\fP"
.br
.RI "Event raised when a property has changed\&. "
.in -1c
.SH "Detailed Description"
.PP 
Displays validation information for a business object property, and manipulates an associated UI control based on the business object's authorization rules\&. 


.PP
Definition at line 37 of file PropertyStatus\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Csla\&.Xaml\&.PropertyStatus\&.PropertyStatus ()"

.PP
Creates an instance of the object\&. 
.PP
Definition at line 72 of file PropertyStatus\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual void Csla\&.Xaml\&.PropertyStatus\&.ClearState ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Clears the state\&. Must be called whenever the DataContext is updated (and new object is selected)\&. 
.PP
Definition at line 628 of file PropertyStatus\&.cs\&.
.SS "DependencyObject Csla\&.Xaml\&.PropertyStatus\&.FindChild (DependencyObject parent, string name)\fC [protected]\fP"

.PP
Find child dependency property\&. 
.PP
\fBParameters\fP
.RS 4
\fIparent\fP The parent\&.
.br
\fIname\fP The name\&.
.RE
.PP
\fBReturns\fP
.RS 4
DependencyObject child
.RE
.PP

.PP
Definition at line 678 of file PropertyStatus\&.cs\&.
.SS "object Csla\&.Xaml\&.PropertyStatus\&.GetRealSource (object source, string bindingPath)\fC [protected]\fP"

.PP
Gets the real source helper method\&. 
.PP
\fBParameters\fP
.RS 4
\fIsource\fP The source\&.
.br
\fIbindingPath\fP The binding path\&.
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
Definition at line 264 of file PropertyStatus\&.cs\&.
.SS "virtual void Csla\&.Xaml\&.PropertyStatus\&.GoToState (bool useTransitions)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Updates the status of the Property in UI 
.PP
\fBParameters\fP
.RS 4
\fIuseTransitions\fP if set to \fCtrue\fP then use transitions\&.
.RE
.PP

.PP
Definition at line 639 of file PropertyStatus\&.cs\&.
.SS "override void Csla\&.Xaml\&.PropertyStatus\&.OnApplyTemplate ()"

.PP
Applies the visual template\&. 
.PP
Definition at line 106 of file PropertyStatus\&.cs\&.
.SS "virtual void Csla\&.Xaml\&.PropertyStatus\&.OnPropertyChanged (string propertyName)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Raises the PropertyChanged event\&. 
.PP
\fBParameters\fP
.RS 4
\fIpropertyName\fP Name of the changed property\&.
.RE
.PP

.PP
Definition at line 710 of file PropertyStatus\&.cs\&.
.SS "virtual void Csla\&.Xaml\&.PropertyStatus\&.SetSource (bool propertyValueChanged)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Sets the source binding and updates status\&. 
.PP
Definition at line 201 of file PropertyStatus\&.cs\&.
.SS "virtual void Csla\&.Xaml\&.PropertyStatus\&.SetSource (object dataItem)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Sets the source binding and updates status\&. 
.PP
Definition at line 214 of file PropertyStatus\&.cs\&.
.SS "virtual void Csla\&.Xaml\&.PropertyStatus\&.UpdateState ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Updates the state on control Property\&. 
.PP
Definition at line 545 of file PropertyStatus\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "readonly DependencyProperty Csla\&.Xaml\&.PropertyStatus\&.BrokenRulesProperty\fC [static]\fP"
\fBInitial value:\fP
.PP
.nf
= DependencyProperty\&.Register(
      "BrokenRules",
      typeof(ObservableCollection<BrokenRule>),
      typeof(PropertyStatus),
      null)
.fi
.PP
Gets the broken rules collection from the business object\&. 
.PP
Definition at line 338 of file PropertyStatus\&.cs\&.
.SS "readonly DependencyProperty Csla\&.Xaml\&.PropertyStatus\&.PropertyProperty\fC [static]\fP"
\fBInitial value:\fP
.PP
.nf
= DependencyProperty\&.Register(
      "Property",
      typeof(object),
      typeof(PropertyStatus),
      new PropertyMetadata(new object(), (o, e) =>
      {
        bool changed = true;
        if (e\&.NewValue == null)
        {
          if (e\&.OldValue == null)
            changed = false;
        }
        else if (e\&.NewValue\&.Equals(e\&.OldValue))
        {
          changed = false;
        }
        ((PropertyStatus)o)\&.SetSource(changed);
      }))
.fi
.PP
Gets or sets the source business property to which this control is bound\&. 
.PP
Definition at line 120 of file PropertyStatus\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "string Csla\&.Xaml\&.PropertyStatus\&.BindingPath\fC [get]\fP, \fC [set]\fP, \fC [protected]\fP"

.PP
Gets or sets the binding path\&. The binding path\&.
.PP
Definition at line 172 of file PropertyStatus\&.cs\&.
.SS "ObservableCollection<\fBBrokenRule\fP> Csla\&.Xaml\&.PropertyStatus\&.BrokenRules\fC [get]\fP"

.PP
Gets the broken rules collection from the business object\&. 
.PP
Definition at line 349 of file PropertyStatus\&.cs\&.
.SS "bool Csla\&.Xaml\&.PropertyStatus\&.CanRead\fC [get]\fP, \fC [protected set]\fP"

.PP
Gets a value indicating whether the user is authorized to read the property\&. 
.PP
Definition at line 365 of file PropertyStatus\&.cs\&.
.SS "bool Csla\&.Xaml\&.PropertyStatus\&.CanWrite\fC [get]\fP, \fC [protected set]\fP"

.PP
Gets a value indicating whether the user is authorized to write the property\&. 
.PP
Definition at line 384 of file PropertyStatus\&.cs\&.
.SS "bool Csla\&.Xaml\&.PropertyStatus\&.IsBusy\fC [get]\fP"

.PP
Gets a value indicating whether the property is busy with an asynchronous operation\&. 
.PP
Definition at line 403 of file PropertyStatus\&.cs\&.
.SS "bool Csla\&.Xaml\&.PropertyStatus\&.IsReadOnly\fC [get]\fP, \fC [set]\fP, \fC [protected]\fP"

.PP
Gets or sets a value indicating whether this DependencyProperty field is read only\&. \fCtrue\fP if this DependencyProperty is read only; otherwise, \fCfalse\fP\&. 
.PP
Definition at line 52 of file PropertyStatus\&.cs\&.
.SS "bool Csla\&.Xaml\&.PropertyStatus\&.IsValid\fC [get]\fP"

.PP
Gets a value indicating whether the property is valid\&. 
.PP
Definition at line 422 of file PropertyStatus\&.cs\&.
.SS "object Csla\&.Xaml\&.PropertyStatus\&.Property\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the source business property to which this control is bound\&. 
.PP
Definition at line 144 of file PropertyStatus\&.cs\&.
.SS "string Csla\&.Xaml\&.PropertyStatus\&.PropertyName\fC [get]\fP, \fC [set]\fP, \fC [protected]\fP"

.PP
Gets or sets the name of the property\&. The name of the property\&. 
.PP
Definition at line 192 of file PropertyStatus\&.cs\&.
.SS "string Csla\&.Xaml\&.PropertyStatus\&.RuleDescription\fC [get]\fP"

.PP
Gets the description of the most severe broken rule for this property\&. 
.PP
Definition at line 462 of file PropertyStatus\&.cs\&.
.SS "\fBRuleSeverity\fP Csla\&.Xaml\&.PropertyStatus\&.RuleSeverity\fC [get]\fP"

.PP
Gets a valud indicating the worst severity of all broken rules for this property (if IsValid is false)\&. 
.PP
Definition at line 443 of file PropertyStatus\&.cs\&.
.SS "object Csla\&.Xaml\&.PropertyStatus\&.Source\fC [get]\fP, \fC [set]\fP, \fC [protected]\fP"

.PP
Gets or sets the Source\&. The source\&.
.PP
Definition at line 155 of file PropertyStatus\&.cs\&.
.SH "Event Documentation"
.PP 
.SS "PropertyChangedEventHandler Csla\&.Xaml\&.PropertyStatus\&.PropertyChanged"

.PP
Event raised when a property has changed\&. 
.PP
Definition at line 704 of file PropertyStatus\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
