.TH "Csla.Configuration" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Configuration
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBConfigurationErrorsException\fP"
.br
.RI "Exception thrown due to configuration errors\&. "
.ti -1c
.RI "class \fBConfigurationManager\fP"
.br
.RI "ConfigurationManager that abstracts underlying configuration management implementations and infrastructure\&. "
.ti -1c
.RI "class \fBConnectionStringSettings\fP"
.br
.RI "Information about a connection string "
.ti -1c
.RI "class \fBConnectionStringSettingsCollection\fP"
.br
.RI "Collection of connection strings\&. "
.ti -1c
.RI "class \fBCslaConfigurationOptions\fP"
.br
.RI "Contains configuration options which can be loaded using dot net core configuration subsystem "
.ti -1c
.RI "class \fBCslaDataPortalConfigurationOptions\fP"
.br
.RI "Use this type to configure the settings for the CSLA \&.NET data portal using dot net core "
.ti -1c
.RI "class \fBCslaBuilder\fP"
.br
.RI "Default CSLA \&.NET service builder "
.ti -1c
.RI "class \fBCslaConfigurationExtension\fP"
.br
.RI "Extension method for \fBCslaDataPortalConfiguration\fP "
.ti -1c
.RI "class \fBCslaConfiguration\fP"
.br
.RI "Use this type to configure the settings for CSLA \&.NET\&. "
.ti -1c
.RI "class \fBCslaDataConfigurationExtension\fP"
.br
.RI "Extension method for \fBCslaDataConfiguration\fP "
.ti -1c
.RI "class \fBCslaDataConfiguration\fP"
.br
.RI "Use this type to configure the settings for the CSLA \&.NET data portal\&. "
.ti -1c
.RI "class \fBCslaDataPortalConfigurationExtension\fP"
.br
.RI "Extension method for \fBCslaDataPortalConfiguration\fP "
.ti -1c
.RI "class \fBCslaDataPortalConfiguration\fP"
.br
.RI "Use this type to configure the settings for the CSLA \&.NET data portal\&. "
.ti -1c
.RI "class \fBCslaSecurityConfigurationExtension\fP"
.br
.RI "Extension method for \fBCslaSecurityConfiguration\fP "
.ti -1c
.RI "class \fBCslaSecurityConfiguration\fP"
.br
.RI "Use this type to configure the settings for security\&. "
.ti -1c
.RI "class \fBCslaSerializationConfigurationExtension\fP"
.br
.RI "Extension method for \fBCslaSerializationConfiguration\fP "
.ti -1c
.RI "class \fBCslaSerializationConfiguration\fP"
.br
.RI "Use this type to configure the settings for serialization\&. "
.ti -1c
.RI "interface \fBICslaConfiguration\fP"
.br
.RI "Use this type to configure the settings for CSLA \&.NET\&. "
.ti -1c
.RI "interface \fBICslaBuilder\fP"
.br
.RI "Define CSLA \&.NET service builder "
.ti -1c
.RI "class \fBBlazorConfigurationExtensions\fP"
.br
.RI "Implement extension methods for \&.NET \fBCore\fP configuration "
.ti -1c
.RI "class \fBBlazorWasmConfigurationExtensions\fP"
.br
.RI "Implement extension methods for \&.NET \fBCore\fP configuration "
.ti -1c
.RI "class \fBWindowsConfigurationExtensions\fP"
.br
.RI "Implement extension methods for \&.NET \fBCore\fP configuration "
.ti -1c
.RI "class \fBXamlConfigurationExtensions\fP"
.br
.RI "Implement extension methods for \&.NET \fBCore\fP configuration "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
