.TH "Csla.Configuration.CslaSecurityConfiguration" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Configuration.CslaSecurityConfiguration \- Use this type to configure the settings for security\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCslaSecurityConfiguration\fP \fBPrincipalCacheMaxCacheSize\fP (int size)"
.br
.RI "Sets the max size of the PrincipalCache cache\&. "
.in -1c
.SH "Detailed Description"
.PP 
Use this type to configure the settings for security\&. 


.PP
Definition at line 27 of file CslaSecurityConfiguration\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBCslaSecurityConfiguration\fP Csla\&.Configuration\&.CslaSecurityConfiguration\&.PrincipalCacheMaxCacheSize (int size)"

.PP
Sets the max size of the PrincipalCache cache\&. 
.PP
\fBParameters\fP
.RS 4
\fIsize\fP Max cache size
.RE
.PP

.PP
Definition at line 33 of file CslaSecurityConfiguration\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
