.TH "Csla.Analyzers.Tests.Extensions.ITypeSymbolExtensionsTests" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Analyzers.Tests.Extensions.ITypeSymbolExtensionsTests
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "async Task \fBIsSpecialTypeSerializableForNonPrimitiveType\fP ()"
.br
.ti -1c
.RI "async Task \fBIsSpecialTypeSerializableForBool\fP ()"
.br
.ti -1c
.RI "async Task \fBIsSpecialTypeSerializableForChar\fP ()"
.br
.ti -1c
.RI "async Task \fBIsSpecialTypeSerializableForString\fP ()"
.br
.ti -1c
.RI "async Task \fBIsSpecialTypeSerializableForByte\fP ()"
.br
.ti -1c
.RI "async Task \fBIsSpecialTypeSerializableForSByte\fP ()"
.br
.ti -1c
.RI "async Task \fBIsSpecialTypeSerializableForInt16\fP ()"
.br
.ti -1c
.RI "async Task \fBIsSpecialTypeSerializableForUInt16\fP ()"
.br
.ti -1c
.RI "async Task \fBIsSpecialTypeSerializableForInt32\fP ()"
.br
.ti -1c
.RI "async Task \fBIsSpecialTypeSerializableForUInt32\fP ()"
.br
.ti -1c
.RI "async Task \fBIsSpecialTypeSerializableForInt64\fP ()"
.br
.ti -1c
.RI "async Task \fBIsSpecialTypeSerializableForUInt64\fP ()"
.br
.ti -1c
.RI "async Task \fBIsSpecialTypeSerializableForSingle\fP ()"
.br
.ti -1c
.RI "async Task \fBIsSpecialTypeSerializableForDouble\fP ()"
.br
.ti -1c
.RI "async Task \fBIsSpecialTypeSerializableForDecimal\fP ()"
.br
.ti -1c
.RI "async Task \fBIsSpecialTypeSerializableForDateTime\fP ()"
.br
.ti -1c
.RI "void \fBIsBusinessBaseWhenSymbolIsNull\fP ()"
.br
.ti -1c
.RI "async Task \fBIsBusinessRuleForTypeThatIsNotABusinessRule\fP ()"
.br
.ti -1c
.RI "async Task \fBIsSerializableByMobileFormatterForSupportedType\fP ()"
.br
.ti -1c
.RI "async Task \fBIsSerializableByMobileFormatterForNonSupportedType\fP ()"
.br
.ti -1c
.RI "async Task \fBIsBusinessRuleForTypeThatIsABusinessRule\fP ()"
.br
.ti -1c
.RI "async Task \fBIsBusinessRuleForTypeThatIsABusinessRuleAsync\fP ()"
.br
.ti -1c
.RI "async Task \fBIsObjectFactoryForNotObjectFactoryType\fP ()"
.br
.ti -1c
.RI "async Task \fBIsObjectFactoryForObjectFactoryType\fP ()"
.br
.ti -1c
.RI "async Task \fBIsIPropertyInfoWhenSymbolDoesNotDeriveFromIPropertyInfo\fP ()"
.br
.ti -1c
.RI "async Task \fBIsIPropertyInfoWhenSymbolDerivesFromIPropertyInfo\fP ()"
.br
.ti -1c
.RI "async Task \fBIsBusinessBaseWhenSymbolIsNotABusinessBase\fP ()"
.br
.ti -1c
.RI "async Task \fBIsBusinessBaseWhenSymbolIsABusinessBase\fP ()"
.br
.ti -1c
.RI "async Task \fBIsEditableStereotypeWhenSymbolIsABusinessBase\fP ()"
.br
.ti -1c
.RI "async Task \fBIsEditableStereotypeWhenSymbolIsABusinessListBase\fP ()"
.br
.ti -1c
.RI "async Task \fBIsEditableStereotypeWhenSymbolIsADynamicListBase\fP ()"
.br
.ti -1c
.RI "async Task \fBIsEditableStereotypeWhenSymbolIsABusinessBindingListBase\fP ()"
.br
.ti -1c
.RI "async Task \fBIsEditableStereotypeWhenSymbolIsACommandBase\fP ()"
.br
.ti -1c
.RI "void \fBIsStereotypeWhenSymbolIsNull\fP ()"
.br
.ti -1c
.RI "async Task \fBIsStereotypeWhenSymbolIsNotAStereotype\fP ()"
.br
.ti -1c
.RI "async Task \fBIsStereotypeWhenSymbolIsStereotypeViaIBusinessObject\fP ()"
.br
.ti -1c
.RI "async Task \fBIsStereotypeWhenSymbolIsStereotypeViaBusinessBase\fP ()"
.br
.ti -1c
.RI "async Task \fBIsStereotypeWhenSymbolIsDynamicListBase\fP ()"
.br
.ti -1c
.RI "async Task \fBIsStereotypeWhenSymbolIsStereotypeViaCommandBase\fP ()"
.br
.ti -1c
.RI "async Task \fBIsRunLocalAttribute\fP ()"
.br
.ti -1c
.RI "async Task \fBIsArgumentInjectableWithAttribute\fP ()"
.br
.ti -1c
.RI "async Task \fBIsArgumentInjectableWithoutAttribute\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 13 of file ITypeSymbolExtensionsTests\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "async Task Csla\&.Analyzers\&.Tests\&.Extensions\&.ITypeSymbolExtensionsTests\&.IsArgumentInjectableWithAttribute ()"

.PP
Definition at line 398 of file ITypeSymbolExtensionsTests\&.cs\&.
.SS "async Task Csla\&.Analyzers\&.Tests\&.Extensions\&.ITypeSymbolExtensionsTests\&.IsArgumentInjectableWithoutAttribute ()"

.PP
Definition at line 411 of file ITypeSymbolExtensionsTests\&.cs\&.
.SS "async Task Csla\&.Analyzers\&.Tests\&.Extensions\&.ITypeSymbolExtensionsTests\&.IsBusinessBaseWhenSymbolIsABusinessBase ()"

.PP
Definition at line 258 of file ITypeSymbolExtensionsTests\&.cs\&.
.SS "async Task Csla\&.Analyzers\&.Tests\&.Extensions\&.ITypeSymbolExtensionsTests\&.IsBusinessBaseWhenSymbolIsNotABusinessBase ()"

.PP
Definition at line 248 of file ITypeSymbolExtensionsTests\&.cs\&.
.SS "void Csla\&.Analyzers\&.Tests\&.Extensions\&.ITypeSymbolExtensionsTests\&.IsBusinessBaseWhenSymbolIsNull ()"

.SS "async Task Csla\&.Analyzers\&.Tests\&.Extensions\&.ITypeSymbolExtensionsTests\&.IsBusinessRuleForTypeThatIsABusinessRule ()"

.PP
Definition at line 156 of file ITypeSymbolExtensionsTests\&.cs\&.
.SS "async Task Csla\&.Analyzers\&.Tests\&.Extensions\&.ITypeSymbolExtensionsTests\&.IsBusinessRuleForTypeThatIsABusinessRuleAsync ()"

.PP
Definition at line 166 of file ITypeSymbolExtensionsTests\&.cs\&.
.SS "async Task Csla\&.Analyzers\&.Tests\&.Extensions\&.ITypeSymbolExtensionsTests\&.IsBusinessRuleForTypeThatIsNotABusinessRule ()"

.PP
Definition at line 131 of file ITypeSymbolExtensionsTests\&.cs\&.
.SS "async Task Csla\&.Analyzers\&.Tests\&.Extensions\&.ITypeSymbolExtensionsTests\&.IsEditableStereotypeWhenSymbolIsABusinessBase ()"

.PP
Definition at line 268 of file ITypeSymbolExtensionsTests\&.cs\&.
.SS "async Task Csla\&.Analyzers\&.Tests\&.Extensions\&.ITypeSymbolExtensionsTests\&.IsEditableStereotypeWhenSymbolIsABusinessBindingListBase ()"

.PP
Definition at line 302 of file ITypeSymbolExtensionsTests\&.cs\&.
.SS "async Task Csla\&.Analyzers\&.Tests\&.Extensions\&.ITypeSymbolExtensionsTests\&.IsEditableStereotypeWhenSymbolIsABusinessListBase ()"

.PP
Definition at line 278 of file ITypeSymbolExtensionsTests\&.cs\&.
.SS "async Task Csla\&.Analyzers\&.Tests\&.Extensions\&.ITypeSymbolExtensionsTests\&.IsEditableStereotypeWhenSymbolIsACommandBase ()"

.PP
Definition at line 314 of file ITypeSymbolExtensionsTests\&.cs\&.
.SS "async Task Csla\&.Analyzers\&.Tests\&.Extensions\&.ITypeSymbolExtensionsTests\&.IsEditableStereotypeWhenSymbolIsADynamicListBase ()"

.PP
Definition at line 290 of file ITypeSymbolExtensionsTests\&.cs\&.
.SS "async Task Csla\&.Analyzers\&.Tests\&.Extensions\&.ITypeSymbolExtensionsTests\&.IsIPropertyInfoWhenSymbolDerivesFromIPropertyInfo ()"

.PP
Definition at line 200 of file ITypeSymbolExtensionsTests\&.cs\&.
.SS "async Task Csla\&.Analyzers\&.Tests\&.Extensions\&.ITypeSymbolExtensionsTests\&.IsIPropertyInfoWhenSymbolDoesNotDeriveFromIPropertyInfo ()"

.PP
Definition at line 193 of file ITypeSymbolExtensionsTests\&.cs\&.
.SS "async Task Csla\&.Analyzers\&.Tests\&.Extensions\&.ITypeSymbolExtensionsTests\&.IsObjectFactoryForNotObjectFactoryType ()"

.PP
Definition at line 176 of file ITypeSymbolExtensionsTests\&.cs\&.
.SS "async Task Csla\&.Analyzers\&.Tests\&.Extensions\&.ITypeSymbolExtensionsTests\&.IsObjectFactoryForObjectFactoryType ()"

.PP
Definition at line 183 of file ITypeSymbolExtensionsTests\&.cs\&.
.SS "async Task Csla\&.Analyzers\&.Tests\&.Extensions\&.ITypeSymbolExtensionsTests\&.IsRunLocalAttribute ()"

.PP
Definition at line 384 of file ITypeSymbolExtensionsTests\&.cs\&.
.SS "async Task Csla\&.Analyzers\&.Tests\&.Extensions\&.ITypeSymbolExtensionsTests\&.IsSerializableByMobileFormatterForNonSupportedType ()"

.PP
Definition at line 147 of file ITypeSymbolExtensionsTests\&.cs\&.
.SS "async Task Csla\&.Analyzers\&.Tests\&.Extensions\&.ITypeSymbolExtensionsTests\&.IsSerializableByMobileFormatterForSupportedType ()"

.PP
Definition at line 138 of file ITypeSymbolExtensionsTests\&.cs\&.
.SS "async Task Csla\&.Analyzers\&.Tests\&.Extensions\&.ITypeSymbolExtensionsTests\&.IsSpecialTypeSerializableForBool ()"

.PP
Definition at line 23 of file ITypeSymbolExtensionsTests\&.cs\&.
.SS "async Task Csla\&.Analyzers\&.Tests\&.Extensions\&.ITypeSymbolExtensionsTests\&.IsSpecialTypeSerializableForByte ()"

.PP
Definition at line 44 of file ITypeSymbolExtensionsTests\&.cs\&.
.SS "async Task Csla\&.Analyzers\&.Tests\&.Extensions\&.ITypeSymbolExtensionsTests\&.IsSpecialTypeSerializableForChar ()"

.PP
Definition at line 30 of file ITypeSymbolExtensionsTests\&.cs\&.
.SS "async Task Csla\&.Analyzers\&.Tests\&.Extensions\&.ITypeSymbolExtensionsTests\&.IsSpecialTypeSerializableForDateTime ()"

.PP
Definition at line 121 of file ITypeSymbolExtensionsTests\&.cs\&.
.SS "async Task Csla\&.Analyzers\&.Tests\&.Extensions\&.ITypeSymbolExtensionsTests\&.IsSpecialTypeSerializableForDecimal ()"

.PP
Definition at line 114 of file ITypeSymbolExtensionsTests\&.cs\&.
.SS "async Task Csla\&.Analyzers\&.Tests\&.Extensions\&.ITypeSymbolExtensionsTests\&.IsSpecialTypeSerializableForDouble ()"

.PP
Definition at line 107 of file ITypeSymbolExtensionsTests\&.cs\&.
.SS "async Task Csla\&.Analyzers\&.Tests\&.Extensions\&.ITypeSymbolExtensionsTests\&.IsSpecialTypeSerializableForInt16 ()"

.PP
Definition at line 58 of file ITypeSymbolExtensionsTests\&.cs\&.
.SS "async Task Csla\&.Analyzers\&.Tests\&.Extensions\&.ITypeSymbolExtensionsTests\&.IsSpecialTypeSerializableForInt32 ()"

.PP
Definition at line 72 of file ITypeSymbolExtensionsTests\&.cs\&.
.SS "async Task Csla\&.Analyzers\&.Tests\&.Extensions\&.ITypeSymbolExtensionsTests\&.IsSpecialTypeSerializableForInt64 ()"

.PP
Definition at line 86 of file ITypeSymbolExtensionsTests\&.cs\&.
.SS "async Task Csla\&.Analyzers\&.Tests\&.Extensions\&.ITypeSymbolExtensionsTests\&.IsSpecialTypeSerializableForNonPrimitiveType ()"

.PP
Definition at line 16 of file ITypeSymbolExtensionsTests\&.cs\&.
.SS "async Task Csla\&.Analyzers\&.Tests\&.Extensions\&.ITypeSymbolExtensionsTests\&.IsSpecialTypeSerializableForSByte ()"

.PP
Definition at line 51 of file ITypeSymbolExtensionsTests\&.cs\&.
.SS "async Task Csla\&.Analyzers\&.Tests\&.Extensions\&.ITypeSymbolExtensionsTests\&.IsSpecialTypeSerializableForSingle ()"

.PP
Definition at line 100 of file ITypeSymbolExtensionsTests\&.cs\&.
.SS "async Task Csla\&.Analyzers\&.Tests\&.Extensions\&.ITypeSymbolExtensionsTests\&.IsSpecialTypeSerializableForString ()"

.PP
Definition at line 37 of file ITypeSymbolExtensionsTests\&.cs\&.
.SS "async Task Csla\&.Analyzers\&.Tests\&.Extensions\&.ITypeSymbolExtensionsTests\&.IsSpecialTypeSerializableForUInt16 ()"

.PP
Definition at line 65 of file ITypeSymbolExtensionsTests\&.cs\&.
.SS "async Task Csla\&.Analyzers\&.Tests\&.Extensions\&.ITypeSymbolExtensionsTests\&.IsSpecialTypeSerializableForUInt32 ()"

.PP
Definition at line 79 of file ITypeSymbolExtensionsTests\&.cs\&.
.SS "async Task Csla\&.Analyzers\&.Tests\&.Extensions\&.ITypeSymbolExtensionsTests\&.IsSpecialTypeSerializableForUInt64 ()"

.PP
Definition at line 93 of file ITypeSymbolExtensionsTests\&.cs\&.
.SS "async Task Csla\&.Analyzers\&.Tests\&.Extensions\&.ITypeSymbolExtensionsTests\&.IsStereotypeWhenSymbolIsDynamicListBase ()"

.PP
Definition at line 362 of file ITypeSymbolExtensionsTests\&.cs\&.
.SS "async Task Csla\&.Analyzers\&.Tests\&.Extensions\&.ITypeSymbolExtensionsTests\&.IsStereotypeWhenSymbolIsNotAStereotype ()"

.PP
Definition at line 330 of file ITypeSymbolExtensionsTests\&.cs\&.
.SS "void Csla\&.Analyzers\&.Tests\&.Extensions\&.ITypeSymbolExtensionsTests\&.IsStereotypeWhenSymbolIsNull ()"

.PP
Definition at line 324 of file ITypeSymbolExtensionsTests\&.cs\&.
.SS "async Task Csla\&.Analyzers\&.Tests\&.Extensions\&.ITypeSymbolExtensionsTests\&.IsStereotypeWhenSymbolIsStereotypeViaBusinessBase ()"

.PP
Definition at line 352 of file ITypeSymbolExtensionsTests\&.cs\&.
.SS "async Task Csla\&.Analyzers\&.Tests\&.Extensions\&.ITypeSymbolExtensionsTests\&.IsStereotypeWhenSymbolIsStereotypeViaCommandBase ()"

.PP
Definition at line 374 of file ITypeSymbolExtensionsTests\&.cs\&.
.SS "async Task Csla\&.Analyzers\&.Tests\&.Extensions\&.ITypeSymbolExtensionsTests\&.IsStereotypeWhenSymbolIsStereotypeViaIBusinessObject ()"

.PP
Definition at line 338 of file ITypeSymbolExtensionsTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
