.TH "Csla.Serialization.NetDataContractSerializerWrapper" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Serialization.NetDataContractSerializerWrapper
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.Serialization\&.ISerializationFormatter\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "object \fBDeserialize\fP (System\&.IO\&.Stream serializationStream)"
.br
.RI "Converts a serialization stream into an object graph\&. "
.ti -1c
.RI "object \fBDeserialize\fP (byte[] buffer)"
.br
.RI "Converts a serialization stream into an object graph\&. "
.ti -1c
.RI "void \fBSerialize\fP (System\&.IO\&.Stream serializationStream, object graph)"
.br
.RI "Converts an object graph into a byte stream\&. "
.ti -1c
.RI "byte[] \fBSerialize\fP (object graph)"
.br
.RI "Converts an object graph into a byte stream\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "NetDataContractSerializer \fBFormatter\fP\fC [get]\fP"
.br
.RI "Gets a reference to the underlying NetDataContractSerializer object\&. "
.in -1c
.SH "Detailed Description"
.PP 
Wraps the NetDataContractSerializer in the \fBISerializationFormatter\fP interface so it can be used in a standardized manner\&. 
.PP
Definition at line 19 of file NetDataContractSerializerWrapper\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "object Csla\&.Serialization\&.NetDataContractSerializerWrapper\&.Deserialize (byte[] buffer)"

.PP
Converts a serialization stream into an object graph\&. 
.PP
\fBParameters\fP
.RS 4
\fIbuffer\fP Byte stream containing the serialized data\&.
.RE
.PP
\fBReturns\fP
.RS 4
A deserialized object graph\&.
.RE
.PP

.PP
Implements \fBCsla\&.Serialization\&.ISerializationFormatter\fP\&.
.PP
Definition at line 43 of file NetDataContractSerializerWrapper\&.cs\&.
.SS "object Csla\&.Serialization\&.NetDataContractSerializerWrapper\&.Deserialize (System\&.IO\&.Stream serializationStream)"

.PP
Converts a serialization stream into an object graph\&. 
.PP
\fBParameters\fP
.RS 4
\fIserializationStream\fP Byte stream containing the serialized data\&.
.RE
.PP
\fBReturns\fP
.RS 4
A deserialized object graph\&.
.RE
.PP

.PP
Implements \fBCsla\&.Serialization\&.ISerializationFormatter\fP\&.
.PP
Definition at line 31 of file NetDataContractSerializerWrapper\&.cs\&.
.SS "byte [] Csla\&.Serialization\&.NetDataContractSerializerWrapper\&.Serialize (object graph)"

.PP
Converts an object graph into a byte stream\&. 
.PP
\fBParameters\fP
.RS 4
\fIgraph\fP Object graph to be serialized\&.
.RE
.PP

.PP
Implements \fBCsla\&.Serialization\&.ISerializationFormatter\fP\&.
.PP
Definition at line 64 of file NetDataContractSerializerWrapper\&.cs\&.
.SS "void Csla\&.Serialization\&.NetDataContractSerializerWrapper\&.Serialize (System\&.IO\&.Stream serializationStream, object graph)"

.PP
Converts an object graph into a byte stream\&. 
.PP
\fBParameters\fP
.RS 4
\fIserializationStream\fP Stream that will contain the the serialized data\&.
.br
\fIgraph\fP Object graph to be serialized\&.
.RE
.PP

.PP
Implements \fBCsla\&.Serialization\&.ISerializationFormatter\fP\&.
.PP
Definition at line 55 of file NetDataContractSerializerWrapper\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "NetDataContractSerializer Csla\&.Serialization\&.NetDataContractSerializerWrapper\&.Formatter\fC [get]\fP"

.PP
Gets a reference to the underlying NetDataContractSerializer object\&. 
.PP
Definition at line 77 of file NetDataContractSerializerWrapper\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
