.TH "Csla.Web.Mvc.IModelCreator" 3 "Thu Jul 22 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Web.Mvc.IModelCreator \- ASP\&.NET MVC model creator\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "object \fBCreateModel\fP (Type modelType)"
.br
.RI "Creates a model object of the specified type\&. "
.in -1c
.SH "Detailed Description"
.PP 
ASP\&.NET MVC model creator\&. 


.PP
Definition at line 18 of file IModelCreator\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "object Csla\&.Web\&.Mvc\&.IModelCreator\&.CreateModel (Type modelType)"

.PP
Creates a model object of the specified type\&. 
.PP
\fBParameters\fP
.RS 4
\fImodelType\fP Type of model object to create\&.
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
