.TH "csla.netcore.test.Configuration.TestObjectFactoryLoader" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csla.netcore.test.Configuration.TestObjectFactoryLoader
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.Server\&.IObjectFactoryLoader\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "object \fBGetFactory\fP (string factoryName)"
.br
.RI "Returns an ObjectFactory object\&. "
.ti -1c
.RI "Type \fBGetFactoryType\fP (string factoryName)"
.br
.RI "Returns the type of the factory object\&. "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 133 of file ReadConfigFromDotnetCoreSubsystemTests\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "object csla\&.netcore\&.test\&.Configuration\&.TestObjectFactoryLoader\&.GetFactory (string factoryName)"

.PP
Returns an ObjectFactory object\&. 
.PP
\fBParameters\fP
.RS 4
\fIfactoryName\fP Name of the factory to create, typically an assembly qualified type name\&. 
.RE
.PP

.PP
Implements \fBCsla\&.Server\&.IObjectFactoryLoader\fP\&.
.PP
Definition at line 135 of file ReadConfigFromDotnetCoreSubsystemTests\&.cs\&.
.SS "Type csla\&.netcore\&.test\&.Configuration\&.TestObjectFactoryLoader\&.GetFactoryType (string factoryName)"

.PP
Returns the type of the factory object\&. 
.PP
\fBParameters\fP
.RS 4
\fIfactoryName\fP Name of the factory to create, typically an assembly qualified type name\&. 
.RE
.PP

.PP
Implements \fBCsla\&.Server\&.IObjectFactoryLoader\fP\&.
.PP
Definition at line 140 of file ReadConfigFromDotnetCoreSubsystemTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
