.TH "Csla.Test.DataPortal.MyCriteria" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.DataPortal.MyCriteria
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.ReadOnlyBase< MyCriteria >\fP, and \fBCsla\&.Test\&.DataPortal\&.ICriteria\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBId\fP\fC [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 382 of file ServiceProviderMethodCallerTests\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "int Csla\&.Test\&.DataPortal\&.MyCriteria\&.Id\fC [get]\fP"

.PP
Definition at line 384 of file ServiceProviderMethodCallerTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
