.TH "Csla.Test.Data.TransactionContextUser" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.Data.TransactionContextUser
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.BusinessBase< TransactionContextUser >\fP\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBTransactionContextUser\fP \fBNewTransactionContextUser\fP ()"
.br
.ti -1c
.RI "static \fBTransactionContextUser\fP \fBGetTransactionContextUser\fP (\fBCsla\&.Data\&.SafeDataReader\fP reader)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBDataPortal_Create\fP ()"
.br
.ti -1c
.RI "void \fBChild_Fetch\fP (\fBCsla\&.Data\&.SafeDataReader\fP reader)"
.br
.ti -1c
.RI "void \fBChild_DeleteSelf\fP ()"
.br
.ti -1c
.RI "void \fBChild_Insert\fP (\fBTransactionContextUserList\fP parent)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBFirstName\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBLastName\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBSmallColumn\fP\fC [get, set]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 19 of file TransactionContextUser\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Csla\&.Test\&.Data\&.TransactionContextUser\&.Child_DeleteSelf ()\fC [protected]\fP"

.PP
Definition at line 67 of file TransactionContextUser\&.cs\&.
.SS "void Csla\&.Test\&.Data\&.TransactionContextUser\&.Child_Fetch (\fBCsla\&.Data\&.SafeDataReader\fP reader)\fC [protected]\fP"

.PP
Definition at line 60 of file TransactionContextUser\&.cs\&.
.SS "void Csla\&.Test\&.Data\&.TransactionContextUser\&.Child_Insert (\fBTransactionContextUserList\fP parent)\fC [protected]\fP"

.PP
Definition at line 78 of file TransactionContextUser\&.cs\&.
.SS "void Csla\&.Test\&.Data\&.TransactionContextUser\&.DataPortal_Create ()\fC [protected]\fP"

.PP
Definition at line 55 of file TransactionContextUser\&.cs\&.
.SS "static \fBTransactionContextUser\fP Csla\&.Test\&.Data\&.TransactionContextUser\&.GetTransactionContextUser (\fBCsla\&.Data\&.SafeDataReader\fP reader)\fC [static]\fP"

.PP
Definition at line 47 of file TransactionContextUser\&.cs\&.
.SS "static \fBTransactionContextUser\fP Csla\&.Test\&.Data\&.TransactionContextUser\&.NewTransactionContextUser ()\fC [static]\fP"

.PP
Definition at line 42 of file TransactionContextUser\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "string Csla\&.Test\&.Data\&.TransactionContextUser\&.FirstName\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 23 of file TransactionContextUser\&.cs\&.
.SS "string Csla\&.Test\&.Data\&.TransactionContextUser\&.LastName\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 29 of file TransactionContextUser\&.cs\&.
.SS "string Csla\&.Test\&.Data\&.TransactionContextUser\&.SmallColumn\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 36 of file TransactionContextUser\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
