.TH "Csla.Test.AppContext.ExceptionRoot" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.AppContext.ExceptionRoot
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.BusinessBase< ExceptionRoot >\fP\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBExceptionRoot\fP \fBNewExceptionRoot\fP ()"
.br
.ti -1c
.RI "static \fBExceptionRoot\fP \fBGetExceptionRoot\fP (string \fBData\fP)"
.br
.ti -1c
.RI "static void \fBDeleteExceptionRoot\fP (string \fBData\fP)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override object \fBGetIdValue\fP ()"
.br
.RI "Override this method to return a unique identifying value for this object\&. "
.ti -1c
.RI "void \fBDataPortal_Fetch\fP (object criteria)"
.br
.ti -1c
.RI "void \fBDataPortal_Insert\fP ()"
.br
.ti -1c
.RI "void \fBDataPortal_Update\fP ()"
.br
.ti -1c
.RI "void \fBDataPortal_Delete\fP (object criteria)"
.br
.ti -1c
.RI "void \fBDataPortal_DeleteSelf\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBData\fP\fC [get, set]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 14 of file ExceptionRoot\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Csla\&.Test\&.AppContext\&.ExceptionRoot\&.DataPortal_Delete (object criteria)\fC [protected]\fP"

.PP
Definition at line 110 of file ExceptionRoot\&.cs\&.
.SS "void Csla\&.Test\&.AppContext\&.ExceptionRoot\&.DataPortal_DeleteSelf ()\fC [protected]\fP"

.PP
Definition at line 118 of file ExceptionRoot\&.cs\&.
.SS "void Csla\&.Test\&.AppContext\&.ExceptionRoot\&.DataPortal_Fetch (object criteria)\fC [protected]\fP"

.PP
Definition at line 71 of file ExceptionRoot\&.cs\&.
.SS "void Csla\&.Test\&.AppContext\&.ExceptionRoot\&.DataPortal_Insert ()\fC [protected]\fP"

.PP
Definition at line 93 of file ExceptionRoot\&.cs\&.
.SS "void Csla\&.Test\&.AppContext\&.ExceptionRoot\&.DataPortal_Update ()\fC [protected]\fP"

.PP
Definition at line 102 of file ExceptionRoot\&.cs\&.
.SS "static void Csla\&.Test\&.AppContext\&.ExceptionRoot\&.DeleteExceptionRoot (string Data)\fC [static]\fP"

.PP
Definition at line 66 of file ExceptionRoot\&.cs\&.
.SS "static \fBExceptionRoot\fP Csla\&.Test\&.AppContext\&.ExceptionRoot\&.GetExceptionRoot (string Data)\fC [static]\fP"

.PP
Definition at line 61 of file ExceptionRoot\&.cs\&.
.SS "override object Csla\&.Test\&.AppContext\&.ExceptionRoot\&.GetIdValue ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Override this method to return a unique identifying value for this object\&. 
.PP
Reimplemented from \fBCsla\&.BusinessBase< ExceptionRoot >\fP\&.
.PP
Definition at line 25 of file ExceptionRoot\&.cs\&.
.SS "static \fBExceptionRoot\fP Csla\&.Test\&.AppContext\&.ExceptionRoot\&.NewExceptionRoot ()\fC [static]\fP"

.PP
Definition at line 54 of file ExceptionRoot\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "string Csla\&.Test\&.AppContext\&.ExceptionRoot\&.Data\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 17 of file ExceptionRoot\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
