.TH "Csla.Analyzers.Tests.AsynchronousBusinessRuleInheritingFromBusinessRuleAnalyzerTests" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Analyzers.Tests.AsynchronousBusinessRuleInheritingFromBusinessRuleAnalyzerTests
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBVerifySupportedDiagnostics\fP ()"
.br
.ti -1c
.RI "async Task \fBAnalyzeWhenClassIsNotABusinessRule\fP ()"
.br
.ti -1c
.RI "async Task \fBAnalyzeWhenClassIsABusinessRuleButDoesNotOverrideExecute\fP ()"
.br
.ti -1c
.RI "async Task \fBAnalyzeWhenClassIsABusinessRuleAndOverridesExecuteAndIsNotAsync\fP ()"
.br
.ti -1c
.RI "async Task \fBAnalyzeWhenClassIsABusinessRuleAndOverridesExecuteAndIsAsync\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 9 of file AsynchronousBusinessRuleInheritingFromBusinessRuleAnalyzerTests\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "async Task Csla\&.Analyzers\&.Tests\&.AsynchronousBusinessRuleInheritingFromBusinessRuleAnalyzerTests\&.AnalyzeWhenClassIsABusinessRuleAndOverridesExecuteAndIsAsync ()"

.PP
Definition at line 71 of file AsynchronousBusinessRuleInheritingFromBusinessRuleAnalyzerTests\&.cs\&.
.SS "async Task Csla\&.Analyzers\&.Tests\&.AsynchronousBusinessRuleInheritingFromBusinessRuleAnalyzerTests\&.AnalyzeWhenClassIsABusinessRuleAndOverridesExecuteAndIsNotAsync ()"

.PP
Definition at line 54 of file AsynchronousBusinessRuleInheritingFromBusinessRuleAnalyzerTests\&.cs\&.
.SS "async Task Csla\&.Analyzers\&.Tests\&.AsynchronousBusinessRuleInheritingFromBusinessRuleAnalyzerTests\&.AnalyzeWhenClassIsABusinessRuleButDoesNotOverrideExecute ()"

.PP
Definition at line 43 of file AsynchronousBusinessRuleInheritingFromBusinessRuleAnalyzerTests\&.cs\&.
.SS "async Task Csla\&.Analyzers\&.Tests\&.AsynchronousBusinessRuleInheritingFromBusinessRuleAnalyzerTests\&.AnalyzeWhenClassIsNotABusinessRule ()"

.PP
Definition at line 35 of file AsynchronousBusinessRuleInheritingFromBusinessRuleAnalyzerTests\&.cs\&.
.SS "void Csla\&.Analyzers\&.Tests\&.AsynchronousBusinessRuleInheritingFromBusinessRuleAnalyzerTests\&.VerifySupportedDiagnostics ()"

.PP
Definition at line 12 of file AsynchronousBusinessRuleInheritingFromBusinessRuleAnalyzerTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
