.TH "C:/Users/korye/source/repos/csla/Source/Csla/Serialization/Mobile/CslaReaderWriterFactory.cs" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/korye/source/repos/csla/Source/Csla/Serialization/Mobile/CslaReaderWriterFactory.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCsla\&.Serialization\&.Mobile\&.CslaReaderWriterFactory\fP"
.br
.RI "Factory class that is used to create Reader/Writer pair of classes to read/write the data during serialization / deserialization process "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBCsla\fP"
.br
.ti -1c
.RI "namespace \fBCsla\&.Serialization\fP"
.br
.ti -1c
.RI "namespace \fBCsla\&.Serialization\&.Mobile\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
