.TH "Csla.Test.LogicalExecutionLocation.LogicalExecutionLocationTests" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.LogicalExecutionLocation.LogicalExecutionLocationTests
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBTestLogicalExecutionLocation\fP ()"
.br
.ti -1c
.RI "void \fBTestRulesLogicalExecutionLocation\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 25 of file LogicalExecutionLocationTests\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Csla\&.Test\&.LogicalExecutionLocation\&.LogicalExecutionLocationTests\&.TestLogicalExecutionLocation ()"

.PP
Definition at line 28 of file LogicalExecutionLocationTests\&.cs\&.
.SS "void Csla\&.Test\&.LogicalExecutionLocation\&.LogicalExecutionLocationTests\&.TestRulesLogicalExecutionLocation ()"

.PP
Definition at line 45 of file LogicalExecutionLocationTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
