.TH "Csla.Axml.Binding.Binding" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Axml.Binding.Binding \- Contains an individual binding to tie a property on an \fBAxml\fP view to the property on a supplied object\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits IDisposable\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBinding\fP (View target, string targetProperty, object source, string sourceProperty)"
.br
.RI "Creates a new instance of the \fBBinding\fP class\&. "
.ti -1c
.RI "\fBBinding\fP (View target, string targetProperty, object source, string sourceProperty, Func< object, object > convert)"
.br
.RI "Creates a new instance of the \fBBinding\fP class\&. "
.ti -1c
.RI "\fBBinding\fP (View target, string targetProperty, object source, string sourceProperty, Func< object, object > convert, Func< object, object > convertBack)"
.br
.RI "Creates a new instance of the \fBBinding\fP class\&. "
.ti -1c
.RI "void \fBUpdateSource\fP ()"
.br
.RI "Updates the source with the current value in the target object\&. Uses the ConvertBack function to convert the data if available\&. "
.ti -1c
.RI "void \fBUpdateTarget\fP ()"
.br
.RI "Updates the target with the current value in the source object\&. Uses the Convert function to convert the data if available\&. "
.ti -1c
.RI "void \fBDispose\fP ()"
.br
.RI "Clears the bindings, references and event handlers\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "View \fBTarget\fP\fC [get]\fP"
.br
.RI "The \fBAxml\fP view that is used by the binding\&. "
.ti -1c
.RI "object \fBSource\fP\fC [get]\fP"
.br
.RI "The object that the view is bound to\&. "
.ti -1c
.RI "System\&.Reflection\&.PropertyInfo \fBTargetProperty\fP\fC [get]\fP"
.br
.RI "The \fBPropertyInfo\fP for the property on the target view that is being bound to\&. "
.ti -1c
.RI "System\&.Reflection\&.PropertyInfo \fBSourceProperty\fP\fC [get]\fP"
.br
.RI "The \fBPropertyInfo\fP for the property on the source object that is being bound to\&. "
.ti -1c
.RI "Func< object, object > \fBConvert\fP\fC [get]\fP"
.br
.RI "A reference to a function to do a custom conversion from the source property to the target property\&. "
.ti -1c
.RI "Func< object, object > \fBConvertBack\fP\fC [get]\fP"
.br
.RI "A reference to a function to do a custom conversion from the target property to the source property\&. "
.in -1c
.SH "Detailed Description"
.PP 
Contains an individual binding to tie a property on an \fBAxml\fP view to the property on a supplied object\&. 


.PP
Definition at line 18 of file Csla\&.Axml\&.Android/Binding/Binding\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Csla\&.Axml\&.Binding\&.Binding\&.Binding (View target, string targetProperty, object source, string sourceProperty)"

.PP
Creates a new instance of the \fBBinding\fP class\&. 
.PP
\fBParameters\fP
.RS 4
\fItarget\fP A reference to the control to bind to\&.
.br
\fItargetProperty\fP The name of the property on the view to bind to\&.
.br
\fIsource\fP A reference to the object that will be bound to the control\&.
.br
\fIsourceProperty\fP The name of the property on the object that will be bound to the target property\&.
.RE
.PP

.PP
Definition at line 57 of file Csla\&.Axml\&.Android/Binding/Binding\&.cs\&.
.SS "Csla\&.Axml\&.Binding\&.Binding\&.Binding (View target, string targetProperty, object source, string sourceProperty, Func< object, object > convert)"

.PP
Creates a new instance of the \fBBinding\fP class\&. 
.PP
\fBParameters\fP
.RS 4
\fItarget\fP A reference to the control to bind to\&.
.br
\fItargetProperty\fP The name of the property on the view to bind to\&.
.br
\fIsource\fP A reference to the object that will be bound to the control\&.
.br
\fIsourceProperty\fP The name of the property on the object that will be bound to the target property\&.
.br
\fIconvert\fP A reference to a function to do a custom conversion from the source property to the target property\&.
.RE
.PP

.PP
Definition at line 69 of file Csla\&.Axml\&.Android/Binding/Binding\&.cs\&.
.SS "Csla\&.Axml\&.Binding\&.Binding\&.Binding (View target, string targetProperty, object source, string sourceProperty, Func< object, object > convert, Func< object, object > convertBack)"

.PP
Creates a new instance of the \fBBinding\fP class\&. 
.PP
\fBParameters\fP
.RS 4
\fItarget\fP A reference to the control to bind to\&.
.br
\fItargetProperty\fP The name of the property on the view to bind to\&.
.br
\fIsource\fP A reference to the object that will be bound to the control\&.
.br
\fIsourceProperty\fP The name of the property on the object that will be bound to the target property\&.
.br
\fIconvert\fP A reference to a function to do a custom conversion from the source property to the target property\&.
.br
\fIconvertBack\fP A reference to a function to do a custom conversion from the target property to the source property\&.
.RE
.PP

.PP
Definition at line 82 of file Csla\&.Axml\&.Android/Binding/Binding\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Csla\&.Axml\&.Binding\&.Binding\&.Dispose ()"

.PP
Clears the bindings, references and event handlers\&. 
.PP
Definition at line 154 of file Csla\&.Axml\&.Android/Binding/Binding\&.cs\&.
.SS "void Csla\&.Axml\&.Binding\&.Binding\&.UpdateSource ()"

.PP
Updates the source with the current value in the target object\&. Uses the ConvertBack function to convert the data if available\&. 
.PP
Definition at line 124 of file Csla\&.Axml\&.Android/Binding/Binding\&.cs\&.
.SS "void Csla\&.Axml\&.Binding\&.Binding\&.UpdateTarget ()"

.PP
Updates the target with the current value in the source object\&. Uses the Convert function to convert the data if available\&. 
.PP
Definition at line 139 of file Csla\&.Axml\&.Android/Binding/Binding\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "Func<object, object> Csla\&.Axml\&.Binding\&.Binding\&.Convert\fC [get]\fP"

.PP
A reference to a function to do a custom conversion from the source property to the target property\&. 
.PP
Definition at line 43 of file Csla\&.Axml\&.Android/Binding/Binding\&.cs\&.
.SS "Func<object, object> Csla\&.Axml\&.Binding\&.Binding\&.ConvertBack\fC [get]\fP"

.PP
A reference to a function to do a custom conversion from the target property to the source property\&. 
.PP
Definition at line 48 of file Csla\&.Axml\&.Android/Binding/Binding\&.cs\&.
.SS "object Csla\&.Axml\&.Binding\&.Binding\&.Source\fC [get]\fP"

.PP
The object that the view is bound to\&. 
.PP
Definition at line 28 of file Csla\&.Axml\&.Android/Binding/Binding\&.cs\&.
.SS "System\&.Reflection\&.PropertyInfo Csla\&.Axml\&.Binding\&.Binding\&.SourceProperty\fC [get]\fP"

.PP
The \fBPropertyInfo\fP for the property on the source object that is being bound to\&. 
.PP
Definition at line 38 of file Csla\&.Axml\&.Android/Binding/Binding\&.cs\&.
.SS "View Csla\&.Axml\&.Binding\&.Binding\&.Target\fC [get]\fP"

.PP
The \fBAxml\fP view that is used by the binding\&. 
.PP
Definition at line 23 of file Csla\&.Axml\&.Android/Binding/Binding\&.cs\&.
.SS "System\&.Reflection\&.PropertyInfo Csla\&.Axml\&.Binding\&.Binding\&.TargetProperty\fC [get]\fP"

.PP
The \fBPropertyInfo\fP for the property on the target view that is being bound to\&. 
.PP
Definition at line 33 of file Csla\&.Axml\&.Android/Binding/Binding\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
