.TH "Csla.Rules.PropertyRuleAsync" 3 "Thu Jul 22 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Rules.PropertyRuleAsync \- Base class for a property rule  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.Rules\&.BusinessRuleAsync\fP\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual string \fBGetMessage\fP ()"
.br
.RI "Gets the error message text\&. "
.ti -1c
.RI "\fBPropertyRuleAsync\fP ()"
.br
.RI "Initializes a new instance of the \fBPropertyRule\fP class\&. "
.ti -1c
.RI "\fBPropertyRuleAsync\fP (\fBIPropertyInfo\fP propertyInfo)"
.br
.RI "Initializes a new instance of the \fBPropertyRule\fP class\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBMessageText\fP\fC [get, set]\fP"
.br
.RI "Gets or sets the error message (constant)\&. "
.ti -1c
.RI "Func< string > \fBMessageDelegate\fP\fC [get, set]\fP"
.br
.RI "Gets or sets the error message function for this rule\&. Use this for localizable messages from a resource file\&. "
.ti -1c
.RI "bool \fBHasMessageDelegate\fP\fC [get]\fP"
.br
.RI "Gets a value indicating whether this instance has message delegate\&. "
.ti -1c
.RI "bool \fBCanRunAsAffectedProperty\fP\fC [get, set]\fP"
.br
.RI "Gets or sets a value indicating whether this instance can run as affected property\&. "
.ti -1c
.RI "bool \fBCanRunOnServer\fP\fC [get, set]\fP"
.br
.RI "Gets or sets a value indicating whether this instance can run in logical serverside data portal\&. "
.ti -1c
.RI "bool \fBCanRunInCheckRules\fP\fC [get, set]\fP"
.br
.RI "Gets or sets a value indicating whether this instance can run when CheckRules is called on BO\&. "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Base class for a property rule 


.PP
Definition at line 16 of file PropertyRuleAsync\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Csla\&.Rules\&.PropertyRuleAsync\&.PropertyRuleAsync ()\fC [protected]\fP"

.PP
Initializes a new instance of the \fBPropertyRule\fP class\&. 
.PP
Definition at line 56 of file PropertyRuleAsync\&.cs\&.
.SS "Csla\&.Rules\&.PropertyRuleAsync\&.PropertyRuleAsync (\fBIPropertyInfo\fP propertyInfo)\fC [protected]\fP"

.PP
Initializes a new instance of the \fBPropertyRule\fP class\&. 
.PP
\fBParameters\fP
.RS 4
\fIpropertyInfo\fP The property info\&.
.RE
.PP

.PP
Definition at line 68 of file PropertyRuleAsync\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual string Csla\&.Rules\&.PropertyRuleAsync\&.GetMessage ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Gets the error message text\&. 
.PP
\fBReturns\fP
.RS 4

.RE
.PP

.PP
Definition at line 48 of file PropertyRuleAsync\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "bool Csla\&.Rules\&.PropertyRuleAsync\&.CanRunAsAffectedProperty\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets a value indicating whether this instance can run as affected property\&. \fCtrue\fP if this instance can run as affected property; otherwise, \fCfalse\fP\&. 
.PP
Definition at line 81 of file PropertyRuleAsync\&.cs\&.
.SS "bool Csla\&.Rules\&.PropertyRuleAsync\&.CanRunInCheckRules\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets a value indicating whether this instance can run when CheckRules is called on BO\&. \fCtrue\fP if this instance can run when CheckRules is called; otherwise, \fCfalse\fP\&. 
.PP
Definition at line 125 of file PropertyRuleAsync\&.cs\&.
.SS "bool Csla\&.Rules\&.PropertyRuleAsync\&.CanRunOnServer\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets a value indicating whether this instance can run in logical serverside data portal\&. \fCtrue\fP if this instance can run logical serverside data portal; otherwise, \fCfalse\fP\&. 
.PP
Definition at line 103 of file PropertyRuleAsync\&.cs\&.
.SS "bool Csla\&.Rules\&.PropertyRuleAsync\&.HasMessageDelegate\fC [get]\fP, \fC [protected]\fP"

.PP
Gets a value indicating whether this instance has message delegate\&. \fCtrue\fP if this instance has message delegate; otherwise, \fCfalse\fP\&. 
.PP
Definition at line 39 of file PropertyRuleAsync\&.cs\&.
.SS "Func<string> Csla\&.Rules\&.PropertyRuleAsync\&.MessageDelegate\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the error message function for this rule\&. Use this for localizable messages from a resource file\&. 
.br
 
.PP
Definition at line 31 of file PropertyRuleAsync\&.cs\&.
.SS "string Csla\&.Rules\&.PropertyRuleAsync\&.MessageText\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the error message (constant)\&. 
.PP
Definition at line 21 of file PropertyRuleAsync\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
