.TH "Csla.Test.DataPortalTestDatabaseDataSet" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.DataPortalTestDatabaseDataSet \- Represents a strongly typed in-memory cache of data\&. /summary>  

.SH SYNOPSIS
.br
.PP
.PP
Inherits global\&.SystemData\&.DataSet\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDataPortalTestDatabaseDataSet\fP ()"
.br
.ti -1c
.RI "override global::System\&.Data\&.DataSet \fBClone\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static global::System\&.Xml\&.Schema\&.XmlSchemaComplexType \fBGetTypedDataSetSchema\fP (global::System\&.Xml\&.Schema\&.XmlSchemaSet xs)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBDataPortalTestDatabaseDataSet\fP (global::System\&.Runtime\&.Serialization\&.SerializationInfo info, global::System\&.Runtime\&.Serialization\&.StreamingContext context)"
.br
.ti -1c
.RI "override void \fBInitializeDerivedDataSet\fP ()"
.br
.ti -1c
.RI "override bool \fBShouldSerializeTables\fP ()"
.br
.ti -1c
.RI "override bool \fBShouldSerializeRelations\fP ()"
.br
.ti -1c
.RI "override void \fBReadXmlSerializable\fP (global::System\&.Xml\&.XmlReader reader)"
.br
.ti -1c
.RI "override global::System\&.Xml\&.Schema\&.XmlSchema \fBGetSchemaSerializable\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override global::System\&.Data\&.SchemaSerializationMode \fBSchemaSerializationMode\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "new global::System\&.Data\&.DataTableCollection \fBTables\fP\fC [get]\fP"
.br
.ti -1c
.RI "new global::System\&.Data\&.DataRelationCollection \fBRelations\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Represents a strongly typed in-memory cache of data\&. /summary> 
.PP
Definition at line 12 of file DataPortalTestDatabaseDataSet\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Csla\&.Test\&.DataPortalTestDatabaseDataSet\&.DataPortalTestDatabaseDataSet ()"

.PP
Definition at line 31 of file DataPortalTestDatabaseDataSet\&.Designer\&.cs\&.
.SS "Csla\&.Test\&.DataPortalTestDatabaseDataSet\&.DataPortalTestDatabaseDataSet (global::System\&.Runtime\&.Serialization\&.SerializationInfo info, global::System\&.Runtime\&.Serialization\&.StreamingContext context)\fC [protected]\fP"

.PP
Definition at line 42 of file DataPortalTestDatabaseDataSet\&.Designer\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override global\&.System\&.Data\&.DataSet Csla\&.Test\&.DataPortalTestDatabaseDataSet\&.Clone ()"

.PP
Definition at line 114 of file DataPortalTestDatabaseDataSet\&.Designer\&.cs\&.
.SS "override global\&.System\&.Xml\&.Schema\&.XmlSchema Csla\&.Test\&.DataPortalTestDatabaseDataSet\&.GetSchemaSerializable ()\fC [protected]\fP"

.PP
Definition at line 157 of file DataPortalTestDatabaseDataSet\&.Designer\&.cs\&.
.SS "static global\&.System\&.Xml\&.Schema\&.XmlSchemaComplexType Csla\&.Test\&.DataPortalTestDatabaseDataSet\&.GetTypedDataSetSchema (global::System\&.Xml\&.Schema\&.XmlSchemaSet xs)\fC [static]\fP"

.PP
Definition at line 195 of file DataPortalTestDatabaseDataSet\&.Designer\&.cs\&.
.SS "override void Csla\&.Test\&.DataPortalTestDatabaseDataSet\&.InitializeDerivedDataSet ()\fC [protected]\fP"

.PP
Definition at line 106 of file DataPortalTestDatabaseDataSet\&.Designer\&.cs\&.
.SS "override void Csla\&.Test\&.DataPortalTestDatabaseDataSet\&.ReadXmlSerializable (global::System\&.Xml\&.XmlReader reader)\fC [protected]\fP"

.PP
Definition at line 135 of file DataPortalTestDatabaseDataSet\&.Designer\&.cs\&.
.SS "override bool Csla\&.Test\&.DataPortalTestDatabaseDataSet\&.ShouldSerializeRelations ()\fC [protected]\fP"

.PP
Definition at line 129 of file DataPortalTestDatabaseDataSet\&.Designer\&.cs\&.
.SS "override bool Csla\&.Test\&.DataPortalTestDatabaseDataSet\&.ShouldSerializeTables ()\fC [protected]\fP"

.PP
Definition at line 123 of file DataPortalTestDatabaseDataSet\&.Designer\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "new global\&.System\&.Data\&.DataRelationCollection Csla\&.Test\&.DataPortalTestDatabaseDataSet\&.Relations\fC [get]\fP"

.PP
Definition at line 98 of file DataPortalTestDatabaseDataSet\&.Designer\&.cs\&.
.SS "override global\&.System\&.Data\&.SchemaSerializationMode Csla\&.Test\&.DataPortalTestDatabaseDataSet\&.SchemaSerializationMode\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 77 of file DataPortalTestDatabaseDataSet\&.Designer\&.cs\&.
.SS "new global\&.System\&.Data\&.DataTableCollection Csla\&.Test\&.DataPortalTestDatabaseDataSet\&.Tables\fC [get]\fP"

.PP
Definition at line 89 of file DataPortalTestDatabaseDataSet\&.Designer\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
