.TH "Csla.AspNetCore.Mvc.TagHelpers.CslaInformationTagHelper" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.AspNetCore.Mvc.TagHelpers.CslaInformationTagHelper \- Razor tag helper that displays CSLA \&.NET information text in a span\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits TagHelper\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBProcess\fP (TagHelperContext context, TagHelperOutput output)"
.br
.RI "Process method "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "ModelExpression \fBCslaInformationFor\fP\fC [get, set]\fP"
.br
.RI "Model expression "
.in -1c
.SH "Detailed Description"
.PP 
Razor tag helper that displays CSLA \&.NET information text in a span\&. 


.PP
Definition at line 19 of file CslaInformationTagHelper\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override void Csla\&.AspNetCore\&.Mvc\&.TagHelpers\&.CslaInformationTagHelper\&.Process (TagHelperContext context, TagHelperOutput output)"

.PP
Process method 
.PP
\fBParameters\fP
.RS 4
\fIcontext\fP 
.br
\fIoutput\fP 
.RE
.PP

.PP
Definition at line 31 of file CslaInformationTagHelper\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "ModelExpression Csla\&.AspNetCore\&.Mvc\&.TagHelpers\&.CslaInformationTagHelper\&.CslaInformationFor\fC [get]\fP, \fC [set]\fP"

.PP
Model expression 
.PP
Definition at line 24 of file CslaInformationTagHelper\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
