.TH "Csla.Test.Linq.TestItem" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.Linq.TestItem
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.BusinessBase< TestItem >\fP\&.
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBPropertyInfo\fP< int > \fBIdProperty\fP = RegisterProperty<int>(c => c\&.Id)"
.br
.ti -1c
.RI "static \fBPropertyInfo\fP< string > \fBNameProperty\fP = RegisterProperty<string>(c => c\&.Name)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBId\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBName\fP\fC [get, set]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 447 of file LinqObservableCollectionTest\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBPropertyInfo\fP<int> Csla\&.Test\&.Linq\&.TestItem\&.IdProperty = RegisterProperty<int>(c => c\&.Id)\fC [static]\fP"

.PP
Definition at line 449 of file LinqObservableCollectionTest\&.cs\&.
.SS "\fBPropertyInfo\fP<string> Csla\&.Test\&.Linq\&.TestItem\&.NameProperty = RegisterProperty<string>(c => c\&.Name)\fC [static]\fP"

.PP
Definition at line 456 of file LinqObservableCollectionTest\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "int Csla\&.Test\&.Linq\&.TestItem\&.Id\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 450 of file LinqObservableCollectionTest\&.cs\&.
.SS "string Csla\&.Test\&.Linq\&.TestItem\&.Name\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 457 of file LinqObservableCollectionTest\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
