.TH "Csla.Core.IExtendedBindingList" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Core.IExtendedBindingList \- Extends IBindingList by adding extra events\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits IBindingList\&.
.PP
Inherited by \fBCsla\&.Core\&.ExtendedBindingList< T >\fP\&.
.SS "Events"

.in +1c
.ti -1c
.RI "EventHandler< \fBRemovingItemEventArgs\fP > \fBRemovingItem\fP"
.br
.RI "Event indicating that an item is being removed from the list\&. "
.in -1c
.SH "Detailed Description"
.PP 
Extends IBindingList by adding extra events\&. 


.PP
Definition at line 17 of file IExtendedBindingList\&.cs\&.
.SH "Event Documentation"
.PP 
.SS "EventHandler<\fBRemovingItemEventArgs\fP> Csla\&.Core\&.IExtendedBindingList\&.RemovingItem"

.PP
Event indicating that an item is being removed from the list\&. 
.PP
Definition at line 23 of file IExtendedBindingList\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
