.TH "Csla.Test.ValidationRules.LookupCustomer" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.ValidationRules.LookupCustomer
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.Rules\&.PropertyRule\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLookupCustomer\fP (\fBIPropertyInfo\fP primaryProperty, \fBIPropertyInfo\fP nameProperty)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBExecute\fP (\fBIRuleContext\fP context)"
.br
.RI "Business or validation rule implementation\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBIPropertyInfo\fP \fBNameProperty\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 242 of file RuleBaseClassesRoot\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Csla\&.Test\&.ValidationRules\&.LookupCustomer\&.LookupCustomer (\fBIPropertyInfo\fP primaryProperty, \fBIPropertyInfo\fP nameProperty)"

.PP
Definition at line 245 of file RuleBaseClassesRoot\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override void Csla\&.Test\&.ValidationRules\&.LookupCustomer\&.Execute (\fBIRuleContext\fP context)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Business or validation rule implementation\&. 
.PP
\fBParameters\fP
.RS 4
\fIcontext\fP Rule context object\&.
.RE
.PP

.PP
Reimplemented from \fBCsla\&.Rules\&.BusinessRule\fP\&.
.PP
Definition at line 258 of file RuleBaseClassesRoot\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "\fBIPropertyInfo\fP Csla\&.Test\&.ValidationRules\&.LookupCustomer\&.NameProperty\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 244 of file RuleBaseClassesRoot\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
