.TH "Csla.Rules.CommonRules.MinLength" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Rules.CommonRules.MinLength \- Business rule for a minimum length string\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.Rules\&.CommonRules\&.CommonBusinessRule\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMinLength\fP (\fBCsla\&.Core\&.IPropertyInfo\fP primaryProperty, int min)"
.br
.RI "Creates an instance of the rule\&. "
.ti -1c
.RI "\fBMinLength\fP (\fBCsla\&.Core\&.IPropertyInfo\fP primaryProperty, int min, string message)"
.br
.RI "Creates an instance of the rule\&. "
.ti -1c
.RI "\fBMinLength\fP (\fBCsla\&.Core\&.IPropertyInfo\fP primaryProperty, int min, Func< string > messageDelegate)"
.br
.RI "Creates an instance of the rule\&. "
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override string \fBGetMessage\fP ()"
.br
.RI "Gets the error message\&. "
.ti -1c
.RI "override void \fBExecute\fP (\fBIRuleContext\fP context)"
.br
.RI "Rule implementation\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBMin\fP\fC [get]\fP"
.br
.RI "Gets the min length value\&. "
.in -1c
.SH "Detailed Description"
.PP 
Business rule for a minimum length string\&. 


.PP
Definition at line 238 of file Csla/Rules/CommonRules\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Csla\&.Rules\&.CommonRules\&.MinLength\&.MinLength (\fBCsla\&.Core\&.IPropertyInfo\fP primaryProperty, int min)"

.PP
Creates an instance of the rule\&. 
.PP
\fBParameters\fP
.RS 4
\fIprimaryProperty\fP Property to which the rule applies\&.
.br
\fImin\fP Min length value\&.
.RE
.PP

.PP
Definition at line 250 of file Csla/Rules/CommonRules\&.cs\&.
.SS "Csla\&.Rules\&.CommonRules\&.MinLength\&.MinLength (\fBCsla\&.Core\&.IPropertyInfo\fP primaryProperty, int min, string message)"

.PP
Creates an instance of the rule\&. 
.PP
\fBParameters\fP
.RS 4
\fIprimaryProperty\fP Property to which the rule applies\&.
.br
\fImessage\fP The message\&.
.br
\fImin\fP The minimum length\&.
.RE
.PP

.PP
Definition at line 264 of file Csla/Rules/CommonRules\&.cs\&.
.SS "Csla\&.Rules\&.CommonRules\&.MinLength\&.MinLength (\fBCsla\&.Core\&.IPropertyInfo\fP primaryProperty, int min, Func< string > messageDelegate)"

.PP
Creates an instance of the rule\&. 
.PP
\fBParameters\fP
.RS 4
\fIprimaryProperty\fP Property to which the rule applies\&.
.br
\fImin\fP Min length value\&.
.br
\fImessageDelegate\fP The localizable message\&.
.RE
.PP

.PP
Definition at line 276 of file Csla/Rules/CommonRules\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override void Csla\&.Rules\&.CommonRules\&.MinLength\&.Execute (\fBIRuleContext\fP context)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Rule implementation\&. 
.PP
\fBParameters\fP
.RS 4
\fIcontext\fP Rule context\&.
.RE
.PP

.PP
Reimplemented from \fBCsla\&.Rules\&.BusinessRule\fP\&.
.PP
Definition at line 295 of file Csla/Rules/CommonRules\&.cs\&.
.SS "override string Csla\&.Rules\&.CommonRules\&.MinLength\&.GetMessage ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Gets the error message\&. 
.PP
Reimplemented from \fBCsla\&.Rules\&.PropertyRule\fP\&.
.PP
Definition at line 286 of file Csla/Rules/CommonRules\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "int Csla\&.Rules\&.CommonRules\&.MinLength\&.Min\fC [get]\fP"

.PP
Gets the min length value\&. 
.PP
Definition at line 243 of file Csla/Rules/CommonRules\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
