.TH "Csla.Validation.CommonRules.DataAnnotationRuleArgs" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Validation.CommonRules.DataAnnotationRuleArgs \- Arguments provided to the DataAnnotation rule method  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.Validation\&.RuleArgs\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDataAnnotationRuleArgs\fP (string name, System\&.ComponentModel\&.DataAnnotations\&.ValidationAttribute attribute)"
.br
.RI "Creates an instance of the object\&. "
.ti -1c
.RI "override string \fBToString\fP ()"
.br
.RI "Gets a string representation of the object\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "System\&.ComponentModel\&.DataAnnotations\&.ValidationAttribute \fBAttribute\fP\fC [get, set]\fP"
.br
.RI "The attribute containing the rule implementation\&. "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Arguments provided to the DataAnnotation rule method 


.PP
Definition at line 1386 of file Csla\&.Validation\&.Shared/CommonRules\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Csla\&.Validation\&.CommonRules\&.DataAnnotationRuleArgs\&.DataAnnotationRuleArgs (string name, System\&.ComponentModel\&.DataAnnotations\&.ValidationAttribute attribute)"

.PP
Creates an instance of the object\&. 
.PP
\fBParameters\fP
.RS 4
\fIname\fP Name of the property to be validated\&. 
.br
\fIattribute\fP System\&.ComponentModel\&.DataAnnotations\&.ValidationAttribute object containing the rule implementation\&. 
.RE
.PP

.PP
Definition at line 1398 of file Csla\&.Validation\&.Shared/CommonRules\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override string Csla\&.Validation\&.CommonRules\&.DataAnnotationRuleArgs\&.ToString ()"

.PP
Gets a string representation of the object\&. 
.PP
Definition at line 1412 of file Csla\&.Validation\&.Shared/CommonRules\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "System\&.ComponentModel\&.DataAnnotations\&.ValidationAttribute Csla\&.Validation\&.CommonRules\&.DataAnnotationRuleArgs\&.Attribute\fC [get]\fP, \fC [set]\fP"

.PP
The attribute containing the rule implementation\&. 
.PP
Definition at line 1407 of file Csla\&.Validation\&.Shared/CommonRules\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
