.TH "Csla.Test.Basic.GenRoot" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.Basic.GenRoot
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.Test\&.Basic\&.GenRootBase\fP, and \fBCsla\&.Test\&.Basic\&.GenRootBase\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 15 of file csla\&.netcore\&.test/Basic/GenRoot\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
