.TH "Csla.IDataPortalFactory" 3 "Thu Jul 22 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.IDataPortalFactory \- Defines a data portal service used to get an access to a client-side data portal instance\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBIDataPortal\fP< T > \fBGetPortal< T >\fP ()"
.br
.RI "Get a client-side data portal instance\&. "
.in -1c
.SH "Detailed Description"
.PP 
Defines a data portal service used to get an access to a client-side data portal instance\&. 


.PP
Definition at line 19 of file IDataPortalFactory\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBIDataPortal\fP<T> Csla\&.IDataPortalFactory\&.GetPortal< T > ()"

.PP
Get a client-side data portal instance\&. 
.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP Root business object type
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
