.TH "Csla.Test.Basic.Root.Criteria" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.Basic.Root.Criteria
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCriteria\fP ()"
.br
.ti -1c
.RI "\fBCriteria\fP (string data)"
.br
.ti -1c
.RI "\fBCriteria\fP ()"
.br
.ti -1c
.RI "\fBCriteria\fP (string data)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fB_data\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 39 of file Root\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Csla\&.Test\&.Basic\&.Root\&.Criteria\&.Criteria ()"

.PP
Definition at line 43 of file Root\&.cs\&.
.SS "Csla\&.Test\&.Basic\&.Root\&.Criteria\&.Criteria (string data)"

.PP
Definition at line 48 of file Root\&.cs\&.
.SS "Csla\&.Test\&.Basic\&.Root\&.Criteria\&.Criteria ()"

.PP
Definition at line 53 of file Root\&.cs\&.
.SS "Csla\&.Test\&.Basic\&.Root\&.Criteria\&.Criteria (string data)"

.PP
Definition at line 58 of file Root\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "string Csla\&.Test\&.Basic\&.Root\&.Criteria\&._data"

.PP
Definition at line 41 of file Root\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
