.TH "Csla.Test.DataPortal.Issue2287List" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.DataPortal.Issue2287List
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.Test\&.DataPortal\&.Issue2287ListBase\fP\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBIssue2287List\fP \fBFetchIssue2287List\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 607 of file ServiceProviderMethodCallerTests\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "static \fBIssue2287List\fP Csla\&.Test\&.DataPortal\&.Issue2287List\&.FetchIssue2287List ()\fC [static]\fP"

.PP
Definition at line 609 of file ServiceProviderMethodCallerTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
