.TH "Csla.Test.ValidationRules.RuleTestClass" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.ValidationRules.RuleTestClass
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.BusinessBase< RuleTestClass >\fP\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBAddBusinessRules\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBName\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string[] \fBRules\fP\fC [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 93 of file RuleDescriptionTests\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override void Csla\&.Test\&.ValidationRules\&.RuleTestClass\&.AddBusinessRules ()\fC [protected]\fP"

.PP
Definition at line 102 of file RuleDescriptionTests\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "string Csla\&.Test\&.ValidationRules\&.RuleTestClass\&.Name\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 96 of file RuleDescriptionTests\&.cs\&.
.SS "string [] Csla\&.Test\&.ValidationRules\&.RuleTestClass\&.Rules\fC [get]\fP"

.PP
Definition at line 107 of file RuleDescriptionTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
