.TH "Csla.Test.DataPortal.DpRoot" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.DataPortal.DpRoot
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.BusinessBase< DpRoot >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDpRoot\fP \fBCloneThis\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBDpRoot\fP \fBNewRoot\fP ()"
.br
.ti -1c
.RI "static \fBDpRoot\fP \fBGetRoot\fP (string data)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBPropertyInfo\fP< string > \fBDataProperty\fP = RegisterProperty<string>(c => c\&.Data)"
.br
.ti -1c
.RI "static \fBPropertyInfo\fP< string > \fBDenyReadOnPropertyProperty\fP = RegisterProperty<string>(c => c\&.DenyReadOnProperty)"
.br
.ti -1c
.RI "static \fBPropertyInfo\fP< string > \fBDenyWriteOnPropertyProperty\fP = RegisterProperty<string>(c => c\&.DenyWriteOnProperty)"
.br
.ti -1c
.RI "static \fBPropertyInfo\fP< string > \fBDenyReadWriteOnPropertyProperty\fP = RegisterProperty<string>(c => c\&.DenyReadWriteOnProperty)"
.br
.ti -1c
.RI "static \fBPropertyInfo\fP< string > \fBAllowReadWriteOnPropertyProperty\fP = RegisterProperty<string>(c => c\&.AllowReadWriteOnProperty)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBDataPortal_Fetch\fP (object criteria)"
.br
.ti -1c
.RI "void \fBDataPortal_Insert\fP ()"
.br
.ti -1c
.RI "void \fBDataPortal_Update\fP ()"
.br
.ti -1c
.RI "void \fBDataPortal_DeleteSelf\fP ()"
.br
.ti -1c
.RI "void \fBDataPortal_Delete\fP (object criteria)"
.br
.ti -1c
.RI "override void \fBDataPortal_OnDataPortalInvoke\fP (\fBDataPortalEventArgs\fP e)"
.br
.ti -1c
.RI "override void \fBDataPortal_OnDataPortalInvokeComplete\fP (\fBDataPortalEventArgs\fP e)"
.br
.ti -1c
.RI "override void \fBAddBusinessRules\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBData\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBAuth\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBDenyReadOnProperty\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBDenyWriteOnProperty\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBDenyReadWriteOnProperty\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBAllowReadWriteOnProperty\fP\fC [get, set]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 17 of file DpRoot\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override void Csla\&.Test\&.DataPortal\&.DpRoot\&.AddBusinessRules ()\fC [protected]\fP"

.PP
Definition at line 142 of file DpRoot\&.cs\&.
.SS "\fBDpRoot\fP Csla\&.Test\&.DataPortal\&.DpRoot\&.CloneThis ()"

.PP
Definition at line 81 of file DpRoot\&.cs\&.
.SS "void Csla\&.Test\&.DataPortal\&.DpRoot\&.DataPortal_Delete (object criteria)\fC [protected]\fP"

.PP
Definition at line 123 of file DpRoot\&.cs\&.
.SS "void Csla\&.Test\&.DataPortal\&.DpRoot\&.DataPortal_DeleteSelf ()\fC [protected]\fP"

.PP
Definition at line 117 of file DpRoot\&.cs\&.
.SS "void Csla\&.Test\&.DataPortal\&.DpRoot\&.DataPortal_Fetch (object criteria)\fC [protected]\fP"

.PP
Definition at line 96 of file DpRoot\&.cs\&.
.SS "void Csla\&.Test\&.DataPortal\&.DpRoot\&.DataPortal_Insert ()\fC [protected]\fP"

.PP
Definition at line 105 of file DpRoot\&.cs\&.
.SS "override void Csla\&.Test\&.DataPortal\&.DpRoot\&.DataPortal_OnDataPortalInvoke (\fBDataPortalEventArgs\fP e)\fC [protected]\fP"

.PP
Definition at line 128 of file DpRoot\&.cs\&.
.SS "override void Csla\&.Test\&.DataPortal\&.DpRoot\&.DataPortal_OnDataPortalInvokeComplete (\fBDataPortalEventArgs\fP e)\fC [protected]\fP"

.PP
Definition at line 133 of file DpRoot\&.cs\&.
.SS "void Csla\&.Test\&.DataPortal\&.DpRoot\&.DataPortal_Update ()\fC [protected]\fP"

.PP
Definition at line 111 of file DpRoot\&.cs\&.
.SS "static \fBDpRoot\fP Csla\&.Test\&.DataPortal\&.DpRoot\&.GetRoot (string data)\fC [static]\fP"

.PP
Definition at line 73 of file DpRoot\&.cs\&.
.SS "static \fBDpRoot\fP Csla\&.Test\&.DataPortal\&.DpRoot\&.NewRoot ()\fC [static]\fP"

.PP
Definition at line 67 of file DpRoot\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBPropertyInfo\fP<string> Csla\&.Test\&.DataPortal\&.DpRoot\&.AllowReadWriteOnPropertyProperty = RegisterProperty<string>(c => c\&.AllowReadWriteOnProperty)\fC [static]\fP"

.PP
Definition at line 214 of file DpRoot\&.cs\&.
.SS "\fBPropertyInfo\fP<string> Csla\&.Test\&.DataPortal\&.DpRoot\&.DataProperty = RegisterProperty<string>(c => c\&.Data)\fC [static]\fP"

.PP
Definition at line 23 of file DpRoot\&.cs\&.
.SS "\fBPropertyInfo\fP<string> Csla\&.Test\&.DataPortal\&.DpRoot\&.DenyReadOnPropertyProperty = RegisterProperty<string>(c => c\&.DenyReadOnProperty)\fC [static]\fP"

.PP
Definition at line 156 of file DpRoot\&.cs\&.
.SS "\fBPropertyInfo\fP<string> Csla\&.Test\&.DataPortal\&.DpRoot\&.DenyReadWriteOnPropertyProperty = RegisterProperty<string>(c => c\&.DenyReadWriteOnProperty)\fC [static]\fP"

.PP
Definition at line 193 of file DpRoot\&.cs\&.
.SS "\fBPropertyInfo\fP<string> Csla\&.Test\&.DataPortal\&.DpRoot\&.DenyWriteOnPropertyProperty = RegisterProperty<string>(c => c\&.DenyWriteOnProperty)\fC [static]\fP"

.PP
Definition at line 174 of file DpRoot\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "string Csla\&.Test\&.DataPortal\&.DpRoot\&.AllowReadWriteOnProperty\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 215 of file DpRoot\&.cs\&.
.SS "string Csla\&.Test\&.DataPortal\&.DpRoot\&.Auth\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 30 of file DpRoot\&.cs\&.
.SS "string Csla\&.Test\&.DataPortal\&.DpRoot\&.Data\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 24 of file DpRoot\&.cs\&.
.SS "string Csla\&.Test\&.DataPortal\&.DpRoot\&.DenyReadOnProperty\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 157 of file DpRoot\&.cs\&.
.SS "string Csla\&.Test\&.DataPortal\&.DpRoot\&.DenyReadWriteOnProperty\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 194 of file DpRoot\&.cs\&.
.SS "string Csla\&.Test\&.DataPortal\&.DpRoot\&.DenyWriteOnProperty\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 175 of file DpRoot\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
