.TH "Csla.Test.DataPortal.Issue2287ListBase" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.DataPortal.Issue2287ListBase
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.BusinessBindingListBase< Issue2287List, Issue2287Edit >\fP\&.
.PP
Inherited by \fBCsla\&.Test\&.DataPortal\&.Issue2287List\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCriteria\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 616 of file ServiceProviderMethodCallerTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
