.TH "Csla.Testing.Business.DataPortal" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Testing.Business.DataPortal
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAsyncPortalWithCulture\fP"
.br
.ti -1c
.RI "class \fBAuthorizeDataPortalStub\fP"
.br
.ti -1c
.RI "class \fBDontAuthorizeDataPortalStub\fP"
.br
.ti -1c
.RI "class \fBSetAppSettingValueCmd\fP"
.br
.ti -1c
.RI "class \fBSingleWithException\fP"
.br
.ti -1c
.RI "class \fBTestableDataPortal\fP"
.br
.RI "Basically this test class exposes protected \fBDataPortal\fP constructor overloads to the Unit \fBTesting\fP System, allowing for a more fine-grained Unit Tests "
.ti -1c
.RI "class \fBTestBO\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
