.TH "Csla.Blazor.CslaValidator" 3 "Thu Jul 22 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Blazor.CslaValidator \- Class offering integration of CSLA validation into \fBBlazor\fP edit forms This is a component with no visible behaviour; it simply requests hook up of validation  

.SH SYNOPSIS
.br
.PP
.PP
Inherits ComponentBase\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnInitialized\fP ()"
.br
.RI "Override to do work after initialization "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "EditContext \fBCurrentEditContext\fP\fC [get, set]\fP"
.br
.RI "Gets or sets the current edit context for the component "
.in -1c
.SH "Detailed Description"
.PP 
Class offering integration of CSLA validation into \fBBlazor\fP edit forms This is a component with no visible behaviour; it simply requests hook up of validation 


.PP
Definition at line 14 of file CslaValidator\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override void Csla\&.Blazor\&.CslaValidator\&.OnInitialized ()\fC [protected]\fP"

.PP
Override to do work after initialization 
.PP
Definition at line 26 of file CslaValidator\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "EditContext Csla\&.Blazor\&.CslaValidator\&.CurrentEditContext\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the current edit context for the component 
.PP
Definition at line 21 of file CslaValidator\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
