.TH "Csla.Server.Hosts.DataPortalChannel.DataPortalResponse" 3 "Thu Jul 22 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Server.Hosts.DataPortalChannel.DataPortalResponse \- Response message for returning the results of a data portal call\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.ReadOnlyBase< DataPortalResponse >\fP\&.
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static readonly \fBPropertyInfo\fP< \fBDataPortalErrorInfo\fP > \fBErrorDataProperty\fP = RegisterProperty<\fBDataPortalErrorInfo\fP>(c => c\&.ErrorData)"
.br
.RI "Server-side exception data if an exception occurred on the server\&. "
.ti -1c
.RI "static readonly \fBPropertyInfo\fP< byte[]> \fBGlobalContextProperty\fP = RegisterProperty<byte[]>(c => c\&.GlobalContext)"
.br
.RI "Serialized GlobalContext data returned from the server (deserialize with MobileFormatter)\&. "
.ti -1c
.RI "static readonly \fBPropertyInfo\fP< byte[]> \fBObjectDataProperty\fP = RegisterProperty<byte[]>(c => c\&.ObjectData)"
.br
.RI "Serialized business object data returned from the server (deserialize with MobileFormatter)\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBDataPortalErrorInfo\fP \fBErrorData\fP\fC [get, set]\fP"
.br
.RI "Server-side exception data if an exception occurred on the server\&. "
.ti -1c
.RI "byte[] \fBGlobalContext\fP\fC [get, set]\fP"
.br
.RI "Serialized GlobalContext data returned from the server (deserialize with MobileFormatter)\&. "
.ti -1c
.RI "byte[] \fBObjectData\fP\fC [get, set]\fP"
.br
.RI "Serialized business object data returned from the server (deserialize with MobileFormatter)\&. "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Response message for returning the results of a data portal call\&. 


.PP
Definition at line 18 of file DataPortalResponse\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "readonly \fBPropertyInfo\fP<\fBDataPortalErrorInfo\fP> Csla\&.Server\&.Hosts\&.DataPortalChannel\&.DataPortalResponse\&.ErrorDataProperty = RegisterProperty<\fBDataPortalErrorInfo\fP>(c => c\&.ErrorData)\fC [static]\fP"

.PP
Server-side exception data if an exception occurred on the server\&. 
.PP
Definition at line 23 of file DataPortalResponse\&.cs\&.
.SS "readonly \fBPropertyInfo\fP<byte[]> Csla\&.Server\&.Hosts\&.DataPortalChannel\&.DataPortalResponse\&.GlobalContextProperty = RegisterProperty<byte[]>(c => c\&.GlobalContext)\fC [static]\fP"

.PP
Serialized GlobalContext data returned from the server (deserialize with MobileFormatter)\&. 
.PP
Definition at line 37 of file DataPortalResponse\&.cs\&.
.SS "readonly \fBPropertyInfo\fP<byte[]> Csla\&.Server\&.Hosts\&.DataPortalChannel\&.DataPortalResponse\&.ObjectDataProperty = RegisterProperty<byte[]>(c => c\&.ObjectData)\fC [static]\fP"

.PP
Serialized business object data returned from the server (deserialize with MobileFormatter)\&. 
.PP
Definition at line 51 of file DataPortalResponse\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "\fBDataPortalErrorInfo\fP Csla\&.Server\&.Hosts\&.DataPortalChannel\&.DataPortalResponse\&.ErrorData\fC [get]\fP, \fC [set]\fP"

.PP
Server-side exception data if an exception occurred on the server\&. 
.PP
Definition at line 28 of file DataPortalResponse\&.cs\&.
.SS "byte [] Csla\&.Server\&.Hosts\&.DataPortalChannel\&.DataPortalResponse\&.GlobalContext\fC [get]\fP, \fC [set]\fP"

.PP
Serialized GlobalContext data returned from the server (deserialize with MobileFormatter)\&. 
.PP
Definition at line 42 of file DataPortalResponse\&.cs\&.
.SS "byte [] Csla\&.Server\&.Hosts\&.DataPortalChannel\&.DataPortalResponse\&.ObjectData\fC [get]\fP, \fC [set]\fP"

.PP
Serialized business object data returned from the server (deserialize with MobileFormatter)\&. 
.PP
Definition at line 56 of file DataPortalResponse\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
