.TH "Csla.Core.RemovingItemEventArgs" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Core.RemovingItemEventArgs \- Contains event data for the RemovingItem event\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits EventArgs\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRemovingItemEventArgs\fP (object removingItem)"
.br
.RI "Create an instance of the object\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "object \fBRemovingItem\fP\fC [get]\fP"
.br
.RI "Gets a reference to the item that was removed from the list\&. "
.in -1c
.SH "Detailed Description"
.PP 
Contains event data for the RemovingItem event\&. 


.PP
Definition at line 16 of file RemovingItemEventArgs\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Csla\&.Core\&.RemovingItemEventArgs\&.RemovingItemEventArgs (object removingItem)"

.PP
Create an instance of the object\&. 
.PP
\fBParameters\fP
.RS 4
\fIremovingItem\fP A reference to the item that was removed from the list\&. 
.RE
.PP

.PP
Definition at line 36 of file RemovingItemEventArgs\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "object Csla\&.Core\&.RemovingItemEventArgs\&.RemovingItem\fC [get]\fP"

.PP
Gets a reference to the item that was removed from the list\&. 
.PP
Definition at line 24 of file RemovingItemEventArgs\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
