.TH "Csla.Test.ValidationRules.RuleTests" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.ValidationRules.RuleTests
.SH SYNOPSIS
.br
.PP
.PP
Inherits TestBase\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "async Task \fBCleanupWhenAddBusinessRulesThrowsException\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 14 of file RuleTests\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "async Task Csla\&.Test\&.ValidationRules\&.RuleTests\&.CleanupWhenAddBusinessRulesThrowsException ()"

.PP
Definition at line 17 of file RuleTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
