.TH "Csla.Test.ChildrenByInterface.Item2" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.ChildrenByInterface.Item2
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.BusinessBase< Item2 >\fP, and \fBCsla\&.Test\&.ChildrenByInterface\&.IItem\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBItem2\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override object \fBGetIdValue\fP ()"
.br
.RI "Override this method to return a unique identifying value for this object\&. "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 58 of file ChildInterfaceTests\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Csla\&.Test\&.ChildrenByInterface\&.Item2\&.Item2 ()"

.PP
Definition at line 60 of file ChildInterfaceTests\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override object Csla\&.Test\&.ChildrenByInterface\&.Item2\&.GetIdValue ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Override this method to return a unique identifying value for this object\&. 
.PP
Reimplemented from \fBCsla\&.BusinessBase< Item2 >\fP\&.
.PP
Definition at line 65 of file ChildInterfaceTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
