.TH "Csla.Blazor.Test.Rules.OneOfSeveralStringsRequiredRule" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Blazor.Test.Rules.OneOfSeveralStringsRequiredRule \- Business rule for when one of two strings must be provided  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.Rules\&.PropertyRule\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBOneOfSeveralStringsRequiredRule\fP (params \fBCsla\&.Core\&.IPropertyInfo\fP[] affectedProperties)"
.br
.RI "Creates an instance of the rule\&. "
.ti -1c
.RI "\fBOneOfSeveralStringsRequiredRule\fP (string message, params \fBCsla\&.Core\&.IPropertyInfo\fP[] affectedProperties)"
.br
.RI "Creates an instance of the rule\&. "
.ti -1c
.RI "\fBOneOfSeveralStringsRequiredRule\fP (Func< string > messageDelegate, params \fBCsla\&.Core\&.IPropertyInfo\fP[] affectedProperties)"
.br
.RI "Creates an instance of the rule\&. "
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override string \fBGetMessage\fP ()"
.br
.RI "Gets the error message\&. "
.ti -1c
.RI "override void \fBExecute\fP (\fBIRuleContext\fP context)"
.br
.RI "Rule implementation\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBRuleSeverity\fP \fBSeverity\fP = RuleSeverity\&.Error\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Business rule for when one of two strings must be provided 


.PP
Definition at line 12 of file OneOfSeveralStringsRequiredRule\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Csla\&.Blazor\&.Test\&.Rules\&.OneOfSeveralStringsRequiredRule\&.OneOfSeveralStringsRequiredRule (params \fBCsla\&.Core\&.IPropertyInfo\fP[] affectedProperties)"

.PP
Creates an instance of the rule\&. 
.PP
\fBParameters\fP
.RS 4
\fIaffectedProperties\fP Array of properties to which the rule applies\&.
.RE
.PP

.PP
Definition at line 19 of file OneOfSeveralStringsRequiredRule\&.cs\&.
.SS "Csla\&.Blazor\&.Test\&.Rules\&.OneOfSeveralStringsRequiredRule\&.OneOfSeveralStringsRequiredRule (string message, params \fBCsla\&.Core\&.IPropertyInfo\fP[] affectedProperties)"

.PP
Creates an instance of the rule\&. 
.PP
\fBParameters\fP
.RS 4
\fIaffectedProperties\fP Array of properties to which the rule applies\&.
.br
\fImessage\fP The message\&.
.RE
.PP

.PP
Definition at line 33 of file OneOfSeveralStringsRequiredRule\&.cs\&.
.SS "Csla\&.Blazor\&.Test\&.Rules\&.OneOfSeveralStringsRequiredRule\&.OneOfSeveralStringsRequiredRule (Func< string > messageDelegate, params \fBCsla\&.Core\&.IPropertyInfo\fP[] affectedProperties)"

.PP
Creates an instance of the rule\&. 
.PP
\fBParameters\fP
.RS 4
\fIaffectedProperties\fP Array of properties to which the rule applies\&.
.br
\fImessageDelegate\fP The localizable message\&.
.RE
.PP

.PP
Definition at line 44 of file OneOfSeveralStringsRequiredRule\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override void Csla\&.Blazor\&.Test\&.Rules\&.OneOfSeveralStringsRequiredRule\&.Execute (\fBIRuleContext\fP context)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Rule implementation\&. 
.PP
\fBParameters\fP
.RS 4
\fIcontext\fP Rule context\&.
.RE
.PP

.PP
Reimplemented from \fBCsla\&.Rules\&.BusinessRule\fP\&.
.PP
Definition at line 65 of file OneOfSeveralStringsRequiredRule\&.cs\&.
.SS "override string Csla\&.Blazor\&.Test\&.Rules\&.OneOfSeveralStringsRequiredRule\&.GetMessage ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Gets the error message\&. 
.PP
Reimplemented from \fBCsla\&.Rules\&.PropertyRule\fP\&.
.PP
Definition at line 56 of file OneOfSeveralStringsRequiredRule\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "\fBRuleSeverity\fP Csla\&.Blazor\&.Test\&.Rules\&.OneOfSeveralStringsRequiredRule\&.Severity = RuleSeverity\&.Error\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 50 of file OneOfSeveralStringsRequiredRule\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
