.TH "Csla.Rules.AuthorizationRuleManager" 3 "Thu Jul 22 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Rules.AuthorizationRuleManager \- Manages the list of authorization rules for a business type\&.  

.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "List< \fBIAuthorizationRule\fP > \fBRules\fP\fC [get]\fP"
.br
.RI "Gets the list of rule objects for the business type\&. "
.ti -1c
.RI "bool \fBInitialized\fP\fC [get, set]\fP"
.br
.RI "Gets or sets a value indicating whether the rules have been initialized\&. "
.ti -1c
.RI "bool \fBInitializedPerType\fP\fC [get, set]\fP"
.br
.RI "Gets or sets a value indicating whether the rules have been initialized\&. "
.in -1c
.SH "Detailed Description"
.PP 
Manages the list of authorization rules for a business type\&. 


.PP
Definition at line 21 of file AuthorizationRuleManager\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "bool Csla\&.Rules\&.AuthorizationRuleManager\&.Initialized\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets a value indicating whether the rules have been initialized\&. 
.PP
Definition at line 146 of file AuthorizationRuleManager\&.cs\&.
.SS "bool Csla\&.Rules\&.AuthorizationRuleManager\&.InitializedPerType\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets a value indicating whether the rules have been initialized\&. 
.PP
Definition at line 151 of file AuthorizationRuleManager\&.cs\&.
.SS "List<\fBIAuthorizationRule\fP> Csla\&.Rules\&.AuthorizationRuleManager\&.Rules\fC [get]\fP"

.PP
Gets the list of rule objects for the business type\&. 
.PP
Definition at line 140 of file AuthorizationRuleManager\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
