.TH "Csla.Test.Security.PermissionsRoot" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.Security.PermissionsRoot
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.BusinessBase< PermissionsRoot >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBDoWork\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBAddObjectAuthorizationRules\fP ()"
.br
.ti -1c
.RI "static \fBPermissionsRoot\fP \fBNewPermissionsRoot\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBPropertyInfo\fP< string > \fBFirstNameProperty\fP = RegisterProperty<string>(c => c\&.FirstName)"
.br
.ti -1c
.RI "static readonly \fBCsla\&.Core\&.IMemberInfo\fP \fBDoWorkMethod\fP = \fBRegisterMethod\fP(typeof(\fBPermissionsRoot\fP), 'DoWork')"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override object \fBGetIdValue\fP ()"
.br
.RI "Override this method to return a unique identifying value for this object\&. "
.ti -1c
.RI "override void \fBAddBusinessRules\fP ()"
.br
.ti -1c
.RI "void \fBDataPortal_Create\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBFirstName\fP\fC [get, set]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 24 of file PermissionsRoot\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override void Csla\&.Test\&.Security\&.PermissionsRoot\&.AddBusinessRules ()\fC [protected]\fP"

.PP
Definition at line 78 of file PermissionsRoot\&.cs\&.
.SS "static void Csla\&.Test\&.Security\&.PermissionsRoot\&.AddObjectAuthorizationRules ()\fC [static]\fP"

.PP
Definition at line 70 of file PermissionsRoot\&.cs\&.
.SS "void Csla\&.Test\&.Security\&.PermissionsRoot\&.DataPortal_Create ()\fC [protected]\fP"

.PP
Definition at line 107 of file PermissionsRoot\&.cs\&.
.SS "void Csla\&.Test\&.Security\&.PermissionsRoot\&.DoWork ()"

.PP
Definition at line 62 of file PermissionsRoot\&.cs\&.
.SS "override object Csla\&.Test\&.Security\&.PermissionsRoot\&.GetIdValue ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Override this method to return a unique identifying value for this object\&. 
.PP
Reimplemented from \fBCsla\&.BusinessBase< PermissionsRoot >\fP\&.
.PP
Definition at line 27 of file PermissionsRoot\&.cs\&.
.SS "static \fBPermissionsRoot\fP Csla\&.Test\&.Security\&.PermissionsRoot\&.NewPermissionsRoot ()\fC [static]\fP"

.PP
Definition at line 89 of file PermissionsRoot\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "readonly \fBCsla\&.Core\&.IMemberInfo\fP Csla\&.Test\&.Security\&.PermissionsRoot\&.DoWorkMethod = \fBRegisterMethod\fP(typeof(\fBPermissionsRoot\fP), 'DoWork')\fC [static]\fP"

.PP
Definition at line 60 of file PermissionsRoot\&.cs\&.
.SS "\fBPropertyInfo\fP<string> Csla\&.Test\&.Security\&.PermissionsRoot\&.FirstNameProperty = RegisterProperty<string>(c => c\&.FirstName)\fC [static]\fP"

.PP
Definition at line 32 of file PermissionsRoot\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "string Csla\&.Test\&.Security\&.PermissionsRoot\&.FirstName\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 34 of file PermissionsRoot\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
