.TH "Csla.Test.Serialization" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.Serialization
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBClaimsPrincipalTests\fP"
.br
.ti -1c
.RI "class \fBSerializationTests\fP"
.br
.ti -1c
.RI "class \fBBinaryReaderWriterTestClassList\fP"
.br
.ti -1c
.RI "class \fBBinaryReaderWriterTestClass\fP"
.br
.ti -1c
.RI "class \fBCslaClaimsPrincipalSerializationTests\fP"
.br
.ti -1c
.RI "class \fBDCRoot\fP"
.br
.ti -1c
.RI "class \fBNonCslaChild\fP"
.br
.ti -1c
.RI "class \fBnonSerializableEventHandler\fP"
.br
.ti -1c
.RI "class \fBNonSerializedClass\fP"
.br
.ti -1c
.RI "class \fBOverrideSerializationRoot\fP"
.br
.ti -1c
.RI "class \fBSerializationRoot\fP"
.br
.ti -1c
.RI "class \fBTestCommand\fP"
.br
.ti -1c
.RI "class \fBTestEventSink\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum class \fBRandomEnum\fP { \fBNone\fP = 0, \fBValue1\fP = 1, \fBValue2\fP = 2 }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBCsla\&.Test\&.Serialization\&.RandomEnum\fP\fC [strong]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fINone \fP\fP
.TP
\fB\fIValue1 \fP\fP
.TP
\fB\fIValue2 \fP\fP
.PP
Definition at line 11 of file BinaryReaderWriterTestClass\&.cs\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
