.TH "Csla.Test.PropertyInfo" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.PropertyInfo
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPropertyInfoRoot\fP"
.br
.ti -1c
.RI "class \fBPropertyInfoTests\fP"
.br
.ti -1c
.RI "class \fBXamlPropertyInfoTests\fP"
.br
.ti -1c
.RI "class \fBTestRoot\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
