.TH "Csla.Testing.Business.ObjectFactory" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Testing.Business.ObjectFactory
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBusinessItem\fP"
.br
.ti -1c
.RI "class \fBObjectFactoryBusinessItem\fP"
.br
.ti -1c
.RI "class \fBObjectFactoryBusinessItemFactory\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
