.TH "Csla.Rules.BusinessRuleManager" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Rules.BusinessRuleManager \- Manages the list of rules for a business type\&.  

.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "List< \fBIBusinessRuleBase\fP > \fBRules\fP\fC [get]\fP"
.br
.RI "Gets the list of rule objects for the business type\&. "
.ti -1c
.RI "bool \fBInitialized\fP\fC [get, set]\fP"
.br
.RI "Gets or sets a value indicating whether the rules have been initialized\&. "
.in -1c
.SH "Detailed Description"
.PP 
Manages the list of rules for a business type\&. 


.PP
Definition at line 17 of file BusinessRuleManager\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "bool Csla\&.Rules\&.BusinessRuleManager\&.Initialized\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets a value indicating whether the rules have been initialized\&. 
.PP
Definition at line 78 of file BusinessRuleManager\&.cs\&.
.SS "List<\fBIBusinessRuleBase\fP> Csla\&.Rules\&.BusinessRuleManager\&.Rules\fC [get]\fP"

.PP
Gets the list of rule objects for the business type\&. 
.PP
Definition at line 72 of file BusinessRuleManager\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
