.TH "Csla.Test.Basic.SerializableListener" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.Basic.SerializableListener
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSerializableListener\fP (\fBCore\&.BusinessBase\fP obj)"
.br
.ti -1c
.RI "void \fBObj_IsDirtyChanged\fP (object sender, System\&.ComponentModel\&.PropertyChangedEventArgs e)"
.br
.ti -1c
.RI "\fBSerializableListener\fP (\fBCore\&.BusinessBase\fP obj)"
.br
.ti -1c
.RI "void \fBobj_IsDirtyChanged\fP (object sender, System\&.ComponentModel\&.PropertyChangedEventArgs e)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 479 of file BasicTests\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Csla\&.Test\&.Basic\&.SerializableListener\&.SerializableListener (\fBCore\&.BusinessBase\fP obj)"

.PP
Definition at line 483 of file BasicTests\&.cs\&.
.SS "Csla\&.Test\&.Basic\&.SerializableListener\&.SerializableListener (\fBCore\&.BusinessBase\fP obj)"

.PP
Definition at line 415 of file BasicTests\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Csla\&.Test\&.Basic\&.SerializableListener\&.Obj_IsDirtyChanged (object sender, System\&.ComponentModel\&.PropertyChangedEventArgs e)"

.PP
Definition at line 489 of file BasicTests\&.cs\&.
.SS "void Csla\&.Test\&.Basic\&.SerializableListener\&.obj_IsDirtyChanged (object sender, System\&.ComponentModel\&.PropertyChangedEventArgs e)"

.PP
Definition at line 421 of file BasicTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
