.TH "Csla.Test.ValidationRules.RuleDescriptionTests" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.ValidationRules.RuleDescriptionTests
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBCheckDescription\fP ()"
.br
.ti -1c
.RI "void \fBBasicParsing\fP ()"
.br
.ti -1c
.RI "void \fBNameParsing\fP ()"
.br
.ti -1c
.RI "void \fBSpecialCharacterParsing\fP ()"
.br
.ti -1c
.RI "void \fBLongTypeName\fP ()"
.br
.ti -1c
.RI "void \fBArguments\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 27 of file RuleDescriptionTests\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Csla\&.Test\&.ValidationRules\&.RuleDescriptionTests\&.Arguments ()"

.PP
Definition at line 79 of file RuleDescriptionTests\&.cs\&.
.SS "void Csla\&.Test\&.ValidationRules\&.RuleDescriptionTests\&.BasicParsing ()"

.PP
Definition at line 41 of file RuleDescriptionTests\&.cs\&.
.SS "void Csla\&.Test\&.ValidationRules\&.RuleDescriptionTests\&.CheckDescription ()"

.PP
Definition at line 30 of file RuleDescriptionTests\&.cs\&.
.SS "void Csla\&.Test\&.ValidationRules\&.RuleDescriptionTests\&.LongTypeName ()"

.PP
Definition at line 69 of file RuleDescriptionTests\&.cs\&.
.SS "void Csla\&.Test\&.ValidationRules\&.RuleDescriptionTests\&.NameParsing ()"

.PP
Definition at line 53 of file RuleDescriptionTests\&.cs\&.
.SS "void Csla\&.Test\&.ValidationRules\&.RuleDescriptionTests\&.SpecialCharacterParsing ()"

.PP
Definition at line 61 of file RuleDescriptionTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
