.TH "Csla.DeleteSelfAttribute" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.DeleteSelfAttribute \- Specifies a method used by the server-side data portal to delete domain object data during an explicit delete operation\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.DataPortalRootOperationAttribute\fP\&.
.SH "Detailed Description"
.PP 
Specifies a method used by the server-side data portal to delete domain object data during an explicit delete operation\&. 


.PP
Definition at line 104 of file DataPortalOperationAttributes\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
