.TH "Csla.Test.Silverlight.Rollback.RollbackRoot" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.Silverlight.Rollback.RollbackRoot
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.BusinessBase< RollbackRoot >\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBUnInitedP\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBAnother\fP\fC [get, set]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 15 of file Silverlight/Rollback/RollbackRoot\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "string Csla\&.Test\&.Silverlight\&.Rollback\&.RollbackRoot\&.Another\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 27 of file Silverlight/Rollback/RollbackRoot\&.cs\&.
.SS "int Csla\&.Test\&.Silverlight\&.Rollback\&.RollbackRoot\&.UnInitedP\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 20 of file Silverlight/Rollback/RollbackRoot\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
