.TH "Csla.Server.Hosts.Mobile.MobileUpdateRequest" 3 "Thu Jul 22 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Server.Hosts.Mobile.MobileUpdateRequest \- Class that will be used to execute an Update request from a client\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.Server\&.Hosts\&.Mobile\&.IMobileRequest\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMobileUpdateRequest\fP (object objectToUpdate, IPrincipal principal, \fBContextDictionary\fP globalContext, \fBContextDictionary\fP clientContext, string clientCulture, string clientUICulture)"
.br
.RI "New instance of criteria object "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "object \fBObjectToUpdate\fP\fC [get, set]\fP"
.br
.RI "Business object that will be updated\&. "
.ti -1c
.RI "IPrincipal \fBPrincipal\fP\fC [get, set]\fP"
.br
.RI "Principal that will be set for the request "
.ti -1c
.RI "\fBContextDictionary\fP \fBGlobalContext\fP\fC [get, set]\fP"
.br
.RI "Global context object\&. "
.ti -1c
.RI "\fBContextDictionary\fP \fBClientContext\fP\fC [get, set]\fP"
.br
.RI "Client context object\&. "
.ti -1c
.RI "string \fBClientCulture\fP\fC [get, set]\fP"
.br
.RI "The client culture\&. "
.ti -1c
.RI "string \fBClientUICulture\fP\fC [get, set]\fP"
.br
.RI "The client UI culture\&. "
.in -1c
.SH "Detailed Description"
.PP 
Class that will be used to execute an Update request from a client\&. 


.PP
Definition at line 17 of file MobileUpdateRequest\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Csla\&.Server\&.Hosts\&.Mobile\&.MobileUpdateRequest\&.MobileUpdateRequest (object objectToUpdate, IPrincipal principal, \fBContextDictionary\fP globalContext, \fBContextDictionary\fP clientContext, string clientCulture, string clientUICulture)"

.PP
New instance of criteria object 
.PP
\fBParameters\fP
.RS 4
\fIobjectToUpdate\fP Business object that will be updated\&.
.br
\fIprincipal\fP Principal that will be set for the request
.br
\fIglobalContext\fP Global context object\&.
.br
\fIclientContext\fP Client context object\&.
.br
\fIclientCulture\fP The client culture\&.
.br
\fIclientUICulture\fP The client UI culture\&.
.RE
.PP

.PP
Definition at line 53 of file MobileUpdateRequest\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "\fBContextDictionary\fP Csla\&.Server\&.Hosts\&.Mobile\&.MobileUpdateRequest\&.ClientContext\fC [get]\fP, \fC [set]\fP"

.PP
Client context object\&. 
.PP
Definition at line 34 of file MobileUpdateRequest\&.cs\&.
.SS "string Csla\&.Server\&.Hosts\&.Mobile\&.MobileUpdateRequest\&.ClientCulture\fC [get]\fP, \fC [set]\fP"

.PP
The client culture\&. 
.PP
Definition at line 38 of file MobileUpdateRequest\&.cs\&.
.SS "string Csla\&.Server\&.Hosts\&.Mobile\&.MobileUpdateRequest\&.ClientUICulture\fC [get]\fP, \fC [set]\fP"

.PP
The client UI culture\&. 
.PP
Definition at line 42 of file MobileUpdateRequest\&.cs\&.
.SS "\fBContextDictionary\fP Csla\&.Server\&.Hosts\&.Mobile\&.MobileUpdateRequest\&.GlobalContext\fC [get]\fP, \fC [set]\fP"

.PP
Global context object\&. 
.PP
Definition at line 30 of file MobileUpdateRequest\&.cs\&.
.SS "object Csla\&.Server\&.Hosts\&.Mobile\&.MobileUpdateRequest\&.ObjectToUpdate\fC [get]\fP, \fC [set]\fP"

.PP
Business object that will be updated\&. 
.PP
Definition at line 22 of file MobileUpdateRequest\&.cs\&.
.SS "IPrincipal Csla\&.Server\&.Hosts\&.Mobile\&.MobileUpdateRequest\&.Principal\fC [get]\fP, \fC [set]\fP"

.PP
Principal that will be set for the request 
.PP
Definition at line 26 of file MobileUpdateRequest\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
