.TH "Csla.Web.Mvc.Test.ModelBinderTest.ImAlwaysInvalidAttribute" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Web.Mvc.Test.ModelBinderTest.ImAlwaysInvalidAttribute
.SH SYNOPSIS
.br
.PP
.PP
Inherits ValidationAttribute\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBImAlwaysInvalidAttribute\fP (string errorMessage)"
.br
.ti -1c
.RI "override bool \fBIsValid\fP (object value)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 60 of file RootWithValidation\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Csla\&.Web\&.Mvc\&.Test\&.ModelBinderTest\&.ImAlwaysInvalidAttribute\&.ImAlwaysInvalidAttribute (string errorMessage)"

.PP
Definition at line 62 of file RootWithValidation\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override bool Csla\&.Web\&.Mvc\&.Test\&.ModelBinderTest\&.ImAlwaysInvalidAttribute\&.IsValid (object value)"

.PP
Definition at line 66 of file RootWithValidation\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
