.TH "cslalighttest.ReadOnly.MockReadOnly" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cslalighttest.ReadOnly.MockReadOnly
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.BusinessBase< MockReadOnly >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMockReadOnly\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static readonly \fBPropertyInfo\fP< int > \fBIdProperty\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBId\fP\fC [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 26 of file MockReadOnly\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "cslalighttest\&.ReadOnly\&.MockReadOnly\&.MockReadOnly ()"

.PP
Definition at line 28 of file MockReadOnly\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "readonly \fBPropertyInfo\fP<int> cslalighttest\&.ReadOnly\&.MockReadOnly\&.IdProperty\fC [static]\fP"
\fBInitial value:\fP
.PP
.nf
= RegisterProperty<int>(
      typeof(MockReadOnly),
      new PropertyInfo<int>("Id"))
.fi
.PP
Definition at line 30 of file MockReadOnly\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "int cslalighttest\&.ReadOnly\&.MockReadOnly\&.Id\fC [get]\fP"

.PP
Definition at line 34 of file MockReadOnly\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
