.TH "Csla.Test.CslaDataProvider.CslaDataProviderTests" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.CslaDataProvider.CslaDataProviderTests
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBTestAddNew\fP ()"
.br
.ti -1c
.RI "void \fBTestAddNewReturnsNull\fP ()"
.br
.ti -1c
.RI "void \fBTestCancelError\fP ()"
.br
.ti -1c
.RI "void \fBTestSavedWithChanges\fP ()"
.br
.ti -1c
.RI "void \fBTestSavedWithChangesInvalid\fP ()"
.br
.ti -1c
.RI "void \fBTestSavedWithoutChanges\fP ()"
.br
.ti -1c
.RI "void \fBClearContextsAfterEachTest\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 30 of file CslaDataProviderTests\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Csla\&.Test\&.CslaDataProvider\&.CslaDataProviderTests\&.ClearContextsAfterEachTest ()"

.PP
Definition at line 126 of file CslaDataProviderTests\&.cs\&.
.SS "void Csla\&.Test\&.CslaDataProvider\&.CslaDataProviderTests\&.TestAddNew ()"

.PP
Definition at line 33 of file CslaDataProviderTests\&.cs\&.
.SS "void Csla\&.Test\&.CslaDataProvider\&.CslaDataProviderTests\&.TestAddNewReturnsNull ()"

.PP
Definition at line 44 of file CslaDataProviderTests\&.cs\&.
.SS "void Csla\&.Test\&.CslaDataProvider\&.CslaDataProviderTests\&.TestCancelError ()"

.PP
Definition at line 54 of file CslaDataProviderTests\&.cs\&.
.SS "void Csla\&.Test\&.CslaDataProvider\&.CslaDataProviderTests\&.TestSavedWithChanges ()"

.PP
Definition at line 72 of file CslaDataProviderTests\&.cs\&.
.SS "void Csla\&.Test\&.CslaDataProvider\&.CslaDataProviderTests\&.TestSavedWithChangesInvalid ()"

.PP
Definition at line 91 of file CslaDataProviderTests\&.cs\&.
.SS "void Csla\&.Test\&.CslaDataProvider\&.CslaDataProviderTests\&.TestSavedWithoutChanges ()"

.PP
Definition at line 109 of file CslaDataProviderTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
