.TH "Csla.Test.Serialization.OverrideSerializationRoot" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.Serialization.OverrideSerializationRoot
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.Test\&.Serialization\&.SerializationRoot\fP\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override bool \fBShouldHandlerSerialize\fP (PropertyChangedEventHandler value)"
.br
.ti -1c
.RI "override bool \fBShouldHandlerSerialize\fP (PropertyChangingEventHandler value)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 7 of file OverrideSerializationRoot\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override bool Csla\&.Test\&.Serialization\&.OverrideSerializationRoot\&.ShouldHandlerSerialize (PropertyChangedEventHandler value)\fC [protected]\fP"

.PP
Definition at line 9 of file OverrideSerializationRoot\&.cs\&.
.SS "override bool Csla\&.Test\&.Serialization\&.OverrideSerializationRoot\&.ShouldHandlerSerialize (PropertyChangingEventHandler value)\fC [protected]\fP"

.PP
Definition at line 17 of file OverrideSerializationRoot\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
