.TH "Csla.Test.DataAnnotations.DataAnnotationsTests" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Csla.Test.DataAnnotations.DataAnnotationsTests
.SH SYNOPSIS
.br
.PP
.PP
Inherits TestBase\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "async Task \fBSingleAttribute\fP ()"
.br
.ti -1c
.RI "async Task \fBMultipleAttributes\fP ()"
.br
.ti -1c
.RI "async Task \fBCustomAttribute\fP ()"
.br
.ti -1c
.RI "void \fBMultipleMetaRules\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 37 of file DataAnnotationsTests\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "async Task Csla\&.Test\&.DataAnnotations\&.DataAnnotationsTests\&.CustomAttribute ()"

.PP
Definition at line 77 of file DataAnnotationsTests\&.cs\&.
.SS "async Task Csla\&.Test\&.DataAnnotations\&.DataAnnotationsTests\&.MultipleAttributes ()"

.PP
Definition at line 58 of file DataAnnotationsTests\&.cs\&.
.SS "void Csla\&.Test\&.DataAnnotations\&.DataAnnotationsTests\&.MultipleMetaRules ()"

.PP
Definition at line 95 of file DataAnnotationsTests\&.cs\&.
.SS "async Task Csla\&.Test\&.DataAnnotations\&.DataAnnotationsTests\&.SingleAttribute ()"

.PP
Definition at line 40 of file DataAnnotationsTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
