.TH "CustomerWithEnum.cs" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CustomerWithEnum.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBcslalighttest\&.Serialization\&.CustomerWithEnum\fP"
.br
.RI "Implementation of a test business object with an enum\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBcslalighttest\fP"
.br
.ti -1c
.RI "namespace \fBcslalighttest\&.Serialization\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum class \fBcslalighttest\&.Serialization\&.CustomerQuality\fP { \fBcslalighttest\&.Serialization\&.None\fP = 0, \fBcslalighttest\&.Serialization\&.Good\fP = 1, \fBcslalighttest\&.Serialization\&.Bad\fP = 2 }"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
