.TH "DataBindingApp.Form1" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DataBindingApp.Form1
.SH SYNOPSIS
.br
.PP
.PP
Inherits Form\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMyObject\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBForm1\fP ()"
.br
.ti -1c
.RI "void \fBdataSource_AddingNew\fP (object sender, AddingNewEventArgs e)"
.br
.ti -1c
.RI "void \fBRunFormWithBusinessListBaseObj\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBMain\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 19 of file Form1\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "DataBindingApp\&.Form1\&.Form1 ()"

.PP
Definition at line 25 of file Form1\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void DataBindingApp\&.Form1\&.dataSource_AddingNew (object sender, AddingNewEventArgs e)"

.PP
Definition at line 97 of file Form1\&.cs\&.
.SS "static void DataBindingApp\&.Form1\&.Main ()\fC [static]\fP"

.PP
Definition at line 147 of file Form1\&.cs\&.
.SS "void DataBindingApp\&.Form1\&.RunFormWithBusinessListBaseObj ()"

.PP
Definition at line 141 of file Form1\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
