.TH "DataPortalOperations.cs" 3 "Thu Jul 22 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DataPortalOperations.cs
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBCsla\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum class \fBCsla\&.DataPortalOperations\fP : int { \fBCsla\&.Create\fP, \fBCsla\&.Fetch\fP, \fBCsla\&.Update\fP, \fBCsla\&.Delete\fP, \fBCsla\&.Execute\fP }"
.br
.RI "List of data portal operations\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
