.TH "DataPortalOperationAttributes.cs" 3 "Thu Jul 22 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DataPortalOperationAttributes.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCsla\&.InjectAttribute\fP"
.br
.RI "Specifies a parameter that is provided via dependency injection\&. "
.ti -1c
.RI "class \fBCsla\&.DataPortalOperationAttribute\fP"
.br
.RI "Base type for data portal operation attributes\&. "
.ti -1c
.RI "class \fBCsla\&.DataPortalRootOperationAttribute\fP"
.br
.RI "Base type for data portal root operation attributes\&. "
.ti -1c
.RI "class \fBCsla\&.DataPortalChildOperationAttribute\fP"
.br
.RI "Base type for data portal child operation attributes\&. "
.ti -1c
.RI "class \fBCsla\&.CreateAttribute\fP"
.br
.RI "Specifies a method used by the server-side data portal to initialize a new domain object\&. "
.ti -1c
.RI "class \fBCsla\&.FetchAttribute\fP"
.br
.RI "Specifies a method used by the server-side data portal to load existing data into the domain object\&. "
.ti -1c
.RI "class \fBCsla\&.InsertAttribute\fP"
.br
.RI "Specifies a method used by the server-side data portal to insert domain object data during an update operation\&. "
.ti -1c
.RI "class \fBCsla\&.UpdateAttribute\fP"
.br
.RI "Specifies a method used by the server-side data portal to update domain object data during an update operation\&. "
.ti -1c
.RI "class \fBCsla\&.ExecuteAttribute\fP"
.br
.RI "Specifies a method used by the server-side data portal to execute a command object\&. "
.ti -1c
.RI "class \fBCsla\&.DeleteAttribute\fP"
.br
.RI "Specifies a method used by the server-side data portal to delete domain object data during an update operation\&. "
.ti -1c
.RI "class \fBCsla\&.DeleteSelfAttribute\fP"
.br
.RI "Specifies a method used by the server-side data portal to delete domain object data during an explicit delete operation\&. "
.ti -1c
.RI "class \fBCsla\&.CreateChildAttribute\fP"
.br
.RI "Specifies a method used by the server-side data portal to initialize a new child object\&. "
.ti -1c
.RI "class \fBCsla\&.FetchChildAttribute\fP"
.br
.RI "Specifies a method used by the server-side data portal to load existing data into the child object\&. "
.ti -1c
.RI "class \fBCsla\&.InsertChildAttribute\fP"
.br
.RI "Specifies a method used by the server-side data portal to insert child object data during an update operation\&. "
.ti -1c
.RI "class \fBCsla\&.UpdateChildAttribute\fP"
.br
.RI "Specifies a method used by the server-side data portal to update child object data during an update operation\&. "
.ti -1c
.RI "class \fBCsla\&.DeleteSelfChildAttribute\fP"
.br
.RI "Specifies a method used by the server-side data portal to delete child object data during an update operation\&. "
.ti -1c
.RI "class \fBCsla\&.ExecuteChildAttribute\fP"
.br
.RI "Specifies a method used by the server-side data portal to execute a child command object during an update operation\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBCsla\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
