.TH "DataBindingApp.ListObject.DataObject" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DataBindingApp.ListObject.DataObject
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.BusinessBase< DataObject >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDataObject\fP (string data, int number)"
.br
.ti -1c
.RI "void \fBDataObject_PropertyChanged\fP (object sender, System\&.ComponentModel\&.PropertyChangedEventArgs e)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override object \fBGetIdValue\fP ()"
.br
.RI "Override this method to return a unique identifying value for this object\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBNumber\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBData\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBID\fP\fC [get, set]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 20 of file ListObject\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "DataBindingApp\&.ListObject\&.DataObject\&.DataObject (string data, int number)"

.PP
Definition at line 49 of file ListObject\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void DataBindingApp\&.ListObject\&.DataObject\&.DataObject_PropertyChanged (object sender, System\&.ComponentModel\&.PropertyChangedEventArgs e)"

.PP
Definition at line 57 of file ListObject\&.cs\&.
.SS "override object DataBindingApp\&.ListObject\&.DataObject\&.GetIdValue ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Override this method to return a unique identifying value for this object\&. 
.PP
Reimplemented from \fBCsla\&.BusinessBase< DataObject >\fP\&.
.PP
Definition at line 44 of file ListObject\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "string DataBindingApp\&.ListObject\&.DataObject\&.Data\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 32 of file ListObject\&.cs\&.
.SS "int DataBindingApp\&.ListObject\&.DataObject\&.ID\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 38 of file ListObject\&.cs\&.
.SS "int DataBindingApp\&.ListObject\&.DataObject\&.Number\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 26 of file ListObject\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
