.TH "DataMapperTests.cs" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DataMapperTests.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCsla\&.Test\&.DataMapper\&.DataMapperTests\fP"
.br
.ti -1c
.RI "class \fBCsla\&.Test\&.DataMapper\&.ManagedTarget\fP"
.br
.ti -1c
.RI "class \fBCsla\&.Test\&.DataMapper\&.DataMapTarget\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBCsla\fP"
.br
.ti -1c
.RI "namespace \fBCsla\&.Test\fP"
.br
.ti -1c
.RI "namespace \fBCsla\&.Test\&.DataMapper\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum class \fBCsla\&.Test\&.DataMapper\&.DataMapEnum\fP { \fBCsla\&.Test\&.DataMapper\&.First\fP, \fBCsla\&.Test\&.DataMapper\&.Second\fP, \fBCsla\&.Test\&.DataMapper\&.Third\fP }"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
