.TH "DataAnnotationsTests.cs" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DataAnnotationsTests.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCsla\&.Test\&.DataAnnotations\&.DataAnnotationsTests\fP"
.br
.ti -1c
.RI "class \fBCsla\&.Test\&.DataAnnotations\&.Single\fP"
.br
.ti -1c
.RI "class \fBCsla\&.Test\&.DataAnnotations\&.Multiple\fP"
.br
.ti -1c
.RI "class \fBCsla\&.Test\&.DataAnnotations\&.Custom\fP"
.br
.ti -1c
.RI "class \fBCsla\&.Test\&.DataAnnotations\&.TestRuleAttribute\fP"
.br
.ti -1c
.RI "class \fBCsla\&.Test\&.DataAnnotations\&.MultipleMeta\fP"
.br
.ti -1c
.RI "class \fBCsla\&.Test\&.DataAnnotations\&.MultipleMetaDataClass\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBCsla\fP"
.br
.ti -1c
.RI "namespace \fBCsla\&.Test\fP"
.br
.ti -1c
.RI "namespace \fBCsla\&.Test\&.DataAnnotations\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
