.TH "DataBindingApp.Form1.MyObject" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DataBindingApp.Form1.MyObject
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMyObject\fP (string name, int age)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBName\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBAge\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 52 of file Form1\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "DataBindingApp\&.Form1\&.MyObject\&.MyObject (string name, int age)"

.PP
Definition at line 69 of file Form1\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "int DataBindingApp\&.Form1\&.MyObject\&.Age\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 63 of file Form1\&.cs\&.
.SS "string DataBindingApp\&.Form1\&.MyObject\&.Name\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 57 of file Form1\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
