.TH "UpdateRequest.cs" 3 "Thu Jul 22 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UpdateRequest.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCsla\&.Server\&.Hosts\&.DataPortalChannel\&.UpdateRequest\fP"
.br
.RI "Request message for updating a business object\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBCsla\fP"
.br
.ti -1c
.RI "namespace \fBCsla\&.Server\fP"
.br
.ti -1c
.RI "namespace \fBCsla\&.Server\&.Hosts\fP"
.br
.ti -1c
.RI "namespace \fBCsla\&.Server\&.Hosts\&.DataPortalChannel\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
