.TH "C:/Users/korye/source/repos/csla/Source/csla.netcore.test/DataPortal/DataPortalClientTests.cs" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/korye/source/repos/csla/Source/csla.netcore.test/DataPortal/DataPortalClientTests.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBcsla\&.netcore\&.test\&.DataPortal\&.DataPortalClientTests\fP"
.br
.ti -1c
.RI "class \fBcsla\&.netcore\&.test\&.DataPortal\&.DefaultType\fP"
.br
.ti -1c
.RI "class \fBcsla\&.netcore\&.test\&.DataPortal\&.TestType\fP"
.br
.ti -1c
.RI "class \fBcsla\&.netcore\&.test\&.DataPortal\&.ResourceType\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBcsla\fP"
.br
.ti -1c
.RI "namespace \fBcsla\&.netcore\fP"
.br
.ti -1c
.RI "namespace \fBcsla\&.netcore\&.test\fP"
.br
.ti -1c
.RI "namespace \fBcsla\&.netcore\&.test\&.DataPortal\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum class \fBcsla\&.netcore\&.test\&.DataPortal\&.ServerResources\fP { \fBcsla\&.netcore\&.test\&.DataPortal\&.LotsOfMemory\fP, \fBcsla\&.netcore\&.test\&.DataPortal\&.AccessToLegacyDatabase\fP, \fBcsla\&.netcore\&.test\&.DataPortal\&.SpecializedAlgorithm\fP }"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
