.TH "DataBindingApp.ListObject" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DataBindingApp.ListObject
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.BusinessListBase< ListObject, ListObject\&.DataObject >\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDataObject\fP"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBListObject\fP \fBGetList\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 17 of file ListObject\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "static \fBListObject\fP DataBindingApp\&.ListObject\&.GetList ()\fC [static]\fP"

.PP
Definition at line 66 of file ListObject\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
