.TH "DefaultPropertyInfoFactory.cs" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DefaultPropertyInfoFactory.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCsla\&.Core\&.FieldManager\&.DefaultPropertyInfoFactory\fP"
.br
.RI "Creates \fBPropertyInfo\fP objects\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBCsla\fP"
.br
.ti -1c
.RI "namespace \fBCsla\&.Core\fP"
.br
.ti -1c
.RI "namespace \fBCsla\&.Core\&.FieldManager\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
