.TH "DictionaryCheckResult.cs" 3 "Thu Jul 22 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DictionaryCheckResult.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBCsla\&.Serialization\&.Mobile\&.DictionaryCheckResult\fP"
.br
.RI "This struct contains the result of check for existing dictionary key/value pair when creating internal dictionary of strings in order to minimize the amount of data that \fBCslaBinaryWriter\fP sends over the wire "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBCsla\fP"
.br
.ti -1c
.RI "namespace \fBCsla\&.Serialization\fP"
.br
.ti -1c
.RI "namespace \fBCsla\&.Serialization\&.Mobile\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
