.TH "FilterProvider.cs" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FilterProvider.cs
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBCsla\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "delegate bool \fBCsla\&.FilterProvider\fP (object item, object filter)"
.br
.RI "Defines the method signature for a filter provider method used by \fBFilteredBindingList\fP\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
