.TH "C:/Users/korye/source/repos/csla/Source/Csla.Channels.Grpc/GrpcProxy.cs" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/korye/source/repos/csla/Source/Csla.Channels.Grpc/GrpcProxy.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCsla\&.Channels\&.Grpc\&.GrpcProxy\fP"
.br
.RI "Implements a data portal proxy to relay data portal calls to a remote application server by using gRPC\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBCsla\fP"
.br
.ti -1c
.RI "namespace \fBCsla\&.Channels\fP"
.br
.ti -1c
.RI "namespace \fBCsla\&.Channels\&.Grpc\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
