.TH "HostPropertyAttribute.cs" 3 "Thu Jul 22 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HostPropertyAttribute.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCsla\&.Windows\&.HostPropertyAttribute\fP"
.br
.RI "\fBHostPropertyAttribute\fP is used on components to indicate the property on the component that is to be used as the parent container control in conjunction with HostComponentDesigner\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBCsla\fP"
.br
.ti -1c
.RI "namespace \fBCsla\&.Windows\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
