.TH "HtmlExtensions.cs" 3 "Thu Jul 22 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HtmlExtensions.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCsla\&.Web\&.Mvc\&.HtmlExtensions\fP"
.br
.RI "Html extension methods providing support for HTML rendering based on security permissions in an application\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBCsla\fP"
.br
.ti -1c
.RI "namespace \fBCsla\&.Web\fP"
.br
.ti -1c
.RI "namespace \fBCsla\&.Web\&.Mvc\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
