.TH "IBusinessRule.cs" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IBusinessRule.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "interface \fBCsla\&.Rules\&.IBusinessRuleBase\fP"
.br
.RI "Interface defining a business/validation rule implementation\&. "
.ti -1c
.RI "interface \fBCsla\&.Rules\&.IBusinessRule\fP"
.br
.RI "Interface defining a business/validation rule implementation\&. "
.ti -1c
.RI "interface \fBCsla\&.Rules\&.IBusinessRuleAsync\fP"
.br
.RI "Interface defining a business/validation rule implementation\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBCsla\fP"
.br
.ti -1c
.RI "namespace \fBCsla\&.Rules\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum class \fBCsla\&.Rules\&.RunModes\fP { \fBCsla\&.Rules\&.Default\fP =0, \fBCsla\&.Rules\&.DenyCheckRules\fP = 1, \fBCsla\&.Rules\&.DenyAsAffectedProperty\fP = 2, \fBCsla\&.Rules\&.DenyOnServerSidePortal\fP = 4 }"
.br
.RI "Flags enum to define when rule is allowed or denied to run "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
