.TH "ICslaWriter.cs" 3 "Thu Jul 22 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ICslaWriter.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "interface \fBCsla\&.Serialization\&.Mobile\&.ICslaWriter\fP"
.br
.RI "Represents a class that can be used to write a list of \fBSerializationInfo\fP objects into a stream, typically MemoryStream "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBCsla\fP"
.br
.ti -1c
.RI "namespace \fBCsla\&.Serialization\fP"
.br
.ti -1c
.RI "namespace \fBCsla\&.Serialization\&.Mobile\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
