.TH "InheritedOperationTests.cs" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
InheritedOperationTests.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCsla\&.Test\&.DataPortal\&.InheritedOperationTests\fP"
.br
.ti -1c
.RI "class \fBCsla\&.Test\&.DataPortal\&.PersonList\fP"
.br
.ti -1c
.RI "class \fBCsla\&.Test\&.DataPortal\&.PersonListBase\fP"
.br
.ti -1c
.RI "class \fBCsla\&.Test\&.DataPortal\&.PersonListBase\&.Criteria\fP"
.br
.ti -1c
.RI "class \fBCsla\&.Test\&.DataPortal\&.PersonEdit\fP"
.br
.ti -1c
.RI "class \fBCsla\&.Test\&.DataPortal\&.PersonEditBase< T >\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBCsla\fP"
.br
.ti -1c
.RI "namespace \fBCsla\&.Test\fP"
.br
.ti -1c
.RI "namespace \fBCsla\&.Test\&.DataPortal\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
