.TH "NameValueListBase.cs" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NameValueListBase.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCsla\&.NameValueListBase< K, V >\fP"
.br
.RI "This is the base class from which readonly name/value collections should be derived\&. "
.ti -1c
.RI "class \fBCsla\&.NameValueListBase< K, V >\&.NameValuePair\fP"
.br
.RI "Contains a key and value pair\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBCsla\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
