.TH "C:/Users/korye/source/repos/csla/Source/Csla/Security/NoAccessBehavior.cs" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/korye/source/repos/csla/Source/Csla/Security/NoAccessBehavior.cs
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBCsla\fP"
.br
.ti -1c
.RI "namespace \fBCsla\&.Security\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum class \fBCsla\&.Security\&.NoAccessBehavior\fP { \fBCsla\&.Security\&.SuppressException\fP, \fBCsla\&.Security\&.ThrowException\fP }"
.br
.RI "Options available for handling no access to a property due to authorization rules\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
