.TH "C:/Users/korye/source/repos/csla/Source/Csla.AspNetCore.Shared/RazorPages/PageModel.cs" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/korye/source/repos/csla/Source/Csla.AspNetCore.Shared/RazorPages/PageModel.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCsla\&.AspNetCore\&.RazorPages\&.PageModel< T >\fP"
.br
.RI "Custom \fBPageModel\fP for CSLA \&.NET "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBCsla\fP"
.br
.ti -1c
.RI "namespace \fBCsla\&.AspNetCore\fP"
.br
.ti -1c
.RI "namespace \fBCsla\&.AspNetCore\&.RazorPages\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
