.TH "ProjectTracker.Library.ResourceList" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ProjectTracker.Library.ResourceList
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.ReadOnlyListBase< ResourceList, ResourceInfo >\fP\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBResourceList\fP \fBEmptyList\fP ()"
.br
.ti -1c
.RI "static \fBResourceList\fP \fBGetResourceList\fP ()"
.br
.in -1c
.SS "Static Protected Member Functions"

.in +1c
.ti -1c
.RI "static void \fBAddObjectAuthorizationRules\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 9 of file ResourceList\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "static void ProjectTracker\&.Library\&.ResourceList\&.AddObjectAuthorizationRules ()\fC [static]\fP, \fC [protected]\fP"

.PP
Definition at line 27 of file ResourceList\&.cs\&.
.SS "static \fBResourceList\fP ProjectTracker\&.Library\&.ResourceList\&.EmptyList ()\fC [static]\fP"

.PP
Definition at line 13 of file ResourceList\&.cs\&.
.SS "static \fBResourceList\fP ProjectTracker\&.Library\&.ResourceList\&.GetResourceList ()\fC [static]\fP"

.PP
Definition at line 18 of file ResourceList\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
