.TH "ProjectTracker.Library.ResourceInfo" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ProjectTracker.Library.ResourceInfo
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCsla\&.Validation\&.ReadOnlyBase< ResourceInfo >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override string \fBToString\fP ()"
.br
.ti -1c
.RI "\fBResourceInfo\fP ()"
.br
.in -1c
.SS "Static Protected Member Functions"

.in +1c
.ti -1c
.RI "static void \fBAddObjectAuthorizationRules\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBId\fP\fC [get]\fP"
.br
.ti -1c
.RI "string \fBName\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 8 of file ResourceInfo\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ProjectTracker\&.Library\&.ResourceInfo\&.ResourceInfo ()"

.PP
Definition at line 39 of file ResourceInfo\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "static void ProjectTracker\&.Library\&.ResourceInfo\&.AddObjectAuthorizationRules ()\fC [static]\fP, \fC [protected]\fP"

.PP
Definition at line 33 of file ResourceInfo\&.cs\&.
.SS "override string ProjectTracker\&.Library\&.ResourceInfo\&.ToString ()"

.PP
Definition at line 22 of file ResourceInfo\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "int ProjectTracker\&.Library\&.ResourceInfo\&.Id\fC [get]\fP"

.PP
Definition at line 11 of file ResourceInfo\&.cs\&.
.SS "string ProjectTracker\&.Library\&.ResourceInfo\&.Name\fC [get]\fP"

.PP
Definition at line 17 of file ResourceInfo\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
