.TH "C:/Users/korye/source/repos/csla/Source/Csla/Core/FieldManager/PropertyInfoManager.cs" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/korye/source/repos/csla/Source/Csla/Core/FieldManager/PropertyInfoManager.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCsla\&.Core\&.FieldManager\&.PropertyComparer\fP"
.br
.RI "Compare to \fBPropertyInfo\fP x with y for sorting "
.ti -1c
.RI "class \fBCsla\&.Core\&.FieldManager\&.PropertyInfoManager\fP"
.br
.RI "Manages the \fBPropertyInfo\fP data for business object types\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBCsla\fP"
.br
.ti -1c
.RI "namespace \fBCsla\&.Core\fP"
.br
.ti -1c
.RI "namespace \fBCsla\&.Core\&.FieldManager\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
