.TH "ReadOnlyListTestsLocalAndRemote.cs" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ReadOnlyListTestsLocalAndRemote.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBcslalighttest\&.Stereotypes\&.ReadOnlyListTestsLocalAndRemote\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBcslalighttest\fP"
.br
.ti -1c
.RI "namespace \fBcslalighttest\&.Stereotypes\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
