.TH "RelationshipTypes.cs" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RelationshipTypes.cs
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBCsla\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum class \fBCsla\&.RelationshipTypes\fP { \fBCsla\&.None\fP = 0x0, \fBCsla\&.Child\fP =0x1, \fBCsla\&.LazyLoad\fP =0x2, \fBCsla\&.PrivateField\fP =0x4 }"
.br
.RI "List of valid relationship types between a parent object and another object through a managed property\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
