.TH "C:/Users/korye/source/repos/csla/Source/csla.netcore.test/DataPortal/RoutingTagTests.cs" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/korye/source/repos/csla/Source/csla.netcore.test/DataPortal/RoutingTagTests.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBcsla\&.netcore\&.test\&.DataPortal\&.RoutingTagTests\fP"
.br
.ti -1c
.RI "class \fBcsla\&.netcore\&.test\&.DataPortal\&.RoutingTest\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBcsla\fP"
.br
.ti -1c
.RI "namespace \fBcsla\&.netcore\fP"
.br
.ti -1c
.RI "namespace \fBcsla\&.netcore\&.test\fP"
.br
.ti -1c
.RI "namespace \fBcsla\&.netcore\&.test\&.DataPortal\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
