.TH "C:/Users/korye/source/repos/csla/Source/Csla.test/ValidationRules/RuleBaseClassesRoot.cs" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/korye/source/repos/csla/Source/Csla.test/ValidationRules/RuleBaseClassesRoot.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCsla\&.Test\&.ValidationRules\&.RuleBaseClassesRoot\fP"
.br
.ti -1c
.RI "class \fBCsla\&.Test\&.ValidationRules\&.CalcSum\fP"
.br
.RI "\fBCalcSum\fP rule will set primary property to the sum of all\&. "
.ti -1c
.RI "class \fBCsla\&.Test\&.ValidationRules\&.ValidateRootObject\fP"
.br
.ti -1c
.RI "class \fBCsla\&.Test\&.ValidationRules\&.LessThan\fP"
.br
.RI "Implements a rule to compare 2 property values and make sure property1 is less than property2 "
.ti -1c
.RI "class \fBCsla\&.Test\&.ValidationRules\&.LookupCustomer\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBCsla\fP"
.br
.ti -1c
.RI "namespace \fBCsla\&.Test\fP"
.br
.ti -1c
.RI "namespace \fBCsla\&.Test\&.ValidationRules\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
