.TH "RuleUri.cs" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RuleUri.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCsla\&.Rules\&.RuleUri\fP"
.br
.RI "Parses a rule:// URI to provide easy access to the parts of the URI\&. "
.ti -1c
.RI "class \fBCsla\&.Rules\&.UriExtensions\fP"
.br
.RI "Extension methods for System\&.Uri\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBCsla\fP"
.br
.ti -1c
.RI "namespace \fBCsla\&.Rules\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
