.TH "C:/Users/korye/source/repos/csla/Source/Csla.Validation.Shared/RuleExtensions.cs" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/korye/source/repos/csla/Source/Csla.Validation.Shared/RuleExtensions.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCsla\&.Validation\&.RuleExtensions\fP"
.br
.RI "Helper class for wrapping old style (\fBCsla\fP 3\&.8x and earlier) rules with a lambda rule in \fBCsla\fP 4\&.x to simplify migration of older style apps\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBCsla\fP"
.br
.ti -1c
.RI "namespace \fBCsla\&.Validation\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "delegate bool \fBCsla\&.Validation\&.RuleHandler\fP (object target, RuleArgs e)"
.br
.RI "The delegate definition for CSLA 3\&.8 rule handler "
.ti -1c
.RI "delegate bool \fBCsla\&.Validation\&.RuleHandler< T, R >\fP (T target, R e)"
.br
.RI "The delegate definition for CSLA 3\&.8 generic rule handler "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
