.TH "RuleSeverity.cs" 3 "Thu Jul 22 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RuleSeverity.cs
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBCsla\fP"
.br
.ti -1c
.RI "namespace \fBCsla\&.Rules\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum class \fBCsla\&.Rules\&.RuleSeverity\fP { \fBCsla\&.Rules\&.Error\fP, \fBCsla\&.Rules\&.Warning\fP, \fBCsla\&.Rules\&.Information\fP, \fBCsla\&.Rules\&.Success\fP }"
.br
.RI "Values for validation rule severities\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
