.TH "SerializationInfo.cs" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SerializationInfo.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCsla\&.Serialization\&.Mobile\&.SerializationInfo\fP"
.br
.RI "Object containing the serialization data for a specific object\&. "
.ti -1c
.RI "class \fBCsla\&.Serialization\&.Mobile\&.SerializationInfo\&.FieldData\fP"
.br
.RI "Object that contains information about a single field\&. "
.ti -1c
.RI "class \fBCsla\&.Serialization\&.Mobile\&.SerializationInfo\&.ChildData\fP"
.br
.RI "Object that contains information about a single child reference\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBCsla\fP"
.br
.ti -1c
.RI "namespace \fBCsla\&.Serialization\fP"
.br
.ti -1c
.RI "namespace \fBCsla\&.Serialization\&.Mobile\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
