.TH "C:/Users/korye/source/repos/csla/Source/csla.netcore.test/DataPortal/ServiceProviderMethodCallerTests.cs" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/korye/source/repos/csla/Source/csla.netcore.test/DataPortal/ServiceProviderMethodCallerTests.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCsla\&.Test\&.DataPortal\&.ServiceProviderMethodCallerTests\fP"
.br
.ti -1c
.RI "class \fBCsla\&.Test\&.DataPortal\&.OldStyleNoOverride\fP"
.br
.ti -1c
.RI "class \fBCsla\&.Test\&.DataPortal\&.PrivateMethodBase< T >\fP"
.br
.ti -1c
.RI "class \fBCsla\&.Test\&.DataPortal\&.PrivateMethod\fP"
.br
.ti -1c
.RI "class \fBCsla\&.Test\&.DataPortal\&.OldStyleCreate\fP"
.br
.ti -1c
.RI "class \fBCsla\&.Test\&.DataPortal\&.OldStyleCriteria\fP"
.br
.ti -1c
.RI "class \fBCsla\&.Test\&.DataPortal\&.OldStyleCriteriaBase\fP"
.br
.ti -1c
.RI "interface \fBCsla\&.Test\&.DataPortal\&.ICriteria\fP"
.br
.ti -1c
.RI "class \fBCsla\&.Test\&.DataPortal\&.MyCriteria\fP"
.br
.ti -1c
.RI "class \fBCsla\&.Test\&.DataPortal\&.InterfaceCriteria\fP"
.br
.ti -1c
.RI "class \fBCsla\&.Test\&.DataPortal\&.SimpleNoCriteriaCreate\fP"
.br
.ti -1c
.RI "class \fBCsla\&.Test\&.DataPortal\&.SimpleCriteriaCreate\fP"
.br
.ti -1c
.RI "class \fBCsla\&.Test\&.DataPortal\&.ObjectCriteriaCreate\fP"
.br
.ti -1c
.RI "class \fBCsla\&.Test\&.DataPortal\&.ObjectCriteriaCreateSubtype\fP"
.br
.ti -1c
.RI "class \fBCsla\&.Test\&.DataPortal\&.AmbiguousNoCriteriaCreate\fP"
.br
.ti -1c
.RI "class \fBCsla\&.Test\&.DataPortal\&.CriteriaCreateWithDI\fP"
.br
.ti -1c
.RI "class \fBCsla\&.Test\&.DataPortal\&.MultipleCriteriaCreateWithDI\fP"
.br
.ti -1c
.RI "class \fBCsla\&.Test\&.DataPortal\&.CriteriaCreateWithMultipleDI\fP"
.br
.ti -1c
.RI "class \fBCsla\&.Test\&.DataPortal\&.CriteriaCreateWithMultipleAmbiguousDI\fP"
.br
.ti -1c
.RI "class \fBCsla\&.Test\&.DataPortal\&.MultipleCriteriaCreateWithDIInterleaved\fP"
.br
.ti -1c
.RI "class \fBCsla\&.Test\&.DataPortal\&.BasicChild\fP"
.br
.ti -1c
.RI "class \fBCsla\&.Test\&.DataPortal\&.ParamsChild\fP"
.br
.ti -1c
.RI "class \fBCsla\&.Test\&.DataPortal\&.ModernChild\fP"
.br
.ti -1c
.RI "class \fBCsla\&.Test\&.DataPortal\&.NullableCriteria\fP"
.br
.ti -1c
.RI "class \fBCsla\&.Test\&.DataPortal\&.MultipleOverlappingCriteria\fP"
.br
.ti -1c
.RI "class \fBCsla\&.Test\&.DataPortal\&.Issue2109List\fP"
.br
.ti -1c
.RI "class \fBCsla\&.Test\&.DataPortal\&.Issue2109\fP"
.br
.ti -1c
.RI "interface \fBCsla\&.Test\&.DataPortal\&.ICriteriaBase\fP"
.br
.ti -1c
.RI "class \fBCsla\&.Test\&.DataPortal\&.My2109Criteria\fP"
.br
.ti -1c
.RI "class \fBCsla\&.Test\&.DataPortal\&.Issue2287List\fP"
.br
.ti -1c
.RI "class \fBCsla\&.Test\&.DataPortal\&.Issue2287ListBase\fP"
.br
.ti -1c
.RI "class \fBCsla\&.Test\&.DataPortal\&.Issue2287ListBase\&.Criteria\fP"
.br
.ti -1c
.RI "class \fBCsla\&.Test\&.DataPortal\&.Issue2287Edit\fP"
.br
.ti -1c
.RI "class \fBCsla\&.Test\&.DataPortal\&.Issue2287EditBase< T >\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBCsla\fP"
.br
.ti -1c
.RI "namespace \fBCsla\&.Test\fP"
.br
.ti -1c
.RI "namespace \fBCsla\&.Test\&.DataPortal\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
