.TH "Customer.cs" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Customer.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBcslalighttest\&.CslaDataProvider\&.Customer\fP"
.br
.ti -1c
.RI "class \fBcslalighttest\&.CslaDataProvider\&.Customer\&.FetchCriteria\fP"
.br
.ti -1c
.RI "class \fBcslalighttest\&.CslaDataProvider\&.CustomerWO_DP_XYZ\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBcslalighttest\fP"
.br
.ti -1c
.RI "namespace \fBcslalighttest\&.CslaDataProvider\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum class \fBcslalighttest\&.CslaDataProvider\&.CustomeType\fP { \fBcslalighttest\&.CslaDataProvider\&.Active\fP, \fBcslalighttest\&.CslaDataProvider\&.Inactive\fP }"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
