.TH "AuthorizeDataPortalTests.cs" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AuthorizeDataPortalTests.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCsla\&.Test\&.Silverlight\&.DataPortal\&.AuthorizeDataPortalTests\fP"
.br
.RI "Set of integration tests for IAUthorizeDataPortal Notice 2 roundtrips to the server in each test, first being Execute Command, and second being a \fBData\fP Portal call being tested\&. (Create, Fatch, Delete, and Update)\&. The reason for the first roundtrip is to set the appSetting in App\&.Config to value needed by the test "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBCsla\fP"
.br
.ti -1c
.RI "namespace \fBCsla\&.Test\fP"
.br
.ti -1c
.RI "namespace \fBCsla\&.Test\&.Silverlight\fP"
.br
.ti -1c
.RI "namespace \fBCsla\&.Test\&.Silverlight\&.DataPortal\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
