.TH "TaskLoader.cs" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TaskLoader.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCsla\&.Core\&.LoadManager\&.TaskDataPortalResult\fP"
.br
.ti -1c
.RI "class \fBCsla\&.Core\&.LoadManager\&.TaskLoader< T >\fP"
.br
.RI "Wraps async loading by Task>T< from DataPortal\&.XYZAsync methods "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBCsla\fP"
.br
.ti -1c
.RI "namespace \fBCsla\&.Core\fP"
.br
.ti -1c
.RI "namespace \fBCsla\&.Core\&.LoadManager\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
