.TH "TestClasses.cs" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TestClasses.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCsla\&.Test\&.GraphMerge\&.Foo\fP"
.br
.ti -1c
.RI "class \fBCsla\&.Test\&.GraphMerge\&.FooList\fP"
.br
.ti -1c
.RI "class \fBCsla\&.Test\&.GraphMerge\&.FooBindingList\fP"
.br
.ti -1c
.RI "class \fBCsla\&.Test\&.GraphMerge\&.FooDynamicList\fP"
.br
.ti -1c
.RI "class \fBCsla\&.Test\&.GraphMerge\&.FooDynamicBindingList\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBCsla\fP"
.br
.ti -1c
.RI "namespace \fBCsla\&.Test\fP"
.br
.ti -1c
.RI "namespace \fBCsla\&.Test\&.GraphMerge\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
