.TH "Utilities.cs" 3 "Wed Jul 21 2021" "Version 5.4.2" "CSLA.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Utilities.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCsla\&.Utilities\fP"
.br
.RI "Contains utility methods used by the CSLA \&.NET framework\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBCsla\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum class \fBCsla\&.CallType\fP { \fBCsla\&.Get\fP, \fBCsla\&.Let\fP, \fBCsla\&.Method\fP, \fBCsla\&.Set\fP }"
.br
.RI "Valid options for calling a property or method via the Csla\&.Utilities\&.CallByName method\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CSLA\&.NET from the source code\&.
