//HintName: TestApp.PersonEdit.DataPortalExtensions.g.cs
//<auto-generated/>
#nullable enable

namespace TestApp
{
  /// <summary>
  /// Strongly typed data portal extension methods for <see cref="global::TestApp.PersonEdit"/>.
  /// </summary>
  public static partial class PersonEditDataPortalExtensions
  {
    /// <summary>
    /// Invokes the <c>Create()</c> Create operation of <see cref="global::TestApp.PersonEdit"/>.
    /// </summary>
    public static global::System.Threading.Tasks.Task<global::TestApp.PersonEdit> PortalCreateAsync(this global::Csla.IDataPortal<global::TestApp.PersonEdit> portal)
    {
      if (portal is global::Csla.IDataPortalOperationInvoker<global::TestApp.PersonEdit> __invoker)
        return __invoker.CreateByOperationAsync("Create", false, global::System.Array.Empty<object?>());
      return portal.CreateAsync();
    }

    /// <summary>
    /// Invokes the <c>Create()</c> Create operation of <see cref="global::TestApp.PersonEdit"/>.
    /// </summary>
    public static global::TestApp.PersonEdit PortalCreate(this global::Csla.IDataPortal<global::TestApp.PersonEdit> portal)
    {
      if (portal is global::Csla.IDataPortalOperationInvoker<global::TestApp.PersonEdit> __invoker)
        return __invoker.CreateByOperation("Create", false, global::System.Array.Empty<object?>());
      return portal.Create();
    }

    /// <summary>
    /// Invokes the <c>Fetch(int)</c> Fetch operation of <see cref="global::TestApp.PersonEdit"/>.
    /// </summary>
    public static global::System.Threading.Tasks.Task<global::TestApp.PersonEdit> PortalFetchAsync(this global::Csla.IDataPortal<global::TestApp.PersonEdit> portal, int id)
    {
      if (portal is global::Csla.IDataPortalOperationInvoker<global::TestApp.PersonEdit> __invoker)
        return __invoker.FetchByOperationAsync("Fetch__Int32", false, new object?[] { id });
      return portal.FetchAsync(new object?[] { id });
    }

    /// <summary>
    /// Invokes the <c>Fetch(int)</c> Fetch operation of <see cref="global::TestApp.PersonEdit"/>.
    /// </summary>
    public static global::TestApp.PersonEdit PortalFetch(this global::Csla.IDataPortal<global::TestApp.PersonEdit> portal, int id)
    {
      if (portal is global::Csla.IDataPortalOperationInvoker<global::TestApp.PersonEdit> __invoker)
        return __invoker.FetchByOperation("Fetch__Int32", false, new object?[] { id });
      return portal.Fetch(new object?[] { id });
    }
  }
}
