//HintName: TestApp.PersonEdit.DataPortalExtensions.g.cs
//<auto-generated/>
#nullable enable

namespace TestApp
{
  /// <summary>
  /// Strongly typed data portal extension methods for <see cref="global::TestApp.PersonEdit"/>.
  /// </summary>
  public static partial class PersonEditDataPortalExtensions
  {
    /// <summary>
    /// Invokes the <c>GetById(int)</c> Fetch operation of <see cref="global::TestApp.PersonEdit"/>.
    /// </summary>
    public static global::System.Threading.Tasks.Task<global::TestApp.PersonEdit> GetByIdAsync(this global::Csla.IDataPortal<global::TestApp.PersonEdit> portal, int id)
    {
      if (portal is global::Csla.IDataPortalOperationInvoker<global::TestApp.PersonEdit> __invoker)
        return __invoker.FetchByOperationAsync("Fetch__Int32", false, new object?[] { id });
      return portal.FetchAsync(new object?[] { id });
    }

    /// <summary>
    /// Invokes the <c>GetById(int)</c> Fetch operation of <see cref="global::TestApp.PersonEdit"/>.
    /// </summary>
    public static global::TestApp.PersonEdit GetById(this global::Csla.IDataPortal<global::TestApp.PersonEdit> portal, int id)
    {
      if (portal is global::Csla.IDataPortalOperationInvoker<global::TestApp.PersonEdit> __invoker)
        return __invoker.FetchByOperation("Fetch__Int32", false, new object?[] { id });
      return portal.Fetch(new object?[] { id });
    }
  }
}
