//HintName: TestApp.LineItem.DataPortalExtensions.g.cs
//<auto-generated/>
#nullable enable

namespace TestApp
{
  /// <summary>
  /// Strongly typed data portal extension methods for <see cref="global::TestApp.LineItem"/>.
  /// </summary>
  public static partial class LineItemDataPortalExtensions
  {
    /// <summary>
    /// Invokes the <c>NewChild()</c> CreateChild operation of <see cref="global::TestApp.LineItem"/>.
    /// </summary>
    public static global::System.Threading.Tasks.Task<global::TestApp.LineItem> NewChildAsync(this global::Csla.IChildDataPortal<global::TestApp.LineItem> portal)
    {
      if (portal is global::Csla.IChildDataPortalOperationInvoker<global::TestApp.LineItem> __invoker)
        return __invoker.CreateChildByOperationAsync("CreateChild", global::System.Array.Empty<object?>());
      return portal.CreateChildAsync();
    }

    /// <summary>
    /// Invokes the <c>NewChild()</c> CreateChild operation of <see cref="global::TestApp.LineItem"/>.
    /// </summary>
    public static global::TestApp.LineItem NewChild(this global::Csla.IChildDataPortal<global::TestApp.LineItem> portal)
    {
      if (portal is global::Csla.IChildDataPortalOperationInvoker<global::TestApp.LineItem> __invoker)
        return __invoker.CreateChildByOperation("CreateChild", global::System.Array.Empty<object?>());
      return portal.CreateChild();
    }

    /// <summary>
    /// Invokes the <c>LoadChild(int, string)</c> FetchChild operation of <see cref="global::TestApp.LineItem"/>.
    /// </summary>
    public static global::System.Threading.Tasks.Task<global::TestApp.LineItem> LoadChildAsync(this global::Csla.IChildDataPortal<global::TestApp.LineItem> portal, int id, string name)
    {
      if (portal is global::Csla.IChildDataPortalOperationInvoker<global::TestApp.LineItem> __invoker)
        return __invoker.FetchChildByOperationAsync("FetchChild__Int32_String", new object?[] { id, name });
      return portal.FetchChildAsync(new object?[] { id, name });
    }

    /// <summary>
    /// Invokes the <c>LoadChild(int, string)</c> FetchChild operation of <see cref="global::TestApp.LineItem"/>.
    /// </summary>
    public static global::TestApp.LineItem LoadChild(this global::Csla.IChildDataPortal<global::TestApp.LineItem> portal, int id, string name)
    {
      if (portal is global::Csla.IChildDataPortalOperationInvoker<global::TestApp.LineItem> __invoker)
        return __invoker.FetchChildByOperation("FetchChild__Int32_String", new object?[] { id, name });
      return portal.FetchChild(new object?[] { id, name });
    }
  }
}
