//HintName: TestApp.PersonEdit.DataPortalExtensions.g.cs
//<auto-generated/>
#nullable enable

namespace TestApp
{
  /// <summary>
  /// Strongly typed data portal extension methods for <see cref="global::TestApp.PersonEdit"/>.
  /// </summary>
  public static partial class PersonEditDataPortalExtensions
  {
    /// <summary>
    /// Invokes the <c>GetByInternal(InternalCriteria)</c> Fetch operation of <see cref="global::TestApp.PersonEdit"/>.
    /// </summary>
    internal static global::System.Threading.Tasks.Task<global::TestApp.PersonEdit> GetByInternalAsync(this global::Csla.IDataPortal<global::TestApp.PersonEdit> portal, global::TestApp.InternalCriteria criteria)
    {
      if (portal is global::Csla.IDataPortalOperationInvoker<global::TestApp.PersonEdit> __invoker)
        return __invoker.FetchByOperationAsync("Fetch__InternalCriteria", false, new object?[] { criteria });
      return portal.FetchAsync(new object?[] { criteria });
    }

    /// <summary>
    /// Invokes the <c>GetByInternal(InternalCriteria)</c> Fetch operation of <see cref="global::TestApp.PersonEdit"/>.
    /// </summary>
    internal static global::TestApp.PersonEdit GetByInternal(this global::Csla.IDataPortal<global::TestApp.PersonEdit> portal, global::TestApp.InternalCriteria criteria)
    {
      if (portal is global::Csla.IDataPortalOperationInvoker<global::TestApp.PersonEdit> __invoker)
        return __invoker.FetchByOperation("Fetch__InternalCriteria", false, new object?[] { criteria });
      return portal.Fetch(new object?[] { criteria });
    }
  }
}
