//HintName: TestApp.PersonEdit.DataPortalExtensions.g.cs
//<auto-generated/>
#nullable enable

namespace TestApp
{
  /// <summary>
  /// Strongly typed data portal extension methods for <see cref="global::TestApp.PersonEdit"/>.
  /// </summary>
  public static partial class PersonEditDataPortalExtensions
  {
    /// <summary>
    /// Invokes the <c>GetById(int)</c> Fetch operation of <see cref="global::TestApp.PersonEdit"/>.
    /// </summary>
    public static global::System.Threading.Tasks.Task<global::TestApp.PersonEdit> GetByIdAsync(this global::Csla.IDataPortal<global::TestApp.PersonEdit> portal, int id)
    {
      if (portal is global::Csla.IDataPortalOperationInvoker<global::TestApp.PersonEdit> __invoker)
        return __invoker.FetchByOperationAsync("Fetch__Int32", false, new object?[] { id });
      return portal.FetchAsync(new object?[] { id });
    }

    /// <summary>
    /// Invokes the <c>Remove(int)</c> Delete operation of <see cref="global::TestApp.PersonEdit"/>.
    /// </summary>
    public static global::System.Threading.Tasks.Task RemoveAsync(this global::Csla.IDataPortal<global::TestApp.PersonEdit> portal, int id)
    {
      if (portal is global::Csla.IDataPortalOperationInvoker<global::TestApp.PersonEdit> __invoker)
        return __invoker.DeleteByOperationAsync("Delete__Int32", false, new object?[] { id });
      return portal.DeleteAsync(new object?[] { id });
    }

    /// <summary>
    /// Invokes the <c>LoadChild(int)</c> FetchChild operation of <see cref="global::TestApp.PersonEdit"/>.
    /// </summary>
    public static global::System.Threading.Tasks.Task<global::TestApp.PersonEdit> LoadChildAsync(this global::Csla.IChildDataPortal<global::TestApp.PersonEdit> portal, int id)
    {
      if (portal is global::Csla.IChildDataPortalOperationInvoker<global::TestApp.PersonEdit> __invoker)
        return __invoker.FetchChildByOperationAsync("FetchChild__Int32", new object?[] { id });
      return portal.FetchChildAsync(new object?[] { id });
    }
  }
}
