//HintName: BusinessBaseTestClass.g.cs
//<auto-generated/>
#pragma warning disable CSLA0007
#nullable enable
using System;
using Csla;

namespace Test;

public partial class BusinessBaseTestClass
{
	public static readonly PropertyInfo<string[]> NameProperty = RegisterProperty<string[]>(nameof(Name));
	public partial string[] Name
	{
		get => GetProperty(NameProperty)!;
		private set => SetProperty(NameProperty, value);
	}
}
#pragma warning restore CSLA0007
