//HintName: BusinessBaseTestClass.g.cs
//<auto-generated/>
#pragma warning disable CSLA0007
#nullable enable
using System;
using Csla;

namespace Test;

public partial class BusinessBaseTestClass
{
	public static readonly PropertyInfo<int?> AgeProperty = RegisterProperty<int?>(nameof(Age));
	public partial int? Age
	{
		get => GetProperty(AgeProperty);
		private set => SetProperty(AgeProperty, value);
	}
}
#pragma warning restore CSLA0007
